### ISSUE TITLE
Laravel With MongoDb Connection Issue

### ISSUE THREAD

**Issue by dhanabalanc** [jenssegers/laravel-mongodb#1001]
Hi,

I try to connect Laravel 5 with MongoDb., it shows below error msg.
**Class 'App\Http\Controllers\MongoClient' not found**

I have Installed   PHP 5.6 / Mongo 3.1 &  php Mongo Driver DLL version : 1.6.14.

But still same have the problem. 

**Second thing.** >composer require jenssegers/mongodb

If i try to run above command, it shows  below error msg.

  **Problem 1
    - jenssegers/mongodb v3.1.1 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.3, 1.0.0, 1.0.1, 1.0.2].
    - jenssegers/mongodb v3.1.0 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.3, 1.0.0, 1.0.1, 1.0.2].
    - jenssegers/mongodb v3.1.1 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.3, 1.0.0, 1.0.1, 1.0.2].
    - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for jenssegers/mongodb ^3.1 -> satisfiable by jenssegers/mongodb[v3.1.0, v3.1.1].**

Pls guide me to fix the issue.

Regards,
Dhanabalan.c

**Comment by kofispaceman** [comment]
Looks like you don't have the PHP mongodb extension installed on your system. You need the PHP mongodb driver in order for this package to work. Provide your system environment and I might be able to guide you.
