### ISSUE TITLE
Laravel 4.2 now supporting PHP 7

### ISSUE THREAD

**Issue by opb** [jenssegers/laravel-mongodb#1003]
Yesterday Laravel 4.2.20 was released which supports PHP7.

However, this package only supports 4.2 in the 2.0.x versions, and these versions don't support the "new" Mongo driver, which is required for PHP7.

So I guess the question would be, "is there any chance of a backport of the use of the newer driver to 2.0.x?"

Thanks!

**Comment by jonwhittlestone** [comment]
+1

**Comment by nodekra** [comment]
+1

**Comment by Ardakilic** [comment]
Another +1 for this.

I'm trying https://github.com/alcaeus/mongo-php-adapter/ but insert (save()) method throws error, so I'm not sure if it's compatible.

**Comment by 2128** [comment]
+1, please help @jenssegers #adore#

**Comment by Ardakilic** [comment]
@jenssegers Sorry to bump, but any plans for this ? Current Laravel 4's PHP7 compatibility would be already enough for my case.

**Comment by candasm** [comment]
+1

**Comment by smtaydemir** [comment]
+1

**Comment by Ardakilic** [comment]
I have created a PR for this: https://github.com/jenssegers/laravel-mongodb/pull/1197 , please check. The fix requires an additional package, and may break compatibility with PHP versions lower than 5.5. I can confirm I can run Laravel 4.2 with PHP7 smoothly with the patch in the PR.

**Comment by opb** [comment]
@Ardakilic awesome, thanks for your work on this. I hope it makes it in!

**Comment by Ardakilic** [comment]
@opb You're welcome! Actually, none of the code is my original work. I saw solutions in the other discussions, tried them, simply merged them and made a pull request. I hope it's considered 🙏
