### ISSUE TITLE
`firstOrCreate` fails because connection name is not saved

### ISSUE THREAD

**Issue by Blizzke** [jenssegers/laravel-mongodb#1006]
When the [`DatabaseManager::makeConnection()`](https://github.com/laravel/framework/blob/5.3/src/Illuminate/Database/DatabaseManager.php#L164) calls an extension callback-function, it passes the connection name as the second argument. 

It is apparently expected that you keep this name in your config. 
All the `firstOrXXXXXX` functions perform a call somewhat like this:

``` PHP
$instance = $this->model->newInstance($attributes)->setConnection(
            $this->query->getConnection()->getName()
);
```

Since mongo connection does not keep the connection here (`getName()` by default returns `$this->getConfig('name')`), this will return `null`, causing the default connection to be used. So basically none of those functions work at this point.

The patch is as simple as:

`MongodbServiceProvider.php`:

``` PHP
$this->app->resolving('db', function ($db) {
   $db->extend('mongodb', function ($config, $name) {
      $config['name'] = $name;
      return new Connection($config);
   });
});
```

This is on Laravel 5.3
I haven't looked back how long this name argument is being specified, but I can imagine just giving it a default value of `null` would also make it work in case it isn't specified in an older version.

**Comment by herzcthu** [comment]
@Blizzke Should add to documentation.

**Comment by Blizzke** [comment]
Should add what to the documentation? This just is a bugfix imo, it's not new fuctionality
