### ISSUE TITLE
I just not running mongodb - [MongoDB\Driver\Exception\ConnectionTimeoutException]

### ISSUE THREAD

**Issue by francisrod01** [jenssegers/laravel-mongodb#1007]
Hy guys!

I'm not running mongodb with laravel.
The mongodb server not init automatically in server without `sudo` command.

``` bash
$ php artisan migrate

  [MongoDB\Driver\Exception\ConnectionTimeoutException]
  No suitable servers found (`serverselectiontryonce` set): [Failed connecting to '127.0.0.1:27017': Connection refused]
```

Can you help me to resolve it, please?

**Comment by sharkreader** [comment]
Follow the instructions at http://php.net/manual/en/mongodb.installation.php for the driver installation, and visit the Laravel Version Compatibility section at https://github.com/jenssegers/Laravel-MongoDB#schema to be sure your version of Laravel is compatible with the version of jenssegers/laravel-mongodb package you installed.
