### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by BlakeGardner** [jenssegers/laravel-mongodb#1009]
I noticed that there is no license attached to this library. May i suggest licensing it under the MIT license and dropping a `LICENSE.md` file in the repo with a copy?

https://opensource.org/licenses/MIT has a good copy.

This could have been a pull request but it is more appropriate for the original author to explicitly state the license under which the code is released.

**Comment by pi0** [comment]
@BlakeGardner Thanks for starting this topic, as a newbie to opensource community, it was always my question that when MIT almost allows anything to do without restrictions, so why it even matters including MIT or not ?

**Comment by BlakeGardner** [comment]
@pi0 It matters because some software developers work for companies with legal departments that have to do checks on any software component used for compliance reasons. If there is no license attached then adoption of the library would be impossible without clarification in writing.

[TL;DR Legal](https://tldrlegal.com/) is a good resource as well.
