### ISSUE TITLE
Issue in saving date as ISODate in mongoDB using laravel

### ISSUE THREAD

**Issue by imrannazirbhat** [jenssegers/laravel-mongodb#1015]
date is not getting saved as ISODate in mongodb, though looking at users table I can see the timestamp dates are being saved in correct format. But for some reason when I try to save date it gets save in the below format:

 **"date_departure" : {
        "date" : "2016-07-14 17:50:17.000000",
        "timezone_type" : 3,
        "timezone" : "UTC"
    }**

which actually should be in a format like **"date_departure" : ISODate("2016-07-13T06:43:12.998Z")**

Pls suggest a fix!

**Comment by mamiysr** [comment]
+1

**Comment by isnoor** [comment]
Assumption collection name is _Event_ .
use **Event->save()** not  **Event::insert($array)** .
Also add line "protected $dates = ['created_at', 'updated_at', 'datetime']" on model file

**Comment by matteo-mazzanti-ps** [comment]
`use_this_value = new \MongoDB\BSON\UTCDateTime($datetime_object);`
