### ISSUE TITLE
How to integrate with Larevel 5.3?

### ISSUE THREAD

**Issue by xparthx** [jenssegers/laravel-mongodb#1016]
Hello,

As per the documentation of this package, we need to extend its Eloquent class in each model like:

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
class User extends Eloquent {}

But User model provided by Laravel 5.3 already extends Authenticatable class and PHP doesn't supports multiple inheritance. So what is the solution here?
 
https://github.com/laravel/laravel/blob/master/app/User.php

I would prefer a solution in which User model provided by Laravel 5.3 doesn't need to be modify much.

Thanks,
Parth vora

**Comment by guney** [comment]
Here is the solution I found: I implemented all of the interfaces that `Illuminate\Foundation\Auth\User` implements and used the same traits it uses. So I finally be able to extend `Jenssegers\Mongodb\Eloquent\Model` from my User model. I kinda bypassed `Auth\User` with this solution. This is the final version of User:

```php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Jenssegers\Mongodb\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract
{
    use Notifiable, Authenticatable, Authorizable, CanResetPassword;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'user_meta' => 'array',
    ];

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

```

**Comment by robsoncombr** [comment]
Can't we have this officially documented on package read me?

**Comment by robsoncombr** [comment]
My User.php model for Laravel 5.4, if anyone find something wrong or missing please let me know.

<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\HybridRelations;
use Jenssegers\Mongodb\Eloquent\SoftDeletes;

use Illuminate\Notifications\Notifiable;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;

use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Auth\Authenticatable as AuthenticableTrait;

use Illuminate\Contracts\Auth\CanResetPassword;
use Illuminate\Auth\Passwords\CanResetPassword as CanResetPasswordTrait;

class User extends Model implements Authenticatable, CanResetPassword
{
    use Notifiable, AuthenticableTrait, CanResetPasswordTrait;

    use HybridRelations, SoftDeletes;
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
