### ISSUE TITLE
id and date columns in embedded displaying {}

### ISSUE THREAD

**Issue by pankajadhyapak** [jenssegers/laravel-mongodb#1019]
_id and date (created_at and updated_at ) are displaying as blank json object in nested / embedded document .. example below 

same problem when using \DB::table root document's _id , dates are displaying {}

"_id": {},
"utm_content": "Brand",
"history": [
{
"_id": {},
"comments": "New",
"updated_at": {}
},

Any Solution for this ??

**Comment by ezsil** [comment]
I am having this same issue.

**Comment by ezsil** [comment]
Ok - the embedded model needs to be loaded (eager or lazy).

**Comment by robsoncombr** [comment]
same problem. how do we load? anyone?

**Comment by robsoncombr** [comment]
ok worked here: Model::with(['relationEmbedMany'])->find(<_id>)
