### ISSUE TITLE
Laravel 5.3.21 Issue - mongoDB to MySQL

### ISSUE THREAD

**Issue by Vittalks** [jenssegers/laravel-mongodb#1021]
When db connection change from mongoDB to MySQL getting this error
ErrorException in Builder.php line 101:
Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\MySqlConnection given, called in /Applications/MAMP/htdocs/testlaravel53/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php on line 536 and defined

please help me out

**Comment by Xplouder** [comment]
+1

**Comment by herzcthu** [comment]
Facing same error.

**Comment by sakalauskas** [comment]
Had the same problem, after upgrading to 5.3

Simple fix is just make sure in your db configuration you have name and driver as mongodb

e.g.
```
'mongodb' => [
                'name' => 'mongodb',
                'driver' => 'mongodb',
                'host' => 'localhost',
                'port' => 27017,
                'username' => '',
                'password' => '',
                'database' => env('DB_DATABASE', 'forge'),
            ],
```
