### ISSUE TITLE
Laravel 5.3, cannot query model but migration works

### ISSUE THREAD

**Issue by sasavranic** [jenssegers/laravel-mongodb#1034]
Hi,
Trying to implement MongoDB connection and I have one strange problem.
Everything is setup right in place (by manual on main page).

When I create a new model and new migration and run migrate cmd, new collection is created and I can confirm that with RoboMongo UI tool.

When I try to call Blog::all() on my controller I'm getting timeout page with "The connection was reset." ?!??

Interesting part is: migrations collection is updated regualarly :)

Here is my model:

```
<?php
namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Moloquent;

class Blog extends Moloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'blogs';

    protected $fillable = [
        'author',
        'name'
    ];
}
```
Here is my controller:

```
class ApiController extends Controller
{
    public function getBlogItems() {
        $blogs = Blog::all();
        return response()->json([ 'blogs' => $blogs]);
    }

}
```

MongoDB driver for PHP: 1.2.0alpha3
Laravel mongo library: 3.1.3

**Comment by kurtulik** [comment]
I have same problem. PHP 7 Laravel 5.3. Schema migration is ok or get data is failed no error only stop all code.

**Comment by mdd1704** [comment]
I have same problem too. HHVM 3.19.2 Laravel 5.4.
