### ISSUE TITLE
Drop Index in Migration Can't Find Index with Name

### ISSUE THREAD

**Issue by Oyelaking** [jenssegers/laravel-mongodb#1036]
I get this output when running the migration rollback command. But the up method works fine, and creates the index as expected. It's rolling back(dropping the index that's the issue).

<img width="637" alt="screen shot 2016-11-17 at 2 28 23 pm" src="https://cloud.githubusercontent.com/assets/858948/20391104/31485858-acd2-11e6-82c0-4af839dca94b.png">

This is the migration file content:

```
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateProductFacetsIndex extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::connection('productsdb')->table('products', function (Blueprint $collection) {
            $collection->index(
                [
                    "facets.name" => 1,
                    "facets.value" => 1,
                ],
                'facets_index',
                null,
                ['name' => 'facets_index']
            );
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::connection('productsdb')->table('products', function (Blueprint $collection) {
            $collection->dropIndex(['facets_index']);
        });
    }
}

```

I think this is a bug. Looking at the code, I see that '_1' is always appended to the index name when the dropIndex method is called.

**Comment by richardbenson** [comment]
Experiencing this too.

As far as I can tell, the issue comes from [this line](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Schema/Blueprint.php#L79). Since `fluent` will always return an array, the next block will be fallen into which appends the `_1` to the names of all columns.  This doesn't happen in the create index function, so you can't delete indexes you have created.

**Comment by ebrahimradi** [comment]
+1

**Comment by Dmitry-Kucher** [comment]
+1
