### ISSUE TITLE
Bulk write error thrown

### ISSUE THREAD

**Issue by theminer3746** [jenssegers/laravel-mongodb#1039]
When I use 
```
DB::collection('applicants')->insert([
    'citizen_id' => $citizen_id,
]);
```

`MongoDB\Driver\Exception\BulkWriteException: BulkWrite error` will be thrown. But strangely when I use that through artisan console, there's no error.

**Comment by maulikmmodi** [comment]
It will work great with bulk addition, this way, you just need to create on array and pass it to it.

    $temp = [
                [
                    'item'=> "envelopes"
                ],`enter code here`
                [
                    'item'=> "envelopesas"
                ],
                [
                    'item'=> "lala"
                ]
            ];
    
            $userData = DB::table('log')->raw( function ( $collection ) use ($temp) {
    
                return $collection->insertMany($temp);
            });
