### ISSUE TITLE
cache functionality don't work

### ISSUE THREAD

**Issue by manojnegee** [jenssegers/laravel-mongodb#1040]
unable to use remember method on a modal . I am using laravel 5.1 and laravel-mongodb 3.0.2.

**Comment by tuwid** [comment]
@manojnegii90 can you put more data ? Your full stack, some code snippets , what have you tried and so ?
People here cant read minds yet and fortunetelling wont work either..

**Comment by manojnegii90** [comment]
OK I will upload it soon.

On Nov 25, 2016 7:23 PM, "Artur D" <notifications@github.com> wrote:
>
> @manojnegii90 can you put more data ? Your full stack, some code snippets
, what have you tried and so ?

**Comment by Wu4m4n** [comment]
I have the same issue.

```
BadMethodCallException in Builder.php line 2450:
Call to undefined method Jenssegers\Mongodb\Query\Builder::remember()
```
the query 

`$query = ModelMongo::where('field',$product)->remember(10)->get();
`

if I dont use the remember function work great!
