### ISSUE TITLE
Increment not working

### ISSUE THREAD

**Issue by ming517** [jenssegers/laravel-mongodb#1041]
Hi, 

I have an issue that increment function is working.

```
{
    "_id" : "583567fe9a89202b051adecc",
   "name": "Testing",
    "integrations" : [ 
        {
            "name" : "integration 1",
            "numOfOrderSynced" : 0,
            "numOfProductSynced" : 4
        }, 
       {
            "name" : "integration 2",
            "numOfOrderSynced" : 0,
            "numOfProductSynced" : 0
        }
    ]
}
```

Im trying to increment the second subdocument of `integrations`

```
Channel::where("_id","583567fe9a89202b051adecc")
->increment("integrations.1.numOfOrderSynced")
```

However, the code above does not update the value. I was trying to dig out the increment function source code and found out this

```
public function increment($column, $amount = 1, array $extra = [], array $options = [])
    {
        $query = ['$inc' => [$column => $amount]];

        if (! empty($extra)) {
            $query['$set'] = $extra;
        }

        // Protect
        $this->where(function ($query) use ($column) {
            $query->where($column, 'exists', false);

            $query->orWhereNotNull($column);
        });

        return $this->performUpdate($query, $options);
    }
```

If I modify `$query->where($column, 'exists', false);`  to `$query->where($column, 'exists', true);`, my code is able to increment the value.

May I know is this a bug or the code I did was wrong?

Thanks

**Comment by m-vdv** [comment]
@jenssegers Any update on this? Thanks 👍

**Comment by notflip** [comment]
+1

**Comment by banqhsia** [comment]
I guess you've already figured out that solutions in these years? (maybe not?)

I have a same question that `->increment()` can't update nested object.  
Since I can update a nested object through the shell, I wrote a raw expression below: 

    $result = Article::raw(function($collection) use ($request){

        return $collection->findOneAndUpdate([
            '_id' => new \MongoDB\BSON\ObjectID ($request->_id),
        ], [ '$inc' => [ 'stats.likes' => 1 ] ] );

    });

Notice that you may have effect with `db.articles.update()`, but the `Mongo\Collection` doesn't have a method named `update()`, use `findOneAndUpdate`, or others instead. (`UpdateMany`, `UpdateOne`)

**Comment by F1NaL** [comment]
As i understand this behavior from https://github.com/jenssegers/laravel-mongodb/issues/97
Mb add flag for disable Protect ?
