### ISSUE TITLE
Eager Loading latest of relation not working

### ISSUE THREAD

**Issue by aglipanci** [jenssegers/laravel-mongodb#1042]
I have a scenario that I would like to Eager Load the model with a latest relation.

The main model:
```
class Server extends Eloquent
{
    public function data()
    {
        return $this->hasMany('App\Data');
    }

}
```

The relation model:
```
class Data extends Eloquent
{
    public function server()
    {
        return $this->belongsTo('App\Server');
    }
}

```

The eager loading:
```
 $servers = $user->servers()->with(['data' => function($query){
		    $query->latest()->first();
	    }])->get();
```

The output of data relation it limited to one for all servers, not one per server. The subquery is supposed to filter the relations per server not the whole output.

**Comment by stefanschindler** [comment]
@jenssegers 
sorry for the late reply but why did you close this issue? I just ran into the same problem, I think that is not solved yet, is it?
