### ISSUE TITLE
Paginate method - Memory Limit exceeded

### ISSUE THREAD

**Issue by yorci** [jenssegers/laravel-mongodb#1043]
im using paginate method and if i request after 45th pages i get that error, 

> Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.

but if i use manually "skip(x)->limit(x)->get();" methods, there is no problem, i dont get this, how can i solve pagitane method problem ? 

im using two seperated server and both has 1gb memory.

**Comment by yorci** [comment]
I realized that its about "orderBy" method, when i use orderBy its return me slower result and if i try to get after 45th pages, throw that error.

**Comment by yorci** [comment]
i resolve memory limit exceeded error with creating index to column of sorting, but its still give me slow response.

**Comment by ahren-condos-ca** [comment]
i have an index on the orderby column and am still getting this error. Working on a Table that has over 2 Million rows and is several GB's of data
