### ISSUE TITLE
count

### ISSUE THREAD

**Issue by ccorrea792** [jenssegers/laravel-mongodb#1049]
Hello,

Someone knows how to make a count using group by, I'm trying with something like this, but it returns me null

$test = DB::table('medicos')
            ->select(DB::raw('COUNT(*) as total'))
            ->groupBy('nacionalidad')
            ->get();
dd($test);

0 => array:3 [▼
    "_id" => array:1 [▶]
    "nacionalidad" => "Hondureña"
    "COUNT(*) as total" => null
 ]

**Comment by maulikmmodi** [comment]
I have same problem and i am not able to find any specific solution for this, it's always returns NULL on count

**Comment by maulikmmodi** [comment]
$nacionalidad = DB::table('medicos')->raw( function ( $collection ) {
            return $collection->aggregate([
                [
                    '$group' => [
                        '_id'    => array(
                            'nacionalidad' => '$nacionalidad'
                        ),
                        'count'  => ['$sum' => 1],
                    ]
                ],
            ]);
        });

It will return CURSOR pointer and u need to iterate that, u can look it in here https://docs.mongodb.com/v3.0/reference/glossary/#term-cursor or by following :

 $nacionalidad = json_decode(json_encode(iterator_to_array($nacionalidad)));
