### ISSUE TITLE
Cannot connect to mongodb from mongoApp/public in xampp

### ISSUE THREAD

**Issue by lehoang1312211** [jenssegers/laravel-mongodb#1051]
When I run `php artisan serve` so that ok but when I access from ../htdocs/myapp/public then I cannot open this page.
I got error: 
![capture](https://cloud.githubusercontent.com/assets/9296903/20875167/1ed7b778-baeb-11e6-831e-f104661e1ae7.PNG)

**Comment by 4ltugh** [comment]
+1

**Comment by lehoang1312211** [comment]
Thanks men! I'm done! This is work when run in x64 Server
