### ISSUE TITLE
Error installing on PHP7

### ISSUE THREAD

**Issue by anghelalexandra** [jenssegers/laravel-mongodb#1054]
Hi there,

I'm trying to install laravel-mongodb on a new Laravel 5.3 project and I'm getting the following error:

`PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/mongodb.so' - /usr/lib/php/20151012/mongodb.so: undefined symbol: php_json_serializable_ce in Unknown on line 0`

My PHP version is 7.0.9. Could this be related to the [mongo-php-library 1.1.0 release](https://github.com/mongodb/mongo-php-library/releases) from yesterday?

I have used laravel-mongodb in different projects and it was working just fine until today.

**Comment by anghelalexandra** [comment]
I temporarily solved the problem by using an older PECL mongodb version (1.1.9). There was an update to [version 1.2.0 on November 29th](https://pecl.php.net/package/mongodb), which is why the mongo-php-library also got updated.

I did the following:

`pecl uninstall mongodb`
`pecl install mongodb-1.1.9`

After this, 'composer update' worked.

**Comment by henryhoang92** [comment]
I have same problem:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/mongodb.so' - /usr/lib/php5/20121212/mongodb.so: undefined symbol: zval_used_for_init in Unknown on line 0
Using version ^3.1 for jenssegers/mongodb
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb v3.1.0 requires illuminate/support ^5.1 -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - jenssegers/mongodb v3.1.1 requires illuminate/support ^5.1 -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - jenssegers/mongodb v3.1.2 requires illuminate/support ^5.1 -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - jenssegers/mongodb v3.1.3 requires illuminate/support ^5.1 -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4].
    - illuminate/support v5.3.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.3.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.3.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.3.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.45 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.43 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.37 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.32 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.27 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.26 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.24 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.21 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.41 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.30 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.20 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.13 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - Installation request for jenssegers/mongodb ^3.1 -> satisfiable by jenssegers/mongodb[v3.1.0, v3.1.1, v3.1.2, v3.1.3].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/7.1/cli/php.ini
    - /etc/php/7.1/cli/conf.d/10-opcache.ini
    - /etc/php/7.1/cli/conf.d/10-pdo.ini
    - /etc/php/7.1/cli/conf.d/15-xml.ini
    - /etc/php/7.1/cli/conf.d/20-calendar.ini
    - /etc/php/7.1/cli/conf.d/20-ctype.ini
    - /etc/php/7.1/cli/conf.d/20-dom.ini
    - /etc/php/7.1/cli/conf.d/20-exif.ini
    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.1/cli/conf.d/20-ftp.ini
    - /etc/php/7.1/cli/conf.d/20-gettext.ini
    - /etc/php/7.1/cli/conf.d/20-iconv.ini
    - /etc/php/7.1/cli/conf.d/20-json.ini
    - /etc/php/7.1/cli/conf.d/20-phar.ini
    - /etc/php/7.1/cli/conf.d/20-posix.ini
    - /etc/php/7.1/cli/conf.d/20-readline.ini
    - /etc/php/7.1/cli/conf.d/20-shmop.ini
    - /etc/php/7.1/cli/conf.d/20-simplexml.ini
    - /etc/php/7.1/cli/conf.d/20-sockets.ini
    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.1/cli/conf.d/20-wddx.ini
    - /etc/php/7.1/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.1/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.1/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.
`

**Comment by orrd** [comment]
These issues aren't really related to Laravel MongoDB specifically.  They're just issues with enabling the PHP MongoDB extension in general.  You might find more info at http://php.net/manual/en/mongo.installation.php.

**Comment by peimn** [comment]
You are wrong @orrd ,
Laravel MongoDB should update himself for compatibility with latest PHP's MongoDB ext version

**Comment by orrd** [comment]
The first error is "PHP Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20160303/mongodb.so'".  I believe even just running "php" will generate that warning if that's the case, so that probably is happening long before any Laravel MongoDB even gets touched. 

It's because of an issue with the installation of the PHP Mongo extension.
