### ISSUE TITLE
Why use aggregation to paginate?

### ISSUE THREAD

**Issue by limen** [jenssegers/laravel-mongodb#1056]
Get rows from collection with pagination.
- Use aggregation
db.{dbname}.aggregate([{$sort:{_id:-1}}, {$skip:2}, {$limit:2}]);
- Not use aggregation
db.{dbname}.find().sort({"_id":-1}).skip(2).limit(2)
The returned data sets are all the same but the time consumption are very different. So why use aggregation to paginate?

**Comment by lvqingan** [comment]
with millions of records pagination took very long time ......

**Comment by san4io** [comment]
Yes, this is issue, with millions of records total aggregation is slow.

@jenssegers is there any plans to count totals with count instead of aggregation?

Ofcourse, it is possible to write custom paginator, but still I'm wondering do you have this issue in to-do list.

**Comment by srabouin** [comment]
Had this issue as well, had to leave pagination to left/right only otherwise it would time out on collection with lots of documents..

**Comment by judhizputra** [comment]
+1, this issue still accouring till now

**Comment by renegadeirfan** [comment]
mongodb is used for performance mainly, but using aggregate instead of find is killing the purpose.
+1
