### ISSUE TITLE
firstOrNew not working

### ISSUE THREAD

**Issue by leadsoft** [jenssegers/laravel-mongodb#1057]
Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\MySqlConnection given, called in /var/www/html/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php on line 503 and defined

When data is found, it's working, but this happens when is trying to insert. 
On older package versions, like 2.1.x,  is working.

Code example
`$data = Data::firstOrNew(['data_id' => 123, 'country_id' => 1]);
$data->text = 'Test';
$data->save();`

**Comment by wrzhao1987** [comment]
I'm facing the same problem just as what leadsoft said. The $connection property will be set to null where data is not found. In my environment the default connection is mysql, so an instance of Illuminate\Database\MySqlConnection is given. Hope the problem can be fixed.

**Comment by dhavaldav** [comment]
You can use **findOneAndUpdate** for it with **"upsert' => true"**

### Code example
```
Data::raw(function($collection) use($data_id, $country_id, $text) {
      $collection->findOneAndUpdate(
          ['data_id' => $data_id, 'country_id' => $country_id ], 
          [ '$set' => [ 'text' => $text ]],
          [
              'upsert' => true
          ]                
      );
  });
```

https://docs.mongodb.com/php-library/v1.7/reference/method/MongoDBCollection-findOneAndUpdate/index.html
