### ISSUE TITLE
Replication mongodb

### ISSUE THREAD

**Issue by hungtt57** [jenssegers/laravel-mongodb#1061]
Hello.
I need to connect replication mongodb.
I used code below:

   'social_mongodb' => [
            'driver'   => 'mongodb',
            'host'     => array('server1','server2','server3'),
            'port'     =>27017,
            'database' => 'database',
            'username' =>'user',
            'password' => 'pass',
            'options'  => ['replicaSet' => 'replicaSetName']
        ],
But laravel show message :
# No suitable servers found (`serverSelectionTryOnce` set) 
Help me!!

**Comment by gnrcampos** [comment]
It will be easier to help if you post the rest of the error message.
I, for instance, had a similar issue and what was missing was the 'database' => 'authentication db name' in the options array.

**Comment by imuneer** [comment]
setting 'replicaset' in the option worked for me and solve my issue getting the error message 'no master"
