### ISSUE TITLE
Nested BSONDocument and BSONArray

### ISSUE THREAD

**Issue by orangeShadow** [jenssegers/laravel-mongodb#1064]
Hi, please can anyone answer me? Only I have a problem with nested object element after aggregation ?  Maybe I don't know something ? 

When I have elements with nested object or array they have BSONDocument or BSONArray.

I have created[ pull request](https://github.com/jenssegers/laravel-mongodb/pull/1062), but  don't have a feedback, now I use my fork.

It would be great, if it was in original package.

**Comment by uriel2707** [comment]
## For Laravel 5.3 
**Aggregate method return BSONDocument**
	
Use function bsonSerialize convert to array

[https://github.com/mongodb/mongo-php-library/blob/master/src/Model/BSONArray.php](https://github.com/mongodb/mongo-php-library/blob/master/src/Model/BSONArray.php)

**Example for method Model**

```
$tags = self::raw(function($collection) use ($query) {
                    return $collection->aggregate($query);
                });
                
                
        foreach ($tags as $item) {
            
            if (isset($item->_id) && gettype($item->_id) == "object" && get_class($item->_id) == "MongoDB\Model\BSONArray") {

                $bsonSerialize = $item->_id->bsonSerialize();
               
                $item->_id = array_shift($bsonSerialize);
            }
        }
```

#### Its Works

**Comment by prashant-pokhriyal** [comment]
@uriel2707  It's not working.  Please help me out I got stuck for past 1 month.

**Comment by uriel2707** [comment]
@prashant-pokhriyal  Other option parse element
```
function formatTypeBson($item) {

$response= NULL;
        if (isset($item) && gettype($item) == "object" && (get_class($item) == "MongoDB\Model\BSONArray" || get_class($item) == "MongoDB\Model\BSONDocument")) {

            $bsonSerialize = $item->bsonSerialize();
            

            $response = array_values((array)$bsonSerialize);
        } else if (isset($item) && gettype($item) == "object" && get_class($item) == "MongoDB\BSON\UTCDateTime") {

            $response = $item->toDateTime();
        }

return $response;
    }
```
