### ISSUE TITLE
Allowing "readPreferenceTags" settings for Read Preference Modes

### ISSUE THREAD

**Issue by jaimeescano** [jenssegers/laravel-mongodb#1066]
Hi All,

I've been playing with Read Preference Modes and seems that readPreference works. But in my implementation, I'd like to prioritise my web server to communicate with specific Mongo instance.

Via PHP driver, this is done with the parameter readPreferenceTags. In this case you could add many "readPreferenceTags" on the URL. I've checked the laravel mongo implementations, but it seems that it won't use the following settings:

          'options' => [
                'database'      => env('DB_DATABASE_MONGOGRID', 'database'), 
                'replicaSet'    => env('REPLICASET_NAME_MONGO', 'database'),  
                'readPreference'=> env('READ_PREFERENCE_MONGO', 'nearest'),          // Preference Read option
                'readPreferenceTags'=> env('READ_PREFERENCE_TAG_MONGO', 'dc:source1'),        // Preference Read option
                 'readPreferenceTags'=> env('READ_PREFERENCE_TAG_MONGO', 'dc:source2')        // Preference Read option
            ]

In this case ... seems that the driver is only using the latest parameter "readPreferenceTags".

Is there any idea to support such scenario?

Details about readPreferenceTags: http://php.net/manual/en/mongo.readpreferences.php

Regards,
Jaime

**Comment by stevenmyhre** [comment]
FYI, looks like you can specify these by specifying the whole DSN url, using the ```dsn``` key on the options array

[see here](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Connection.php#L206)
