### ISSUE TITLE
Using 'laravel-mongodb' plugin in Laravel Notifications

### ISSUE THREAD

**Issue by murshid1988** [jenssegers/laravel-mongodb#1067]
Is there a possibility that we could achieve adding notification to the database via this plugin?
https://laravel.com/docs/5.3/notifications#database-notifications

**Comment by sontungx305** [comment]
Do you have a solution ?

**Comment by dmitov** [comment]
@jenssegers Is this going to be released anytime soon? I see it's merged to master, but we don't have an official version with this included.

**Comment by FarmerNeil** [comment]
@jenssegers as a follow up to @dmitov's comment, any idea when there will be an official release to support notifications?

**Comment by deviouspk** [comment]
@jenssegers could you please release an official version with this merged? Would really appreciate it :)

**Comment by deviouspk** [comment]
Actually after reviewing it i think it would be better extend the notifiable trait and to remove the hasDatabaseNotifications. The implementation would then look like this:

```
use Foundation\Models\MongoDatabaseNotification;

trait Notifiable
{
    use \Illuminate\Notifications\Notifiable {
        \Illuminate\Notifications\Notifiable::notifications as baseNotificationsMethod;
    }

    public function notifications()
    {
        if (config('database.default') === 'mongodb') {
            return $this->morphMany(MongoDatabaseNotification::class, 'notifiable')
                ->orderBy('created_at', 'desc');
        }
        return $this->baseNotificationsMethod();
    }
}
```

**Comment by vladshoob** [comment]
It is still not a part of jenssegers/laravel-mongodb for some strange reason.

Eventually sorted it out for temp solution. Should create custom class and traits as per pull request provided and use this custom Notifiable class in order for Laravel Notifications to work.

**Comment by dean-x** [comment]
@jenssegers could you please release an official version with this merged? Would really appreciate it :)

**Comment by Smolevich** [comment]
> @jenssegers could you please release an official version with this merged? Would really appreciate it :)

@dean-x what do you mean? Please don't reply in old closed issues

**Comment by dean-x** [comment]
> > @jenssegers could you please release an official version with this merged? Would really appreciate it :)
> 
> @dean-x what do you mean? Please don't reply in old closed issues

I am sorry, I am trying to store notification on db, and facing the same issue, it is not working in monogdb, I checked the suggested answer and it been merged but not being pushed i think?

**Comment by Smolevich** [comment]
If you have a problem, please create new issue or go to slack channel for this project
