### ISSUE TITLE
Return random record

### ISSUE THREAD

**Issue by gmarineau** [jenssegers/laravel-mongodb#107]
The following code return a error

 $articles = Article::orderBy(DB::raw('RAND()'))->get();

Illegal offset type in /Mongodb/Query/Builder.php Line 284

**Comment by mdhama** [comment]
if number of articles equals to random number than it will gives `null`. should use

`$article = Article::take(1)->skip(rand(0,$noOfArticles-1))->first();`

**Comment by ragazzid** [comment]
db.collection.aggregate([{$sample: {size: 5} }])

**Comment by laratutodotcom** [comment]
https://laratuto.com/how-to-get-random-records-in-laravel/ see this guys............
