### ISSUE TITLE
Call to a member function getDateFormat() on null when using with Cashier package

### ISSUE THREAD

**Issue by xparthx** [jenssegers/laravel-mongodb#1074]
Hello,

Error: Call to a member function getDateFormat() on null
I'm getting above error with this code:

```
$user = User::create($user_info);
$user->newSubscription('weekly', 'weekly')->create($data['stripeToken']);
```

Without second line everything works.

Any help would be appreciated.

Thanks

**Comment by uriel2707** [comment]
## For Laravel 5.3 
**Call to a member function getDateFormat() on nul**

Use another name of model **User.php**, example **UserMongo.php**

```php

<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Authenticatable;
//use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;


use App\ModeloBase as Base;


class UserMongo extends Base implements AuthenticatableContract, AuthorizableContract, CanResetPasswordContract {

    use Authenticatable,
        Authorizable,
        CanResetPassword;
    
    use Notifiable;

    /**
     * The database table used by the model.
     *
     * @var string
     */
//    protected $table = 'users';


    protected $collection = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [

        "name",
        "email",
        "password"
        
    ];
    protected $guarded = [
        
    ];


}
```

**Comment by xparthx** [comment]
@uriel2707 
Even if its work, I don't think that it is a good idea to edit that file. Lets say after 1 year Laravel 5.4 get released and I update the framework, that change will be gone and lead back to the same problem.

Looking forward to see some standard solution.

Anyway thanks.

**Comment by manojsb** [comment]
@xparthx its already out

**Comment by uriel2707** [comment]
## other solution
**Call to a member function getDateFormat() on null**
	
After installation laravel-mongodb run command for composer 
`php artisan clear-compiled` and `composer dump-autoload` => for composer global installation

#### Its Works
