### ISSUE TITLE
Insert a Document Specifying an _id Field

### ISSUE THREAD

**Issue by J-Ibarra** [jenssegers/laravel-mongodb#1085]
Hello, Please someone help mw,

I need insert document in my db for create Clients in laravel passport

I use this

```
use Laravel\Passport\Client;

Client::create([
      'user_id' => '',
      'name' => 'test client',
      'secret' => 'ajsnjkJHSnk128j3289',
      'redirect' => '',
      'password_client' => 1,
      'personal_access_client' => 0,
      'revoked' => 0,
  ]); 
```

this found fine, but I drop mi db for test and when i create the client agains this create a new _id, but i need the specific _id for my clients

i try use this

```
Client::create([
      '_id' =>  '1A',
      'user_id' => '',
      'name' => 'test client',
      'secret' => 'ajsnjkJHSnk128j3289',
      'redirect' => '',
      'password_client' => 1,
      'personal_access_client' => 0,
      'revoked' => 0,
  ]); 
```

and this

```
$c = Client::create([
      'user_id' => '',
      'name' => 'test client',
      'secret' => 'ajsnjkJHSnk128j3289',
      'redirect' => '',
      'password_client' => 1,
      'personal_access_client' => 0,
      'revoked' => 0,
  ]); 

$c->_id = '1A';
$c->save();
```

but no found, please help me
sorry for my english

reference:
[https://docs.mongodb.com/v3.2/reference/method/db.collection.insert/](https://docs.mongodb.com/v3.2/reference/method/db.collection.insert/)

**Comment by uriel2707** [comment]
You already tested with??
 `use MongoDB\BSON\ObjectID;`

   ` $objectID = new ObjectID();`

`'_id' =>  $objectID;`
### OR
`'_id' => (string) $objectID;`
