### ISSUE TITLE
Undefined property: Jenssegers\Mongodb\Relations\BelongsTo::$otherKey

### ISSUE THREAD

**Issue by vincentri** [jenssegers/laravel-mongodb#1087]
Hi, i already update laravel to 5.4 version 5 mintues ago and i got an error like this.

Undefined property: Jenssegers\Mongodb\Relations\BelongsTo::$otherKey

Can someone help me what happen here?

**Comment by artdarek** [comment]
Have the same error... 

$this->otherKey has to be renamed to $this->ownerKey in Jenssegers/Mongodb/Relations/BelongsTo.php

**Comment by vincentri** [comment]
yeah, I already solve it by change this. Hope Jenssegers update it soon
