### ISSUE TITLE
FatalThrowableError in Client.php line 81: Class 'MongoDB\Driver\Manager' not found

### ISSUE THREAD

**Issue by considine** [jenssegers/laravel-mongodb#1093]
I've installed the mongodb driver with PECL, and keep getting this error when attempting a simple query

**Comment by ShaneWilton** [comment]
❤️ 💚 💙 💛 💜

**Comment by considine** [comment]
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Profile extends Eloquent
{
    //
    // $manager = new MongoDB\Driver\Manager("mongodb://localhost:27017");
    protected $connection = 'mongodb';
    protected $collection = 'Profiles';
}

**Comment by MarceloBFreitas** [comment]
I was with this same error, which I did was as follows, I installed the latest version of the driver with threadsafe for the phpinfo () platform, in my case the 86x, after that the composer worked without problem
