### ISSUE TITLE
Issues with carbon date store/get

### ISSUE THREAD

**Issue by c0h1b4** [jenssegers/laravel-mongodb#1099]
Hello,

I have an object with an attribute of a date that shows as a Carbon object.

Contrato {#337 ▼
  #connection: "mongodb"
  #collection: "users"
  #dates: array:1 [▶]
  #contrato: null
  #primaryKey: "_id"
  #parentRelation: null
  #table: null
  #keyType: "int"
  #perPage: 15
  +incrementing: true
  +timestamps: true
  #attributes: array:13 [▼
    "name" => "John Doe"
    "date" => Carbon {#530 ▼
      +"date": "2012-02-01 00:00:00.000000"
      +"timezone_type": 3
      +"timezone": "UTC"
    } ...

When I save it to the mongodb, the date is converted to an array with the 3 k/values.

So, after this I can't work with the date anymore because it is always being read as a sub-array of my data.

Collection {#203 ▼
  #items: array:1 [▼
    0 => User {#202 ▼
      #connection: "mongodb"
      #collection: "users"
      #dates: array:1 [▼
        0 => "deleted_at"
      ]
      #contrato: null
      #primaryKey: "_id"
      #parentRelation: null
      #table: null
      #keyType: "int"
      #perPage: 15
      +incrementing: true
      +timestamps: true
      #attributes: array:13 [▼
        "_id" => ObjectID {#206 ▶}
        "name" => "John Doe"
        "date" => array:3 [▼
          "date" => "2012-02-01 00:00:00.000000"
          "timezone_type" => 3
          "timezone" => "UTC"
        ]...

How can I extract the date from my object after I read it from the database? Also I tried to do some filters on the date and it is not working...

Thanks,
Mauro W

**Comment by c0h1b4** [comment]
Ok, I found the issue.

On Laravel 5.4 the date cast now converts the date to a Carbon object. 
If you would like to preserve the time portion of the date, you should use the datetime cast.

At the Mongodb\Eloquent\Model in method "fromDateTime", on line 155 there is a request to the parent class to convert the date object and it is expecting a date class, but now Laravel is sending a Carbon class.

I believe that the casting should be done by the method itself and not rely on the partent class anymore.

I will try to fix it manually and submit a proposal fix there.

Thanks for your help.

**Comment by Smolevich** [comment]
@llioor, do you have same problem?
