### ISSUE TITLE
Laravel 5.4 BelongsToMany otherKey error

### ISSUE THREAD

**Issue by Svyatoy** [jenssegers/laravel-mongodb#1108]
After upgrading to laravel 5.4 got error:

[ErrorException]                                                           
Undefined property: Jenssegers\Mongodb\Relations\BelongsToMany::$otherKey.

As mentioned earlier about BelongsTo relation error "$this->otherKey" this problem is similar.
It can be fixed by replacing in Jenssegers\Mongodb\Relations\BelongsToMany "$this->otherKey" property to "$this->relatedKey"

**Comment by boparaiamrit** [comment]
@jenssegers Please Fix This, Or I will create a pull request.

**Comment by jenssegers** [comment]
PR's are definitely welcome!

**Comment by kamranahmedse** [comment]
@jenssegers man when is the next release expected? 👴

**Comment by jenssegers** [comment]
I think this is fixed in the master branch. Let me know if it works.
