### ISSUE TITLE
Cannot establish connection via Model due to invalid argument

### ISSUE THREAD

**Issue by JanisOzolins** [jenssegers/laravel-mongodb#1109]
So I've set up Laravel 5.4 and Mongo 3.4.1 database and using Jenssegers extension. I'm trying to test if the application can connect to database using the model by typing `php artisan tinker` and then querying `App\Patient::all()`. However, the system returns the following error, and I'm close to desperation because it refuses to work with MongoDB :

`TypeError: Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\MySqlConnection given, called in /Users/janisozolins/www/laravel/patients/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php on line 503`

When I checked the Model.php file on line 503, there is a function:

```php
protected function newBaseQueryBuilder()
    {
        $connection = $this->getConnection();

        return new QueryBuilder($connection, $connection->getPostProcessor());
    }
```

My model file looks like this: 

```php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Model;

class Patient extends Model {

    protected $connection = 'mongodb';
    protected $table = 'patient';

}
```

My connection to the database:

```php
'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE', 'testdb'),
            'username' => env('DB_USERNAME', 'testdb'),
            'password' => env('DB_PASSWORD', 'testdb'),
            'options' => array(
                'db' => 'testdb' // sets the authentication database required by mongo 3
            )
        ],
```

**Comment by acidjazz** [comment]
@JanisOzolins can you tell me what you found wrong? how you fixed this?

**Comment by JanisOzolins** [comment]
@acidjazz I had several issues I was dealing with while trying to establish the connection between Laravel and my MongoDB. But the two main faults were:

- wrong authentication database in your `config/database.php` file
- incorrectly extended User class

Currently, this is how my model class looks like:
```php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class User extends Eloquent {
    protected $collection = "users"; // specify the name of your collection within your Mongo database
}
```
