### ISSUE TITLE
Updating sub documents in Mongodb 3.4 & laravel 5.4

### ISSUE THREAD

**Issue by dasjet** [jenssegers/laravel-mongodb#1113]
How to convert this query?
```
db.leads.update(
    {user_id: 'user_id', 'leads.id': 'id'}, 
    {$pull: {"leads.$.data": { id: { $in: ['589d5012992df10c4c007e78',  '589d6155992df10c4c007e7d' ] } }}}
)
```
I tried to convert it like

```
Lead::raw(function ($collection) use ($user_id, $list_id) {
            return $collection->update(
                [ 'user_id', $user_id, 'leads.id', $list_id ],
                [ '$pull' => ["leads.$.data"=> [ 'id' => [ '$in' => ['589d5012992df10c4c007e78', '589d6155992df10c4c007e7d' ] ] ]]]
            );
        });
```

Return error: 
> call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Collection' does not have a method 'update'

**Comment by dasjet** [comment]
Done

```
$deleted = Lead::raw()->findOneAndUpdate(
            ['user_id' => $user_id, 'leads.id' => $list_id,
            ['$pull' => ["leads.$.data" => [ 'id' => [ '$in' => ['589d5012992df10c4c007e78', '589d6155992df10c4c007e7d' ] ] ]]]
        );
```

**Comment by joerecra** [comment]
Hey @dasjet How did you do to work with "$" operator??

I'm using this query: 

JobOfferResults::raw()->findOneAndUpdate(
            ['_id' => new \MongoDB\BSON\ObjectID ("5b7ebde0de1941044a16242d")],
            ['$set'=> ["results.$.test"=>"Joel Recra"]]
        );

And I got: "message": "The positional operator did not find the match needed from the query. Unexpanded update: results.$.test",

I'm using MongoDB 3.6.3
