### ISSUE TITLE
Reset Password not working Laravel 5.4.

### ISSUE THREAD

**Issue by Sb8691** [jenssegers/laravel-mongodb#1124]
Hi Guys,

I've tried to implement password reset, also with 'Jenssegers\Mongodb\Auth\PasswordResetServiceProvider::class' , but there are certain mistakes 

First: Jenssegers\Mongodb\Auth\PasswordBrokerManager::class is big mistake with missing parameter in function, should look like this : 

protected function createTokenRepository(array $config)
    {
        return new DatabaseTokenRepository(
            $this->app['db']->connection(),
            $this->app['hash'],  // this is missing
            $config['table'],
            $this->app['config']['app.key'],
            $config['expire']
        );
    }

And after that is problem with: Cannot use object of type MongoDB\BSON\UTCDateTime as array

It would be helpful to fix it,

Thanks

**Comment by dasjet** [comment]
> Same problem here.. Any solution?

**Comment by misterion** [comment]
Same problem here

**Comment by natanshalva** [comment]
Any solution?

**Comment by Jchang0210** [comment]
Same problem here

**Comment by kcleveland** [comment]
Same issue here as well. Any fix planned?

**Comment by Brutalbeard** [comment]
Test the above and working for me.

**Comment by Gil9091e10** [comment]
Try this solution but I still get the same error: Can not use object of type MongoDB \ BSON \ UTCDateTime as array

Someone else found some other solution for this error.

**Comment by mikekamornikov** [comment]
My dirty hack for reset issues:

Add the following to `Auth/ForgotPasswordController` and `Auth/ResetPasswordController` to make it work (requires php 7):

```php
/**
 * Get the broker to be used during password reset.
 *
 * TODO: remove this method once Jenssegers\Mongodb reset password issues are fixed
 *
 * @return \Illuminate\Contracts\Auth\PasswordBroker
 */
public function broker()
{
    return new class(app()) extends \Jenssegers\Mongodb\Auth\PasswordBrokerManager {

        protected function createTokenRepository(array $config)
        {
            $c = $this->app['db']->connection();
            $h = $this->app['hash'];
            $t = $config['table'];
            $k = $this->app['config']['app.key'];
            $e = $config['expire'];

            return new class($c, $h, $t, $k, $e) extends \Illuminate\Auth\Passwords\DatabaseTokenRepository {

                protected function getPayload($email, $token)
                {
                    return ['email' => $email, 'token' => $this->hasher->make($token), 'created_at' => new UTCDateTime(time() * 1000)];
                }

                protected function tokenExpired($token)
                {
                    // Convert UTCDateTime to a date string.
                    if ($token instanceof UTCDateTime) {
                        $date = $token->toDateTime();
                        $date->setTimezone(new DateTimeZone(date_default_timezone_get()));
                        $token = $date->format('Y-m-d H:i:s');
                    } elseif (is_array($token) and isset($token['date'])) {
                        $date = new DateTime($token['date'], new DateTimeZone(isset($token['timezone']) ? $token['timezone'] : 'UTC'));
                        $date->setTimezone(new DateTimeZone(date_default_timezone_get()));
                        $token = $date->format('Y-m-d H:i:s');
                    }

                    return parent::tokenExpired($token);
                }
            };
        }
    };
}
```

As you see there are 2 issues:
- token should be stored as a hash (`$this->hasher->make($token)`)
- `tokenExpired` gets $token which doesn't require `$token['created_at']` anymore

**Comment by bsormagec** [comment]
any update ?

**Comment by alsemany** [comment]
Thank you so much @mikekamornikov  this solution working very well 

it just need to add 

`use MongoDB\BSON\UTCDateTime;
`

also 
`new \DateTimeZone` 

if someone tried this solution and not worked , you just need to make a new reset request 
example.com/password/reset 
##then 
try the new token

**Comment by joerecra** [comment]
Hey @mikekamornikov, I made all you wrote, but doesn't work.

I'm getting this error: DateTime::__construct(): Failed to parse time string (1539211570000) at position 11 (0): Unexpected character

Help me please!

**Comment by mikekamornikov** [comment]
@joerecra I need more context. Where does this error come from (trace)?

**Comment by mcandylab** [comment]
In Config/App.php replace `Illuminate\Auth\Passwords\PasswordResetServiceProvider` on `Jenssegers\Mongodb\Auth\PasswordResetServiceProvider`
In App/Http/Controllers/Auth/ResetPasswordController.php add `use MongoDB\BSON\UTCDateTime; `

Timezone: Europe/Moscow
Laravel: 5.7.*
Jenssegers/mongodb: "^3.4"
