### ISSUE TITLE
I Can't use mongodb in laravel 5.4, please help me!

### ISSUE THREAD

**Issue by thachthen** [jenssegers/laravel-mongodb#1128]
Laravel 5.4 mongodb is not working with me!
My Model:

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
class Cities extends Eloquent
{
 
    protected $connection = 'jobtest';
    protected $collection = 'cities';
    protected $fillable = ['_id','title','name'];
    public $timestamps = false;
   
}

and in controller i call
public function abc(){

		$test = new Cities();
		$test->title = 'Ho chi minh';
		$test->name = 'ho-chi-minh';
		$test->save();

	}

in config/database.php i has add code:
` 'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('DB_HOST', 'localhost'),
            'port'     => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options'  => [
                'database' => 'admin' // sets the authentication database required by mongo 3
            ]
        ],`
But it not working with error 500.
Please helpe me!

Thank all!

**Comment by JanisOzolins** [comment]
This mongodb connection array needs to go inside the `config/database.php` file not `config/app.php`,  among other connection that can be found there.

Also, change `protected $connection = 'jobtest';` to `protected $connection = 'mongodb';`

Have you set your app to use mongodb in your `config/database.php` file? It should be like this: `'default' => env('DB_CONNECTION', 'mongodb'),`

And turn on your DEBUG mode in the `config/app.php` file for mode detailed error messages by changing this line: ```'debug' => env('APP_DEBUG', true),```
