### ISSUE TITLE
[QUESTION] Use eloquent with MongoDB

### ISSUE THREAD

**Issue by mprandot** [jenssegers/laravel-mongodb#1129]
Hello!!

I'm searching about MongoDB and Laravel, i will use it in one application thas was using Eloquent.

My question is : I can use Eloquent with laravel-mongodb driver? I can call a relationship with 2 models when one is in eloquent and another in mongodb?

Thanks!

**Comment by jenssegers** [comment]
Yes, see https://github.com/jenssegers/laravel-mongodb#mysql-relations
