### ISSUE TITLE
Call to a member function compileSelect() on null

### ISSUE THREAD

**Issue by d0hn** [jenssegers/laravel-mongodb#1133]
Upon following the guide from
[HERE](https://laravel.io/index.php/forum/09-20-2014-html-form-class-not-found-in-laravel-5/?page=2)
and running composer update I ran into an issue. No matter what I do I get compileSelect() on null.

I have followed steps from [HERE](https://github.com/jenssegers/laravel-mongodb/issues/901) and [HERE](https://github.com/jenssegers/laravel-mongodb/issues/1023) I can only get my system to work partially. I can login but that's it, everything else is broken.

All code from the guide mentioned earlier has been removed but I still can't revive my system.

**Comment by d0hn** [comment]
Managed to revert the changes, I think the laravelcollective must have corrupted my project in someway.

**Comment by msankar1991** [comment]
@d0hn : Getting same error after `composer update`. May I know how revert the last changes using composer.

**Comment by d0hn** [comment]
I had a backup of my composer.json file, and decent commit history so I deleted my project and cloned again.
However the issue you are facing is related to a null variable or object somewhere in your code. In my case it was to do with the Authentication, login and user details. Try removing bits of your code and you will find the bit responsible for the error.
