### ISSUE TITLE
PasswordBrokerManager.php has conflict with laravel 5.4

### ISSUE THREAD

**Issue by mahdiraad** [jenssegers/laravel-mongodb#1138]
```
protected function createTokenRepository(array $config)
    {
        return new DatabaseTokenRepository(
            $this->app['db']->connection(),
            $this->app['hash'], // Todo: I think you have to add this line for laravel 5.4
            $config['table'],
            $this->app['config']['app.key'],
            $config['expire']
        );
    }
```

**Comment by omidahn** [comment]
see #1164

**Comment by JuCarr** [comment]
It was not enough to fix it for me. Here is what I did:

Jenssegers\Mongodb\Auth\PasswordBrokerManager:

    protected function createTokenRepository(array $config)
    {
        return new DatabaseTokenRepository(
            $this->app['db']->connection(),
            $this->app['hash'],
            $config['table'],
            $this->app['config']['app.key'],
            $config['expire']
        );
    }

Jenssegers\Mongodb\Auth\DatabaseTokenRepository:

    protected function getPayload($email, $token)
    {
       // Hash token
        return ['email' => $email, 'token' => $this->hasher->make($token), 'created_at' => new UTCDateTime(time() * 1000)];
    }

    protected function tokenExpired($token)
    {
        // Added this first if
        if($token instanceof UTCDateTime) {

            $date = $token->toDateTime();
            $date->setTimezone(new DateTimeZone(date_default_timezone_get()));

            $createdAt = $date->format('Y-m-d H:i:s');

            return parent::tokenExpired($createdAt);
        }

        // Convert UTCDateTime to a date string.
        elseif ($token['created_at'] instanceof UTCDateTime) {

            $date = $token['created_at']->toDateTime();
            $date->setTimezone(new DateTimeZone(date_default_timezone_get()));
            $token['created_at'] = $date->format('Y-m-d H:i:s');

        } elseif (is_array($token['created_at']) and isset($token['created_at']['date'])) {

            $date = new DateTime($token['created_at']['date'], new DateTimeZone(isset($token['created_at']['timezone']) ? $token['created_at']['timezone'] : 'UTC'));
            $date->setTimezone(new DateTimeZone(date_default_timezone_get()));
            $token['created_at'] = $date->format('Y-m-d H:i:s');
        }


        return parent::tokenExpired($token);
    }
