### ISSUE TITLE
Avoid duplicated Queues

### ISSUE THREAD

**Issue by elfeffe** [jenssegers/laravel-mongodb#1139]
I'm thinking a way to avoid duplicated queues. May be you can do some upsert for each queue, if a queue exist with same function and same parameters, we skip.
It can even be an optional parameter.
The thing is that I can't find where you do the insert in mongo of each queue.
Do this already has the duplication setting? Or where do you make the insert, so I can change with an upsert?

**Comment by divine** [comment]
Hello,

This is has nothing to do with this library, please check laravel documentation on how to avoid duplicate queues.

Thanks.
