### ISSUE TITLE
firstOrFail() not implemented?

### ISSUE THREAD

**Issue by c0h1b4** [jenssegers/laravel-mongodb#1140]
Hello,

I just tried the firstOrFail() method and got

No query results for model [App\...].

I am using the Jenssegers\Mongodb\Eloquent\Model as Eloquent.

Thanks,
Mauro W

**Comment by rummykhan** [comment]
Are you sure you have record in your database ?

**Comment by benpoulson** [comment]
Can confirm Model::firstOrFail() is working fine for me.

`$p = \App\Product::where('item_id', '541511756092')->firstOrFail();`

**Comment by victorioustr** [comment]
I have that same problem. The problem occurs when you serialize and unserialize the queue job.

`Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\MODEL]. in /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:480
Stack trace:
#0 /vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(102): Illuminate\Database\Eloquent\Builder->firstOrFail()`

**Comment by Djuki** [comment]
When queues send models, and models have relations, queue will fail in `SerializesAndRestoresModelIdentifiers`

To solve this model need to load relations, and this method is missing in model:

```
    /**
     * Eager load relations on the model.
     *
     * This method is required to loads relations on serialize deserialize queues
     *
     * @param  array|string  $relations
     * @return $this
     */
    public function load($relations)
    {
        if (!empty($relations)) {
            foreach ($relations as $relation) {
                $this->{$relation};
            }
        }

        return $this;
    }
