### ISSUE TITLE
Unsupported driver [mongodb] unless provider added to app.php

### ISSUE THREAD

**Issue by vesper8** [jenssegers/laravel-mongodb#1143]
I already solved my problem but was wondering if you were able to share some insight on something.

In my projects I use a lot of custom packages in order to group dependencies together. These packages always include a service provider and in there I register the dependencies' own service providers.

So instead of adding Jenssegers\Mongodb\MongodbServiceProvider::class directly to app.php, I would add something like this

app.php
```
MyCustomPackages\CustomPackageName\Providers\CustomMongodbServiceProvider::class,
```

And in that provider I do 

```
    public function boot()
    {
        $this->app->register('Jenssegers\Mongodb\MongodbServiceProvider');
    }
```

Maybe that sounds redundant to you, but it works for me and many of these custom packages include many dependencies in their own composer.json and add all the aliases/providers/migrations/etc/etc in their custom service provider

This works 99% of the time, but sometimes, such as in the case of this package, it fails.

This package for some reason that I would like to understand explicitly requires that the Jenssegers\Mongodb\MongodbServiceProvider' be added in the app.php and it will return the error above if it is loaded as part of a package's service provider.

Could you explain why that is please?

Many thanks!

**Comment by divine** [comment]
Hello,

If you're using newer laravel versions which has `auto loading the packages` feature this is no longer a case.

Thanks.
