### ISSUE TITLE
Moloquent VS laravel-mongodb ( laravel passport )

### ISSUE THREAD

**Issue by deividaspetraitis** [jenssegers/laravel-mongodb#1144]
Hi,

Alright. I'm a little bit confused. I tried to google but with no luck. What is the difference between these two repos having in mind that both are maintained by jenssegers if I'm right?

I'm trying to use laravel passport with MongoDB. Moloquent ( https://github.com/moloquent/moloquent ): there is some provider for such purposes however in this repo there is nothing about it.

Thanks.

**Comment by jenssegers** [comment]
The moloquent repository you mentioned is not maintained by me.

**Comment by deividaspetraitis** [comment]
Ok, thanks for clarifying things up. Please feel free to close this issue since I was misled. In case anything about passport I will create new one.

**Comment by jenssegers** [comment]
Probably makes sense to add Passport support here as well :)

**Comment by deividaspetraitis** [comment]
Sure, I'm open for contribution just need some research. :)

**Comment by JoeyHoutenbos** [comment]
@jenssegers any update about the Passport support?

**Comment by deividaspetraitis** [comment]
@JoeyHoutenbos I believe there is no possible solution to integrate passport without modifying directly it's own files, since all models are extending elequent. I have forked passport repo and added configuration feature to be able set own models it worked like a charm and I'm using it on my projects without any problems. However my pull request to official repo was rejected. My fork: https://github.com/deividaspetraitis/passport

**Comment by JoeyHoutenbos** [comment]
@deividaspetraitis , this fork has an Service Provider which fixes the problems: https://moloquent.github.io/master/#passport

**Comment by jenssegers** [comment]
@deividaspetraitis Can you link me to your PR?

**Comment by deividaspetraitis** [comment]
@JoeyHoutenbos well, they just merged passports source with moloquent source since as I mentioned you can't integrate passport with MongoDB without modifying directly it's source.
@jenssegers please see: https://github.com/laravel/passport/pull/306

**Comment by JoeyHoutenbos** [comment]
@deividaspetraitis I see what you mean. Is there any reason not to solve this problem using the method provided by Moloquent?
@jenssegers Would be awesome to have Passport support as soon as possible, so maybe you can help us out?

**Comment by deividaspetraitis** [comment]
The main reason why I do not updated this issue is that changes must be made from passport side not from this package.
However in order to add default support of passport I think best way is to follow moloquent approach and include passport source to this package. However you will need to maintain two packages.

**Comment by deividaspetraitis** [comment]
@jenssegers what do you think? In case such approach would be considered I could merge my repo and create a pull request.

**Comment by Aragami23** [comment]
Any news about this?
Thanks for the hard work, loving laravel-mongodb so far, but now I want to implement passport without altering passport files :/

**Comment by azhard4int** [comment]
@deividaspetraitis @Aragami23  you can use this version of repository if you are using laravel 5.3 with v1.0 branch https://github.com/azhard4int/passport/tree/1.0/src

**Comment by deividaspetraitis** [comment]
@azhard4int  I would suggest update to laravel 5.4.. I've already fork version with models extending feature implemented here: https://github.com/deividaspetraitis/passport but thanks, maybe for others it will be useful!

**Comment by saman** [comment]
@deividaspetraitis would you tell me how use your fork? base on [composer document](https://getcomposer.org/doc/05-repositories.md#vcs), I couldn't use it. Thanks.

**Comment by deividaspetraitis** [comment]
@saman I would suggest to use it as a local package. I should notice that this package is not synchronized with latest repo at the moment but I will try to do that when have some free time.
