### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by hulkwan** [jenssegers/laravel-mongodb#1152]
The version of lumen is 5.1.x,  jenssegers is 3.1, when i updated. 

Problem 1
    - The requested package jenssegers/mongodb (installed at v3.1.3, required as ^3.2) is satisfiable by jenssegers/mongodb[v3.1.3] but these conflict with your requirements or minimum-stability.

the commond is   composer update vendor\jenssegers\

**Comment by Smolevich** [comment]
@hulkwan, this issue is actual?
