### ISSUE TITLE
MongoClient is deprecated

### ISSUE THREAD

**Issue by hulkwan** [jenssegers/laravel-mongodb#1155]
Warning

This extension that defines this class is deprecated. Instead, the MongoDB extension should be used. Alternatives to this class include:

    MongoDB\Driver\Manager

this is from php.net
so，how to upload？

**Comment by socialknowledge** [comment]
MongoClient is not available for PHP 7.  What are we supposed to do?

**Comment by divine** [comment]
Hello,

You could install new mongodb extenstion.

Sorry for late reply.
Thanks.
