### ISSUE TITLE
gridfs help

### ISSUE THREAD

**Issue by muhabutt** [jenssegers/laravel-mongodb#1161]
hi, i would like to know how to upload large files using this package..

**Comment by aconital** [comment]
@muhabutt I see you closed this issue. Do you mind sharing how you resolved this?

**Comment by jmikola** [comment]
> Do you mind sharing how you resolved this?

@aconital: I'm not the OP, but https://github.com/jenssegers/laravel-mongodb/issues/826#issuecomment-290362789 may be helpful for you.

**Comment by bisht2050** [comment]
GridFS is now supported! 
Follow the docs to learn how to use GridFS : https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/filesystems/
