### ISSUE TITLE
Denormalized reference Eloquent relationship

### ISSUE THREAD

**Issue by NoelDeMartin** [jenssegers/laravel-mongodb#1166]
I recently read a blog post by the mongo team talking about how to relate models in schema design. In part 2 of the series they talk about denormalized references: [Part 2: Two-way referencing and denormalization](https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-2?_ga=1.89737499.1461869878.1487685130)

Basically, to put an example, if you have a posts collection and an authors collection, you could have the following structure:

**posts**
`{
    id: ObjectId,
    title: string,
    body: string,
    author: {
        id: ObjectId,
        name: string
    }
}`

**authors**
`{
    id: ObjectId,
    name: string,
    email: string,
    password: string
}`

Notice how the posts collection has a reference to the author, but instead of being an `author_id` field, it has an embedded document with some data from the author.

Having this into account, I think it'd be nice to handle this with eloquent with a new relationship (since this isn't HasOne, because I don't want to query the authors collection everytime I read the author, but it isn't an EmbedsOne either, since in some occasion I may want to query the full author model).

@jenssegers I guess this issue should have an enhancement label but I cannot assign it myself. Besides the fact that this is a new feature and I understand there will be many other issues with higher priority, would you accept a PR on this in case I decide to do it myself? Does this make sense to you?

**Comment by NoelDeMartin** [comment]
@jenssegers Did you have a chance to read the issue? As I said, I may be able to implement it myself and create a PR but I won't proceed until you tell me if it makes sense.

**Comment by divine** [comment]
Hello,

Since we've planned to drop support for embedded documents, this is something custom that we're trying to avoid.

Thanks.
