### ISSUE TITLE
$appends not work in artisan

### ISSUE THREAD

**Issue by ihsanberahim** [jenssegers/laravel-mongodb#1168]
I'm using this package with Lumen 5.4. This package works nicely in my project. Just the `$appends` not work in 'artisan'. Anything i missed?

```
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class MyData extends Eloquent{
 protected $appends = ['field_one', 'field_two'];

 public function getFieldOneAttribute()
 {
  return 'field_one';
 }
 public function getFieldTwoAttribute()
 {
  return 'field_two';
 }
}
```

**Comment by ivangan2307** [comment]
Hi @ihsanberahim , did you manage to find the solution to this? I'm facing this issue and could not seems to find the solution anywhere. Thanks!

**Comment by ihsanberahim** [comment]
Actually, it works but you need to call `toArray`

It is not working
```
App\Models\Notification::first()
```

It is working
```
App\Models\Notification::first()->toArray()
```
