### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by nwesber** [jenssegers/laravel-mongodb#1169]
I'm saving an object date in ISO format which works fine but when I retrieve it in my controller it changes to UTC with 01-01-1970 in milliseconds. I don't know what to do. Thank you so much.

**Comment by flangofas** [comment]
@nwesber Mongo requires dates to be stored as ```MongoDB\BSON\UTCDateTime``` and the package does this for you ;)

When you have UTCDateTime object in your hand, you can do the following to get a DateTime object
```
$datetime = $utcdatetime->toDateTime();
```
see more [here](http://php.net/manual/en/mongodb-bson-utcdatetime.todatetime.php)

**Comment by nwesber** [comment]
thank you so much

**Comment by nwesber** [comment]
My problem is that when I save an object via eloquent it is saved correctly
![mongodb](https://cloud.githubusercontent.com/assets/11203053/24709056/4b6113ec-1a4b-11e7-9acd-3c6b42cee98d.PNG)

but when I grab this document in my controller it returns it like this
![output](https://cloud.githubusercontent.com/assets/11203053/24709093/6c73b198-1a4b-11e7-8e6a-39a7b6235036.PNG)

this is how i convert it in my blade file
![blade](https://cloud.githubusercontent.com/assets/11203053/24709216/c21c9bc8-1a4b-11e7-8b39-d8eef7979cdd.PNG)

and this is the error
![error](https://cloud.githubusercontent.com/assets/11203053/24709226/c9f869a8-1a4b-11e7-99b9-52aa70a84b88.PNG)

I don't understand the error

**Comment by nwesber** [comment]
thank you so much
