### ISSUE TITLE
php v7.0 or phpv5.6 and with what stable release for Windows?

### ISSUE THREAD

**Issue by jamesstar89** [jenssegers/laravel-mongodb#1171]
Hello,

trying for past few nights now to get Laravel MongoDB up and running and failing, I've considered now must be to do with having all versions compatible with each other.

PHP 7.0 and release 3.2 is failing for me with latest MongoDB driver.

So what is the recommended php version and release version?

Thank you.

**Comment by jkpatil211** [comment]
@puffstream This happened with me also. Please provide solution if you find it

**Comment by divine** [comment]
Hello,

This is has nothing to do with this library, it's an issue with mongodb extension. Please check it first of all.

Thans.
