### ISSUE TITLE
Difference with Moloquent

### ISSUE THREAD

**Issue by alagaccia** [jenssegers/laravel-mongodb#1180]
What is the difference between this two repos?
Which one is best to use?

- https://github.com/jenssegers/laravel-mongodb
- https://github.com/moloquent/moloquent

**Comment by MatthewDrouin** [comment]
This is a very good question. It seems like the moloquent team is trying to determine how to get changes made in laravel-mongodb into moloquent. The moloquent team seems more responsive and accepts PRs faster so it's really a catch 22 unfortunately.

**Comment by microwavekonijn** [comment]
This one. Read answer from markszymik.
#1192

**Comment by divine** [comment]
Hello guys,

This library is being updated and any issues/prs are taken care instantly.

Moloquent hasn't been updated since 2017.

Sorry for late reply.
Thanks.
