### ISSUE TITLE
Create dynamic databases

### ISSUE THREAD

**Issue by Nilesh4991** [jenssegers/laravel-mongodb#1188]
Hello , 

I want to create dynamic databases , till now i tried following in my model: 

DB::getConnection()->statement('CREATE DATABASE :schema', array('schema' => $dbname))

getting following error : 

call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getConnection'

**Comment by davorminchorov** [comment]
There's no such thing as "database" in MongoDB. Documents are the closest thing to databases and collections are the closest to tables.

**Comment by trq** [comment]
There is such a thing as a database in Mongo. Databases contain collections, and collections contain documents.

This particular package can only connect to one at a time though as far as I can tell.

What exactly is the use case for creating databases dynamically though?

**Comment by 775397252** [comment]
i also hava same question?i want to create a datebase by code
