### ISSUE TITLE
With so many open issues. Is this even actively maintained repo?

### ISSUE THREAD

**Issue by dannysood** [jenssegers/laravel-mongodb#1189]
@jenssegers @pi0 Want to use it for a new project but the sheer number of open issues and very little interaction on any of them concerns me. Is it being actively maintained?

**Comment by pi0** [comment]
@dannysood  Both [jenssegers/laravel-mongodb](https://github.com/jenssegers/laravel-mongodb) and [moloquent](https://moloquent.github.io/master/) are active projects and are being used by hundreds of production projects. (at least we at @fandogh have more than 3 active projects using moloquent, and even zarinpal (a big financial and online payment service in iran) i think are using too)
For big projects like this, it is actually normal thing to have many open issues, but should not be considered as unstable ;)

**Comment by dannysood** [comment]
@pi0 Thanks for the response :) Ill close this then. ;)
