### ISSUE TITLE
[Question] Should I use moloquent/moloquent or this repository ?

### ISSUE THREAD

**Issue by CaporalDead** [jenssegers/laravel-mongodb#1192]
Hi !

I'm looking for an ODM to work with Laravel as a long term solution in my company and I found your package and moloquent/moloquent and I'm a little bit confused because : 

* Your package have way more downloads than moloquent's
* Your package have a lot of unresolved issues with some since 2014
* This quote from moloquent : "The base repo WAS and IS being developed and maintained by Jenssegers. Our goal is to provide higher quality support/bugfixes with fresh and additional features."
* Your the main maintainer of this repo and moloquent
* moloquent have a nice online documentation

I looked at the network graph and it seems that moloquent does not get any PR from this repository.

I just want to know  what are the main differences between those 2 packages :).

Thanks for your time.

**Comment by markszymik** [comment]
>  Our goal is to provide higher quality support/bugfixes with fresh and additional features.

It's simply not true. And there's lack of support.

For example with issue with Laravel 5.4 compatibility wasn't resolved by them - they are/were waiting for main repo to be updated.

I've wasted a lot of time with moloquent/moloquent and went to back to the jenssegers/laravel-mongodb (support it's not great, but community is more engaged).

**Comment by ebisbe** [comment]
Same for me as @markszymik said.

**Comment by divine** [comment]
Hello guys,

This library is being updated and any issues/prs are taken care instantly.

Moloquent hasn't been updated since 2017.

Sorry for late reply.
Thanks.

**Comment by CaporalDead** [comment]
Thanks @divine for the feedback :). Just FYI, we decided at that time to use this package and it's been almost 3 years now that we are happy with it !
