### ISSUE TITLE
Error with Jobs Queue

### ISSUE THREAD

**Issue by pirmax** [jenssegers/laravel-mongodb#1202]
@jenssegers

Hi !

I use this package and queue of Laravel 5.4.

When I dispatch a job, I have an error :

> Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'site_com.items' doesn't exist (SQL: select * from `items` where `user_id` = 1 and `slug` = slug-slug-slug-slug-slug and `feed_id` = 1 limit 1) in /home/site_com/http/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

My Handle Job :

```
return Item::create([
                'user_id' => $this->feed->user_id,
                'feed_id' => $this->feed->id,
                'title' => $this->itemTitle,
                'slug' => $this->itemSlug,
            ]);
```

My Model :

```
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Item extends Eloquent
{
    protected $collection = 'items';
    protected $connection = 'mongodb';

    protected $fillable = [
        'user_id',
        'feed_id',
        'title',
        'slug',
    ];
```

Why he use MySQL database instead of MongoDB database ?

**Comment by divine** [comment]
Hello,

Please check documentation that you need to change queue driver.

Sorry for late reply.

Thanks.
