### ISSUE TITLE
Not able to connect to Atlas (MongoDB as Service )

### ISSUE THREAD

**Issue by pankajadhyapak** [jenssegers/laravel-mongodb#1204]
No suitable servers found (`serverSelectionTryOnce` set): [connection closed calling ismaster on 'simplilead-shard-00-00-zhvkn.mongodb.net:27017'] [connection closed calling ismaster on 'simplilead-shard-00-01-zhvkn.mongodb.net:27017'] [connection closed calling ismaster on 'simplilead-shard-00-02-zhvkn.mongodb.net:27017']

**Comment by anushanw** [comment]
@pankajadhyapak Can you please comment on how you get the issue resolved?

**Comment by pankajadhyapak** [comment]
My DB Config file 
`
'atlas' => [
            'driver'   => 'mongodb',
            'host'     => [
                            'example-shard-00-00-zhvkn.mongodb.net:27017',
                            'example-shard-00-01-zhvkn.mongodb.net:27017',
                            'example-shard-00-02-zhvkn.mongodb.net:27017'
                          ],
            'database' => 'exampleDB',
            'username' => 'example',
            'password' => 'example',
            'options'  => [
                'replicaSet' => 'example-shard-0',
                'ssl' => 'true',
                'authSource' => 'admin'
                ]
        ],`

**Comment by monothorn** [comment]
This worked for me = 
In Laravel, Use 'dsn' key in config/database.php as shown below to mention the complete cluster url.

   ```
 'mongodb_conn' => [
            'driver' => 'mongodb',
            'dsn'=>'mongodb://username:password@hosts/database?ssl=true&replicaSet=replicaSet&authSource=admin',
            'database' => 'my_data',
        ]
```

**Comment by zishiguo** [comment]
@jenssegers [configuration](https://github.com/jenssegers/laravel-mongodb#configuration)
`'mongodb' => [
    'driver'   => 'mongodb',
    'host'     => ['server1', 'server2'],
    'port'     => env('DB_PORT', 27017),
    'database' => env('DB_DATABASE'),
    'username' => env('DB_USERNAME'),
    'password' => env('DB_PASSWORD'),
    'options'  => [
		'replicaSet' => 'replicaSetName'
	]
],`
I see source code.
`
    /**
     * Create a DSN string from a configuration.
     *
     * @param  array $config
     * @return string
     */
    protected function getDsn(array $config)
    {
        // Check if the user passed a complete dsn to the configuration.
        if (! empty($config['dsn'])) {
            return $config['dsn'];
        }

        // Treat host option as array of hosts
        $hosts = is_array($config['host']) ? $config['host'] : [$config['host']];

        foreach ($hosts as &$host) {
            // Check if we need to add a port to the host
            if (strpos($host, ':') === false && ! empty($config['port'])) {
                $host = $host.':'.$config['port'];
            }
        }

        // Check if we want to authenticate against a specific database.
        $auth_database = isset($config['options']) && ! empty($config['options']['database']) ? $config['options']['database'] : null;

        return 'mongodb://'.implode(',', $hosts).($auth_database ? '/'.$auth_database : '');
    }
`
and 
`
    /**
     * Create a new MongoDB connection.
     *
     * @param  string $dsn
     * @param  array  $config
     * @param  array  $options
     * @return \MongoDB\Client
     */
    protected function createConnection($dsn, array $config, array $options)
    {
        // By default driver options is an empty array.
        $driverOptions = [];

        if (isset($config['driver_options']) && is_array($config['driver_options'])) {
            $driverOptions = $config['driver_options'];
        }

        // Check if the credentials are not already set in the options
        if (! isset($options['username']) && ! empty($config['username'])) {
            $options['username'] = $config['username'];
        }
        if (! isset($options['password']) && ! empty($config['password'])) {
            $options['password'] = $config['password'];
        }

        return new Client($dsn, $options, $driverOptions);
    }
`
No dsn way of configuration use [$uriOptions](http://php.net/manual/zh/mongodb-driver-manager.construct.php). However $uriOptions accepts "authMechanism" and "authMechanismProperties" options until 1.3.0. 

Can you compatible the version  1.2.0 ?
