### ISSUE TITLE
FatalThrowableError: Class 'MongoDB\Client' not found

### ISSUE THREAD

**Issue by manektechmehul** [jenssegers/laravel-mongodb#1207]
Hi, I am trying to implement mongodb withl laravel 5.4,
I have many tried to implement but i always get the error like:
"Class 'MongoDB\Client' not found".

I am using laravel 5.4, and also installed the jenssegers version  3.2.2
And also i was enabled extension mogodb.dll for wampserver php 64bit
![2017-06-02_1335](https://cloud.githubusercontent.com/assets/15045745/26724557/bf0dc4d6-47b7-11e7-9bb0-10f12cfb9193.png)
Please help me!

**Comment by divine** [comment]
Hello,

This has nothing to do with this library, it's an issue with missing/incorrect settings for mongodb extension.
For more information see: https://jira.mongodb.org/browse/PHPC-656

Thanks.
