### ISSUE TITLE
Define model column as mongodb ID

### ISSUE THREAD

**Issue by hpaknia** [jenssegers/laravel-mongodb#1214]
Setting primary key as mongodb id is easy `protected $primaryKey = 'uploadID';` What if I want to set another column e.g. `bookID`  as a mongodb id?

**Comment by hpaknia** [comment]
Any answers? Have I missed something here?

**Comment by drewlag** [comment]
What do you mean? The primary key is only one and it is defined by _protected $primaryKey_

**Comment by hpaknia** [comment]
Suppose there is another column which is of type MongoIs, that would be
great if library take care of ID conversion of this culomn  to string

**Comment by hpaknia** [comment]
Suppose there is another column which is of type MongoIs, that would be
great if library take care of mongoId conversion of this column  to string. Like the way we interact with primary key.
Example: In order to set or get primary key in `$model`:

```
// setting primary key
$model->_id = 'a_string_as_mongo_id';
// getting after retrieval
echo $model->_id; // it's a string
```
Suppose column book is a mongoID:

```
// setting a column which is mongoId
$model->book = new \MongoDB\BSON\ObjectID('a_string_as_mongo_id');
// getting after retrieval
echo (string) $model->book; // it's not a string, we need to cast ot to string
```

While conversion on primary key is happening automatically, I anticipate there should be some options (similar the way we set some columns as date) to let moloquent know that mongoId conversion should happen automatically behind the scenes.

**Comment by vingrad** [comment]
any updates?
