### ISSUE TITLE
Mongo db custom query

### ISSUE THREAD

**Issue by mubbashar** [jenssegers/laravel-mongodb#1219]
Hi
I want to run this mongo db query . What is the way to run the query directly instead of using Eloquent
`db.analytics.group({
    "key": {
        "type": true,
        "social": true,
        "campaign_id": true
    },
    "initial": {
        "total": 0
    },
    "reduce": function(obj, prev) {
        if (true != null) if (true instanceof Array) prev.total += true.length;
        else prev.total++;
    },
    "cond": {
        "user_id": {
            "$in": [ '5825cf8a3f0682527b65f011']
        }
    }
});`

please help me out
thanks!

**Comment by usamamashkoor** [comment]
Hi @mubbashar did you find any solution for this...?

**Comment by mubbashar** [comment]
@usamamashkoor  unfortunately no solution found yet

**Comment by usamamashkoor** [comment]
Thanks for the update.

**Comment by umar28dec** [comment]
Is there any solution found.
