### ISSUE TITLE
Enable logging of executed queries

### ISSUE THREAD

**Issue by sebastiaanluca** [jenssegers/laravel-mongodb#122]
Any way to make MongoDB queries show up in `\DB::getQueryLog()`? It currently only logs SQL queries.

**Comment by mutaharte** [comment]
**before query execute**
`DB::connection( 'mongodb' )->enableQueryLog(); `

**after query**
`dd(DB::connection('mongodb')->getQueryLog());`

you will get the array containing the query.

**Comment by evan766** [comment]
//  work for both mysql and mongodb.
//  call this function before the query

 function dump_sql($connection='mysql')
    {
        $db = app('db')->connection($connection);
        
        // 如果是使用 composer包 "jenssegers/mongodb"查询 mongodb库, 需要enableQueryLog()。
        // 而mysql查询可以不用这个
        $db->enableQueryLog();
        
        $db->listen(function ($sql) {
            
            $singleSql = $sql->sql;
            
            if ($sql->bindings)
            {
                foreach ($sql->bindings as $replace) {
                    $value = is_numeric($replace) ? $replace : "'" . $replace . "'";
                    $singleSql = preg_replace('/\?/', $value, $singleSql, 1);
                }
            }
            
            dump($singleSql);
        });
    }

> **before query execute** `DB::connection( 'mongodb' )->enableQueryLog(); `
> 
> **after query** `dd(DB::connection('mongodb')->getQueryLog());`
> 
> you will get the array containing the query.
