### ISSUE TITLE
OrderBy not working with integer values

### ISSUE THREAD

**Issue by diksha-srivastava** [jenssegers/laravel-mongodb#1221]
Hi,

I have price stored as integer and sorting integer values are not working. I also tried storing it as string and with that sorting works but where condition does not works. 

Please help as both operations are required for me.
![selection_001](https://user-images.githubusercontent.com/17315681/27174707-a394f274-51da-11e7-92df-001366cb3ae7.png)
![selection_002](https://user-images.githubusercontent.com/17315681/27174706-a38f07f6-51da-11e7-876c-4e2af572b1be.png)

**Comment by zemo20** [comment]
how did u solve this shit ?

**Comment by zemo20** [comment]
how did you solve this problem ?
