### ISSUE TITLE
Laravel WhereHas() Method Not Working

### ISSUE THREAD

**Issue by ghost** [jenssegers/laravel-mongodb#1225]
Laravel Framework I use WhereHas() with mongo db setup in my project. I facing issue with Mongo DB after Using WhereHas() In laravel.
Error:Call to undefined method Jenssegers\Mongodb\Query\Builder::getHasCompareKey()

**Comment by gitdward** [comment]
Is this really solved? Because the methods "has" and "whereHas" is not working for me
