### ISSUE TITLE
Two like is not working

### ISSUE THREAD

**Issue by sarathiscookie** [jenssegers/laravel-mongodb#1228]
I have a text box for search some data. For that I have used **like**.  I have followed the same rules in documentation but not working. When I search **invoice_number** data is return empty. But when I search **beds** data is getting perfectly. Please correct me.  

```
$bookings = Booking::select('invoice_number', 'temp_user_id', 'user', 'checkin_from', 'reserve_to', 'beds', 'dormitory', 'sleeps', 'status', 'payment_status', 'payment_type', 'total_prepayment_amount', 'txid')
                ->where('is_delete', 0)
                ->where('invoice_number', 'like', "%{$search}%")
                ->orWhere('beds', 'like', "%{$search}%")
                ->skip($start)
                ->take($limit)
                ->orderBy($order, $dir)
                ->get();
```

**Comment by JennerTien** [comment]
`Booking::select('invoice_number', 'temp_user_id', 'user', 'checkin_from', 'reserve_to', 'beds', 'dormitory', 'sleeps', 'status', 'payment_status', 'payment_type', 'total_prepayment_amount', 'txid')
		->where('is_delete', 0)
		->where(function ($query) use ($search) {
			$query->where('invoice_number', 'like', "%{$search}%")
				  ->orWhere('beds', 'like', "%{$search}%")
			return $query;
		});`
		->skip($start)
		->take($limit)
		->orderBy($order, $dir)
		->get();
`

**Comment by sarathiscookie** [comment]
@JennerTien Thank you
