### ISSUE TITLE
Unable to apply where condition to join table

### ISSUE THREAD

**Issue by prashantcct** [jenssegers/laravel-mongodb#1233]
Hello @jenssegers 

I am unable to apply where condition to join table when I am using laravel-mongodb.
Please help me asap!

Thanks in advanced

**Comment by alexgiuvara** [comment]
MongoDB's left join `$lookup` operator has not been implemented here. [Check here](https://github.com/jenssegers/laravel-mongodb/wiki/Complexe-aggregate-call) how to use advanced aggregations
