### ISSUE TITLE
Attach doesnt work

### ISSUE THREAD

**Issue by MirlanJA** [jenssegers/laravel-mongodb#1234]
Hi, I'm using MongoDB and

`$adminRole->users()->attach($adminUser);`

doesn't create rows in role_users table. How to solve this problem?

P.S In all my models I used this `use Jenssegers\Mongodb\Eloquent\Model as Eloquent;`

**Comment by simonschaufi** [comment]
Attaching related objects only works if the mother object is persisted already! So if your adminRole is not yet stored in the database, it doesn't work. I had the same problem.

**Comment by irvv17** [comment]
> Attaching related objects only works if the mother object is persisted already! So if your adminRole is not yet stored in the database, it doesn't work. I had the same problem.

I think this is the reason of my seeder failing, tnaks..
