### ISSUE TITLE
Bug in MongoQueue class

### ISSUE THREAD

**Issue by JuCarr** [jenssegers/laravel-mongodb#1242]
@jenssegers 

Hi,

I think there is something wrong in the MongoQueue class. Could you have a look at this?

First, this request does not seem to work properly on my server when the "reserved" field is not set which is the case for any newly inserted job.

```
        // Jenssegers\Mongodb\Queue\MongoQueue
        // getNextAvailableJobAndReserve($queue)

        // ...
    
        $job = $this->database->getCollection($this->table)->findOneAndUpdate(
            [
                'queue' => $this->getQueue($queue),
                'reserved' => 0,
                'available_at' => ['$lte' => Carbon::now()->getTimestamp()],
            ],
            [
                '$set' => [
                    'reserved' => 1,
                    'reserved_at' => Carbon::now()->getTimestamp(),
                ],
            ],
            [
                'returnDocument' => FindOneAndUpdate::RETURN_DOCUMENT_AFTER,
                'sort' => ['available_at' => 1],
            ]
        );

        // ...
```
I changed it like this and it seems to work:
```
        // Jenssegers\Mongodb\Queue\MongoQueue
        $job = $this->database->getCollection($this->table)->findOneAndUpdate(
            [
                'queue' => $this->getQueue($queue),
                //'reserved' => 0,
                'reserved'     => ['$ne' => 1],
                'available_at' => ['$lte' => Carbon::now()->getTimestamp()],
            ],
            [
                '$set' => [
                    'reserved' => 1,
                    'reserved_at' => Carbon::now()->getTimestamp(),
                ],
            ],
            [
                'returnDocument' => FindOneAndUpdate::RETURN_DOCUMENT_AFTER,
                'sort' => ['available_at' => 1],
            ]
        );
```
Most importantly, I don't understand what you tried to do in the "releaseJobsThatHaveBeenReservedTooLong" method. Based on its name, I would assume that this method reset the jobs (so setting reserved to 0 and reserved_at to null) that have run for too long so that then can be tried one more time. But in this case why also selecting jobs that are just ready to be processed?

```
    protected function releaseJobsThatHaveBeenReservedTooLong($queue)
    {
        $expiration = Carbon::now()->subSeconds($this->retryAfter)->getTimestamp();
        $now = time();

        $reserved = $this->database->collection($this->table)
            ->where('queue', $this->getQueue($queue))
            ->where(function ($query) use ($expiration, $now) {
                // Check for available jobs
                //** WHY selecting these ones? **
                $query->where(function ($query) use ($now) {
                    $query->whereNull('reserved_at');
                    $query->where('available_at', '<=', $now);
                });

                // Check for jobs that are reserved but have expired
               // Yes, make sense!
                $query->orWhere('reserved_at', '<=', $expiration);

            })->get();

        foreach ($reserved as $job) {
            $attempts = $job['attempts'] + 1;
            $this->releaseJob($job['_id'], $attempts);
        }
    }
```
What happened on my server is that ready to be processed jobs where picked up by this method to be released, setting then the "reserved" field to 0 (which in turn could allow then to be selected by the getNextAvailableJobAndReserve method). 

Unfortunately, under some load, these jobs were picked up many times by the "releaseJobsThatHaveBeenReservedTooLong", increasing the "attempts" field before they even get a chance to be picked up by the "getNextAvailableJobAndReserve". Ultimately, they would end up as 
failed jobs because of too many attempts while they actually never had been processed!

So I updated this method like this to fix this issue:

```
    protected function releaseJobsThatHaveBeenReservedTooLong($queue)
    {
        $expiration = Carbon::now()->subSeconds($this->retryAfter)->getTimestamp();
        $now = time();

        $reserved = $this->database->collection($this->table)
            ->where('queue', $this->getQueue($queue))
            ->where(function ($query) use ($expiration, $now) {

                // Check for jobs that are reserved but have expired
                $query->where('reserved', '=', 1);
                $query->where('reserved_at', '<=', $expiration);

            })->get();

        foreach ($reserved as $job) {
            $attempts = $job['attempts'] + 1;
            $this->releaseJob($job['_id'], $attempts);
        }
    }
```
This seems to work fine for me but I have the feeling that I misunderstood something. Could you have a look and tell me if I'm correct?

Thanks!

**Comment by sbourdette** [comment]
I confirm that under Heavy load Queue doesn't speed up.
With the proposed correction it solve it

Regards

**Comment by JuCarr** [comment]
To make this issue clear, here a very simple example to reproduce it.
First, let's make a basic job which only echoes something:

```
<?php

namespace App\Jobs;

use App\Jobs\Job;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;


class EchoJob extends Job implements ShouldQueue
{
    use InteractsWithQueue, SerializesModels;

    protected $id;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct($id)
    {
        $this->id = $id;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        echo 'Handling job: ' . $this->id . PHP_EOL;
    }
}
```
Then, let's make a command to queue a few jobs

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Jobs\EchoJob;

class CreateEchoJobs extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'create:echo:jobs';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Queue echo jobs';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        for($i = 0; $i < 200; $i++) {
            
            // let's add some load here
            $job = new EchoJob($i);
            $job->delay(rand(10, 30));

            dispatch($job);
        }
    }
}

```
Then execute the command and run the queue worker:

`php artisan queue:work --tries=3`

On my laptop (i7, 16GB Ram), I get this kind of result:

> 
> [2017-09-11 15:53:06] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:06] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:06] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:06] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:06] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:06] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:06] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:06] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:06] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob
> Handling job: 19
> [2017-09-11 15:53:09] Processed:  App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob
> Handling job: 50
> [2017-09-11 15:53:09] Processed:  App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob
> Handling job: 52
> [2017-09-11 15:53:09] Processed:  App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:09] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:09] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:09] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob
> [2017-09-11 15:53:09] Failed:     App\Jobs\EchoJob
> [2017-09-11 15:53:09] Processing: App\Jobs\EchoJob

Most of the jobs fail. With my correction, none of the jobs fail. 

> [2017-09-11 16:03:57] Processed:  App\Jobs\EchoJob
> [2017-09-11 16:03:57] Processing: App\Jobs\EchoJob
> Handling job: 70
> [2017-09-11 16:03:57] Processed:  App\Jobs\EchoJob
> [2017-09-11 16:03:57] Processing: App\Jobs\EchoJob
> Handling job: 94
> [2017-09-11 16:03:57] Processed:  App\Jobs\EchoJob
> [2017-09-11 16:03:57] Processing: App\Jobs\EchoJob
> Handling job: 96
> [2017-09-11 16:03:57] Processed:  App\Jobs\EchoJob
> [2017-09-11 16:03:57] Processing: App\Jobs\EchoJob
> Handling job: 136
> [2017-09-11 16:03:57] Processed:  App\Jobs\EchoJob
> [2017-09-11 16:03:57] Processing: App\Jobs\EchoJob
> Handling job: 159
> [2017-09-11 16:03:57] Processed:  App\Jobs\EchoJob
> [2017-09-11 16:03:57] Processing: App\Jobs\EchoJob
> Handling job: 171
> [2017-09-11 16:03:57] Processed:  App\Jobs\EchoJob
> [2017-09-11 16:03:57] Processing: App\Jobs\EchoJob
> Handling job: 181
> //...

But my correction breaks the attempt counter. A job will only be tried once, no matter what you put in the --tries option. So, it's not really satisfactory... Anyone has a better idea on this...?

**Comment by hartono-sulaiman-kaskus** [comment]
+1

**Comment by sbourdette** [comment]
Any update ?

**Comment by nshore** [comment]
I am visiting this issue as I am experiencing the same issue when trying to use MongoDB as my queue store.  I agree the query to find which jobs to update looks incorrect.  I can see that this commit changed it from something that looked like it worked -> https://github.com/jenssegers/laravel-mongodb/commit/76281c1be6693f76b09490e71551ff4e034c3120#diff-ae07dda5cc8020335d5bbd7ef01ca671

Do we know why the code was changed as part of this commit that was changing the automated test?  No explanation in the commit.

**Comment by nshore** [comment]
Looks like someone tried to fix it https://github.com/jenssegers/laravel-mongodb/pull/1535

**Comment by sbourdette** [comment]
up

**Comment by divine** [comment]
Closing, fixed in https://github.com/jenssegers/laravel-mongodb/pull/1855
