### ISSUE TITLE
[Question] Should I use Advanced Wheres or Aggregation ?

### ISSUE THREAD

**Issue by yosephoche** [jenssegers/laravel-mongodb#1243]
@jenssegers  i'm having a code like this :
`$program = Program::where(function($query){`
             `$query->where('_id', '=', '5965a47e26469e39c8007033')`
		`->where('status', '=', 1)`
		`->where('bidang._id', '=', '5901bf920bd6da6812000029')`
		`->where('bidang.status', '=', 1)`
		`->where('isu._id', '=', '5908169c0bd6dae02e000029')`
		`->where('isu.status', '=', 1)`
		`->where('skpd._id', '=', '5940ef2826469e264c005162')`
		`->where('skpd.status', '=', 1);`
        `})->get();`

there is nothing problem about the result, but i don't want my query take too long time and take too much memory usage, so which one should i use advance where or aggregation ??

**Comment by lindelius** [comment]
There is no need to use aggregations for this.

If the query is taking a long time to execute, make sure that you have a proper index to handle that specific query.
