### ISSUE TITLE
How to access object properties?

### ISSUE THREAD

**Issue by lucavallin** [jenssegers/laravel-mongodb#1246]
Hello,
when retrieving some entry from mongo, I have two problems:

1 - properties are empty. If I do $obj->getName(), name is null. But there's an attributes object that contains all my properties with the right value.
2 - I can't call ->getCreatedAt(), how do I access timestamps?

**Comment by alexgiuvara** [comment]
The properties are accessible as any regular SQL powered Eloquent model. To answer your questions:
1. $obj->name;
2. $obj->created_at

You have to implement the magic getters
