### ISSUE TITLE
laravel-mongodb community 

### ISSUE THREAD

**Issue by acidjazz** [jenssegers/laravel-mongodb#1247]
@jenssegers would it make sense to create and promote some type of discord or gitter channel for this package? this might help get the questions out of the issues and potentially be a go-to for people just getting started

I can set it all up and PR the readme changes if you'd like.

**Comment by divine** [comment]
Hello and sorry for late reply!

We're as community trying to help out this library on fixes and new features. Most of the issues has been closed and PRs merged as well new version released.

We kindly ask you for your help [here ](https://github.com/jenssegers/laravel-mongodb/issues/1974)

Thanks!
