### ISSUE TITLE
How to use pivot table on many to many?

### ISSUE THREAD

**Issue by shawn-lin** [jenssegers/laravel-mongodb#1248]
If pivot table has been created, ex:user_group.

And users and groups collection doesn't have group_ids and user_ids field.

Any way to get groups by $user->groups or User::with("groups") statement?

**Comment by alexgiuvara** [comment]
> The `belongsToMany` relation will not use a pivot "table" but will push id's to a related_ids attribute instead

So, `users` and `groups` collection must have `group_ids` and `user_ids` fields.
Maybe you want to use `embedsMany`
```
class User {
    public function groups()
    {
        return $this->embedsMany(Group::class, 'userGroups');
    }
}

User::first()->groups()->create(['group_details_here']);
dd(User::first()->groups());
```

**Comment by vaishnavmhetre** [comment]
Hi @alexgiuvara, as of my requirement, I can't embed new object (eg. _Group_ object) directly as I need to reference instanciated one, hence utterly need pivot style functionality.

I thought about a workaround. Just need to know if this will work.

`
class UserGroupAssoc{
    /* 
        Has the following schema -

        _id (will autogenerate)
        user_id
        group_id

    */

    public function user(){
        return $this->hasOne(User::class);
    }

    public function group(){
        return $this->hasOne(Group::class);
    }
}

class Group{

    // ...boilerplate stuff

    public function getUsersAttribute(){
        return UserGroupAssoc::whereGroupId($this->_id)->get()->map(function($userGroupAssoc){
            return $userGroupAssoc->user
        })
    }
}

class User{

    // ...boilerplate stuff

    public function groups(){
        return $this->embedsMany(UserGroupAssoc::class);
    }

    public function getGroupsAttribute(){
        return $this->groups->map(function($userGroupAssoc){
            return $userGroupAssoc->group
        })
    }
}
`

**Comment by alexgiuvara** [comment]
@vaishnavmhetre sorry mate, can't help you. I haven't touched mongo for one year already.

**Comment by vaishnavmhetre** [comment]
@alexgiuvara, currently the defined logic is okay to function, I just want to ask, that a relation defined as name groups is in User class. Can I still define groups as an explicit attribute only as a getter?
