### ISSUE TITLE
Multiple hosts in replica set takes long time when one host goes down

### ISSUE THREAD

**Issue by rms2219** [jenssegers/laravel-mongodb#125]
I have a replica set with 2 hosts. When 1 goes down, regardless of whether it is a primary or secondary, all requests take a long time (~60 seconds), and sometimes timeout. We've verified that if ServerA goes down, and it was the primary, ServerB successfully becomes the primary, yet we still have very slow responses. As soon as we bring ServerA back up, everything continues as normal with the expected response times.

EDIT : We are using PHP MongoDB driver v1.4.5 and MongoDB v2.4.8

**Comment by jcorry** [comment]
@rms2219 did you ever resolve this? We are having similar issues and I don't know where to begin to troubleshoot...

**Comment by rms2219** [comment]
@jcorry Unfortunately no, we never did resolve this. It hasn't been a problem, so we've brushed it under the rug for the time being. Let me know if you find anything.

**Comment by juanmrad** [comment]
Has any of you been able to fix this?

We are experiencing the same issue and becomes a problem when scaling cluster size up and down.
