### ISSUE TITLE
How to select specific fields from all document?

### ISSUE THREAD

**Issue by prashant-pokhriyal** [jenssegers/laravel-mongodb#1250]
suppose I want to get only ids of all documents in a collection. How will I achieve this, I'm not able to find any api for this. Equivalent of SQL command will be as follows : 

`SELECT _id FROM user;`

I tried following command : 

`$user_id = User::get(['_id']);`

But it's not returning array or ids. In fact its returning id with extra information which I don't want. One way that I found is to parse this object and get the ids, but I think there must be some smarter way to get only ids.

**Comment by shijinmon** [comment]
Prashant-pokhriyal, if you get any solution please share. iam stuck with this problem. Thank you.

**Comment by prashant-pokhriyal** [comment]
@shijinmon, you can use [`select`][1] method to get specific columns. Like below
```php
User::select('_id')->find($id);
```

[1]: https://laravel.com/docs/5.7/queries#selects

**Comment by shijinmon** [comment]
> @shijinmon, you can use [`select`](https://laravel.com/docs/5.7/queries#selects) method to get specific columns. Like below
> 
> ```
> User::select('_id')->find($id);
> ```

Thank you for the reply. User::select('_id')->find($id), this is fine, but if there is any way to getting this format, User::select('_id', 'full_name as name')->find($id);
