### ISSUE TITLE
Not able to install with laravel 5.4

### ISSUE THREAD

**Issue by rameshnittali** [jenssegers/laravel-mongodb#1251]
I am using laravel 5.4 and my php version is 7.0.10 in WAMP 3.0.6. I have used the MongoDB driver both 1.1.1 and 1.1.2 dll but the composer errors out with below log : 

Using version ^3.2 for jenssegers/mongodb
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb v3.2.0 requires mongodb/mongodb ^1.0.0 -> satisfiable b
y mongodb/mongodb[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2]
.
    - jenssegers/mongodb v3.2.1 requires mongodb/mongodb ^1.0.0 -> satisfiable b
y mongodb/mongodb[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2]
.
    - jenssegers/mongodb v3.2.2 requires mongodb/mongodb ^1.0.0 -> satisfiable b
y mongodb/mongodb[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2]
.
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.0.5 requires ext-mongodb ^1.1.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.0.4 requires ext-mongodb ^1.1.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP ext
ension mongodb is missing from your system.
    - Installation request for jenssegers/mongodb ^3.2 -> satisfiable by jensseg
ers/mongodb[v3.2.0, v3.2.1, v3.2.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - E:\wamp64\bin\php\php7.0.10\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PH
P in CLI mode.

Installation failed, reverting ./composer.json to its original content.

Kindly  help me. Thanks in advance.

**Comment by msztorc** [comment]
You have to enable mongodb extension in your php.ini

http://php.net/manual/en/mongodb.installation.windows.php
