### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by SimplyCorey** [jenssegers/laravel-mongodb#1258]
I ran into this issue when I upgraded to laravel 5.5

```Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Illuminate\Database\Eloquent\Model::belongsToMany($related, $table = NULL, $foreignPivotKey = NULL, $relatedPivotKey = NULL, $parentKey = NULL, $relatedKey = NULL, $relation = NULL)```

**Comment by Ojvar** [comment]
Exactly ! I have same problem !
I guess the authors must be redefine "belongsToMany" function with new parameters

Thanks again for your great work!

**Comment by andycaramba** [comment]
Broken from Laravel v5.4.31. See [this commit](https://github.com/laravel/framework/commit/f59f6b29539fe149841c1f88bb5ad3d97e0403c0#diff-fac59ee2778e54567a539e9140a1a42cR743).

**Comment by SimplyCorey** [comment]
Fixed on laravel's side.  https://github.com/laravel/framework/pull/20407

**Comment by elanvans** [comment]
fixed this issue?

**Comment by smendozaisf** [comment]
@SimplyCorey How do we fix it? I read about solved in Laravel Side, but still getting this error with laravel 5.5 installed yesterday and the package added today.

**Comment by godfreymakori** [comment]
Check out https://github.com/jenssegers/laravel-mongodb/pull/1282/commits/066e2193bc50d2dce1802c00d46ce3b7d252a1c6

**Comment by godfreymakori** [comment]
@smendozaisf Check out this gist https://github.com/jenssegers/laravel-mongodb/pull/1282/commits/066e2193bc50d2dce1802c00d46ce3b7d252a1c6

**Comment by SimplyCorey** [comment]
@smendozaisf  Laravel ended up reverting the change and making it a backwards breaking change again.  My comment is no longer valid.

**Comment by smendozaisf** [comment]
I ended using Laravel 5.4. I don't like to change `vendor` folder files. When this package make the update, I'll migrate to Laravel 5.5. I hope it will soon

Thanks :)

**Comment by Once88** [comment]
i getting  the same issue with laravel 5.5

**Comment by kideny** [comment]
i getting the same issue with laravel 5.5.14

**Comment by klferreira** [comment]
No fix yet? I guess i'll have to go back to 5.4 for now.

**Comment by hainv053** [comment]
i getting the same issue with lumen 5.5

**Comment by git4shankars** [comment]
i too am getting this error with laravel 5.5!! Is this issue resolved, if not why is it showing as Closed!!

**Comment by yassine-khachlek** [comment]
Me too i have the same problem with Laravel 5.5

**Comment by fathur** [comment]
why @jenssegers not resolve this issue?

**Comment by jesseyofferenvan** [comment]
This issue still stands 👎
