### ISSUE TITLE
json support and create_at

### ISSUE THREAD

**Issue by bigpws** [jenssegers/laravel-mongodb#1260]
How about add json functions that we can use it when we create one or more record?
so record form api which json formmat result can be saved directly。
and create_at as well,how could I define any record insert to some on collection will be and a create_at timestamp automatic

**Comment by alexgiuvara** [comment]
you cannot use native PHP json_* functions to save directly to MongoDB. 
created_at is automatic when you save the model and follow Laravel's documentation.
