### ISSUE TITLE
where clause on a nested document

### ISSUE THREAD

**Issue by arashrahimi46** [jenssegers/laravel-mongodb#1261]
Hi 
I have a nested document like this : 
`{
    "_id" : ObjectId("598577f3acb9ee0c3b3e7199"),
    "shenase" : "12300",
    "name" : "ff",
    "vehicle" : "van",
    "locations" : [ 
        {
            "time" : "12:16:59",
            "date" : "12/05/1396",
            "latiude" : 35.7380266088257,
            "langtiude" : 51.5072907224076
        }, 
        {
            "time" : "12:17:00",
            "date" : "13/05/1396",
            "latiude" : 35.7380266088257,
            "langtiude" : 51.5072907224076
        }, 
        {
            "time" : "12:17:02",
            "date" : "14/05/1396",
            "latiude" : 35,
            "langtiude" : 51.5074229552436
        }
    ]
}`
Now I want to make  a where clause query like this but I dont know who should I do this .

here is the code that I tried but unsuccessful .

`$locations = DB::collection('mycollection')->where("locations.latiude", "=", 35)->get();`

**Comment by alexgiuvara** [comment]
Can't reproduce the problem:
`php artisan tinker`
```
>>> use Illuminate\Support\Facades\DB;
>>> DB::collection('mycollection')->where("locations.latiude",35)->get();
=> Illuminate\Support\Collection {#889
     all: [
       [
         "_id" => MongoDB\BSON\ObjectID {#888
           +"oid": "598577f3acb9ee0c3b3e7199",
         },
         "shenase" => "12300",
         "name" => "ff",
         "vehicle" => "van",
         "locations" => [
           [
             "time" => "12:16:59",
             "date" => "12/05/1396",
             "latiude" => 35.738026608826,
             "langtiude" => 51.507290722408,
           ],
           [
             "time" => "12:17:00",
             "date" => "13/05/1396",
             "latiude" => 35.738026608826,
             "langtiude" => 51.507290722408,
           ],
```
