### ISSUE TITLE
Count not working with multiple where

### ISSUE THREAD

**Issue by Jafo232** [jenssegers/laravel-mongodb#1264]
I am not sure what I am doing wrong here..  In mongo shell, this returns two results:

`db.interactions.find( { $and: [{'park_id':'797'}, {'type':'park_phone'}] })`

But in my model, it returns null.  This does not happen with other values in the type column, so I am at a loss.  I have confirmed $parkid == 797 in the following code:

`Interactions::where('type', '=', "park_phone")->where('park_id', $parkid)->count()`

Any ideas?

**Comment by Jafo232** [comment]
This was a casting issue.  Consider it solved.

**Comment by emanuelverardi** [comment]
I have the same problem.
if I run the same script using the php artisan tinker command the count is displayed correctly, but not in my logs or debug.

count() always return 0

Any Ideas ?

**Comment by Jafo232** [comment]
If I recall correctly, my issue was that $parkid was not casted correctly.
