### ISSUE TITLE
Apache mpm_event

### ISSUE THREAD

**Issue by IvanSostarko** [jenssegers/laravel-mongodb#1265]
Hi,

I have a problem when I want to use this package with Apache mpm_worker or  mpm_event. It's only works with mpm_prefork.
I'm using Apache/2.4.6 (CentOS) and PHP7.1

Error:
FatalThrowableError in Client.php line 81:
Class 'MongoDB\Driver\Manager' not found

**Comment by divine** [comment]
Hello,

Please check your php.ini that mongodb extension has been enabled.

Sorry for late reply.
Thanks.
