### ISSUE TITLE
Database [mongodb] not configured.

### ISSUE THREAD

**Issue by diveshpanwar** [jenssegers/laravel-mongodb#1268]
**My configuration in database.php**
    'mongodb' => [
        'driver'   => 'mongodb',
        'host'     => env('DB_HOST', 'localhost'),
        'port'     => env('DB_PORT', 27017),
        'database' => env('DB_DATABASE'),
        'username' => env('DB_USERNAME'),
        'name'=>'mongodb',
        'password' => env('DB_PASSWORD'),
        'options'  => [
            'database' => 'admin' // sets the authentication database required by mongo 3
        ]
],

**## my configuration in .env is**

DB_CONNECTION=mongodb
DB_HOST=127.0.0.1
DB_PORT=27017
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=divesh

**I am trying the code below in my routes file web.php**
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('mongo',function() {
    **$entries = DB::collection('laravels')->get();
    var_dump($entries);**
});

and I am getting error 
**(1/1) InvalidArgumentException
Database [mongodb] not configured.**

Please help me with a solution

I am using php 7.0, laravel 5.4 and mongodb 3.2.16

**Comment by alexgiuvara** [comment]
Change your default database connection name in `config/database.php`:
```php
'default' => env('DB_CONNECTION', 'mongodb'),
```
The piece of code you're trying to test doesn't say anything to me 
> I am trying the code below in my routes file web.php
> `get(); var_dump($entries);** });` and I am getting error

**Comment by nguyen179son** [comment]
Any solution? I have the same issue when running migration

**Comment by divine** [comment]
Please check duplicate issue #515
