### ISSUE TITLE
HybridRelations::belongsToMany not compatible with Model::belongsToMany

### ISSUE THREAD

**Issue by dfreer** [jenssegers/laravel-mongodb#1273]
#1258 

Started a new project with Laravel and I am running into this issue.

laravel/framework dev-master (608732a => 60860f3) Checking out 60860f3fdb
jenssegers/mongodb (v3.2.2)

`ErrorException: Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Illuminate\Database\Eloquent\Model::belongsToMany($related, $table = NULL, $foreignPivotKey = NULL, $relatedPivotKey = NULL, $parentKey = NULL, $relatedKey = NULL, $relation = NULL)`

Looks like it's missing 2 parameters

**Comment by Entrio** [comment]
Is there an ETA on this?

**Comment by elanvans** [comment]
fix this issue?

**Comment by akaroot** [comment]
take a look at issue #1282

**Comment by sagargulati** [comment]
Is this fixed?

**Comment by nadeemzai** [comment]
fix HybridRelations::belongsToMany not compatible with Model::belongsToMany #1282
best ... i solved this issue by using above link :)

**Comment by sagargulati** [comment]
Which Link?
