### ISSUE TITLE
distinct() not working as expected

### ISSUE THREAD

**Issue by george-viaud** [jenssegers/laravel-mongodb#1274]
I have a rather large database that I am trying to get a distinct list of a particular field from.

To do this in the console I execute: 
```db.getCollection('mycollection').distinct('myfield')```

in ~0.1 seconds I am given a list of 11 unique values.

I should also note that this field is indexed.

When I perform a similar operation in Laravel, the operation times out and dies but I'm not sure why:

```
$results = MyModel::distinct('myfield')->get()->toArray();
```

Any advice would be greatly appreciated - thank you

UPDATE:  The code below works fine, but I'd really like to understand why the above does not:
```
MyModel::raw()->distinct('myfield');
```

**Comment by pablofmorales** [comment]
toArray() function is going to create an array in memory with all the elements in the results. 

Don't use toArray() or limit the results

**Comment by george-viaud** [comment]
Thanks for the insight @pablofmorales  - any idea why the raw code works but model-derived call didnt?  Thanks!
