### ISSUE TITLE
Issues with date whereBetween not work

### ISSUE THREAD

**Issue by im-zhangxi** [jenssegers/laravel-mongodb#1276]
my code:
$startDate = new \DateTime($startDate);
$endDate = new \DateTime($endDate);
User::whereBetween('created_at', [$startDate, $endDate ]);

Execute SQL:
User.aggregate([{"$match":{{"created_at":{"$gte":{"date":"2016-09-01 00:00:00.000000","timezone_type":3,"timezone":"Asia\/Shanghai"},"$lte":{"date":"2017-09-01 00:00:00.000000","timezone_type":3,"timezone":"Asia\/Shanghai"}}},{"deleted_at":null}]}},{"$group":{"aggregate":{"$sum":1},"_id":null}}],{"typeMap":{"root":"array","document":"array"}})

Please help

**Comment by hartono-sulaiman-kaskus** [comment]
I also had this problem

**Comment by Wu4m4n** [comment]
I have the same issue.

**Comment by im-zhangxi** [comment]
@Wu4m4n me too

**Comment by mustyzod** [comment]
> I have the same issue.
> To fix this I use
> 
> `where($dateField,'>=',$begin)->where($dateField,'<=',$end)`
> 
> and works great!

i have tried all this earlier, it doesnt work with time, only the date is considered in the quey, i need it to filter date and time
