### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by elanvans** [jenssegers/laravel-mongodb#1279]
Started a new project with Laravel 5.5 and I am running into this issue.

ErrorException thrown with message "Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Illuminate\Database\Eloquent\Model::belongsToMany($related, $table = NULL, $foreignPivotKey = NULL, $relatedPivotKey = NULL, $parentKey = NULL, $relatedKey = NULL, $relation = NULL)"

**Comment by devcircus** [comment]
I'm sure once 5.5 is officially official, the package will be updated to handle any breaks.

**Comment by elanvans** [comment]
@devcircus yes laravel 5.5 is officially released.

https://laravel-news.com/laravel-5-5

**Comment by devcircus** [comment]
I'm sure a PR would be much appreciated.

**Comment by sagargulati** [comment]
@jenssegers : when should we expect MongoDB package update for Laravel 5.5

+1

**Comment by SimplyCorey** [comment]
See: https://github.com/jenssegers/laravel-mongodb/pull/1280

**Comment by nesk** [comment]
@elanvans Asking for an issue to be fixed ASAP on a free and open source projet while not providing any work by yourself is kinda [a dick move](https://user-images.githubusercontent.com/817508/29976186-78dd9030-8f39-11e7-97d9-2cdb78525b4b.png).

Laravel's 5.5 release is just a few days old, give some time to this project to be updated and tested.

**Comment by djzara** [comment]
@elanvans

Which PR was it you opened? I'm trying to find it.

**Comment by pirmax** [comment]
I have the same issue...

**Comment by kirensiva** [comment]
I have the same issue...
https://stackoverflow.com/questions/45983708/laravel-5-5-mongo-db-error

**Comment by kirensiva** [comment]
Thank you it is fixed now.

**Comment by RemiCollin** [comment]
PR in progress : https://github.com/jenssegers/laravel-mongodb/pull/1295

BelongsToMany & Embedded relationships are not working anymore (see failing tests). Anyone wanting to join in to help find the fix is welcome ;)

**Comment by jenssegers** [comment]
I released an alpha tag.

**Comment by elanvans** [comment]
@jenssegers 

I get error, when i update laravel-mongodb package

` [ErrorException]
  Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::belongsToMany($related, $collection = NULL, $foreign
  Key = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Illuminate\Database\Eloquent\Model::be
  longsToMany($related, $table = NULL, $foreignPivotKey = NULL, $relatedPivotKey = NULL, $parentKey = NULL, $relat
  edKey = NULL, $relation = NULL)


Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.`

**Comment by akas84bg** [comment]
same here... :(

**Comment by djzara** [comment]
Are there any real updates on this? I'll be happy to try and submit my own PR, but I recall seeing one already worked on. It's been over 2 months now.

**Comment by RemiCollin** [comment]
This releases works for me : https://github.com/jenssegers/laravel-mongodb/releases/tag/v3.3.0-alpha

**Comment by akas84bg** [comment]
Yes, the alpha seems to be working..
