### ISSUE TITLE
SQL hybrid models require primaryKey override

### ISSUE THREAD

**Issue by bmwalter68** [jenssegers/laravel-mongodb#128]
I noticed that when using a hybrid SQL/MongoDB model relationship that in addition to descending my SQL models from Jenssegers\Eloquent\Model I also need to specify:

protected $primaryKey = 'id';

in my SQL models or queries fail due to the primary key defaulting to '_id'.  It didn't take much poking about to find primaryKey, but if this is the intended behavior it should probably be documented.
On the other hand, if I'm doing something 'Dirty and Evil (tm)' by overriding this, please let me know ;)
Thanks for the code, it's superb!

**Comment by roosh-t3** [comment]
This Still persist !! I can confirm
