### ISSUE TITLE
jenssegers/laravel 3.2.2  mongodb 2.6 error, someone help me!

### ISSUE THREAD

**Issue by langming** [jenssegers/laravel-mongodb#1285]
Fatal error: Uncaught MongoDB\Driver\Exception\AuthenticationException: auth failed in /var/www/html/vendor/mongodb/mongodb/src/Operation/Find.php:219 Stack trace: #0 /var/www/html/vendor/mongodb/mongodb/src/Operation/Find.php(219): MongoDB\Driver\Server->executeQuery('homepage_flow.p...', Object(MongoDB\Driver\Query), Object(MongoDB\Driver\ReadPreference)) #1 /var/www/html/vendor/mongodb/mongodb/src/Collection.php(525): MongoDB\Operation\Find->execute(Object(MongoDB\Driver\Server)) #2 [internal function]: MongoDB\Collection->find(Array, Array) #3 /var/www/html/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php(43): call_user_func_array(Array, Array) #4 /var/www/html/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(389): Jenssegers\Mongodb\Collection->__call('find', Array) #5 /var/www/html/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(206): Jenssegers\Mongodb\Query\Builder->getFresh(Array) #6 / in /var/www/html/vendor/mongodb/mongodb/src/Operation/Find.php on line 219

**Comment by divine** [comment]
Hello,

Please check that you've given correct permission for connecting user.

Sorry for late reply.
Thanks.
