### ISSUE TITLE
Need to Ovewrite Collection - (ERROR Collection already exists)

### ISSUE THREAD

**Issue by jpldev** [jenssegers/laravel-mongodb#1287]
Hello! 

I want to ovewrite my schema with migrations. So I delete the models and migrations files to start again.

But when I run php artisan migrate ; I can't do this because  I have this error. 

ftpuser@MONITOREO-HUBS:/var/www/html/new-ups$ php artisan migrate -vvv

  **[MongoDB\Driver\Exception\RuntimeException (48)]
  a collection 'monitoringhubs.ups' already exists**

I go to Mongo and delete manually the collection, but when I run again the command it creates the collection again.... 

**How can I use in Blueprint the option safe:false?**

**db.createCollection('test', {safe:true}, function(err, collection) {});
The {safe:true} option will make the method return an error if the collection already exists.**

Exception trace:
 () at /var/www/html/new-ups/vendor/mongodb/mongodb/src/Operation/CreateCollection.php:184
 MongoDB\Driver\Server->executeCommand() at /var/www/html/new-ups/vendor/mongodb/mongodb/src/Operation/CreateCollection.php:184
 MongoDB\Operation\CreateCollection->execute() at /var/www/html/new-ups/vendor/mongodb/mongodb/src/Database.php:206
 MongoDB\Database->createCollection() at /var/www/html/new-ups/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Schema/Blueprint.php:174
 Jenssegers\Mongodb\Schema\Blueprint->create() at /var/www/html/new-ups/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Schema/Builder.php:90
 Jenssegers\Mongodb\Schema\Builder->create() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/html/new-ups/database/migrations/2017_09_04_153824_create_ups_table.php:35
 CreateUpsTable->up() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:359
 Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:365
 Illuminate\Database\Migrations\Migrator->runMigration() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:177
 Illuminate\Database\Migrations\Migrator->runUp() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:146
 Illuminate\Database\Migrations\Migrator->runPending() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php:95
 Illuminate\Database\Migrations\Migrator->run() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php:69
 Illuminate\Database\Console\Migrations\MigrateCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/html/new-ups/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/html/new-ups/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/new-ups/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /var/www/html/new-ups/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /var/www/html/new-ups/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/new-ups/artisan:35

**Comment by salamex** [comment]
@jpldev  have u changed the down method at ur migration, making the Schema use mongodb connection?

**Comment by jpldev** [comment]
Hi! I don't use migrations anymore, because Mongo is schemaless. I've realized that I don't need migrations

Define your model and it's done.
