### ISSUE TITLE
An idea of the release date for Laravel 5.5?

### ISSUE THREAD

**Issue by pirmax** [jenssegers/laravel-mongodb#1291]
An idea of the release date for Laravel 5.5?

Thanks.

**Comment by jpldev** [comment]
It has been relesead on 30th August

https://laravel-news.com/category/laravel-5.5

**Comment by pirmax** [comment]
I have this error with a fresh Laravel 5.5 installation... It isn't been released :/

> Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::belongsToMany($related, $collection = NULL, $foreignKey = NULL, $otherKey = NULL, $relation = NULL) should be compatible with Illuminate\Database\Eloquent\Model::belongsToMany($related, $table = NULL, $foreignPivotKey = NULL, $relatedPivotKey = NULL, $parentKey = NULL, $relatedKey = NULL, $relation = NULL)

**Comment by dasbit** [comment]
+1

**Comment by grudge61** [comment]
+1

**Comment by jenssegers** [comment]
There are 2 PR's open, but both of them have failing tests. Would be nice if I could merge a PR to fix issues for 5.5 since I'm quite busy atm.

**Comment by pirmax** [comment]
Thank you for making fast ☺ Courage and luck!

**Comment by dasbit** [comment]
https://github.com/jenssegers/laravel-mongodb/pull/1282 what's wrong with this PR?

**Comment by matohavo** [comment]
+1

**Comment by thiagovictorino** [comment]
+1

**Comment by jpldev** [comment]
You need to replace red lines with green lines.

![image](https://user-images.githubusercontent.com/20649315/30275027-354cf0aa-96d6-11e7-85b8-a894efeec678.png)

Follow this link>
https://github.com/jenssegers/laravel-mongodb/pull/1295/commits/47ce0ff4ff07e7f05e3f4881ed1af64d2067b7dc

**Comment by thiagovictorino** [comment]
@jpldev I did what you said but now I got the error: 
`
[MongoDB\Driver\Exception\AuthenticationException]  
 auth failed
`

Have anyone idea what is going on?

**Comment by jenssegers** [comment]
I released an alpha tag.
