### ISSUE TITLE
MongoDB\Collection does not have a method update

### ISSUE THREAD

**Issue by johnboc** [jenssegers/laravel-mongodb#1292]
I am trying to upgrade a small project from
Laravel 4.2
PHP Version 5.6.25
jenssegers/mongodb dev-issue/count-0.0.3

to:
Laravel 5.4
PHP Version 7.0.10
jenssegers/mongodb 3.2

I have most of the code working but get an error when trying to update a collection. I get the following error:
_call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Collection' does not have a method 'update' in C:\Projects\projectupgrade\vendor\jenssegers\mongodb\src\Jenssegers\Mongodb\Collection.php:43_

I've looked at [https://github.com/jenssegers/laravel-mongodb/issues/734](https://github.com/jenssegers/laravel-mongodb/issues/734) and [https://github.com/alcaeus/mongo-php-adapter/issues/107#issuecomment-219393254](https://github.com/alcaeus/mongo-php-adapter/issues/107#issuecomment-219393254) but I'm struggling to see how to fix this.
Any input much appreciated.

**Comment by futurityverb** [comment]
How are you encountering the error in your code? You may need to change an `update()` call to `updateMany()` or `updateOne()` for the new mongo driver

**Comment by johnboc** [comment]
> You may need to change an update() call to updateMany() or updateOne() for the new mongo driver

Spot on. Many thanks that did the trick.

**Comment by moazam1** [comment]
@futurityverb @johnboc I am using following code but getting an error:

      $temp = [
		[ 'id' => 1 ],
		[
			'item'       => "envelopes",
			'id'         => 1,
			'test_field' => rand( 1000, 1000000 )
		]
	];

        $userData = DB::table( 'test' )->raw( function ( $collection ) use ( $temp ) {

		return $collection->updateMany( $temp, [ 'upsert' => true ] );
	} );

      InvalidArgumentException
      First key in $update argument is not an update operator
