### ISSUE TITLE
When can support V5.5

### ISSUE THREAD

**Issue by BrianBi** [jenssegers/laravel-mongodb#1297]
Many of the features are not fully compatible with 5.5. I hope  can support 5.5. At least one version is ok。
THS!!!

**Comment by eboye** [comment]
The temp workaround for me was to include the master branch and chery-pick these three commits: https://github.com/jenssegers/laravel-mongodb/pull/1282

It's working without issues for me.

**Comment by BrianBi** [comment]
@eboye Thank you very much for your answer！I give it a try

**Comment by RemiCollin** [comment]
Be aware these commits don't solve issues introduced with Laravel 5.5. I fixed some of them but some of the test aren't passing yet : https://github.com/jenssegers/laravel-mongodb/pull/1295

**Comment by BrianBi** [comment]
@RemiCollin Yes, I have tried to submit several versions, but there are still many problems.

**Comment by sagargulati** [comment]
@jenssegers  : any update on this?

**Comment by ciruvan** [comment]
@jenssegers I will send you flowers, a box of chocolate and also a love letter (if you wish) if you manage to update your awesome package to Laravel 5.5 any time soon. I know you're busy but boy, that would make my day.

**Comment by RemiCollin** [comment]
It seems https://github.com/jenssegers/laravel-mongodb/pull/1300 is fixing the issues. Guess we just need @jenssegers to merge & bump package version

**Comment by ciruvan** [comment]
@RemiCollin oh, didn't even notice. that would be fantastic.

**Comment by ciruvan** [comment]
@RemiCollin actually, I'm not so sure that PR really solves the issue. It seems to make some tests work by simply removing a lot of assertions. See [https://github.com/jenssegers/laravel-mongodb/pull/1300/commits/809c3a733096eb0749cd00c4272b4c4489421873#diff-86ff60326877dd9361acfa65b6cda5ce](url)

**Comment by RemiCollin** [comment]
Ah yes you're right... didn't watch in details.. I'll see if I can have my PR working soon, was nearly there but lack time

**Comment by sagargulati** [comment]
So what should we expect to happen?

**Comment by jenssegers** [comment]
I released an alpha tag.
