### ISSUE TITLE
retrieve nested children laravel query

### ISSUE THREAD

**Issue by jnorvor** [jenssegers/laravel-mongodb#1304]
What is the Laravel equivalent for retrieving a specific nested document/documents?

**Comment by ysb** [comment]
You can access child documents as an array. If there is another way, i want to learn too.

**Comment by jnorvor** [comment]
yes but that means you retrieve the data then pick what you want, as opposed to just retrieving the child documents at a specific id. Could I know the query you are talking about @ysb and also how to do what I am asking for if its at all possible

**Comment by ysb** [comment]
Yes, i am talking about retrieve the data and use the children.

Do you want to retrieve children without parent model?

**Comment by jnorvor** [comment]
yes

**Comment by styper** [comment]
I know this thread is old but I was trying to do the same thing and figured out a way

I don't think it's possible using Eloquent, as Eloquent always returns a Model or a Collection of Models.

However, this can be achieved with dot notation and accessing the collection directly. In my DB I have a collection 'test' as
![image](https://user-images.githubusercontent.com/22199797/66260965-0c5f5700-e79c-11e9-9569-f355c3f60d76.png)

So:
```
$result = DB::collection('test')->select(['nested_doc.field_i_want'])->get();
dump($result);
dump($result->pluck('nested_doc.field_i_want'));

$result = DB::collection('test')->project(['nested_doc.field_i_want' => 1, '_id' => 0])->get();
dump($result);
dump($result->pluck('nested_doc.field_i_want'));
```
![image](https://user-images.githubusercontent.com/22199797/66260948-d621d780-e79b-11e9-82c5-e0a88ad7d713.png)
