### ISSUE TITLE
$appends adding new field to DB on save

### ISSUE THREAD

**Issue by NGorco** [jenssegers/laravel-mongodb#1314]
If I'm doing save on model that have $appends field filled it calculates and saved also. But I wanted to achieve another behavior - got new fields only on selecting and returning REST-data.

**Comment by NGorco** [comment]
Was an error in logic. Sended data with $appends fields and then not modified nor cropped data pushed to server. Obviously, $appends would b there.

**Comment by ajaybhargav** [comment]
@NGorco Can you please tell me how to not save the appends field after it is loaded. Everytime I read document from DB and access the appends field and the new field also gets saved along with default document. How can I prevent it?

**Comment by ajaybhargav** [comment]
awesome 👍 
I added this and it worked perfectly. test is what I appended.

```
public function save(array $options = [])
{
	if (isset($this->test))
		unset($this->test);
	parent::save($options);
}
```
