### ISSUE TITLE
L5.5/v3.3.0-alpha "ERR_EMPTY_RESPONSE"

### ISSUE THREAD

**Issue by AndreasElia** [jenssegers/laravel-mongodb#1327]
Hello,

I just installed Laravel 5.5 and setup this package. I can connect to my mongo setup just fine but when I go to use a model which extends `Jenssegers\Mongodb\Eloquent\Model` I appear to be getting a grey chrome page with the error `ERR_EMPTY_RESPONSE`.

Any suggestions for possible solutions would be great 😄 

Model: [gist](https://gist.github.com/AndreasElia/01bc3c461c3054b847b9d6d2a8bae810)

Controller: `dd(\App\Site::all());`

**Comment by lpj145** [comment]
This package have some errors, yesterday illuminate/database upgrade to 5.5.3 and crash Model, the package needed usage with laravel, if not, you need add app function with anonymous class with function #978.

**Comment by kideny** [comment]
please tell me how to use alpha to composer.json

**Comment by fabpin** [comment]
me too

**Comment by AndreasElia** [comment]
@kideny @fabpin 
`"jenssegers/mongodb": "dev-master",`

**Comment by lpj145** [comment]
To fine works:
```
"illuminate/console": "^5.2.2",
        "illuminate/filesystem": "^5.2.2",
        "jenssegers/mongodb": "dev-master",
        "illuminate/database": "5.5.2",
        "illuminate/container": "5.5.2",
        "illuminate/pagination": "^5.2.2",
```

**Comment by kideny** [comment]
thank you everyone , i love you !
