### ISSUE TITLE
How to store the datetime by unix timestamp

### ISSUE THREAD

**Issue by robin520** [jenssegers/laravel-mongodb#1331]
I set the $dateFormat = 'U' is not work.

**Comment by nhanle92** [comment]
I personaly use `Carbon::now()->timestamp ` to save current time to Unix timestamp format.

**Comment by robin520** [comment]
@nhanle92 It wil still use mongotime to save the updated_at When I updated the document.

**Comment by dsalcedo** [comment]
Why not use 
```
use MongoDB\BSON\UTCDateTime;

new UTCDateTime('your date');

$modelResult = [
    'date'=> $obj['date']->toDateTime()
]
```

**Comment by ahren-condos-ca** [comment]
I had a similar problem. 
using the `protected $dates = ['entry_date'];` only worked for Date fields that where not nested.

This is the workaround I found that is now working for me. I created an Observer on "saving" of my model that casts any nested date fields using the below function and these then save in the correct format

```/**
     * Returns the date as required by dates format in MongoDB
     *
     * @param   string $date The string to check
     * @return  string
     */
    function get_mongo_date($date)
    {
        if ($date instanceof \MongoDB\BSON\UTCDateTime)
        {
            return $date;
        }
        else if ($date instanceof \Carbon\Carbon)
        {
            return new \MongoDB\BSON\UTCDateTime(new DateTime($date->toDateTimeString()));
        }
        else
        {
            return new \MongoDB\BSON\UTCDateTime(new DateTime($date));
        }
    }
```
