### ISSUE TITLE
Why this don't work?

### ISSUE THREAD

**Issue by josegustavo** [jenssegers/laravel-mongodb#1332]
Excuse me, I want to know why the find it by _id in array does not work, example:

`$query->where(['_id' => ['$in' => ['59d2f17b32f9eb1f2c0027c0','59d2f16a32f9eb1f2c0027be','59d2f10232f9eb1f2c0027b2']]]);`

Thanks

**Comment by vesper8** [comment]
have you tried

```
$query->whereIn('_id', ['59d2f17b32f9eb1f2c0027c0','59d2f16a32f9eb1f2c0027be','59d2f10232f9eb1f2c0027b2']);
```

**Comment by josegustavo** [comment]
It works, thanks!
