### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by doubtlymistaken** [jenssegers/laravel-mongodb#1335]
hai im havin issues with pagination, 
this code works fine  
$perangkats = perangkatModel::paginate(1);
        return view('inven.home',['perangkats'=>$perangkats]);

but when i called {{ $perangkats->links() }} 
it saids Call to undefined method Jenssegers\Mongodb\Query\Builder::links()

**Comment by doubtlymistaken** [comment]
KONTOLAL

**Comment by mashurimansur** [comment]
try using {{ $perangkats->render() }}

**Comment by doubtlymistaken** [comment]
@mashurimansur hey im already done with my paging. now my problem is how can i do my pagination with sorting. im trying this code
$perangkats = perangkatModel::simplePaginate(10)->sortBy('tahun');

but i get error


Method links does not exist. (View: C:\xampp\htdocs\kominfo\resources\views\durab\durability.blade.php)
--
in Macroable.php (line 74)

**Comment by ysb** [comment]
Hi,

Did you try this?

```php
$perangkats = perangkatModel::sortBy('tahun')->simplePaginate(10);
```
