### ISSUE TITLE
Help - anyone manage to get jenssegers / mongodb working in userfrosting yet?

### ISSUE THREAD

**Issue by marcustan138** [jenssegers/laravel-mongodb#1342]
Hi, any one manage to get this working in userfrosting yet?

Should I be using the capsule method?  Any example?

**Comment by alexweissman** [comment]
In UF 4.1, you should be able to just override the default `db` service, and replace the `foreach` loop that adds the connections with something like:

```
foreach ($config['db'] as $name => $dbConfig) {
    if ($dbConfig['driver'] == 'mongodb') {
        $capsule->getDatabaseManager()->extend($name, function ($dbConfig) {
            return new Jenssegers\Mongodb\Connection($dbConfig);
        });
    } else {
        $capsule->addConnection($dbConfig, $name);
    }
}
```

**Comment by marcustan138** [comment]
Tried that but it will report SQL error.  From the flow, it seems that jenssengers mongodb was not invoked at all.  Mongodb underlying query syntax apparently not the same as SQL.

**Comment by alexweissman** [comment]
Well, my impression of this library is that it should be generating Mongo queries, not SQL.  So, my guess is there is still something wrong in the way you're setting up your `db` service in UF.  

At any rate, we shouldn't clutter this project's issue tracker with usage questions - let's continue debugging your setup in chat.
