### ISSUE TITLE
When is this package compatible with Laravel 5.5?

### ISSUE THREAD

**Issue by disto** [jenssegers/laravel-mongodb#1346]
When is this package compatible with Laravel 5.5?
thx

**Comment by robsoncombr** [comment]
+1

**Comment by Zaknfn** [comment]
+1

**Comment by gazben** [comment]
https://github.com/jenssegers/laravel-mongodb/releases/tag/v3.3.0-alpha

We should test it out

**Comment by Zaknfn** [comment]
Thanks 👏
