### ISSUE TITLE
Cannot aggragate sum

### ISSUE THREAD

**Issue by adnanfajr** [jenssegers/laravel-mongodb#1353]
Here is my code : 
$str_uang = Investor::where('project_id', $id)->sum('nominal');

It can't get sum value, just sum function while count is working.
What happened?
Is it because I save 'nominal' value as a string in a collection?

Btw how can I save 'nominal' value type as double, not a string

**Comment by mkumarjha** [comment]
yes you have save it as string that's why i have faced same issue.

**Comment by nemesisKO** [comment]
you should change the filed to integer or double type with shell command first

    db.collection.updateMany({}, [ {$set:{ "total_value_usd" : {$toDouble: 
    "$total_value_usd"}}} ], {multi:true})
