### ISSUE TITLE
Overriding $primaryKey does not work with find($id)

### ISSUE THREAD

**Issue by jim5359** [jenssegers/laravel-mongodb#1354]
I get the error:
Undefined index: myId in /Jenssegers/Mongodb/Query/Builder.php:575

It looks like the Builder class is hard-coded to expect the key as _id:

`return $sequence == '_id' ? $result->getInsertedId() : $values[$sequence];`

This causes problems when doing a find($id) when you've modified the primaryKey to be something else in the model class.

`public $primaryKey = 'myId';`

I'm using the latest master version using PHP7 and Mongo 3.4

**Comment by jim5359** [comment]
Actually, I tried hacking that file and got rid of the error, but now it's just ignoring the $primaryKey setting.  So looks like this capability is broken in the latest version.

**Comment by DMNSteve** [comment]
@jim5359 the fix in #1392 should solve your problem :)

**Comment by jim5359** [comment]
Awesome @DMNSteve !
