### ISSUE TITLE
about disconnection function

### ISSUE THREAD

**Issue by MrVidon** [jenssegers/laravel-mongodb#1359]
I see the source about disconnection the mongodb client
[https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Connection.php#L147](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Connection.php#L147)
why not use`MongoClient::close()` to close the connection instead of `unset`?
my mongdb server set maxConnections.  
when I run the laravel program, i use `db.serverStatus().connections` the count is always growing up, I guess  the reason is `unset` don't close the connection.

**Comment by zhong-shizeng** [comment]
me too

**Comment by MrVidon** [comment]
@zhong-shizeng how to fix it?

**Comment by Magiweb** [comment]
Sorry to revive an ancient issue, but it's still valid and I'm curious to understand why it was changed from ->close() to unset()? I've tried to find a way to at least be able to call the ->close() method directly from the object, but haven't found a way to do it. 

Any guidance / explanation etc. would be appreciated.

**Comment by divine** [comment]
Hello,

There is no possibility to close connection so closing it for now.

See https://github.com/mongodb/mongo-php-driver/issues/739

Thanks.
