### ISSUE TITLE
Many to many relationship not working?

### ISSUE THREAD

**Issue by benwrigley** [jenssegers/laravel-mongodb#1363]
Hi, I've two collections that have a many to many relationship. The 'parent' has 13,000 documents and the 'child' has about 20. I'm storing the foreign keys in the parent document only  (as I don't want arrays 000s long in the child document).

I've set up the belongsToMany methods on each Model.

I get an empty collection back when I call parent->children(). Do I need to store the parent keys in the child document to make this work?

Thanks

**Comment by Oleg-Arkhipov** [comment]
Yes, it works only that way. You can just check the query which is made when you call `$parent->children`, it is something like:
```
children.find({"parent_ids":"parent_object_id_here"}
```
