### ISSUE TITLE
hasmany not working

### ISSUE THREAD

**Issue by nikhildeshmukh** [jenssegers/laravel-mongodb#1367]
Project Model
class Project extends Model {
    use HybridRelations;
    protected $connection = 'mysql';

}

public function tasks() {
            //return $this->hasMany(Taskm::class,'projectID','id');
        //return $this->hasMany(Taskm::class,'projectID','id');
        return $this->hasMany('App\Taskm', 'projectID');

    }

Taskm model
namespace App;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Taskm extends Eloquent {

    protected $connection = 'mongodb';
    protected $collection = 'tasks';

    public function project()
    {
        return $this->hasOne(Project::class,'id','projectID');

    }

Projects is on mysql
tasks are in mongodb with task collections with id projectID

Can anyone let me know what am i doing wrong ?

**Comment by mdandidarmawan** [comment]
Still was an issue.
