### ISSUE TITLE
Call to undefined method MongoDB\Driver\ReadConcern::isDefault()

### ISSUE THREAD

**Issue by mo7ammadrashidi11** [jenssegers/laravel-mongodb#1368]
![6](https://user-images.githubusercontent.com/25270296/32989212-52dcdc52-cd27-11e7-8a99-c7069143e24c.png)
I really don't know what the problem is!

**Comment by kamihouse** [comment]
Hi @mo7ammadrashidi11, see this: https://github.com/mongodb/mongo-php-library/issues/412#issuecomment-346107357
