### ISSUE TITLE
Composer install failed due to dependency requirements

### ISSUE THREAD

**Issue by ultraN** [jenssegers/laravel-mongodb#1369]
Environment:
laravel 5.4.36
php 7.1
mongodb/mongodb 1.1.2
jenssegers/mongodb v3.2.3

Reproduction:
composer require jenssegers/mongodb:3.3.1

Output:

  Problem 1
    - Installation request for jenssegers/mongodb 3.3.1 -> satisfiable by jenssegers/mongodb[v3.3.1].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - jenssegers/mongodb v3.3.1 requires illuminate/events ^5.5 -> satisfiable by illuminate/events[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/events v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/events v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/events v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/events v5.5.2|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].

Description:
Well, seems like the latest package doesn't support laravel 5.4 anymore.

**Comment by D3nnisH** [comment]
indeed: https://github.com/jenssegers/laravel-mongodb/pull/1300/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R17

**Comment by ultraN** [comment]
@D3nnisH Any plan to fix?

**Comment by D3nnisH** [comment]
This cannot be "fixed" in code, the only 2 possible fixes are:
- upgrading to Laravel 5.5
- staying at jenssegers/mongodb v3.2.3 or below

**Comment by ultraN** [comment]
@D3nnisH Ok, good to know. But can you highlight this significant breaking change on the main description page? So people can see it straight away.

**Comment by ultraN** [comment]
Intended breaking change, no need for fix.

**Comment by D3nnisH** [comment]
someone already had this idea :smirk:  https://github.com/jenssegers/laravel-mongodb/pull/1364/files
