### ISSUE TITLE
How can I query into collections which have relations

### ISSUE THREAD

**Issue by mehrud** [jenssegers/laravel-mongodb#1380]
I have a collection named `users`, and another collection called `books`, relationship methods are defined in which a `user` may have many `books`. I would like to find all `books` for a specific `user` with an `email`. Is there any way I can make such a query?

**Comment by D3nnisH** [comment]
```
class User extends Model { 
    ...
    public function books() {
        return $this->hasMany(Book::class);
    }
}
```

`User::where('email', $email)->with('books')->firstOrFail()->books`
