### ISSUE TITLE
Repository support

### ISSUE THREAD

**Issue by NoelDeMartin** [jenssegers/laravel-mongodb#1389]
I have been using this project for a long time in different projects, and I have now decided to stop using it and either search for an alternative or implement laravel / mongo integration from scratch. It really is a shame, because the community on this project is quite active. I understand the maintainers may not have any time to dedicate to an open source project, but the least they could do is accept PRs which make sense in a sensible amount of time (or at least say why they are rejected). Some of them have been open for months now without any presence of the maintainers.

Is there a way we (the community) can help in some way, other than doing PRs? Because I really feel like this could be an awesome addition to the Laravel ecosystem, but in my opinion it's too unstable at the moment.

**Comment by DMNSteve** [comment]
We use this project across a lot of our production applications. We have explored other Laravel MongoDB implementations and have found that they seem to also become a little inactive after a period of time. This project does have a great community and is generally quite active.

As @NoelDeMartin said, if there is anyway that we as part of the community can help, we'd be keen to do what we can.

**Comment by divine** [comment]
Hello and sorry for late reply!

We're as community trying to help out this library on fixes and new features. Most of the issues has been closed and PRs merged as well new version released.

We kindly ask you for your help [here ](https://github.com/jenssegers/laravel-mongodb/issues/1974)

Thanks!
