### ISSUE TITLE
Foreignkey in embeded collections and join operation

### ISSUE THREAD

**Issue by Ojvar** [jenssegers/laravel-mongodb#1391]
Hi guys
I faced with a problem.
I have below tables (or collections):
  1:  "users" -> {id, name}
  2:  "committees" -> {id, title, members[]}
       2-1: "members[]" -> {user_id}                  <--- It keep only users id (just like as pivot table)

example:
```

users:
  id    |  name
----------------------------------------------------
  1     |  Alex
  2     |  John

committees:
  id    |  title                       |  members
----------------------------------------------------
  1     |  Park Committee   |  { 1, 2 }
  2     |  Pool Committee   |  { 2 }

```

And now, my question is, How can I get list of committees with "users names" instead of "users ids"

I except such result: 
```

{ id: 1, title: 'Park Committee', members: [{id: 1, name: 'Alex'}, {id: 2, name: 'John'}]},
{ id: 2, title: 'Pool Committee', members: [{id: 2, name: 'John'}]},
```

And another question:
I just need to store users' "id" field into embed collection, How?

Tnx

**Comment by harrysbaraini** [comment]
What you want is not embedMany but HasMany. HasMany will store only users' ids, then when you call $comittees->members you will get the info you need.

**Comment by Ojvar** [comment]
Hi harry
I want to save just Foreign Keys in embedded record,
Let me to describe what I want:

I have these collections:

1- **Posts** collection (store Authors posts)
2- **Users** collections (store Users)
3- **Comments** collections (store comments of users)

Now, I want to save Posts comments in a embedded record, and it has such structure:

```
{
   _id,
  created_at,
  **user_id,**          // <-------- Must be in relation with **Users** table
  comment
}
```

I can store data in such case, But I can't Make a relation between **Users** collection and **user_id** field.
How can I do that?

Tnx ;)

**Comment by harrysbaraini** [comment]
Hi!

IMO, you described another situation now. Let's see both.

**First question**

You don't need a Member model to act as a pivot, in your Committee model you just have to do:

```
class Committee extends Mode
{
    ...

   public function members(): HasMany
  {
    return $this->hasMany(User::class);
  }
}
```

The library will automatically add a `members_ids` in the committee document on MongoDB.

---

** Second question (posted in your reply)**

I would not save comments as embeds. At any given moment your post may have so many comments that you'll have a headache.

I would have a collection specific for comments, then use a HasMany relation on posts. The Comment model has a belongsTo relation to Users.

```
class User extends Model
{
    protected $fillable = [
        'name',
        'email',
    ];

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    public function posts(): HasMany
    {
        return $this->hasMany(Post::class);
    }
}

// ---

class Comment extends Model
{
    protected $fillable = [
        'content',
    ];
    
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
    
    public function post(): BelongsTo
    {
        return $this->belongsTo(Post::class);
    }
}

// ---

class Post extends Model
{
    protected $fillable = [
        'title',
        'content',
        'tags',
    ];
    
    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
    
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }
}
```

Let me know if it's not what you're trying to solve.
