### ISSUE TITLE
Advanced Where Attempt: Cannot use object of type Jenssegers\Mongodb\Eloquent\Builder as array

### ISSUE THREAD

**Issue by acidjazz** [jenssegers/laravel-mongodb#1393]
I'm trying an Advanced query from the example [here](https://github.com/jenssegers/laravel-mongodb#query-builder)

```php
$items = $items->where(function($query) {
  $query
    ->where('title', 'regex', new \MongoDB\BSON\Regex(preg_quote($search), 'i'))
    ->orWhere('description', 'regex', new \MongoDB\BSON\Regex(preg_quote($search), 'i'));
});
```
And I get the error:

```
Symfony\Component\Debug\Exception\FatalThrowableError thrown with message "Cannot use object of type Jenssegers\Mongodb\Eloquent\Builder as array"
```
The stack trace goes directly to this code on the line `->where` inside the function

**Comment by DMNSteve** [comment]
Can you just confirm what version of the library you are using, please.

Can you also paste the full error response as well? Thanks

**Comment by acidjazz** [comment]
I'm unable to produce this error anymore, apologies, closing.
