### ISSUE TITLE
embedsMany Relation, need help

### ISSUE THREAD

**Issue by ghost** [jenssegers/laravel-mongodb#1394]
Hello guys,

I'm currently trying to build an embedsMany relation between elements (Component and Part) but I can't get it to work.

I've been trying the eager loading, has shown in the documentation [here](https://laravel.com/docs/5.5/eloquent-relationships#eager-loading).

Let me show you my code : 

```
namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class Component extends Model
{

    protected $connection = 'mongodb-cld';

    protected $collection = 'components';

    protected $primaryKey = 'id_component';

    public function part()
    {
        return $this->embedsMany('App\Models\Part', 'ids');
    }

}
```

```
namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class Part extends Model
{

    protected $connection = 'mongodb-cld';

    protected $collection = 'parts';

    protected $primaryKey = 'id_part';

}
````

My data :
**components**
```
{
    "_id" : ObjectId("5a44ad735a24c79140f66e8a"),
    "id_component" : 1,
    "name" : "first component",
    "ids" : [ 
        2, 
        4
    ]
}

{
    "_id" : ObjectId("5a44ad735a24c79140f66e8b"),
    "id_component" : 2,
    "name" : "second component",
    "ids" : []
}

{
    "_id" : ObjectId("5a44ad735a24c79140f66e8c"),
    "id_component" : 3,
    "name" : "third component",
    "ids" : [ 
        1
    ]
}
````

**parts**
```
{
    "_id" : ObjectId("5a44adcb5a24c79140f66e8d"),
    "id_part" : 1,
    "name" : "first part"
}

{
    "_id" : ObjectId("5a44adcb5a24c79140f66e8e"),
    "id_part" : 2,
    "name" : "second part"
}

{
    "_id" : ObjectId("5a44adcc5a24c79140f66e8f"),
    "id_part" : 3,
    "name" : "third part"
}

{
    "_id" : ObjectId("5a44adcc5a24c79140f66e90"),
    "id_part" : 4,
    "name" : "fourth part"
}

{
    "_id" : ObjectId("5a44adcc5a24c79140f66e91"),
    "id_part" : 5,
    "name" : "fifth part"
}
```

And finally, my call and the result : 

```
$components = Component::with('part')->get();

foreach ($components as $component) {
      dump($component->part);
}
```

And what I get : 

![capture d ecran 2017-12-28 a 09 57 15](https://user-images.githubusercontent.com/34089378/34405777-8339a662-ebb5-11e7-946c-a38334fd9600.png)

As you can see, I'm having each Component with every Part (that's good so far) but the attributes are all missing. I'm probably missing something but .. I can't see what !

Any help would be much appreciated :)

Laravel 5.5.14
laravel-mongodb 3.3.1

**Comment by Wachsmann** [comment]
Having the same problem here. But the embedsOne works fine.

**Comment by naonak** [comment]
Same for me. Someone can help ? Thanks !

**Comment by brusin** [comment]
Up pls ? :)

**Comment by petronetto** [comment]
I'm sure that this is not the best approach, but will work.

```php
$components = App\Models\Component::get();

$parts = collect([]);
foreach ($components as $component) {
    $parts->push($component->parts);
}

return $parts->flatten();
```

**Comment by brusin** [comment]
Thx @petronetto I'll give a try asap and let you know.
Do you confirm a bug in the EmbedsMany relation ?

**Comment by petronetto** [comment]
I don't think that is a bug. If that query makes sense for you, and you will use it in more places in your code, maybe you should use a different data structure. It is almost certainly supposed to be a first-level citizen instead.

**Comment by bzbislawski** [comment]
I have the same problem with latests version of this library and laravel 5.8

**Comment by tguyonnet** [comment]
up ?

**Comment by jvors88** [comment]
same
