### ISSUE TITLE
How use unix domain sock connected?

### ISSUE THREAD

**Issue by gzanthony** [jenssegers/laravel-mongodb#1396]
i try in databases.php confinure:
'mongodb' => [
            'driver' => 'mongodb',
            'dsn' => env("MONGODB_DSN", "mongodb://sqpon:123123@/datas/run/mongodb/mongodb-27017.sock:0"),
            'database' => env('MONGODB_DATABASE', 'sqpon')
        ],

but it popup a error like:
[2018-01-05 21:40:02] product.ERROR: Failed to parse MongoDB URI: 'mongodb://sqpon:f1041Jn6gS4@/datas/run/mongodb/mongodb-27017.sock'. Invalid host string in URI. {"exception":"[object] (MongoDB\\Driver\\Exception\\InvalidArgumentException(code: 0): Failed to parse MongoDB URI: 'mongodb://sqpon:123123@/datas/run/mongodb/mongodb-27017.sock'. Invalid host string in URI. at /home/datas/apps/dat/web/working/sqpon_v2/vendor/mongodb/mongodb/src/Client.php:83)

so how to use a unix domain sock ? 
thanks for you helping.

**Comment by DMNSteve** [comment]
Looks like the driver is expecting a url encoded dsn string.

Do you have any luck with using `mongodb://sqpon%3A123123%40%2Fdatas%2Frun%2Fmongodb%2Fmongodb-27017.sock%3A0`?

**Comment by gzanthony** [comment]
thanks for you help, but it not work.

**Comment by gzanthony** [comment]
laravel database config i have try this

        'mongodb' => [
            'driver' => 'mongodb',
            'dsn' => 'mongodb://' . rawurlencode('sqpon:f1041Jn6gS4@/datas/run/mongodb/mongodb-27017.sock:0'),
            'database' => env('MONGODB_DATABASE', 'sqpon'),
        ],

it's not work too, any idea where is error ??

**Comment by robbytaylor** [comment]
@gzanthony You may want to edit your last reply to remove the password.

Can you share a screenshot of the error you're getting?

**Comment by gzanthony** [comment]
thanks for you remine, the password not important.
here is my demo site.
http://demo.sqpon.bokmanli.com/test

now my config is my last post.

**Comment by camohub** [comment]
Hi do you have a solution of this issue?
Thanks.
