### ISSUE TITLE
dates array only works on root of JSON document does not work on 'parent.child' format

### ISSUE THREAD

**Issue by ajaybhargav** [jenssegers/laravel-mongodb#1399]
I have a JSON document to be stored where datetime is currently sent in unix timestamp format. e.g.

```
{
"uid": "1735010011468",
"info": {
"dt": 1455984596,
"msgid": 11720,
}
}
```

Dates array I have defined as follows:
`protected $dates = ['data.info.dt'];`

Before storing I have updating dt to UTCDateTime so that it gets stored properly
```
$data['info']['dt'] = new \MongoDB\BSON\UTCDateTime($request->info['dt'] * 1000);
$newdata->data = $data;

```
Document gets stored properly:
"dt" : ISODate("2016-02-20T16:09:56.000Z"),

But when I fetch the data, dt is not a carbon instance instead its Unix Timestamp * 1000.

However, If I keep date time outside in root of JSON document, everything works as expected e.g.
`$newdata->datetime = $data['info']['dt'];`

and dates array updated to
`protected $dates = ['data.info.dt', 'datetime'];`

Everything works fine, datetime is returned as Carbon instance now.

Please tell me where possibly things are going wrong or its something to do with this repository which is not implemented yet??

**Comment by ahren-condos-ca** [comment]
I had the same problem. 
using the `protected $dates = ['entry_date'];` only worked for Date fields that where not nested.

This is the workaround I found that is now working for me. I created an Observer on "saving" of my model that casts any nested date fields using the below function and these then save in the correct format

`/**
     * Returns the date as required by dates format in MongoDB
     *
     * @param   string $date The string to check
     * @return  string
     */
    function get_mongo_date($date)
    {
        if ($date instanceof \MongoDB\BSON\UTCDateTime)
        {
            return $date;
        }
        else if ($date instanceof \Carbon\Carbon)
        {
            return new \MongoDB\BSON\UTCDateTime(new DateTime($date->toDateTimeString()));
        }
        else
        {
            return new \MongoDB\BSON\UTCDateTime(new DateTime($date));
        }
    }`

**Comment by dzhiryakov** [comment]
Confirm a problem

```php
protected $dates = ['export.system.uploaded_at'];
```

Input data:

```json
{
    "export" : {
        "system" : {
            "uploaded_at" : "2018-01-01 12:00:00"
        }
    }
}
```

Saved in collection:
```json
{
    "export" : {
        "system" : {
            "uploaded_at" : "2018-01-01 12:00:00"
        }
    }
}
```

How it must be:
```json
{
    "export" : {
        "system" : {
            "uploaded_at" : ISODate("2018-01-10T12:00:00.000Z")
        }
    }
}
```

Problem only for nested fields
