### ISSUE TITLE
the result return blank object, but in actual there is data available

### ISSUE THREAD

**Issue by yatinPatel13490** [jenssegers/laravel-mongodb#1400]
Hi, 
I used laravel-mongodb("jenssegers/mongodb": "3.2.x",) with laravel 5.4 ,
the configration is:

 'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('MONGO_HOST', '127.0.0.1'),
            'port' => env('MONGO_PORT', '27017'),
            'database' => env('DB_DATABASE', 'test_mongo'),
        ],

and 

// $result = \DB::connection('mongodb')->collection('book')->find('513d66b6ce5858205100001f');
when I print the result is shows me:

Illuminate\Support\Collection Object
(
    [items:protected] => Array
        (
        )

)

but in actually there is data available I export the data in json here is sample:
{"_id":{"$oid":"513d66b6ce5858205100001f"},"uid":"4374","gid":0, ...}

I do not understand what is the issue. Please help me out.

thanks in advance

**Comment by D3nnisH** [comment]
I think the exported Data should look like this to be found by Laravel:
`{"_id":ObjectId("513d66b6ce5858205100001f"),"uid":"4374","gid":0, ...}`
