### ISSUE TITLE
how to use $divide (aggregation)  in jenssegers/mongodb

### ISSUE THREAD

**Issue by jetamooz** [jenssegers/laravel-mongodb#1401]
hi every body
i want to  Divides one number by another and returns the result. Pass the arguments to $divide in an array.
mongobd has $divide (aggregation)
but i can not find $divide  in[ jenssegers/mongodb](https://jenssegers.com/projects/laravel-mongodb)

i also check moloquent but i can not find divide function
https://moloquent.github.io/master/advanced/#schema

we can see this function that define in mongodb.com in [this url ](https://docs.mongodb.com/manual/reference/operator/aggregation/divide/)

please help me
how i can use divide function in laravel with jenssegers package ??

**Comment by LucasLeandro1204** [comment]
Did u solved this issue? @jetamooz 

I'm having trouble when I use $query->project with paginate
