### ISSUE TITLE
Error - Call to a member function all() on array

### ISSUE THREAD

**Issue by mainawycliffe** [jenssegers/laravel-mongodb#1402]
Hi, I am receiving the following error **Call to a member function all() on array** when i call eloquent methods such as all(), get() etc. I am using Slim PHP v3 with jenseegers/mongodb vs 3.3. Here is a list of my composer dependents: 

```
        "doctrine/cache": "^1.6",
        "cocur/slugify": "^2.5",
        "slim/slim": "3.7",
        "slim/http-cache": "^0.3.0",
        "phpmailer/phpmailer": "^5.2",
        "respect/validation": "^1.1",
        "firebase/php-jwt": "^5.0",
        "illuminate/pagination": "^5.5",
        "nesbot/carbon": "^1.22",
        "jenssegers/mongodb": "^3.3"
```

This is my connection using capsule:

```
$capsule = new \Illuminate\Database\Capsule\Manager;
$config = $container['settings']['mongodb'];
$capsule->addConnection($config);
$capsule->getDatabaseManager()->extend('mongodb', function ($config) {
    return new Connection($config);
});
$capsule->setAsGlobal();
$capsule->bootEloquent();
$container['db'] = function ($container) use ($capsule) {
    return $capsule;
};
```

And here is my master model:
```
use Jenssegers\Mongodb\Eloquent\Model;

class appModel extends Model
{
    const CREATED_AT = 'dateCreated';
    const UPDATED_AT = 'dateModified';
}

```
Here is the code that throws the error 

` $user = users::where('email', 'emailadd@gmail.com')->get();`

![capture](https://user-images.githubusercontent.com/12270550/34682581-5b7fd476-f4b0-11e7-856a-43205b8b7c23.PNG)

**Comment by xemose** [comment]
I'm having the same issue, did you find a solution?

**Comment by MainaWycliffe** [comment]
I can't recall exactly what I did but I went back to my code and I seem to have re arranged the order of the code, so that 

`$capsule->addConnection($config);`

Comes after:

```
$capsule->getDatabaseManager()->extend('mongodb', function ($config) {
    return new Connection($config);
});
```

Instead of before it. The whole code looks like this:

```
$capsule->getDatabaseManager()->extend('mongodb', function ($config) {
    return new Connection($config);
});
```

**Comment by xemose** [comment]
That doesn't seem to work for me hm

**Comment by xemose** [comment]
The solution I found is this

```
use Illuminate\Database\Capsule\Manager as Capsule;

Capsule::connection('mongodb')->collection('default')->where('_id', '=', $ID)->get();
```
