### ISSUE TITLE
Query Caching Call to undefined method Jenssegers\Mongodb\Query\Builder::remember()

### ISSUE THREAD

**Issue by linkev21** [jenssegers/laravel-mongodb#1405]
Hello,

I try to use cache functionnality but I got this error.

The cache functionnality does'nt work for this lib ?

I use Laravel 5.5 and jenssegers driver 3.3.1.

Thank you,

**Comment by BurpyDelivers** [comment]
Can you please fix this.

**Comment by tuandm** [comment]
Laravel dropped query caching since 5.0:
```
Eloquent Caching
Eloquent no longer provides the remember method for caching queries. You now are responsible for caching your queries manually using the Cache::remember function.
```
https://laravel.com/docs/5.1/upgrade#upgrade-5.0

I think we should follow this update of Laravel framework. Manual caching is more suitable for DB queries while it's manageable and easy to clear individual cache by key
