### ISSUE TITLE
Saving embedsMany relationship to multiple models not working as expected

### ISSUE THREAD

**Issue by matthewerskine** [jenssegers/laravel-mongodb#1406]
Hi, I'm experiencing some unexpected behaviour with the the `embedsMany` style relationship.

```php
public function test_it_can_get_for_user()
    {
        $userA = factory(User::class)->make(['name' => 'John']);
        $userB = factory(User::class)->make(['name' => 'Jane']);

        // (Seems we have to save() the model before it will store any relations...)
        $journalA = tap(factory(Journal::class)->create())->save();
        $journalB = tap(factory(Journal::class)->create())->save();

        $journalA->users()->saveMany([$userA, $userB]);
        $journalB->users()->saveMany([$userA, $userB]);

        // No 'users' in $journalB.
        dd($journalA->toArray(), $journalB->toArray());
     }
```

Here's the output I get from simple test above.

![screen shot 2018-01-16 at 10 08 27](https://user-images.githubusercontent.com/7579504/34983377-373f33fe-faa5-11e7-9668-d81ba782d479.png)

As you can see the users are only saving for the first model, is this expected behaviour? How can I store the users against both of the journal records?

Thanks.

**Comment by marlongichie** [comment]
+1 Also experiencing this issue. Were you able to figure this out @matthewerskine ?

**Comment by pkpk520** [comment]
Try use setAttributes( $key, $value ) like this :

$journalA->setAttribute( "users", [ $userA->toArray(), $userB->toArray() ]);
