### ISSUE TITLE
"Class 'MongoDB\Driver\Manager' not found"

### ISSUE THREAD

**Issue by ghost** [jenssegers/laravel-mongodb#1407]
I am new to the framework and wanted to use MongoDB for my application. Used composer to pull the package, used query builder to check if it's working and the error was "Manager class could not be found". Checked the vendor/mongodb/mongodb/src path but couldn't find a directory named Driver. Can somebody help? Thanks!
PS: The service provider has been configured.

**Comment by StevePorter92** [comment]
Worth having a look at these issues here:

https://github.com/jenssegers/laravel-mongodb/issues/1358
https://github.com/jenssegers/laravel-mongodb/issues/761
https://github.com/jenssegers/laravel-mongodb/issues/1163

Do you have the mongo php drivers installed?
https://docs.mongodb.com/ecosystem/drivers/php/
