### ISSUE TITLE
'MongoResultException' with message '127.0.0.1:27017: The 'cursor' option is required

### ISSUE THREAD

**Issue by surajde16** [jenssegers/laravel-mongodb#1412]
Hello,
I am using laravel 5.2 with jensegers mongodb 2.2

Am getting this error.
 exception 'MongoResultException' with message '127.0.0.1:27017: The 'cursor' option is required, except for aggregate with the explain argument' in /var/www/html/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php:42

The same code works in my localhost.

Server is Ubuntu 14.04 with apache, PHP 5.6.33 and mongodb driver 1.6.16.

Please let me know if you need any other data from me.

thank you

**Comment by surajde16** [comment]
Hello All,
The issue is solved. I had to downgrade the Mongo DB version from 3.6 to 3.4

**Comment by JoyG42** [comment]
Is there any way to solve it with keep using MongoDB 3.6

**Comment by surajde16** [comment]
@JoyG42 probably you should update jenssegers/mongodb version but again for that you need to update laravel framework version.
