### ISSUE TITLE
$withCount return Illegal offset type

### ISSUE THREAD

**Issue by HassanIbrahim** [jenssegers/laravel-mongodb#1416]
I get the `Illegal offset type` error with `protected $withCount = ['replies']` or `Post::withCount('replies')`.

Any fix soon?

**Comment by HassanIbrahim** [comment]
Solved by Appending and Accessor

`  protected $appends = ['RepliesCount'];`

` public function getRepliesCountAttribute()
    {
        return $this->replies->count();
    }`

**Comment by alexjose** [comment]
Please reopen this issue the workaround by making it an accessor will not help eager loading. 

`withCount` should be the proper way to do this.

**Comment by HassanIbrahim** [comment]
@alexjose done.
