### ISSUE TITLE
Laravel 5.5.3 feilds not creating

### ISSUE THREAD

**Issue by vignesh007vicky** [jenssegers/laravel-mongodb#1424]
I'm new using this jenssegers/laravel-mongodb

1.I have implemented Jwt auth and jenssegers/laravel-mongodb in my laravel5.5.33 pack
2.I have deleted default migration files given by laravel and created two new migration files 
   i)users
   ii)password resets
3.when i migrate the files two migrations created and in db also two collections created but not all feilds are created
   **i)password filed of type string not created this is an issue** 

**_4.migration rollback fails on these two migration files_**

these below are my files
** users migration**
use Illuminate\Support\Facades\Schema;
use Jenssegers\Mongodb\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreateUserCollection extends Migration
{
   /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $collections) {
            $collections->increments('id');
            $collections->string('name');
            $collections->string('email')->unique();
            $collections->string('password');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}

**forgot password**

use Illuminate\Support\Facades\Schema;
use Jenssegers\Mongodb\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreatePasswordResetCollections extends Migration
{
     /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('password_resets', function (Blueprint $collections) {
            $collections->string('email');
            $collections->string('token');
            
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('password_resets');
    }
}

**User Modal**

namespace App;
use App\User;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use DB;

/*class User extends Authenticatable
{
    use Notifiable;

   
    protected $fillable = [
        'name', 'email', 'password',
    ];

    
    protected $hidden = [
        'password', 'remember_token',
    ];
}*/

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

    class User extends Eloquent
    {
        protected $connection = 'mongodb';
        protected $collection = 'users';
        public static function userslist($params)
    {
        $users = User::all();

        return $users;
    }

    public static function userscreate($params)
    {
        /*$b = User::create([ 'name' => $params['name'],'email' => $params['email'] ]);*/

         $newuser = new User;
         $newuser->name = $params['name']; 
         $newuser->email = $params['email'];
         $newuser->save();

        return true;
    }

    public static function usersupdate($params)
    {
       $user = DB::collection('users')->where('_id', $params['_id'])
                       ->update(['name'=> $params['name'],
                                'email'=> $params['email']
                        ]);

        return $user;
    }

     public static function usersdelete($params)
    {
        $delete=DB::collection('users')->where('_id', $params['_id'])->delete();
        return $delete;
    }

    }

**Comment by harrysbaraini** [comment]
Migrations are not really needed when you work with Mongodb. I see usage for them only when you need to set indexes and stuff like that.

Did you create an user and checked on your Mongo database if the password is present there? When you consume an User's data (e.g. `$user->toArray()`), you don't see password because it is included in `hidden` property of your `User` model.

And another tip:

You can replace `DB::collection('users')->` with `static::` or `self::`. For example:

```php
public static function usersdelete($params)
{
    return static::where('_id', $params['_id'])->delete();
}
```

Anyway, I would rather move this kind of code to an external class, like a Repository or Service. If you want to separate Business logic from Persistance layer, move it out to a service/repository class. Otherwise, yuo could just do `User::findOrFail($id)->delete()`.

**Comment by vignesh007vicky** [comment]
thanks @harrysbaraini  

I have solved this issue 

the password is in the hidden property, i just removed from the array its just worked fine.
