### ISSUE TITLE
how to implement jwt auth with enssegers/laravel5.5.3-mongodb

### ISSUE THREAD

**Issue by vignesh007vicky** [jenssegers/laravel-mongodb#1425]
Laravel 5.5.3

when i post name and passwords in postman this is the error im getting

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function prepare() on null
   
Symfony\Component\Debug\Exception\FatalThrowableError 
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php326

please help..

**Comment by nickalcala** [comment]
I used tymon/jwt-auth with jenssegers/laravel-mongodb and I solved it by updating `identifier` key in *config/jwt.php* from `id` to `_id`.
