### ISSUE TITLE
Find on Embeds

### ISSUE THREAD

**Issue by alexjose** [jenssegers/laravel-mongodb#1427]
I have an object like below. 
```bson
{
	"_id" : ObjectId("5a799303c062ce77ab0145a3"),
	"name" : "Sample Sector 2",
	"updated_at" : ISODate("2018-02-06T18:10:20.000+05:30"),
	"created_at" : ISODate("2018-02-06T17:05:31.000+05:30"),
	"trades" : [
		{
			"name" : "Sample Trade 1 for Sector 1",
			"updated_at" : ISODate("2018-02-06T19:17:24.000+05:30"),
			"created_at" : ISODate("2018-02-06T19:17:24.000+05:30"),
			"_id" : ObjectId("5a79b1ecc062ce77aa6bf612")
		},
		{
			"name" : "Sample Trade 2 for Sector 1",
			"updated_at" : ISODate("2018-02-06T19:17:35.000+05:30"),
			"created_at" : ISODate("2018-02-06T19:17:35.000+05:30"),
			"_id" : ObjectId("5a79b1f7c062ce77ab0145a4")
		}
	]
}
```

I have created two models `Sector` and `Trade`. `Sector` has an embedsMany relation to `Trade`. 

Now I would like to query the Trade using the trade id. Is it possible?

Thanks in advance

**Comment by mthler** [comment]
Hi alexjose,

did you try:
Sector::where('trades._id', '5a79b1ecc062ce77aa6bf612')
            ->project([
            'trades' => [
                '$elemMatch' => [
                    '_id' => '5a79b1ecc062ce77aa6bf612'
                ]
            ]]);

this should give you 
{
_id: 5a799303c062ce77ab0145a3
trades: {
			"name" : "Sample Trade 1 for Sector 1",
			"updated_at" : ISODate("2018-02-06T19:17:24.000+05:30"),
			"created_at" : ISODate("2018-02-06T19:17:24.000+05:30"),
			"_id" : ObjectId("5a79b1ecc062ce77aa6bf612")
		}
}
