### ISSUE TITLE
Eloquent has() doesn't work with embedsOne/Many

### ISSUE THREAD

**Issue by gilenoranna** [jenssegers/laravel-mongodb#1430]
I've two relationships that make use of embed

```
public function memberApplication(){
	return $this->embedsOne("App\Models\Member");
}

public function notes(){
	return $this->embedsMany("App\Models\Note");
}

```
When I try to check if the relationship exists, like that

```
Guest::has("notes")->count();
Guest::has("memberApplication")->count();
```

Both queries returns me this error:

BadMethodCallException with message 'Call to undefined method Jenssegers\Mongodb\Query\Builder::getOwnerKey()'

Same thing occurs when I use whereHas() method, but it only happens to embeds like relationships.

**Comment by mihkelallorg** [comment]
Why was there a "wontfix" label added? Looks like the issue is still relevant. Is there a specific reason it's not going to be fixed?
