### ISSUE TITLE
Support for Laravel 5.6

### ISSUE THREAD

**Issue by dbebawy** [jenssegers/laravel-mongodb#1431]
When can we expect support for Laravel 5.6? 
Thanks in advance.

**Comment by RemiCollin** [comment]
A PR for supporting Laravel 5.6 is underway : https://github.com/jenssegers/laravel-mongodb/pull/1428

**Comment by divine** [comment]
Closed in https://github.com/jenssegers/laravel-mongodb/pull/1428
