### ISSUE TITLE
getDateFormat() must be public for laravel 5.6

### ISSUE THREAD

**Issue by slouma2000** [jenssegers/laravel-mongodb#1432]
Access level to Jenssegers\Mongodb\Eloquent\Model::getDateFormat() must be public (as in class Illuminate\Database\Eloquent\Model)

**Comment by Sohit18595** [comment]
I am also getting same issue with Jenssegers\Mongodb package...

**Comment by jwrunge** [comment]
I'm having the same problem, but installed and used with no problem a few days ago. I'm noticing the MongoDB PHP driver was updated on 2/9. Perhaps that has something to do with it?

**Comment by RemiCollin** [comment]
A PR for supporting Laravel 5.6 is underway : https://github.com/jenssegers/laravel-mongodb/pull/1428

**Comment by amjad-eremnews** [comment]
After changing function's access modifier from protected to public, another Error occurs with lumen 5.6
(1/1) ErrorException
Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::morphTo($name = NULL, $type = NULL, $id = NULL) should be compatible with Illuminate\Database\Eloquent\Model::morphTo($name = NULL, $type = NULL, $id = NULL, $ownerKey = NULL)

**Comment by vad-naitik** [comment]
I am also getting the same issue with Jenssegers\Mongodb package...
any idea about that?
how can I solve and how can I use a passport in Laravel with MongoDB

**Comment by heismehrab** [comment]
it might be help 
https://github.com/moloquent/moloquent/issues/97#issuecomment-480710970
