### ISSUE TITLE
How to use update method without replace old data ?

### ISSUE THREAD

**Issue by markpolarisdesign** [jenssegers/laravel-mongodb#1435]
Assume

**Initial Data**

`{ _id = 1, order = { A = 1, B = 2} }`

And I want to update C  and D to order field

Order::where('_id', ObjectID('1'))->update($request->all());

**Result**
`{ _id = 1, order = { C = 3, D = 4} }`

It's work ! but it replace all data.

I want

**Result**
`{ _id = 1, order = { A=1, B=2, C = 3, D = 4} }`

How to keep old data and add new data ?

Thank you.

**Comment by quando12** [comment]
if I use upsert, I can't insert created_at
