### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by raghav-g** [jenssegers/laravel-mongodb#1439]
@jenssegers  The library is amazing but we cannot use it in any of our applications or contribute to it if it does not have a registered license.

It would be great if you can register with MIT or apache and add a LICENSE.MD to your library.

**Comment by christoferw** [comment]
we have the same issue here

**Comment by christoferw** [comment]
would be great if you add a MIT license, like laravel does.

**Comment by jenssegers** [comment]
The composer file has MIT as license. Could anyone do a PR with an MIT license file? No access to my computer atm.

**Comment by christoferw** [comment]
https://github.com/jenssegers/laravel-mongodb/pull/1780

**Comment by divine** [comment]
It has been merged and this issue should be closed.

cc @Smolevich
