### ISSUE TITLE
Error after mongodb:1.3.0

### ISSUE THREAD

**Issue by bsormagec** [jenssegers/laravel-mongodb#1443]
Type error: Argument 3 passed to MongoDB\\Driver\\Server::executeQuery() must be an instance of MongoDB\\Driver\\ReadPreference or null, array given

I got this error after update mongodb package, is anyone else got this ?

Thank you

**Comment by vishal767** [comment]
check

**Comment by jmikola** [comment]
I think this is answered by https://github.com/mongodb/mongo-php-library/pull/498#issuecomment-366987657 and can be closed.

**Comment by brad13x** [comment]
The fix is to update mongodb/mongodb and update mongo.

sudo pecl install mongodb
sudo systemctl restart php7.1-fpm
sudo systemctl restart nginx
