### ISSUE TITLE
FatalErrorException with lumen 5.6

### ISSUE THREAD

**Issue by amjad-eremnews** [jenssegers/laravel-mongodb#1445]
(1/1) FatalErrorExceptionAccess level to Jenssegers\Mongodb\Eloquent\Model::fromDateTime() must be public (as in class Illuminate\Database\Eloquent\Model)
in Model.php (line 15)

Access level to Jenssegers\Mongodb\Eloquent\Model::fromDateTime() must be public (as in class Illuminate\Database\Eloquent\Model

**Getting ErrorException after making this function protected**

(1/1) ErrorException
Declaration of Jenssegers\Mongodb\Eloquent\HybridRelations::morphTo($name = NULL, $type = NULL, $id = NULL) should be compatible with Illuminate\Database\Eloquent\Model::morphTo($name = NULL, $type = NULL, $id = NULL, $ownerKey = NULL)

**Comment by univicosa** [comment]
Following. Same problem with Laravel 5.6

**Comment by MattDalm** [comment]
+1, same for me

**Comment by rbochenski** [comment]
+1, same for me in laravel 5.6

**Comment by olimarferraz** [comment]
Solved on release v3.4.0!

**Comment by amjad-eremnews** [comment]
Yes solved in 3.4.0
