### ISSUE TITLE
Relationship help

### ISSUE THREAD

**Issue by DavendraNaraine** [jenssegers/laravel-mongodb#1448]
Hi I am new to using mongodb with laravel. I am having a hard time understanding the relationships aspect.

I have a Form Model:

`id:5a9425e192f422f9fa65febf
name:"New Applicant"
sections:Array
0:"5a940eea92f422572661faf6"
1:"5a940eea92f422572661fafb"
2:"5a940eea92f422572661fb00"
3:"5a940eea92f422572661fb05"
4:"5a940eea92f422572661fb09"
5:"5a940eea92f422572661fb0c"
6:"5a940eea92f422572661fb14"
7:"5a940eea92f422572661fb19"
8:"5a940eea92f422572661fb1e"`

Section is another model. Is there a way for me to eager load the sections with the form?

**Comment by coreywelch** [comment]
You can find model relationships in Laravel here:
https://laravel.com/docs/5.5/eloquent-relationships

Here is a good read about using MongoDB relationships:
https://docs.mongodb.com/manual/tutorial/model-embedded-one-to-one-relationships-between-documents/

MongoDB Data Modeling concepts:
https://docs.mongodb.com/manual/core/data-model-design/
