### ISSUE TITLE
Connection string broken after upgrading to Laravel 5.6

### ISSUE THREAD

**Issue by Bowens20832** [jenssegers/laravel-mongodb#1449]
I am attempting to upgrade my install from 5.5 to 5.6. I am getting  No suitable servers found (`serverSelectionTryOnce` set) on my production and sandbox clusters. 

Any ideas whats going on? Everything works fine in 5.5. 

My database.php looks like:

'mongodb' => [
            'driver'   => 'mongodb',
            'dsn' =>env('MONGO_PATH', ''),
            'database' => ' databasename ',
        ],

**Comment by MordiSacks** [comment]
Had the same problem, I think something with the dsn parsing is broken
this worked for me

```
        'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => [
                'xxx-00-00-mfddc.mongodb.net',
                'xxx-00-01-mfddc.mongodb.net',
                'xxx-00-02-mfddc.mongodb.net',
            ],
            'port'     => 27017,
            'database' => env('MONGODB_DATABASE'),
            'username' => env('MONGODB_USERNAME'),
            'password' => env('MONGODB_PASSWORD'),
            'options'  => [
                'ssl'        => true,
                'replicaSet' => 'replicaSetName',
            ],
        ],
```

**Comment by Bowens20832** [comment]
@MordiSacks lol I literally took your approach a couple hours ago which fixed the issue. Thank you for your suggestion.

**Comment by divine** [comment]
Closing, merged in https://github.com/jenssegers/laravel-mongodb/pull/1457
