### ISSUE TITLE
Method Jenssegers\Mongodb\Query\Builder::notify does not exist.

### ISSUE THREAD

**Issue by amjad-eremnews** [jenssegers/laravel-mongodb#1450]
Method Jenssegers\Mongodb\Query\Builder::notify does not exist.

**Comment by scx7** [comment]
Hello, I had the same problem, just add the Notifiable class on User model

`<?php

namespace App\Models;

use DateTimeZone;
use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Authenticatable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Eloquent implements AuthenticatableContract,  CanResetPasswordContract {

	use Authenticatable, CanResetPassword, Notifiable;

}`
