### ISSUE TITLE
[Question]How can i change active mongodb dynamically

### ISSUE THREAD

**Issue by emrecanozkok** [jenssegers/laravel-mongodb#1462]
hi,im using laravel and multiple mongodb and mongodb collections.

every customer is a single database and every customer branches is collection in my mongo.
 
i can set collection like this. but i need to change database and collection dynamically.

```
class Info extends Eloquent
{
    protected $connection = 'mongodb';
    protected $collection = 'loc_outside';

}
```

how i can ?

**Comment by dorinmusteata** [comment]
Query your db with DB class and set a dynamic database name.

**Comment by emrecanozkok** [comment]
@dorinmusteata im using mysql for my all of customer information and login system im using mongo for only timeseries data and some customer have multiple location.i need to change db name and collection dynamically i dont understand how i will make.i can change codes of this library but i dont want to do it.

**Comment by dorinmusteata** [comment]
DB::disconnect('mongodb'); // Connection name
Config::set('database.connections.mongodb.database', $dbName); // New database name

Or , if you have small amount of users , you can define your connections array in database.php 

Or , you can make a connection manager which will affect certain models connections

**Comment by emrecanozkok** [comment]
@dorinmusteata Sorry for my problem.mongo is not my primary db connections.my default connection is mysql.

And how i can run this command i dont know
im new switched codeigniter to laravel


```
$client = DB::getMongoClient();
$db = DB::getMongoDB();
```
what is the DB instance or what i need to import top of my controller file.or where its usable controller or model i dont know. if its works for me i can change db and collection whatever i need.

**Comment by emrecanozkok** [comment]
im removed this lib and starting to use native mongo lib with laravel, and im writing database interface now.
Thanx for all.

**Comment by blade93ny** [comment]
There really should be an easy way to change the "database" name on the model level without having to define a ton of different connections where everything is the same except the "database" name... The server host is the same, the user creds are the same, the only thing that differs is the "database" name...
---
Using the approach of Single DB server, multiple DBs makes sense to create a multi-tenant system on the same exact DB server... regardless if its MongoDB or MySQL... its just with MySQL you would need to run a separate migration on the "Client" DB and a different migration on the "PRIMARY" DB... with MongoDB you dont need to run any laravel defined migrations as the collections will be automatically created when the records are created... or you can simply have an "ONBOARDING" process which will create empty collections with schema definition when a new client is created...
