### ISSUE TITLE
List all collections

### ISSUE THREAD

**Issue by diksha-srivastava** [jenssegers/laravel-mongodb#1464]
Hi,
I have a requirement to list all tables through code previously is built in mysql. Now I am using this plugin to list all collections but i cant find a replacement of below here:

$tables = DB::select('SHOW TABLES');

Any help would be appreciated

**Comment by hassanzohdy** [comment]
For anyone coming from google
Here is the available way to list all collections in the database.

```php
foreach (\DB::connection()->getMongoDB()->listCollections() as $collection) {
    echo $collection->getName() ;
}
```

**Comment by DevZaX** [comment]
`   foreach (DB::connection("mongodb")->getMongoDB()->listCollections() as $collection) {
        echo $collection->getName() ;
    }`

this worked for me
