### ISSUE TITLE
Issue with hasMany

### ISSUE THREAD

**Issue by MattDalm** [jenssegers/laravel-mongodb#1467]
Hi - 

I am facing the exact same issue described here: #1024 and #1253 for example. 
The issue seems to be that the foreign key is not converted to an ObjectId when the query is built, and this is true even when the foreign key ends with `_id`

What do you guys think about that?

**Comment by shivamgupta94** [comment]
Same issue. Thanks for the quick fix @MattDalm

**Comment by csgt** [comment]
This only works when the name of the key ends with _id.  This is not the case for every database.  The correct solution would be to parse de $casts value, and convert each value there to string.
For example, in the model, adding

$casts = [
    'remoteKey' => 'string'
]

public function brand()
{
    return $this->belongsTo(Brand::class, 'remoteKey', '_id');
}

Should convert the remoteKey ObjectID to string in the where statement.

**Comment by csgt** [comment]
This is also a little extreme, since it goes through every single column, but it should work, since the function $this->convertKeys checks if the value is an ObjectID:

      // Convert id's.
            if (isset($where['column'])) {
                // Multiple values.
                if (isset($where['values'])) {
                    foreach ($where['values'] as &$value) {
                        $value = $this->convertKey($value);
                    }
                } // Single value.
                elseif (isset($where['value'])) {
                    $where['value'] = $this->convertKey($where['value']);
                }
            }

**Comment by zacroker** [comment]
This fixed it for me @MattDalm

**Comment by Fahd-Ibtikar** [comment]
I agree with @csgt . No need for the checks to go so extreme.
It's good to have the database fields following the standard mongo way but that's not always the case espesially when migrating old projects
