### ISSUE TITLE
Is it necessary to create migrations?

### ISSUE THREAD

**Issue by TresCe** [jenssegers/laravel-mongodb#1470]
Hello, I wanted to know if it is necessary to create migrations

**Comment by MattDalm** [comment]
I was wondering the same so I've stopped doing it and I do not see any impact. So if anyone has background on that I would like to know. as well.

**Comment by artaex** [comment]
You only need migrations to create indexes. Because MongoDB is NoSQL, there's no need to define a database schema.

**Comment by Oleg-Arkhipov** [comment]
You may also need migrations to create some initial data which your application requires to work.
