### ISSUE TITLE
[suggestion] add some collaborators to this repository

### ISSUE THREAD

**Issue by wppd** [jenssegers/laravel-mongodb#1472]
hi @jenssegers 
thanks for your hard work first.
Looking at the number of issues and pull requests, I think it's time to invite some collaborators for this great project.

**Comment by MattDalm** [comment]
It's not only great, it is also really useful and (almost) mandatory for anyone using lumen/laravel with mongodb

**Comment by Oleg-Arkhipov** [comment]
At least there is a lack of issue management. There are a ton of issues here, and a lot of them are plain questions (some of them are really old and it is unlikely that authors are still waiting for answers), duplicated issues, etc.
Labels are barely used too (to distinguish bugs and enhancements, to manage priorities, etc).
I think that these problems should be fixed for a serious product like this.

**Comment by sololance** [comment]
@jenssegers maybe now it's right time finally to manage this repo?

If you don't have any time let community manage it for all of us who are using this library in their project.

Thanks.

**Comment by ollieread** [comment]
My understanding is that @jenssegers has been quite busy lately, and hasn't had the time to fully tend to this project, so you're probably correct in that it could do with some collaborators.

It is, however, worth noting that there's currently a rework in progress, splitting out the core of the functionality to https://github.com/jenssegers/laravel-mongodb-core, with this package eventually being modified to use that and then become an Eloquent extension of it.

**Comment by sololance** [comment]
@ollieread well, if @jenssegers working on a new version why not announce it on main page or make it pinned? I'm sure a lot of people are ready to help but it's impossible to track his personal github profile neither tracking his decisions which lost somewhere?

**Comment by divine** [comment]
Hello and sorry for late reply!

We're as community trying to help out this library on fixes and new features. Most of the issues has been closed and PRs merged as well new version released.

We kindly ask you for your help [here ](https://github.com/jenssegers/laravel-mongodb/issues/1974)

Thanks!
