### ISSUE TITLE
Cannot drop composite index

### ISSUE THREAD

**Issue by mnich0ls** [jenssegers/laravel-mongodb#1478]
Passing a list of column names to dropIndex fails to generate the correct index name. 
dropIndex does not conform to the Illuminate Blueprint interfaces where indexes can be dropped by name or array of columns.

**Comment by Elypson** [comment]
You are right and I second your issue... Note, if not yet known, the workaround that you can pass as second parameter to `index` an arbitrary name of the key.

    $table->index(['field1', 'field2'], 'my_special_key');

, so that later

    $table->dropIndex('my_special_key');

works.

**Comment by Smolevich** [comment]
@mnich0ls, can you close issue?
