### ISSUE TITLE
How to create Text Index?

### ISSUE THREAD

**Issue by saeedvaziry** [jenssegers/laravel-mongodb#1489]
How can i create text index in migrations?

**Comment by Sebbba** [comment]
Hey, guys! 
It's realy good qquestion. 
How can I run  totally raw query? 
Need something like 
DB::statement('db.proposals.createIndex( { summary: "text", content: "text", title: "text" } )');

**Comment by Sebbba** [comment]
@saeedvaziry 
https://github.com/jenssegers/laravel-mongodb/wiki/Creating-Full-Text-Index-With-Laravel-Migration-Using-Moloquent

Here is the answer)

**Comment by saeedvaziry** [comment]
@Sebbba Thanks for your answer. I used this solution to my problem

https://docs.mongodb.com/php-library/current/tutorial/indexes/#create-indexes

**Comment by tranghaviet** [comment]
```Schema::table('provinces', function (Blueprint $table) {
            $table->index(['name' => 'text'], 'name_full_text');
    });
```
