### ISSUE TITLE
192.168.9.43:27017: not authorized for query on telesanteclik.users

### ISSUE THREAD

**Issue by sharmahemal** [jenssegers/laravel-mongodb#1497]
Hello ,

I have set my configration in .env file.
.env
------------------------
DB_CONNECTION=mongodb
DB_HOST=192.168.9.43
DB_DATABASE=telesanteclik
DB_USERNAME=odentoclick
DB_PASSWORD=123456

And i have use mongod --auth command for authentication 

But when i will execute the code error like below,
"192.168.9.43:27017: not authorized for query on telesanteclik.users"

it's working fine connection in tools [No SQL manager].

Please help me.

Thanks in advance.

**Comment by jafar-albadarneh** [comment]
Have you solved this issue ? am running into the same problem !

**Comment by sharmahemal** [comment]
yes i have resolved that issue,
do like below example,
-----------------------------------------------
use admin
db.createUser(
  {
    user: "admin",
    pwd: "password",
    roles: [ { role: "root", db: "admin" } ]
  }
);
---------------------------------------------------
db.createUser(
  {
    user: "user",
    pwd: "password",
    roles: [ { role: "redwriteDb", db: "your-db" } ]
  }
);
and i have resolved that issue

**Comment by aysenli** [comment]
@sharmahemal 
am running into the same problem  too!
your mongodb service did not open the certification ???   --auth
