### ISSUE TITLE
If you use the dusterio/lumen-passport library, what should you do?

### ISSUE THREAD

**Issue by guoyanjun5** [jenssegers/laravel-mongodb#1499]
When I use   [dusterio/lumen-passport](https://packagist.org/packages/dusterio/lumen-passport)    library library, execute 

`php artisan passport:install `
error 
`"In Connection.php line 445: Call to a member function prepare() on null"`

what should I do?

**Comment by sedrak1987** [comment]
use my package for mongodb(based to Laravel passport, so you can use Passport doc)
https://packagist.org/packages/sedrak/laravel-mongodb-passport
remove larvel passport from composer and install this.
