### ISSUE TITLE
Php 7 with laravel 5.5.40 mongo db driver issue

### ISSUE THREAD

**Issue by stardesign77** [jenssegers/laravel-mongodb#1510]
Php 7 with laravel 5.5.40 mongo db driver issue

composer update jenssegers/mongodb
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.5.40
    - Conclusion: don't install laravel/framework v5.5.40
    - jenssegers/mongodb v3.4.0 requires illuminate/database ^5.6 -> satisfiable
 by illuminate/database[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6
.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.3, v5.6.4, v5.6.5
, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - jenssegers/mongodb v3.4.1 requires illuminate/database ^5.6 -> satisfiable
 by illuminate/database[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6
.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.3, v5.6.4, v5.6.5
, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - jenssegers/mongodb v3.4.2 requires illuminate/database ^5.6 -> satisfiable
 by illuminate/database[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6
.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.3, v5.6.4, v5.6.5
, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/database v5.6.0|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.1|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.10|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.11|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.12|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.13|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.14|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.15|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.16|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.17|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.19|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.2|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.20|don't install laravel/framework
v5.5.40
    - don't install illuminate/database v5.6.3|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.4|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.5|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.6|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.7|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.8|don't install laravel/framework v
5.5.40
    - don't install illuminate/database v5.6.9|don't install laravel/framework v
5.5.40
    - Installation request for laravel/framework (locked at v5.5.40, required as
 5.5.*) -> satisfiable by laravel/framework[v5.5.40].
    - Installation request for jenssegers/mongodb ^3.4 -> satisfiable by jensseg
ers/mongodb[v3.4.0, v3.4.1, v3.4.2].

**Comment by stardesign77** [comment]
composer require jenssegers/mongodb 3.3.1

**Comment by vitoryugulisqq** [comment]
> composer require jenssegers/mongodb 3.3.1

Saved my life!
