### ISSUE TITLE
Soft deletes not working on embedded documents

### ISSUE THREAD

**Issue by cheems77** [jenssegers/laravel-mongodb#1513]
As referenced in Issue #422 

I'm working with version 3.2 of this package and Laravel 5.5 and there doesn't appear to be a resolve.

The deleted_at attribute is set to false using the Jenssegers\Mongodb\Eloquent\SoftDeletes trait but queries still return documents where `deleted: true`

**Comment by aowie1** [comment]
Any update on this? Dealing with the same problem...
I also tried solving by adding a where condition to the EmbedsMany, but it throws an Exception: "... must return a relationship instance."

**Comment by Giacomo92** [comment]
Hi @aowie1 in the end I have realized that is not a simple implementation and not so useful. Infact I always keep the "delete data" in the master model.
