### ISSUE TITLE
(1/1) ErrorException Trying to get property 'headers' of non-object  in VerifyCsrfToken.php line 158 at HandleExceptions->handleError(8, 'Trying to get property \'headers\' of non-object', 

### ISSUE THREAD

**Issue by stardesign77** [jenssegers/laravel-mongodb#1516]
(1/1) ErrorExceptionTrying to get property 'headers' of non-object
--
in VerifyCsrfToken.php line 158
at HandleExceptions->handleError(8, 'Trying to get property \'headers\' of non-object',

**Comment by naspy971** [comment]
I just got this error because in my middleware I was returning a route instead of 'return redirect()->route('')';

That resolved my case.

**Comment by stardesign77** [comment]
return redirect()->route('')  in which file path, i have to change this?

**Comment by naspy971** [comment]
Depends on what you did in your application just before that happened. For me, I had just created custom middleware : 

```
   public function handle($request, Closure $next)
    {
        if (!Auth::user()->admin) {
            return redirect(route('forum'));
        }
        return $next($request);
    }
```

But I was actually returning it like this : 
```
   public function handle($request, Closure $next)
    {
        if (!Auth::user()->admin) {
            **return route('forum');**
        }
        return $next($request);
    }
```

Which was my problem that got me the same error. The custom middleware file is located in app/Http/Middleware

I think you might be returning directly a route or a view instead of redirecting...

Hope that will help you !

**Comment by stardesign77** [comment]
I am creating connection with mongodb, do you have any suggestions for this?

**Comment by stardesign77** [comment]
Do you have example for crud operations and login/register with mongodb?

**Comment by stardesign77** [comment]
1. $statement = $this->prepared($this->getPdoForSelect($useReadPdo)
   2. ->prepare($query));

*vendor\laravel\framework\src\Illuminate\Database\Connection.php*

Symfony \ Component \ Debug \ Exception \FatalThrowableError (E_ERROR)
Call to a member function prepare() on null

**Comment by naspy971** [comment]
For your second error, check this : 
[](https://stackoverflow.com/questions/28592400/fatal-error-call-to-a-member-function-prepare-on-null?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa )

Have you done the configuration correctly according to this ? 

[](https://github.com/jenssegers/laravel-mongodb#configuration)

Honestly I haven't used mongodb with Laravel so I can't tell you more about it.

**Comment by stardesign77** [comment]
For your second error, check this : what i have to check?

**Comment by naspy971** [comment]
Hum don't you see the link below what I said ??

> https://stackoverflow.com/questions/28592400/fatal-error-call-to-a-member-function-prepare-on-null?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

> https://github.com/jenssegers/laravel-mongodb#configuration

**Comment by Eyewash01** [comment]
FYI, I had this exact issue, and it was because of the following:

1/ I was using multiple auth guards (e.g. admin and front end user)
2/ I had overridden the unauthenticated method on the exception handler, and had logic to perform different actions for different guards
3/ I hadn't specified an action for the guard in question, and therefore this method was returning null

**Comment by agm1984** [comment]
> Sacha QUESTEL ***@***.***> wrote: I just got this error because in my middleware I was returning a route instead of 'return redirect()->route('')';

Lol oops, I just triggered this error by having:

``` php
return request()->json(['asdf' => 'asdf], 401);
```

I didn't notice it because `request` looks so similar to `response`. Also unfortunately VS Code and PHP intelephense didn't lint it.

Changed it to the correct:

``` php
return response()->json(['asdf' => 'asdf], 401);
```

**Comment by sachinpandeyatd** [comment]
I was also facing the same problem, but mine was resolved after I added "return $next($request);" line after the "if-else" condition

**Comment by rdxdas20** [comment]
/**

     * Add the CSRF token to the response cookies.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  \Symfony\Component\HttpFoundation\Response  $response

     * @return \Symfony\Component\HttpFoundation\Response

     */

    protected function addCookieToResponse($request, $response)

    {

        $config = config('session');

 

        if ($response instanceof Responsable) {

            $response = $response->toResponse($request);

        }

 

        $response->headers->setCookie(

            new Cookie(

                'XSRF-TOKEN', $request->session()->token(), $this->availableAt(60 * $config['lifetime']),

                $config['path'], $config['domain'], $config['secure'], false, false, $config['same_site'] ?? null

            )

        );

 

        return $response;

    }

 

    /**

     * Determine if the cookie contents should be serialized.

     *

     * @return bool

     */

    public static function serialized()

**Comment by rdxdas20** [comment]
Trying to get property 'headers' of non-object
