### ISSUE TITLE
raw expression

### ISSUE THREAD

**Issue by matteo030** [jenssegers/laravel-mongodb#1522]
Is there a way to make native-mongodb request to the database using raw expression like in mysql?I read jenssenger readme file and the raw expression section but i couldn't find something similar to this: 

`DB::raw("SELECT distinct ID, post_title,post_name FROM app_posts)`

**Comment by kwame101** [comment]
Have a look at mongodb aggregate function [here](https://docs.mongodb.com/manual/reference/operator/aggregation/project/)
You can implement what you want in php like 
```
AppPost::raw(function ($collection){
     return $collection->aggregate([
         [ '$project' => [
                'post_title' => 1,
                'post_name' => 1
             ]
         ],
         //since distinct dont work in aggregate u can use group 
         ['$group' =>
            '_id' => [ 
                   'id' => '$_id',
                   'post_title' => '$post_title',
                   'post_name' => '$post_name' 
              ]
         ]
   ]);
});
```
I think something like this is similar to your sql statement above

**Comment by matteo030** [comment]
Thanks, this is very useful
