### ISSUE TITLE
whereHas error

### ISSUE THREAD

**Issue by Siebov** [jenssegers/laravel-mongodb#1527]
On 

ModelName::whereHas('something', function($q){
...
})
...
->get();

Error 

"Method Jenssegers\\Mongodb\\Query\\Builder::getOwnerKey does not exist.",

**Comment by Sebbba** [comment]
@behnamazimi I don't remember((( 
It seems it was somthing wrong with relation on my side, try to check it. 

I've searched along my project for whereHas() and found on;y this 

```php
$contribution = $this->contribution
                ->with(['proposal'])
                ->where('_id', $id)
                ->whereHas('proposal', function ($q) {
                    $q->where('user_id', Auth::id());
                })
                ->firstOrFail();
```

**Comment by sbourdette** [comment]
@behnamazimi did you find a solution ?

**Comment by sbourdette** [comment]
@jenssegers did you ever seen that ?

**Comment by thesea2201** [comment]
Error was raise when I want to use sub-relation like relationship **hasManyThrough**() in Laravel Eloquent.

I have 3 model: **Book**(_id, book_category), **BookCategory**(_id, book_id, category_id) and **ReadAfter**(book_id). I want to list all **Book** in **Read After** and **Book** has category in $categoryId array.
Model **ReadAfter**() with function:
`public function book()
    {
        return $this->belongsTo('App\Model\Book', 'book_id', '_id');
    }`
Model **Book** with function:
`public function bookCategory()
    {
        return $this->hasMany('App\Model\BookCategory');
    }`
Last, I query result
`$item = $this->model->where($where)
                    ->whereHas('book', function($query) use( $categoryId) {
                        $query->whereHas('bookCategory', function($subquery) use($categoryId){
                            $subquery->whereIn('category_id', $categoryId);
                        });
                    })
                    ->with(['book'])->get();`

This is my case, hope help you.

**Comment by thesea2201** [comment]
Error was raise when I want to use sub-relation like relationship **hasManyThrough**() in Laravel Eloquent.

I have 3 model: **Book**(_id, book_category), **BookCategory**(_id, book_id, category_id) and **ReadAfter**(book_id). I want to list all Book in Read After and Book has category in $categoryId array.
Model **ReadAfter**() with function:
```php
public function book()
    {
        return $this->belongsTo('App\Model\Book', 'book_id', '_id');
    }
```
Model **Book** with function:
```php
public function bookCategory()
    {
        return $this->hasMany('App\Model\BookCategory');
    }
```
Last, I query result
```php
$item = $this->model->where($where)
                    ->whereHas('book', function($query) use( $categoryId) {
                        $query->whereHas('bookCategory', function($subquery) use($categoryId){
                            $subquery->whereIn('category_id', $categoryId);
                        });
                    })
                    ->with(['book'])->get();
```

This is my case, hope help you.
