### ISSUE TITLE
The 'cursor' option is required, except for aggregate with the explain argument

### ISSUE THREAD

**Issue by sandipmavani** [jenssegers/laravel-mongodb#1530]
after mongodb migrate 3.4 to 3.6

**Comment by JoyG42** [comment]
same issue here 
Is there anyone who can solve?
Laravel 5.1
Php 5.6.36
MongoDB 3.6

**Comment by si2w** [comment]
Same issue here. Any idea how to solve this ? 

Thanks

**Comment by si2w** [comment]
I solved the issue on the version 2.3.5 by doing those modifications : 
see pull request https://github.com/jenssegers/laravel-mongodb/pull/1569 and https://github.com/jenssegers/laravel-mongodb/pull/1570
