### ISSUE TITLE
whereDate / whereMonth / whereDay / whereYear / whereTime ???

### ISSUE THREAD

**Issue by Mellowz** [jenssegers/laravel-mongodb#1536]
is whereDate / whereMonth / whereDay / whereYear / whereTime are not imlement ?

**Comment by msyahidin** [comment]
+1

**Comment by mean-cj** [comment]
+1

**Comment by Smolevich** [comment]
You can implement this function in trait for example or prepare implementation this examples

**Comment by marooj** [comment]
oh i am need a lot please prepare these functions

**Comment by gialang** [comment]
+1

**Comment by a-zog** [comment]
I'm not sure about your use case, but I could solve mine using the native Eloquent features.

If you need to get all posts for a specific time period and display a chart from the result.

```
  $results =\DB::collection($model)
                ->whereBetween(
                    'created_at',
                    array(
                        Carbon::parse($min),
                        Carbon::parse($max)
                    )
                 )
                ->get()
                ->groupBy(function ($item) {
                    return $item['created_at']->toDateTime()->format("Ym");
                });
```

Hope that would help

**Comment by seamive** [comment]
Any example to get current month records based on whereDate?
We're trying 
`Story::where('author_id', $userProfile->_id)->whereDate('timestamp', '>=', now()->month)->first();`
but getting
`Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereDate()
`
