### ISSUE TITLE
chunkById() does not work when _id is integer

### ISSUE THREAD

**Issue by halaei** [jenssegers/laravel-mongodb#1538]
In order to reproduce, make a collection with documents having integer ids. Then run the following:

```php
\DB::connection('mongodb')->enableQueryLog();
User::query()->chunkById(100, function ($collection) {
    dd($collection->count());
});
dd(\DB::connection('mongodb')->getQueryLog());
```

The expected behavior would be dumping the count of first chunk.
What actually happens is this query getting dumped:

```
users.find({"_id":{"$gt":"000000000000000000000000"}},{"sort":{"_id":1},"limit":100,"typeMap":{"root":"array","document":"array"}})
```
Apparently, no integer is less than '000000000000000000000000' in MongoDb.

A Related PR: https://github.com/jenssegers/laravel-mongodb/pull/1317
ping @DFurnes 
Any idea on how to fix this?

**Comment by halaei** [comment]
I think the related PR in laravel/framework fixes this as well. Just a need to delete a couple of lines after laravel 5.7 release.

**Comment by DFurnes** [comment]
Yep, removing that hack now that this is fixed in Laravel makes sense to me! 👍
