### ISSUE TITLE
belongsToMany querying the wrong table

### ISSUE THREAD

**Issue by mbeech** [jenssegers/laravel-mongodb#154]
I'm struggling to retrieve relations when using belongsToMany. The related_ids are being pushed correctly, but when I try and retrieve the relation the wrong table is being queried.

I've got two models, Orders and Products. An Orders belongs to many Products and in the Order table has a product_ids field with an array.

```
use Jenssegers\Mongodb\Model as Eloquent;

class Order extends Eloquent {

    ...

    public function products()
    {
        return $this->belongsToMany('Product');
    }

}
```

However, when I run:

```
Order->with('products')
    ->where('_id', '=', $id)
    ->first();
```

The first query runs:

```
orders.find({"_id":{"$id":"531eeaa39c7e251f0800119a"}}, [])
```

And then the second query is:

```
products.find({"order_ids":{"$in":["531eeaa39c7e251f0800119a"]}}, [])
```

Shouldn't the second query be using the product_ids from the Orders table, rather than looking in the Product table for order_ids?

I'm unsure if this is a bug, or if I'm doing something wrong.

Thanks

**Comment by ilyachase** [comment]
@jenssegers Hi man. Thanks for your work and repo. But I just wondering, why did you implement many-to-many relationship this way, and not with a pivot collection?
