### ISSUE TITLE
Does not work hasMany

### ISSUE THREAD

**Issue by viacheslavpleshkov** [jenssegers/laravel-mongodb#1540]
Model User
https://github.com/slava-pleshkov/laravel-slavapleshkov/blob/master/app/User.php
Model Role
https://github.com/slava-pleshkov/laravel-slavapleshkov/blob/master/app/Role.php
Controllers User
https://github.com/slava-pleshkov/laravelslavapleshkov/blob/master/app/Http/Controllers/Admin/UserController.php
View
https://github.com/slava-pleshkov/laravel-slavapleshkov/blob/master/resources/views/admin/users/index.blade.php
Does not show in view.
Prompt me how I must decide a problem

**Comment by slava-pleshkov** [comment]
The problem was solved.

**Comment by LynX39** [comment]
> The problem was solved.

Please post your solutions. Thanks.
