### ISSUE TITLE
Error while inserting records 

### ISSUE THREAD

**Issue by ZAZmaster** [jenssegers/laravel-mongodb#1552]
Model:
```php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Result extends Eloquent
{
    protected $connection = 'mongodb';
    protected $guarded = ['id'];
    public $timestamps = false;
}
```

Controller:
```php
<?php

namespace App\Http\Controllers;

use App\Result;

class TestController extends Controller
{
    public function result(Request $request, $id)
    {
        $result = Result::create($request->except('_token'));
        dd($result);
	}
}
```

Get error:
```
Argument 3 passed to MongoDB\Driver\Server::executeBulkWrite() must be an instance of MongoDB\Driver\WriteConcern or null, array given
```

**Comment by ZAZmaster** [comment]
Version of mongodb php extesions is mismatch. Upgrade be helpful!

**Comment by lesvere** [comment]
root@751fff3a2f2e:~# php -v

PHP 7.1.11 (cli) (built: Nov  4 2017 10:24:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

root@751fff3a2f2e:~# pecl list

Installed packages, channel pecl.php.net:
=========================================
Package Version State
mongodb 1.5.2   stable
redis   3.1.4   stable
xdebug  2.5.5   stable




Same content as ZAZmaster.

response: 
Argument 3 passed to MongoDB\Driver\Server::executeBulkWrite() must be an instance of MongoDB\Driver\WriteConcern or null, array given
