### ISSUE TITLE
 Searching in array of objects.

### ISSUE THREAD

**Issue by renanmoraes** [jenssegers/laravel-mongodb#1558]
Well I need to do an advanced search in my collection I have:

```
"cities": [
  {
        "city":{
              "_id":"596e446637d3ea00e58249fe",
              "name":"coronel fabriciano",
             "state_name":"minas gerais",
              "state_abbr":"MG"
        },
       "order":{
             "tripA":0, 
            "tripB":1
        }, 
       "_id":"5af48a554f27d91f205e4441",
       "line_name":"Cel. Fabriciano - Acesita"
   },
  {
       "city":{
             "_id":"596e448237d3ea00e5824a00",
            "name":"Timóteo",
            "state_name":"Minas Gerais",
            "state_abbr":"MG"
        },
       "order":{
           "tripA":1,
           "tripB":0
        }, 
       "_id":"5af48a554f27d91f205e4440",
      "line_name":"Acesita - Cel. Fabriciano"
  }
]
```
![captura de tela de 2018-07-03 10-27-04](https://user-images.githubusercontent.com/12611706/42222996-148552da-7ead-11e8-9be2-994485df2aef.png)

Seen this I must do a search where the name of the city is Colonel Fabriciano and the line is Cel. Fabriciano - Acesita.

With moongose ​​(nodejs) it is easy to do this, but with php (laravel - lumen) I am not sure how to do it.

How would a query look like in the example above in the item in question?

**Comment by sunny047** [comment]
hi, i have a same situation.Any update on this....

**Comment by Smolevich** [comment]
@renanmoraes, it is possible. Join to slack channel and ask there, Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)
