### ISSUE TITLE
LIKE and like

### ISSUE THREAD

**Issue by mbeech** [jenssegers/laravel-mongodb#156]
I tend to write LIKE in capital letters as is normal if you're writing raw SQL.

```
$user = Comment::where('body', 'LIKE', '%spam%')->get();
```

This gives a error, Undefined index: result
vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php
Line: 166

After consulting the docs, I assumed my MongoDB wasn't greater than 2.2. After 20 mins of debugging I tried lowercase 'like' instead and it worked. Doh!

**Comment by VijayBapodariya** [comment]
The query builder now converts all operators to lowercase.

-> till not working
