### ISSUE TITLE
$ref

### ISSUE THREAD

**Issue by williansebastiao** [jenssegers/laravel-mongodb#1561]
Hello!
Is it possible to perform a reference-based search?
I did not find anything in the documentation about it, so I'm using the raw () method to use the mongo commands, but I'm not having success. See my code that I'm trying to execute.

```
        $projections = ['data' => 0, 'document' => 0];
        $push = PushCollection::raw(function($collection) use($projections, $companyId, $company){
            return $collection->findOne([['$ref' => 'companys', '$id' => $companyId], $projections]);
        });
```

**Comment by tuandm** [comment]
I don't know how did you store company, but I could query reference with something like this:
```
Article::where('author.$id', $user['_id']);
```

I'm not the big fan of document reference.

**Comment by williansebastiao** [comment]
@tuandm Hello!
That way I did not get the expected result.
I'll give you an example of my result, okay?

When I run the query: db.pushCollection.findOne({"parent" : DBRef("companys", ObjectId("52c7077a958e2070178b4567"))})
one of the nodes is: "company" : DBRef("companys", ObjectId("52c7077a958e2070178b4567")),

My question is: how to write this in my lumen application to get the same result.

**Comment by williansebastiao** [comment]
olá, consegui resolver. Irei deixar um exemplo caso alguém passse por isso.

```
$company = Companys::where('apiKey', $apiKey)->first(['apiKey', 'cnpj']);
$companyId = $company->_id;

$projections = ['projection' => ['data' => false, 'document' => false]];
$filter = ['company' => ['$ref' => 'companys', '$id' => new ObjectID($companyId)]];

$push = PushCollection::raw(function ($collection) use($filter, $projections){
        return $collection->find($filter, $projections);
});
```
Remember to instantiate the ObjectID
