### ISSUE TITLE
find user don't work

### ISSUE THREAD

**Issue by parsidev** [jenssegers/laravel-mongodb#1562]
Hello.

I have a problem to find user in my database.
i use this code
```$user = User::where('_id', new \MongoDB\BSON\ObjectId('﻿5b474381b577fa0d811937fe'))->first();```
and i get this response
```Error parsing ObjectId string: ﻿5b474381b577fa0d811937fe```

I try to use 
```$user = User::find('﻿5b474381b577fa0d811937fe');```
and i get null response

please help me
Thanks

**Comment by Smolevich** [comment]
In function `where` you miss operator in second argument. See [laravel source code](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Builder.php)

**Comment by MNSolderstar** [comment]
In your user model add `protected $appends = ['id'];` then find($id) or `findOrFail($id)` will work as expected. You can pass the ID as a plain string as you tried to use.

you can use `protected $hidden = ['_id']` to clean up JSON etc responses so you don't have two id's.
