### ISSUE TITLE
_id field getting null

### ISSUE THREAD

**Issue by sranjithk** [jenssegers/laravel-mongodb#1564]
All configuration done properly.

I'm using in laravel

"php": ">=5.6.4",
 "jenssegers/mongodb": "^3.2",  

Query:
 $result = DB::collection('message_template_db')->get();

Response for the above one: 
{
    "status": 1,
    "data": [
        {
            "_id": {},
            "template_name": "my emojis ",
            "template_description": "Social media emojis template",
    }
  ]
}

**Comment by Smolevich** [comment]
For example, i run this code 
```
DB::collection('message_template_db')->insert(
                [
                    'status' => 1,
                    'data' => [
                        [
                            'template_name' => 'my emojis',
                            'template_description' => 'Social media emojis template',
                        ]
                    ]
                ]
            );
            $result = DB::collection('message_template_db')->get();
            dd($result);
```
Reponse seems like 
```
array:1 [
  0 => array:3 [
    "_id" => MongoDB\BSON\ObjectId {#796
      +"oid": "5b517c6aafd5765f530f5342"
    }
    "status" => 1
    "data" => array:1 [
      0 => array:2 [
        "template_name" => "my emojis"
        "template_description" => "Social media emojis template"
      ]
    ]
  ]
]
```

**Comment by sranjithk** [comment]
for dd() its working but its not working for return response()->json(array("status"=>1,"data"=>$result));         

can you told me what is the issues with this ?

**Comment by sranjithk** [comment]
"_id" => MongoDB\BSON\ObjectId {#796
      +"oid": "5b517c6aafd5765f530f5342"
    }

How to fetch this one ?

**Comment by Smolevich** [comment]
Can you show code insert in mongo storage? For fetch one field you write code such as ```  DB::collection('message_template_db')->get(['_id']);```. dd is function helper in Laravel

**Comment by sranjithk** [comment]
**Insert query** 
DB::collection('message_template_db','autoIndexId:true')->insert(['template_name' => "emoji",'template_description' => "My emoji",'message_template_log'=>"null",'created_at'=>date('Y-m-d H:i:s'),"created_by"=>"sagar","status"=>1])

its working fine 

**Fetching from mongo db;**
db.social_template_db.findOne();
{
	"_id" : ObjectId("5b45ce62f631fc2566550011"),
	"template_name" : "my emoji",
	"template_description" : "My social media emoji",
	"message_template_log" : "null",
	"created_at" : "2018-07-11 09:31:14",
	"created_by" : "sagar",
	"status" : 1
}


when i exporting to 
response()->json(array);

id is not populating

**Comment by MNSolderstar** [comment]
This might help... I always use Eloquent models.

```php
<?php
namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class SocialTemplate extends Model
{
  protected $connection = 'mongodb';

  protected $collection = 'social_template_db';

  protected $appends = ['id'];

  protected $hidden = ['_id'];

  protected $dates = ['created_at','updated_at','deleted_at'];

  public $timestamps = true;
}
```

By appending ID, built in method to cast **_id** to **id** will make native functions like **find** and **findOrFail** work from the Eloquent builder as well as native Laravel Relations and Polymorphic Relations.

**$hidden**  on **_id** only hides it from the JSON response, simply de-junks the response since you a copy is now on the key of **id**.

Ajax request handled by controller or in this example directly by a route. (web.php or api.php)

```php
  // Returns JSON object, don't need to use response()->json()
  Route::get('/social/template/{$id}', function($id = null) {
    return \App\Models\SocialTemplate::findOrFail($id);
  });
```

You have to put $appends and $hidden in every model you create, they don't work from inside the extended base model, Would be nice to have id appended automatically.

**Comment by Smolevich** [comment]
In future better ask questions in new issue. Maybe create base common model and in all anothers models extends base common model?

**Comment by MNSolderstar** [comment]
Wasn't an question was an alternate answer to original posters question and that was what I was pointing out is that you can't use a base model that is extended on to set those attributes.
I tried it already so saving them the hassle of trying it and finding it does not work by making the point that it does not work but great if it did, its an issue for Laravel it's self not this project.
