### ISSUE TITLE
SelectRaw Count * is not working

### ISSUE THREAD

**Issue by yupangestu** [jenssegers/laravel-mongodb#1571]
`
$start                  = new MongoDate(new DateTime($from_date));
$end                    = new MongoDate(new DateTime($to_date));
`
`
$data       = StatisticModel::selectRaw("COUNT(*) as 'count'")
                ->with('productrels')
                ->where('type',"website_button")
                ->whereBetween('created_at',[$start,$end])
                ->groupBy('product_id')
                ->get();
`

guys, can someone help me? The goal is to collect the sum of each product that occured in the database by grouping and counting, but the problem is when i use the above code, it just return as

`"product_id" => "745"
        "COUNT(*) as 'count'" => null`

Thanks

**Comment by yupangestu** [comment]
help?

**Comment by divine** [comment]
I'm not sure why are you trying to run RAW SQL query on NOSQL database.

**Comment by tpaksu** [comment]
@divine there's one reason for you, we can't use model scopes with raw collection aggregate queries. So we need to convert that raw queries into to query builder equivalents. And there doesn't seem to exist a way to create a `[custom_name]: { $sum: 1 }` group.
