### ISSUE TITLE
php7 not use

### ISSUE THREAD

**Issue by li3007liuu** [jenssegers/laravel-mongodb#1576]
php7 install mongodb.so lib ,in this ,new Client cannot created,now i want to say,you can update to php7?

**Comment by dbakiu** [comment]
You can definitely use this extension with PHP7. I am using PHP 7.2.7 and it's working fine. 

But you need to make sure that the mongodb extension is installed. Further instructions can be found [here](http://php.net/manual/en/mongodb.installation.php).
