### ISSUE TITLE
Converting MongoDates in subdocument arrays to string 

### ISSUE THREAD

**Issue by webmobiletechie** [jenssegers/laravel-mongodb#1578]
I found that if I add "comment.created" in protected $dates, it gets converted to string. But if I have sub-document array "comments" with attribute "created", it does not get converted to string automatically, even if I add "comments.created" to protected $dates.

Do we have any such functionality in place already? If not, I'd like to contribute.

Let me know.

**Comment by JannieT** [comment]
Seems related to this issue: https://github.com/jenssegers/laravel-mongodb/issues/1252
