### ISSUE TITLE
->orWhere() result depending on order in method chain 

### ISSUE THREAD

**Issue by philipstanislaus** [jenssegers/laravel-mongodb#158]
Dear jenssegers, 

thank you very much for developing and maintaining this plugin! 

Unfortunately, I have some problems using the ->orWhere() method. Chaining like follows:

``` php
$event = Event::where("active", true)
                ->where('start_at', '>', Carbon::now()->subHours(8))
                ->orWhere('end_at', '>', Carbon::now()->subHours(2))
                ->get();
```

results in:

``` json
events.find({"active":true,"start_at":{"$gt":{"sec":1394720784,"usec":0}},"$or":[{"end_at":{"$gt":{"sec":1394742384,"usec":0}}}]}, [])
```

which translates into: 

```
active == true AND start_at > sometime AND (end_time > sometime2)
```

while:

``` php
$event = Event::where('start_at', '>', Carbon::now()->subHours(8))
                ->orWhere('end_at', '>', Carbon::now()->subHours(2))
                ->where("active", true)
                ->get();
```

results in: 

``` json
events.find({"$or":[{"start_at":{"$gt":{"sec":1394720838,"usec":0}}},{"end_at":{"$gt":{"sec":1394742438,"usec":0}}}],"active":true}, [])
```

which translates into: 

```
active == true AND (start_at > sometime OR end_time > sometime2)
```

As far as I understood the documentation, the "orWhere()" method should always refer to the "where()" method in the method chain before itself. Consequently, a chaining like Event::where()->where()->orWhere() leads to a wrong result. 

Kind regards and thanks a lot for your efforts!

Philip

**Comment by spmsupun** [comment]
@jenssegers this works perfectly
