### ISSUE TITLE
$casts doesn't work

### ISSUE THREAD

**Issue by elfeffe** [jenssegers/laravel-mongodb#1580]
I'm using latest version of the package and of Laravel. Also latest PHP 7 and MongoDB 4
I'm using    

```
 /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'force_stock' => 'integer'
    ];

```
But force-stock always save as string, unless I cast it by hand before save.
Any fix?

**Comment by iluozhiqiang** [comment]
`<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class Base extends Model
{
    /**
     * 设置时处理数据类型
     *
     * @param string $key
     * @param string $value
     * @return void
     */
    public function setAttribute($key, $value)
    {
        if ($this->hasCast($key)) {
            $value = $this->castAttribute($key, $value);
        }
        return parent::setAttribute($key, $value);
    }
}
`

**Comment by playerarm123** [comment]
i have same problem when i call update() method. any fix ?
