### ISSUE TITLE
$in does not support

### ISSUE THREAD

**Issue by KKarayat** [jenssegers/laravel-mongodb#1584]
While trying to do filtering based on category id in category array, 'exists' is not giving accurate results and when search for equivalent query in mongo, it suggested to use $in.

when tried putting in "in" in query builder it doesn't worked out

**Comment by Bowens20832** [comment]
Can you give an example of a query in Laravel and also the raw query in the Mongo shell if you can?

Your issue does not explain the context very well.

**Comment by BlueAmbition** [comment]
you can use like     BaiKe::whereRaw(['$text' => ['$search' => $key]])->count();
or UcInfo::whereIn('user_id', $userIdArr)->select('user_id', 'name')->get();
