### ISSUE TITLE
Class 'MongoClient' not found

### ISSUE THREAD

**Issue by rushabhsamcom** [jenssegers/laravel-mongodb#1585]
Hello,
I am getting error while using this library
![screenshot from 2018-08-21 16 36 06](https://user-images.githubusercontent.com/41897838/44398124-608b8580-a560-11e8-8231-c437a6feccc0.png)

Below is my configurations
PHP - 7.1.20
Mongodb driver version - 1.5.2
Os : Ubuntu - 14.04
Strange thing is same configuration in WINDOWS working fine.
Can anyone please help me to sorted out this issue.

**Comment by KyawNaingTun** [comment]
Hi @rushabhsamcom 
You need to update your mongo library(https://github.com/mongodb/mongo-php-library). I think, this package was updated for php7
![mongo php library src at master mongodb mongo php library](https://user-images.githubusercontent.com/6079250/44768037-fbe6b100-ab85-11e8-9661-674f64dff3fb.png)

**Comment by cincauhangus** [comment]
you probably have the file named in the wrong case. linux is case sensitive and windows is not
