### ISSUE TITLE
ordeby can not work

### ISSUE THREAD

**Issue by BlueAmbition** [jenssegers/laravel-mongodb#1586]
DB::connection('mongodb')->collection('baike_recommend') ->orderBy('update_time','desc')->toSql();
 BaiKeRecommend::orderBy('update_time','desc')->toSql();
explans sql
select * from "baike_recommend" order by ""；

but order by cant not works,please give a solution，tank you。

**Comment by HassanIbrahim** [comment]
@BlueAmbition You can do `BaiKeRecommend::latest()`

**Comment by BlueAmbition** [comment]
@HassanIbrahim If i want order by other filed?

**Comment by HassanIbrahim** [comment]
@BlueAmbition `BaiKeRecommend::orderBy('db_field', 'desc')->get();`

**Comment by n0n0n0n0** [comment]
i confirm it's not working in any ways

**Comment by n0n0n0n0** [comment]
latest/orderby doesnt matter
