### ISSUE TITLE
positional operator $ doesn't work

### ISSUE THREAD

**Issue by joerecra** [jenssegers/laravel-mongodb#1588]
Hi,

I'm Trying to execute this query with raw expression:

DB::collection('joboffer_results')->raw(function($collection)
      {
          return $collection->updateMany([],['$set'=> ['results.$.test'=>'Joel Recra2']]);
      });

But it doesn't work, returns message: The positional operator did not find the match needed from the query. Unexpanded update: results.$.test

Laravel 5.5, Mongo v3.6.3, jenssegers/mongodb": "3.3"

Please, help.

**Comment by gitdward** [comment]
Same problem here:

` DB::connection('mongodb')->collection('conceptos')->update([
                    '$set' => ['unidad.$' => $data['nombre']],
                ]);`

Laravel 5.7 Mongo v3.6.3 jenssegers/mongodb: 3.3

**Comment by joerecra** [comment]
Hi  @gitdward , this is an old issue, but I'm going to close it, because it's a problem of my query not of library, you need to add a "where clause" because "$" works finding an coincidence and then update it. For more information go to https://docs.mongodb.com/manual/reference/operator/update/positional/index.html

**Comment by gitdward** [comment]
Thanks for the answer
