### ISSUE TITLE
Support for Laravel Nova

### ISSUE THREAD

**Issue by alexjose** [jenssegers/laravel-mongodb#1589]
Laravel Nova is great admin UI tool. It will be good if Mongo DB can be used with Nova.

**Comment by chintanbanugaria** [comment]
+1

**Comment by alexjose** [comment]
As of now, it won't work. Listing and Searching works fine. But create/modification won't work as the Nova tries to run queries as the transaction.

**Comment by nbyloff** [comment]
I created a migration that adjusted the `action_events` table to allow for strings to be stored (`MongoId`). I just was about to do an update successfully to an existing model. 

I am having issues opening a create form for models that have relationships, but haven't dug into why yet. (Using Laravel Spark, I cannot open create team form because of a `uriKey()` error about the team owner)

```
Schema::table('action_events', function (Blueprint $table) {
       $table->string('actionable_id')->change();
	$table->string('target_id')->change();
	$table->string('model_id')->change();
        });
```

**Comment by medspec** [comment]
is there any movement on this?

**Comment by matthewjumpsoffbuildings** [comment]
im very interested to see if this is possible too

**Comment by midorikocak** [comment]
following

**Comment by marl01** [comment]
> following



> following

??

**Comment by Smolevich** [comment]
Please show example that this library don't be used in Nova, looks like a problem in nova and this situation don't related with this library

**Comment by divine** [comment]
Hello,

> As of now, it won't work. Listing and Searching works fine. But create/modification won't work as the Nova tries to run queries as the transaction.

Even if a transaction https://github.com/jenssegers/laravel-mongodb/pull/1904 coming soon,  would you have a sharded setup of MongoDB cluster?

> is there any movement on this?

Laravel Nova is a paid product. Why don't you guys ask them?

Closing it.

Thanks!
