### ISSUE TITLE
embedsMany same model multiple times

### ISSUE THREAD

**Issue by nulele** [jenssegers/laravel-mongodb#1590]
Hi,

is there a way to embed the same model multiple times inside a parent model through the embedsMany relation?

I have an ecommerce cart where the same article may have different weight, so I need to insert every article as a single row with jus one weight attribute. So if you add quantity 4 of an article, I have to split it in 4 rows each with quantity 1.

I know I can simply add one row and manage multiple weights with an array but I'm afraid this solution can complicate things.

Actually I managed to do this for inserting but I'm having trouble when saving or disocciating related models bacause they obviously has the same _id attribute, so every time I save or dissociate a row, this affect other rows with the same _id too.

Thanks!

**Comment by george-viaud** [comment]
Thinking on this further, this is likely very related to #1628 and #1618 if instead of an embedsMany you wanted to use a relational table.
