### ISSUE TITLE
'PHP Notice:  Array to string conversion in C:/xampp/htdocs/laravel5/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php on line 80 

### ISSUE THREAD

**Issue by danish-manzoor** [jenssegers/laravel-mongodb#1591]
**ProductFactory.php**
<?php

use Faker\Generator as Faker;

$factory->define(App\Product::class, function (Faker $faker) {
    return [
       	'name' => (string)$faker->word,
       	'details'=> (string)$faker->paragraphs,
       	'price'=> $faker->numberBetween(100,1000),
       	'stock'=> $faker->randomDigit,
       	'discount'=> $faker->numberBetween(2,30)
    ];
});
?>

And the migration of product
 public function up()
    {
        Schema::create('products', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name');
            $table->text('details');
            $table->integer('price');
            $table->integer('stock');
            $table->integer('discount');
            $table->timestamps();
        });
    }

**Comment by cincauhangus** [comment]
first of all, your error states MySql and this is a mongoDB plugin. second of all, posting the error and a bunch of code without any context won't get you far.
