### ISSUE TITLE
Unsupported driver [mongodb]

### ISSUE THREAD

**Issue by mojo2405** [jenssegers/laravel-mongodb#1593]
Hi,
I searched all possible solutions out there, but I'm still getting this annoying error.
I'm using : 
Centos 6.9
PHP 5.6.30
Laravel 5.4

Mongo extension is installed : 

php -m | grep mongo
mongo

I user laravel-mongodb v 3.2.23
I put inside config/app.php 
providers => [ .. 
Jenssegers\Mongodb\MongodbServiceProvider::class,
..]

When trying the API I'm getting : Unsupported driver [mongodb]

my model looks like this : 

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Notification extends Eloquent 
{
    protected $connection = 'mongodb';
}

I'm not using Lumen.
Any help will be appriciated.

**Comment by mojo2405** [comment]
none of those helped :(

**Comment by StevePorter92** [comment]
What version of the php-mongodb extension do you have installed? 

There is a legacy mongo and modern mongodb extension and php library. It looks like you may have the legacy one. You can find more information here https://docs.mongodb.com/ecosystem/drivers/php/#drivers
