### ISSUE TITLE
Hybrid relations and default connection

### ISSUE THREAD

**Issue by sebestenyb** [jenssegers/laravel-mongodb#1595]
Hi guys,

I'm a bit of a trouble with the hybrid relation I didn't have in v2.
I have two models, `User` and `Listing`.
`User` is a MySQL model, `Listing` is a MongoDB one.
A `User` hasMany `Listing`.

My default connection is MySQL, so originally I only specified it for the MongoDB model:

```
class Listing extends Model
{
    use SoftDeletes;
    protected $connection = 'mongodb';
```

If I try to access the related model, it will throw an exception:

```
return $listing->load('user')
```

```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function prepare() on null
```

If I specify the connection for the `User` model either way below, it works.
```
    protected $connection = 'mysql';
```

or
 
```
    public function getConnectionName()
    {
        return config('database.default');
    }
```

Any idea, what could cause this?
I'd appreciate any help, cheers :)

**Comment by solofeed** [comment]
+1, the same behavior

**Comment by jleonardolemos** [comment]
+1 same behavior, same fix
