### ISSUE TITLE
Sort by Relationship 

### ISSUE THREAD

**Issue by kushan2** [jenssegers/laravel-mongodb#1607]
How do we sort record by Relationship for example I have,

In my  model,

class UserProfile extends Moloquent
{
    protected $collection = 'user_profiles';

    public function companies() {
        return $this->hasOne('App\Models\Company', '_id', 'company');
    }
}

I want to sort UserProfile by Company name. Is it possible?

**Comment by george-viaud** [comment]
Perhaps sort companies by name, then iterate over the results, building a collection or array of users as you go using the inverse relationship `users()` in the `Company` model?

**Comment by kaseywright** [comment]
I have a situation in which I need to do this also. Has anyone found a resolution?
