### ISSUE TITLE
Filter date using where is not working

### ISSUE THREAD

**Issue by Giacomo92** [jenssegers/laravel-mongodb#1615]
Hi everyone,
I am trying to filtered a date field with where with this code:

`$users = User::where('custom_date', '=', new DateTime('today'))->get();`

Like the docs said [here](https://github.com/jenssegers/laravel-mongodb#dates)

I also read some issues, but none of those solutions are working for me.

Can you please help me with this?

Thank you

**Comment by Bowens20832** [comment]
Use an ISODate instead. 

```
$users = User::where('custom_date', '=', ISODate("2017-09-01T00:00:00.000Z"))->get();
```
