### ISSUE TITLE
hasMany relationship with ObjectID

### ISSUE THREAD

**Issue by Marcuss57** [jenssegers/laravel-mongodb#1617]
Hi all,

I know that there are already several tickets on this subject, but none of them answer concretely ...

I have a model "**PermissionModule**" that contains a **hasMany** to **PermissionCategory**.

In PermissionModule:

```php
    public function categories()
    {
        return $this->hasMany('App\Model\Permission\PermissionCategory', 'fk_permission_module_id', '_id')
                    ->orderBy('code', 'asc');
    }
```

This relation returns nothing **because fk_permission_module_id is an ObjectID**. If **I remove ObjectID**, the relationship works fine.

@jenssegers Is it possible to have a maj as soon as possible or a solution to use this relationship appropriately.

Thx all for help,

Marc

**Comment by xiaozhuai** [comment]
Hey, bro. @Marcuss57 
Did you solved this problem?
