### ISSUE TITLE
Add UUID support for _id field

### ISSUE THREAD

**Issue by altaraven** [jenssegers/laravel-mongodb#1621]
Please make it possible to use UUID as primary key. For example, doctrine can do this via annotations
```
/** @Id(strategy="UUID", type="string") */
private $id;
```

**Comment by mfauveau** [comment]
Hi @altaraven,

I made some modifications to be able to do just that. See this PR https://github.com/jenssegers/laravel-mongodb/pull/1611.

**Comment by altaraven** [comment]
Hello @mfauveau. Yes, I saw your PR. I just hope that package author will accept it or write his own. I also didn't get why you used `Binary` and not simple string

**Comment by Smolevich** [comment]
@altaraven, https://github.com/jenssegers/laravel-mongodb-core/issues/1

**Comment by divine** [comment]
Closing, merged in https://github.com/jenssegers/laravel-mongodb/pull/1611
