### ISSUE TITLE
Auth on laravel 5.7 not working normally

### ISSUE THREAD

**Issue by drmmyx** [jenssegers/laravel-mongodb#1622]
This is the user model
```
<?php


namespace SomeApp;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
// use Illuminate\Foundation\Auth\User as Authenticatable;
use Jenssegers\Mongodb\Auth\User as Authenticatable;


class User extends Authenticatable //implements MustVerifyEmail
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

```
This is the error 
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR)
Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\MySqlConnection given, called in `\vendor\jenssegers\mongodb\src\Jenssegers\Mongodb\Eloquent\Model.`
```

if i implements must verify email
```
class User extends Authenticatable implements MustVerifyEmail

```

it will cause the following error

```
Class SomeApp\User contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Auth\MustVerifyEmail::hasVerifiedEmail, Illuminate\Contracts\Auth\MustVerifyEmail::markEmailAsVerified, Illuminate\Contracts\Auth\MustVerifyEmail::sendEmailVerificationNotification)
```

**Comment by johannesschobel** [comment]
can you implement the 3 missing methods that are mentioned in the exception you got?

**Comment by johannesschobel** [comment]
yeah, of course you need to add your own business logic here..

**Comment by johannesschobel** [comment]
of course you need to create a mongodb connection..

**Comment by NHuebner1983** [comment]
@drmmyx Did you manage to get this working? I am having the same trouble here: https://github.com/jenssegers/laravel-mongodb/issues/1678

**Comment by azhar255** [comment]
Below Its Work For me
Please use this in User.php  

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;


class User extends Authenticatable implements MustVerifyEmail
{
    use MustVerifyEmail, Notifiable;

**Comment by appflush** [comment]
> Below Its Work For me
> Please use this in User.php
> 
> use Illuminate\Contracts\Auth\MustVerifyEmail;
> use Illuminate\Notifications\Notifiable;
> use Illuminate\Foundation\Auth\User as Authenticatable;
> use Illuminate\Contracts\Auth\MustVerifyEmail as MustVerifyEmailContract;
> 
> class User extends Authenticatable implements MustVerifyEmail
> {
> use MustVerifyEmail, Notifiable;

`use Illuminate\Contracts\Auth\MustVerifyEmail;`
have to
`use Illuminate\Auth\MustVerifyEmail;`
