### ISSUE TITLE
Date time parsing in Accessors

### ISSUE THREAD

**Issue by arju88nair** [jenssegers/laravel-mongodb#1624]
Hi, 
I am trying to parse the created_at to a readable format using  an Accessor method

 ```
public function getCreatedAtAttribute($value) {

                return Carbon::parse($value)->diffForHumans();

    }
```
which throws 

> DateTime::__construct(): Failed to parse time string (xxxxxxx) at position 11 (0): Unexpected character 

Anyway to work around this ? Digged a lot and couldn't find anything to solve this. Thank you

**Comment by george-viaud** [comment]
Would you post an example string in the error message `(xxxxxxx)` please?  (I don't think this has to do with laravel-mongodb)

**Comment by arju88nair** [comment]
@george-viaud That was the time shown in epoch format

**Comment by george-viaud** [comment]
I assume this is in your model?  If so, there is no need to pass a variable in, just do:

```
return $this->created_at->diffForHumans();
```

Laravel will auto-magically treat any `$dates` field as Carbon.

Hope this helps

**Comment by george-viaud** [comment]
Simple example from inside tinker using standard `Users` collection:

```
>>> \App\User::first()->created_at->diffForHumans();
=> "2 years ago"
```

**Comment by george-viaud** [comment]
Ahh.  Carbon doesn't take epoch time in this way.  Try createFromTimeStamp instead:

```Carbon::createFromTimeStamp(1540051389)->diffForHumans();```

**Comment by arju88nair** [comment]
Thanks
