### ISSUE TITLE
Unable to fetch embeded object directly where _id matches

### ISSUE THREAD

**Issue by george-viaud** [jenssegers/laravel-mongodb#1625]
I'm unsure of the correct approach here - I was hoping for an inverse reationship to "embedsMany" and "embedsOne" but can't seem to find it (if it exists).

I have an _id of what is a child object and wish to fetch it directly into a proper child object without iterating through the parent first.

doing something like the following returns empty:

```
$child = new ChildClass::where('_id', '=', $knownChildId)->first();
```
Any tips on how to do this would be wonderfully appreciated.

Many thanks!

**Comment by george-viaud** [comment]
So I was able to get what I want thought I hope there is a better way.

I implement a function in the child class that finds the instance of the parent which contains the matching child ID... then I filter where _id of the child = $id like so:

```
function getById($id) {
   return ParentClass::where('child_class._id', '=', $id)->first()->children()->where('_id', $id)->first();
}
```

Is there a better way to do this?

I'm worried about multiple-sublevels deep as I plan to use embedsmany in this way if possible.

However I can imagine needing to parse through `child1.child2.child3.child4._id` and then ->children->where('child2.child3.child4._id', $id)` and this solution then seems much less sexy

Your thoughts greatly appreciated

**Comment by LucasLeandro1204** [comment]
I do have the same problem =/
