### ISSUE TITLE
Does is set multiple servers / replica sets speed up my query ?

### ISSUE THREAD

**Issue by dekoci** [jenssegers/laravel-mongodb#1633]
At one time I want to add more members because of very large query usage,
I can still run queries if I only add only 1 host in my project and I checked my servers log and see connections between members also some queries handled by that server.

##### Multiple
`'host'     => ['mongo-01', 'mongo-02', 'mongo-03', 'mongo-04']`

##### Single
`'host'     => 'mongo-01'`

**Comment by vaneves** [comment]
Use MongoDB itself to replicate: https://docs.mongodb.com/manual/replication/
