### ISSUE TITLE
Strange behaviour, inside laradock

### ISSUE THREAD

**Issue by mhddenno** [jenssegers/laravel-mongodb#1634]
Hello everybody,

I am using Laravel 5.7.6, PHP 7.2.4 and mongodb using Laradock.
That problem that I am facing sounds strange. I can't find all the methods that supposed to be in an (jenssegers)Eloquent model. 
For example:
Retrieving All Models
`Model::all() ` works perfectly but using 'where' like this `Model::where(...)` gives error all the time. Therefore, my turnaround was as follows:
`Model::all()->where('Besitzer','$eq','bla bla');`
But I am not sure if that is a good way to do that.
Any ideas would be very helpful. 

Thanks in advance

**Comment by deviouspk** [comment]
`Model::all()->where('Besitzer','$eq','bla bla');`

that is pretty bad. It retrieves all possible models from the database first and then filters it based on your where statement. Can you post the error you are getting?
