### ISSUE TITLE
Windows 10 Class 'MongoDB\Driver\Manager' not found

### ISSUE THREAD

**Issue by davidmather** [jenssegers/laravel-mongodb#1636]
Windows 10 with Php 7.2.9 and the latest mongodb driver https://pecl.php.net/package/mongodb/1.5.3/windows following the installation instructions and it is working for most commands php artisan make:auth worked perfectly and created the database but it is throwing an error when using the php artisan migrate command:
Class 'MongoDB\Driver\Manager'  not found but the driver is definitely listed in php.ini. I have tried a few driver versions and am not sure which one will work.

**Comment by divine** [comment]
Hello,

This has nothing to do with this library, it's an issue with missing/incorrect settings for mongodb extension.
For more information see: https://jira.mongodb.org/browse/PHPC-656

Thanks.
