### ISSUE TITLE
belongsToMany without pivot

### ISSUE THREAD

**Issue by nulele** [jenssegers/laravel-mongodb#1646]
Hello,
I've been facing this annoying problem: cannot get related objects with belongsToMany **without** pivot collection.

The case: a company can have multiple payment methods.

My **companies** document contains this attribute:
```
"payment_method_ids" : [
    "5bbdd1f19a8920079943ba22", 
    "5bbdd2829a8920044e1b8dc2", 
    "5bbdd2c79a8920044e1b8dc4"
]
```

The **payment_methods** collection contains (for example) this document:
```
{ 
    "_id" : ObjectId("5bbdd1f19a8920079943ba22"), 
    "name" : "Bank Transfer", 
    "description" : "Lorem ipsum..."
}
```

My **Company** model contains this relation:
```
public function payment_methods()
{
    return $this->belongsToMany(PaymentMethod::class, null, 'payment_method_ids');
}
```

When I try to get payment methods from company I always get an empty collection:
`dd($company->payment_methods->toArray());`

Many thanks!

**Comment by marcnewton** [comment]
Hi, Two things I have observed.

**One**
I have found when using any relationship models with MondgoDB that it is best to specify the class model name only on all relations, leave all other attributes alone in every single model and it all works perfectly.

**Two**
In every single model, adding the following line also resolves a lot of issues :

`protected $appends = ['id'];`

**Comment by nulele** [comment]
Hi Marc,

thank you for the suggestion. I'll give it a try and will let you know...

**Comment by marcnewton** [comment]
Oh there is a 3rd observation too, When I found when being field selective in a parent model, you must also select the children's ids too when working a on a with() relation query..

Wont work: 
Parent::select(['name'])->with(['child'])->get()

Will work:
Parent::select(['name','child_id')->with(['child'])->get()

**Comment by tarikhagustia** [comment]
> Hi Marc,
> 
> thank you for the suggestion. I'll give it a try and will let you know...

hello @nulele , how to solve this problem?
