### ISSUE TITLE
Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereDate() {"userId":"5bfbada69dc6d67f4e0fdb4b","email":"onese@g000.cn","exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Jenssegers\\Mongodb\\Query\\Builder::compileWhereDate() at /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)

### ISSUE THREAD

**Issue by iPhonePKAndroid** [jenssegers/laravel-mongodb#1654]
[2018-11-26 17:57:09] pro.ERROR: Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereDate() {"userId":"5bfbada69dc6d67f4e0fdb4b","email":"youermai@g000.cn","exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Jenssegers\\Mongodb\\Query\\Builder::compileWhereDate() at /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
[stacktrace]
#0 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2917): Illuminate\\Database\\Query\\Builder::throwBadMethodCallException('compileWhereDat...')
#1 /Users/a/Downloads/fakajun/laravel/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(1158): Illuminate\\Database\\Query\\Builder->__call('compileWhereDat...', Array)
#2 /Users/a/Downloads/fakajun/laravel/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(954): Jenssegers\\Mongodb\\Query\\Builder->__call('compileWhereDat...', Array)
#3 /Users/a/Downloads/fakajun/laravel/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(235): Jenssegers\\Mongodb\\Query\\Builder->compileWheres()
#4 /Users/a/Downloads/fakajun/laravel/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(211): Jenssegers\\Mongodb\\Query\\Builder->getFresh(Array)
#5 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(516): Jenssegers\\Mongodb\\Query\\Builder->get(Array)
#6 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(500): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#7 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(77): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#8 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(482): Illuminate\\Database\\Eloquent\\Builder->first(Array)
#9 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->value('profit')
#10 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(385): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo(Object(Jenssegers\\Mongodb\\Eloquent\\Builder), 'value', Array)
#11 /Users/a/Downloads/fakajun/laravel/app/User.php(67): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call('value', Array)
#12 /Users/a/Downloads/fakajun/laravel/app/Http/Controllers/UserController.php(31): App\\User->jrsr()
#13 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): App\\Http\\Controllers\\UserController->overview(Object(Illuminate\\Http\\Request))
#14 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\UserController), 'overview')
#15 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#16 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Routing\\Route->run()
#17 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(684): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#42 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#43 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#44 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#45 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/a/Downloads/fakajun/laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#61 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#63 /Users/a/Downloads/fakajun/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#64 /Users/a/Downloads/fakajun/laravel/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#65 /Users/a/Downloads/fakajun/laravel/server.php(21): require_once('/Users/a/Downlo...')
#66 {main}
"}

**Comment by carsonlius** [comment]
same issue

**Comment by carsonlius** [comment]
[you can this solution](#https://github.com/jenssegers/laravel-mongodb/issues/1191)

**Comment by carsonlius** [comment]
[find this solution](#1191 )

**Comment by AkshayHere** [comment]
Cant believe this issue still unresolved but closed

**Comment by Smolevich** [comment]
@AkshayHere do you have same problem?

**Comment by AkshayHere** [comment]
Yes. 
Below is the same line of code i wrote in laravel
`$submittedApplications = Application::whereIn('currentStatusCode', $submittedStatusCodes)->whereDate('created_at', Carbon::now()->subDays(7))->get();`

I got the following error while execution
`[2020-04-01 15:12:56] dev.ERROR: Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereDate() {"exception":"[object] (BadMethodCallException(code: 0): Call to undefined method Jenssegers\\Mongodb\\Query\\Builder::compileWhereDate() at /home/hladmin/dennydev/hlas_pas2_akshay/laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:50)
[stacktrace]
#0 /home/hladmin/dennydev/hlas_pas2_akshay/laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3087): Illuminate\\Database\\Query\\Builder::throwBadMethodCallException('compileWhereDat...')`

I referenced to this stackoverflow solution
[https://stackoverflow.com/questions/46731298/laravel-search-for-records-7-days-old-only](url)

**Comment by divine** [comment]
> Cant believe this issue is still unresolved but closed

Its closed because it's a duplicate https://github.com/jenssegers/laravel-mongodb/issues/1536

It's not implemented yet, yes, after many years.

Next time search for issues and check for labels.

**Comment by AkshayHere** [comment]
Sorry but was unable to find any reference to the open issue.
Thanks a lot for the immediate response.
