### ISSUE TITLE
how to call stored functions from laravel

### ISSUE THREAD

**Issue by sankarbiswas07** [jenssegers/laravel-mongodb#1655]
i have enabled auth from mongodb config file. so i have to login using  id and pwd , which is written in env. and i have all set to fetch and insert in mongoDB.

but i have written a function 

```
db.system.js.save(
      {
       _id: "echoFunction",
       value : function(x) { return x; }
     }
   )
```
but how to call it from my laravel controller  ?

i have tried this : 
```
$cursor = DB::connection('mongodb')->command(array('eval' => 'echoFunction("4")'));
 $data = $cursor->toArray();
 dd($data);

```
but it show me an error 

> not authorized on xyz_db to execute command { eval: "echoFunction("4")", $db: "xyz_db", $readPreference: { mode: "primaryPreferred" }, lsid: { id: UUID("91e20240-dcd8-4d90-b6c0-c5bc97c95b6f") } }

it would be better if i can trigger this function from the driver.
thank you in advance.

**Comment by divine** [comment]
Hello,

You need to give permission to user, so it'll be authorized to run such commands.

Thanks.
