### ISSUE TITLE
updates only one piece of data

### ISSUE THREAD

**Issue by 1-bytes** [jenssegers/laravel-mongodb#1662]
**I need to update one data at a time .**
But I see that he just called "UpdateMany", no UpdateOne

vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php:
`    /**
     * @inheritdoc
     */
    public function update(array $values, array $options = [])
    {
        // Use $set as default operator.
        if (!starts_with(key($values), '$')) {
            $values = ['$set' => $values];
        }

        return $this->performUpdate($values, $options);
    }

    /**
     * Perform an update query.
     *
     * @param  array $query
     * @param  array $options
     * @return int
     */
    protected function performUpdate($query, array $options = [])
    {
        // Update multiple items by default.
        if (!array_key_exists('multiple', $options)) {
            $options['multiple'] = true;
        }

        $wheres = $this->compileWheres();
        $result = $this->collection->UpdateMany($wheres, $query, $options);
        if (1 == (int) $result->isAcknowledged()) {
            return $result->getModifiedCount() ? $result->getModifiedCount() : $result->getUpsertedCount();
        }

        return 0;
    }
`

The " 'multi' => false " parameter doesn't help me
what should I do?

I hope to get your help...
Best Regards :)

**Comment by EnzoTools** [comment]
lumen version 5.2
jenssegers/laravel-mongodb version 3.2.x

**Comment by samerzaki** [comment]
The same problem still exists

**Comment by samerzaki** [comment]
@1-bytes how you solved it ?
