### ISSUE TITLE
Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereInRaw()

### ISSUE THREAD

**Issue by ludo1960** [jenssegers/laravel-mongodb#1668]
Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereInRaw()

Brand new install laravel latest and Jenseggers\Mongodb latest

`var/www/laramongo.local.com/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php
            if ($matches['class'] != get_class($object) ||
                $matches['method'] != $method) {
                throw $e;
            }
 
            static::throwBadMethodCallException($method);
        }
    }
 
    /**
     * Throw a bad method call exception for the given method.
     *
     * @param  string  $method
     * @return void
     *
     * @throws \BadMethodCallException
     */
    protected static function throwBadMethodCallException($method)
    {
        throw new BadMethodCallException(sprintf(
            'Call to undefined method %s::%s()', static::class, $method
        ));
    }
}
 
Arguments
"Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereInRaw()"`

Any Idea what versions do work ?

**Comment by graphicmist** [comment]
Hey, What is the solution? my morphmany Relation is throwing the same error?

**Comment by atulmahankal** [comment]
I am also still facing same issue.
