### ISSUE TITLE
Can't connect mongo db version 2.4.9 

### ISSUE THREAD

**Issue by MoraesGil** [jenssegers/laravel-mongodb#1669]
Hi, I have a Unifi server with mongo 2.4.9, I've  tried so much php drivers and differents laravel-mongodb versions but still not connect, after 3 days, can anyone help the right version ?

**Comment by ludo1960** [comment]
what have you tried?

**Comment by MoraesGil** [comment]
Currently I work with PHP 7.1.12 and Laravel 5.5
I Tried 
Laravel 5.5 current project  and current jenssegers/laravel-mongodb
I've got message required mongo 3.0 and I've tried sue old versions 
and new projects with Laravel
5.0, 5.2 ,5.3 (also with PHP 5.6)
with jenssegers/laravel-mongodb
2.1, 2.2, 2.3

and somes PHP Drivers.
php_mongodb-1.2.9-5.6-ts-vc11-x64
php_mongodb-1.2.9-5.6-ts-vc11-x86
php_mongodb-1.3.4-5.6-ts-vc11-x86
php_mongodb-1.3.4-7.1-ts-vc14-x86
php_mongodb-1.4.0-5.6-ts-vc11-x86
php_mongodb-1.4.0-7.1-ts-vc14-x64
php_mongodb-1.4.0-7.1-ts-vc14-x86
php_mongodb-1.5.3-7.1-ts-vc14-x86

but no success =/

**Comment by MoraesGil** [comment]
> install the latest php mongodb driver first, forget the other ones

@ludo1960 but last php driver not support MongoDB 2.4 I guess, right?

well I installed php_mongodb-1.5.3-7.1-ts-vc14-x86
 with my Laravel 5.5 and Php 7.1.12
and this package
"jenssegers/mongodb":"3.3.*"

- php --ri mongodb | grep version
- MongoDB extension version => 1.5.3
- libbson bundled version => 1.13.0
- libmongoc bundled version => 1.13.0`


but

> Server at sever.local:27117 reports wire version 0, but this version of libmongoc requires at least 3 (MongoDB 3.0)
