### ISSUE TITLE
Class 'MongoDB\Driver\Manager' not found in homestead

### ISSUE THREAD

**Issue by khoant88** [jenssegers/laravel-mongodb#1682]
I install laravel and mongodb by homestead. When I register account then error Class 'MongoDB\Driver\Manager' not found is displayed. Please help me to fix it. Thank you so much

**Comment by Thedigit** [comment]
http://laradock.io/ is a better solution for local stacks.

you may need to add the mongodb extension to your php and reload php.

**Comment by divine** [comment]
Hello,

See this comment how to install mongodb with homestead
https://github.com/jenssegers/laravel-mongodb/issues/1163#issuecomment-391971560

Thanks.
