### ISSUE TITLE
how can i use bulkWrite for Update query ?

### ISSUE THREAD

**Issue by savendra92** [jenssegers/laravel-mongodb#1683]
**my query is**

        require('vendor/mongodb/mongodb/src/BulkWriteResult.php');
        $bulk = new \MongoDB\Driver\BulkWrite();
        foreach ($request->allocation_data as $key => $value) {
                $bulk->update(
                                          ["userid" => $value],
                                          [  '$set' => [ "flag" => 1,  "status" => "Allocated" ]  ]
                                   ); } 
       $manager = new \MongoDB\Driver\Manager('mongodb://localhost:27017');
       $result = $manager->executeBulkWrite('db.collection', $bulk);

**from where i can import  $bulk and $manager object in this library, 
i don't want to use mongodb connection again**

**Comment by puuble** [comment]
+ rep

**Comment by jmikola** [comment]
Apologies for bumping an old issue, but I just came across this while researching whether the this library provides an API for bulk writes. #500 does not address the original question and the response in that issue also appears to conflate multi-document update and delete operations with the bulk write API found in MongoDB drivers. The [`update`](https://www.mongodb.com/docs/manual/reference/command/update/) and [`delete`](https://www.mongodb.com/docs/manual/reference/command/delete/) commands allow specifying multiple write _statements_, each of which may apply to one or multiple _documents_ matching the query filter.

The discussion in #2316 may be more accurate, as it demonstrates using `raw()` to access the underlying `MongoDB\Collection` object to invoke [`MongoDB\Collection::bulkWrite()`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBCollection-bulkWrite/). That method would allow an application to issue a single `update` command consisting of many individual update operations, and is the [library](https://github.com/mongodb/mongo-php-library) equivalent of the OP's code using `foreach` to iteratively stage operations on a [`MongoDB\Driver\BulkWrite`](https://www.php.net/manual/en/class.mongodb-driver-bulkwrite.php) object prior to execution.

Best I can tell, this library does not provide an API for issuing bulk writes, short of using `raw()` or some other escape hatch to access the library or extension directly.
