### ISSUE TITLE
How can access mongodb remotely in mlab.com?

### ISSUE THREAD

**Issue by borysfranko11** [jenssegers/laravel-mongodb#1694]
I tried  to connect mongodb  remotely mlab.com with laravel.

Mongodb version: 3.6
Laravel version: 5.2

        'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('DB_HOST', 'localhost'),
            'port'     => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE', ''),
            'username' => env('DB_USERNAME', ''),
            'password' => env('DB_PASSWORD', ''),
            'options' => [
                'database' => env('DB_DATABASE', '') // sets the authentication database required by mongo 3
            ]
        ],
I used this one.  
In local, it works fine. but when access remotely, it says authenticaton failed.
How can i solve this issue?

**Comment by blongho** [comment]
@borysfranko11 @divine  did you find an answer to this problem?
