### ISSUE TITLE
MongoQueryBuilderEngine support datatable 8.x + laravel 5.7

### ISSUE THREAD

**Issue by drsaluml** [jenssegers/laravel-mongodb#1699]
namespace App;

use Yajra\DataTables\QueryDataTable;
use Illuminate\Http\Request;

class MongoQueryBuilderEngine extends QueryDataTable {

    public function __construct($model,Request $request)
    {
        parent::__construct($model->getQuery(),$request);
        $this->query      = $model;
        $this->query_type = 'eloquent';
    }
    
    protected function compileQuerySearch($query, $column, $keyword, $relation = 'or')
    { 
        $query->orWhere(''.$column.'','like','%'.$keyword.'%');
    }
    
    public function count()
    {
        $myQuery = clone $this->query;
        return $myQuery->count();
    }
    
    public function ordering() {
        collect($this->request->orderableColumns())
            ->map(function ($orderable) {

                $orderable['name'] = $this->getColumnName($orderable['column'], true);

                return $orderable;
            })
            ->reject(function ($orderable) {
                
                return $this->isBlacklisted($orderable['name']) && ! $this->hasOrderColumn($orderable['name']);
            })
            ->each(function ($orderable) {
                $column = $this->resolveRelationColumn($orderable['name']);

                if ($this->hasOrderColumn($column)) {
                    $this->applyOrderColumn($column, $orderable);
                } else {
                    $nullsLastSql = $this->getNullsLastSql($column, $orderable['direction']);
                    $normalSql = $this->wrap($column) . ' ' . $orderable['direction'];
                    $sql = $this->nullsLast ? $nullsLastSql : $normalSql;
                    $this->query->orderBy($this->wrap($column), $orderable['direction']);
                }
            });
    }
    
    public function paging()
    {
        $this->query->skip((int)$this->request->start)
                    ->take((int) $this->request->length > 0 ? (int)$this->request->length : 10);
    }
    
}

## use function

use App\MongoQueryBuilderEngine;

-----------
$datatables = new MongoQueryBuilderEngine($data,$request->capture());
return $datatables->make(true);

## issue
- cannot support sort order by desc | asc

**Comment by mts88** [comment]
How did you editColumn or added new one?

**Comment by mts88** [comment]
> How did you editColumn or added new one?

Solved by myself after saw the exetended class. Thanks, solution works!
