### ISSUE TITLE
Unrecognized expression '$toString' in Aggregate.php

### ISSUE THREAD

**Issue by rupendradhiman-kiwi** [jenssegers/laravel-mongodb#1701]
I have issue on QA environment.
I am running a project using Docker. Docker configuration are same on all environments.
But the issue is only on QA.

We are trying to convert _id from object to string.

**laravel.ERROR: Unrecognized expression '$toString'**

**Comment by luisalvesjb** [comment]
tomou no cu

**Comment by brunoassiscarvalho** [comment]
This is about mongo version, in documentation [$toString](https://docs.mongodb.com/manual/reference/operator/aggregation/toString/), only in version 4 above. I have the same problem, and I resolved with { $convert: { input: <expression>, to: "string" } }.
