### ISSUE TITLE
Add collation to query

### ISSUE THREAD

**Issue by AliN11** [jenssegers/laravel-mongodb#1708]
I want to search case-insensitive items and didn't find a way except using `like`
But in MongoDB docs there are some options to do so.
[See here](https://docs.mongodb.com/manual/core/index-case-insensitive/)

`db.fruit.find( { type: "apple" } ).collation( { locale: 'en', strength: 2 } )`
Is there anyway to add collation to query like above query?

**Comment by AliN11** [comment]
I have this problem too.

**Comment by stefangeorgescu** [comment]
This would be really useful. Maybe as a third argument for orderBy?

**Comment by lukasamd** [comment]
It's possible to set collation in aggreagate function in second argument (options).

**Comment by matthias-influry** [comment]
I had to dive into the code to figure it out, but you can set a collation for a query through the `options` method of the Mongo Eloquent Model.
Your example would translate to something like
```php
Fruit::where('type', 'apple')->options([
    'collation' => [
        'locale' => 'en',
        'strength' => 2
    ]
])->get();
```

**Comment by GlauberF** [comment]
@matthias-influry can I configure these collation options globally, so that it works this way for all queries?

**Comment by matzeso** [comment]
@GlauberF  I am not working with this package at the moment, but in Eloquent you can overwrite the default query builder (see https://laravel.com/api/8.x/Illuminate/Database/Eloquent/Model.html#method_newEloquentBuilder) or just the query (see https://laravel.com/api/8.x/Illuminate/Database/Eloquent/Model.html#method_newQuery). 

So I'd try to make a BaseModel, that overwrites `newQuery` and then extend all other models from that BaseModel.
Not sure if it works with the mongodb eloquent though.
