### ISSUE TITLE
Having issue connecting AWS DocumentDB

### ISSUE THREAD

**Issue by yul-klj** [jenssegers/laravel-mongodb#1709]
Having issue connecting AWS DocumentDB with the DSN configuration, as it connects with ssl and pem file has to be with the connection, kindly help on this issue

Laravel version: 5.5
jenssegers/laravel-mongodb Version: 3.3.1

**Comment by Smolevich** [comment]
Do you use this package for connection to AWS DocumentDB?

**Comment by Smolevich** [comment]
Did you try use official sdk [AWS SDK](https://github.com/aws/aws-sdk-php)?

**Comment by george-viaud** [comment]
We are also having issues connecting to DocumentDB.  How to configure laravel-mongodb to use SSL/TLS ?

**Comment by george-viaud** [comment]
So the problem here seems to be that, while it's possible to put a `stream_context_create()` inside the config, it doesn't survive the caching process (i.e. the object instance is destroyed by var_export when caching the data)...  I think the best likely fix here is to make config aware of the structure of special keyword 'context' and then assemble this stream_context_create() into the cached file...

For reference here is my config:
```
'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('DB_HOST', env('DB_HOST')),
            'port' => env('DB_PORT', env('DB_PORT')),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options' => [
                'ssl' => true,
            ],
            'driver_options' => [
                'context' => stream_context_create([
                    'ssl' => [
                        'local_cert' => '/var/www/.ssh/id_rsa',
                        'cafile' => '/var/www/.ssh/rds-combined-ca-bundle.pem',
                        'allow_self_signed' => true,
                        'verify_peer' => false,
                        'verify_peer_name' => false,
                        'verify_expiry' => false,
                    ]
                ])
            ]
        ]
```

And here is the config:clear function which is caching using var_export:

```
/**
     * Execute the console command.
     *
     * @return void
     */
    public function fire()
    {
        $this->call('config:clear');

        $config = $this->getFreshConfiguration();

        $this->files->put(
            $this->laravel->getCachedConfigPath(), '<?php return '.var_export($config, true).';'.PHP_EOL
        );

        $this->info('Configuration cached successfully!');
    }
```

**Comment by george-viaud** [comment]
> Do you use this package for connection to AWS DocumentDB?

AWS DocumentDB is a managed DB solution which is MongoDB compatible.

By default it is strongly configured and uses SSL/TLS with certificate requirements.  To configure this through php mongodb drivers, a stream_context_create() is needed, which doesn't survive the config caching process (ends up as a NULL in the bootstrap config cache).

A long while ago (likely before config caching?) these options actually worked, see the following PR / Merge for reference: https://github.com/jenssegers/laravel-mongodb/pull/460

**Comment by george-viaud** [comment]
Ok I think I see how to fix this - inside Connection.php we need to make an exception inside `driver_options` for `context` such that it can be an array, and will be used to create a `stream_context` runtime.  I'll give this a go.

**Comment by george-viaud** [comment]
PR1751 should fix this problem.

Note that your database.php will need to look something like this:
```
        'mongodb' => [
            'driver' => 'mongodb',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options' => [
                'ssl' => true,
            ],
            'driver_options' => [
                'context' => [
                    'ssl' => [
                        'local_cert' => '/home/ubuntu/.ssh/rds-combined-ca-bundle.pem',
                        'allow_self_signed' => true,
                        'verify_peer' => true,
                        'verify_peer_name' => true,
                        'verify_expiry' => true,
                    ]
                ]
            ]
        ]
```

**Comment by george-viaud** [comment]
@yul-klj - would you be able to try the proposed code change in GH-1751?  Additional voices with this problem being solved may help promote this MR to @jenssegers

**Comment by luhuiya** [comment]
@george-viaud did you solve this issue?

**Comment by george-viaud** [comment]
@yul-klj indeed, see my post above with PR GH-1751 and description of necessary database.php modifications.

Note: We're running Laravel 5.2 so YMMV

**Comment by luhuiya** [comment]
i end up override the service provider to setting the connection as i require

**Comment by divine** [comment]
Closing. See this issue for possible solution https://github.com/jenssegers/laravel-mongodb/issues/2077
