### ISSUE TITLE
v3.5.0 bug, updated document has duplicated update time attribute

### ISSUE THREAD

**Issue by tenstep** [jenssegers/laravel-mongodb#1716]
the model i use is as follow:
`class Event extends Model`   
`{`   
   `protected $collection = 'event';   `
   `const CREATED_AT = 'create_time';`   
   `const UPDATED_AT = 'update_time';`   
`}`
when i update an exist document, the result is :
`{`
    `"_id": ObjectId("5c77ec4f48079835183e08c4"),`
    `"update_time": ISODate("2019-02-28T14:12:31.000Z"),`
    `"create_time": ISODate("2019-02-28T14:12:31.000Z"),`
    `"event": {`
        `"update_time": ISODate("2019-03-01T04:37:33.000Z")`
    `}`
`}` 
there's an extra sub dcoument "event" with the new "update_time" attribute in the original document,
the problem appears in latest version v3.5.0

**Comment by rennokki** [comment]
Can confirm, this happens to me too.

**Comment by Smolevich** [comment]
@rennokki, this problem fixed in [commit sha](https://github.com/jenssegers/laravel-mongodb/commit/bdb15c948cb1f3d703df0996753d7e5336950bee) and latest release of library will be work correctly

**Comment by rennokki** [comment]
Guess this has to be closed?

**Comment by Smolevich** [comment]
@rennokki, i think yes

**Comment by rennokki** [comment]
@tenstep @jenssegers Close this pls?
