### ISSUE TITLE
Laravel authentication and a "FAT" user

### ISSUE THREAD

**Issue by sstativa** [jenssegers/laravel-mongodb#1718]
This is not the issue, however, it might be in some cases.

As we know Laravel pulls the user's record on every request protected by "auth" middleware, even if the request does not require the user's data. 
Usually, if the user's document is small there is no harm to have an extra request, however, if the user's document is larger than 1 MB, retrieving user's data will be just a waste of server's resources. 

Is there any best practice to resolve this situation? I mean is there a better way to check that user is authenticated without retrieving the data from DB? I have several ideas in mind (custom user provider, caching), but I'm wondering if there is already a solution for this.

**Comment by gotys** [comment]
Use sessions, they take couple of bytes

**Comment by sstativa** [comment]
I'm not sure what do you suggest.

`Auth::check()` will pull the whole document from MongoDB on each request. If my users' records are 1MB on average that means on each request Laravel will pull 1Mb from Mongo.
100 req/seconds = 100MB/s from Mongo. 

Probably there should be a way for laravel-mongo, to select a limited set of fields on Auth and a full document on a request. 

As for myself, I created a custom UserProvider that uses only a limited set of fields and caches that record in Redis. Then I use something like this `User::findOne(Auth::id())`. It's ugly, but it works and does not "waste" a lot of memory. I assume the issue can be closed.

**Comment by gotys** [comment]
Aaah, ok you would probably need to override laravel's check method to pull only the fields you want. What you did with Redis is good
