### ISSUE TITLE
Help with query: aggregate, distinct and count

### ISSUE THREAD

**Issue by CientistaDaWeb** [jenssegers/laravel-mongodb#1721]
Hello, I need help in formulating a query.

I have the following collection:

[{"_id":ObjectId("5c3a25dd2f18ce0f975aa072"),"content":{"@attributes":{"versao":"4.00","Id":"NFe43190192091065000108650010000756521530484785"},"det":[{"@attributes":{"nItem":"1"},"prod":{"cEAN":"7891058017392"}},{"@attributes":{"nItem":"2"},"prod":{"cEAN":"7899470802565"}}]},"transferency":0},{"_id":ObjectId("5c3a25dd2f18ce11bc32d3c2"),"content":{"@attributes":{"versao":"4.00","Id":"NFe24181235647759000145650010000716891370378403"},"det":[{"@attributes":{"nItem":"1"},"prod":{"cEAN":"7896523207803"}},{"@attributes":{"nItem":"2"},"prod":{"cEAN":"7896004712147"}}]},"transferency":0},{"_id":ObjectId("5c3a25dd2f18ce0fa650c942"),"content":{"@attributes":{"versao":"4.00","Id":"NFe24181235647759000145650010000744371160708268"},"det":[{"@attributes":{"nItem":"1"},"prod":{"cEAN":"7896637023115"}},{"@attributes":{"nItem":"2"},"prod":{"cEAN":"7896523214351"}}]},"transferency":0}]

I need to search this collection of sales to find out which products are best sold together with others, I thought the following instructions:
1) pick up only records that have "tranferency: 0"
2) get only records that the element "content.det" is an array
3) filter so that the "content.det.prod.cEAN" has an informed value
4) return the "content.det.prod.cEAN" distinct and with a count of occurrences with limit of 15 documents

until the moment I arrived in this script, but still not bringing me what I want:

db.getCollection ('exit_invoices'). aggregate ([
    {
        $match: {
            'content.det.1': {$exists: true},
            'transference': 0,
            'content.det': {
                "$elemMatch": {
                    "prod.cEAN": {
                        "$ all": [
                            "7896714205823"
                            ]
                        }
                    }
                }
            }
    },
    {
        $group: {
            _id: {
                ean: '$content.det.prod.cEAN'
            },
            notes: {$addToSet: '$content. @attributes.Id'}
        }
    },
    {
        $unwind: "$ notes"
    },
    {
        $group: {_id: "$ _id", invoicesCount: {$sum: 1}}
    },
    {
        $sort: {invoicesCount: -1}
    },
    {
        $limit: 15
    },
    {
        $project: {
            "ean": "$ean",
            'notes': '$invoicesCount'
        }
    },
], {allowDiskUse: true})

**Comment by Smolevich** [comment]
@CientistaDaWeb, this problem is actual for you?
