### ISSUE TITLE
 Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::getOwnerKey()

### ISSUE THREAD

**Issue by msacar** [jenssegers/laravel-mongodb#1725]
```
 Classified::has('user.info')
                  ->limit(5)
                  ->get();
```

throws  Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsTo::getOwnerKey()  

But its fine when i delete use HybridRelations ; from Classified model

**Comment by msacar** [comment]
Okey,  i fixed    with 
` protected $connection      = "mysql";
`

**Comment by Smolevich** [comment]
It was fixed [here](https://github.com/jenssegers/laravel-mongodb/pull/1724). It linked with cnanges n [laravel framework](https://github.com/laravel/framework/commit/2ee18923eaff142a89439f0adf0d3f15c30db85b)

**Comment by Smolevich** [comment]
@msacar , this issue is actual for you?

**Comment by divine** [comment]
Closing, merged in https://github.com/jenssegers/laravel-mongodb/pull/1724
