### ISSUE TITLE
updateOrCreate dont work with unique index in matching attribute

### ISSUE THREAD

**Issue by fabiel-leon** [jenssegers/laravel-mongodb#1730]
#updateOrCreate dont work with unique index in matching attribute

## mongo 3.6, laravel 5.7, php 7.1.3
`
$te = TipoEvento::updateOrCreate(['attr' => "hello"]);
//field denominacion is unique index
Evento::updateOrCreate(['denominacion' => "Santiago"],['tipo_id' => $te->_id]);
`
   MongoDB\Driver\Exception\BulkWriteException  : E11000 duplicate key error collection: suitdo_db.evento index: denominacion_1 dup key: { : "Santiago" }

**Comment by Smolevich** [comment]
@fabiel-leon, 
Describe structure models. I see two models `TipoEvento` and `Evento` in description.
True way for understanding problem: 

1. Clear collection `suitdo_db.evento`
2. Show indexes for collection `suitdo_db.evento`
3. Show full php code
