### ISSUE TITLE
Query on list of reference

### ISSUE THREAD

**Issue by Pescu** [jenssegers/laravel-mongodb#1735]
Hello, I have some problems with some query building. For example, we could say that I have a model (User) with a field that is a list of reference for another model (Toys). I need to take the Users that have in the list a Toy with a specific field. I tried to take first the Toy with the specific field and also using an aggregation query but with no success. 

I tried: 
$codedef = array("abc");
$toy = Toy::where('codeDef', 'all', array($codedef))->first();

User::where('toys', 'all', array($toy))->first();
and also
User::where('toys', 'all', array($toy->_id))->first();

but with no results.

**Comment by Pescu** [comment]
@Smolevich Hello, I tryed what you propose but seems that Laravel cannot found "App\Http\Controllers\MongoDB\BSON\ObjectId' not found" in the MongoDB lib.

**Comment by Smolevich** [comment]
Namespace starts with `\MongoDB`

**Comment by Pescu** [comment]
Ohh, I wasn't importing the lib, cheers!!
