### ISSUE TITLE
can you please make $lookup to connect to mysql database?

### ISSUE THREAD

**Issue by drevendy** [jenssegers/laravel-mongodb#1737]
i have 2 tables, 'teachers' on mongodb and 'class' on mysql. i want to get data from table 'teachers' on mongo and group by column 'date'. i need to sum column 'class_qty' in table 'class' on mysql. i use aggregate query to do that. so i need to use $lookup to make relation between mongodb and mysql. btw, the framework i used is Laravel.  can you make $lookup to connect to mysql? or do you have another idea how to do this? here is the example code:

$data = Teaches::raw(function ($collection) {
            return $collection->aggregate([
                [
                    '$match' => [
                        'status' => 1
                    ]
                ],
                [
                    '$lookup' => [
                        'connection' => 'mysql',
                        'localField' => 'classId',
                        'from' => 'class',
                        'foreignField' => 'id',
                        'as' => 'class'
                    ]
                ],
                [
                    '$group'    => [
                        '_id'   => [
                            'month' => [
                                '$month' => '$created_at'
                            ],
                            'day' => [
                                '$dayOfMonth' => '$created_at'
                            ],
                            'year' => [
                                '$year' => '$created_at'
                            ]
                        ],
                        'total' => [
                            '$sum'  => '$class.class_qty'
                        ]
                    ],
                ]
            ]);
        });

**Comment by Smolevich** [comment]
I think that isn't possible. You can get collection using function with. See [tests](https://github.com/jenssegers/laravel-mongodb/blob/master/tests/HybridRelationsTest.php#L179-L182)
