### ISSUE TITLE
Exist uniqueness validation not handled by Jensseger

### ISSUE THREAD

**Issue by naveedyasin** [jenssegers/laravel-mongodb#174]
I have a registration form with unique email validation, when i enter multiple duplicate emails it does not apply unique validation for email i have rules below, Note: i am using mongodb.
public static $rules = array(
        'email' => 'required|email|unique:users'  
    );

**Comment by joebenson** [comment]
In case someone runs into this again, the likely culprit is if you're using multiple database connections and MongoDB is not your default. In this case, you must set the presence verifier's connection to your MongoDB connection key prior to validating, then all should work well.

One way to do it is in the authorize() method of a custom FormRequest class (because it is called prior to validate()). Example:

```php
public function authorize(){
	// Make MongoDB the presence verifier
	$this->getValidatorInstance()->getPresenceVerifier()->setConnection('mongodb');
	// in this case we're authorizing any user
	return true;
}
```

**Comment by rolodef1** [comment]
> In case someone runs into this again, the likely culprit is if you're using multiple database connections and MongoDB is not your default. In this case, you must set the presence verifier's connection to your MongoDB connection key prior to validating, then all should work well.
> 
> One way to do it is in the authorize() method of a custom FormRequest class (because it is called prior to validate()). Example:
> 
> ```
> public function authorize(){
>     // Make MongoDB the presence verifier
>     $this->getValidatorInstance()->getPresenceVerifier()->setConnection('mongodb');
>     // in this case we're authorizing any user
>     return true;
> }
> ```

Other solution is to specify the database connection in unique validation

`'email' => 'unique:mongodb.users,email_address'`

**Comment by mtcarvalho** [comment]
This works well for string values, but could/should it work for integers?

I added an rule like `'city' => 'required|integer|exists:cities,id',`

but it always says that the city I passed don't exist, however it exists on database.

I already tried like `'city' => 'exists:mongodb.cities,id',`

but neither passed. I just have one mongodb database in my Laravel 6 app.
