### ISSUE TITLE
Eager loading embedded relation sets erroneus parent relation to root object

### ISSUE THREAD

**Issue by BenjaminOwlient** [jenssegers/laravel-mongodb#1743]
As said in title. Eager loading embedded objects, either by "with" or a late "load", sets an erroneous parent relation to the root object. This makes the save function ineffective.

**Comment by mdandidarmawan** [comment]
Why this was closed? @divine

**Comment by divine** [comment]
@mdandidarmawan please kindly stop spamming on old issues. If you have a problem create a new issue.
