### ISSUE TITLE
No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling ismaster on '..docdb.amazonaws.com:27017']

### ISSUE THREAD

**Issue by VirendraArekar** [jenssegers/laravel-mongodb#1752]
'mongodb' => [
        'driver'   => 'mongodb',
        'host' => [env('MONGO_DB_HOST')],
        'port'     => env('MONGO_DB_PORT'),
        'database' => env('MONGO_DB_DATABASE'),
        'username' => env('MONGO_DB_USERNAME'),
        'password' => env('MONGO_DB_PASSWORD'),
        'options'  => [
            'ssl' => true,
            'database' => env('MONGO_DB_DATABASE')
        ],
        'driver_options' => [
            'context' => stream_context_create( [
                'ssl' => [
                    'cafile'     =>   base_path('rds-combined-ca-bundle.pem'),
                    'allow_self_signed' => true,
                    'verify_peer'       => false,
                    'verify_peer_name'  => false,
                    'verify_expiry'     => false,
                ]

            ])
        ]
                ],

No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling ismaster on '..docdb.amazonaws.com:27017'] please Guide me.For previous one server this setting is working but for new server it unable to connect and showing this error message.

**Comment by george-viaud** [comment]
Please see GH-1751 as this should solve your problem.  You can not use `stream_context_create()` inside the config because it is lost to cache encoding.  Please let me know if this solves your problem - I'd love to get that PR merged - thanks and good luck.
