### ISSUE TITLE
has() and whereHas() not working with version ^3.1

### ISSUE THREAD

**Issue by Yeenot** [jenssegers/laravel-mongodb#1756]
php: 5.6.27
laravel/lumen-framework: 5.3.*
laravel-mongodb: ^3.1

has and whereHas are not working with two different connections (mysql and mongodb) and has an error of 

Call to undefined method Illuminate\\Database\\Query\\Builder::getRelationWithoutConstraints()

I need to maintain the php version and lumen version since it is an existing project

**Comment by divine** [comment]
See https://github.com/jenssegers/laravel-mongodb/pull/1195
