### ISSUE TITLE
How to support 'REGEXP' operator in laravell

### ISSUE THREAD

**Issue by psanjib** [jenssegers/laravel-mongodb#1758]
i have written a simple query using "REGEXP" operator it's not working

```
$comments = new Comment;
$query = $comments::where('title', 'REGEXP', '8183|81600')->get();
```

It returns all record. It should return only 2 record. i have tested by writing Sql Query
Raw Sql query - `SELECT * FROM Test where title REGEXP '8183|81600'`; It is working fine.

Please find the attached image, records available in the DB.
![table-data](https://user-images.githubusercontent.com/1003735/57695483-05f50500-766c-11e9-99f6-c56893fb0dab.png)

Anyone can help about this.

Thanks

**Comment by Smolevich** [comment]
@psanjib, show the model definition please. Is the property connection mysql?
