### ISSUE TITLE
Native mail verification not working with jenseggers mongo-db

### ISSUE THREAD

**Issue by McMazalf** [jenssegers/laravel-mongodb#1759]
Following the guide to implement Mail verification brings to an error

`"Class App\User contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\Contracts\Auth\MustVerifyEmail::hasVerifiedEmail, Illuminate\Contracts\Auth\MustVerifyEmail::markEmailAsVerified, Illuminate\Contracts\Auth\MustVerifyEmail::sendEmailVerificationNotification)`

Does anyone have a fix for this?

**Comment by nicolasyousician** [comment]
Hey @McMazalf 

This is not related to this package at all. You are implementing a contract that requires you to have three methods in your model. You either write those youself (the error tells you what the methods are) or you implement the following trait `Illuminate\Auth\MustVerifyEmail` from laravel that contains an out of the box implementation for you.

**Comment by divine** [comment]
Closed, merged in https://github.com/jenssegers/laravel-mongodb/pull/1933
