### ISSUE TITLE
addColumn not use

### ISSUE THREAD

**Issue by sixwalker** [jenssegers/laravel-mongodb#1770]
use it like this

        $Blueprint  = new Blueprint(DB::connection(),'goods_sku');
        $Blueprint->addColumn('string','title');
run ok,but the Column not in the collection,now I don`t know how to do

**Comment by nicolasyousician** [comment]
Hey @sixwalker , you can't define your columns this way, I think it's stated in the documentation. Someone can correct me if I'm wrong, but given the nature of mongodb, you don't need to define your columns.

**Comment by Smolevich** [comment]
@sixwalker, do you solve your problem?
