### ISSUE TITLE
Is the package compatible with the laravel-ide-helper?

### ISSUE THREAD

**Issue by salexfo** [jenssegers/laravel-mongodb#1772]
Here is the URL of the ide-helper repo:
https://github.com/barryvdh/laravel-ide-helper

Thanks,
Alexander

**Comment by Smolevich** [comment]
@salexfo, I think that this package is compatible. Any difficulties?

**Comment by Smolevich** [comment]
@salexfo, see [issue](https://github.com/jenssegers/laravel-mongodb/issues/1785)

**Comment by salexfo** [comment]
@Smolevich thank you!
