### ISSUE TITLE
Error trying to display timestamps in a blade file

### ISSUE THREAD

**Issue by fbc** [jenssegers/laravel-mongodb#1778]
When I try to use:
`{{$profile->updated_at}}`

I get an error like this:
`
/home/ubuntu/xxx/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php
 
            // Prepend mock datetime only if the format does not contain non escaped unix epoch reset flag.
            if (!preg_match("/{$nonEscaped}[!|]/", $format)) {
                $format = static::MOCK_DATETIME_FORMAT.' '.$format;
                $time = ($mock instanceof self ? $mock->rawFormat(static::MOCK_DATETIME_FORMAT) : $mock->format(static::MOCK_DATETIME_FORMAT)).' '.$time;
            }
 
            // Regenerate date from the modified format to base result on the mocked instance instead of now.
            $date = self::createFromFormatAndTimezone($format, $time, $tz);
        }
 
        if ($date instanceof DateTimeInterface) {
            $instance = static::instance($date);
            $instance::setLastErrors($lastErrors);
 
            return $instance;
        }
 
        if (static::isStrictModeEnabled()) {
            throw new InvalidArgumentException(implode(PHP_EOL, $lastErrors['errors']));
        }
 
        return false;
    }
 
    /**
     * Create a Carbon instance from a specific format.
     *
     * @param string                          $format Datetime format
     * @param string                          $time
     * @param \DateTimeZone|string|false|null $tz
     *
     * @throws InvalidArgumentException
     *
     * @return static|CarbonInterface|false
     */
    public static function createFromFormat($format, $time, $tz = null)
    {
        $function = static::$createFromFormatFunction;
 
Arguments
"""
Unexpected data found.
Unexpected data found.
Unexpected data found.
Trailing data (View: /home/ubuntu/xxx/resources/views/profile/show.blade.php)
"""
`
Looks like it might be a CARBON related issue..

**Comment by fbc** [comment]
found my fix... added this to my model:
protected $dateFormat = 'Y-m-d H:i:s';

**Comment by Smolevich** [comment]
@fbc, issue is actual?

**Comment by fbc** [comment]
Nope I figured it out..
