### ISSUE TITLE
ISODate used for query but the query parsed by mongodb Eloquent used numberlong

### ISSUE THREAD

**Issue by minhnh94** [jenssegers/laravel-mongodb#1781]
My query using Eloquent looks like this
`$builder->where(['time' => ['$gt' => new UTCDateTime($dates[0]->timestamp * 1000), '$lt' => new UTCDateTime($dates[1]->timestamp * 1000)]]);`

But the raw query that was parsed by Eloquent (it was captured by Debugbar) seems to be using numberLong for querying datetime
`model.find({"$and":[{"action":{"$in":["add"]}},{"time":{"$gt":{"$date":{"$numberLong":"1531811040000"}},"$lt":{"$date":{"$numberLong":"1563347040000"}}}}]})`

I want the parsed query to use ISODate instead of numberLong for querying.
Is this possible?

**Comment by Smolevich** [comment]
Is the query `model.find({"$and":[{"action":{"$in":["add"]}},{"time":{"$gt":{"$date":{"$numberLong":"1531811040000"}},"$lt":{"$date":{"$numberLong":"1563347040000"}}}}]})` returned not correct data?
