### ISSUE TITLE
How to use insert options ?

### ISSUE THREAD

**Issue by wanghanwanghan** [jenssegers/laravel-mongodb#1782]
I haven't found a location where I can pass in this parameter, such as:
```php
DB::collection->doc->insert([
   ['foo1'=>'bar1'],
   ['foo2'=>'bar2'],
   ...
],[
   ['ordered'=>true],
]);
```

**Comment by wanghanwanghan** [comment]
help me ~

**Comment by Smolevich** [comment]
What reason of using this case?

**Comment by wanghanwanghan** [comment]
@Smolevich When many data are inserted at the same time, I hope that nonexistent data can be inserted successfully.

**Comment by Smolevich** [comment]
Options can't be sent as argument
You can use `DB::getMongoClient();` and use bulk write `https://www.php.net/manual/ru/mongodb-driver-manager.executecommand.php`

If you can check not existing data, you can do like this
`User::firstOrCreate(['name' => 'Test'])`, update needed fields and save model

**Comment by wanghanwanghan** [comment]
@Smolevich thank~

**Comment by Smolevich** [comment]
@wanghanwanghan, If issue is not actual, please close him
