### ISSUE TITLE
MongoDB specific operators :: $size

### ISSUE THREAD

**Issue by Abhinanddas** [jenssegers/laravel-mongodb#1784]
I am trying to find the mongo documents having a field with specific array size. As per the jessenger guide the code to find documents with a specific size is given:

**User::where('tags', 'size', 3)->get();**

But I need to find conditions like:
**Greater than a value, Less than a value, Not Equal and Between.**

Can anyone help me with this?

**Comment by Smolevich** [comment]
@Abhinanddas, You should use aggregate function
```
User::raw(function ($collection) {
    return $collection->aggregate(
        [

            [
                '$project' => [
                    'size_of_tags' =>  ['$size' =>  '$tags']
                ]
            ],
            [
                '$match' => [
                    'size_of_tags' => [
                        '$gt' => 3
                    ]
                ]
            ]
        ]
    );
});
```

**Comment by Abhinanddas** [comment]
I am working with a dynamic where clause. So I need a way to find the value ranges in the eloquent model. Can't do it with the aggregate function.

**Comment by Smolevich** [comment]
You can use operator [$where](https://docs.mongodb.com/manual/reference/operator/query/where/)

**Comment by Smolevich** [comment]
Try use like [this](https://github.com/jenssegers/laravel-mongodb/blob/master/README.md#raw-expressions)

**Comment by Abhinanddas** [comment]
Since I am working on a dynamic where clause, I cant use raw expressions.

**Comment by Smolevich** [comment]
What do you mean in dynamic where clause?

**Comment by Abhinanddas** [comment]
Let me show my code. I am working on Laravel.

$query= Collection_Model();
$query=$query->where('field_name',value);
if(condition){
      $query=$query->where('field_name',value);
}else{
    $query=$query->where('field_name',value);
}

Since I am building a Query based on various conditions and clauses, I can't use aggregation.

**Comment by Smolevich** [comment]
```
$departmentId = 20;
$query = User::where('department_id', '=', 10);
if ($departmentId === 20) {
      $query->whereRaw(['$where' => 'this.scores.length > 1'])
} else {
     $query->whereRaw(['$where' => 'this.scores.length > 3'])
}
dd($query->get());
```

**Comment by Smolevich** [comment]
@Abhinanddas, do you solve your problem?

**Comment by Abhinanddas** [comment]
@Smolevich Thanks bro it worked......

**Comment by Smolevich** [comment]
@Abhinanddas, please close issue
