### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pierrejoye** [jenssegers/laravel-mongodb#1787]
Thanks for your great work on mongodb support in Eloquent! Keep going!

There is no license file nor license headers. What is the license used for this package? :)

**Comment by Smolevich** [comment]
@jenssegers can answer on this question

**Comment by Smolevich** [comment]
@pierrejoye, you can license in another [branch](https://github.com/jenssegers/laravel-mongodb/blob/develop/LICENSE)

**Comment by divine** [comment]
It has been merged https://github.com/jenssegers/laravel-mongodb/pull/1780 and this issue should be closed.

cc @Smolevich
