### ISSUE TITLE
About $unwind a little bug?

### ISSUE THREAD

**Issue by hunfwj** [jenssegers/laravel-mongodb#1789]
`Array ( 
	[0] => Array ( 
		[_id] => MongoDB\BSON\ObjectId Object ( [oid] => 5d39252d8c97450302470d52 ) 
		[reply_list] => Array ( 
			[0] => Array ( 
					[issue_number] => 0 
					[iss_type] => 2 
					[content] => 了解 
				) 
			[1] => Array ( 
					[issue_number] => 1 
					[iss_type] => 2 
					[content] => 耗时 
				) 
			[2] => Array ( 
					[issue_number] => 2 
					[iss_type] => 2 
					[content] => 当然啦 
				) 
			[3] => Array ( 
					[issue_number] => 3 
					[iss_type] => 0 
					[content] => 1 
				) 
			[4] => Array ( 
					[issue_number] => 4 
					[iss_type] => 1 
					[content] => Array ( [0] => 0 [1] => 1 [2] => 2 ) 
				) 
		) 
	) 
	[1] => Array ( 
		[_id] => MongoDB\BSON\ObjectId Object ( [oid] => 5d39252d8c97450302470d52 ) 
		[reply_list] => Array ( 
			[0] => Array ( 
					[issue_number] => 0 
					[iss_type] => 2 
					[content] => 不了解 
				) 
			[1] => Array ( 
					[issue_number] => 1 
					[iss_type] => 2 
					[content] => 不太耗时 
				) 
			[2] => Array ( 
					[issue_number] => 2 
					[iss_type] => 2 
					[content] => 嗯嗯 
				) 
			[3] => Array ( 
					[issue_number] => 3 
					[iss_type] => 0 
					[content] => 1 
				) 
			[4] => Array ( 
					[issue_number] => 4 
					[iss_type] => 1 
					[content] => Array ( [0] => 0 [1] => 1 [2] => 2 ) 
				) 
		) 
	)
）`

`$res = Reply::raw(function ($collection) {
            return $collection->aggregate([
                [
                    '$unwind' => [
                        'path' => '$reply_list',
                        'includeArrayIndex' => 'arrayIndex'
                    ]
                ],
                [
                    '$match' => [
                        'arrayIndex' => 0
                    ]
                ],
                [
                    '$project' => [
                        'reply_list.issue_number' => 1,
                        'reply_list.iss_type' => 1,
                        'reply_list.content' => 1
                    ]
                ]
            ]);
        })->toArray();`

**It have four . Why ??? it should be two ..**
`Array ( 
	[0] => Array ( 
		[_id] => 5d39252d8c97450302470d52 
		[reply_list] => MongoDB\Model\BSONDocument Object ( [storage:ArrayObject:private] => Array ( 
			[issue_number] => 0 
			[iss_type] => 2 
			[content] => 了解 
		) 
		) 
	) 
	[1] => Array ( 
		[_id] => 5d3944168c9745079e3eeb22 
		[reply_list] => MongoDB\Model\BSONDocument Object ( [storage:ArrayObject:private] => Array ( 
		[issue_number] => 0 
		[iss_type] => 2 
		[content] => 不太了解 
		) 
		) 
	) 
	[2] => Array ( 
		[_id] => 5d3958a78c974503040ecd92 
		[reply_list] => MongoDB\Model\BSONDocument Object ( [storage:ArrayObject:private] => Array ( 
		[issue_number] => 0 
		[iss_type] => 0 [content] => 0 
		) 
		) 
	) 
	[3] => Array ( 
		[_id] => 5d3958c68c974503037e9ae2 
		[reply_list] => MongoDB\Model\BSONDocument Object ( [storage:ArrayObject:private] => Array ( 
		[issue_number] => 0 
		[iss_type] => 0 
		[content] => 1 
		) 
		) 
	) 
	[4] => Array ( 
		[_id] => 5d3965928c97450bad625282 
		[reply_list] => MongoDB\Model\BSONDocument Object ( [storage:ArrayObject:private] => Array ( 
		[issue_number] => 0 
		[iss_type] => 1 
		[content] => MongoDB\Model\BSONArray Object ( 
			[storage:ArrayObject:private] => Array ( 
				[0] => 0 
				[1] => 1 
				[2] => 2 
			) 
		) 
		) 
		) 
	) 
)`

**Comment by hunfwj** [comment]
I tried to make the format more beautiful, but my indentation was gone. This is awkward

**Comment by Smolevich** [comment]
Please, describe fromatted json data for research

**Comment by Smolevich** [comment]
Is it same [issue](https://github.com/jenssegers/laravel-mongodb/issues/1788) ?
