### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by Smolevich** [jenssegers/laravel-mongodb#1791]
@jenssegers, please answer here   
There are many old not actual issues.
Maybe better create channel in Slack for questions with any help and allow issues with bugs?
What do you think about searching maintainers for this library and separating functionality on core and another parts?

PS I created slack [channel](https://join.slack.com/t/laravel-mongodb/shared_invite/enQtNzQyOTAzMzg0ODIwLWNjMzA0MjUwYzNiM2Q2NDdkYmE2NGJjZDM3NjgzODE2NTFlN2NlOWVjYjdiNjFjZTQ2ZjYwZDgzMGRiZGI4MGM) Welcome to join and discuss

**Comment by simonschaufi** [comment]
@Smolevich the invitation link is not valid any more.

**Comment by Smolevich** [comment]
Valid [link](https://join.slack.com/t/laravel-mongodb/shared_invite/enQtNzQyOTAzMzg0ODIwLWNjMzA0MjUwYzNiM2Q2NDdkYmE2NGJjZDM3NjgzODE2NTFlN2NlOWVjYjdiNjFjZTQ2ZjYwZDgzMGRiZGI4MGM)
