### ISSUE TITLE
Update item in array

### ISSUE THREAD

**Issue by williansebastiao** [jenssegers/laravel-mongodb#1793]
Hello everyone, how's it going?
I need to update an item in an array, how could I do?
The item would be active inside card

"gateway" : [ 
        {
            "iugu" : {
                "default_payment_method_id" : "9360991C853C4FCFA90F28E45DDCE3BE",
                "customer_id" : "030C8A08058A4CA7BD112D5A4F54C81C",
                "card" : [ 
                    {
                        "brand" : "VISA",
                        "name" : "Anna Silva",
                        "number" : "XXXX-XXXX-XXXX-1881",
                        "month" : 1,
                        "year" : 20,
                        "active" : true
                    }
                ],
                "subscription" : {
                    "id" : "C23E7E49880642A8A8BBC256C22C94AD",
                    "suspended" : false,
                    "value" : 2990,
                    "expires_at" : "2019-08-01",
                    "created_at" : "2019-07-25T16:12:27-03:00",
                    "updated_at" : "2019-07-25T16:12:27-03:00",
                    "customer_id" : "030C8A08058A4CA7BD112D5A4F54C81C",
                    "customer_name" : "Anna Silva",
                    "plan_name" : "Plano semanal",
                    "logs" : [ 
                        {
                            "id" : "803CD10FACA0427E8403850F84C1F9B8",
                            "description" : "Assinatura Criada",
                            "notes" : "Assinatura Criada ",
                            "created_at" : "2019-07-25T16:12:27-03:00"
                        }
                    ]
                },
                "created_at" : "2019-07-25T16:12:25-03:00",
                "updated_at" : "2019-07-25T16:12:25-03:00",
                "active" : true
            }
        }
    ],

**Comment by Smolevich** [comment]
You can use push and pull 
Or see example [here](https://github.com/jenssegers/laravel-mongodb/issues/1783)
