### ISSUE TITLE
Job exception missing from failed_jobs table when using Laravel Queues

### ISSUE THREAD

**Issue by maxakropolis** [jenssegers/laravel-mongodb#1800]
We've noticed whilst testing that the `exception` column is not populated when using MongoDb (but it when the configuration is changed to use MySQL)

Amending the logic in MongoFailedJobProvider to cast $exception (as is done in the default DatabaseFailedJobProvider) seems to fix the issue

```
    public function log($connection, $queue, $payload, $exception)
    {
        $failed_at = Carbon::now()->getTimestamp();

        $exception = (string) $exception;

        $this->getTable()->insert(compact('connection', 'queue', 'payload', 'failed_at', 'exception'));
    }
```
Is this a bug or have we misconfigured something?

**Comment by Smolevich** [comment]
@maxakropolis, describe steps for reproducing problem
