### ISSUE TITLE
How to count optimal data relations

### ISSUE THREAD

**Issue by trungdiep92** [jenssegers/laravel-mongodb#1801]
How to count optimal data relations:

Collection: photos, photos_like, photos_comment
Result: Photo i, count like, count comment

Case 1:

$photos = Photo::with(['like', 'comment' => function ($query) {
            $query->where('is_approved', '1');}])
            ->select('photo_featured', 'title', 'view_count')->where('status', "1")->orderBy('created_at', 'desc')
            ->get();
			
view:
$photo->like->count()
$photo->comment->count()

But it selects all data in like and comment collection and then counts
->consuming memory, slow processor

Case 2: Use withCount

->return: Illegal offset type

https://github.com/jenssegers/laravel-mongodb/issues/1339
https://github.com/jenssegers/laravel-mongodb/issues/1147
https://github.com/jenssegers/laravel-mongodb/issues/1416

I did not find a way to fix the error

Case 3: Use query builder and raw

$photos = DB::table('photos')
            ->select(['photos.photo_featured', 'photos.title', 'photos.view_count', DB::raw("COUNT(photos_like._id) as like_count"), 
			DB::raw("COUNT(photos_comment._id) as comment_count")])
			->....
			
->return: Illegal offset type

error when using DB::raw

https://github.com/jenssegers/laravel-mongodb/issues/1123
https://github.com/jenssegers/laravel-mongodb/issues/1693

How to get count from table relation???

**Comment by Smolevich** [comment]
@trungdiep92, let's go to slack, you can find link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by trungdiep92** [comment]
The function withCount relation of this library is faulty. I research and found two solutions:
1. Relation: Use aggregate mongodb

2. Embed: Use embed array and count size of array or use like_count filed(increment)

Hope this helps!

**Comment by GromNaN** [comment]
This feature is implemented by https://github.com/mongodb/laravel-mongodb/pull/3560
