### ISSUE TITLE
EmbedsMany relationship save fails

### ISSUE THREAD

**Issue by aowie1** [jenssegers/laravel-mongodb#1802]
laravel-mongodb Version: 3.3.1
mongo db version v4.0.10

Attempts to save an embedded relation is failing using code like:
`$parent->children()->save($child);`

Debugging the query log shows an updateMany query like:
```
db.getCollection('parents').updateMany(
    {
            "$and":[
                {"_id":"5d449203d9350a001337fded"},
                {"children._id":"5d449203d9350a001337fdee"}
            ]
    },
    {
        "$set":{
            "children.$.sub_children": [1,2,3]
        },
    },
    {"multiple":true}
);
```

The filter in this generated query above is incorrect. It needs to use actual ObjectIds in the where clause, like:
```
db.getCollection('parents').updateMany(
    {
            "$and":[
                {"_id":ObjectId("5d449203d9350a001337fded")},
                {"children._id":ObjectId("5d449203d9350a001337fdee")}
            ]
    },
    {
        "$set":{
            "children.$.sub_children": [1,2,3]
        },
    },
    {"multiple":true}
);
```

**Comment by Smolevich** [comment]
@aowie1, let's go to slack, see

**Comment by andresgcarmona** [comment]
Hi @aowie1, can you please tell me where to find the query log you mention?. I had the same "issue", when trying to save an embedded model inside a parent model, it turns out that if the child model is not "dirty" then the update (save operation) is not performed on the parent model, which in turn doesn't embed the child into the parent model.

I used the associate function to associate the child with the parent and then called save on the parent model.

**Comment by aowie1** [comment]
@andresgcarmona https://laravel.com/docs/5.0/database#query-logging
Thanks for that note.

The issue does not seem to appear in L5.8 with jenssegers/laravel-mongodb@3.5.2.
Since I cannot upgrade right now, I had to solve my case in the interim by overwriting the embedded document with a mutated clone of the original using the update() method. Then saving the parent.

**Comment by Smolevich** [comment]
@aowie1, do you solve your problem?

**Comment by aowie1** [comment]
@Smolevich Yes, I have a workaround but the bug still exists in 3.3.1. Maybe just label this as "Won't Fix" due to it being resolved in a more recent version?
