### ISSUE TITLE
getIdAttribute accessor creating issue of loading traits for a model

### ISSUE THREAD

**Issue by tariqali021** [jenssegers/laravel-mongodb#1803]
I have a model name 'Language'. This has an id, _id, abbr attributes.

This model has some traits say ATrait, BTrait. After loading everything model does not load traits ATrait, BTrait. I have an accessor named 

```
public function getIdAttribute($value)
{
	return $this->attributes['abbr'];
}
```

When I removed this accessor, everything works fine. But I want to know why it is happening. I have the same application with a MySQL database. In that application, this accessor is working fine so I thought it's Mongo issue somewhere. 
Could you please help me figure it out because I need this accessor in my Model.

**Comment by Smolevich** [comment]
@tariqali021, let's go to slack. See [link](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by tariqali021** [comment]
Worked for me by updating the accessor

```
public function getIdAttribute($value **= null** )
{
	return $this->attributes['abbr'];
}
```

**Comment by Smolevich** [comment]
@tariqali021, please close issue
