### ISSUE TITLE
Working with big queries and timeout

### ISSUE THREAD

**Issue by henriqu3** [jenssegers/laravel-mongodb#1805]
I have a query whici works with more or less 40k parameters inside a $in.
The question is, everytime I run this query I get timeout error.

Is possible use timeout with this lib? follow below the code..

`DB::collection('urls_palavras')
                ->timeout(-1)
                ->raw(function($collection) use ($request) {
                    return $collection->aggregate([
                        ['$match' => 
                            [
                                '$and' => [
                                    ['palavra_id' => ['$in' => $request->palavras]],
                                    ['url_id' => ['$in' => $request->urls]],
                                    ['posicao' => ['$lte' => 100]],
                                ]                            
                            ]
                        ],
                        ['$lookup' =>
                            [
                                'from'=> 'historicos',
                                'as'=> 'historicos' ,
                                'let'=> ["url_palavra_id"=> '$id'],
                                'pipeline'=> [
                                    [
                                        '$match'=> [
                                            '$expr'=> [
                                                '$and'=> [
                                                    ['$eq'=> ['$url_palavra_id', '$$url_palavra_id']],
                                                    ['$gte'=> ['$dt_pesquisa', $request->start]],
                                                    ['$lte'=> ['$dt_pesquisa', $request->end]]
                                                ]
                                            ]
                                        ]
                                    ],
                                ]
                            ]
                        ],
                         ['$project'=> [
                             '_id' => 0,
                             'historicos'=> ['$arrayElemAt'=> ['$historicos', 0]],
                             'palavra'=> '$palavra_id'
                         ]],
                         ['$group'=> [
                            '_id'=> ['$add' => [['$floor' => ['$divide' => ['$historicos.posicao', 10]]],1]],
                            'palavras'=> ['$addToSet'=> '$palavra']
                         ]],
                         ['$match' => [
                            '_id' => ['$gte' => 0]
                         ]],
                         ['$project' => ['_id' => 0, 'posicao' => '$_id', 'quantidade' => ['$size' => ['$palavras']]]],
                         ['$sort' => ['posicao' => 1]]
                    ],['allowDiskUse'=>true]);
                })->toArray();`

**Comment by Smolevich** [comment]
@henriqu3, let's go to slack, you can find link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by Skeazy11** [comment]
Hello, did you find any solution?
