### ISSUE TITLE
An embedded model cannot be unserialized

### ISSUE THREAD

**Issue by JValck** [jenssegers/laravel-mongodb#1808]
Let's say that a `User` has an `Address` which is embedded in the `User` model.
When adding the `Address` as a public property in a job or event (p.e. for a broadcast), not all the fields will be up to date or include when unserializing.

Steps to reproduce:
```
unserialize(serialize($address))
```
when comparing `$x` to `$address` you'll notice that they are different if `$address` was recently updated.

Workaround:
first call `toJson` or `toArray` on `$address` before adding them as a property to the job or event.

**Comment by Smolevich** [comment]
@JValck,  let's go to slack, you can find link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)
