### ISSUE TITLE
zero-length keys are not allowed, did you use $ with double quotes?

### ISSUE THREAD

**Issue by ananduee** [jenssegers/laravel-mongodb#181]
``` php
MongoException
zero-length keys are not allowed, did you use $ with double quotes?

public function get($columns = array('*')) {
    if ( ! is_null($this->cacheMinutes)) return $this->getCached($columns);

    return $this->getFresh($columns);
}
```

i am getting this error when using Auth::check().
i am using database as session driver.

**Comment by stampycode** [comment]
I got this error by accidentally passing an array into the search criteria for a field expecting a single value:

        $user = $repo->findBy(['username' => $username]);
        if($user) {
            $owner = $repo->findBy(['owner' => $user]);
        }

The first `findBy` should have been a `findOneBy` - even if only one `$user` is found, it breaks the query.
