### ISSUE TITLE
How to get Record for specified date? 

### ISSUE THREAD

**Issue by nishh06** [jenssegers/laravel-mongodb#1811]
{
"_id": "02ce6ec6-50b1-4c3d-b961-32a3f452c9da",
"rid": "WW3EvLk9TdwXwfK6AYTyEx5t4PfDWx9xfP",
"msg": "Hello",
"ts": {
"$date": {
"$numberLong": "1558085847819"
}
},
"u": {
"_id": "YTyEx5t4PfDWx9xfP",
"username": "9738084090",
"name": "Suhas"
},
"_updatedAt": {
"$date": {
"$numberLong": "1558085847832"
}
},
"mentions": [],
"channels": []
}

Here now i need to fetch the records according to the date. Ex. Records created today. How can i do that? @jenssegers

**Comment by Smolevich** [comment]
@hishh06, what date field do you use for find query?

**Comment by Smolevich** [comment]
You can find example [here](https://github.com/jenssegers/laravel-mongodb/blob/master/tests/ModelTest.php#L384)
