### ISSUE TITLE
embedsMany not casting fields properly?

### ISSUE THREAD

**Issue by bytewoopy** [jenssegers/laravel-mongodb#1818]
I updated to the latest version before sending this in, 

    "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^6.3",
        "jenssegers/mongodb": "^3.5",
        "laravel/framework": "5.8.*",
        "laravel/telescope": "^2.0",
        "laravel/tinker": "^1.0",
        "optimus/api-consumer": "0.2.*",
        "votong/laravel-mongodb-passport": "^1.1"

I tried using an embedsMany relationship and saved some items into the db. When i retrieve them they are not casting object Ids and dates properly? Is there  step I am missing or is this the result of a collection being returned?

**parameters** -> is the embedsMany relationship.
![image](https://user-images.githubusercontent.com/48188775/64034615-ddeabe00-cb03-11e9-97fc-3c6c76bf88e0.png)

**Comment by Smolevich** [comment]
@bytewoopy, $oid is standard mongodb representation for ObjectId. See [docs](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#ObjectId)

**Comment by dungnv93** [comment]
> I've got this working now, I was probably not loading the relation when listing the results.

i having the same issue. can you show 2 model file for me? thanks you
