### ISSUE TITLE
has and whereHas relationship queries crash

### ISSUE THREAD

**Issue by Mulkave** [jenssegers/laravel-mongodb#182]
Using the relationship querying facilities like `has('relationship')` and `whereHas('relationship', Closure)` breaks with the error

```
exception
'Symfony\Component\Debug\Exception\FatalErrorException'
with message 'Call to a member function wrap() on a non-object' in
/.../laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php:279

```

**Comment by tusharvikky** [comment]
@Mulkave Where you able to query ```has``` and ```whereHas```?

**Comment by bart** [comment]
What would be a possibility to query for related information instead, like for a comment title which is related to a post?

**Comment by sfaisal-modus** [comment]
https://stackoverflow.com/questions/42430157/laravel-jenssegers-mongodb-wherehas-and-has-returns-empty-collection

https://stackoverflow.com/questions/46023352/laravel-mongo-many-to-many-relation-wherehas-not-working
