### ISSUE TITLE
id or _id not populated after calling save function

### ISSUE THREAD

**Issue by tathong** [jenssegers/laravel-mongodb#1820]

**Comment by tathong** [comment]
Hi,
I am not getting the id or _id value after saving to Mongodb.
I am on version 3.4.

```
$obj = new MyModel;
$obj->name = 'something';
$obj->save();

$obj->_id // null
$obj->id  // null
```
My model class look something like this

```
use Jenssegers\Mongodb\Eloquent\Model;

class MyModel extends Model 
{
      protected $connection = 'mongodb';
}

```

**Comment by Smolevich** [comment]
Check return for function save. It equal to 0 or 1

**Comment by tathong** [comment]
Sorry, I missed that information out.
After running `save` it return `true`.

**Comment by Smolevich** [comment]
@tathong, What about mongo storage, new document didn't finded?

**Comment by tathong** [comment]
Hi, yes. The document was created properly with an ObjectId.

**Comment by Smolevich** [comment]
@tathong, show code for eloquent model.

**Comment by tathong** [comment]
Hi @Smolevich , the class is the same as the one I mentioned in the comment. Just wondering, in the event of mongo replication lag, will it by any chance cause this issue?

**Comment by Smolevich** [comment]
@tathong, are you build docker container with mongodb and test on it?

**Comment by tathong** [comment]
I am running the code in a vagrant box. The mongo and source is in the same box.

**Comment by tathong** [comment]
Ok @Smolevich I think I found the issue. 
There is a `public $incrementing = false;` inside my model class.
Remove it and it works.

Thank you for the time. I will close this issue.

**Comment by uneekswatian** [comment]
I am facing the same issue, with laravel version 9, after $model->save() when I try to retrieve $model->_id its coming "null", any help will be appreciated.

Here is my model

`<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Jenssegers\Mongodb\Eloquent\Model;

class Campaign extends Model
{
    use HasFactory;

    protected $collection = "campaigns";

    protected $guarded = [];
`
