### ISSUE TITLE
Fails to install on Laravel 6.0

### ISSUE THREAD

**Issue by ReeceM** [jenssegers/laravel-mongodb#1821]
Hi @jenssegers, 
# Question

Is this going to be updated or are there problems if this package were to be updated to require the latest versions? i.e. breaking changes?

I have just tried to run a `composer update` against my application in order to upgrade to Laravel 6.0. 

But I get hit with the following error, which seems to be caused by the requirements of the `composer.json` for the Illuminate packages

https://github.com/jenssegers/laravel-mongodb/blob/01ac069cf88a2d1b2749cf3a2df45496b753d11b/composer.json#L13-L19

Errror from `composer update || composer require jenssegers/mongodb`

```
- Conclusion: don't install jenssegers/mongodb v3.5.3
    - Conclusion: don't install jenssegers/mongodb v3.5.2
    - Conclusion: remove jenssegers/mongodb v3.5.1
    - Conclusion: don't install jenssegers/mongodb v3.5.1
    - Conclusion: don't install jenssegers/mongodb v3.5.0
    - Conclusion: don't install laravel/framework v6.0.0
    - Installation request for jenssegers/mongodb ^3.5 -> satisfiable by jenssegers/mongodb[v3.5.0, v3.5.1, v3.5.2, v3.5.3].
    - Conclusion: don't install laravel/framework 6.x-dev
    - jenssegers/mongodb v3.5.1 requires illuminate/support ^5.8 -> satisfiable by laravel/framework[v5.8.34, 5.8.x-dev], illuminate/support[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
```

I gather this is because the package is not pulling the related `illuminate/* ^6.0` for its requirements.

**Comment by Smolevich** [comment]
[Latest](https://github.com/laravel/framework/releases/tag/v6.0.0) version was released 11 hours ago, you can prepare PR for new release. Join to our  [slack](https://join.slack.com/t/laravel-mongodb/shared_invite/enQtNzQyOTAzMzg0ODIwLWNjMzA0MjUwYzNiM2Q2NDdkYmE2NGJjZDM3NjgzODE2NTFlN2NlOWVjYjdiNjFjZTQ2ZjYwZDgzMGRiZGI4MGM) community

**Comment by Smolevich** [comment]
@jenssegers, please close issue
