### ISSUE TITLE
How to group by a nested array

### ISSUE THREAD

**Issue by thewasta** [jenssegers/laravel-mongodb#1822]
```
 0 => array:50 [▼
    "_id" => "5d68fdcd88db090006626886"
     ...
    "shippingData" => array:5 [▼
      "id" => "shippingData"
      "address" => array:13 [▶]
      "logisticsInfo" => array:2 [▼
        0 => array:17 [▼
          "slas" => array:1 [▶]
          "shipsTo" => array:28 [▶]
          "deliveryIds" => array:1 [▼
            0 => array:5 [▼
              "courierId" => "1cc98e6"
            ]
          ]
          "deliveryChannel" => "delivery"
          "pickupStoreInfo" => array:5 [▶]
        ]
        1 => array:17 [▶]
```
I have to go to shippingData->logisticInfo[0]->corrierId, and based in this id group all information,
the problem is logisticInfo[0], and it will only check the first value and I want to check all of them, I don't know if it will be 1 or 3, etc. I want to group all by the value from 'courierId'

I had trie
```
dd($this->raw()->find(['shippingData.logisticsInfo' => [
            'deliveryIds' => [
                'courierId' => "1"
            ]
        ]
        ])->toArray());
```
```
dd($this->where('shippingData.logisticsInfo.0.deliveryIds.0.courierId', "1")->get()->toArray());
```

But nothing returns what I expect.

I'm working with laravel 5.5 and jenssegers/mongodb:3.3.*

**Comment by Smolevich** [comment]
Join to our  [slack](https://join.slack.com/t/laravel-mongodb/shared_invite/enQtNzQyOTAzMzg0ODIwLWNjMzA0MjUwYzNiM2Q2NDdkYmE2NGJjZDM3NjgzODE2NTFlN2NlOWVjYjdiNjFjZTQ2ZjYwZDgzMGRiZGI4MGM) community

**Comment by Smolevich** [comment]
For begin you can dump real query to mongodb, you can switch on ```DB::enableQueryLog()``` and after query run ```DB::getQueryLog()```

**Comment by thewasta** [comment]
> For begin you can dump real query to mongodb, you can switch on `DB::enableQueryLog()` and after query run `DB::getQueryLog()`

I did this:
```
DB::enableQueryLog();
$myQuery = DB::connection('mongodb')->table('mycollection')->get();
$querylog = DB::getQueryLog();
dd($querylog);
```

But it's empty
