### ISSUE TITLE
Update support Laravel 6.0

### ISSUE THREAD

**Issue by dlu92** [jenssegers/laravel-mongodb#1825]
It is currently not possible to upgrade from Laravel 5.8 to version 6.0 if this dependency is installed.

When the release is planned a new version that has support for Laravel 6.0?

**Comment by VeeeneX** [comment]
https://github.com/laravel/framework/releases/tag/v6.0.0

**Comment by Smolevich** [comment]
@dlu92, https://github.com/jenssegers/laravel-mongodb/pull/1824 PR in work

**Comment by Smolevich** [comment]
@dlu92, support in `3.6.0`

**Comment by VeeeneX** [comment]
@jenssegers You can close this now :)
