### ISSUE TITLE
Class 'MongoDB\BSON\ObjectId' not found

### ISSUE THREAD

**Issue by kajem** [jenssegers/laravel-mongodb#1826]
I am using Ubuntu 18.04.2 LTS and my server is nginx. I am getting below error. 

`FatalThrowableError in ReportFileController.php line 906: Class 'MongoDB\BSON\ObjectId' not found`

906 line is: 
`'$id' => new ObjectId(request('patient_id'))`

FYI,I have installed php-mongodb and added extenstion=mongodb.so in the /cli/php.ini file and restarted nginx.

Can anyone please help me?

**Comment by Smolevich** [comment]
@kajem, Check that extension was installed for php-fpm

**Comment by Smolevich** [comment]
You can see on this [issue](https://github.com/jenssegers/laravel-mongodb/issues/1786)

**Comment by kajem** [comment]
@Smolevich, I have checked and founds php-fpm is installed and active.
![image](https://user-images.githubusercontent.com/3541403/64606926-3ca81580-d3e9-11e9-9059-b751c569826d.png)

**Comment by Smolevich** [comment]
@kajem, check that installed `mongodb`

**Comment by Smolevich** [comment]
@kajem, let's go to slack community. Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by stephandesouza** [comment]
You need to insert the `extenstion=mongodb.so` on php.ini of `php-fpm`, you only putted on `cli`.
