### ISSUE TITLE
config/database.php 'options - database' 

### ISSUE THREAD

**Issue by jampzo** [jenssegers/laravel-mongodb#1832]
work only if I change the word 'database' for 'db'
laravel 6 php 7.2

**Comment by Smolevich** [comment]
@jampzo, let's go to slack. You can find link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by Smolevich** [comment]
@jampzo, do you solve this problem?

**Comment by jampzo** [comment]
yes @Smolevich thanks!

I changed the word database by db 
options' => [
                'db' => 'admin'
]
and it's working.
