### ISSUE TITLE
"Maximum execution time of 30 seconds exceeded" in Count with 4M documents

### ISSUE THREAD

**Issue by fparareda** [jenssegers/laravel-mongodb#1833]
Good morning,
I have faced an error: "Maximum execution time of 30 seconds exceeded" after a Count in my MongoDB. My Laravel is a v5.7.22 and I am using your library to use MongoDB as my primary DB (which is awesome, btw).

`
$amount_companies = CompanyCompaniesBucket::count();
`

The class I have defined is:

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

`
class CompanyCompaniesBucket extends Eloquent {
    protected $connection = 'mongodb2';
    protected $collection = 'companies';
}
`

I don't know why, but the count reaches 30 seconds when using another tool to explore the MongoDB is only 0.03 seconds (Compass or Robo3T). Do you know what can produce this timeout issue? 

Thanks in advance

**Comment by josemiguelq** [comment]
https://github.com/jenssegers/laravel-mongodb/pull/1695

**Comment by Smolevich** [comment]
@fparareda check please and close issue if it's not actual

**Comment by fparareda** [comment]
I am going to try it first. Thanks!
