### ISSUE TITLE
MongoDB + Laravel eloquent

### ISSUE THREAD

**Issue by GiuliaLage** [jenssegers/laravel-mongodb#1834]
I'm using Jenssegers to make it work. 

On mongo I have the **Collection Company** and inside the company I have the **object Config** and inside the object config I have another object called  **sms_config** 

How can I make a select on the sms_config using eloquent ? I dont know how going to be my model and my controller in this case.

This is  the company collection : 

![Captura de tela de 2019-09-21 12-55-36](https://user-images.githubusercontent.com/45069025/65375757-52320080-dc6f-11e9-9661-2ae45c12b3af.png)

**Comment by Jannnnnn** [comment]
Did you try a embedded relation? This should work for you 
https://github.com/jenssegers/laravel-mongodb/blob/master/README.md#embedsone-relations
