### ISSUE TITLE
BelongsToMany in array of objects

### ISSUE THREAD

**Issue by mts88** [jenssegers/laravel-mongodb#1839]
Hello there, I have a problem with relationships, in particular Many-To-Many. I have two models: `Tag` and `Container`, with this structure:
**Tag**
```
{
 _id: ObjectId("..."),
uuid: string
}
```

**Container**
```
{
_id: ObjectId("..."),
uuid: string,
name: string,
tags: [
   {
     uuid: (uuid of tag),
    name: (name of tag)
},
.....
]
}
```

I have these relationships in models:
**TagModel**

 ```
public function containers()
    {
        return $this->hasMany("\App\Container", "tags.uuid", "uuid");
    }
```

**ContainerModel**
```
    public function tagsList()
    {
        return $this->belongsToMany('\App\Tag', null, "uuid", "tags.uuid");
    }
```

The relationship of TagModel works and I retrieve all container of a tag, but from containers to tags not works.
I don't understand the belongsToMany relationship and, in particular, can I use this relationship with this structure?

Thanks.

**Comment by billschmidt** [comment]
The hasMany inverse is belongsTo. See the Laravel documentation on relationships.

Use belongsToMany for many to many relationships

**ContainerModel**
`public function tags() 
{
    return $this->belongsToMany(TagModel::class);
}`

**TagModel**
`public function containers() 
{
    return $this->belongsToMany(ContainerModel::class);
}`

You can then do stuff like:
`$container->tags()->attach($tag);`

I don't know what your intention is with uuid, but it's probably just complicating things here.
