### ISSUE TITLE
After update  3.5.1 errro 

### ISSUE THREAD

**Issue by rasyid46** [jenssegers/laravel-mongodb#1842]
This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.

how i can clone by version 3.5 older ?

thank you

**Comment by Smolevich** [comment]
@rasyid46 , Please more info for reproducing problem

**Comment by rasyid46** [comment]
sorry I already fixed it

for the ext-mongodb version (1.6.0)
during dbhost config there must be an additional DBHOST
?retryWrites = false

**Comment by Ardakilic** [comment]
If anyone's wondering, here's what I did to fix this in Laravel 4. Should work for newer versions, too.

```diff
diff --git a/app/config/database.php b/app/config/database.php
index e282e6c..b0d0b5e 100755
--- a/app/config/database.php
+++ b/app/config/database.php
@@ -71,6 +71,9 @@ return array(
             'username' => 'nope',
             'password' => 'hellnope',
             'database' => 'ofcoursenope',
+            'options' => [
+                'retryWrites' => false,
+            ],
         )
     ),
```
