### ISSUE TITLE
Unsupported driver [mongodb] in mongodb 4.2

### ISSUE THREAD

**Issue by khanhvu14** [jenssegers/laravel-mongodb#1844]
- Laravel 6.0
- PHP 7.3
- Mongodb 4.2
I have a issue driver with mongodb. 
<img width="1071" alt="Screen Shot 2019-10-09 at 14 11 38" src="https://user-images.githubusercontent.com/4197632/66459181-baba1380-ea9e-11e9-8e18-18e569a9ae78.png">

**Comment by Smolevich** [comment]
What do you do? Install package?

**Comment by khanhvu14** [comment]
Oh sorry, My mistake, I'm closing issue now.
