### ISSUE TITLE
alias name of the column with jenssegersMongoDb

### ISSUE THREAD

**Issue by mvtaheri** [jenssegers/laravel-mongodb#1846]
How to alias name of the column with jenssegersMongodb?
I use this query 
 $categories=Category::project(
                    [
                        'id'=>1,
                        "title"=>'$name',
                        "parent"=>'$parent.id'
                    ]
                )->get();
but not work for me.

**Comment by Smolevich** [comment]
@mvtaheri, Use aggreagation framework for this case
