### ISSUE TITLE
MongoDB model HasMany SQL Models

### ISSUE THREAD

**Issue by CROSP** [jenssegers/laravel-mongodb#1849]
Hi, I am trying to model my relations between `MongoDB` and `MySQL` but cannot get it working. 

Here is my `Order` (mongodb) model:

```
class Order extends BaseNosqlModel {
    use HybridRelations;
    protected $collection = 'orders';

    public function products() {
        return $this->hasMany( Product::class, 'id', 'productIds' );
    }
}
```

And my `Product` (mysql) model:

```
class Product extends BaseModel {
    use HybridRelations;
    protected $table = 'products';
}
```

My `Order` item looks like that in the database:
```

{
    "_id" : ObjectId("5da3625190cba903bb7cba22"),
    // other info
    "productIds" : [ 
        3, 
        7
    ],
    "updated_at" : ISODate("2019-10-13T17:49:03.000Z"),
    "created_at" : ISODate("2019-10-13T17:43:45.000Z")
}
```

I want to get all products related to a specific order. 

However when I try to query with the `with` method  (`with('products')`) I get the following error:

```
/laravel/framework/src/Illuminate/Database/Eloquent/Relations/HasOneOrMany.php"
line: 134
message: "Illegal offset type in isset or empty"
```

How to model such relationships correctly?

I would be grateful for any help!

**Comment by Smolevich** [comment]
You relate models by array field `productIds`, i think that you can try relate models such as
1. Create Order model
2. Create Product model with field `order_id` filled from step 1
3. Use `with` function for getting orders with products

**Comment by CROSP** [comment]
@Smolevich  Thanks for the answer. However the code snippet above are just examples, I have another domain. I just wanted to express the desired behavior. 
I've temporarily solved the problem by manually merging data after MongoDB models are retrieved.  
I user `whereIn` query to find all products and then merge with previously retrieved nosql models.

I would be grateful if someone a better solution to this issue. Also I can change my models, however relations between them should stay the same.
