### ISSUE TITLE
case-insensitive search in laravel, mongo with jenssegers/mongodb 3.0

### ISSUE THREAD

**Issue by yashpalchhajer** [jenssegers/laravel-mongodb#1857]
Hey,

I need to select data that matches value in case-insensitive.
if a collection looks like the below :-

`{
    "_id" : "00LJVY3EBQWERTYPK59F",
    "username" : "demo1"
}`

then i can search this user by `demo1`, `Demo1`, DEMO1` without like because, There can be a another user like below

`{
    "_id" : "00LJVY3EBQWERTYPK59F",
    "username" : "demo12"
}`

and in this case it can return 2 records.

any hint or help will be appreciated.

Many Thanks.

**Comment by Smolevich** [comment]
@yashpalchhajer, use [regex](https://docs.mongodb.com/manual/reference/operator/query/regex/) for this cases

**Comment by yashpalchhajer** [comment]
Hi @Smolevich 

with regex if any we search `demo` instead of `demo1` it will return two record. but, there is no record with username demo.

It should return empty set in these type of cases;

**Comment by Smolevich** [comment]
@yashpalchhajer, 

Test documents:
```
{"_id":"5dad5934153d15343c36ce93","user":"demo"}
{"_id":"5dad593e153d15343c36ce94","user":"demo12"}
{"_id":"5dad5946153d15343c36ce95","user":"demo1"}
```
Query: 
```
db.collection.find({user: /demo$/i})
```
return only one document

**Comment by yashpalchhajer** [comment]
Hey @Smolevich ,

thanks..! it's working fine.
