### ISSUE TITLE
Transaction does not rollback

### ISSUE THREAD

**Issue by niiice91** [jenssegers/laravel-mongodb#1860]
I need to use transactions on mongodb in laravel-5.8. I use like below snippet in my code but it does not rollback when one of queries failed.

```
$session = MongoDB::startSession();
$session->startTransaction();
try {
    Player::document()->update($updates, ['session' => $session]);
    $session->commitTransaction();
    return true;
} catch (\Exception $e) {
    $session->abortTransaction();
    return false;
}
```
Does this package support transactions? I desperately need to transactions in my code. Is [https://github.com/moloquent/moloquent](url) similar this package?

**Comment by Smolevich** [comment]
This package doesn't support transactions, but you can get native mongodb client and use him for transaction cases

**Comment by niiice91** [comment]
@Smolevich Thanks. How can I do this? Would you please give snippet me for guidance.

**Comment by Smolevich** [comment]
https://github.com/jenssegers/laravel-mongodb/issues/1334#issuecomment-500191105

**Comment by Smolevich** [comment]
@niiice91, please close issue if you don't have a questions
