### ISSUE TITLE
DSNs Including DB Name

### ISSUE THREAD

**Issue by derekrprice** [jenssegers/laravel-mongodb#1861]
My Mongo DSN looks like `mongodb://mongo:27017/dbname`.  Using this configuration yields an error about "$databaseName is not defined":

```
'mongo' => [
    'driver' => 'mongodb',
    'dsn' => 'mongodb://mongo:27017/dbname',
]
```

Adding a database name to the configuration works around the issue, but it is redundant with the information in the URL:
```
'mongo' => [
    'driver' => 'mongodb',
    'dsn' => 'mongodb://mongo:27017/dbname',
    'database' => 'dbname',
]
```

All our other environments in both PHP & JS work just fine with only the DSN and no DB name specified, including ones using the same base PHP Mongo driver.  `database` should not be required with a full `dsn`.

**Comment by Smolevich** [comment]
it will be changed [here](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Connection.php#L41)

**Comment by derekrprice** [comment]
@divine what do the "awaiting-author" and "question" tags mean?  You are waiting for someone to submit a PR?

**Comment by divine** [comment]
Hello,

Could you please confirm that this PR https://github.com/jenssegers/laravel-mongodb/pull/1954 fixed your issue?

New release on the way.

Awaiting author means I'm waiting any more information from the author, it has been almost 5 month since last reply so not sure if it's still actual.

Thanks.

**Comment by derekrprice** [comment]
I added some comments to PR #1954.  If I leave 'database' name out of my config, I still get this error:
```
Undefined index: database {"userId":7,"exception":"[object] (ErrorException(code: 0): Undefined index: database at /var/www/device-service/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:41)
```
This is the config that I would like to use:
```
'mongo' => [
    'driver' => 'mongodb',
    'dsn' => 'mongodb://mongo:27017/dbname',
]
```

**Comment by divine** [comment]
@derekrprice could you please just create a new PR with your proposed fixes?

I've just recreated from commit that was waiting for 2 years so you should understand and accept our apologies for my mistakes that I've made.

**Comment by derekrprice** [comment]
Yeah.  I should be able to put something together within a few days.

**Comment by divine** [comment]
@derekrprice could you please check PR #1971 ?

Thanks.

**Comment by derekrprice** [comment]
That worked, thanks!

**Comment by derekrprice** [comment]
Actually, not quite.  It works for URLs like "mongodb://..." but not for "mongodb+srv://", so it worked in my development envirionment but failed as soon as it got to our integration environement.
