### ISSUE TITLE
How can I fix retryWrites=false during connect with mLab

### ISSUE THREAD

**Issue by pms007** [jenssegers/laravel-mongodb#1862]
MongoDB\Driver\Exception\BulkWriteException  : This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.

**Comment by Smolevich** [comment]
@pms007, you can set this setting in config for connection such as like
```
...
          'driver_options' => [
                'retryWrites' => 'true',
                'w' => 'majority'
            ]
```

**Comment by pms007** [comment]
Thanks @Smolevich , I added driver_options as your given in config connection,but it still error.
Now, I added retryWrites=false in options[ ] like that
.....
 'options'  => [
                'database' => env(''),
                'retryWrites' => false,
                //'w' => 'majority'
 ]

it working now, Thanks
