### ISSUE TITLE
How to pass parameters to inner function in advance wheres?

### ISSUE THREAD

**Issue by probeyang** [jenssegers/laravel-mongodb#1863]
for example, this is code:
`$users = User::where('name', '=', 'John')->orWhere(function($query)
    {
        $query->where('votes', '>', 100)
              ->where('title', '<>', 'Admin');
    })
    ->get();`
i want to pass paramters to methods, but it can't support it:
`$users = User::where('name', '=', 'John')->orWhere(function($query, $args)
    {
        $query->where('votes', '>', $args['votes'])
              ->where('title', '<>', $args['title']);
    })
    ->get();`
how can i do? and, how to get the sql?

thanks.

**Comment by Smolevich** [comment]
You can see on [query logging](https://github.com/jenssegers/laravel-mongodb/blob/master/README.md#query-logging)

**Comment by Mike-Ab** [comment]
Have you tried 
```$users = User::where('name', '=', 'John')->orWhere(function($query) use($args) { $query->where('votes', '>', $args['votes']) ->where('title', '<>', $args['title']); }) ->get();```
