### ISSUE TITLE
How can I create a case-sensitive index

### ISSUE THREAD

**Issue by TheGeekyM** [jenssegers/laravel-mongodb#1864]
I want to do something like that:

db.test.createIndex( { name: 1}, { collation: { locale: 'en', strength: 2 } })

**Comment by Smolevich** [comment]
@TheGeekyM, see [function](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Schema/Blueprint.php#L40)
