### ISSUE TITLE
Import issue with Facade

### ISSUE THREAD

**Issue by podcasthosting** [jenssegers/laravel-mongodb#1868]
First off thank you for this great library!

In vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/MongodbQueueServiceProvider.php you changed line 16

`if (config('queue.failed.database') == 'mongodb') {`

in version 3.6.0 to 

`if (DB::connection(config('queue.failed.database'))->getDriverName() == 'mongodb') {`

in version 3.6.1 (line 17).

You import the DB facade with the statement

`use DB;`

causing a conflict in my application with a legacy class named DB that does not use a namespace. 

It causes a

`Cannot declare class, because the name is already in use`

Could you please change the import to the complete path:

`use Illuminate\Support\Facades\DB;`

which solves the issue.

I´d appreciate that very much. Thank you!

**Comment by Smolevich** [comment]
@podcasthosting please add description

**Comment by podcasthosting** [comment]
> @podcasthosting please add description

Please see updated issue. Sorry, I hit the send button accidentally.

**Comment by Smolevich** [comment]
Is this facade occur error?

**Comment by Smolevich** [comment]
I install version `3.6.1` and don't catch errors with work eloquent models
Show test code for reproducing problem

**Comment by podcasthosting** [comment]
As I wrote it conflicts with a legacy class called DB that it not using a namespace.

Just add a class

`class DB {}`

to your code and you´ll see.

**Comment by Smolevich** [comment]
```
namespace App;

class DB {
    public const NAME='CUSTOM CLASS';
}
```

and successfully use this class and `Illuminate\Support\Facades\DB` together

**Comment by podcasthosting** [comment]
I cannot modify the class because it comes from a library ([Pear DB](https://pear.php.net/package/DB)). 

Why can´t you just modify the import statement to the full path as outlined above?

**Comment by divine** [comment]
Hi @podcasthosting,

Sorry about late fix, I've pushed a PR https://github.com/jenssegers/laravel-mongodb/pull/1968 it will be merged and new version released as well.

Thank you!
