### ISSUE TITLE
Does not work with 7.1 as doctrine/lexer has minimum requirement for 7.2

### ISSUE THREAD

**Issue by varuog** [jenssegers/laravel-mongodb#1869]
Does not work with 7.1 as doctrine/lexer has minimum requirement for 7.2

**Comment by Smolevich** [comment]
@varuog, Show steps for reproducing

**Comment by Smolevich** [comment]
@varuog any updates?

**Comment by Smolevich** [comment]
Looks like not linked with this library
@varuog, if you have problem, please reopen this issue
