### ISSUE TITLE
Transaction numbers are only allowed on a replica set member or mongos

### ISSUE THREAD

**Issue by jeremiarm** [jenssegers/laravel-mongodb#1874]
Hello
so i create a simple CRUD with env and database config just like the guide. I can do READ, Update, and Delete but getting this error(of the title) when do INSERT with ->save(). 

this is the config/database.php

'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('DB_HOST', '192.168.16.53'),
            'port'     => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options'  => [
                'database' => 'admin',
            ]
        ],

and the .env

DB_CONNECTION=mongodb
DB_HOST=192.168.16.53
DB_PORT=27017
DB_DATABASE=shoes
DB_USERNAME=mongo-admin
DB_PASSWORD=password

i am using vagrant server for mongodb, and following https://www.linode.com/docs/databases/mongodb/build-database-clusters-with-mongodb/ tutorial for database clustering. only create not working, update read delete works

**Comment by masitings** [comment]
i got the same issue when trying to queue a lot of files. Does anyone have a clue about this ? 
<img width="786" alt="image" src="https://github.com/mongodb/laravel-mongodb/assets/29356430/e07fee8a-ccd9-4cff-a36f-76408339402f">

**Comment by alcaeus** [comment]
This error occurs if you are using transactions or retryable writes on a standalone server. From the trace excerpt you screenshotted, I can see a `find` operation being involved, so my guess would be on transactions.

However, there is not enough information to help you with this problem. If you'd like for us to help you investigate this, please create a new issue including information about the versions of this library and the MongoDB driver being used, version and topology of the MongoDB deployment you are connecting to, and the full trace of the error. Without this information, there's nothing we can do.

**Comment by masitings** [comment]
> This error occurs if you are using transactions or retryable writes on a standalone server. From the trace excerpt you screenshotted, I can see a `find` operation being involved, so my guess would be on transactions.
> 
> However, there is not enough information to help you with this problem. If you'd like for us to help you investigate this, please create a new issue including information about the versions of this library and the MongoDB driver being used, version and topology of the MongoDB deployment you are connecting to, and the full trace of the error. Without this information, there's nothing we can do.

But it really strange tho, im not evolving any `find` operation in this but in this case im using Laravel Excel to do the jobs, so i think it must be somewhere in there. Well thanks a lot for the reply. I think im good enough knowing this so no need to create a new issue for now.
