### ISSUE TITLE
issue with no mongodb records returned 

### ISSUE THREAD

**Issue by lunawesley9** [jenssegers/laravel-mongodb#1877]
recently I meet an issue of unable to find records from mongo db while the records are there and searchable in command line. I started the mongo query log and find this

--> this is the query from the program
```
find { find: "external_log", filter: { $and: [ { execution_id: "731" }, { url: /.*10\.100\.9\.14.*/i } ] }, limit: 1 } planSummary: COLLSCAN keysExamined:0 docsExamined:12335 cursorExhausted:1 numYields:96 nreturned:0 reslen:115 locks:{ Global: { acquireCount: { r: 194 } }, Database: { acquireCount: { r: 97 } }, Collection: { acquireCount: { r: 97 } } }
```

--> this is the query from command line
```
find { find: "external_log", filter: { execution_id: "731", url: /.*10\.100\.9\.14.*/i }, limit: 1.0, singleBatch: true } planSummary: COLLSCAN keysExamined:0 docsExamined:12336 cursorExhausted:1 numYields:96 nreturned:1 reslen:510 locks:{ Global: { acquireCount: { r: 194 } }, Database: { acquireCount: { r: 97 } }, Collection: { acquireCount: { r: 97 } } } protocol:op_command 15ms
```

as you can see nreturned is 0 for query from laravel program and 1 for the command line one. 
i suspect that the issue comes with `singleBatch: true`  but i am not sure. 

the code is 
 $log = $this->log->where('execution_id', $id)->where('url','LIKE','%'.$ip.'%')->first();

**Comment by Smolevich** [comment]
@lunawesley9, try to do like 
```
$log = $this->log->where('execution_id', $id)->where('url', 'regex', '/#1/i')->first();
```

**Comment by Giacomo92** [comment]
Hi @lunawesley9 `log` is a subcollection of `$this`?
