### ISSUE TITLE
Please Add 'distanceField' in mongodb geoNear query

### ISSUE THREAD

**Issue by Siltaz** [jenssegers/laravel-mongodb#1878]
I'm trying to make a geoNear query:
```
            '$geometry' => [
                'type' => 'Point',
                'coordinates' => [
                    $longitude,
                    $latitude
                ],
            ],
            '$maxDistance' => 2000,
            'distanceField' => 'distance'
```

and getting an error "invalid argument in geo near query: distanceField"

But MongoDB supports 'distanceField' option. Reference https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear

Please add 'distanceField' in geo near query, this will make this library better !!
And thanks for this amazing library :+1:

**Comment by Smolevich** [comment]
@siltaz please fill description

**Comment by qingdi** [comment]
$rs = $this->raw(function ($collection){
            return $collection->aggregate([
                [
                    '$geoNear' => [
                        'key' => "coordinates",
                        'near' =>  ['type' => "Point",  'coordinates' => [ 116.414326, 39.922964 ] ],
                        'maxDistance' =>  1000,
                        'distanceField' =>  "distance",
                        'spherical' =>  true
                    ]
                ]
            ]);
        });
        return $rs;

**Comment by henriquetroiano** [comment]
Thanks @qingdi ! I'll make a pull request on the readme with that instruction!
