### ISSUE TITLE
In memory database

### ISSUE THREAD

**Issue by A-H-Pooladvand** [jenssegers/laravel-mongodb#1888]
Hi there!  
I know this is probably isn't a related question but since we using this package we can't really take advantage of sqlite for testing so my question is that is there any possible way to have or implement an in-memory database testing for mongodb?

**Comment by Smolevich** [comment]
@A-H-Pooladvand, do you want use mongodb for testing cases or main storage?

**Comment by A-H-Pooladvand** [comment]
@Smolevich well I'm using mongodb as main DB but I want to know if there is an in memory feature for test cases

**Comment by Smolevich** [comment]
it depends from configuration mongodb, For example you can run instance with in-memory engine( [Docs](https://docs.mongodb.com/manual/core/inmemory/))

**Comment by Smolevich** [comment]
@A-H-Pooladvand Am i answer on your question?

**Comment by sevillaarvin** [comment]
Thanks, it answered my question. As mentioned in the linked docs, however, inMemory engine is mongodb enterprise only.

See also https://github.com/docker-library/mongo/issues/224

Guess I'll just spin up a mongodb docker instance for testing.
