### ISSUE TITLE
Making it work on HHVM?

### ISSUE THREAD

**Issue by ryuheiyokokawa** [jenssegers/laravel-mongodb#189]
I know this one's a long shot, but I do have it almost working on HHVM.
I've compiled HHVM 3.0 and HHVM Mongodb drivers from 10gen-labs (https://github.com/10gen-labs/mongo-hhvm-driver).

I can connect to the thing and everything works except for MongoCollection:

```
Fatal error: Uncaught exception 'ErrorException' with message 'Undefined variable: cmd' in :0
Stack trace:
#0 (): Illuminate\\Exception\\Handler->handleError()
#1 (): MongoDB->command()
#2 /laravel/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(159): MongoCollection->aggregate()
#3 /laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1261): Jenssegers\\Mongodb\\Query\\Builder->getFresh()
#4 /laravel/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(250): Illuminate\\Database\\Query\\Builder->get()
#5 /laravel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1589): Jenssegers\\Mongodb\\Query\\Builder->aggregate()
#6 (): Illuminate\\Database\\Query\\Builder->count()
```

(above is from Mongodb/Query/Builder.php line 159).

I looked at the code, but apparently it thinks that the system is not being passed an array ($cmd) when it clearly is passing an array.

I'll cross post this on the 10gen-labs issues too, but if you have any ideas about this please let me know.

**Comment by lukepolo** [comment]
I have installed hhvm and mongofill-hhvm , it almost works except it doesn't like the IN clause 

        "$err" => "Can't canonicalize query: BadValue $in needs an array"
        "code" => 17287

**Comment by jenssegers** [comment]
I will add HHVM and PHP7 to the Travis builds and try to fix them as much as possible.

**Comment by abishekrsrikaanth** [comment]
Are there any updates to this?

**Comment by jenssegers** [comment]
Still need to figure out how to get mongodb working on Travis + HHVM

**Comment by abishekrsrikaanth** [comment]
Would you have any specific date on when this would be ready. I am not able to deploy my application on hhvm because of this dependency.

**Comment by jenssegers** [comment]
Not really. I'm hoping for people to contribute PR's as I'm not very familiar with HHVM.
