### ISSUE TITLE
Compatibility: Laravel 5.6 - PHP 7.2 - MongoDB 4.2

### ISSUE THREAD

**Issue by Benjiiii** [jenssegers/laravel-mongodb#1890]
Hi,

Sorry if this is more a question than an issue but I haven't found the documentation confirming what I'm asking.

We are currently running a environment with Laravel 5.6, PHP 7.2 and MongoDB 3.4 and have to migrate our MongoDB host to a new solution. We are thinking of updating MongoDB to 4.2 during this process.

It this setup compatible? (PHP 7.2, Laravel 5.6, laravel-mongodb 3.4.*, MongoDB 4.2)

Thanks!

**Comment by Smolevich** [comment]
hello, @Benjiiii . it is possible

**Comment by Benjiiii** [comment]
Great! Thank you :)
