### ISSUE TITLE
Cannot instantiate abstract class App\User

### ISSUE THREAD

**Issue by biswajit-unified** [jenssegers/laravel-mongodb#1891]
At first, I have setup laravel project with MySQL, now I switched to MongoDB. Then I am getting this error: `Cannot instantiate abstract class App\User`. This issue happens when I implement MustVerifyEmail ->
~~~php
class User extends Authenticatable implements MustVerifyEmail
{
~~~

I got detailed error from telescope:
~~~json
{
    "message": "Class App\\User contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Illuminate\\Contracts\\Auth\\MustVerifyEmail::hasVerifiedEmail, Illuminate\\Contracts\\Auth\\MustVerifyEmail::markEmailAsVerified, Illuminate\\Contracts\\Auth\\MustVerifyEmail::sendEmailVerificationNotification, ...)",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "file": "/var/www/html/lv/test/app/User.php",
    "line": 11,
    "trace": []
}
~~~

![Screenshot_2019-12-19 Screenshot](https://user-images.githubusercontent.com/58461485/71153348-e99ef380-225e-11ea-9920-895a4bf0f2bc.png)

Please help.

**Comment by Smolevich** [comment]
Try as 
```
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
```

**Comment by biswajit-unified** [comment]
@Smolevich 

I have already removed the interface MustVerifyEmail. Thanks for your quick response.

**Comment by Smolevich** [comment]
@biswajit-unified if you solve this problem, please close issue
