### ISSUE TITLE
Proposal about new maintainers

### ISSUE THREAD

**Issue by Smolevich** [jenssegers/laravel-mongodb#1892]
@jenssegers, library has pending PR's waiting review one month and more, old docs, broken ci in travis, many issues without answers for community. I propose to find new maintainers from community, if you don't have enough time to maintance this library. Any can fork and improve separately but I think that community can improve this library if maintainers will have enough time for maintance.

With regards, Smolevich

**Comment by Smolevich** [comment]
Fixed failed ci https://github.com/jenssegers/laravel-mongodb/pull/1893

**Comment by brandon-braner** [comment]
I would be more than happy to volunteer to help maintain this project. I am just starting to use it however I was also a bit concerned about the number of open issues and pull requests. It makes me feel uneasy about using it in a production system.

Does anyone know how to get a hold of the owner? If they are not checking issues not sure this will ever get seen.

**Comment by jenssegers** [comment]
Hi @brandon-braner, shall we set up a skype call to discuss this?

**Comment by brandon-braner** [comment]
@jenssegers I would love to. Can I email you at hello@jenssegers.com? Grabbed that from your Github profile.

**Comment by Smolevich** [comment]
@brandon-braner, @jenssegers can we discuss together, in slack or email?

**Comment by brandon-braner** [comment]
Slack sounds appropriate @Smolevich @jenssegers Here is a link to the slack workspace I made. I have it setup so I have to approve your addition so if you can let me know when you join and I will approve it

[Join Open Source Code Project](https://join.slack.com/t/opensourcecodeproject/shared_invite/enQtODc0ODEyOTk0NDgyLWIwYzRmMDk0ODEzNzA2Y2YwYzFjZmZkOWE0M2Q4MWNiZTI3NWFiYWE4NTkyOGFhN2JhNzBhNmRiYjM1YTBmNGE)

One of my new years goals was to start contributing to open source and maybe make a youtube channel out of it to teach and encourage others to do it as well, I am very excited that this could kick that off with a bang 💥

**Comment by Smolevich** [comment]
@brandon-braner, [here](https://github.com/jenssegers/laravel-mongodb/issues/1791) link on existing slack community

**Comment by divine** [comment]
@jenssegers well, first of thank you for the work that you've done.

We can understand that this is open source and you're not paid for this, however the fact that you've simply ignoring pull requests from other contributors makes everyone sad and unhappy while using this library in a project.

If you don't have a time, please kindly archive this repo and give a chance to somebody else/some other library or just add some information to readme that this library reviewing pull requests in ~4 months and there are so many bugs/issues - use at your own risk.

Thank you!

**Comment by rennokki** [comment]
I stopped waiting for the updates and jumped and improved it in my fork: https://github.com/rennokki/laravel-mongodb

PRs are welcomed :)

**Comment by Smolevich** [comment]
@rennokki i propose to wait answer from @jenssegers. Are you single maintainer of your fork? Do you have plans on improvement library ? How many time do you spend on library?

**Comment by rennokki** [comment]
I use mongo actively on some production workloads on my day-to-day job and side projects, and sometimes custom implementations are not unusual, and the times to wait for an update is killing the productivity, that's why I forked the repo.
 Currently, I am the only one, but I can actively select some in the case it is needed.

**Comment by divine** [comment]
@Smolevich @rennokki well, if we're a looking for a new fork some issues needs to be fixed and reworked.

Current implementation is a bit hacky, probably best would to remove mysql support and use [doctrine mongodb](https://github.com/doctrine/mongodb-odm).

There is already an [implemented integration](https://github.com/chefsplate/laravel-doctrine-odm) but it's not updated since 2017.

**Comment by rennokki** [comment]
I have searched for issues throughout the Issues board and the addressed PRs, but i found some that are old and i didn't find any real reason why they should be merged.

The broken CI also freaked me because having several production workloads and using a package that continues to merge the PRs without having the CI check is risky.

**Comment by Smolevich** [comment]
@rennokki PR with support GA was [merged](https://github.com/jenssegers/laravel-mongodb/pull/1859), problem with failed travis ci was [fixed](https://github.com/jenssegers/laravel-mongodb/pull/1893), so all new PR's are checked 

@rennokki do you want to help with maintenance this library ? As i can see you improve you fork but we (@jenssegers , @brandon-braner and I) can come together to support an improve this library but before we discuss about future plans on this library
I propose each ask on some questions if someone want to become maintainer of this library:
1. What is your experience as a maintainer of some library or framework? Maybe links on projects on github
2. How many hours are you ready spent on supporting this library?
3. Who uses this library in production ?

**Comment by rennokki** [comment]
Not much in open source - i really implemented packages across several Laravel apps in private repos at my day-to-day job which sticks with Laravel/Lumen for 2+ years.
I check github daily on issues, so that's what made me tryna gather more ppl to PR their problems and fix them in a separate package.

I don't mind maintaining this library at all. I also use it in production on several projects.

**Comment by divine** [comment]
Well, I'm really happy this isn't new fork and we're all here now. Previously something like this already happened (see dead fork which isn't maintained anymore https://github.com/moloquent/moloquent).

@jenssegers I kindly ask you (or just my personal suggestion), please add new maintainers who are ready to help out, everyone will be just happy and issues will be fixed instantly!

@Smolevich thank you for taking care!

Thank you!

**Comment by rennokki** [comment]
@Smolevich mail me the slack if there's any

**Comment by Smolevich** [comment]
@rennokki, `Alex Renoki` is it your nickname in slack for this library?

**Comment by Smolevich** [comment]
@jenssegers add new some contributors. Thanks for reaction, Jens. 
I propose to do next tasks as soon possible :
1. collect bugs in last issues
2. Add https://github.com/apps/stale for check new issues 
2. Add templates for issues () [Docs](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) Link to issue https://github.com/jenssegers/laravel-mongodb/issues/1912
3. Close old and not actual issues and PR's

**Comment by divine** [comment]
> @jenssegers add new some contributors.

That's sound great 👍 . Thank you @jenssegers!

> 3\. Add templates for issues () [Docs](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) Link to issue #1912

I might take care as well.

> 4. Close old and not actual issues and PR's
I'm currently checking each PR's if it was already merged/fixed, it takes time.

**Comment by Giacomo92** [comment]
@Smolevich 
5 Add a static site docs. The README is too long. So I think we can improve searchability and add more examples

**Comment by rennokki** [comment]
@Giacomo92 i think that would be too complicated, maybe having a short and concise docs would be better.

**Comment by rennokki** [comment]
StyleCI and CodeCov/Codacy can be a good start too.

**Comment by Smolevich** [comment]
I propose to add any ideas here https://github.com/jenssegers/laravel-mongodb/issues/1914

**Comment by Giacomo92** [comment]
> @Giacomo92 i think that would be too complicated, maybe having a short and concise docs would be better. It's about the quality not the quantity.

Complicated? Why ? It is a simple markdown file. You do not need to know anything else. A docs site is more readable and maintainable. Every package has a site, see [Spatie Docs](https://docs.spatie.be)
