### ISSUE TITLE
Call to undefined method Jenssegers\Mongodb\Query\Builder::getCategoriesAttribute()

### ISSUE THREAD

**Issue by hassan-maavan** [jenssegers/laravel-mongodb#1895]
"laravel/lumen-framework": "5.5.*",
"jenssegers/mongodb": "^3.2",

###Lumen

BadMethodCallExceptionCall to undefined method Jenssegers\Mongodb\Query\Builder::getCategoriesAttribute()
--
in Builder.php line 2483
at Builder->__call('getCategoriesAttribute', array(null))in Builder.php line 1150
at Builder->__call('getCategoriesAttribute', array(null))in Builder.php line 1286
at Builder->__call('getCategoriesAttribute', array(null))in Model.php line 1477
at Model->__call('getCategoriesAttribute', array(null))in Model.php line 433
at Model->__call('getCategoriesAttribute', array(null))in HasAttributes.php line 438
at Model->mutateAttribute('categories', null)in HasAttributes.php line 450
at Model->mutateAttributeForArray('categories', null)in HasAttributes.php line 109
at Model->attributesToArray()in Model.php line 189
at Model->attributesToArray()in Model.php line 977
at Model->toArray()in Model.php line 1006
at Model->jsonSerialize()in Model.php line 990
at Model->toJson()in Response.php line 74
at Response->morphToJson(object(User))in Response.php line 35
at Response->setContent(object(User))in Response.php line 206
at Response->__construct(object(User))in RoutesRequests.php line 431
at Application->prepareResponse(object(User))in RoutesRequests.php line 373
at Application->callControllerCallable(array(object(AccountController), 'loginUser'), array())in RoutesRequests.php line 339
at Application->callLumenController(object(AccountController), 'loginUser', array(true, array('uses' => 'App\\Http\\Controllers\\AccountController@loginUser'), array()))in RoutesRequests.php line 313
at Application->callControllerAction(array(true, array('uses' => 'App\\Http\\Controllers\\AccountController@loginUser'), array()))in RoutesRequests.php line 275
at Application->callActionOnArrayBasedRoute(array(true, array('uses' => 'App\\Http\\Controllers\\AccountController@loginUser'), array()))in RoutesRequests.php line 260
at Application->handleFoundRoute(array(true, array('uses' => 'App\\Http\\Controllers\\AccountController@loginUser'), array()))in RoutesRequests.php line 160
at Application->Laravel\Lumen\Concerns\{closure}(object(Request))
at call_user_func(object(Closure), object(Request))in Pipeline.php line 52
at Pipeline->Laravel\Lumen\Routing\{closure}(object(Request))in LogRequest.php line 24
at LogRequest->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request))in Pipeline.php line 32
at Pipeline->Laravel\Lumen\Routing\{closure}(object(Request))in Request.php line 29
at Request->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
at call_user_func(object(Closure), object(Request))in Pipeline.php line 32
at Pipeline->Laravel\Lumen\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in RoutesRequests.php line 410
at Application->sendThroughPipeline(array('App\\Http\\Middleware\\Request', 'App\\Http\\Middleware\\LogRequest'), object(Closure))in RoutesRequests.php line 166
at Application->dispatch(null)in RoutesRequests.php line 107
at Application->run()

**Comment by Smolevich** [comment]
@hassan-maavan what steps for reproducing this error?

**Comment by hassan-maavan** [comment]
I have a user model with the embed relation.
```
public function purchasedStories()
    {
        return $this->embedsMany('App\Models\UserPurchaseStory');
    }
```
whenever I do find the user with wrong _Id, means that don't exists in the DB, it shows me this error.

**Comment by Smolevich** [comment]
@hassan-maavan show more info:
version of library
php-driver version
mongo version
