### ISSUE TITLE
jenssegers/mongodb 3.6 not supported required 3.5.* error

### ISSUE THREAD

**Issue by brijesh6491** [jenssegers/laravel-mongodb#1897]
<b> Problem 1
- designmynight/laravel-mongodb-passport v1.2.7 requires jenssegers/mongodb 3.3.* || 3.4.* || 3.5.* -> satisfiable by jenssegers/mongodb[v3.3.0, v3.3.0-alpha, v3.3.1, v3.4.0, v3.4.1, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.5.0, v3.5.1, v3.5.2, v3.5.3] but these conflict with your requirements or minimum-stability.
</b>

``` 
"require": {
        "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "jenssegers/mongodb": "^3.6",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0",
        "league/fractal": "^0.18.0",
        "prettus/l5-repository": "^2.6",
        "robclancy/presenter": "^1.4"
    }
```

**Comment by Smolevich** [comment]
@brijesh6491 please format text as code block and show version of this package in your composer.json

**Comment by brijesh6491** [comment]
please check I have updated code block and added composer JSON

**Comment by Smolevich** [comment]
Write maintainer library `designmynight/laravel-mongodb-passport` about new release or use `master-dev` https://github.com/designmynight/laravel-mongodb-passport/blob/master/composer.json#L17

**Comment by Smolevich** [comment]
@brijesh6491 https://github.com/designmynight/laravel-mongodb-passport/issues/28

**Comment by Smolevich** [comment]
@brijesh6491 it is not problem of this library, so close issue please

**Comment by brijesh6491** [comment]
ok, thank you
