### ISSUE TITLE
How to define $dates attribute for array of documents?

### ISSUE THREAD

**Issue by dungnv93** [jenssegers/laravel-mongodb#1898]
Hi,
in Laravel + MongoDB
So my problem is: For example I want following structure:

```
"bands" : [
    {
        "valid_from" : ISODate("2019-01-01T09:00:00.000+09:00"),
        "valid_to" : ISODate("2019-08-31T09:00:00.000+09:00")
    },
    {
        "valid_from" : ISODate("2019-09-01T09:00:00.000+09:00"),
        "valid_to" : ISODate("2019-12-31T09:00:00.000+09:00")
    }
]
```

But on select as related object I have this date conversion issue
```
"bands" : [
    {
        "valid_from" : {
            "$date": {
                "$numberLong": "1554542206000"
            }
        },
        "valid_to" : {
            "$date": {
                "$numberLong": "1554455806312"
            }
        }
    },
    {
        "valid_from" : {
            "$date": {
                "$numberLong": "1554542206000"
            }
        },
        "valid_to" : {
            "$date": {
                "$numberLong": "1554455806312"
            }
        }
    }
]
```
Thanks for your help !

**Comment by lostdesign** [comment]
Did you try to use the [Laravel Date Mutators](https://laravel.com/docs/6.x/eloquent-mutators#date-mutators) on your Model? That should be enough, it will give you Carbon instances which you can then modify.

**Comment by dungnv93** [comment]
@lostdesign thanks for help
but you know, 
```
protected $dates = ['bands.valid_from', 'bands.valid_to'];
```
With the setting above for the single array $bands as 
```
"bands" : [
    "valid_from" : ISODate("2019-01-01T09:00:00.000+09:00"),
    "valid_to" : ISODate("2019-08-31T09:00:00.000+09:00")
]
```
so, i changed model to
```
protected $dates = ['bands.*.valid_from', 'bands.*.valid_to'];
```
Of course, laravel doesn't understand the setting above, and i customized attributesToArray() function in model. now it working.
![image](https://user-images.githubusercontent.com/41067937/71881079-fc795980-3174-11ea-9b40-1349f1d2dcab.png)
i don't know other good idea. if who have good idea, please tell to me.
thanks!
