### ISSUE TITLE
Moloquent object returns 2 different types of _id attribute in v1.2.7. 

### ISSUE THREAD

**Issue by smaeda** [jenssegers/laravel-mongodb#190]
Hi, there.

$some_mol_obj_id = $some_mol_obj->_id;
// $some_mol_obj_id has a string value like below.
// "01234678901234567890123"

// but, 
$attributes = $some_mol_obj->getAttributes();
// $attributes['_id'] has a HASH value like below.
// [
//     '$id' => "01234678901234567890123"
// ]

In v1.2.3 I found they returned the same string values "01234678901234567890123".
Changed?

**Comment by fraank** [comment]
Is this issue still open? I'm running into the same Problems, when updating a Model (on created-observer, which is just created) getting an error "Mod on _id not allowed".
