### ISSUE TITLE
how to sort data

### ISSUE THREAD

**Issue by mkumarjha** [jenssegers/laravel-mongodb#1900]
How i can achieve sort data by given array using orderBy here ?
$prd_ids = [5,3,4]; 
$product_data = Product::where('status',1)->orderBy('avg_rev',$prd_ids);

**Comment by Smolevich** [comment]
[orderBy](https://github.com/laravel/framework/blob/0dd1a50f041f227e21c42f0bd92f91af9121eab8/src/Illuminate/Database/Query/Builder.php#L1801) implemented as laravel repository
Also mongodb has issue in tracker https://jira.mongodb.org/browse/SERVER-7528
