### ISSUE TITLE
Documentation: Create unique index in background

### ISSUE THREAD

**Issue by cbanbury** [jenssegers/laravel-mongodb#1906]
Can you provide an example in the README of how to create a unique index in the background, I can't figure out how to combine these options.

Thanks!

**Comment by Giacomo92** [comment]
Hi @cbanbury , what do you mean with "in background"?
In the docs there is an example of how to create an index with a migration. See [here](https://github.com/jenssegers/laravel-mongodb#schema)

**Comment by cbanbury** [comment]
@Giacomo92, 

I'm trying to do something like this:

```
db.users.createIndex( { "username": 1 }, { sparse: true, unique: true, background: true} )
```
The docs show how to make a unique index, and lists supported options including background and sparse, but I don't know how to build something like the above.

I expect to be able to do something like :
```
$collection->unique('username')->background(true);
```

**Comment by Giacomo92** [comment]
@cbanbury 
Try to pass a key value array on the `$options` parameter.
```
$collection->index('username',null,null,[
                'sparse' => true,
                'unique' => true,
                'background' => true
]);
```

See the`index()` method implementation [here](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Schema/Blueprint.php#L40)

**Comment by cbanbury** [comment]
@Giacomo92 
Ahh that works, cheers!
