### ISSUE TITLE
How to return "_id" in string?

### ISSUE THREAD

**Issue by ngooide** [jenssegers/laravel-mongodb#1921]
Hi all great contributors,
I have this challenges on getting "_id" in string.
as per the image attached,
document _id return as expected as string
but embedsMany return as ObjectId.
Anything that I've done wrongly?
Tq everyone!

value return to json
![image](https://user-images.githubusercontent.com/4960528/72906948-0357bd00-3d6e-11ea-9e41-b7214d98d5da.png)

value in mongodb.
![image](https://user-images.githubusercontent.com/4960528/72906908-ecb16600-3d6d-11ea-802a-2937c2735501.png)

**Comment by Smolevich** [comment]
@ngooide, What do you want to do?

**Comment by Smolevich** [comment]
Please show code for models, version of library, version php driver, mongo version

**Comment by divine** [comment]
@ngooide have you tried attribute casting?

https://laravel.com/docs/6.x/eloquent-mutators#attribute-casting

**Comment by matthiouze** [comment]
it's ugly but when I create a new object after the insertion I update an id field with the actual _id

so I have 
_id : new ObjectId
id : I save it after the insertion...

it's not a beautiful solution but I have to move forward lol
