### ISSUE TITLE
Old checks in ci

### ISSUE THREAD

**Issue by Smolevich** [jenssegers/laravel-mongodb#1925]
We have old not existing checks, 
<img width="658" alt="Снимок экрана 2020-01-24 в 10 41 50" src="https://user-images.githubusercontent.com/7188867/73052786-039fa780-3e97-11ea-9022-ad193ffe8ffd.png">

Link on community forum: https://github.community/t5/GitHub-Actions/GitHub-Actions-Pull-requests-always-include-some-outdated-checks/td-p/30030

**How fix it**: remove the outdated check in the protected brunch settings of the repository settings.

PR's with old checks: 
https://github.com/jenssegers/laravel-mongodb/pull/1924
https://github.com/jenssegers/laravel-mongodb/pull/1917
https://github.com/jenssegers/laravel-mongodb/pull/1916
https://github.com/jenssegers/laravel-mongodb/pull/1923

**Comment by rennokki** [comment]
@Smolevich close this?
