### ISSUE TITLE
MongoDB 4.0 support?

### ISSUE THREAD

**Issue by AbhijeetSalunkhe** [jenssegers/laravel-mongodb#1932]
is this application support mongodb 4.x version.

**Comment by Smolevich** [comment]
Yes

**Comment by AbhijeetSalunkhe** [comment]
Can you tell me dependency about this package and laravel+mongo+php

**Comment by Giacomo92** [comment]
Hi @AbhijeetSalunkhe , as you can see from GA:
- [PHP](https://github.com/jenssegers/laravel-mongodb/blob/master/.github/workflows/build-ci.yml#L14): '7.1', '7.2', '7.3', '7.4'
- [Mongo](https://github.com/jenssegers/laravel-mongodb/blob/master/.github/workflows/build-ci.yml#L14): '3.6', '4.0', '4.2'
- Laravel: see [here](https://github.com/jenssegers/laravel-mongodb#laravel-version-compatibility)

**Comment by AbhijeetSalunkhe** [comment]
Hi @Giacomo92 , i want laravel+php+mongo version which are compatible for this package..
if i update mongo 4.0 + laravel 6.0 + PHP 7.1.. so this package are run without issue?
That's why i create this issue, so i want to use this package for mongo 4.x version

**Comment by Smolevich** [comment]
@AbhijeetSalunkhe , this library supports work with mongo >4.0, table in README describe compability with laravel framework
