### ISSUE TITLE
String being converted to INF (infinite) on insert

### ISSUE THREAD

**Issue by rafaelget** [jenssegers/laravel-mongodb#1936]
this strange behaviour is happening with only this string "5e0650730336790041540328", at least this is the only one that I had notice

When I do: 
$newActivity = ['member_id' => "5e0650730336790041540328"];
$activity = $duel->activities()->create($newActivity);

It returns me:
[
       "_id" => "5e32dd6fe6c0c55c79231723",
       "duel_id" => "5dfd04b4717d3001101769d0",
       **"member_id" => INF**
]

**Comment by Smolevich** [comment]
@rafaelget describe version laravel-mongodb, php mongo driver and mongo

**Comment by Smolevich** [comment]
What mongo store `member_id`?

**Comment by rafaelget** [comment]
laravel/framework v5.8.30
jenssegers/mongodb v3.5.1
mongodb/mongodb 1.2.0

mongodb 3.6

If a do the insertion directly on database (Robo 3T), the correct string is inserted.

member_id holds the string ID from members collection.

**Comment by Smolevich** [comment]
No, i means if execute code 
```
$newActivity = ['member_id' => "5e0650730336790041540328"];
$activity = $duel->activities()->create($newActivity);
```
and see and cli for mongo or Robo3T, what value will be shown?

**Comment by rafaelget** [comment]
stored value is: Infinity
type: Double

**Comment by Smolevich** [comment]
Try replace `$newActivity = ['member_id' => "5e0650730336790041540328"];` on `$newActivity = ['member_id' => new ObjectId("5e0650730336790041540328")];`

**Comment by rafaelget** [comment]
it worked, thank you
