### ISSUE TITLE
Cannot update positions

### ISSUE THREAD

**Issue by matthiouze** [jenssegers/laravel-mongodb#1946]
Hello,
Here is the context. I have some categories and subCategories. each subCategories are embeded in a category, it gives

`{
    "_id" : ObjectId("1"),
    "name" : "Category 1",
    "subCategories" : [ 
        {
            "nom" : "subCat 1",
            "position" : 1,
            "_id" : ObjectId("2")
        }, 
                {
            "nom" : "subCat 2",
            "position" : 2,
            "_id" : ObjectId("3")
        }, 
        {
            "nom" : "subCat 3",
            "position" : 3,
            "_id" : ObjectId("3")
        }
    ]
}`

I just want to reorder with a drag and drop all subCategories by updating the position.
with laravel I can update the position with a :
$subcat->update(['position' => $position]);
the update in the database is done but the render does not change.

I think that I have to change the order in the json...
if I want to have subCat 2 in position 1 in the render, I have to have subCat 2 in first position in the json.

I have found that peace of mongodb code (executed directly in the console of robo 3T): 

`db.getCollection("categories").update(
   { _id: ObjectId("1") },
   {
     $push: {
       subCategories: {
         $each: [],
         $sort: { position: 1 }
       }
     }
   }
)`
It seems to work fine after the update in laravel but I don't find anything to run that peace of code in laravel.

Could you help (@jenssegers ) ?

Many Thanks

**Comment by divine** [comment]
Hello,

Could you please try using raw expression?

Something like this, just and idea, haven't tested.

```php
Product::raw(function($collection) {

 return $collection->update(

    ['_id' => '1'],

    [
        '$push' => [

            'subCategories' => [

                '$each' => [],

                '$sort' => ['position' => 1]

            ]

        ]

    ]);
}

```

**Comment by matthiouze** [comment]
Hello,

with the request you gave me I have an error :
 call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Collection' does not have a method 'update'

I've tried with :



````
DB::connection('mongodb')->collection('categories', function($collection) use($categoryId)
            {
                $collection->push(
                    ['_id' => $categoryId],
                    [
                        'sections' => [
                            '$each' => [],
                            '$sort' => ['position' => 1]
                        ]
                    ]);
            });`

but nothing is updated

**Comment by divine** [comment]
Sorry, change update to findOneAndUpdate

**Comment by matthiouze** [comment]
no errors but still nothing :(

**Comment by matthiouze** [comment]
you need to cast the categoryId with 
````
Questionnaire::raw(function($collection) use($questionnaireId)
        {
            $collection->findOneAndUpdate(
            ['_id' => new ObjectId($questionnaireId)], // and not just ['_id' => $categoryId]
            [
                '$push' => [
                    'sections' => [
                        '$each' => [],
                        '$sort' => ['position' => 1]
                    ]
                ]
            ]);
        });
