### ISSUE TITLE
MorphMany Relation error -  Call to undefined method Builder::compileWhereInRaw()

### ISSUE THREAD

**Issue by graphicmist** [jenssegers/laravel-mongodb#1947]
Hi,

I am using latest version of  jenssegers / laravel-mongodb and laravel 5.8.
I am using  morphMany Relation which is causing the following error:
```
 BadMethodCallException
Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereInRaw()
```

My Relation:
```
    public function logs(): MorphMany
    {
        return $this->morphMany(Log::class, 'subject');
    }

```
All logs are inserted in mongodb, whereas rest of tables are in mysql database.
Log Class extends Jenssegers\Mongodb\Eloquent\Model
Fetching logs basis subject is causing this error.
Any ideas?

**Comment by graphicmist** [comment]
The relation is working fine but if i try to fetch the records using with in model it is throwing the above error.
Eg:
Product::with('logs')->find($id);

**Comment by divine** [comment]
Hello,

Could you please try current master version?

Can be installed via `composer require jenssegers/mongodb:dev-master`

It has been fixed (see PR https://github.com/jenssegers/laravel-mongodb/pull/1871) but new version isn't released just yet.

Thank you!

**Comment by graphicmist** [comment]
Thanks @divine
