### ISSUE TITLE
Model::truncate fails

### ISSUE THREAD

**Issue by fosron** [jenssegers/laravel-mongodb#1948]
`\Jenssegers\Mongodb\Query\Builder::truncate` method is failing when invoked as `Model::truncate()`

<img width="592" alt="Screenshot 2020-02-07 17 36 47" src="https://user-images.githubusercontent.com/3708631/74042564-739e4980-49d0-11ea-90eb-22baa07afa1b.png">

It checks the `result` as an object, even though an array is returned.

I'm running this from PHPUnit's `setUp` or `tearDown` steps.

Doing `Email::raw()->drop();` works.

MongoDB version: v4.2.2
Library version: 3.6.1

**Comment by divine** [comment]
Hello,

Could you please check PR https://github.com/jenssegers/laravel-mongodb/pull/1949

Does it fix your issue?

Thank you!

**Comment by fosron** [comment]
@divine It took some time to release it, but it works great! Thanks!
