### ISSUE TITLE
Authentication with collection subdocument in laravel mongodb is not working

### ISSUE THREAD

**Issue by vinothini3** [jenssegers/laravel-mongodb#1965]
Im trying to do authentication with collection's subcollection but i can't able to do it.

Please someone help... Struggling a lot with this. 

Please see the my stackoverflow question : https://stackoverflow.com/questions/60202602/authentication-with-collection-subdocument-in-laravel-mongodb

**Comment by divine** [comment]
Hello,

Laravel passport doesn't work out of the box since its using eloquent models instead of this libraries one.

Use something like https://github.com/designmynight/laravel-mongodb-passport

Thanks.

**Comment by vinothini3** [comment]
So i cant use passport in jessenger/laravel-mongodb?

**Comment by divine** [comment]
> So i cant use passport in jessenger/laravel-mongodb?

This is currently doesn't work as I have said previously, you will need to use third party package which is only overwriting default models to use from this library.

Thanks.
