### ISSUE TITLE
Using nested object fields with Form Model Binding

### ISSUE THREAD

**Issue by duro** [jenssegers/laravel-mongodb#197]
We have a Mongo Model that has a structure like so:

```
{
  _id: ObjectId('...'),
  name: 'Model Name',
  address: {
    street1: '555 Fake St.',
    street2: 'Unit 123',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90293'
  }
}
```

We are trying to use this object with form model binding.

Here is what that form looks like:

```
{{ Form::model($object, array('route' => 'named.route') }}
{{ Form::text('name') }}
{{ Form::text('address[street1]') }}
{{ Form::text('address[street2]') }}
{{ Form::text('address[city]') }}
{{ Form::text('address[state]') }}
{{ Form::text('address[zip]') }}
{{ Form::submit('save') }}
{{ Form::close() }}
```

This syntax works just fine for saving a new instance of the object. However, when we try and use the same form to display an existing instance of the object, the `name` field displays, but none of the nested field that belong to `address` will display.

I did some digging, and it appears that when the Eloquent object that is returned represents that nested object as an array. The internals of Laravel (`Illuminate/Html/FormBuilder->getModelAttribute()` ) convert this syntax to dot notation (eg. `address.street1` ) and then use an internal function in `Illuminate/Support/helpers.php` called `object_get` to traverse the model using that dot syntax looking for the value.

It seems that Laravel does not like the mixing of types. It does not like to use that dot syntax to look inside an object, and then dig into an array to find the next key.

Let me know if I'm not making sense.

It seems to me, that what Laravel wants, is for the `address` to be an object, not an array.

Is this something that would be possible to adjust in the way Laravel-MongoDB converts nested objects when turning them into Elequent models?

**Comment by foxbit19** [comment]
Any news on this?
