### ISSUE TITLE
Eloquent Query using Dynamic Model Laravel[Question] 

### ISSUE THREAD

**Issue by starking8b** [jenssegers/laravel-mongodb#1973]
I have this code which I am using to create a dynamic model in laravel

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class CRUD extends Eloquent
{
public $collection ;

function __construct($attributes = [],$collection ="" )
{  
    parent::__construct($attributes);
$this->collection = $collection;

}
}
and I call this class using this code

 $table='HW12345' ;
 $device_model = new CRUD([],$table);
 $device_model::limit(10)->get();
but this code return empty array . if I put this code inside the constractor

echo $collection
it print the correct value

HW12345

that mean model get the value of passed variable .

if I replaced the code

$this->collection = $collection;

to

$this->collection = 'HW12345';

it is working right without any problem and return data from collection HW12345 what is my wrong and why is that happening

this is the link on stackoverflow
https://stackoverflow.com/questions/60415088/eloquent-query-using-dynamic-model-laravel

**Comment by divine** [comment]
You have got answer on stackoverflow, follow up here.

**Comment by starking8b** [comment]
I followed but the answer was not correct so I post the question here  , you can check the comments under the answer which you talking about

**Comment by starking8b** [comment]
please help me, I need your help, I stuck here

**Comment by divine** [comment]
Have you checked that it works with mysql at first?

See this answer https://stackoverflow.com/a/57400031

**Comment by starking8b** [comment]
I checked but also get nothings

**Comment by starking8b** [comment]
my code is logically right and working when I set the table name inside the class but not working when pass table name as variable, that makes me crazy

**Comment by ollieread** [comment]
This problem isn't with this package it's with laravel. The code behind eloquent is somewhat mad, but there's several new instances of the model created during the process, so new instances won't inherit the table.

**Comment by starking8b** [comment]
so what do u think the solution ?  what should I do

**Comment by divine** [comment]
@starking8b use something like this instead of eloquent magic:

```php
    public function testInsert()
    {
        DB::collection('users')->insert([
            'tags' => ['tag1', 'tag2'],
            'name' => 'John Doe',
        ]);

        $users = DB::collection('users')->get();
        $this->assertCount(1, $users);

        $user = $users[0];
        $this->assertEquals('John Doe', $user['name']);
        $this->assertIsArray($user['tags']);
    }
```

Stolen from https://github.com/jenssegers/laravel-mongodb/blob/master/tests/QueryBuilderTest.php#L83-L96
