### ISSUE TITLE
Find on EmbedsMany?

### ISSUE THREAD

**Issue by mikebronner** [jenssegers/laravel-mongodb#199]
Maybe I'm overthinking this, or went down the wrong track with my train of thought, but for some reason I can't figure out how to get a specific embedded subdocument. Given the User / Books example in the read me:

```
use Jenssegers\Mongodb\Model as Eloquent;

class User extends Eloquent {
    public function books()
    {
        return $this->embedsMany('Book');
    }
}
```

I want to do the following:

```
$user = Users::find(1); // no problems there, we have a good user object with many books
$books = $user->books();
$book = $books->where(['title', '=', 'The Great Gatsby'])->first(); //this isn't working
```

Depenging on the query, it will either time out or return the following error:

```
Illegal offset type.

            if (substr($value, -1) != '%')   $regex = $regex . '$';

            $value = new MongoRegex("/$regex/i");
        }

        if (!isset($operator) || $operator == '=')
        {
-->            $query = array($column => $value); //this line errors out
        }
        else if (array_key_exists($operator, $this->conversion))
```

I also tried running a filter on it, but that didn't seem to work either:

```
$user = Users::find(1);
$books = $user->books();
$book = $books->filter(function($book) {
    if ($book->title == 'The Great Gatsby') {
        return true;
    }
});
```

Returned with the following error:

```
Call to undefined method Jenssegers\Mongodb\Query\Builder::filter()

/vagrant/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php line 1951
```

I probably have the query constructed incorrectly? What is the correct method?

Thanks!

**Comment by krishnae** [comment]
I installed jenssegers for mongodb in Laravel and i just started to using mongoDB with Laravel.
I followed the steps to install through https://github.com/jenssegers/laravel-mongodb this link

this is my eloquent model
<?php
namespace App;
use Jenssegers\Mongodb\Model as Eloquent;
use Illuminate\Database\Eloquent\Model;
class Events extends Eloquent
{
    protected $connection='mongodb';
    protected $colletion='eventType';
}

and i am trying to get the data from my collection in controller
$customers = mongodbtest::all();
and tried $user = \DB::connection('mongodb')->collection('eventType')->get(); like this also
but i am getting empty json object with both approaches
can you please anyone help me out on this
