### ISSUE TITLE
Issue with Queues

### ISSUE THREAD

**Issue by DivByZeroIT** [jenssegers/laravel-mongodb#1991]
Hey team!

First of all thanks for the amazing work supporting this library, really appreciated!

I'm experiencing a strange behavior when retrieving data from mongoDB inside of queues. 
I'm not using Mongo as the queue driver, that's handled by redis.

When a process gets executed in the queue and I have something like:
$structure= \App\ContactStructure::where('_id',$id)->first();

it always returns false. There's no error thrown. 

Same line of code from an http controller works.
Same line on code in Cli through tinker works as well and return data. (So Mongo works in Php cli)

Any kind of mongodb data retrieval executed within a Job always return false. Mysql works.

Could this be a bug? Any idea how to debug it? 

Thanks
Massimo

**Comment by khakanali** [comment]
@DivByZeroIT 
That's the data type issue. Mongodb stored _id as a objectid. Please change data type of $id string to object id

**Comment by DivByZeroIT** [comment]
Thanks for the heads up @khakanali 

I'll do a couple of tests but I don't think that's the problem because same line of code works when invoked from http\Controller plus I have the same issue with other queries not using _id.

They are however querying int data ... I'll try casting to int and let you know!

Thanks
Max

**Comment by DivByZeroIT** [comment]
Thanks @khakanali ... you were right, that was the problem, I'm getting data from different sources and in the queue process I had the wrong casting!
