### ISSUE TITLE
Why it's not working with Laravel 7.1.3?

### ISSUE THREAD

**Issue by LinkedForest** [jenssegers/laravel-mongodb#1999]
I have install Laravel 7.1.3 and when i use "composer require jenssegers/mongodb"
I see a lot off issues : 
composer : Using version ^3.6 for jenssegers/mongodb
At line:1 char:1
+ composer require jenssegers/mongodb
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Using version ^...ssegers/mongodb:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
./composer.json has been updated

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install jenssegers/mongodb v3.6.3
    - Conclusion: don't install jenssegers/mongodb v3.6.2
    - Conclusion: don't install jenssegers/mongodb v3.6.1
    - Conclusion: remove laravel/framework v7.1.3
    - Installation request for jenssegers/mongodb ^3.6 -> satisfiable by jenssegers/mongodb[v3.6.0, v3.6.1, v3.6.2, v3.6.3].
    - Conclusion: don't install laravel/framework v7.1.3
    - jenssegers/mongodb v3.6.0 requires illuminate/events ^5.8|^6.0 -> satisfiable by illuminate/events[5.8.x-dev, 6.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, 
v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, 
v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/events 5.8.x-dev|don't install laravel/framework v7.1.3
    - don't install illuminate/events 6.x-dev|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.11|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.12|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.14|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.15|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.17|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.18|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.19|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.2|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.20|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.22|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.24|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.27|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.28|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.29|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.3|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.30|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.31|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.32|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.33|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.34|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.35|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.36|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.4|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.8|don't install laravel/framework v7.1.3
    - don't install illuminate/events v5.8.9|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.0.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.0.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.0.2|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.0.3|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.0.4|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.1.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.10.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.11.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.12.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.13.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.13.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.14.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.15.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.15.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.16.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.17.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.17.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.18.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.18.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.2.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.3.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.4.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.5.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.5.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.5.2|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.6.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.6.1|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.6.2|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.7.0|don't install laravel/framework v7.1.3
    - don't install illuminate/events v6.8.0|don't install laravel/framework v7.1.3
    - Installation request for laravel/framework (locked at v7.1.3, required as ^7.0) -> satisfiable by laravel/framework[v7.1.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by khakanali** [comment]
@LinkedForest because new release for 7 not yet published. They are doing some major changes for release 4.please used develop branch. They already updated that one for 7.

**Comment by khakanali** [comment]
@LinkedForest Please used this one

> composer require jenssegers/mongodb:dev-develop 

>

**Comment by rlxsensors** [comment]
I would like to join the slack channel. can you provide me the link?

**Comment by Smolevich** [comment]
@rlxsensors https://github.com/jenssegers/laravel-mongodb/issues/1791#issuecomment-526439915

**Comment by shailesh5152** [comment]
> @LinkedForest Please used this one

 
**This command is also not working.**

**Comment by kalkin** [comment]
> composer require jenssegers/mongodb:dev-develop

Works for me

**Comment by amarendraksahoo** [comment]
works for me

**Comment by virgiltu** [comment]
awesome work, I wish laravel used this module out of the box rather than mysql. Atlas is amazing.

**Comment by elfeffe** [comment]
> composer require jenssegers/mongodb:dev-develop works
> 
> awesome work, I wish laravel used this module out of the box rather than mysql. Atlas is amazing.

I also can't understand why Laravel, as they use always the latest software, doesn't officially support MongoDB.
They, al least, should sponsor this project.

**Comment by BehroozBvk** [comment]
> @LinkedForest Please used this one
> 
> > composer require jenssegers/mongodb:dev-develop
> 
> >

I use this command but it doesn't work. The Laravel version is 7.13.
output :
```
$ composer require jenssegers/mongodb:dev-develop
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mongodb/mongodb v1.7.x-dev requires ext-mongodb ^1.8 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
    - mongodb/mongodb v1.6.x-dev requires ext-mongodb ^1.7 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
    - mongodb/mongodb 1.8.x-dev requires ext-mongodb ^1.8 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
    - mongodb/mongodb 1.7.0-beta1 requires ext-mongodb ^1.8 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
    - mongodb/mongodb 1.6.0 requires ext-mongodb ^1.7 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
    - jenssegers/mongodb dev-develop requires mongodb/mongodb ^1.6 -> satisfiable by mongodb/mongodb[1.6.0, 1.7.0-beta1, 1.8.x-dev, v1.6.x-dev, v1.7.x-dev].
    - Installation request for jenssegers/mongodb dev-develop -> satisfiable by jenssegers/mongodb[dev-develop].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-bz2.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-curl.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-mongodb.ini
    - /etc/php/7.4/cli/conf.d/20-mysqli.ini
    - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by thitami** [comment]
As suggested `dev-develop` branch resolves this issue in the meantime.

**Comment by kennyrafael** [comment]
> > @LinkedForest Please used this one
> > > composer require jenssegers/mongodb:dev-develop
> > 
> > 
> > >
> 
> I use this command but it doesn't work. The Laravel version is 7.13.
> output :
> 
> ```
> $ composer require jenssegers/mongodb:dev-develop
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - mongodb/mongodb v1.7.x-dev requires ext-mongodb ^1.8 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
>     - mongodb/mongodb v1.6.x-dev requires ext-mongodb ^1.7 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
>     - mongodb/mongodb 1.8.x-dev requires ext-mongodb ^1.8 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
>     - mongodb/mongodb 1.7.0-beta1 requires ext-mongodb ^1.8 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
>     - mongodb/mongodb 1.6.0 requires ext-mongodb ^1.7 -> the requested PHP extension mongodb has the wrong version (1.6.1) installed.
>     - jenssegers/mongodb dev-develop requires mongodb/mongodb ^1.6 -> satisfiable by mongodb/mongodb[1.6.0, 1.7.0-beta1, 1.8.x-dev, v1.6.x-dev, v1.7.x-dev].
>     - Installation request for jenssegers/mongodb dev-develop -> satisfiable by jenssegers/mongodb[dev-develop].
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - /etc/php/7.4/cli/php.ini
>     - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
>     - /etc/php/7.4/cli/conf.d/10-opcache.ini
>     - /etc/php/7.4/cli/conf.d/10-pdo.ini
>     - /etc/php/7.4/cli/conf.d/15-xml.ini
>     - /etc/php/7.4/cli/conf.d/20-bz2.ini
>     - /etc/php/7.4/cli/conf.d/20-calendar.ini
>     - /etc/php/7.4/cli/conf.d/20-ctype.ini
>     - /etc/php/7.4/cli/conf.d/20-curl.ini
>     - /etc/php/7.4/cli/conf.d/20-dom.ini
>     - /etc/php/7.4/cli/conf.d/20-exif.ini
>     - /etc/php/7.4/cli/conf.d/20-ffi.ini
>     - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
>     - /etc/php/7.4/cli/conf.d/20-ftp.ini
>     - /etc/php/7.4/cli/conf.d/20-gd.ini
>     - /etc/php/7.4/cli/conf.d/20-gettext.ini
>     - /etc/php/7.4/cli/conf.d/20-iconv.ini
>     - /etc/php/7.4/cli/conf.d/20-json.ini
>     - /etc/php/7.4/cli/conf.d/20-mbstring.ini
>     - /etc/php/7.4/cli/conf.d/20-mongodb.ini
>     - /etc/php/7.4/cli/conf.d/20-mysqli.ini
>     - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
>     - /etc/php/7.4/cli/conf.d/20-phar.ini
>     - /etc/php/7.4/cli/conf.d/20-posix.ini
>     - /etc/php/7.4/cli/conf.d/20-readline.ini
>     - /etc/php/7.4/cli/conf.d/20-shmop.ini
>     - /etc/php/7.4/cli/conf.d/20-simplexml.ini
>     - /etc/php/7.4/cli/conf.d/20-sockets.ini
>     - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
>     - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
>     - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
>     - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
>     - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
>     - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
>     - /etc/php/7.4/cli/conf.d/20-xsl.ini
>     - /etc/php/7.4/cli/conf.d/20-zip.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
> 
> Installation failed, reverting ./composer.json to its original content.
> ```

You have to enable the mongodb extension by downloading it's DLL and changing your php.ini file.

https://pecl.php.net/package/mongodb/1.7.4/windows

**Comment by jleonardolemos** [comment]
Any thought about Laravel 7 tag? version 7 is up for a long time, i dont want to install from dev-developer. I would try a PR but i think the backage already has the code working on developer branch.

**Comment by Smolevich** [comment]
@jleonardolemos you can use 4.0 alpha release

**Comment by edgargaza** [comment]
Is there an expected date for it to be compatible with PHP v7 in a formal release?

**Comment by divine** [comment]
> Is there an expected date for it to be compatible with PHP v7 in a formal release?

Sorry, no ETA.
