### ISSUE TITLE
Larvel 7.x support - Should I?

### ISSUE THREAD

**Issue by nahojj** [jenssegers/laravel-mongodb#2004]
If I understand everything right, you don't support newer versions of Laravel yet?
Should I re-think using MongoDB as my primary database and aim for Postgres instead?

I'm currently on Laravel 7.3 and was thinking about MongoDB but without laravel-mongodb support, I'm not sure anymore. Why isn't it any support for newer Larvel versions out yet and when can we see this coming?

**Comment by activemonkeys** [comment]
Please have a look at this link: https://github.com/jenssegers/laravel-mongodb/issues/1974

**Comment by Smolevich** [comment]
@nahojj, you can try ti use development branch for support laravel 7

**Comment by nahojj** [comment]
Thanks, Is the development branch really "safe" in that case so we can use it in production or is it like more just to have a quick fix for the Laravel 7 support locally until it's finished?

Have we any clue when this should be in place? I mean, is it close so we're talking about waiting 1-3 weeks or is it further away until we have dev to production?

**Comment by Smolevich** [comment]
This solution can has potencial bugs, please report about them
We have plans to start work on new release soon

**Comment by nahojj** [comment]
Thanks.
