### ISSUE TITLE
[Question] How to get embedded array object of document result?

### ISSUE THREAD

**Issue by mydevlocal** [jenssegers/laravel-mongodb#2005]
Hi,
Does this library support search operation like `db.getCollection('media_collection').find({tags: {$elemMatch: {value: "javascript"}} })`?

For example i have embedded array object of documents like:

```
"tags" : [ 
  {
    "key" : "code",
     "value" : "code"
  }, 
  {
    "key" : "javascript",
    "value" : "javascript"
  }, 
  {
    "key" : "lo",
    "value" : "lo"
  }
],
```

What operation should i use to get the result? maybe something like `$elementMatch`

**Comment by khakanali** [comment]
@mydevlocal yes. You can do someting like this
CollectionModel::where('tags.value', 'like', '% javascript%')->get(); 
Or you can use whereRaw method

**Comment by mydevlocal** [comment]
Oh great, it works. Thank you.
