### ISSUE TITLE
Exeption on empty of datetime value (created_at, updated_at...)

### ISSUE THREAD

**Issue by quangtam** [jenssegers/laravel-mongodb#2007]
- Laravel-mongodb Version: 3.6
- PHP Version: 7.3.11
- Database Driver & Version: 1.7

### Description:
I have table called is employees, this is sample fields:
- name
- birth_date (date time)
- created_at (date time)
.....
When I query from this table and one of date time fields value is empty I've got exeption: Data missing

### Steps to reproduce
1. Insert record with empty date time value (not set default)
2. Query from db this record
3. Throw exeption

### Expected behaviour
It will be return empty same with MySQL normal.

### My investigate
The issue will be fixed if I change Jenssegers\Mongodb\Eloquent\Model function asDateTime to like this:
```
protected function asDateTime($value)
    {
        // Convert UTCDateTime instances.
        if ($value instanceof UTCDateTime) {
            return Date::createFromTimestampMs($value->toDateTime()->format('Uv'));
        }
        try {
            return parent::asDateTime($value);
        } catch (\Exception $exception) {
            return parent::asDateTime(Carbon::now());
        }

    }
```
But I think this is not solution because I try to use empty by now() is not a correct solution.

**Comment by carlosmolano** [comment]
👉It would be nice if you implemented it in the latest version of the package!!

**Comment by divine** [comment]
Hello,

I wasn't able to reproduce this issue.

Do you use some kind of relations with MySQL?

Thanks.
