### ISSUE TITLE
Retrieve Document Based on data in Subdocument?

### ISSUE THREAD

**Issue by mikebronner** [jenssegers/laravel-mongodb#201]
I would like to retrieve a document based on criteria in a subdocument. Is this currently possible?

I found an example on StackOverflow: http://stackoverflow.com/questions/11823296/mongodb-find-subdocument-in-array-matching-parameters

For a more appropriate example, using the books analogy:
- Given I have many users
- Given each user embedsMany books
- I would like to find the user that owns the book titled 'The Great Gatsby'

**Comment by siltaz** [comment]
User::where('books', 'elemMatch', array('title' => 'The Great Gatsby'))->first();

This worked great but what if i want to check more than one field ?

like 'title' = 'The Great Gatsby' AND 'author' = 'Alex'

i tried doing like this:
User::where('books', 'elemMatch', array('title' => 'The Great Gatsby', 'author' => 'Alex'))->first();

But didn't work !

**Comment by mshamaseen** [comment]
> I have added the elemMatch operator:
> 
> ```
> User::where('books', 'elemMatch', array('title' => 'The Great Gatsby'))->get();
> ```
> 
> Embedded relations do indeed use an underscore prefix, so in this case you would have to query the _books field.

would be great if that got documented
