### ISSUE TITLE
One Hour late  from the current time

### ISSUE THREAD

**Issue by jgodstime** [jenssegers/laravel-mongodb#2010]
The created_at and updated_at field is always one hour late from the current time (system time), so i always do this  

  ```
  protected $guarded =['created_at','updated_at'];

   public function freshTimestamp()
    {
        return  Carbon::now('UTC')->addhour();
   }
```
in  my model

**Comment by Smolevich** [comment]
@jgodstime, we need more info
What do you mean ?

**Comment by divine** [comment]
Please, kindly check your php timezone configuration.
