### ISSUE TITLE
Like query not working on integer fields.

### ISSUE THREAD

**Issue by ultimateakash** [jenssegers/laravel-mongodb#2016]
- Laravel-mongodb Version: ^3.5
- PHP Version: 7.3
- Database Driver & Version: 3.4 (mongo)

### Description:
In my project i need to implement search functionality on different columns. on string column it works fine but it didn't work on integer fields.

### Steps to reproduce
Just for example
```
$code = 256;
        
$branch = Branch::where('code','like',"%".$code."%")->first();
        return response()->json([
            'branch' => $branch
        ]);
```

**Comment by Smolevich** [comment]
@ultimateakash What is the type for `code` in mongodb?

**Comment by divine** [comment]
Closing. PR with the fix has been merged and released.

Thanks!
