### ISSUE TITLE
Trying to establish database connection to input new subscribers in MongoDB but I get error Call to a member function prepare() on null

### ISSUE THREAD

**Issue by laingmedia** [jenssegers/laravel-mongodb#2034]
Trying to establish database connection to input new subscribers but I get error "Call to a member function prepare() on null". Users are successfully registering and log in in with MongoDB database but when I try to add them as a subscriber the error comes in. 

**The file that the error is pointing to is:** …/vendor/laravel/framework/src/Illuminate/Database/Connection.php457

    public function statement($query, $bindings = [])
        {
            return $this->run($query, $bindings, function ($query, $bindings) {
                if ($this->pretending()) {
                    return true;
                }

                $statement = $this->getPdo()->prepare($query);

                $this->bindValues($statement, $this->prepareBindings($bindings));

                $this->recordsHaveBeenModified();

                return $statement->execute();
            });
        }

Considering everything else works, is this a bug?

**Comment by Smolevich** [comment]
Please describe full problem
It seems like error in configuration

**Comment by divine** [comment]
There is no way that I could reproduce and no reply for 5 months.

Closing.
