### ISSUE TITLE
[Question] How to import from an exported json?

### ISSUE THREAD

**Issue by realtebo** [jenssegers/laravel-mongodb#2036]
I exported some documents from a collection using mongodump. 

I need a way to import into my collection after a db reset.

Is there a way to load the json and directly add all its content to collection?

**Comment by Smolevich** [comment]
You can use mongorestore. See [docs](https://docs.mongodb.com/manual/reference/program/mongorestore/)

**Comment by realtebo** [comment]
OMG. I should explicitly say that I want use your library... I am asking here for a reason !

**Comment by Smolevich** [comment]
@realtebo i didn't see reason in your question
If you can load blob file(maybe json, maybe tar) directly using default work of this library, you can parse blob file and using work with Eloquent model or collection
This library dont't have mechanism to load blob files into collections

**Comment by realtebo** [comment]
Ok, good to know, I was only looking for this info. It's not possible. ok.
