### ISSUE TITLE
An error occurs when installing this package with laravel 7.12.0

### ISSUE THREAD

**Issue by evonikgu** [jenssegers/laravel-mongodb#2037]
I have created a fresh application on laravel 7.12.0 and I'm working with mongodb, but when I try to install this composer package, it shows me comething like that
`  Problem 1
    - Conclusion: don't install jenssegers/mongodb v3.6.4
    - Conclusion: don't install jenssegers/mongodb v3.6.3
    - Conclusion: don't install jenssegers/mongodb v3.6.2
    - Conclusion: don't install jenssegers/mongodb v3.6.1
    - Conclusion: remove laravel/framework v7.12.0
    - Installation request for jenssegers/mongodb ^3.6 -> satisfiable by jenssegers/mongodb[v3.6.0, v3.6.1, v3.6.2, v3.6.3, v3.6.4].
    - Conclusion: don't install laravel/framework v7.12.0
    - jenssegers/mongodb v3.6.0 requires illuminate/events ^5.8|^6.0 -> satisfiable by illuminate/events[5.8.x-dev, 6.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - don't install illuminate/events 5.8.x-dev|don't install laravel/framework v7.12.0
    - don't install illuminate/events 6.x-dev|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.11|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.12|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.14|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.15|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.17|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.18|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.19|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.2|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.20|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.22|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.24|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.27|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.28|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.29|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.3|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.30|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.31|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.32|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.33|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.34|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.35|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.36|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.4|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.8|don't install laravel/framework v7.12.0
    - don't install illuminate/events v5.8.9|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.0.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.0.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.0.2|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.0.3|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.0.4|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.1.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.10.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.11.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.12.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.13.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.13.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.14.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.15.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.15.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.16.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.17.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.17.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.10|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.11|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.12|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.13|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.14|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.15|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.2|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.3|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.4|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.5|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.6|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.7|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.8|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.18.9|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.2.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.3.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.4.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.5.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.5.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.5.2|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.6.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.6.1|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.6.2|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.7.0|don't install laravel/framework v7.12.0
    - don't install illuminate/events v6.8.0|don't install laravel/framework v7.12.0
    - Installation request for laravel/framework (locked at v7.12.0, required as ^7.0) -> satisfiable by laravel/framework[v7.12.0].
`
Of course, the installation fails, but everything seems to be good with laravel v7 support, as you mentioned in the issue about 4.0 release.

**Comment by MarisV** [comment]
Same with Laravel v7.11.0

**Comment by Smolevich** [comment]
See https://github.com/jenssegers/laravel-mongodb/issues/1974#issuecomment-632184816

**Comment by salindalakmal** [comment]
Replace the https://github.com/laravel/laravel/blob/master/app/Exceptions/Handler.php file

Next, please update your session configuration file's secure option to have a fallback value of null:
(https://laravel.com/docs/7.x/upgrade)

'secure' => env('SESSION_SECURE_COOKIE', null),
