### ISSUE TITLE
getOriginal() on self::deleting , the result is incorrect

### ISSUE THREAD

**Issue by mean-cj** [jenssegers/laravel-mongodb#2041]
- Laravel 7.5
- Laravel-mongodb Version: dev (4.0.0-alpha.1)
- PHP Version: 7.4.4
- Database Driver & Version: 4.2

### Description:
Result of getOriginal() on self::deleting is incorrect, data have been mutator

I want delete attachment file before delete document.

### Steps to reproduce
**1. Create Model Test** 
```
class Test extends Eloquent
{
  public static function boot()
   {
      parent::boot();

      self::deleting(function ($model) {
        dd($model->getOriginal('attachment'));
      });
   }

   public function getAttachmentAttribute($attachment)
   {
    return "http://domain.com/{$attachment}";
   }
}
```

**2. Create Test Document**
```
Test::create([
   'title' => 'Hello Test', 
   ''attachment' => 'file_abc.png'
]);
```

**3. Select First and Delete**
```
$test = Test::first();
$test->delete();
```

Result dd() is incorrect
> http://domain.com/file_abc.png

correct result is
> file_abc.png

when i use $model->attributes['attachment'] the result is correct.

**Comment by mean-cj** [comment]
I will test **$model->getOriginal()** not work any more.

**Comment by Smolevich** [comment]
https://github.com/laravel/framework/blob/v7.5.0/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php#L1170-L1176 this behavior appeared in laravel framework and looks like expected behavior

**Comment by mean-cj** [comment]
- laravel 7 + laravel-mongodb dev result of getOriginal() not working

Laravel 7 and Symfony 5 respectively use 
**$model->getRawOriginal('field_name')**
or
$model->getAttributes()['field_name']

**Comment by divine** [comment]
I can confirm that is expected behavior that was changed in L7 release.

You need to use `getRawOriginal`

Thanks!
