### ISSUE TITLE
deleting not working with relation

### ISSUE THREAD

**Issue by mean-cj** [jenssegers/laravel-mongodb#2042]
Laravel 7.5
Laravel-mongodb Version: dev (4.0.0-alpha.1)
PHP Version: 7.4.4
Database Driver & Version: 4.2

### Description:
When i delete all comment from thread relation,
deleting method on boot is not working

### Steps to reproduce
**1. Create Thread & Comment Model**
```
class Thread extends Eloquent
{

   public static function boot()
   {
      parent::boot();

      static::deleting(function ($model) {
         $model->Comments()->delete();
      });
   }

   public function Comments()
   {
      return $this->hasMany(Comment::class);
   }
}

class Comment extends Eloquent
{
   public static function boot()
   {
      parent::boot();

      self::deleting(function ($model) {
        dd("Hello Would");
      });
   }
}

```

**2. Create Document & Select First**
```
$thread = Thread::create([ 'message'=> "Hello" ]);
$thread->Comments()->create([ 'message' => "Comment 1" ]);
$thread->Comments()->create([ 'message' => "Comment 2" ]);

$thread = Thread::first();
$thread->Comments()->delete();
```

### Expected behaviour
I need delete all comments, on relation deleting() method is not working 
`$thread->Comments()->delete();`

however deleting() work only on each()
```
$thread->Comments()->each(function ($comment) {
    $comment->delete();
});
```

**Comment by leikxile** [comment]
Same on my side, `Activity::where()->delete()` deletes only 1. Need to use `->each` to delete bulk. This works but I'm worried on how this executes on the query side.

**Comment by divine** [comment]
Hello,

Could you please try v3.7?

Thanks!

**Comment by divine** [comment]
Closing, let us know if you have any issues with 3.7
