### ISSUE TITLE
Can we use db.collection.getIndexes()?

### ISSUE THREAD

**Issue by elfeffe** [jenssegers/laravel-mongodb#2044]
That can be really useful to move indexes to live, you can set them using MongoDB GUI and then move to live with a migration.
I'm trying with Model::raw()->getIndexes() but doesn't work.

**Comment by kurokeita** [comment]
Sorry for asking after a long time, but I'm currently running into this issue here trying to get all indexes from a collection. So have you figured it out, @elfeffe ?
