### ISSUE TITLE
laravel MongoDB /Jessnegers aggregate get selected columns[Question] 

### ISSUE THREAD

**Issue by nrjgit** [jenssegers/laravel-mongodb#2046]
My Code
```

	$cnt = custt::raw(function($collection) {
			return $collection->aggregate(
			[['$match' => ['custstate' => 'MI']]],
			 [

			'$group'    => [
				'_id'   => '$custstate',
				'count' => [
					'$sum'  => 1
				]
				]
			],
			[[
			'$lookup' => [
				'as'=>'info',
				'from'=>'contacts',
				'foreignField'=>'custid',
				'localField'=>'custid'												
						]
					]]);			
			});
			

```
I only want to retrieve custstate column only , but getting all column from tables .How Can I get only few columns in output . I tried Groupby , but I thnk it is now what meant to do this ..Please suggest

**Comment by elfeffe** [comment]
Check this https://laracasts.com/discuss/channels/eloquent/select-specific-columns-using-eloquent-orm

**Comment by nrjgit** [comment]
I want to use lookup/ join + match/ where / projection/ selected columns
combine

**Comment by Smolevich** [comment]
You can use pipe `$project` for selecting fields
