### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by tsmliyun** [jenssegers/laravel-mongodb#2047]
laravel7的版本是什么时候可以支持？

**Comment by Smolevich** [comment]
@tsmliyun please, write on English
If you mean support Laravel 7, you can see [here](https://github.com/jenssegers/laravel-mongodb/issues/1974)

**Comment by elfeffe** [comment]
> laravel7的版本是什么时候可以支持？

`composer require jenssegers/mongodb:dev-develop`


It works on L7
Please write in English, or at least in pseudo English as I do.

**Comment by Smolevich** [comment]
@elfeffe 
For testing work with Laravel 7 you can install alpha release https://github.com/jenssegers/laravel-mongodb/releases/tag/4.0.0-alpha.1

**Comment by elfeffe** [comment]
Yes, it should be composer require "jenssegers/mongodb":"^4.0" then
