### ISSUE TITLE
[Question] Do Mongo Write Options get passed and work?

### ISSUE THREAD

**Issue by juanmrad** [jenssegers/laravel-mongodb#2050]
I was advice by MongoDB to add the following settings on my configurations:

```
Retryable writes and Majority writeConcern
```

I was wondering if anyone has tested this already and how to add them. Any performance or errors experienced?

I was thinking it would be like this, but would like some confirmation.

```
            'options'  => [
                'retryWrites' => 'true',
                'w' => 'majority'
            ],
```

**Comment by divine** [comment]
Hi,

Yes, you can add that configuration and it will work https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Connection.php#L39

Regarding performance or errors, it completely depends on your mongdb setup, library only passes configuration to mongodb and everything rest is being handled by mongodb itself.

Thanks.
