### ISSUE TITLE
Add replacement for removed relationships

### ISSUE THREAD

**Issue by Christophvh** [jenssegers/laravel-mongodb#2053]
Currently, there is a link to a comment about why the embedsMany() relationship got removed but there should be info about how to fix broken code that uses this.

I think this is all that is necessary?

```
//Create example
$item = Item::create([
"name"=>"AAAAA",
"addon" => ['name' => 'Test Addon', 'price' => 100]
]);
$item->save();
```

```
//Update example
$updated_addon = ['name' => 'Updated Test Addon', 'price' => 499]
$item->addon = $updated_addon;
$item->save();
```

Also, I don't agree at all with the removal. embedding relationships is a core function of MongoDB. The main function of this package should be to provide helpers for core MongoDB functionality not try to replicate MySQL and just dump the data into MongoDB. There is nothing wrong with having dedicated methods only for Mongo because it is vastly different than SQL-like databases. 

I also really want to help implementing this. We use this package for a pretty big enterprise product so we would like to contribute, but if any pull requests regarding custom methods like embedding & aggregation just get closed it is not worth our time.

**Comment by Xeroxi91** [comment]
Hi @Christophvh, 
my company also had the same needs so we have developed a package that provides a better support for MongoDB relationships embed-one and embed-many in Laravel Projects. 
You can find it here https://github.com/offline-agency/laravel-mongo-auto-sync
I hope it will be useful. Let me know 😉

**Comment by Christophvh** [comment]
@Xeroxi91 Thanks for the suggestion will take a look

**Comment by divine** [comment]
> embedding relationships is a core function of MongoDB

We have not removed or disabled anyone from using embedded relationships, we've just removed Eloquent integration.

The problem was Eloquent _**magic**_ , it's logic doesn't work well with **embedded documents** and all integration was just a _hack_ _over_ and _over_ again.

> There is nothing wrong with having dedicated methods only for Mongo because it is vastly different than SQL-like databases.

Eloquent _**magic**_ was specially designed only for SQL-like databases.

> We use this package for a pretty big enterprise product so we would like to contribute, but if any pull requests regarding custom methods like embedding & aggregation just get closed it is not worth our time.

We do really appreciate any help with this library. Nothing will be closed, **however** it's not easy as it looks like.

Can you paginate correctly embedded document or maybe just a few bugs https://github.com/jenssegers/laravel-mongodb/issues?q=is%3Aissue+is%3Aclosed+label%3Awontfix

Thanks!

**Comment by Christophvh** [comment]
> > embedding relationships is a core function of MongoDB
> 
> We have not removed or disabled anyone from using embedded relationships, we've just removed Eloquent integration.
> 
> The problem was Eloquent _**magic**_ , it's logic doesn't work well with **embedded documents** and all integration was just a _hack_ _over_ and _over_ again.
> 

This issue is also about how to transition after the update. The current changelog is link to a comment at explains why, but not how to solve it. The underlying library has this: https://docs.mongodb.com/php-library/current/tutorial/crud/#insert-many-documents

So I think we should document it, I can help with that.

> > There is nothing wrong with having dedicated methods only for Mongo because it is vastly different than SQL-like databases.
> 
> Eloquent _**magic**_ was specially designed only for SQL-like databases.
> 

I think you are missing my point. What I mean by dedicated methods is not dedicated methods that have to fit in eloquent, because like you said that isn't possible. What I mean is methods like: paginateMongo(); or something. Or having methods that just return a Laravel Collection() or a Query builder object no need to have everything working in Eloquent because eloquent is not build for that. If you remove all custom methods form this package, this package has no use except for the Service-provider, we can just use the mongo-php-driver directly.

This is an example where this package does do this: `Car::where('name', 'Toyota')->decrement('weight', 50);` Decrement is not related to eloquent it is just a helper specific for Mongo which is great.

**Comment by divine** [comment]
> This issue is also about how to transition after the update. The current changelog is a link to a comment that explains why, but not how to solve it. The underlying library has this: https://docs.mongodb.com/php-library/current/tutorial/crud/#insert-many-documents

Well, you're right, upgrade path wasn't written at all (my bad, sorry). We're still stuck at custom casts which is delaying new release.

> So I think we should document how to use that underlying method if you still want to use embedded documents, I can help with that.

Would be great. I'm not a native speaker so writing technical documentation is a bit hard.

> I think you are missing my point. What I mean by dedicated methods is not dedicated methods that have to fit in eloquent

I got your point but I've forgot to add that _**embedded documents**_ is a _**eloquent relations**_ not helper function.

However, yes, helper functions might be better. I've just tried to get rid of most complained feature and make this library bug free - probably failed and still failing.

> I also want to be clear that I want to help and I understand how hard it is to maintain an open-source package. So thanks for all the work. But it is a very big annoyance for people who use this package in production and when they update 50% of their codebase is broken because that functionality got removed. if you remove existing functionality we should have an 'upgrade path' or a clear explanation to show existing users how to solve the issues they are having.

As I've already said, we do really appreciate any help to make this library better for all of us.

> We also ran in the pagination issue and this is what we have in our code, which works for our hybrid Mysql/MongoDB setup. So maybe we can contribute something, but like i said, if the embedded relationships are gone for good, there is no point to make a pull request to fix those pagination issues.

It was just example, there are tons of unknown bugs with embedded relations... fix over fix - that was the reason why it was hard to maintain correctly eloquent embedded relations.
