### ISSUE TITLE
Convert milliseconds to date and time

### ISSUE THREAD

**Issue by alikhani97** [jenssegers/laravel-mongodb#2058]
i have a problem with dates ,
I have a date saved in database like this : 2020-07-04T10:10:10.593+00:00
When i read this from database in controller it became to milliseconds,  
how to convert this to date and time format?

**Comment by alikhani97** [comment]
![image](https://user-images.githubusercontent.com/23420849/86508981-afabce00-bdf9-11ea-9c16-582e2bdf4841.png)
![image](https://user-images.githubusercontent.com/23420849/86508989-bd615380-bdf9-11ea-9367-840aa30a9844.png)

**Comment by alikhani97** [comment]
first picture is a datetime saved in database and the second one shows that datetime as a milliseconds

**Comment by Smolevich** [comment]
@alikhani97, you can get date and use function parse 
See [example](https://github.com/jenssegers/laravel-mongodb/blob/736415ef6e02fad4a1b67a98da2c23fbaddd8679/src/Jenssegers/Mongodb/Eloquent/Model.php#L102)

**Comment by alikhani97** [comment]
Oh! Thank you, I couldn't find this on the Internet and you saved me with this one :)
