### ISSUE TITLE
Model saving does not work

### ISSUE THREAD

**Issue by wistis** [jenssegers/laravel-mongodb#2066]
Laravel-mongodb Version: 3.6
PHP Version: 7.2
Database Driver & Version:db 3.6 .
 
`  $r=MetricaCurrentTest::first() ;
       $r->name=123;
$r->save();`
Model saving does not work, data does not change. Can only be updated via \DB::update

**Comment by Smolevich** [comment]
@wistis show model code, please

**Comment by wistis** [comment]
Sorry, I found the problem, the error was that I created collection documents and specified _id there without converting it to ObjectId
