### ISSUE TITLE
the connection about MongoDB Atlas

### ISSUE THREAD

**Issue by wohcnosae** [jenssegers/laravel-mongodb#2067]
Hi , i have issue about the connection between Laravel to MongoDB Atlas 

 I tried 
`'mongodb' => [
    'driver' => 'mongodb',
    'dsn' => env('DB_DSN'),
    'database' => env('DB_DATABASE', 'homestead'),
],`

is not working

then I go searching for issue , and someone said ssl issue so I tried 

`  'mongodb' => [
            'driver' => 'mongodb',
            'host' =>  [
              env('MDB_HOST_0', env('DB_HOST')),
              env('MDB_HOST_1', env('DB_HOST')),
              env('MDB_HOST_2', env('DB_HOST')),
            ],
            'port' => env('MDB_PORT', env('DB_PORT')),
            'database' => env('MDB_DATABASE'),
            'username' => env('MDB_USERNAME'),
            'password' => env('MDB_PASSWORD'),
            'options' => [
                'ssl' => [
                  'allow_self_signed' => true,
                  'verify_peer' => false,
                  'verify_peer_name' => false,
                  'verify_expiry' => false,
                ],
                'retryWrites' => true ,
                'w' => 'majority' ,
                'replicaSet'=>'Cluster0-shard-0',
            ],
        ],
`

but seem not working also 

but from ROBO3T with self signed ssl with the link given from MongoDB Atlas is working well 

this is the issue what I get 

`MongoDB\Driver\Exception\ConnectionTimeoutException
No suitable servers found ('serverSelectionTryOnce' set): [connection closed calling ismaster on 'cluster0-shard-00-00-ehmfy.mongodb.net:27017'] [connection closed calling ismaster on 'cluster0-shard-00-01-ehmfy.mongodb.net:27017'] [connection closed calling ismaster on  'cluster0-shard-00-02-ehmfy.mongodb.net:27017']`

my server is handle by cPanel hosting 

     `   "php": "^7.2",
        "fideloper/proxy": "^4.0",
        "google/cloud-firestore": "^1.14",
        "jenssegers/mongodb": "^3.6",
        "kreait/laravel-firebase": "^2.2",
        "laravel/framework": "^6.2",`

**Comment by Smolevich** [comment]
@wohcnosae looks like that you use incorrect db dsn

**Comment by wohcnosae** [comment]
@Smolevich the link from .env is this one 
mongodb+srv://easonchow:<password>@cluster0-ehmfy.mongodb.net/<dbname>?retryWrites=true&w=majority

**Comment by StevePorter92** [comment]
`mongodb+srv://{username}:{password}@{atlasUrl}/{database}?replicaSet={replicaset}&authSource=admin&authMechanism=SCRAM-SHA-1&ssl=true&retryWrites=true&w=majority`

The above works for me as the DSN works for me. Also added `&tlsCAFile=/opt/lib/curl/cert.pem` to get it working with vapor

**Comment by wohcnosae** [comment]
@StevePorter92 same error I got , whatever dsn I tried , get the same error , is it cPanel hosting server unable to connect to MongoDB ?

**Comment by wohcnosae** [comment]
Hi @StevePorter92  @Smolevich  i founded the issue which is have to install the mongo client shell to work
