### ISSUE TITLE
[4.x] Truncate drops indexes? 

### ISSUE THREAD

**Issue by elfeffe** [jenssegers/laravel-mongodb#2071]
I'm using L7 with the version 4 of the package.
truncate() drop my indexes, is that normal? I don't think it used to be before.

**Comment by Smolevich** [comment]
@elfeffe show code for understanding behaviour

**Comment by elfeffe** [comment]
Products::truncate();

**Comment by divine** [comment]
Yes, currently we haven't merged this PR for version 4 https://github.com/jenssegers/laravel-mongodb/pull/1993

However, it will be soon, hopefully.

**Comment by elfeffe** [comment]
Oh, great, thank you

**Comment by divine** [comment]
This should be fixed, I've merged master to develop.

Thanks!
