### ISSUE TITLE
how to enableQueryLog ?

### ISSUE THREAD

**Issue by znau** [jenssegers/laravel-mongodb#2072]
i use this code 
`
DB::connection()->enableQueryLog();
`
but,  it doesn't work

**Comment by mean-cj** [comment]
try

```
use Illuminate\Support\Facades\DB;

DB::enableQueryLog();

Model::first();

dd(DB::getQueryLog());		
```

**Comment by znau** [comment]
@mean-cj  Thanks for your help. 

I have multiple database configurations here, I have to use **DB:: connection()**.  I looked at the **DB:: connection()** method, When the **connection** method has no parameters, it means to use the default database connection config. So I need a loop to turn it on;

I use this code  in   **AppServiceProvider.php**:

 ```
if (! empty($mongoConnectList)) {
     foreach ($mongoConnectList as $mongoConnect) {
            DB::connection($mongoConnect)->enableQueryLog();
     }
 }
```
