### ISSUE TITLE
Authorization failure when connect to AWS DocumentDB

### ISSUE THREAD

**Issue by yunier0525** [jenssegers/laravel-mongodb#2074]
Hi, 

I'm trying to connect to AWS DocumentDB, but after many different configurations tested the closest I've ever been to achieving it is with an "Authorization failure" error.

My config is:
```
'mongodb' => [
    'driver' => 'mongodb',
    'dsn' => env('MONGO_DB_DSN'),
    'database' => env('MONGO_DB_DATABASE', 'develop'),
    'options'  => [
        'database' => env('MONGO_DB_DATABASE', 'develop'),
        'ssl' => true,
        'tlsCAFile' => '/var/www/.ssh/mongodb-certificate-develop.pem',
        'tlsAllowInvalidCertificates' => true,
    ],
]
```
Laravel 5.8
jenssegers/mongodb v3.5.3

Can someone help me, I have spent a day and a half on this.
Regards.

**Comment by divine** [comment]
This has been discussed multiple times, also take a look at pull requests comments. Documentdb based on old mongodb source, however this library never advertised its compatibility with it, neither we could provide a fix.
