### ISSUE TITLE
[Question] Laravel 8 : Can this package be used with Laravel 8?

### ISSUE THREAD

**Issue by thomasdominic** [jenssegers/laravel-mongodb#2081]
This package can be used with Laravel 6 in standard
This packages can be used with Laravel 7 with an alpha version (Thanks for that !)

Can this package be used with Laravel 8 ? and How ?

Thanks.

**Comment by divine** [comment]
Hello,

Let's wait release date, after that we could _probably_ comment about when it will be supported.

Sorry for late reply.

**Comment by thomasdominic** [comment]
And you have an idea for the release date ?

**Comment by divine** [comment]
> And you have an idea for the release date ?

I don't know, maybe one or two weeks after laravel 8 release but no guarantees.
