### ISSUE TITLE
[3.6.5] Model::find with integer keys no longer works after laravel/framework update (v6.18.36 => v6.18.37)

### ISSUE THREAD

**Issue by EligiusSantori** [jenssegers/laravel-mongodb#2087]
- jenssegers/mongodb version: 3.6.4/3.6.5
- mongodb/mongodb version: 1.4.3/1.6.1/1.7.0
- laravel/framework version: 6.18.37 (before update 6.18.36)
- PHP Version: 7.2.24
- Database Driver & Version: 1.5.3/1.7.5

### Description:
After `composer update` the `find()` method always returns null for collections with integrer `_id`.

Also there is difference in `\DB::listen` behaviour. In old framework version `\DB::listen(function($q) { dump($q->sql); });` shows nothing, in new version it shows `"profile.find({"_id":"7016278824"},{"limit":1,"typeMap":{"root":"array","document":"array"}})"`.

### Steps to reproduce
1. MyModel::find($my_id)

### Expected behaviour
Should return MyModel instance with data.

### Actual behaviour
Returns `null`.

**Comment by divine** [comment]
Hello,

This PR https://github.com/laravel/framework/pull/34031 broke that.

Possible solution is to define model key type to int.
`$keyType = 'int'`

Well, this is another breaking change in a minor release.

What do you thing @Smolevich ?

**Comment by Smolevich** [comment]
@EligiusSantori why do you use type string for `_id`?

**Comment by divine** [comment]
> @EligiusSantori why do you use type string for `_id`?

@Smolevich it's being set by default to string here https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Eloquent/Model.php#L38

**Comment by Smolevich** [comment]
I mean another thing, `_id` should value of ObjectId
Test case https://github.com/jenssegers/laravel-mongodb/blob/828e7513f0eeaaa73776724e2f80ee8b66f3bebb/tests/ModelTest.php#L54

**Comment by divine** [comment]
Quite interesting transaction pr also failing https://github.com/jenssegers/laravel-mongodb/pull/1904/checks?check_run_id=1091695716#step:10:22 nothing was changed at all and everything worked like a charm.

**Comment by EligiusSantori** [comment]
Well, `protected $keyType = 'int';` works. I was sure I tried it.

**Comment by divine** [comment]
Glad it was resolved. Closing.
