### ISSUE TITLE
composer package jenssegers/mongodb is broken

### ISSUE THREAD

**Issue by ykmargate** [jenssegers/laravel-mongodb#2099]
- Laravel-mongodb Version: "jenssegers/mongodb": "dev-develop",
- PHP Version: 7.2, 7.4
- Database Driver & Version: 1.8

### Steps to reproduce
composer require "jenssegers/mongodb":"dev-develop"
### Expected behaviour
Proper installation
### Actual behaviour
<b>Installed Relations</b>
BelongsTo.php      
HasMany.php  
MorphMany.php
BelongsToMany.php
HasOne.php   
MorphTo.php
<b>Missing Relations</b> 
EmbedsMany.php
EmbedsOne.php
EmbedsOneorMany.php

**Comment by divine** [comment]
Well, if you have had a chance to read upgrade section you  could see that it was removed and dev develop is a version 4.

If you'd like to try l7 support then install master version.

Thanks!
