### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by abhishekgahlot** [jenssegers/laravel-mongodb#21]
Hi

I am using different port and username|password . I get error 
Failed to connect to: localhost:32759: Authentication failed
I am sure my username and password are correct .  It connects fine via simple php mongoClient class.
Don't know why this happening.

After i reviewed source , it seems ok it should be passing password fine but its not connecting in laravel 4.

**Comment by a-ghasemi** [comment]
I have same problem on Laravel MongoDB, I'm using Laravel 4.2, Mongo 3.2, PHP 5.6
I can migrate and seed with artisan, but in php code when calling 
`DB::table('users')->select();`
with catching errors, it shows:

**Error File:** /var/www/lastsecond/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php
**Error Line: **133
**Error Message:** Failed to connect to: localhost:27017: Permission denied
**Error Code:** 7

**Comment by a-ghasemi** [comment]
Thank you all, My problem answered here:
http://stackoverflow.com/questions/20954985/uncaught-exception-mongoconnectionexception

**Comment by rkang30** [comment]
I have an authentication failed issue with mongodb 3.2 and laravel 5.2 

I have tested it with just php and mongodb php library like below.

require 'vendor/autoload.php';
$uripotions = array();
$uripotions['username'] = 'myuser';
$uripotions['password'] = 'mypassword';
$client = new MongoDB\Client("mongodb://localhost:27017", $uripotions);
$collection = $client->client_db->accounts;

$result = $collection->find();
foreach($result as $item){
	echo $item['first_name'];
	echo '<br><br>';
}

And it worked.

However, it doesn't work on laravel 5.2 after following the steps that jenssegers/laravel-mongodb mentions. 

I have added the service provider class to config/app.php and added my mongodb config in config/database.php like below.

        'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('DB_HOST', 'localhost'),
            'port'     => env('DB_PORT', 27017),
            'database' => env('DB_DATABASE', 'client_db'),
            'username' => env('DB_USERNAME', 'myuser'),
            'password' => env('DB_PASSWORD', 'mypassword'),
            'options' => [
                'db' => 'admin'
            ]
        ],   

In my controller, I put a script like below:

class IntroController extends Controller
{
    public function index(Account $account)
    {
    	$user = $account->where('first_name', 'ryan')->first();
    	return $user;
    }
}

In the Account model:

namespace App;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;
class Account extends Eloquent 
{
    protected $connection = 'mongodb';
    protected $collection = 'accounts';
    protected $fillable = ['first_name', 'last_name', 'email'];
}

I get an error message like below:

AuthenticationException in Find.php line 179: Authentication failed.

It would be appreciated if you could help me with this issue.

Thanks,
Ryan

**Comment by bke-daniel** [comment]
Just in addition to @rkang30 
This is not mainly an issue but in my setup the "port" var doesn't seem to get through and is being replaced with the 3306 MySQL port. Therefore no connection at all, but changing this:
`'port'     => env('DB_PORT', 27017),`
to this
`'port'     => '27017',`
works like a charme.

Cheers

**Comment by infernobass7** [comment]
@bke-daniel Did you change your .env file?

**Comment by bke-daniel** [comment]
@infernobass7 Sadly I have to answer that with a short and straight: Yes. :/

**Comment by chinhvowili** [comment]
Please check auth user in database (admin database, current using database). Make sure 'options' => [
            'db' => 'admin'
        ] is authenticated user. Or use the same authenticated:
'mongodb' => [
   'driver' => 'mongodb',
   'host' => env('DB_HOST', 'localhost'),
   'port' => env('DB_PORT', 27017),
   'database' => env('DB_DATABASE'),
   'username' => env('DB_USERNAME'),
   'password' => env('DB_PASSWORD'),
   'options' => [
        'database' =>  env('DB_DATABASE') // sets the authentication database required by mongo 3
    ]
]

Hop it works.

**Comment by yazeed** [comment]
@chinhvowili's solution worked for me, Laravel 5 should take into consideration the default configuration of MongoDB.
