### ISSUE TITLE
[Feature Request] Laravel 8 support

### ISSUE THREAD

**Issue by rakeshlanjewar** [jenssegers/laravel-mongodb#2101]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.
Yes
### Describe the solution you'd like

As of now this package is not supported by laravel 8, so i would like to use it in laravel 8.

**Comment by huangdijia** [comment]
+1

**Comment by rakeshlanjewar** [comment]
I have added pull request. #2102

**Comment by huangdijia** [comment]
> I have added pull request. #2102

`^7.0|^8.0` ？

**Comment by divine** [comment]
What's up with tests? Why it's not passing?

If you can't read discussion, pinned issue, check latest PR  I really don't know what to say.

**Comment by rakeshlanjewar** [comment]
> What's up with tests? Why it's not passing?
> 
> If you can't read discussion, pinned issue, check latest PR I really don't know what to say.

Sorry for this, i will try again. Your help will be appreciated.
