### ISSUE TITLE
Mongodb for Laravel8

### ISSUE THREAD

**Issue by kazemimorteza68** [jenssegers/laravel-mongodb#2107]
- Laravel-mongodb Version: v3.7.0
- PHP Version: 7.4.10
- Database Driver & Version: 

   MongoDB extension version => 1.7.4
libbson bundled version => 1.16.2
libmongoc bundled version => 1.16.2
libmongocrypt bundled version => 1.0.3

### Description:

Hi
i installed Laravel V8.5.
when want install mongodb package for laravel(This Package) i have problem and cant install this package using composer.
Thanks for help

### Steps to reproduce
1.
2.
3.

### Expected behaviour
i cant install package normally on Laravel8

### Actual behaviour
i encounter  errors that they says i should remove  laravel/framework v8.5.0

<details><summary><b>Logs</b>:</summary>

 Problem 1
    - Installation request for jenssegers/mongodb ^3.7 -> satisfiable by jenssegers/mongodb[v3.7.0].
    - Conclusion: remove laravel/framework v8.5.0
    - Conclusion: don't install laravel/framework v8.5.0
    - jenssegers/mongodb v3.7.0 requires illuminate/events ^7.0 -> satisfiable by illuminate/events[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0, v7.1.1, v7.1.2, v7.1.3, v7.10.0, v7.10.1, v7.10.2, v7.10.3, v7.11.0, v7.12.0, v7.13.0, v7.14.0, v7.14.1, v7.15.0, v7.16.0, v7.16.1, v7.17.0, v7.17.1, v7.17.2, v7.18.0, v7.19.0, v7.19.1, v7.2.0, v7.2.1, v7.2.2, v7.20.0, v7.21.0, v7.22.0, v7.22.1, v7.22.2, v7.22.3, v7.22.4, v7.23.0, v7.23.1, v7.23.2, v7.24.0, v7.25.0, v7.26.0, v7.26.1, v7.27.0, v7.28.0, v7.28.1, v7.28.2, v7.28.3, v7.3.0, v7.4.0, v7.5.0, v7.5.1, v7.5.2, v7.6.0, v7.6.1, v7.6.2, v7.7.0, v7.7.1, v7.8.0, v7.8.1, v7.9.0, v7.9.1, v7.9.2].
    - don't install illuminate/events 7.x-dev|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.3|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.4|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.5|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.6|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.7|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.0.8|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.1.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.1.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.1.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.1.3|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.10.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.10.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.10.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.10.3|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.11.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.12.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.13.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.14.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.14.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.15.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.16.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.16.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.17.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.17.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.17.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.18.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.19.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.19.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.2.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.2.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.2.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.20.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.21.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.22.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.22.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.22.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.22.3|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.22.4|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.23.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.23.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.23.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.24.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.25.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.26.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.26.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.27.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.28.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.28.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.28.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.28.3|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.3.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.4.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.5.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.5.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.5.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.6.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.6.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.6.2|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.7.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.7.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.8.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.8.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.9.0|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.9.1|don't install laravel/framework v8.5.0
    - don't install illuminate/events v7.9.2|don't install laravel/framework v8.5.0
    - Installation request for laravel/framework (locked at v8.5.0, required as ^8.0) -> satisfiable by laravel/framework[v8.5.0].

</details>

**Comment by divine** [comment]
Hello,

Please see this discussion https://github.com/jenssegers/laravel-mongodb/discussions/2081

Thanks!

**Comment by kazemimorteza68** [comment]
Hi Dear  @divine  how can i be aware of release date of this great package?

Thanks.

**Comment by divine** [comment]
> Hi Dear @divine how can i be aware of release date of this great package?
> 
> Thanks.

Soon, I can't say exact day it has been already delayed for a week.

There are some bugs that I should have a look.

Checking even one bug takes time, please be patient we will have new release soon.

Thanks!
