### ISSUE TITLE
Issue with memory limit : Sort exceeded memory limit of 104857600 bytes,

### ISSUE THREAD

**Issue by karimElb** [jenssegers/laravel-mongodb#2110]
Hi I have issue when loading data from mongodb using Sort option
I got this message "message: "multiplanner encountered a failure while selecting best plan :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in."
"
**I know that the memory limit excited and I have to set allowDiskUse to True, I tried this :** 
```
...
->orderBy('created_at',$dir)
->options(['allowDiskUse' => true])
->get.....
```

But it's not working I got the same error.
Is there any solution to resolve this issue.

**Comment by divine** [comment]
Increase your PHP memory limit. I can't really reproduce this.

**Comment by karimElb** [comment]
@divine  I already did, but the issue is related to mongodb.

Aggregation pipeline stages in mongodb have maximum memory use limit. To handle large datasets, we need to set allowDiskUse option to true to enable writing data to temporary files

What MongoDb is saying here is that aggregate like sort has a maximum of RAM configured, but when exceeded instead of abort the operation it will continue using disk file storage instead of RAM, if the allowDiskUse has been set to true.

`db.getCollection('movies').aggregate( [
      { $sort : { year : 1} }
   ],
   { allowDiskUse: true }
)`

But how we can change the value to true in Laravel ?

**Comment by divine** [comment]
Can you please dump that query? Does it contain `{ allowDiskUse: true }` ?

**Comment by aabraham88** [comment]
which version of **laravel-mongodb** are using?

**Comment by SocolaDaiCa** [comment]
you need create index before sort. example

```js
db.user.createIndex({ country: 1 });
```

**Comment by divine** [comment]
Closing as not related.
