### ISSUE TITLE
migration error with query order by

### ISSUE THREAD

**Issue by filipewellpack** [jenssegers/laravel-mongodb#2112]
- Laravel-mongodb Version: 3.8.x
- PHP Version: 7.4.10
- Database Driver & Version: windows PECL 1.8.0 ts / CosmoDb with Mangodb Api 3.6

### Description:
I have an issue while executing console log command : php artisan migrate
It return error :

`
MongoDB\Driver\Exception\CommandException 
Error=2, Details='Response status code does not indicate success: BadRequest (400); 
Substatus: 0; ActivityId: 83dffbbe-b0ac-499d-8a32-05e7d3ef3251; 
Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 83dffbbe-b0ac-499d-8a32-05e7d3ef3251; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 83dffbbe-b0ac-499d-8a32-05e7d3ef3251; Reason: (Message: {"Errors":["The index path corresponding to the specified   at E:\www\labo\laravel\cosmos_db\cosmosdb_mangodb\vendor\mongodb\mongodb\src\Operation\Find.php:337
    333â–•         if ($inTransaction && isset($this->options['readConcern'])) {
    334â–•             throw UnsupportedException::readConcernNotSupportedInTransaction();
    335â–•         }
    336â–• 
  âžœ 337â–•         $cursor = $server->executeQuery($this->databaseName . '.' . $this->collectionName, new Query($this->filter, $this->createQueryOptions()), $this->createExecuteOptions());
    338â–• 
    339â–•         if (isset($this->options['typeMap'])) {
    340â–•             $cursor->setTypeMap($this->options['typeMap']);
    341â–•         }
  1   E:\www\labo\laravel\cosmos_db\cosmosdb_mangodb\vendor\mongodb\mongodb\src\Operation\Find.php:337
      MongoDB\Driver\Server::executeQuery("testdb.migrations", Object(MongoDB\Driver\Query), [Object(MongoDB\Driver\ReadPreference)])
  2   E:\www\labo\laravel\cosmos_db\cosmosdb_mangodb\vendor\mongodb\mongodb\src\Collection.php:663
      MongoDB\Operation\Find::execute(Object(MongoDB\Driver\Server))`
`

the problème come from this file : 
E:\www\labo\laravel\cosmos_db\cosmosdb_mangodb\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php
resolve : comment all order by in this file

### Steps to reproduce
1. install laravel version 8  : laravel new testproject --jet 
2. choose "livewire" when it prompte
3. configure .env with this db option : 
DB_CONNECTION=mongodb
DB_DATABASE=testdb
DB_DSN=connection string
5. execute php artisan migrate

**Comment by divine** [comment]
Hello,

Could you please share your migration file (stripping down any private information).

Also, what is  CosmoDb with Mangodb? Is that Azure?

Thanks!

**Comment by filipewellpack** [comment]
CosmosDb with api mango db is Azure CosmosDB (old name : DocumentDB)

below all migration file i try to execute

[migrations.zip](https://github.com/jenssegers/laravel-mongodb/files/5325917/migrations.zip)

**Comment by oanesbogdan** [comment]
Same issue here with 
PHP 7.4.11
"jenssegers/mongodb": "^3.7",
"laravel/framework": "^7.24",

**Comment by divine** [comment]
> Reason: (Message: {"Errors":["The order by query does not have a correspondin

What's left after this ?

**Comment by oanesbogdan** [comment]
@divine 
![image](https://user-images.githubusercontent.com/6011217/95781754-2436b880-0cd7-11eb-87eb-6252225b7e0e.png)

**Comment by divine** [comment]
I don't know what to say, you guys have some weird errors related to Azure usage:

https://azurecosmosdb.github.io/labs/dotnet/labs/04-indexing_in_cosmosdb.html#adding-a-composite-index

https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-troubleshoot

> Azure Cosmos DB does not host the MongoDB engine. It provides an implementation of the MongoDB wire protocol version 3.6 and legacy support for wire protocol version 3.2, therefore some of these errors are only found in Azure Cosmos DB's API for MongoDB.


Solution is : _Create a matching index (or composite index) for the sort query being attempted._

---

Azure Cosmos DB isn't exactly MongoDB it's trying to imitate MongoDB API but you need to double check documentation what is different and what error does mean. I'm not sure how we could even fix it if it's related to Azure?

This library never advertised to be working with Azure/AWS, they're different completely. Please see this https://www.mongodb.com/cloud/atlas/compare to understand better.

Thanks!

**Comment by filipewellpack** [comment]
thanks for your help.
You advise in the README that we don't create collection with migration but create it on the portal azure in azure cosmos db database.
