### ISSUE TITLE
None of the Relations work 

### ISSUE THREAD

**Issue by virgiltu** [jenssegers/laravel-mongodb#2119]
- Laravel-mongodb Version:  dev-develop
- PHP Version: 7
- Database Driver & Version:  atlas

### Description:
   Ok I have been working on this for three days with no results, I have to assume at this point that there might be bug that is causing this. 
I am setting up an extremely simple relation   hasOne 

```
// Categories
{
	_id: ObjectId('5c8445700000000000000000'),
	name: 'Foo',
	description: 'Test foo'
}

// Posts
{
	_id: ObjectId('5c8445700000000000000001'),
	name: 'Bar',
	text: 'Test foo',
	category_id: ObjectId('5c8445700000000000000000')
}
```

The Controller Code 

```
   protected $collection = 'category';
    protected $primaryKey = '_id';
    protected $guarded = [];

    protected $casts = [
        'category_id' => 'string',
    ];
public function category()
{
    return $this->hasOne(Categories::class,  '_id', 'category_id');
}
```

Blade

```
  $category = Categories::where('name', 'Foo')->first();

           dd($category->parent());
```

No matter what I did or tried the result relation is always empty. 

Anybody has any ideas?

**Comment by divine** [comment]
Hello,

Why are you using dev-develop version and not the latest stable ones?

Thanks!
