### ISSUE TITLE
firstOrCreate on null fields throws error

### ISSUE THREAD

**Issue by mikebronner** [jenssegers/laravel-mongodb#213]
When running the following query:

```
$myUser = User::firstOrCreate(array('middleInitial' => 'T'));
```

And given that I have multiple users with no middle initial, I get the following error:

```
E11000 duplicate key error index: xxxxx dup key: { : null }
```

Shouldn't the nulls just be ignored in this case, and if no positive identification of a record is made, create a new one? The middleInitial field is also not indexed, so I don't think that should be an issue.

Thanks!
~Mike

Update: some more info on the error:

```
/vagrant/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php, line 366:
        $result = $this->collection->insert($values);
```

**Comment by bharanirajan3495** [comment]
.
