### ISSUE TITLE
belongsTo relation with related ObjectId is not working

### ISSUE THREAD

**Issue by cacharrin** [jenssegers/laravel-mongodb#2132]
- Laravel-mongodb Version: v3.6.5
- PHP Version: 7.4
- Database Driver & Version: 4.2.3

### Description:
I have this data on the database:

Collection: `articles`

    {
        "_id": ObjectId("5f8a06c2276f0000c1005c52"),
        --- anoher data
        "userId": ObjectId("5ecd2b3fed5d0000dd000dd2")
    }    

Collection: `users`

    {
        "_id": ObjectId("5ecd2b3fed5d0000dd000dd2"),
        --- anoher data
        "name": "Bob"
    }    

Then I defined my models as:

    class Article extends Model
    {
        public function user() {
            return $this->belongsTo(User::class, "userId");
        }
    }

If I do:

    $article = Articles::find("5f8a06c2276f0000c1005c52");
    $article->load("user");

It display a warning

>Illegal offset type in isset or empty in \vendor\illuminate\database\Eloquent\Relations\BelongsTo.php on line 188

Also the `user` property is set to `null` (no user was loaded)

But if I change the `userId` to be a `string` instead of an `ObjectId`:

    {
        "_id": ObjectId("5f8a06c2276f0000c1005c52"),
        --- anoher data
        "userId": "5ecd2b3fed5d0000dd000dd2"
    }    

The above code works fine.

How can I make the relation to work with ObjectId?

**Comment by divine** [comment]
Hello,

Currently it's doesn't work with Object IDs, you need to change your data to string.

Changing relations to work with object IDs by default is a breaking change, see this https://github.com/jenssegers/laravel-mongodb/issues/1974#issuecomment-592857370

Thanks!

**Comment by SyedSohail9t5** [comment]
@divine Does it support relation with object id now?
