### ISSUE TITLE
Like operator doesn't work with number

### ISSUE THREAD

**Issue by Kyshino** [jenssegers/laravel-mongodb#2138]
- Laravel-mongodb Version: 6.3.1
- PHP Version: 7.4

### Description:

When I try to use the LIKE operator with a number, it doesnt work,

### Steps to reproduce
1. Use $query->where("column", "LIKE", "%29%");

### Expected behaviour
Return all rows that contain the value 29 in column

### Actual behaviour
Returns nothing

### Possible solution
The problem is in the file mongodb/Query/Builder.php specifically in the function called compileWhereBasic.
In this code 

```
       if (in_array($operator, ['like', 'not like'])) {
            if ($operator === 'not like') {
                $operator = 'not';
            } else {
                $operator = '=';
            }
```

$operator change from like to = and then in this other code, a few lines down
```
        if (!isset($operator) || $operator == '=') {
            if ($is_numeric) {
                $query = ['$where' => '/^'.$value->getPattern().'/.test(this.'.$column.')'];
            } else {
                $query = [$column => $value];
            }
```
That check if operator is '=' (what changed a few lanes before) and $is_numeric is true (this is true because our like is with 29) change the query to that and then it doesnt return nothing.

I tried to replace 

```
            if ($is_numeric) {
                $query = ['$where' => '/^'.$value->getPattern().'/.test(this.'.$column.')'];
            } else {
                $query = [$column => $value];
            }
```

for 

`$query = [$column => $value];`

and its working.

<details><summary><b>Logs</b>:</summary>
SyntaxError: identifier starts immediately after numeric literal
(1/1) CommandException
SyntaxError: identifier starts immediately after numeric literal

in Count.php line 176
</details>

**Comment by Kyshino** [comment]
Any news about this?

**Comment by divine** [comment]
Hello,

This was fixed in #2020

Update to latest version of the library.

Thanks!

**Comment by JpuntoLpuntoApps** [comment]
Hi @divine ,

I'm a @Kyshino's teammate, we have update to lastest library version (3.6.6) and now we don't get an error but neither obtain results. When we filter a string datatype like this by value 38, for example, the library not return any data
![image](https://user-images.githubusercontent.com/29434723/102119164-fa1d8600-3e40-11eb-8f09-536e200df880.png)


I tried to replace

            if ($is_numeric) {
                $query = ['$where' => '/^'.$value->getPattern().'/.test(this.'.$column.')'];
            } else {
                $query = [$column => $value];
            }
for

$query = [$column => $value];

and its working. I attach an image with generated filters:

![image](https://user-images.githubusercontent.com/29434723/102118405-f2111680-3e3f-11eb-9788-f080edc6e249.png)

Thanks a lot!

**Comment by divine** [comment]
Hello,

Quite interesting so basically reverting back fixes that issue?

Thanks!

**Comment by JpuntoLpuntoApps** [comment]
Hello,

In our case, if we replace this condition

       if ($is_numeric) {
            $query = ['$where' => '/^'.$value->getPattern().'/.test(this.'.$column.')'];
        } else {
            $query = [$column => $value];
        }

by 
     $query = [$column => $value];

we retrieve expected results, but we don't know if you delete the if condition could generate other errors.

Thanks

**Comment by Kyshino** [comment]
Hello,

Any news about this?

Thanks.

**Comment by divine** [comment]
> Hello @divine,
> 
> Any news about this?
> 
> Thanks.

Hello,

Sorry for the delay but we need to discuss this with @Smolevich.

My personal view would be to revert it back.  That PR created a lot of bugs here and there and it's a real pain with custom code detection for numeric values for like query.

Thanks!

**Comment by Smolevich** [comment]
I see on this bug today or tomorrow

**Comment by Kyshino** [comment]
Thank you very much for the reply @Smolevich,

I look forward to your answer.

**Comment by Kyshino** [comment]
Hello @Smolevich,

Any news about this?

**Comment by divine** [comment]
Hello,

We have reverted back PR that introduced this regression.

Please, update to latest version and let us know.

Thanks!

**Comment by aizaztag** [comment]
for me its not working 
 protected function compileWhereBasic(array $where)
    {
        extract($where);
        $is_numeric = false;

        // Replace like or not like with a Regex instance.
        if (in_array($operator, ['like', 'not like'])) {
            if ($operator === 'not like') {
                $operator = 'not';
            } else {
                $operator = '=';
            }

            // Convert to regular expression.
            $regex          = preg_replace('#(^|[^\\\])%#', '$1.*', preg_quote($value));

            $plain_value    = $value;


            // Convert like to regular expression.
            if (!Str::startsWith($value, '%')) {
                $regex = '^' . $regex;
            }
            else {
                $plain_value = Str::replaceFirst('%', null, $plain_value);
            }
            if (!Str::endsWith($value, '%')) {
                $regex .= '$';
            }else {
                $plain_value = Str::replaceLast('%', null, $plain_value);
            }


            $is_numeric = is_numeric($plain_value);
            $value      = new Regex($regex, 'i');
        } // Manipulate regexp operations.
        elseif (in_array($operator, ['regexp', 'not regexp', 'regex', 'not regex'])) {
            // Automatically convert regular expression strings to Regex objects.
            if (!$value instanceof Regex) {
                $e = explode('/', $value);
                $flag = end($e);
                $regstr = substr($value, 1, -(strlen($flag) + 1));
                $value = new Regex($regstr, $flag);
            }

            // For inverse regexp operations, we can just use the $not operator
            // and pass it a Regex instence.
            if (Str::startsWith($operator, 'not')) {
                $operator = 'not';
            }
        }

        if (!isset($operator) || $operator == '=') {
            $query = [$column => $value];
            
        } elseif (array_key_exists($operator, $this->conversion)) {
            $query = [$column => [$this->conversion[$operator] => $value]];
        } else {
            $query = [$column => ['$' . $operator => $value]];
        }

        return $query;
    }
