### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by alfirus** [jenssegers/laravel-mongodb#2140]
- Laravel-mongodb Version: 3.8
- PHP Version: 7.4
- Database Driver & Version: 1.8

### Steps to reproduce
1. composer require jenssegers/mongodb

### Expected behaviour
Should install normally

### Actual behaviour
Problem 1
    - jenssegers/mongodb[v3.8.0, ..., v3.8.1] require mongodb/mongodb ^1.6 -> satisfiable by mongodb/mongodb[1.6.0, ..., 1.7.2].
    - mongodb/mongodb[1.6.0, ..., 1.6.1] require ext-mongodb ^1.7 -> it is missing from your system. Install or enable PHP's mongodb extension.
    - mongodb/mongodb[1.7.0, ..., 1.7.2] require ext-mongodb ^1.8 -> it is missing from your system. Install or enable PHP's mongodb extension.
    - Root composer.json requires jenssegers/mongodb ^3.8 -> satisfiable by jenssegers/mongodb[v3.8.0, v3.8.1].

**Comment by divine** [comment]
Hello,

Install missing ext-mongodb extension.

Thanks!

**Comment by arslannawaz** [comment]
I did put mongodb extention in php ext dir, and include extension=php_mongodb.dll in php.ini file.. but still having the same error.

**Comment by arslannawaz** [comment]
> Hello,
> 
> Install missing ext-mongodb extension.
> 
> Thanks!

I did put mongodb extention in php ext dir, and include extension=php_mongodb.dll in php.ini file.. but still having the same error.

**Comment by alfirus** [comment]
> > Hello,
> > Install missing ext-mongodb extension.
> > Thanks!
> 
> I did put mongodb extention in php ext dir, and include extension=php_mongodb.dll in php.ini file.. but still having the same error.

For easy installation, I use Ubuntu fr development and server.

![image](https://user-images.githubusercontent.com/3857321/111890432-3229fb80-8a24-11eb-9af3-88e6732effbb.png)
