### ISSUE TITLE
installing to existing Lumen Project has errors.

### ISSUE THREAD

**Issue by BroJenuel** [jenssegers/laravel-mongodb#2145]
- Laravel-mongodb Version: 3.8
- PHP Version: 7.2
- Database Driver & Version: Lumen 6.0

### Description:
We have an existing project, We tried to install the `jenssegers/mongodb` package but it doesn't work.

### Steps to reproduce
1. composer require jenssegers/mongodb

### Expected behaviour
It should install

### Actual behaviour
when installing it added on the composer.json but did not install the package. and this is the error came out

![image](https://user-images.githubusercontent.com/31676163/101595867-0e234b00-3a2f-11eb-89e4-b18de6b7f429.png)
![image](https://user-images.githubusercontent.com/31676163/101595904-1a0f0d00-3a2f-11eb-9cc9-6de86c9b9481.png)

**Comment by nickshore** [comment]
The documentation states that 3.8 requires Laravel/Lumen 8.  See here -> https://github.com/jenssegers/laravel-mongodb#laravel-version-compatibility

I can also see this aligns with the composer output message relating to jenssegers/mongdb v3.8.0 requiring illuminate/events greater than 8.0

**Comment by divine** [comment]
Hello,

Quite interesting why composer picked up version ^8 for your Lumen installation.

Just require version 6 for your installation.

Thanks!

**Comment by nickshore** [comment]
It will be the composer file for jenssegers/mongodb that is forcing the dependency check.  See here -> https://github.com/jenssegers/laravel-mongodb/blob/master/composer.json

**Comment by divine** [comment]
> It will be the composer file for jenssegers/mongodb that is forcing the dependency check. See here -> https://github.com/jenssegers/laravel-mongodb/blob/master/composer.json

I know, however composer should have picked up compatible version on it's own AFAIK.

Thanks!

**Comment by BroJenuel** [comment]
I was able to fix it now by updating my lumen to the latest version thanks.

**Comment by BroJenuel** [comment]
I was able to fix it now by updating my lumen to the latest version thanks.
