### ISSUE TITLE
I want to request a feature about alias

### ISSUE THREAD

**Issue by BroJenuel** [jenssegers/laravel-mongodb#2156]
So for example in SQL we have the `select user_id as id from users`
using as so that it will return data with a property name id instead of user_id.
sample output:

```php
$users = [
     {
          id: 1
      },
     {
          id: 2
      },
     {
          id: 3
      },
     {
          id: 4
      },
     {
          id: 5
      },
]
```

How can this be done in lumen MongoDB? thanks 👍🏻

**Comment by divine** [comment]
Hello,

Please stop spamming new issues, you're asking questions and that's the reason why they should go to discussions.

Thanks!
