### ISSUE TITLE
[Feature Request] Add event saved, saving when using sync() 

### ISSUE THREAD

**Issue by nohattee** [jenssegers/laravel-mongodb#2157]
Hi, I am making an ActivityLog Module. I need to record when the model was changed or was created. But it does not work with the belongsToMany relationship. I looked at Laravel's official website. They said the only way is using pivot. And when I check your package it seems not to support pivot.

Can you help me to solve this problem? Thanks

**Comment by divine** [comment]
Hello,

This package extends Laravel's Eloquent models.  It should work as expected if not please let us know.

Thanks!
