### ISSUE TITLE
Not-optimal fetching data with belongsToMany 

### ISSUE THREAD

**Issue by Artiomtb** [jenssegers/laravel-mongodb#2166]
- Laravel-mongodb Version: 3.8.2
- PHP Version: 8.0.0
- Database Driver & Version: mongodb/mongodb:1.8.0

### Description:

Hello. I have some unexpected behaviour with fetching `belongsToMany` relation

### Steps to reproduce
1. Create classes, link them to each other by many-to-many relation:

```
class ModOne extends Model
{
    protected $collection = 'modelone';

    protected $fillable = ['key1'];

    public $timestamps = false;

    public function modelsTwo()
    {
        return $this->belongsToMany(ModTwo::class);
    }
}
```
```
class ModTwo extends Model
{
    protected $collection = 'modeltwo';

    protected $fillable = ['key2'];

    public $timestamps = false;

    public function modelsOne()
    {
        return $this->belongsToMany(ModOne::class);
    }
}
```
2. Create both objects, link to each other:
```
$mod1 = new ModOne(['key1' => 'val1']);
$mod2 = new ModTwo(['key2' => 'val2']);
$mod1->save();
$mod2->save();

$mod1->modelsTwo()->attach($mod2);
$mod1->save();
```
Then we have in db objects with `mod_two_ids[]` and `mod_one_ids[]` accordingly. That's correct.

3. I try to load `ModOne` data with `modelsTwo` relation:
```
ModOne::with('modelsTwo')->find($modOneId);
```
Data loads correctly. But I see unexpected query to db.
First query loads model `ModOne` by `_id`, it's good, then next query loads related `ModTwo` data.

### Expected behaviour
I want to load `ModTwo` related objects by their `_id`, mentioned in `ModOne.mod_two_ids`:
```
modeltwo.find({"_id":{"$in":["<ModTwo._id from ModOne.mod_two_ids>"]}},{"typeMap":{"root":"array","document":"array"}})
```

### Actual behaviour
We get `_id` of selected `ModOne` and execute such query:
```
modeltwo.find({"mod_one_ids":{"$in":["<ModOne._id>"]}},{"typeMap":{"root":"array","document":"array"}})
```

Could you help me, how to get behavior like such code:

```
$modOne = ModOne::find($id);
$modOne->setRelation('modelsTwo', ModTwo::whereIn('_id', $modOne->mod_two_ids)->get());
```

**Comment by makladuxbert** [comment]
You can have a look at this issue #2040

**Comment by divine** [comment]
Duplicate. Closing.
