### ISSUE TITLE
No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on \'localhost:27017\']

### ISSUE THREAD

**Issue by abdrozak20** [jenssegers/laravel-mongodb#2173]
I get this error No suitable servers found (`serverSelectionTryOnce` set): [connection refused calling ismaster on \'localhost:27017\']
I am using laravel 7
and this is config / database.php
'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => env('MONGO_DB_HOST', 'localhost'),
            'port'     => 27017,
            'database' => env('MONGO_DB_DATABASE'),
            'username' => env('MONGO_DB_USERNAME'),
            'password' => env('MONGO_DB_PASSWORD'),
            'options'   => [
                            'database' =>  env('MONGO_DB_DATABASE') // sets the authentication database required by mongo 3
                        ]
        ],
and this is .env 
DB_CONNECTION=mongodb
MONGO_DB_HOST=localhost
MONGO_DB_PORT=27017
MONGO_DB_DATABASE=halosis
MONGO_DB_USERNAME=
MONGO_DB_PASSWORD=

What should i do for resolve that problem.
Thanks in advice:)

**Comment by divine** [comment]
Hello,

Questions are asked at discussions not here


Thanks.
