### ISSUE TITLE
Using inbetween in a two same dates returns nothing.

### ISSUE THREAD

**Issue by BroJenuel** [jenssegers/laravel-mongodb#2179]
- Laravel-mongodb Version: 3.8
- PHP Version: 7.3

### Description:
I have this code but returns nothing, 
![image](https://user-images.githubusercontent.com/31676163/104142756-d9246280-53f7-11eb-9933-1e6cd658a914.png)

I also tried this using the same dates but returns nothing.
![image](https://user-images.githubusercontent.com/31676163/104142791-fe18d580-53f7-11eb-8235-4e601f584ad9.png)

### Expected behaviour
It should at least grab items in that date. because of the condition greater or equal to the date and less than or equal to the date.

### Actual behaviour
It returns nothing.

**Comment by divine** [comment]
Hello,

Does it work with DateTime?
https://github.com/jenssegers/laravel-mongodb/blob/a362df4f7fec5b91fea92b64273a531db34adfca/tests/ModelTest.php#L390-L398

Thanks!

**Comment by BroJenuel** [comment]
Good day, Sorry late to write a comment in here, It was working actually I saw the problem, the rendered data in the front end was not +8:00 time zone so its hard to know what really the DateTime, but thanks to DateTimeZOne I was able to fix my problem. I'm closing this issue.
