### ISSUE TITLE
Cannot start transaction 1 on session bd264219-dc7b-41f7-af63-57436d3588c - +WgOVnKmrMF6/mSQ4vglRC+SRli4twPTLNSeVRPyVy8= because a newer transaction 8 has already started

### ISSUE THREAD

**Issue by unflower123** [jenssegers/laravel-mongodb#2181]
"jenssegers/mongodb": "3.2.3"
Why does it appear? I didn't use transaction.

**Comment by divine** [comment]
Hello,

How we should determine why it appears? Looks like the MongoDB error not related to this library.

Thanks!

**Comment by unflower123** [comment]
MongoDB\Driver\Exception\BulkWriteException Cannot start transaction 1 on session bd264219-dc7b-41f7-af63-57436d3588c - +WgOVnKmrMF6/mSQ4vglRC+SRli4twPTLNSeVRPyVy8= because a newer transaction 8 has already started

that's the question of this libray, can't you see?

**Comment by unflower123** [comment]
a part of laravel error info:
#0 /data/wwwroot/project/release/1.7.5/vendor/mongodb/mongodb/src/Operation/InsertMany.php(142): MongoDB\Driver\Server->executeBulkWrite('db_table...', Object(MongoDB\Driver\BulkWrite), Array), #1 /data/wwwroot/project/release/1.7.5/vendor/mongodb/mongodb/src/Collection.php(869): MongoDB\Operation\InsertMany->execute(Object(MongoDB\Driver\Server)), #2 [internal function]: MongoDB\Collection->insertMany(Array), #3 /data/wwwroot/project/release/1.7.5/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php(45): call_user_func_array(Array, Array), #4 /data/wwwroot/project/release/1.7.5/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(538): Jenssegers\Mongodb\Collection->__call('insertMany', Array), #5 [internal function]: Jenssegers\Mongodb\Query\Builder->insert(Array), #6 /data/wwwroot/project/

**Comment by unflower123** [comment]
There is other people appear:
https://mongoing.com/anspress/question/mongodbdriverexceptionbulkwriteexception-%EF%BC%88php%E9%A9%B1%E5%8A%A8%E9%93%BE%E6%8E%A5%E9%97%AE%E9%A2%98%EF%BC%89

**Comment by xiehongxin** [comment]
I have the same problem
