### ISSUE TITLE
Cannot start transaction 2 on session

### ISSUE THREAD

**Issue by unflower123** [jenssegers/laravel-mongodb#2184]
- Laravel-mongodb Version: laravel:5.2.34 mongodb 1.7.5
- PHP Version: 7.1
- Database Driver & Version: mongodb 1.7.5

### Steps to reproduce
1.At the time of high frequency request , there are some errors happen.
2.
3.

### Expected behaviour
Tell us what should happen
non Frame error
### Actual behaviour
Tell us what happens instead
Frame error
<details><summary><b>Logs</b>:</summary>
many error such as:
Cannot start transaction 2 on session f81cfefe-188e-4d9f-984f-dbfc4bc875d9 - +WgOVnKmrMF6/mSQ4vglRC+SRli4twPTLNSeVRPyVy8= because a newer transaction 6 has already started
</details>

**Comment by divine** [comment]
Please kindly stop spamming.
