### ISSUE TITLE
How can i get elements and only nested elements check condition?

### ISSUE THREAD

**Issue by Luigidefra** [jenssegers/laravel-mongodb#2185]
hi, I tried but I couldn't.

i have this structure

`{_id: ObjectId('5fc0e7ee65c86d4f646a3d14'),
   slots: [
        {
            _id: '5fc0e7ee65c86d4f646a3d14_5fc0e7ee98a6b',
            created_at: ISODate('2020-11-27T11:50:06.509Z'),
            updated_at: ISODate('2020-11-27T11:50:06.509Z'),
            available_quantity: '234'
        },
        {
            _id: 'asd',
            created_at: ISODate('2020-11-27T11:50:06.509Z'),
            updated_at: ISODate('2020-11-27T11:50:06.509Z'),
            available_quantity: '234'
        }
    ]
}`

I need to retrieve all the documents that have the slot inside with a certain id, but of these documents I want to retrieve only the document and the slots that have verified the condition

Example:
Model::where('slots._id','5fc0e7ee65c86d4f646a3d14_5fc0e7ee98a6b')->get();

it get all document and all nested slots but i want only the document and its checked slot

**Comment by divine** [comment]
Hello,

Please kindly ask your questions at discussions.

Thanks!
