### ISSUE TITLE
Very Slow response in latest version

### ISSUE THREAD

**Issue by sanaderi** [jenssegers/laravel-mongodb#2189]
Tanks for this best package.
After upgrade from laravel 5.8 to 8.0 and then upgrade   jenssegers /laravel-mongodb  to 3.8 version any ajax request are very very slow.
I tested same query by mysql its response speed very good.seems this problem related to this package.

please help me to resolve my problem.
![response result](https://user-images.githubusercontent.com/11719622/105032742-69a01a00-5a6c-11eb-9fb7-db233ffcbe9a.png)

**Comment by divine** [comment]
Hello,

Network tab doesn't show how much time each operation took. Basically you haven't provided any information why it's being slow.

Closing as invalid.

Thanks!
