### ISSUE TITLE
I got error to crud with _id as type Binary - LUUID in existing mongodb

### ISSUE THREAD

**Issue by badpaybad** [jenssegers/laravel-mongodb#2192]
- Laravel-mongodb Version: ^1.8
- PHP Version: 7.4
- Database Driver & Version:  "jenssegers/mongodb": "^3.8",

### Description:
I have to connect to existing mongodb
This system developed in c#, so I got _id as type Binary - LUUID plz see image bellow
What should I do for these? 

![image](https://user-images.githubusercontent.com/6204507/105440583-65a50f80-5c99-11eb-936d-0f66266db29b.png)

**Comment by divine** [comment]
Hello,

Whats the exact error you're having?

Thanks!

**Comment by badpaybad** [comment]
Record created in c# and php did not the same way, so that they can not serialize each other

![image](https://user-images.githubusercontent.com/6204507/105652399-b6ac4200-5eeb-11eb-8382-8786d10548fd.png)

**Comment by divine** [comment]
Hello,

Can you please take a look at this https://github.com/jenssegers/laravel-mongodb/pull/1611 and see trait example here?

Thanks!
