### ISSUE TITLE
Bug: Unable to embed model without a primary key

### ISSUE THREAD

**Issue by 84564221** [jenssegers/laravel-mongodb#221]
To create an Moloquent model for a legacy collection that has no primary key, simply set the protected `primaryKey` attribute to `null`.

This method does not work for EmbedsOne relations or EmbedsMany relations.

Example classes (`User` embedsOne `Item`):

``` php
<?php

class User extends Moloquent
{
    protected $collection = 'users';

    ...

    public function item()
    {
        return $this->embedsOne('Item');
    }
}

...

class Item extends Moloquent
{
        protected $primaryKey = null;

    ...
}
```

Result after performing `$user->item()->save($item)`:

``` html
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 1004`
```

**Comment by apollopy** [comment]
You can try：
```php
<?php

class User extends Moloquent
{
    protected $collection = 'users';

    ...

    public function item()
    {
        return $this->embedsOne('Item');
    }
}

...

class Item extends Moloquent
{
    protected $primaryKey = null;

    public $incrementing = false;

    public $timestamps = false;

    ...
}
```

**Comment by apollopy** [comment]
You can try: 
```php
<?php

class User extends Moloquent
{
    protected $collection = 'users';

    ...

    public function item()
    {
        return $this->embedsOne('Item');
    }
}

...

class Item extends Moloquent
{
        protected $primaryKey = '__id';

    ...
}
```
and dont set  __id

**Comment by vacoup96** [comment]
Is there a solution for this? I'm currently working on a Meteor App that's not using ObjectID's. I'm migrating some things to laravel and now I'm encountering this issue.  Setting no primaryKey variable does not working. Setting it to null also does not work. I think the problem is the setAttribute function. The whole function seems a strange to be honest.
