### ISSUE TITLE
Argument 1 passed to MongoDB\server_supports_feature() must be an instance of MongoDB\Driver\Server, null given

### ISSUE THREAD

**Issue by rakashpal-hcah** [jenssegers/laravel-mongodb#2211]
- Laravel-mongodb Version: 3.8
- PHP Version: 7.4
- Database Driver & Version:

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by divine** [comment]
Thank you for creating an issue without giving any information.
