### ISSUE TITLE
Error while using timestamps

### ISSUE THREAD

**Issue by ingro** [jenssegers/laravel-mongodb#222]
Hello, I've got a nasty problem with this library and Eloquent's timestamps.

When I try to save a new object to Mongo I got this exception, throwed in Eloquent's Model getDateFormat() function:

```
Call to a member function getDateFormat() on a non object
```

If I set $timestamps to false inside my model the problem disappear.

Also I had to explicitly set $primaryKey and $table (instead of $collection) properties on my model declaration to make it work.

Any hint? I'm missing something?

**Comment by Kabangi** [comment]
Am getting this error and it only goes away if i have $timestamp = false. Kindly help. Using laravel 5.2 and laravel-mongodb ^3.0
