### ISSUE TITLE
Custom _id with a pre-generated _id

### ISSUE THREAD

**Issue by nanchet** [jenssegers/laravel-mongodb#225]
Hi!

I have an ObjectId generator in Javascript, which generates "_id" like "5394d7db560c9869a1000002", But when I pass this "_id" to "Moloquent" to do an insert it stores as a string instead of an ObjectId like "ObjectId('5394d7db560c9869a1000002')".

The only way I have found to solve this is to make a new MongoId with the pre-generated "_id".

```
$this->_id  = new MongoId($obj['_id']);
$this->name = $obj['name'];
$this->save();
```

There is another more elegant way to do this? Thanks!

PD: (Sorry for my english)

**Comment by jimeshgajera** [comment]
@jenssegers 
I hope you are doing good!

I have an issue with relationship id, which is store as string. 

How I can store that companyId as Object id?

```
$user = new User;
$user->companyId        = $companyId;
$user->save();
```

**Comment by pirmax** [comment]
@jimeshgajera I want this too!

**Comment by jimeshgajera** [comment]
@pirmax 

I have find solution for same. Try below syntax.

`$id = new \MongoDB\BSON\ObjectID($id);`

As per my code, it will look like below

```
$user = new User;
$user->companyId = new \MongoDB\BSON\ObjectID($companyId);
$user->save();
```

**Comment by pirmax** [comment]
Thanks @jimeshgajera !

**Comment by fodaamr8** [comment]
> Hi!
> 
> I have an ObjectId generator in Javascript, which generates "_id" like "5394d7db560c9869a1000002", But when I pass this "_id" to "Moloquent" to do an insert it stores as a string instead of an ObjectId like "ObjectId('5394d7db560c9869a1000002')".
> 
> The only way I have found to solve this is to make a new MongoId with the pre-generated "_id".
> 
> ```
> $this->_id  = new MongoId($obj['_id']);
> $this->name = $obj['name'];
> $this->save();
> ```
> 
> There is another more elegant way to do this? Thanks!
> 
> PD: (Sorry for my english)

@nanchet 

you can add your id in your create object as id field and add this code in model

protected static function boot()
    {
        parent::boot();

        static::creating(function($order) {
            $order->_id = $order->id;
        });
    }

**Comment by xpaco** [comment]
> @pirmax
> 
> I have find solution for same. Try below syntax.
> 
> `$id = new \MongoDB\BSON\ObjectID($id);`
> 
> As per my code, it will look like below this
> 
> ```
> $user = new User;
> $user->companyId = new \MongoDB\BSON\ObjectID($companyId);
> $user->save();
> ```
❤️❤️
Hug you! Thank you very much!!!
