### ISSUE TITLE
Incompatibility with spatie/laravel-permissions

### ISSUE THREAD

**Issue by Pilskalns** [jenssegers/laravel-mongodb#2252]
- Laravel-mongodb Version: 3.8
- PHP Version: 8.0.6
- Database Driver & Version: 4.4.6

### Description:
Apparently, if another package includes models of its own, then it's not possible to override which Eloquent model to use. The laravel-permissions package includes two models `Role` and `Permission`, where both do `use Illuminate\Database\Eloquent\Model;`.

As in the docs, we have to use `use Jenssegers\Mongodb\Eloquent\Model;`, but if the code is inside the vendor, then it's not _possible_ to patch it.

### Steps to reproduce
1. Install Laravel, `spatie/laravel-permission` and `jenssegers/laravel-mongodb`
2. Do a setup according to all guides and model extending
3. Try to call any method that is provided by laravel-permissions

### Expected behaviour

If I change two lines inside the **vendor** directory to use `use Jenssegers\Mongodb\Eloquent\Model;`, then it works as expected:

https://github.com/spatie/laravel-permission/blob/master/src/Models/Role.php#L5
https://github.com/spatie/laravel-permission/blob/master/src/Models/Permission.php#L6

It works **_only_** on my machine and I will forget about this modification down the line. Is there a better way how to solve this?

### Actual behaviour
Following error is thrown:
`BadMethodCallException`
`Method Jenssegers\Mongodb\Schema\Grammar::compileColumnListing does not exist.`

<details><summary><b>Stack trace</b>:</summary>
[2021-05-13 22:44:03] local.ERROR: Method Jenssegers\Mongodb\Schema\Grammar::compileColumnListing does not exist. {"userId":"609da3556961000019007d46","exception":"[object] (BadMethodCallException(code: 0): Method Jenssegers\\Mongodb\\Schema\\Grammar::compileColumnListing does not exist. at laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Macroable\\Traits\\Macroable.php:103)
[stacktrace]
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Schema\\Builder.php(191): Illuminate\\Database\\Grammar->__call('compileColumnLi...', Array)
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\GuardsAttributes.php(222): Illuminate\\Database\\Schema\\Builder->getColumnListing('roles')
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\GuardsAttributes.php(208): Illuminate\\Database\\Eloquent\\Model->isGuardableColumn('guard_name')
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\GuardsAttributes.php(185): Illuminate\\Database\\Eloquent\\Model->isGuarded('guard_name')
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(352): Illuminate\\Database\\Eloquent\\Model->isFillable('guard_name')
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(175): Illuminate\\Database\\Eloquent\\Model->fill(Array)
laravel_project_root\\vendor\\spatie\\laravel-permission\\src\\Models\\Role.php(27): Illuminate\\Database\\Eloquent\\Model->__construct(Array)
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(1167): Spatie\\Permission\\Models\\Role->__construct()
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(476): Illuminate\\Database\\Eloquent\\Model::query()
laravel_project_root\\app\\Http\\Controllers\\RoleController.php(20): Illuminate\\Database\\Eloquent\\Model::all()
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): App\\Http\\Controllers\\RoleController->index()
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('index', Array)
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\RoleController), 'index')
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(197): Illuminate\\Routing\\Route->runController()
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(695): Illuminate\\Routing\\Route->run()
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Auth\\Middleware\\Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(697): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(636): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(166): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\fruitcake\\laravel-cors\\src\\HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
laravel_project_root\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
laravel_project_root\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
laravel_project_root\\server.php(21): require_once('laravel_project_root...')
{main}
"}
</details>

**Comment by divine** [comment]
Hello,

Have you tried running `php artisan vendor:publish` and publishing tha models files?

I don't see see any issue with this library. Ask them.

Thanks.

**Comment by Pilskalns** [comment]
I wanted to avoid that, then all code would have to be maintained and patched with any future upgrades.

Anyway, I just found the following package https://github.com/mostafamaklad/laravel-permission-mongodb/, which claims to be _the same_ as `spatie` one, except it's made to be compatible with this package.

Maybe, to avoid future questions, like mine, it's worth adding to the docs that one has to be aware that some packages hardcode the _native_ Eloquent model. For compatibility either look for another package or well, yes do `vendor:publish` and patch manually and upgrade manually.

**Comment by divine** [comment]
> Maybe, to avoid future questions, like mine, it's worth adding to the docs that one has to be aware that some packages hardcode the _native_ Eloquent model. For compatibility either look for another package or well, yes do `vendor:publish` and patch manually and upgrade manually.

Hello,

PRs are welcome. I wouldn't able to write better than you 👋 .

Thanks!
