### ISSUE TITLE
Documentation clarification needed

### ISSUE THREAD

**Issue by NickStallman** [jenssegers/laravel-mongodb#2260]
The documentation has this note:
```
NOTE: MongoDB documents are automatically stored with a unique ID that is stored in the _id property. If you wish to use your own ID, substitute the $primaryKey property and set it to your own primary key attribute name.
```
We found that to be somewhat confusingly worded and led to us double checking our understanding of MongoDB.
In particular, the "$primaryKey" field name, and not using ObjectID ids are two unrelated things.

When creating a new model, setting $model->_id = "anything-else"; works perfectly. There's no need to rename the primary key field name to use a different ID value.
MongoDB's _id field can be of any data type, it's only if it's blank that a ObjectID will be created.

Additionally it's probably a good idea to note that while changing $primaryKey works, it's potentially not a good idea since MongoDB will always have a _id field. _id is also automatically indexed, but changing $primaryKey means the new field requires an index to be manually added.

There may be some good use cases I can't think of for changing the $primaryKey, if there are some notes about why you might want to do this would be useful, and maybe some reasons not to do it?

**Comment by divine** [comment]
Hello,

I couldn't explain better than this https://www.mongodb.com/blog/post/generating-globally-unique-identifiers-for-use-with-mongodb

Thanks!

**Comment by NickStallman** [comment]
Thanks @divine, yep that doc outlines the options very nicely.

My point is more about the wording in the README about $primaryKey.
It kind of sounds like if you don't want ObjectID then you need to change $primaryKey to a different field.

This bit here:
*If you wish to use your own ID, substitute the $primaryKey property and set it to your own primary key*

If you want to use your own ID then you just set $model->_id like normal when creating the document.

**Comment by divine** [comment]
Hello,

You're welcome, if you'd like to improve documentation just submit PR.

I don't have better English grammar skills than you do.

Thanks!

**Comment by NickStallman** [comment]
I'll see what I can come up with. :)
