### ISSUE TITLE
getRelationQuery incompatible

### ISSUE THREAD

**Issue by MeerKatDev** [jenssegers/laravel-mongodb#2262]
- Laravel-mongodb Version: 3.8.3
- PHP Version: 7.4.19
- Database Driver & Version:

### Description:
```
<warning>PHP Warning:  
Declaration of Jenssegers\Mongodb\Relations\HasMany::getRelationQuery(Illuminate\Database\Eloquent\Builder $query, 
Illuminate\Database\Eloquent\Builder $parent, $columns = Array) should be compatible with 
Illuminate\Database\Eloquent\Relations\Relation::getRelationQuery() in C:\projects\lookinglass-
backend\vendor\jenssegers\mongodb\src\Jenssegers\Mongodb\Relations\HasMany.php on line 68</warning>
```

### Steps to reproduce
1. just declare a relation

**Comment by shopapps** [comment]
Had the same issue, it is due to new laravel/framework.

had to rollback to 8.42.1 to get it to work:
```
composer require laravel/framework:8.42.1
```

**Comment by sepisoltani** [comment]
having same problem
any solution other than downgrading to Laravel version 8.42.1 ??

**Comment by Ian-Tala** [comment]
For anybody dealing with this issue in Lumen (or also Laravel), you can alternatively force the version of illuminate/database for it to work, until this library is updated.

You'd set it like so:

```
composer require illuminate/database:8.42.1
```

**Comment by divine** [comment]
Hello,

We're aware of this problem and currently looking for a solution.

This looks like a breaking change and probably requiring the release of a new version of this library.

Still in the talks with @Smolevich about it.

Thanks!

**Comment by denaviagt** [comment]
Helo, why i got the same error?

**Comment by sv-hmelevsky** [comment]
Same error when i try use relations!
```
"laravel/framework": "^8.75",
"jenssegers/mongodb": "3.8"
```
