### ISSUE TITLE
Deletes All user.

### ISSUE THREAD

**Issue by Dasinfomedia2** [jenssegers/laravel-mongodb#2297]
- Laravel-mongodb Version: 3.8
- PHP Version: 7.3.26
- Database Driver & Version:

### Steps to reproduce
1. $task->assignedTo()->truncate();
2.
3.

### Expected behavior
May be remove reference array in the task collection

### Actual behavior
deletes all user from user collection.

I am using Lumen 8.

Task.php Model
```
 public function assignedTo()
 {
        return $this->belongsToMany(User::class, null, null, 'assignee');
  }
```

**Comment by divine** [comment]
Hello,

Have a read a documentation what exactly it does.

Thanks!

**Comment by Dasinfomedia2** [comment]
I know this method would delete all records from a table.  But when called on a particular referenced array it should not. Shouldn't it only delete the reference array?

This is not how it works I get it.
