### ISSUE TITLE
Issue when using find() on embeded model

### ISSUE THREAD

**Issue by gmedaglia** [jenssegers/laravel-mongodb#2306]
- Laravel Version: 6.20.32
- jenssegers/mongodb Version: 3.6.8
- PHP Version: 7.3
- Database Driver & Version: Mongo 4

### Description:
I'm using an `EmbedsMany` relationship between my `Proof` and `ProofStage` models, like this:

```
namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Proof extends Eloquent
{
    public function stages(): EmbedsMany
    {
        return $this->embedsMany(ProofStage::class);
    }
    
    // More ...
}
```

```
namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class ProofStage extends Eloquent
{
    // ...
}
```

Based on the docs I should be able to do something like `ProofStage::find('some-id')` and get an instance of the embeded model by its id. But the reality is that I'm always getting `null` when doing so. Of course I'm passing a valid id.

### Expected behaviour
The corresponding model instance is retrieved.

### Actual behaviour
`null` is always returned, even when passing a valid id.

**Comment by Dasinfomedia2** [comment]
have you got a solution on it yet?

**Comment by gmedaglia** [comment]
> have you got a solution on it yet?

Nope.

**Comment by Dasinfomedia2** [comment]
The only way i think is - proof()->stages()->where(...)->first()

**Comment by divine** [comment]
Just don't use  _magic_ embedded relationships.

This has been discussed multiple times already.

If you know how to fix it, go ahead push PR.

Thanks!
