### ISSUE TITLE
[Feature Request] PHP 8 support

### ISSUE THREAD

**Issue by GautierDele** [jenssegers/laravel-mongodb#2308]
### Is your feature request related to a problem?
It is actually not possible to use `laravel-mongodb` since `mongodb/mongodb` 1.6 doesn't allow php 8

### Describe the solution you'd like
PHP 8 support by upgradien mongodb/mongodb to 1.9

**Comment by Wernke96** [comment]
I didn't get this issue when using php8 and I did upgrade mongodb/mongodb to 1.9

**Comment by GautierDele** [comment]
I don't really understand why since jenssegers require mongodb/mondodb 1.6 which requires php ^5.6 || ^7.0

**Comment by divine** [comment]
Hello,

We are already testing PHP 8 compatability via Github actions. Everything works fine.

Try cleaning up you composer lock file and installing again.

Thanks!

**Comment by GautierDele** [comment]
Yeah sorry about that i went a bit fast on it, seems like everything is working fine
