### ISSUE TITLE
GridFS Support

### ISSUE THREAD

**Issue by mikebronner** [jenssegers/laravel-mongodb#231]
I'm not sure exactly how, or even if, this ties into this package, but I was wondering if it is possible to implement GridFS using laravel-mongodb? I'm looking at storing images, and am considering Mongo GridFS as an option.

**Comment by mediablenders** [comment]
How can I use a gribfs record as a hasOne relationship to a document?

**Comment by ryangurn** [comment]
@potsky do you have to upload it to the server and then save it to grid or can you do it all via the upload?

**Comment by potsky** [comment]
Yes it is already uploaded to the server :

```
if ( ( Input::hasFile( 'image' ) ) && ( Input::file( 'image' )->isValid() ) )
{
	$path = strval( Input::file( 'image' ) );
	$id   = $grid->storeFile( $path );
```

**Comment by bisht2050** [comment]
GridFS is now supported! 
Follow the docs to learn how to use GridFS : https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/filesystems/
