### ISSUE TITLE
saving/saved/etc.. events are not fired for embedded models

### ISSUE THREAD

**Issue by NickStallman** [jenssegers/laravel-mongodb#2329]
- Laravel-mongodb Version: 3.8
- PHP Version: 8.0

### Description:
Is there a particular reason why an embedded model would not have it's events fired?
The parent model just needs to capture the events and duplicate them to any relevant sub models.

These events are extremely useful for manipulating or tweaking data before it's saved, or for doing additional actions after a save.

If there's no specific reason why it hasn't been implemented, I could probably put together a pull request to add the feature.

### Steps to reproduce
1. Create two models, where one embeds the other.
2. Add a "saving" event to the embedded model.
3. Call save() on the parent model, and the saving event on the embedded model will not be fired.

### Expected behaviour
Embedded models should also have the same events as a regular model.

### Actual behaviour
The parent model has it's events working normally, but the embedded models do not.

**Comment by SanaviaNicolas** [comment]
Hi @NickStallman, have you tried this [library](https://github.com/offline-agency/laravel-mongo-auto-sync)?
