### ISSUE TITLE
Unique (database) field validation

### ISSUE THREAD

**Issue by vincekovacs** [jenssegers/laravel-mongodb#234]
How to "[Forcing A Unique Rule To Ignore A Given ID](http://laravel.com/docs/validation#rule-unique)" with mongodb?
Following rule always return with "field have to be unique" error message, even if `id` is set to ignore.

``` php
'unique:modelTableName,columnName,' . $model->id
```

**Comment by darkin1** [comment]
Please reopen issue.
I had that same problem and the answear it's convert $id to int.

I did something like this

```php
'unique:operators,email,'.$id.',_id']
```
after I checked parameters in Illuminate\Validation\Validator.php I got

```
array:4 [▼
  0 => "operators"
  1 => "email"
  2 => "2"
  3 => "_id"
]
```
`2 => "2"` it's string not numeric

When I converted id `$id = (int)$id;` in `Validator.php`, validation worked correctly

**Comment by webexpert4rv** [comment]
Any update on this issue please, I tried with -

unique:admin_groups,name,'.$request->get('group_id'),'_id'

No Luck.

**Comment by webexpert4rv** [comment]
Following worked for me.

'unique:admin_groups,name,'.$request->get('group_id') . ',_id',

**Comment by marooj** [comment]
where is it of Illuminate\Validation\Validator.php @darkin1  change it ?
