### ISSUE TITLE
Undefined array key "host"

### ISSUE THREAD

**Issue by rcarvs** [jenssegers/laravel-mongodb#2342]
- Laravel-mongodb Version: 3.8.4
- PHP Version: v8.1.2,
- Database Driver & Version: 4.4.12

### Description:
Connection returning undefined array key "host" on Connection.php:204, but I've used the "driver", "dns" (with full dns uri) and "database" keys, so I think is expected that the "host" is unnecessary. When I insert the host everything works.

If possible, I think I can correct and send the pull request.
Thanks.

### Steps to reproduce
1. I used an atlas instance service, so I get the dns and database from atlas
2. Introduce driver, dns and database only inside mongodb key
3. Try to get some data 

### Expected behaviour
Connection established with DNS and not returning and Exception.

### Actual behaviour
Returning Undefined array key "host"

**Comment by divine** [comment]
How did you solve the issue? Might help others...

Thanks!

**Comment by rcarvs** [comment]
It was my mistake, I just changed **dns** to **dsn** in the connection array, sorry!

I just noticed this by doing some dumps in the method that checks if the dsn was informed  😅

Thank you!
