### ISSUE TITLE
Cannot install jenssegers/mongodb on Laravel 8.75.0

### ISSUE THREAD

**Issue by vmxt** [jenssegers/laravel-mongodb#2383]
- Laravel-mongodb Version: `jenssegers/mongodb:"^3.8`
- PHP Version: `8.0.10`
- Database Driver & Version: `MongoDB 5.0`

### Steps to reproduce
1.  Cloning a repo upon running composer install encounter a bunch of errors.
2. The `php_mongodb.dll` is already enabled on php.ini but on the console it says extension was not enabled.

### Expected behaviour
A Successful Installation

### Actual behaviour
I encounter some case problem after I `composer install`

<details><summary><b>Logs</b>:</summary>
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mongodb/mongodb dev-master requires ext-mongodb ^1.14.0 -> it has the wrong version installed (1.10.0).
    - mongodb/mongodb[1.12.0, ..., v1.12.x-dev] require ext-mongodb ^1.13.0 -> it has the wrong version installed (1.10.0).
    - mongodb/mongodb 1.13.x-dev is an alias of mongodb/mongodb dev-master and thus requires it to be installed too.
    - Root composer.json requires mongodb/mongodb ^1.12 -> satisfiable by mongodb/mongodb[1.12.0, v1.12.x-dev, 1.13.x-dev (alias of dev-master)].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\laragon\bin\php\php-8.0.10-Win32-vs16-x64\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-mongodb` to temporarily ignore these required extensions.
</details>

**Comment by vmxt** [comment]
Problem solved: `composer update`

**Comment by saintanger** [comment]
still seems to be an issue. 


  Problem 1
    - Root composer.json requires jenssegers/mongodb ^3.9 -> satisfiable by jenssegers/mongodb[v3.9.0].
    - jenssegers/mongodb v3.9.0 requires illuminate/support ^9.0 -> found illuminate/support[v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
