### ISSUE TITLE
Getting Class "MongoDB\Driver\Manager" not found on server, Please Help

### ISSUE THREAD

**Issue by Sourovahmad** [jenssegers/laravel-mongodb#2404]
on the local, it is working totally ok. but on server, I am getting this error 
Can anyone please tell me why I am getting this issue on my server

![image](https://user-images.githubusercontent.com/64475548/174041255-0707bf22-2227-45e8-ae5b-484efc477d28.png)

**Comment by divine** [comment]
Hello,

Please install mongodb PHP driver.

Thanks!
