### ISSUE TITLE
502 Bad Gateway with Moloquent $save

### ISSUE THREAD

**Issue by lelu85** [jenssegers/laravel-mongodb#243]
Hi everyone,

With the recent updates of the mongo.so and PHP I've experienced a quite annoying bug. I am using Laravel 4.1, PHP 5.5.13-2+deb.sury.org~trusty+1 (cli) (built: Jun 18 2014 08:33:56) and the mongo.so extension 1.5.4.

When I use this type of code:
$resource = $this->getResource();
$resource->fill();
$resource->save();

Nginx error.log:
2014/06/27 16:21:50 [error] 21288#0: *130 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: {server}, request: "GET /api/affiliates HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "{host}", referrer: "{referrer}"

But when I use:
$resource = $this->getResource();
$resource->fill();
$id = DB::table('affiliates')->insert(
     $resource->toArray()
);

Everything works fine. I can see that everything also works fine at every ORM function or DB facade except the $save.

Right now I had to overwrite the save() function at every model but any idea of what is happening? Because that really took me time to make the temporany solution...

Any ideas??

**Comment by Arkango** [comment]
how to solve this ? in laravel 7 and jenssenge/mongodb 3.4

**Comment by Smolevich** [comment]
@Arkango what is the problem?

**Comment by Arkango** [comment]
When I try to execute a simple query i recieve 502 page from nginx and the following errors

```
        ReportContent::timeout(-1)->find('517c43667db388101e00000f');
```

php         | [22-Oct-2020 15:15:40] WARNING: [pool www] child 8 exited on signal 11 (SIGSEGV) after 35.431576 seconds from start
php         | [22-Oct-2020 15:15:40] NOTICE: [pool www] child 9 started
nginx       | 2020/10/22 15:15:40 [error] 6#6: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.29.0.1, server: localhost, request: "GET /test HTTP/1.1", upstream: "fastcgi://172.29.0.4:9000", host:

How I have to configure correctly my php-fpm7.4-alpine ?

**Comment by Smolevich** [comment]
Show docker config files

**Comment by Arkango** [comment]
I edited only the nginx config file, 

<img width="687" alt="Schermata 2020-10-23 alle 08 47 49" src="https://user-images.githubusercontent.com/23188987/96965626-c131f680-150c-11eb-9036-6139579fe71e.png">


This is my docker command to add mongodb
``` RUN apk add --update --no-cache --virtual .docker-php-mongodb-dependancies \
          heimdal-dev && \
      pecl install mongodb && \
      docker-php-ext-enable mongodb && \
      apk del .docker-php-mongodb-dependancies && \ ```

Which file I have to edit about php-fpm? www.conf, docker.conf or zz-docker.conf

**Comment by divine** [comment]
@Arkango please create a new issue with actual logs (not php-fpm logs), you're having some weird configuration error that you even yourself don't know how to debug.

Thanks!
