### ISSUE TITLE
[Feature Request] Need DB Transactions (begin, commit and rollback) at least.

### ISSUE THREAD

**Issue by henriquetroiano** [jenssegers/laravel-mongodb#2459]
Hello guys,

We need the transactions control for laravel.

This package [https://github.com/salvationarinze/laravel-mongodb-transactions](url) can already do this and works fine. Can you please merge this package into laravel-mongodb ?

**Comment by techbelle** [comment]
This is added in https://github.com/jenssegers/laravel-mongodb/pull/2465 and is available in release [v3.9.3](https://github.com/jenssegers/laravel-mongodb/releases/tag/3.9.3)

:) :shipit:
