### ISSUE TITLE
[Feature Request] Mysql and MongoDB Side by Side Active in same model

### ISSUE THREAD

**Issue by sahnb** [jenssegers/laravel-mongodb#2463]
![image](https://user-images.githubusercontent.com/8742640/201536398-a5213975-1a58-4808-8778-8569be47179a.png)

can anyone guide or suggest how i can used two database concurrently like mysql  and mongodb both.

**Comment by henriquetroiano** [comment]
I do not understand why you need to do that. Can you explain for us?

**Comment by sahnb** [comment]
I want to twice entry one in mongodb cloud, and by default store in mysql cpanel. i handle the situation by initiate two db connection. so, no need now.
