### ISSUE TITLE
elemMatch usage

### ISSUE THREAD

**Issue by EhsanZ** [jenssegers/laravel-mongodb#251]
Hello

First, I'm appreciated your hard work in this library, it helped me a lot, it makes dealing with MongoDB so easy and fun, and it is very clean, it is just amazing :) if there is anyway to support you please tell me.

Here is the question: I have 2 models: Participation and Value, every participation has many values, the value has got an array field named "rank", for example rank = array('client'=>'A','points'=>'100').

I want to get all participations that has a value matches array('client'=>'A') so, there is my code:

```
$participations = Participation::whereHas('Values',function($value_query)
{
       $value_query->where('rank','elemMatch',array('client'=>'A'));
})->get();
```

But Unfortunately it doesnt work, it only works with array with one element so:

```
$value_query->where('rank','=',array('client'=>'A'));
```

I tried to use whereRaw but I doubt that I used it in the proper way - it doesn't work - : 

```
$value_query->whereRaw(array('rank' => array('elemMatch'=>array('client'=>'A'))));
```

Can you help me please ?
Thank you for everything <3

**Comment by manishambashta** [comment]
No it does not work

**Comment by galzetta** [comment]
We are in 2020 and this still does not work.

**Comment by divine** [comment]
> We are in 2020 and this still does not work.

You are free to send a PR in 2020.
