### ISSUE TITLE
Package "jenssegers/laravel-mongodb" is not installed in ^3.9

### ISSUE THREAD

**Issue by shawnnaquin** [jenssegers/laravel-mongodb#2510]
- Laravel-mongodb Version: ^3.9
- PHP Version: 8.1
- Database Driver & Version: 1.15, pecl install

### Description: 
I get a laravel exception:
"Package "jenssegers/laravel-mongodb" is not installed"

![image](https://user-images.githubusercontent.com/9139012/219199972-769017b8-a2d4-4bcb-9437-a9e86a961089.png)

its worth noting, the package name in composer is "jenssegers/mongodb" where the git repo is "jenssegers/laravel-mongodb" I'm pretty sure something got swapped around.

### Steps to reproduce
1. composer require jenssegers/mongodb "^3.9"
3. try to query a model

### Expected behaviour
The plugin should work without exception

### Actual behaviour
The plugin throws a module not found error

**Comment by shawnnaquin** [comment]
looks like this is the commit that broke it.
https://github.com/jenssegers/laravel-mongodb/commit/0b03010682e5041ea80177a3db2d6509da92a9a5

**Comment by alcaeus** [comment]
Whoops, mea culpa. Out of curiosity, how did you notice the exception? I'm asking because the exception should've been caught and silenced. I'm happy it got caught, but still...

**Comment by divine** [comment]
Should be fixed in #2511 and released a new version.

Thanks!

**Comment by shawnnaquin** [comment]
@alcaeus with xdebug, specifically breaking on Exceptions and Errors

**Comment by alcaeus** [comment]
Nice catch there, thank you!
