### ISSUE TITLE
Cursor timeout

### ISSUE THREAD

**Issue by wibiaris** [jenssegers/laravel-mongodb#252]
Hi, How can  implement/adjust the cursor time out?
i'm getting this error when there is a lot of data on MongoDB
"laravel.log:[2014-07-11 03:51:45] default.ERROR: exception 'MongoCursorTimeoutException' with message '192.168.203.48:27017: cursor timed out (timeout: 30000, time left: 0:0, status: 0)' in vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php:158"

**Comment by Binternet** [comment]
Is there a way I can set this timeout on a `::push` method?

**Comment by WillMac29** [comment]
I had the same issue with cursors in laravel and did the following:
           DB::transaction(function () use (....) {
                DB::statement('SET LOCAL statement_timeout = 300000;'); //5 minute timeout
                $data = $this->someQuery...

                foreach ($data as $model) {
                     //perform something on model for resecpetive row from cursor
                }
            });

**Comment by sefsinalas** [comment]
What if I'm not using query builder but Eloquent instead?
