### ISSUE TITLE
Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Grammars\Grammar

### ISSUE THREAD

**Issue by siboulet** [jenssegers/laravel-mongodb#253]
I'm trying to use the MongoDB module with the latest Laravel 4.2. I'm getting the following exception:

Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Grammars\Grammar, null given, called in /x/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1769 and defined

My Model is the User example from Laravel Eloquent documentation here: http://laravel.com/docs/eloquent

Can someone shed some light on what I'm doing wrong?

Thanks

**Comment by veerendratasol** [comment]
Hello what will be the steps to use Jenssegers\Mongodb\Model as Eloquent
I have the exact same issue.

**Comment by siboulet** [comment]
Make sure you have "use Jenssegers\Mongodb\Model as Eloquent;" in your PHP. See https://github.com/jenssegers/laravel-mongodb#eloquent

**Comment by veerendratasol** [comment]
Thanks for the reply yesterday i got the solution on your repo later :)

**Comment by veerendratasol** [comment]
@siboulet , @jenssegers 
I have added the line as suggested by siboulet but i am facing some issues can you please help me out 

I am using 2 connections in my project. One is mysql and another is mongo. I am creating separate database for each user/company.
So while register i need to create 2 database for each type mysql and mongo.
I have added the line just below the regular Eloquent
use Illuminate\Database\Eloquent\Model as Eloquent;
use Jenssegers\Mongodb\Model as Eloquent; 

User class is like 
class User extends Eloquent implements AuthenticatableContract, CanResetPasswordContract {

I want both the connection to be available in the same model. I can switch the connection to use like
DB::connection("connection name")
But i need to comment the line 
use Jenssegers\Mongodb\Model as Eloquent; 
to use mysql and comment the regular Eloquent to use mongo
use Illuminate\Database\Eloquent\Model as Eloquent;
Is there a way out to include both and then can switch the connection anytime without commenting anyone of them.
Looking forward to your support.
Sorry if i sound irrelevant i am new to Laravel

**Comment by mikehenken** [comment]
Often times you will extend a class that implements or uses Eloquent. In those cases there will often times be errors similar to this one #493. I am not sure the best course of action.

**Comment by alexgiuvara** [comment]
If someone need it:
For dual connection, mongodb as default and mysql I use a separate folder to store and run sql migrations:
`php artisan migrate --database=mysql --path=database/migrations/sql/` 
`php artisan migrate:rollback --database=mysql --path=database/migrations/sql/`

and `php artisan migrate:*` for MongoDB collections.

When I revert a migration in this way,  everything is fine
