### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by georak** [jenssegers/laravel-mongodb#2531]
Can you please add an estimation about when the release which be compatible with Laravel 10 will be ready?

Also, are there anywhere the remaining tasks for this feature?

**Comment by divine** [comment]
Duplicate of https://github.com/jenssegers/laravel-mongodb/issues/2500

**Comment by georak** [comment]
I know that it is duplicate, but in the previous thread the questioned is not answered

![image](https://user-images.githubusercontent.com/3660446/230882329-d1a0e967-db37-42d0-bffd-d7a4ecbc5c2a.png)

We need just an estimation, or what tasks should be closed to be ready in order to help with this!

**Comment by divine** [comment]
Hello,

It won't be ever stable until the brighter future of this library, see #2499.

Thanks!
