### ISSUE TITLE
Casting strings to numbers fails

### ISSUE THREAD

**Issue by avivais** [jenssegers/laravel-mongodb#2546]
- Laravel-mongodb Version: 3.9.5
- PHP Version: 8.2.6

### Steps to reproduce
1. Define model with `protected $casts` array with casting to `float` and/or `integer`
2. Create new model instance with strings values
3. Save the model

### Expected behaviour
Attributes should be casted

### Actual behaviour
Attributes are stored as strings

### Example
`StockPrice.php`
```
<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class StockPrice extends Model
{
    protected $casts = [
        'date'   => 'datetime',
        'open'   => 'float',
        'high'   => 'float',
        'low'    => 'float',
        'close'  => 'float',
        'volume' => 'int',
    ];

    protected $fillable = [
        'symbol',
        'date',
        'open',
        'high',
        'low',
        'close',
        'volume',
    ];
}
```

Using `artisan tinker` for the test:
```
> use Carbon\Carbon
> $s = new StockPrice(['symbol' => 'A', 'date' => Carbon::now(), 'volume' => '103434', 'open' => '2.3']);
[!] Aliasing 'StockPrice' to 'App\Models\StockPrice' for this Tinker session.
= App\Models\StockPrice {#6164
    symbol: "A",
    date: MongoDB\BSON\UTCDateTime {#6183
      +"milliseconds": "1686885329504",
    },
    volume: "103434",
    open: "2.3",
  }

> $s->save()
= true

> $s->refresh()
= App\Models\StockPrice {#6164
    _id: MongoDB\BSON\ObjectId {#7129
      +"oid": "648bd3d4a4e639a4a9068ca2",
    },
    symbol: "A",
    date: MongoDB\BSON\UTCDateTime {#7131
      +"milliseconds": "1686885329504",
    },
    volume: "103434",
    open: "2.3",
    updated_at: MongoDB\BSON\UTCDateTime {#7132
      +"milliseconds": "1686885332392",
    },
    created_at: MongoDB\BSON\UTCDateTime {#7133
      +"milliseconds": "1686885332392",
    },
  }
```

And, querying the DB using the shell:
```
[
  {
    _id: ObjectId("648bd3d4a4e639a4a9068ca2"),
    symbol: 'A',
    date: ISODate("2023-06-16T03:15:29.504Z"),
    volume: '103434',
    open: '2.3',
    updated_at: ISODate("2023-06-16T03:15:32.392Z"),
    created_at: ISODate("2023-06-16T03:15:32.392Z")
  }
]
```

What am I missing?

**Comment by alcaeus** [comment]
If I understand casts directly, a `float` cast for an attribute will mean that the attribute will be cast to float when read from the database, ensuring that the model type is consistent. However, when filling data attributes aren't cast - at least that's what I was able to deduce from looking at the model.

What happens when you do the same in a class extending from the default Eloquent Model instead of the MongoDB model from this library?

**Comment by avivais** [comment]
@alcaeus thanks you are totally correct

https://laravel.com/docs/10.x/eloquent-mutators#attribute-casting

> After defining the cast, the is_admin attribute will always be cast to a boolean **when you access it**, even if the underlying value is stored in the database as an integer
