### ISSUE TITLE
Call to a member function prepare() on null with DB Facade solution

### ISSUE THREAD

**Issue by alkhachatryan** [jenssegers/laravel-mongodb#2562]
- Laravel-mongodb Version: 3.8.5
- PHP Version: 8.2

### Steps to reproduce
1. Install package
2. Do needed configs as README asks
3. Create a model, set a connection
4. Create a new record throught eloquent model
5. Get lovelly error

### Expected behaviour
Have a record and database created

### Actual behaviour
Call to a member function prepare() error appears

### SOLUTION
By writing this bug report there are about 30 issues in this project with the same error and there is NO solution.
I have a model ActivityLog which is using mongodb to log everything. When creating a new log like ActitivyLog::create([...]) I have this error.
Switched to DB facade and the problem resolved.

`DB::connection('mongodb')->collection('activity_log')->insert(['asdf' => 'asdfasdf']);`

So if there is no requirement to use ORM, you easily can use DB facade for achieving your goals.

Cheers.

**Comment by alcaeus** [comment]
Can you please try to create a failing test case here? There are several tests where we create new model instances using `Model::create`, and none of them fail with the error you suggested.

If you are getting an error about a failing method call, please provide a stack trace so we can investigate how you ended up with the failing call.
