### ISSUE TITLE
Laravel 10.10 issue

### ISSUE THREAD

**Issue by mo7ameds7awky** [jenssegers/laravel-mongodb#2563]
- Laravel-mongodb Version: 3.9.5
- PHP Version: 8.1
- Database Driver & Version: v6.0.4

### Description:
I am trying to install laravel-mongodb in laravel 10.10 project and I get this issue:
`Problem 1
    - Root composer.json requires jenssegers/mongodb 3.9.5 -> satisfiable by jenssegers/mongodb[v3.9.5].
    - jenssegers/mongodb v3.9.5 requires illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.`

### Steps to reproduce
1. Install new laravel 10.10 project
2. run `composer require jenssegers/mongodb`

### Expected behaviour
Package installed

### Actual behaviour
 I get this issue:
`Problem 1
    - Root composer.json requires jenssegers/mongodb 3.9.5 -> satisfiable by jenssegers/mongodb[v3.9.5].
    - jenssegers/mongodb v3.9.5 requires illuminate/support ^9.0 -> found illuminate/support[v9.0.0, ..., v9.52.15] but these were not loaded, likely because it conflicts with another require.`

**Comment by alcaeus** [comment]
Laravel 10 support will be released in the future. Please see https://github.com/jenssegers/laravel-mongodb/issues/2500#issuecomment-1431024038.
