### ISSUE TITLE
maintain the project and support laravel v10

### ISSUE THREAD

**Issue by mshamaseen** [jenssegers/laravel-mongodb#2564]
Unfortunately, looks like this project is no longer maintained. Thanks to all the people who worked on it; your work is much appreciated.

I've started a new fork, made some fixes, and added Laravel 10 support. Hopefully, with the help of the community, we can continue on providing support for this package.

Here is the package fork:
https://github.com/mshamaseen/laravel-mongodb

I'll be happy if that fork can be merged into this.

**Comment by alcaeus** [comment]
Hi @mshamaseen! Thank you for wanting to maintain a fork of this library to bring in Laravel 10 support. MongoDB is taking over maintenance of this library, and you're welcome to submit pull requests with the changes you've made to improve Laravel support.
