### ISSUE TITLE
Support for Laravel 10

### ISSUE THREAD

**Issue by sushmarana1602** [jenssegers/laravel-mongodb#2573]
### Is your feature request related to a problem?
I am trying to install jenssegers/mongodb "^3.9", package with laravel "laravel/framework": "^10.0", but I am getting error.

### Describe the solution you'd like
Getting below errors:
Problem 1
    - Root composer.json requires jenssegers/mongodb ^3.9 -> satisfiable by jenssegers/mongodb[v3.9.0, ..., v3.9.5].
    - pragmarx/google2fa-laravel[v2.1.0, ..., v2.1.1] require laravel/framework ^5.4.36|^6.0|^7.0|^8.0|^9.0|^10.0 -> satisfiable by laravel/framework[v10.0.0, ..., v10.19.0].
    - Only one of these can be installed: illuminate/events[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.15, v10.0.0, ..., v10.19.0], laravel/framework[v10.0.0, ..., v10.19.0]. laravel/framework replaces illuminate/events and 
thus cannot coexist with it.
    - jenssegers/mongodb[v3.9.0, ..., v3.9.5] require illuminate/events ^9.0 -> satisfiable by illuminate/events[v9.0.0, ..., v9.52.15].

**Comment by alcaeus** [comment]
Please use the issue search. There are multiple issues regarding Laravel 10. Please refer to [this comment](https://github.com/jenssegers/laravel-mongodb/issues/2500#issuecomment-1431024038) for more details.
