### ISSUE TITLE
can't use findAndModify

### ISSUE THREAD

**Issue by laojin** [jenssegers/laravel-mongodb#263]
I want ceate Auto-Incrementing Sequence for _ID  Field , need use findAndModify command , may this not support, hope you add, thanks!

**Comment by Jafarili** [comment]
here's a better method for making auto increament for MongoDB (working in Laravel 5.8):
`public static function getNextSequence($collection, $field): int {
        $seq = \DB::getCollection($collection)->findOneAndUpdate(
            array('_id' => $field),
            array('$inc' => array('seq' => 1)),
            array('new' => true, 'upsert' => true)
        );
        return $seq['seq'];
    }`
