### ISSUE TITLE
Mutator can not handle array

### ISSUE THREAD

**Issue by ithuis** [jenssegers/laravel-mongodb#2634]
- Laravel-mongodb Version: 10
- PHP Version: 8.1
- Database Driver & Version: 4

### Steps to reproduce
create a mutator in a modal class that handles an array

```
  protected function roles(): Attribute
    {
        return Attribute::make(
            set: fn (array $value) => array_unique($value)
       );
}
```

### Actual behaviour
it throws an error in update methode  in file MongoDB\Laravel\Query\Builder :: 664

`str_starts_with(): Argument #1 ($haystack) must be of type string, int given`

the current code is 
`
 if (str_starts_with($key, '$')) {
                continue;
            }
`

maybe?
`
 if (is_string($key) && str_starts_with($key, '$')) {
                continue;
            }
`

**Comment by GromNaN** [comment]
Hello, your patch looks good. Could you create a PR and add a test?
