### ISSUE TITLE
`BadMethodCallException  Method MongoDB\Laravel\Schema\Grammar::compileColumnListing does not exist.` version 4

### ISSUE THREAD

**Issue by batmahir** [jenssegers/laravel-mongodb#2650]
- Laravel-mongodb Version: 4.0
- PHP Version: 8.2
- Database Driver & Version: mongo 5

### Steps to reproduce
1. Go to php artisan tinker
2. Run the command like <AnyModel>::create(['any_data' => 123]) example : 
`App\Models\Post::create(['id' => 1, 'title' => 'The Fault in Our Stars']);`
4. The error will appear :  `BadMethodCallException  Method MongoDB\Laravel\Schema\Grammar::compileColumnListing does not exist.`
5.  My model file : 
6. `<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $connection = 'mongodb';
    
    protected $collection = 'blog_posts';

    protected $guarded = ['_id', 'created_at', 'updated_at', 'deleted_at'];

}
`

### Expected behaviour
It should be successfully create and shown the created data.

### Actual behaviour
The error `BadMethodCallException  Method MongoDB\Laravel\Schema\Grammar::compileColumnListing does not exist.` is thrown

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>
<img width="840" alt="image" src="https://github.com/mongodb/laravel-mongodb/assets/20837786/cd74c10f-8377-447b-abdc-8a60fa8e4fcc">

**Comment by hans-thomas** [comment]
Your Post model must extend `MongoDB\Laravel\Eloquent\Model` base model class.
