### ISSUE TITLE
Call to undefined method compileWhereSub()

### ISSUE THREAD

**Issue by mehmetgulbilge** [jenssegers/laravel-mongodb#2656]
- Laravel-mongodb Version: 4.1
- PHP Version: 8.2
- Database Driver & Version:

BadMethodCallException
Call to undefined method MongoDB\Laravel\Query\Builder::compileWhereSub()

How can I solve this?

**Comment by mehmetgulbilge** [comment]
trace: 
#0 /application/vendor/illuminate/database/Query/Builder.php(3967): Illuminate\\Database\\Query\\Builder::throwBadMethodCallException()\n#1 /application/vendor/mongodb/laravel-mongodb/src/Query/Builder.php(1353): Illuminate\\Database\\Query\\Builder->__call()\n#2 /application/vendor/mongodb/laravel-mongodb/src/Query/Builder.php(1059): MongoDB\\Laravel\\Query\\Builder->__call()\n#3 /application/vendor/mongodb/laravel-mongodb/src/Query/Builder.php(926): MongoDB\\Laravel\\Query\\Builder->compileWheres()\n#4 /application/vendor/mongodb/laravel-mongodb/src/Query/Builder.php(678): MongoDB\\Laravel\\Query\\Builder->performUpdate()\n#5 /application/vendor/mongodb/laravel-mongodb/src/Eloquent/Builder.php(65): MongoDB\\Laravel\\Query\\Builder->update()

**Comment by hans-thomas** [comment]
@GromNaN I reverted my changes in #2658 but the pipeline is still failing.

<details><summary><b>Pipeline's first error</b>:</summary>

```
There were 93 errors:

1) MongoDB\Laravel\Tests\Casts\BooleanTest::testBool
BadMethodCallException: Call to undefined method MongoDB\Laravel\Query\Builder::compileWhereSub()

/home/runner/work/laravel-mongodb/laravel-mongodb/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:67
/home/runner/work/laravel-mongodb/laravel-mongodb/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3967
/home/runner/work/laravel-mongodb/laravel-mongodb/src/Query/Builder.php:1378
/home/runner/work/laravel-mongodb/laravel-mongodb/src/Query/Builder.php:1077
/home/runner/work/laravel-mongodb/laravel-mongodb/src/Query/Builder.php:929
/home/runner/work/laravel-mongodb/laravel-mongodb/src/Query/Builder.php:681
/home/runner/work/laravel-mongodb/laravel-mongodb/src/Eloquent/Builder.php:65
/home/runner/work/laravel-mongodb/laravel-mongodb/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1213
/home/runner/work/laravel-mongodb/laravel-mongodb/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1130
/home/runner/work/laravel-mongodb/laravel-mongodb/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:990
/home/runner/work/laravel-mongodb/laravel-mongodb/tests/Casts/BooleanTest.php:26
```
</details>

Also, this is reported in this issue. I think there is a problem in the `4.1` branch.

**Comment by hans-thomas** [comment]
I didn't have this error until I updated the dependencies. I still don't know what causes this issue.

**Comment by hans-thomas** [comment]
Okay, I solved this. I will make a PR after a little rest😬
