### ISSUE TITLE
🍃 Meet the MongoDB PHP Team

### ISSUE THREAD

**Issue by GromNaN** [jenssegers/laravel-mongodb#2662]
@alcaeus @jmikola and @GromNaN will be doing a live PHP Office Hours event, discussing the MongoDB driver and framework integrations.
https://www.youtube.com/watch?v=rLkoiZGhUq0

<img width="1324" alt="image" src="https://github.com/mongodb/laravel-mongodb/assets/400034/e6ec0a55-3e22-426a-b5ef-df2e14c7ed9c">

**Comment by hans-thomas** [comment]
@alcaeus @jmikola @GromNaN
Thank you guys❤️ such an honor that professional people like you mentioned me and approved my work👌
I'm really proud of having an effect here🥳
