### ISSUE TITLE
Did you mean Jenssegers\Mongodb\Query\Builder::compileWhereRaw() ?

### ISSUE THREAD

**Issue by habibendris** [jenssegers/laravel-mongodb#2673]
I'm getting a message in Laravel saying

**Call to undefined method Jenssegers\Mongodb\Query\Builder::compileWhereInRaw()**
**Did you mean Jenssegers\Mongodb\Query\Builder::compileWhereRaw() ?**

### Steps To Reproduce

Post model extended from Laravel Eloquent Model (MySQL CONNECTION)
Comment model extended from LaravelMongoDB Model (MongoDB CONNECTION)

hasMany Relationship on the Post Model

> 
> public function comments() {
>     return $this->hasMany(Comment::class);
> }
>

**Comment by GromNaN** [comment]
Hello @habibendris. Given the namespace of the classes, you are using an old version of this package. We did a lot of bug fixes on the query builder in `mongodb/laravel-mongodb` v4.0.
You should upgrade to Laravel 10 if you can.

Regarding your issue, do you `use HybridRelations` in your `Comment` class?
We have tests that cover the hybrid relation you describe here (`User` has many `SqlBook`, see [`HybridRelationsTest::testSqlRelations()`](https://github.com/mongodb/laravel-mongodb/blob/4.0/tests/HybridRelationsTest.php)).

**Comment by habibendris** [comment]
Thank you @GromNaN I have forgotten to include HybridRelations trait
