### ISSUE TITLE
Call to undefined method MongoDB\Laravel\Query\Builder::compileWhereSub()

### ISSUE THREAD

**Issue by IribarrenWeb** [jenssegers/laravel-mongodb#2700]
- laravel/framework: 10.38
- mongodb/laravel-mongodb: 4.1.0

I got this error "MongoDB\Laravel\Query\Builder::compileWhereSub()" when i try to run a subQuery like this: 

`$query->where('filters', 'elemMatch', function ($elemMatchQuery) use ($searchBy, $value) {
            $elemMatchQuery->where([
                'search_by' => $searchBy,
                'value' => $value,
            ]);
        });`

How can i solve this?

**Comment by diego-rlima** [comment]
Hi @GromNaN

I saw that you merged the fix to the 4.1 branch [2 weeks ago](https://github.com/mongodb/laravel-mongodb/pull/2717#event-11748621812), but there was no release afterwards. When will this fix be available in a release? 🤔

**Comment by GromNaN** [comment]
I've just released [4.1.2](https://github.com/mongodb/laravel-mongodb/releases/tag/4.1.2)
