### ISSUE TITLE
Need to support upsert function in Laravel 10

### ISSUE THREAD

**Issue by zyz954489346** [jenssegers/laravel-mongodb#2718]
- Laravel-mongodb Version: 4.1
- PHP Version: 8.3
- Database Driver & Version: 4

### Description:
The implementation of Cache's put function is modified to db's upsert function in Laravel10.
![image](https://github.com/mongodb/laravel-mongodb/assets/23162012/2ddc8705-7cfc-4315-81b6-46d3e51834ab)

### Steps to reproduce
When the driver of cache is changed to mongodb，This will lead to an error. Such as this:
```php
 \Cache::store('mongdb-conn')->forever($key, $val);

// or 
 \Cache::store('mongdb-conn')->put($key, $val);

```

The error is: This database engine does not support upserts.

**Comment by GromNaN** [comment]
Thanks for reporting this issue. It's tracked in Jira: [PHPORM-141](https://jira.mongodb.org/browse/PHPORM-141)
