### ISSUE TITLE
 Transaction already in progress

### ISSUE THREAD

**Issue by nicohell** [jenssegers/laravel-mongodb#2720]
- Laravel-mongodb Version: 4.1
- PHP Version: 8.2.15
- Database Driver & Version:  db version v6.0.13 
- PHP MongoDB extension version	**1.17.2**

### Description:
Using firstOrCreate() in a transaction returns an error 

### Steps to reproduce
    $mongodb = DB::connection('app');
    $mongodb->beginTransaction();
    // user does not exist and will be created
    \App\Models\User::firstOrCreate(['username' => 'johncarpenter', 'name' => 'carpenter', 'email' => 'john@example.com']);
    $mongodb->rollBack();

### Expected behaviour
Manage transaction and commit or rollBack 

### Actual behaviour
retuns error :
local.ERROR: MongoDB\Driver\Exception\RuntimeException: Transaction already in progress in vendor/mongodb/mongodb/src/Operation/WithTransaction.php:60

### Notes 
 create() works fine
 firstOrCreate() and updateOrCreate() do work for updates but do not work for creation as they start a transaction in vendor/mongodb/mongodb/src/Operation/WithTransaction.php

### Hack 
We went through adding a test in vendor/mongodb/mongodb/src/Operation/WithTransaction.php

```
 if (!$session->isInTransaction()) {
    $session->startTransaction($this->transactionOptions);
} 
```

**Comment by bisht2050** [comment]
Tracked with [PHPORM-139](https://jira.mongodb.org/browse/PHPORM-139).

**Comment by GromNaN** [comment]
Hello @nicohell, I worked on an implementation of `Model::firstOrCreate()` using the MongoDB operation `findOneAndUpdate` (see https://github.com/mongodb/laravel-mongodb/pull/2742). Would it solve your issue?

**Comment by nicohell** [comment]
Hello @GromNaN, I don't really understand the implications of #2742 and what would make a difference with `findOneAndUpdate` ?
Will your implementation of `Model::firstOrCreate()` using the MongoDB operation `findOneAndUpdate`  manage existing transactions ?

**Comment by GromNaN** [comment]
The initial issue it that MongoDB doesn't support nested transactions, and Laravel Eloquent Query Builder tries to initiate a transaction [in the `createOrFirst` method](https://github.com/laravel/framework/blob/6c27ca43dbcfd232813ca5aba8ad3c80405ba9b1/src/Illuminate/Database/Eloquent/Builder.php#L584).

By changing the implementation, we avoid this nested transaction while providing an optimized implementation.

**Comment by nicohell** [comment]
Do you mean that your implementation will not try to start a new transaction ?

**Comment by GromNaN** [comment]
> Do you mean that your implementation will not try to start a new transaction ?

Yes, because the `findOneAndUpdate` operation is atomic, so it doesn't need a transaction.

**Comment by nicohell** [comment]
Hi @GromNaN 

After updating to 4.2.0 we were happy to see that transactions are working fine, 

Unfortunately "created_at" and "updated_at" fields are no longer automatically inserted in new records using firstOrCreate, createOrFirst, updateOrCreate, ...

This code creates new record with  "created_at" and "updated_at" fields :
```
$obj = new \App\Models\Parameter; // instantiate model
$obj->created_by = 'nico';
$obj->save();
```
It breaks between 4.1.3 and 4.2.0

Regards.
