### ISSUE TITLE
Connection string is missing the option to create dsn as a SRV dsn

### ISSUE THREAD

**Issue by ingLomeland** [jenssegers/laravel-mongodb#2724]
- Laravel-mongodb Version: 4.0
- PHP Version: 8.2
- Database Driver & Version: Mongodb atlas

### Description:
In the documentation it says you can either use dsn env or pass host, username, password etc as their own env variables and it builds the string automatically. This works great for local development, but not if its required to use a SRV string

### Steps to reproduce
1. Add connection details to mongodb atlas as host, username, password etc 
2. Try to connect

### Expected behaviour
Should build the dsn string correctly

### Actual behaviour
It does not, because it builds the string as a standard connection string "mongodb://hostname.....". To connect to mongodb atlas you need to use a SRV string which looks like this "mongodb+srv://username:password@hostname......"

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by GromNaN** [comment]
Hello @ingLomeland, 

Indeed we could add a `scheme` option and use it in the `MongoDB\Laravel\Connection` class.
https://github.com/mongodb/laravel-mongodb/blob/cff277384ca0d8da45663c00a494ea84cafd0459/src/Connection.php#L256

To make sure I understand your needs, why don't you use [`DB_URI`](https://www.mongodb.com/docs/drivers/php/laravel-mongodb/current/quick-start/configure-mongodb/#set-the-connection-string-in-the-database-configuration)? It allows you to use just a single environment variable for your configuration.

**Comment by ingLomeland** [comment]
I didnt want to use DB_URI because then the password would be stored in clear text. But I figured out later that is you specify a password in the DB_PASSWORD it replaces the one in the URI. So now I can use the URI and just write "randompassword" and replace it with the DB_PASSWORD. The documentation could clarify this about the SRV string and standard string though :)

**Comment by GromNaN** [comment]
The username and password are not required in the DSN:

```php
return [
    'connections' => [
        'mongodb' => [
            'driver' => 'mongodb',
            'dsn' => 'mongodb+srv://hostname',
            'username' => env('MONGODB_USERNAME'),
            'password' => env('MONGODB_PASSWORD'),
            'database' => env('MONGODB_DATABASE', 'mydb'),
        ],
    ],
];
```
