### ISSUE TITLE
seperate read, write connection not working

### ISSUE THREAD

**Issue by zaber04** [jenssegers/laravel-mongodb#2728]
- Laravel-mongodb Version: 4.1.1
- PHP Version: 8.3.0
- Database Driver & Version:

### Description:

    'mongodb' => [
        'read'     => [
            'host' => [env('DB_HOST', 'localhost')],
        ],
        'write'    => [
            'host' => [env('DB_HOST', 'localhost')],
        ],
        'driver'   => 'mongodb',
        'port'     => env('DB_PORT', 27017),
        'database' => env('DB_DATABASE'),
        'username' => env('DB_USERNAME'),
        'password' => env('DB_PASSWORD'),
        'options'  => [
            'database' => 'admin' // sets the authentication database required by mongo 3
        ],
    ],

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by GromNaN** [comment]
You can have multiple connections for multiple models, but you can't use distinct connections for read and write on the same models. MongoDB clusters behave like a single server for the connection ([Replica Set Read and Write Semantics](https://www.mongodb.com/docs/manual/applications/replication/)).

By default, the `ReadPreference` is set to `primary` ([`MongoDB\Driver\Manager::__construct()` options](https://www.php.net/manual/fr/mongodb-driver-manager.construct.php)). You can send read queries to the secondary replica, by setting a different value to the `readPreference` option.

```php
'mongodb' => [
    'driver'   => 'mongodb',
    'port'     => env('DB_PORT', 27017),
    'database' => env('DB_DATABASE'),
    'username' => env('DB_USERNAME'),
    'password' => env('DB_PASSWORD'),
    'options'  => [
        'readPreference' => \MongoDB\Driver\ReadPreference::SECONDARY_PREFERRED,
    ],
],
```
