### ISSUE TITLE
Laravel 11 Support?

### ISSUE THREAD

**Issue by dimonets** [jenssegers/laravel-mongodb#2769]
Laravel 11 is out. Can you include its support in composer configuration?

**Comment by bisht2050** [comment]
The required work is done and the 4.2 release that delivers Laravel 11 support should happen very soon.

**Comment by bisht2050** [comment]
Version [4.2](https://github.com/mongodb/laravel-mongodb/releases/tag/4.2.0) released that adds Laravel 11 support.
