### ISSUE TITLE
toSql() Alias from toMql()

### ISSUE THREAD

**Issue by dndarksan** [jenssegers/laravel-mongodb#2797]
### Is your feature request related to an issue?
In some plugins such as rappasoft/laravel-liveware-tables the debug uses the toSql() function and when I used it at that time it gave an error

### Describe the solution you would like
It could be that they aliased the toMql() function to use it as toSql() and then that exception would not arise.

### Additional context
In my case, what I did was make a fork of rappasoft/laravel-liveware-tables to be able to use it with mongodb, because it also makes several somewhat strange functions and I changed the function from toSql() to toMql()

**Comment by GromNaN** [comment]
`toSql` returns a string, while `toMql` returns an array. Would it be useful if `toSql` returned a JSON string representing the BSON query?

**Comment by dndarksan** [comment]
Yes, It could work, the only thing is that it don't respond with a throw exception when using `toSql()`, I solved it in the fork using exactly the same response as `toMql()`

**Comment by GromNaN** [comment]
See https://github.com/mongodb/laravel-mongodb/pull/2931

**Comment by GromNaN** [comment]
Closing as won't fix. See https://github.com/mongodb/laravel-mongodb/pull/2931#discussion_r1591313756

Please submit compatibility fixes to `rappasoft/laravel-liveware-tables`.
