### ISSUE TITLE
Unsupported Driver [mongodb] when updating to v2

### ISSUE THREAD

**Issue by chrissm79** [jenssegers/laravel-mongodb#280]
Just updated to v2 (nice new features btw!). I was able to run db:seed without a problem. However, when I attempted to load the site I'm getting a 

```
InvalidArgumentException 
Unsupported driver [mongodb]
```

Do I need to make a change somewhere else when updating?

``` php
<?php
// app/config/database.php
return [
    ...
    'default' => 'mongodb',

    'connections' => [

        'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => 'localhost',
            'port'     => 27017,
            'database' => 'laravel_nuwavefit',
            'username' => '',
            'password' => ''
        ],
    ],
    ...
]
```

**Comment by jonathanpmartins** [comment]
Same problem here! Don't know why @jenssegers

**Comment by jonathanpmartins** [comment]
@jenssegers Resolved with this Answer:
http://stackoverflow.com/questions/29050410/trouble-with-configuring-users-and-connecting-to-mongo-with-php/29052015#29052015

**Comment by jalon726** [comment]
in config/app.php, add mongo provider
