### ISSUE TITLE
How to support $not operator with regex?

### ISSUE THREAD

**Issue by joe2tw** [jenssegers/laravel-mongodb#282]
<code>
db.inventory.find( { item: { $not: /^p.*/ } } )
</code>

How can I do this query in laravel-mongodb?

Thanks.

**Comment by vijay-dhokrat** [comment]
Hi @jenssegers what will be the max limit for ->take(10)
I want all data for regex

**Comment by psanjib** [comment]
Hi @jenssegers i have wriiten a simple query it's not working 
$comments = new Comment;
$query = $comments::where('identifier', 'REGEXP', '8183|81600')->get();

It returns all record. It should return only 2 record. i have tested by writing Sql Query
Raw Sql query - SELECT * FROM `Test` where title REGEXP '8183|81600';  It is working fine.

Please find the attached image,  records available in the DB.
![table-data](https://user-images.githubusercontent.com/1003735/57692122-9c70f880-7663-11e9-9ee9-fa9b48c0aa7c.png)
