### ISSUE TITLE
Distinct count not counting distinct values

### ISSUE THREAD

**Issue by MartijnThomas** [jenssegers/laravel-mongodb#283]
I'm having an issue with the `distinct`.

When I do the following:
`Model::distinct('status.user.id_str')->count()`
the total number of documents (242) are returned not the number of documents with a distinct user id (209).

When I run:
`Model::distinct('status.user.id_str')->get()`
Only documents with a distinct user_id are returned.

I'm not sure where this goes wrong, but I have a feeling that it is not behaviour I should get.

**Comment by cachila** [comment]
Sorry for reopening this but I am having the same problem.
->distinct('id_str')->count() does not return the expected.

**Comment by diogolast** [comment]
I am having the same problem, the solution I am using is 

`$count = Model::distinct('status.user.id_str')->get();`
`echo count($count);`

but this is not performatic. Anyone founds a properly solution???

**Comment by cachila** [comment]
I could solve it by using
`DB::connection('mongodb')->collection('col')->raw(function($collection) {
            return $collection->aggregate(
                        ...
            );
)};`

The query I used was based in this great article [http://www.forwardadvance.com/course/mongo/mongo-aggregation/aggregation-count], you will have to convert JSON objects to `key => values` arrays.

Hope you make this work.

**Comment by diogolast** [comment]
@cachila thanks, saved my day this great article.

**Comment by lechuhuuha** [comment]
query where with distinct count still not working to this day.

`$email->clickLogs()->distinct('message_id')->get()` 
turn into this mongo query `click_logs.distinct("message_id",{"trackingLog.email_id":1384})`

but this query `$email->clickLogs()->distinct('message_id')->count()`
get turn into this query `click_logs.count({"trackingLog.email_id":1384})` 

this is my relationship

```
    public function clickLogs()
    {
        return \EMA\Model\MongoDb\ClickLog::where('trackingLog.email_id', $this->id);
    }
```

anyone know how can keep the relation and use its with distinct count?
