### ISSUE TITLE
Polymorphic One to One (MorphOne) Relationship [Feature Request] 

### ISSUE THREAD

**Issue by mrraindrop555** [jenssegers/laravel-mongodb#2839]

**Comment by GromNaN** [comment]
This is already supported using `morphOne()`.

Could you describe what you'd like to do, what you've tried and any errors you've encountered?

**Comment by mrraindrop555** [comment]
I tried importing the relationship but found VS code keep highlighting this problem.
Undefined type 'MongoDB\Laravel\Relations\MorphOne'

It works with other polymorphic relationships.

**Comment by GromNaN** [comment]
You can use `Illuminate\Database\Eloquent\Relations\MorphOne`.
