### ISSUE TITLE
Delete/Destroy not working on doubly embedded objects.

### ISSUE THREAD

**Issue by nateemerson** [jenssegers/laravel-mongodb#285]
Right now I'm working with a two layer embedded hierarchy, I have projects, which have an embedded collection of locations, which themselves have an embedded collection of items. My models are set up as so:

```php
class Project extends Eloquent {
    public function locations()
    {
        return $this->embedsMany('Location');
    }
}
class Location extends Eloquent {
    public function items()
    {
        return $this->embedsMany('Item');
    }
}
class Item extends Eloquent { }
```

Now I am trying to delete all items from a location, and I cannot seem to do it. I tried this using three methods:

1. `$location->items()->delete();`
2. Iterate through all items and delete via `$item->delete()`
3. Iterate through all items and delete via `$location->items()->destroy($item)`

None of these methods worked, and the first method actually created an empty items array on the Project document. It would seem that it's going to the top level parent relation for some reason.

I'm in a bit of a hurry right now so I'm sorry for not getting you more information. If you are not able to reproduce please let me know what other information I could offer to help you reproduce.

Also, I want to sincerely thank everyone who contributes to this project. This is an awesome library and I would not be able to work with laravel+mongo otherwise. <3

**Comment by rmb938** [comment]
I am having the same exact issue. 

Also to go off of the example given. When I add an Item to a Location without the "items" key existing it creates the key as a document containing sub documents instead of a list containing sub documents. 

So I end up with

```
{
    locations: [
        {
            items: {"0": {}, "1": {}, "2": {}}
        }
    ]
}
```

Instead of 

```
{
    locations: [
        {
            items: [{}, {}, {}]
        }
    ]
}
```

**Comment by rmb938** [comment]
After googling around a bit I was able to find this 

http://stackoverflow.com/questions/14860247/why-is-my-php-array-being-saved-to-mongodb-as-an-object-then-being-retrieved-as

This could be the issue but I don't know enough about php to figure out how to fix it my self. Any idea? @jenssegers

**Comment by rmb938** [comment]
Ok so I found the fix. It seems like you have to save the parent document after you save the child document. You also have to specifically set the array to a empty array for it to insert into mongo as an array instead of an object.
