### ISSUE TITLE
Feature Request: ReferencesMany/ReferencedBy

### ISSUE THREAD

**Issue by nuwave** [jenssegers/laravel-mongodb#286]
I have run into a few instances where I have a many-to-many relationship set up but I would like the embedded ids to be added to one model. For instance, I have many to many relationship set up between emails and users. I would prefer not to add a list of email ids to the user as it will grow to well over a several thousand (in my application), while the list of users on the email model will usually never exceed 10.

I attempted to create this set up by using a hasMany on the User and belongsToMany on the Email. However, when saving the email, the email id is still stored on the user. I have also tried to push the id to "user_ids" on the Email, but eager loading doesn't work when doing so.

It would be great if a ReferencesMany (Email in this example) and ReferencedBy (User) could be implemented so the list of ids is only embedded on the desired model.

v2.0 is amazing btw, great work on this package!!

**Comment by Oleg-Arkhipov** [comment]
@jenssegers why did you close this issue?
Do you consider this feature unnecessary at all or is its implementation would be too hard?
