### ISSUE TITLE
Soft-delete doesn't seem to be working

### ISSUE THREAD

**Issue by bipinu** [jenssegers/laravel-mongodb#291]
- We've softDeletes() in the migration
- The model uses SoftDeletingTrait, and mentions the name of date field.
- I've verified the actual document inside MongoDB has a deleted_at entry, with date-timestamp
  However, calling ModelName::all(), still returns the soft-deleted field. 

Thanks for the great work. Really appreciate it!

**Comment by AravindhNextbrain** [comment]
> I have not found this issue, added Jenssegers\Mongodb\Eloquent\SoftDeletingTrait not the laravel one, deleted an entry and found the deleted_at key, listing all entries via all(); returns all except with deleted_at.
> so it worked for me.
> ![screenshot_1](https://cloud.githubusercontent.com/assets/3740671/4030289/4fe29b24-2c5b-11e4-867f-3a29977417f6.png)

Yeah ! Its fixed my issue. I too faced same problem.

Before i called trait named => use SoftDeletes;
This one fixed  => use SoftDeletingTrait

Thank you
