### ISSUE TITLE
[Feature Request] getChanges() not supported

### ISSUE THREAD

**Issue by masterbater** [jenssegers/laravel-mongodb#2936]
Call to a member function getChanges() on int
```php
 $update = User::where('_id', $request->userId)->update($validatedData);
 return $update->getChanges();
```

**Comment by GromNaN** [comment]
The function `Illuminate\Database\Query\Builder::update()` returns an `int` in Laravel (see [the code](https://github.com/laravel/framework/blob/869c1d9bfdeda586a62658f19b35a88e543c23d1/src/Illuminate/Database/Query/Builder.php#L3700-L3706)).

The method `getChanges()` exists and is correctly updated when called on a `Model` instance.

```php
$user = User::create(['name' => 'John Doe']);

$updated = User::where('name', 'John Doe')->update(['name' => 'Jane Doe']);
var_dump($updated); // 1

$updated = $user->update(['name' => 'Jimmy Doe']);
var_dump($updated); // 1
var_dump($user->getChanges()); // array(name => Jimmy Doe, updated_at => UTCDateTime)
```

**Comment by masterbater** [comment]
> Call to a member function getChanges() on int
> 
> ```
>  $update = User::where('_id', $request->userId)->update($validatedData);
>  return $update->getChanges();
> ```

I dont understand why this doesnt work, do I need to do first() then update?
With your example you 
why not
```php
$updated = User::where('name', 'John Doe')->update(['name' => 'Jimmy Doe']);
var_dump($updated); // 1
var_dump($updated->getChanges());
```

**Comment by GromNaN** [comment]
The `update` method returns an `int`, this will not change and we can't add a method `getChanges` on an `int`.

Yes, you must get the model instance first.

```php
$user = User::where('name', 'John Doe')->first();
$updated = $user->update(['name' => 'Jimmy Doe']);
var_dump($updated); // 1
var_dump($user->getChanges());
```

**Comment by masterbater** [comment]
> The `update` method returns an `int`, this will not change and we can't add a method `getChanges` on an `int`.
> 
> Yes, you must get the model instance first.
> 
> ```
> $user = User::where('name', 'John Doe')->first();
> $updated = $user->update(['name' => 'Jimmy Doe']);
> var_dump($updated); // 1
> var_dump($user->getChanges());
> ```

Thanks
