### ISSUE TITLE
dynamically set collection

### ISSUE THREAD

**Issue by MartijnThomas** [jenssegers/laravel-mongodb#296]
Hi, I'd like to set the collection of the model in the controller (or in this case an artisan command).

I tried `MyMongoDBModel::collection('abc_'.$id.'_cdf')->create($array)` but then I get the following error:

```
[BadMethodCallException]
Call to undefined method Jenssegers\Mongodb\Query\Builder::collection()
```

Is there a way to set the collection dynamically?

**Comment by Katerou22** [comment]
@jenssegers it working on get data , what about creation? not working in creation!
