### ISSUE TITLE
Geo near

### ISSUE THREAD

**Issue by supreetssethi** [jenssegers/laravel-mongodb#297]
HI how can i get near function .
something like this in mongo 
db.places.aggregate([ { $geoNear: { near: [11.7681, 40.6819], distanceFi
eld: "distance", spherical: true,maxDistance:7,distanceMultiplier:3959 } } ])

up and running in my laravel framework

**Comment by guicunha** [comment]
$proximos = Perfil::raw(function($collection)
        {
           return $collection->aggregate(
               [
                '$geoNear' => [
                    'near' => [
                        'coordinates' => [-19.927954,-43.938203]
                    ],
                    'sphercial' => 'true'
                ]
            ]);
        });

InvalidArgumentException in Aggregate.php line 93:
$pipeline is not a list (unexpected index: "$geoNear")

**Comment by RafaelPlantard** [comment]
```
'gps_location' => [
	'$nearSphere' => [
		'$geometry'    => [
			'type'        => 'Point',
			'coordinates' => [
				$latitude,
				$longitude
			]
		],
		'$maxDistance' => $rangeInKm * self::meters_per_km
	]
]
```

**Comment by skeezus** [comment]
If anyone is having problems with their index, make sure you know if your database has been configured using GeoJSON or Legacy Coordinate Pairs. As you might suppose, GeoJSON is an object that can have several properties whereas legacy coordinate pairs is just a pair of coordinates.
More on this: https://docs.mongodb.com/manual/reference/glossary/#term-legacy-coordinate-pairs 

I've inherited a database with legacy pairs and below is some code which may help. I haven't tested it extensively but it appears to be working. Scroll to the very bottom of this mongo doc for the function that got me on the right track: https://docs.mongodb.com/manual/reference/operator/query/near/#op._S_near

$query = Shop::raw(function($collection)
                {
                    return $collection->find([
                        'loc' => [
                            '$near' => [
                             -105.0376084, 
                             39.7620472
                            ]
                        ]
                    ]);
                });

**Comment by kertul** [comment]
` User::raw(function($collect) use($radius){
            return $collect->aggregate([
                [
                    '$geoNear' => [
                        'near' => [
                            'type' => 'Point',
                            'coordinates' => [110.410375, -7.781981]
                        ],
                        '$maxDistance' => $radius,
                        'distanceField' => 'dist.calculated',
                        'spherical' => true
                    ]
                ]
            ]);
        });`

I hope this helps
