### ISSUE TITLE
[Feature Request] Use transaction in AWS DocumentDB 

### ISSUE THREAD

**Issue by rafael-magno** [jenssegers/laravel-mongodb#2979]
If I use DB::transaction in AWS DocumentDB this error is thrown: "Feature not supported: Causal consistency".

The way I resolved this was by duplicating the ManagesTransactions trait and making the modification to the getSessionOrCreate method, adding a option on startSession method. As shown below:

```php
    private function getSessionOrCreate(): Session
    {
        if ($this->session === null) {
            $this->session = $this->getMongoClient()->startSession(['causalConsistency' => false]);
        }

        return $this->session;
    }
```

To resolve it definitively, I suggest passing one more parameter ($sessionOptions for example), in the ManagesTransactions::getSessionOrCreate and ManagesTransactions::transaction methods

**Comment by bisht2050** [comment]
AWS DocumentDB is a separate implementation from the MongoDB server. DocumentDB has a number of [compatibility differences](https://www.isdocumentdbreallymongodb.com/) as compared to MongoDB.
If your issue isn’t reproducible with an actual MongoDB deployment, there isn’t much we can do to investigate. You could try using a free tier [MongoDB Atlas cluster](https://www.mongodb.com/products/platform/atlas-database) to compare behaviour. For support using DocumentDB I suggest posting on the AWS Forums.
