### ISSUE TITLE
Can't canonicalize query: BadValue $geometry is required for geo near query

### ISSUE THREAD

**Issue by GoldenZero** [jenssegers/laravel-mongodb#299]
I'm getting the error:
Can't canonicalize query: BadValue $geometry is required for geo near query

for following code:
$query->where('location', 'near',array($criteria['lng'], $criteria['lat']))->get()

**Comment by askmatey** [comment]
Please clarify your specific problem or add additional details to highlight exactly what you need. As it's currently written, it’s hard to tell exactly what you're asking.

Otherwise, this issue should be closed.

**Comment by WenXuanYuan** [comment]
<pre>
where('position', 'near', [
            '$geometry' => [
                'type' => 'Point',
                'coordinates' => [73, -51],
            ],
            '$maxDistance' => 10000000,
        ])
</pre>
