### ISSUE TITLE
hasOne() hasMany() relation not working with Dbref column

### ISSUE THREAD

**Issue by cemil91** [jenssegers/laravel-mongodb#3025]
- Laravel-mongodb Version: 4.4
- PHP Version: 8.1
- Database Driver & Version: 1.19

**Comment by GromNaN** [comment]
That's exact. Laravel and Eloquent is an opinionated framework: the relations use a single `id` field because that's how it's implemented with SQL databases. We can't change this behavior while extending the Eloquent classes.
