### ISSUE TITLE
Eloquent Scope does not satify MongoDB\Laravel\Eloquent\Model

### ISSUE THREAD

**Issue by masterbater** [jenssegers/laravel-mongodb#3026]
- Laravel-mongodb Version: 4.5.0
- PHP Version: 8.3
- Database Driver & Version:

### Description:
create scopes , MongoDB\Laravel\Eloquent\Model Model does not satisfy the type 

### Steps to reproduce
```php
<?php

namespace App\Models\Scopes;

use Illuminate\Database\Eloquent\Builder;
use MongoDB\Laravel\Eloquent\Model as Model;
use Illuminate\Database\Eloquent\Scope;

class TestingLang implements Scope
{
    /**
     * Apply the scope to a given Eloquent query builder.
     */
    public function apply(Builder $builder, Model $model): void
    {
        //
    }
}

```
<img width="1072" alt="image" src="https://github.com/mongodb/laravel-mongodb/assets/26339988/cbde98b9-dd2b-4669-a093-f3d7b074a5d2">

**Comment by GromNaN** [comment]
In PHP, you can't use a more specific class for a parameter when you override a method. That's explained in [Covariance and Contravariance](https://www.php.net/manual/en/language.oop5.variance.php).

You need to follow the signature of the parent class. You can assert the type in the method:

```php
namespace App\Models\Scopes;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Scope;
use MongoDB\Laravel\Eloquent\Model as MongoModel;
use InvalidArgumentException;

use function assert;

class TestingLang implements Scope
{
    /**
     * Apply the scope to a given Eloquent query builder.
     */
    public function apply(Builder $builder, Model $model): void
    {
        assert($model instanceof MongoModel, new InvalidArgumentException('Model must be an instance of ' . MongoModel::class));
    }
}
```
