### ISSUE TITLE
[Feature Request] Support converting arrow into dot notation in where 

### ISSUE THREAD

**Issue by masterbater** [jenssegers/laravel-mongodb#3039]
### Is your feature request related to a problem?
https://github.com/filamentphp/filament/blob/be6290f0d01d3b589274284592e7e3c777e674df/packages/notifications/src/Livewire/DatabaseNotifications.php#L87

This line causes issue like  This database engine does not support JSON operations.
`return $this->getUser()->notifications()->where('data->format', 'filament');`

This package could internally convert data->format into data.format to work?

This doesnt state that WhereJson** queries is not supported or arrow queries 
```
The following Eloquent methods are not supported in Laravel MongoDB:

toSql()

toRawSql()

whereColumn()

orWhereColumn()

whereFulltext()

groupByRaw()

orderByRaw()

inRandomOrder()

union()

unionAll()

havingRaw()

having()

havingBetween()

orHavingRaw()

whereIntegerInRaw()

orWhereIntegerInRaw()

whereIntegerNotInRaw()

orWhereIntegerNotInRaw()
```

**Comment by masterbater** [comment]
Is this going to be included in 5.0 or later on?

**Comment by GromNaN** [comment]
Sure, we can convert `->` to `.`. Probably near this line:
https://github.com/mongodb/laravel-mongodb/blob/47662745dee06148397d08cc06559be5a71d26a1/src/Query/Builder.php#L1172C14-L1172C33

Do you want to open a pull request with some tests?

**Comment by GromNaN** [comment]
Hello,
I've implemented the requested feature. Would you like to try it out? #3170

**Comment by masterbater** [comment]
> Hello, I've implemented the requested feature. Would you like to try it out? #3170

Thanks
