### ISSUE TITLE
Incompatibility with 'php artisan optimize'

### ISSUE THREAD

**Issue by forgottenleaf** [jenssegers/laravel-mongodb#305]
I tried adding all of this project's classes (within the composer vendor/ folder) to app/config/compile.php and then running   
`php artisan optimize`

Even though I tried removing some of the conflicting class names from compile.php, I got errors like:

```
PHP Fatal error:  Cannot use Illuminate\Database\Eloquent\Collection as Collection because the name is already in use in /var/www/html/laravelfiles/bootstrap/compiled.php on line 11132
```

```
PHP Fatal error:  Cannot redeclare class Jenssegers\Mongodb\Relations\EmbedsOneOrMany in /var/www/html/laravelfiles/bootstrap/compiled.php on line 12309
```

**Comment by nandwabee** [comment]
I am getting the same error on centos 6,PHP 5.4.

'Cannot use Illuminate\Database\Eloquent\Collection as Collection because the name is already in use'

Same code runs on Ubuntu although on php 5.5

**Comment by askmatey** [comment]
This issue should be closed, since it was caused by a problem that can no longer be reproduced or a simple typographical error.
