### ISSUE TITLE
[Feature Request]  Add whereLike clause to query builder 

### ISSUE THREAD

**Issue by masterbater** [jenssegers/laravel-mongodb#3080]
https://github.com/laravel/framework/pull/52147

**Comment by GromNaN** [comment]
The "like", "not like", "ilike" and "not ilike" are supported. Have you tried if the new methods already work?

**Comment by masterbater** [comment]
> The "like", "not like", "ilike" and "not ilike" are supported. Have you tried if the new methods already work?

Hello @GromNaN, no I havent. Its better if we can add test for this new method.
