### ISSUE TITLE
Ardent for Moloquent

### ISSUE THREAD

**Issue by davemathews** [jenssegers/laravel-mongodb#309]
@jenssegers great package and we are using it currently, as well as Ardent for our Eloquent packages.  Ardent as you know extends Eloquent by default.  Have you given any thought to how we could implement Ardent with Moloquent? Thanks

**Comment by gidomanders** [comment]
You could use https://github.com/bmcmurray/ardent-mongodb, it's an Ardent fork that uses Moloquent.

**Comment by askmatey** [comment]
This issue should be closed, since it was caused by a problem that can no longer be reproduced or a simple typographical error.
