### ISSUE TITLE
Issue with Soft-delete with orWhere

### ISSUE THREAD

**Issue by luis-deguzman** [jenssegers/laravel-mongodb#310]
This issue was first reported in issue #43 but was closed and not resolved.

I have additional information re the issue to see if someone can help in the resolution.

Here's the query:

$row = Feature::where('name', '=', $input['name'])->orWhere('display_name', '=', $input['display_name'])->get();

We have a sql logger and this what is showing up in our log:

features.find({"$and":[{"deleted_at":null},{"name":"sun_roofs"}],"$or":[{"display_name":"Sun Roof"}]})

I then changed the query to:

$row = Feature::orWhere('name', '=', $input['name'])->orWhere('display_name', '=', $input['display_name'])->get();

The log shows:

features.find({"$or":[{"deleted_at":null},{"name":"sun_roofs"},{"display_name":"Sun Roof"}]})

In both queries, the "deleted_at" clause is not set properly - and it is resulting in wrong results being returned.

**Comment by arcadas** [comment]
+1

**Comment by arcadas** [comment]
I round the problem by this not too nice solution:
```php
Book::whereNotIn('user_id', [0])
  ->orWhere('user_id', $userId)
  ->orWhereIn('group_id', $groups)
  ->get()
```
```js
book.find{{"$and":[
  {"deleted_at":null},
  {"user_id":{"$nin":[0]}}
],
"$or":[
  {"user_id":"541bf64fd4b41cda04fad053"},
  {"group_id":{"$in":[1,2]}}
]}, []}
```
The `whereNotIn('user_id', [0])` condition always will be true.

Original (not works):
```php
Book::where('user_id', $userId)
  ->orWhereIn('group_id', $groups)
  ->get()
```
```js
book.find({"$and":[
  {"deleted_at":null},
  {"user_id":"541bf64fd4b41cda04fad053"}
],
"$or":[
  {"group_id":{"$in":[1,2]}}
]}, [])
```

I also tried (not works):
```php
Book::orWhere('user_id', $userId)
  ->orWhereIn('group_id', $groups)
  ->get()
```
```js
book.find({"$or":[
  {"deleted_at":null},
  {"user_id":"541bf64fd4b41cda04fad053"},
  {"group_id":{"$in":[1,2]}}
]}, [])
```

**Comment by jithinjose2** [comment]
+1

**Comment by artemverbo** [comment]
+1
