### ISSUE TITLE
Failed to connect  mongo

### ISSUE THREAD

**Issue by ganapathi-threesquare** [jenssegers/laravel-mongodb#311]
hi,
 in aws i am facing this problem....

Failed to connect to: 127.0.0.1:27027: Connection refused 

 }
if (isset($config['password']) && $config['password'])
{
$options['password'] = $config['password'];
}
return new MongoClient($dsn, $options);
}

**Comment by askmatey** [comment]
Please clarify your specific problem or add additional details to highlight exactly what you need. As it's currently written, it’s hard to tell exactly what you're asking.

Otherwise, this issue should be closed.
