### ISSUE TITLE
ManyToMany relationships cannot duplicate instances.

### ISSUE THREAD

**Issue by cleanunicorn** [jenssegers/laravel-mongodb#312]
The behavior seems to differ from Eloquent. If you save an instance of a model more than once as a relationship, that instance should be present more than once.

``` php
$card = Card::get()->first();
$deck->cards()->save($card);
$deck->cards()->save($card);
```

Should save the `$card` for the `$deck` twice, as Eloquent does. However the `$card` is only saved once. In case you only want one instance of the `$card` attached to the `$deck` one should do a check similar to this one

``` php
if (!$deck->cards()->contains($card))
{
    $deck->cards()->save($card);
}
else
{
    // The card is saved already in the deck
}
```

Check @taylorotwell's comments in this issue https://github.com/laravel/framework/issues/943

**Comment by shehi** [comment]
```
$card = Card::get()->first();
$deck->cards()->save($card);
$deck->cards()->save($card);
```

Instead, if you create new ```Card``` object and try to save it, duplicate line will be inserted. At least it works this way using Tinker.

```
$card1 = Card::get()->first();
$card2 = Card::get()->first();
$deck->cards()->save($card1);
$deck->cards()->save($card2);
```
