### ISSUE TITLE
embedsMany objectId problem

### ISSUE THREAD

**Issue by mhddurrah** [jenssegers/laravel-mongodb#313]
saving embedded models is working but when I get the parent model and try to get the child models I get the ids as -when logging them-
id: {'$id': '53f9e034fa0da4eb426692cf'} as an instance.

**Comment by JoeyHoutenbos** [comment]
Thanks @lucknerjb this solves the problem. I think the issue can be closed..?!

**Comment by mhddurrah** [comment]
Thanks a lot. solved :)

**Comment by JoeyHoutenbos** [comment]
@lucknerjb I still have this problem when using nested embedsMany relationships. Do you have an solution for this?

For example:
Form ==> embedsMany ==> Fields ==> embedsMany ==> Subfields

**Comment by digitalturtle** [comment]
@JoeyHoutenbos did you ever find a solution for this?

**Comment by JoeyHoutenbos** [comment]
@digitalturtle I ended up overriding/extending the toArray-function in my BaseModel:



    public function toArray()
    {
        $data = parent::toArray();

        // Transform IDs
        array_walk_recursive($data, function(&$item, $key) {
            if ('_id' === $key && is_object($item) && get_class($item) === 'MongoId') {
                $item = (string)$item;
            }
        });

        return $data;
    }


Be aware that this uses the deprecated MongoId (http://php.net/manual/en/class.mongoid.php).
