### ISSUE TITLE
"Fully qualified namespace is too long." when relation is named "collection"

### ISSUE THREAD

**Issue by flappix** [jenssegers/laravel-mongodb#3134]
- Laravel-mongodb Version: 4.6, 4.7, 4.8 (on 4.5 it does not occour)
- PHP Version: 8.2
- Database Driver & Version: php8.2-mongodb

### Description:

I encountered this weird error when two models are connected with a `belongsTo` relation which is named `collection` and when one model have some long attributes. It disappears when the relation is renamed to something else.

### Steps to reproduce
app/Models/ModelA.php

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use MongoDB\Laravel\Eloquent\Model;

class ModelA extends Model
{
    use HasFactory;
}
```

app/Models/ModelB.php
```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use MongoDB\Laravel\Eloquent\Model;

use App\Models\ModelA;

class ModelB extends Model
{
	public function collection() // renaming this to _collection fixes the error
	{
		return $this->belongsTo (ModelA::class);
	}

}
```

routes/web.php
```
Route::get ('/debug', function()
{
	$a = App\Models\ModelA::create();
	$a->attr1 = 'Looooooooooooooooooooooooooooooooooooooooooong attribute';
	$a->attr2 = 'Looooooooooooooooooooooooooooooooooooooooooong attribute';
	$a->attr3 = 'Looooooooooooooooooooooooooooooooooooooooooong attribute';
	$a->attr4 = 'Looooooooooooooooooooooooooooooooooooooooooong attribute';
	$a->save();
	
	$b = App\Models\ModelB::create();
	$b->collection()->associate ($a);
	$b->save();
	
	return 'success';
	
});
```

### Expected behaviour
When calling the route `debug` I expect to see the message `success`

### Actual behaviour
I get this error message:

```
Fully qualified namespace is too long. Namespace: my_app.{"updated_at":"2024-09-04T18:07:55.030000Z","created_at":"2024-09-04T18:07:55.027000Z","_id":"66d8a1fb2ba404ec4206ea61","attr1":"Looooooooooooooooooooooooooooooooooooooooooong attribute","attr2":"Looooooooooooooooooooooooooooooooooooooooooong attribute","attr3":"Looooooooooooooooooooooooooooooooooooooooooong attribute","attr4":"Looooooooooooooooooooooooooooooooooooooooooong attribute"} Max: 255
```

**Comment by masterbater** [comment]
Its not because of your long attributes, I believe it assumes the collection method as your custom collection or table name. 

Fully qualified namespace is too long. Namespace: my_app.{"updated_at":.....
my_app is your database name and after dot notation is your collection name

**Comment by flappix** [comment]
When the attributes are shorter I dont get the error, then the code works as expected.

**Comment by GromNaN** [comment]
This is a conflict with the `collection` property in `MongoDB\Laravel\Eloquent\Model` class. This property have been removed in [version 5.0 (currently in RC)](https://github.com/mongodb/laravel-mongodb/releases/tag/5.0.0-rc1). 

You would have the same issue with all the properties defined in the Eloquent Model class: https://github.com/laravel/framework/blob/11.x/src/Illuminate/Database/Eloquent/Model.php
