### ISSUE TITLE
MongoDB\Driver\Monitoring\CommandSubscriber interface signature

### ISSUE THREAD

**Issue by florianJacques** [jenssegers/laravel-mongodb#3153]
- Laravel-mongodb Version: 5.0.0
- PHP Version: 8.3.8
- Database Driver & Version: mongodb-1.19.4

### Description:

MongoDB\Driver\Monitoring\CommandSubscriber interface implementation Generates deprecation alert due to function signatures. 
Missing vois return type.

**Comment by GromNaN** [comment]
Thanks for noticing this issue. Should be fixed by https://github.com/mongodb/laravel-mongodb/pull/3157
