### ISSUE TITLE
Does not work with Jeffrey Way's Factory

### ISSUE THREAD

**Issue by leekaiwei** [jenssegers/laravel-mongodb#32]
I am trying to do some testing. In doing so, I am generating random data for a model using Jeffrey Way's helper Factory. However, trying to do so by calling `$model = Factory::make('CategoryModel');` generates this error:

```
{"error":{"type":"ErrorException","message":"call_user_func_array() expects 
parameter 1 to be a valid callback, class 'MongoDB' does not have a method 'getDoctrineDriver'","file":"/var/www/leaf/vendor/jenssegers/mongodb/src/
Jenssegers/Mongodb/Connection.php","line":174}}
```

His repository is at https://github.com/JeffreyWay/Laravel-Test-Helpers. I wonder if this is fixable?

**Comment by krtrth** [comment]
is it fixed and how
