### ISSUE TITLE
Performance Regression in Count Query with Indexed Field #3191

### ISSUE THREAD

**Issue by mamtaRaiTech** [jenssegers/laravel-mongodb#3228]
<html>
<body>
<h3><strong>Description</strong></h3><p>I am experiencing a significant performance regression when counting documents in the <code>reefer_measurements</code> collection using the <code>reefer_id</code> index.</p><h3><strong>Details</strong></h3><p><strong>Index Creation</strong>:</p><pre class="!overflow-visible"><div class="contain-inline-size rounded-md border-[0.5px] border-token-border-medium relative bg-token-sidebar-surface-primary dark:bg-gray-950"><div class="flex items-center text-token-text-secondary px-4 py-2 text-xs font-sans justify-between rounded-t-md h-9 bg-token-sidebar-surface-primary dark:bg-token-main-surface-secondary select-none">javascript</div><div class="sticky top-9 md:top-[5.75rem]"><div class="absolute bottom-0 right-2 flex h-9 items-center"><div class="flex items-center rounded bg-token-sidebar-surface-primary px-2 font-sans text-xs text-token-text-secondary dark:bg-token-main-surface-secondary"><span class="" data-state="closed"><button class="flex gap-1 items-center select-none py-1"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-sm"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 5C7 3.34315 8.34315 2 10 2H19C20.6569 2 22 3.34315 22 5V14C22 15.6569 20.6569 17 19 17H17V19C17 20.6569 15.6569 22 14 22H5C3.34315 22 2 20.6569 2 19V10C2 8.34315 3.34315 7 5 7H7V5ZM9 7H14C15.6569 7 17 8.34315 17 10V15H19C19.5523 15 20 14.5523 20 14V5C20 4.44772 19.5523 4 19 4H10C9.44772 4 9 4.44772 9 5V7ZM5 9C4.44772 9 4 9.44772 4 10V19C4 19.5523 4.44772 20 5 20H14C14.5523 20 15 19.5523 15 19V10C15 9.44772 14.5523 9 14 9H5Z" fill="currentColor"></path></svg>Copy code</button></span></div></div></div><div class="overflow-y-auto p-4" dir="ltr"><code class="!whitespace-pre hljs language-javascript">db.<span class="hljs-property">reefer_measurements</span>.<span class="hljs-title function_">createIndex</span>({ <span class="hljs-attr">reefer_id</span>: <span class="hljs-number">1</span> });
</code></div></div></pre><p><strong>Count Query</strong>:</p><pre class="!overflow-visible"><div class="contain-inline-size rounded-md border-[0.5px] border-token-border-medium relative bg-token-sidebar-surface-primary dark:bg-gray-950"><div class="flex items-center text-token-text-secondary px-4 py-2 text-xs font-sans justify-between rounded-t-md h-9 bg-token-sidebar-surface-primary dark:bg-token-main-surface-secondary select-none">php</div><div class="sticky top-9 md:top-[5.75rem]"><div class="absolute bottom-0 right-2 flex h-9 items-center"><div class="flex items-center rounded bg-token-sidebar-surface-primary px-2 font-sans text-xs text-token-text-secondary dark:bg-token-main-surface-secondary"><span class="" data-state="closed"><button class="flex gap-1 items-center select-none py-1"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-sm"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 5C7 3.34315 8.34315 2 10 2H19C20.6569 2 22 3.34315 22 5V14C22 15.6569 20.6569 17 19 17H17V19C17 20.6569 15.6569 22 14 22H5C3.34315 22 2 20.6569 2 19V10C2 8.34315 3.34315 7 5 7H7V5ZM9 7H14C15.6569 7 17 8.34315 17 10V15H19C19.5523 15 20 14.5523 20 14V5C20 4.44772 19.5523 4 19 4H10C9.44772 4 9 4.44772 9 5V7ZM5 9C4.44772 9 4 9.44772 4 10V19C4 19.5523 4.44772 20 5 20H14C14.5523 20 15 19.5523 15 19V10C15 9.44772 14.5523 9 14 9H5Z" fill="currentColor"></path></svg>Copy code</button></span></div></div></div><div class="overflow-y-auto p-4" dir="ltr"><code class="!whitespace-pre hljs language-php"><span class="hljs-variable">$db</span> = <span class="hljs-title class_">ReeferMeasurementModel</span>::<span class="hljs-title function_ invoke__">where</span>(<span class="hljs-string">'reefer_id'</span>, <span class="hljs-string">'='</span>, <span class="hljs-variable">$reefer</span>-&gt;id);
<span class="hljs-variable">$total</span> = <span class="hljs-variable">$db</span>-&gt;<span class="hljs-title function_ invoke__">count</span>();
</code></div></div></pre><p><strong>Performance Comparison</strong>:</p>
Version | Execution Time
-- | --
4.8.0 | 3,869.62ms
5.0.0 | 22,550.24ms

<h3><strong>Environment</strong></h3><ul><li><strong>Laravel-mongodb Version</strong>: 5.0.0</li><li><strong>PHP Version</strong>: 8.2</li><li><strong>Laravel Version</strong>: 11.29.0</li><li><strong>MongoDB Extension Version</strong>: 1.20.0</li><li><strong>Collection</strong>: <code>reefer_measurements</code></li><li><strong>Number of Documents</strong>: 4 million</li></ul><h3><strong>Steps to Reproduce</strong></h3><ol><li>Create a collection <code>reefer_measurements</code> with 4 million documents.</li><li>Create an index on the <code>reefer_id</code> field:<pre class="!overflow-visible"><div class="contain-inline-size rounded-md border-[0.5px] border-token-border-medium relative bg-token-sidebar-surface-primary dark:bg-gray-950"><div class="flex items-center text-token-text-secondary px-4 py-2 text-xs font-sans justify-between rounded-t-md h-9 bg-token-sidebar-surface-primary dark:bg-token-main-surface-secondary select-none">javascript</div><div class="sticky top-9 md:top-[5.75rem]"><div class="absolute bottom-0 right-2 flex h-9 items-center"><div class="flex items-center rounded bg-token-sidebar-surface-primary px-2 font-sans text-xs text-token-text-secondary dark:bg-token-main-surface-secondary"><span class="" data-state="closed"><button class="flex gap-1 items-center select-none py-1"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="icon-sm"><path fill-rule="evenodd" clip-rule="evenodd" d="M7 5C7 3.34315 8.34315 2 10 2H19C20.6569 2 22 3.34315 22 5V14C22 15.6569 20.6569 17 19 17H17V19C17 20.6569 15.6569 22 14 22H5C3.34315 22 2 20.6569 2 19V10C2 8.34315 3.34315 7 5 7H7V5ZM9 7H14C15.6569 7 17 8.34315 17 10V15H19C19.5523 15 20 14.5523 20 14V5C20 4.44772 19.5523 4 19 4H10C9.44772 4 9 4.44772 9 5V7ZM5 9C4.44772 9 4 9.44772 4 10V19C4 19.5523 4.44772 20 5 20H14C14.5523 20 15 19.5523 15 19V10C15 9.44772 14.5523 9 14 9H5Z" fill="currentColor"></path></svg>Copy code</button></span></div></div></div><div class="overflow-y-auto p-4" dir="ltr"><code class="!whitespace-pre hljs language-javascript">db.<span class="hljs-property">reefer_measurements</span>.<span class="hljs-title function_">createIndex</span>({ <span class="hljs-attr">reefer_id</span>: <span class="hljs-number">1</span> });
</code></div></div></pre></li><li>Execute the count query as shown above.</li><li>Compare the performance of the query between versions 4.8.0 and 5.0.0 of the Laravel MongoDB package.</li></ol><h3><strong>Expected Behavior</strong></h3><p>The count query should be optimized to leverage the <code>reefer_id</code> index effectively, resulting in consistent or improved performance compared to version 4.8.0.</p><h3><strong>Actual Behavior</strong></h3><p>The execution time for the count query has significantly increased in version 5.0.0, leading to degraded application performance.</p><hr><h3><strong>Request for Assistance</strong></h3><p>I would appreciate guidance on:</p><ul><li>Potential causes for this performance regression in version 5.0.0.</li><li>Recommendations for optimizing the count operation to restore or improve performance.</li></ul><p>Thank you!</p>
</body>
</html>

**Comment by alcaeus** [comment]
This is a carbon copy of #3191, including the issue number in the title. If you have a similar issue, please post updated information in the original issue, but don't copy someone else's problem into a new issue as it only creates noise. Thank you.
