### ISSUE TITLE
Updating Inner Objects

### ISSUE THREAD

**Issue by seivad** [jenssegers/laravel-mongodb#323]
I can't seem to update the "spaces" on one of these data objects. 

			$tour = Tour::find($booking->id);

			foreach($tour->dates as $date) {
				if( $date['id'] == $booking->tour_date ) {
					//echo 'dateID and Tour Date match!';
					if( $date['spaces'] > 0 ) {
						//echo 'Spaces is more than 0';
						$date['spaces'] = $date['spaces'] - 1;
					}
				}
			}
			$tour->save();

My code above loops over them and I can echo the items out, but when I check back in mongo shell they are still the same, the saving doesn't seem to work.

I'm also not sure how the ->decrement function works, if I can use dot notation to narrow down or not. I don't think there is enough info on updates in the read me. 

	"dates" : [
		{
			"id" : NumberLong(1354906891),
			"start_date" : "26/09/2014",
			"end_date" : "07/10/2014",
			"price" : NumberLong(175000),
			"spaces" : NumberLong(3)
		},
		{
			"id" : NumberLong(572541906),
			"start_date" : "8/10/2014",
			"end_date" : "19/10/2014",
			"price" : NumberLong(180000),
			"spaces" : NumberLong(1)
		},
		{
			"id" : NumberLong(1072327884),
			"start_date" : "20/10/2014",
			"end_date" : "31/10/2014",
			"price" : NumberLong(175000),
			"spaces" : NumberLong(0)
		}
	]

**Comment by askmatey** [comment]
This issue should be closed, since it was caused by a problem that can no longer be reproduced or a simple typographical error (see https://github.com/jenssegers/laravel-mongodb/issues/323#issuecomment-55745239).
