### ISSUE TITLE
MongoDb 64 bit error of converting in INT

### ISSUE THREAD

**Issue by Nishchit14** [jenssegers/laravel-mongodb#324]
Hello sir,

 I am using this library for m project with 64 bit mongodb . But when i am calling my api i get this error.

<pre>
{
	"error": {
		"type": "ErrorException",
		"message": "Object of class MongoInt64 could not be converted to int",
		"file": "\/var\/www\/html\/diamondcart\/branches\/v.1.0\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Query\/Builder.php",
		"line": 1713
	}
}

</pre>

**Comment by askmatey** [comment]
This issue should be closed. The user missed to clarify his specific problem or add additional details to highlight exactly what he needs (202 days since now).

**Comment by Nishchit14** [comment]
This is mongoDB 32/64 bit version issue.

<?php
ini_set('mongo.native_long', 1);

This resolved issue.

For more detail refer this http://derickrethans.nl/64bit-ints-in-mongodb.html
