### ISSUE TITLE
"Serialization of 'Closure' is not allowed" when caching object after adding to "embedsMany" attribute

### ISSUE THREAD

**Issue by rms2219** [jenssegers/laravel-mongodb#329]
I have a "Contract" object which embeds many "Project" objects. The database interactions are working fine. I can add (associate) a new project to a contract and save the contract just fine. When I try to put that recently saved object into my cache, I get the exception: "Serialization of 'Closure' is not allowed".

Here is a bit of test code that shows the issue:

```
use Jenssegers\Mongodb\Model;

class Contract extends Model {
    public function projects()
    {
         return $this->embedsMany('Project');
    }
}

class Project extends Model {}

// routes.php
    Route::post('contracts/{id}/projects', function($id) {

        $contract = Cache::get('Contracts_' . $id);

        if(!$contract) {
            $contract = Contract::findOrFail($id);
        }

        $project = new Project();
        $project->projectName = 'new project';

        $contract->projects()->save($project); // This works just fine

        Cache::forever('Contracts_' . $id, $contract); // Exception thrown here
    });
```

How can I cache the updated contract?

**Comment by darkeus** [comment]
@rms2219 i have the same issue too, do u already get any workaround? now i am browsing the source code trying to check where is the closure. do you know where is the closure located?

**Comment by darkeus** [comment]
@jenssegers i just tried edit the code, in the class EmbedsOneOrMany, i comment all line of code with setParentRelation($this); and now the serialization is working, the closure are contains at the parentRelations attribute, and without parentRelations it is work.

**Comment by jenssegers** [comment]
This is indeed an issue with the current implementation of embedded models. I'm trying to get this fixed in the v3 release.

**Comment by darkeus** [comment]
@jenssegers yep, i think i found the fix =D, i just wanna ask, what is the parentRelation attribute use for? since after i comment it, all work fine for me in embbededMany Relation. thanks for your hard work anyway

**Comment by jenssegers** [comment]
It is used to traverse through multiple embedded model levels to the main parent object that needs to be saved to the database.

**Comment by darkeus** [comment]
@jenssegers i see, then this is not a fix. if i comment this out. it will broke the saved feature, btw jens, how can i contribute? maybe i can help with some bug fixing. since i do my project on mongodb now

**Comment by jenssegers** [comment]
It wil only break stuff if you are using multiple levels of embedded documents and are doing `->save()` on those embedded models. I'm still figuring out a good solution to fix this.

**Comment by darkeus** [comment]
@jenssegers  jens i think i got an idea, how about we implement __sleep magic method in the model class like this

public function __sleep(){
     return array_diff(array_keys(get_object_vars($this)), array('parentRelation'));
}

this code work for me, it still persist relations attribute, so it will cached, only parentRelation set to null before serialization, and if after unserialize we need to call save() method, it still working. it will recreate parentRelation attribute when calling save();

how about you add this to your source for next release? =D

**Comment by zamrih** [comment]
Hi,

As it's only used for generating a cache key, ->compileWheres() in replacement of ->wheres will avoid getting into serializing any where Closures.

Feel free to check that out.
