### ISSUE TITLE
Unsupported driver [mongodb]

### ISSUE THREAD

**Issue by pwfraley** [jenssegers/laravel-mongodb#334]
Hey,

I just tried installing mongo support in laravel, but when I try to seed the database I get the error message:

    [InvalidArgumentException]    
    Unsupported driver [mongodb]

when I check my php for Mongo support with:

    php -i | grep 'Mongo'

I get:

    MongoDB Support => enabled

In my database.php I have default set to mongodb and in the connections array I have an entry for mongodb with driver => 'mongodb'

what have I overlooked?

**Comment by askmatey** [comment]
This issue should be closed, since it was caused by a problem that can no longer be reproduced or a simple typographical error (see https://github.com/jenssegers/laravel-mongodb/issues/334#issuecomment-57601748).

**Comment by ashokcs94a** [comment]
Hi, 
 i am also getting error while migration 

[InvalidArgumentException]    
  Unsupported driver [mongodb] 

i don't why any one plz help ...?

**Comment by tralves** [comment]
1) make sure you are adding the service provider.
2) if you are using lumen, make sure you are adding the service provider **before**  ```$app->withEloquent();```

**Comment by kahovn** [comment]
HI Tralves 
  That great

**Comment by huydoan1999** [comment]
thank you tralves. LOVE YOUU<3

**Comment by TanujKumar709** [comment]
Hi @tralves ,
That perfect solution.Thanks Dude.
