### ISSUE TITLE
Can't insert JSON directly into table without quotes being escaped

### ISSUE THREAD

**Issue by nelsonzheng** [jenssegers/laravel-mongodb#335]
I'm trying to directly insert valid JSON data into a table. However, the JSON is treated like a string and all '"' quotes are being escaped with backslashes. 

`"data":"{\"language\":\"en\",\"headers\":[{\"id\":\"00_0010_7112_0100\",\"description\":\"`

Is there a way around this?

**Comment by rntorm** [comment]
One possible workaround: 
$user = User::find($userId);

$notification = new Notification(array('user' => $user->toArray());
