### ISSUE TITLE
Search by related model (belongsTo relation)

### ISSUE THREAD

**Issue by EhsanZ** [jenssegers/laravel-mongodb#342]
Hi
Assume that I have two models: User & Article.
I want to get all articles which have been written by high school students.
It seems so easy but I'm giving up with it, I tried those two solutions:

```
$articles = Article::with(
array('user'=>function($user_query)
{
$user_query->where('school_level','=','high school');
})
)->get();
```

And:

```
$articles = Articles::where('user.school_level','=','high school');
```

Both don't work,  SQL developers use `join` to solve this problem, what should we use?
Also, if the relationship was `Has Many` the search works good using `whereHas`, for example : 

```
$users = User::whereHas(
'articles', function($article_query)
{
$article->where('subject','like','some text');
})->get()
```

Any suggestions?

**Comment by manojnegii90** [comment]
hi , do you get any solution for this ?

**Comment by EhsanZ** [comment]
@manojnegii90 Hi
I did it by getting all user ids at first then send it to a new query to get articles.
I'm sorry I can't find the code since it is from 2014 and I made up a scenario for company policy, I'll write it here if I found it.

**Comment by manojnegii90** [comment]
@EhsanZ Hi, thanks for the reply  but I want to search on both article title and user name something like this : 
$articles = Article::with('user')->where('title','like',$search')->orWhereHas('user',function($q) use($search) {
         $q->where('user_name','like', $search);
})->paginate(20);

Thanks again for the quick reply. 👍

**Comment by EhsanZ** [comment]
Your code should work, I had a similar scenario but without `or` operator and it did work.
btw, I don't know if this is the issue but you added - mistakenly - quotes around $search variable.

**Comment by manojnegii90** [comment]
Well, The code do work when the relation is hasMany but it is not working in case of belongsTo. I don't know why ? 

and that quote doesn't exits. It shouldn't be there . It exists mysteriously . I've no idea :)
