### ISSUE TITLE
[question]using aggregate mongo function

### ISSUE THREAD

**Issue by Grummfy** [jenssegers/laravel-mongodb#344]
Hi,
I try to use something like this 
db.myCollection.aggregate([{$group: {_id: '$fieldA', total: {$sum: "$fieldB"}, count: { $sum: 1 }, d: "$fieldD"}}])

But don't know how to combine them to something understandable by the created layer.

**Comment by milsanore** [comment]
@Grummfy is the wiki still available?
Thanks

**Comment by Traxo7** [comment]
@milsanore 

https://github.com/jenssegers/laravel-mongodb/wiki

https://github.com/jenssegers/laravel-mongodb/wiki/Complexe-aggregate-call

**Comment by cyrrill** [comment]
Correct page link is:

https://github.com/jenssegers/laravel-mongodb/wiki/Complex-aggregate-call
