### ISSUE TITLE
How to store extra attributes?

### ISSUE THREAD

**Issue by yaim** [jenssegers/laravel-mongodb#347]
Guys, is it possible to store extra attributes using belongToMany relation in Moloquent?

Something like like:
$user->books()->save($book, array('date' => $date));

**Comment by jenssegers** [comment]
The current belongToMany implementation does not use a joining table, so there is no place to actually store it at the moment.

**Comment by askmatey** [comment]
Please clarify your specific problem or add additional details to highlight exactly what you need. As it's currently written, it’s hard to tell exactly what you're asking.

Otherwise, this issue should be closed.
