### ISSUE TITLE
relations failed when the foreign key of type ObjectId

### ISSUE THREAD

**Issue by YSimple** [jenssegers/laravel-mongodb#350]
Hello,

i have an issue when i add any relations such as `hasMany` and the refrences already of type `ObjectId` the query return null but when i change the foreign key to string it worked out 

any suggestions or other way to solve this ??

**Comment by kisuka** [comment]
I have the same issue.

**Comment by jenssegers** [comment]
The current implementation uses strings rather than MongoId's for relations due to some complications with the original Eloquent code. This is something on the todo list.

**Comment by rohitkhatri** [comment]
Any fix for this?
