### ISSUE TITLE
Request Documentation on Using Laravel -MongoDB outside Laravel

### ISSUE THREAD

**Issue by pokoot** [jenssegers/laravel-mongodb#354]
Currenty I am able to use use Eloquent outside Laravel (using the code below). Now I wanted to use your class using MongoDB but I could find any documentation on how to integrate your library ouside Laravel.

Would it be possible if you include on your readme.md documentation? Instruction on how to bootstrap it?

```php

use Illuminate\Database\Capsule\Manager as Capsule;
use Jenssegers\Mongodb\Connection as Connection;

$capsule = new Illuminate\Database\Capsule\Manager;
$capsule->addConnection(array(
    'driver'    => 'mysql',
    // Config goes here 
));

// $capsule->getDatabaseManager()->extend();

$capsule->bootEloquent();
$capsule->setAsGlobal();
``` 

Cheers :100:

**Comment by jenssegers** [comment]
I think people should be able to figure it out following the Capsule documentation. Will write it on my todo list to link it in the readme.

**Comment by Starojitski** [comment]
"Should" as in "if they have no idea how to do it, they should not use this package"? I am all for RTFM but until i came across your comment i did not know which F****** Manual i should be reading.

Having integrated Illuminate/database in my project without Laravel by following their README, Capsule is still an uncharted territory. I did not even realize that the way to make your package work lies in Capsule documentation
