### ISSUE TITLE
Support L5

### ISSUE THREAD

**Issue by GoldenZero** [jenssegers/laravel-mongodb#355]
Dose this lib support L5?

**Comment by duxet** [comment]
I am working on this: https://github.com/duxet/laravel-mongodb/tree/L5

**Comment by jenssegers** [comment]
Nice @duxet! You're ahead of me. I was waiting until L5 gets a bit more stable, because at this moment, they're still breaking a lot of stuff.

**Comment by duxet** [comment]
It's not so hard to make it work with L5, however there is a problem with cleaning after QueryTest: https://travis-ci.org/duxet/laravel-mongodb/jobs/46657530

**Comment by duxet** [comment]
OK, all tests are passing, so i will open PR after final version of L5 gets released :)
