### ISSUE TITLE
Relational Ids stored as Strings

### ISSUE THREAD

**Issue by rmedcalf** [jenssegers/laravel-mongodb#356]
Wouldn't it be correct to store them as ObjectId?

I have a user object

```
public function role()
{
    return $this->belongsTo('Bbfx\Models\Role');
}
```

My role object

```
public function user()
{
    return $this->hasOne('Bbfx\Models\User');
}
```

When saved, a user document is created and has the correct role_id but the role_id type is String. The mongodb documentation says this should be an ObjectId

**Comment by mofodojodino** [comment]
Is there any movement on this - I'm dealing with a legacy db which uses ObjectId throughout which I can't change.

**Comment by stratease** [comment]
Would love to see this implemented too. I'm probably going to implement a workaround like the one listed above - not excited about it.

**Comment by jenssegers** [comment]
I have been trying to do this for quite a while, but it takes a lot more changes than the one above. I'll have another go at it this weekend.

**Comment by barroca** [comment]
+1 on having this implemented. Thanks

**Comment by omidahn** [comment]
+1 on having this implemented. Thanks

**Comment by martingg88** [comment]
+1

**Comment by rohitkhatri** [comment]
+1 on having this implemented. Thanks

**Comment by ericsala** [comment]
+1

**Comment by Oleg-Arkhipov** [comment]
+1

**Comment by maslauskas** [comment]
+1 would really love to see this implemented
