### ISSUE TITLE
$text and sort by $meta - is it possible ?

### ISSUE THREAD

**Issue by proofyman** [jenssegers/laravel-mongodb#358]
To sort fulltext by meta i need to do whereRaw, meta projection and orderBy('name',['$meta'=> 'textScore'], which illegal for laravel-mongodb(only strings acceptable). 

Any workaround or I need to do pull request ?

**Comment by jenssegers** [comment]
Sorry for the late response, how would you implement this?

**Comment by evinkuraga** [comment]
Continuation on @proofyman :

`Articles::whereRaw(['$text' => ['$search' => $query]])->orderBy('score', ['$meta' => "textScore"])->take(10)->get()
`
This gives: 

`Can't canonicalize query: BadValue must have $meta projection for all $meta sort keys`

Unfortunately, this doesn't seem to work for me. I've also tried:

```
$results = Articles::raw(function($collection) use ($request)
        {
            return $collection->find(
                ['$text'=>['$search'=>$request->input('searchquery')]],
                ['score'=>['$meta'=>"textScore"]],
                ['sort'=>['score'=>['$meta'=>'textScore']]]
            );
        })->take(10);
```
Which will return results, just not in the right order. 

@m0lll0t - Seems like he committed a fix to use the orderBy chaining method, but seems like it hasn't been implemented yet. Currently using version:
jenssegers/mongodb (v3.0.2)

If there a way to implement sort with text score with the current version?

**Comment by stratease** [comment]
I'm trying to solve this too - is there a solution, or should the above work?

**Comment by evinkuraga** [comment]
It won't work. I've found a few work arounds since. Here's the prettiest:

Build a query scope. IE:
// Your search controller
`Search::whereText($searchterm)->orderBy('score', 'desc');`

// In model -- need to project the score field

```
$query->getQuery()->projections = [
			'name'=>1,
			'slug'=>1,
                          ... whatever else field you use
			'score'=>['$meta'=>'textScore'],
		];
```

**Comment by stratease** [comment]
Ahh, thanks I'll give it a try. Forgot all about [scopes](https://laravel.com/docs/5.5/eloquent#query-scopes)
