### ISSUE TITLE
Is it possible to rename collection?

### ISSUE THREAD

**Issue by rbruhn** [jenssegers/laravel-mongodb#359]
I did a quick search on the code and didn't see anything regarding renaming a collection. Is this possible and I'm missing it? Using the below throws an error.
~~~
Schema::connection('mongodb')->rename('subjectdocs', 'subjects');
~~~

~~~
[ErrorException]
Argument 2 passed to Illuminate\Database\Schema\Blueprint::build() must be
an instance of Illuminate\Database\Schema\Grammars\Grammar, null given, cal
led in /vagrant/mysite/vendor/laravel/framework/src/Illuminate/Database/Sc
hema/Builder.php on line 169 and defined
~~~

In the meantime, I'm simply running the shell
~~~
db.subjectdocs.renameCollection('subjects')
~~~

**Comment by askmatey** [comment]
No, there's is no method for renaming collections.

**Comment by alexandre-butynski** [comment]
You can use : 

```PHP
DB::statement("db.subjectdocs.renameCollection('subjects')");

**Comment by rbruhn** [comment]
Thanks.

**Comment by ryangurn** [comment]
So i am trying to do the same thing with laravel 5.2 and mongodb and I cannot get the ```DB::statement("...");``` to work properly. Any advice?

**Comment by vingrad** [comment]
> > php artisan migrate
> 
>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Call to a member function prepare() on null

**Comment by peterver** [comment]
I know it looks ugly, but try the following in the meanwhile :) 

```
$connection = DB::connection('mongodb')->getMongoClient();
$db = config('database.connections.mongodb.database');

$mong->admin->command([
    'renameCollection' => "{$db}.ORIGINAL_NAME",
    'to' => "{$db}.NEW_NAME",
]);
```

**Comment by david-navarro** [comment]
Same, when I try: 
`Schema::connection('mongodb')->rename('table1',` 'table2');
I get this error on type >php artisan migrate:
` Type error: Argument 2 passed to Illuminate\Database\Schema\Blueprint::build() must be
  an instance of Illuminate\Database\Schema\Grammars\Grammar, null given, called in /home
  /vagrant/code/adinton/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.p
  hp on line 252`

and trying this 
`DB::statement("db.table1.renameCollection('table2')");`
on type >php artisan migrate:
` Call to a member function prepare() on null`

**Comment by david-navarro** [comment]
@peterver your solution works!

**Comment by beyto1974** [comment]
For version 5.x:

```php
DB::connection('mongodb')
  ->getDatabase(env('MONGO_DB_DATABASE'))
  ->getCollection("{$tableName}_tmp")
  ->rename($tableName, options: ['dropTarget' => true]);
``
