### ISSUE TITLE
Aggregating multiple columns only returns the last column

### ISSUE THREAD

**Issue by jakalofnaar** [jenssegers/laravel-mongodb#360]
I'm trying to retrieve a resultset with the aggregate totals for a few fields in my collection. This is how I'm building my query:

```php
$result = $query->where('prov', $providerId)
	->where('dt', '>=', $startDate)
	->where('dt', '<', $endDate)
	->aggregate('sum', array( 'dl', 'play', 'cnt', 'mb', 'dur' ));
```

And this is what I'm expecting to see:

```json
{
	"dl": 0,
	"play": 1,
	"cnt": 1,
	"mb": 2,
	"dur": 3
}
```

But instead I just get `3`, or the aggregate result for the `dur` column. Looking at the raw mongo query that gets executed I see the `$group` pipeline command only sums that field, ignoring all the other columns passed in to `QueryBuilder::aggregate()`.

Is this intended behaviour? I also see you can only run a single aggregate function (ie. `$sum`), whereas sometimes we may need to account for combined sum and count operations.

**Comment by jenssegers** [comment]
I don't think the original Eloquent allows you do to this either. It will probably be better to use a `raw` query in this case.
