### ISSUE TITLE
Getting count of related_ids

### ISSUE THREAD

**Issue by rbruhn** [jenssegers/laravel-mongodb#361]
I'm trying to retrieve the count of related ids within a document. The ids are stored like this:

expedition_ids : [1,2,3]

I'm using a raw query off the relationship in my Expedition model:
~~~
public function subjectsCountRelation ()
{
        return $this->belongsToMany('Subject')
	        ->selectRaw('count(expedition_ids) as count(*)')
	        ->groupBy('expedition_ids');
}

public function getSubjectsCountAttribute ()
{
        return $this->subjectsCountRelation->first() ? $this->subjectsCountRelation->first()->count : 0;
}
~~~

It builds a query like this but returns nothing:
~~~
subjects.aggregate([{"$match":{"expedition_ids":{"$in":["1","2","3"]}}},{"$group":{"_id":{"expedition_ids":"$expedition_ids"},"expedition_ids":{"$last":"$expedition_ids"},"count(expedition_ids) as count(*)":{"$last":"$count(expedition_ids) as count(*)"}}}])
~~~
Due to the database seeding, I know I have 3 Expeditions with 100 Subjects in each. So I know they exist. Obviously the query is not right. So what would be the correct way of writing the query?

**Comment by lennynyktyk** [comment]
Essentially you are trying to get multiple row aggregate.  Eloquent doesn't seem to have an eloquent way to do.  This StackOverflow http://stackoverflow.com/questions/16764346/getting-daily-aggregates-sum-sorted-by-day-in-laravel answer uses the techniques I would suggest, i.e. `select(DB:raw(...))`and `lists()`.

In your case you'll need to do something to the effect of:
```php
<?php
public function subjectsCountRelation ()
{
    $query = $this->belongsToMany('Subject')->groupBy('expedition_ids');
    $query->getQuery()->aggregate = [ 'function' => 'count', 'columns' => [ 'id' ] ];
    return $query->get();
}
```
Essentially this is what the `Illuminate\Database\Query\Builder::aggregate()` does just skips the `return $results[0];` step.
