### ISSUE TITLE
Advanced where not working?

### ISSUE THREAD

**Issue by lasselehtinen** [jenssegers/laravel-mongodb#362]
Hi,

I understood that advanced where clauses would be supported. I am trying to do the following query:

        $products = DB::table('products')->where(function($query) use ($from, $to) {
            $query->orWhereBetween("created_at", [$from, $to])->orWhereBetween("updated_at", [$from, $to]);
        });

But when I check the actual query done, it is:
```
db.products.find({  
   "$and":[  
      {  
         "created_at":{  
            "$gte":{  
               "sec":1415923200,
               "usec":0
            }
         }
      },
      {  
         "created_at":{  
            "$lte":{  
               "sec":1418342400,
               "usec":0
            }
         }
      }
   ]
},
{  
   "product_number":true
})
```
As you can see there is no clause for the updated_at. Or am I doing something wrong?

**Comment by kimsyversen** [comment]
This is not a direct solution to your answer (and mabye late), but I guess you could solve it by something like this:
```
Model::whereRaw([
			'created_at' => [
						'$gte' => new MongoDate(strtotime($from)),
						'$lt' => new MongoDate(strtotime($to))
			],
			'updated_at' => [
						'$gte' => new MongoDate(strtotime($from)),
						'$lt' => new MongoDate(strtotime($to))
			]])->get();
```
