### ISSUE TITLE
update nested child elements

### ISSUE THREAD

**Issue by Fynkymynky** [jenssegers/laravel-mongodb#368]
I have a document with child elements of items like so

```
"bar" : "547244fe10f0edd3128b4567",
    "items" : [ 
        {
            "1" : {
                "message" : "",
                "display" : "true",
                "type" : "text"
            }
        }, 
        {
            "2" : {
                "id" : "234234",
                "type" : "image",
                "message" : "foo",
                "display" : "true",
                "created_at" : NumberLong(1416432114)
            }
        }, 
        {
            "3" : {
                "message" : "",
                "display" : "true",
                "type" : "text"
            }
        }, 
```

and I'm trying to update one of the childrens value

```
$foo['items']['1']['message'] = 'hello';
$story = InfoDB::where('_id', $id)->update($foo);
```

So that

```
            "1" : {
                "message" : "",
                "display" : "true",
                "type" : "text"
            }
```

Becomes

```
            "1" : {
                "message" : "hello",
                "display" : "true",
                "type" : "text"
            }

```

But when I run the update command it deletes all the children in the document.

Do I have to update the entire document? or is there another function?

Thanks

**Comment by pmventura** [comment]
Thanks @alexandre-butynski

**Comment by harshvirani** [comment]
How to find index so i can apply that query with index @alexandre-butynski

**Comment by RedsAnDev** [comment]
@alexandre-butynski  Thank you so much, your answer is usefull, even after 3 years!

**Comment by prafful-panwar** [comment]
@alexandre-butynski Is there any update method like this
`$story = InfoDB::where('_id', $id)->where(''items.*.uId', $uId)->update(message' => $foo);`

As you can see every time I have to update any value in a nested array I have to do foreach and find that nested Array and do that update.
My Code

````
foreach ($post->comments as $key => $comment) {
                if ($comment['id'] == $commentId) {
                    $dataArray = $request->toBag()->attributes();
                    if ($subCommentId) {
                        foreach ($comment as $nestedkey => $nestedComments) {
                            if ($nestedComments['id'] === $subCommentId && $nestedComments['posted_by'] == $authUser['id']) {
                                $data = $post->update([
                                    "comments.$key.$nestedkey.description" => $dataArray['description'],
                                    "comments.$key.$nestedkey.updated_at" => $dataArray['updated_at'],
                                ]);
                            }
                        }
                    } else {
                        if ($comment['posted_by'] == $authUser['id']) {
                            $data = $post->update([
                                "comments.$key.description" => $dataArray['description'],
                                "comments.$key.updated_at" => $dataArray['updated_at'],
                            ]);
                        }
                    }
                    
                }
            }
````

I just want to avoid that foreach and want to update value inside an array.

Thanks :)

**Comment by navneetccna** [comment]
what if we dont know the index insteat we have id in child doc

**Comment by prafful-panwar** [comment]
@navneetccna https://docs.mongodb.com/manual/reference/operator/update/positional/#up._S_


else 

```
foreach ($post->comments as $key => $comments) {
          if ($comments['id'] === $commentId) {
                  $id = $post->update(["comments.$key.comments" => [$data]], ['upsert' => true]);
          }
}
```

**Comment by navneetccna** [comment]
@prafful-panwar I don't think looping is the right solution. There is already $ operator available in mongo but how we can use in this library.

**Comment by Saneesh** [comment]
> @prafful-panwar I don't think looping is the right solution. There is already $ operator available in mongo but how we can use in this library.

Is this is your question? Here in this snippet, old coupon's(>24Hr) `state` setting as `Expired`.

```
$yesterdaySameTime = Carbon::now()->subHours(24)->format('Y-m-d\TH:i:s');
$yesterdaySameTime = new \DateTime($yesterdaySameTime);

$couponUsage = CouponUsage::query()
      ->where('customer_id', 53)
      ->whereNotIn('data.usage.state', ['Consumed', 'Expired'])
      ->where('data.usage.time', '<', $yesterdaySameTime)
      ->update([
        'data.usage.$.state' => 'Expired'
      ]);
```

**Comment by pluzmedia** [comment]
> query()

I know this thread is too old but still relevant to me. This query is updating first element only in the array.

**Comment by pluzmedia** [comment]
> > @prafful-panwar I don't think looping is the right solution. There is already $ operator available in mongo but how we can use in this library.
> 
> Is this is your question? Here in this snippet, old coupon's(>24Hr) `state` setting as `Expired`.
> 
> ```
> $yesterdaySameTime = Carbon::now()->subHours(24)->format('Y-m-d\TH:i:s');
> $yesterdaySameTime = new \DateTime($yesterdaySameTime);
> 
> $couponUsage = CouponUsage::query()
>       ->where('customer_id', 53)
>       ->whereNotIn('data.usage.state', ['Consumed', 'Expired'])
>       ->where('data.usage.time', '<', $yesterdaySameTime)
>       ->update([
>         'data.usage.$.state' => 'Expired'
>       ]);
> ```

I know this thread is too old but still relevant to me. This query is updating first element only in the array.
