### ISSUE TITLE
getDirty doesn't accurately compare MongoDate values

### ISSUE THREAD

**Issue by ohmance** [jenssegers/laravel-mongodb#373]
I am feeling like this is an issue and am leaning toward the desire for this to be handled within Moloquent rather than above it.

In a model one can subscribe to the "saving" event for example:

    self::saving(function($model) {
         $changes = $model->getDirty();
    });

This returns an array of all properties that have changed within the model during the most recent save.  

if I did `$model->name = 'Ben';`
and then
`$model->name = 'Ben1';`
The property name would show up in getDirty();

If I did `$model->name = 'Ben';`
and then
`$model->name = 'Ben';`
I would expect the property to not show up in getDirty(), and it's as expected.

If I did `$model->date = new MongoDate(1417323606);`
and then
`$model->date = new MongoDate(1417323606);`
I would expect the date property to NOT show up in the getDirty() response.  The problem is that it does.  The reason why is because the date property contains the memory address of the date object rather than the actual date object.  The address changes during this even though contents of each object is the same.

What are the chances that the dirty comparison for objects can be overridden to be a deep comparison rather than shallow comparison?  That way we are comparing actual object values rather than just memory addresses?  This would be useful not only in date objects but any object/array stored in mongo.  I would suggest that Dirty should only return only actually changed values, even if they were set multiple times as the same value.

Thoughts on this?  Would there be any cases where this would be detrimental?

**Comment by hackel** [comment]
I just ran into this issue as well.  I think we need to override the getDirty method and add an additional test just like originalIsNumericallyEquivalent to compare the MongoDate attributes individually.

In the meantime, I simply tested it myself in a mutator:
```php
public function setDateAttribute($value)
{
    $newDate = $this->asDateTime($value);
    if ($newDate->ne($this->date)) {
        $this->attributes['date'] = $this->fromDateTime($newDate);
    }
}
```

**Comment by hackel** [comment]
Nice, thanks @jenssegers!
