### ISSUE TITLE
Double indices

### ISSUE THREAD

**Issue by PepijnSenders** [jenssegers/laravel-mongodb#376]
I tried to add some indexes to my collections, but when i have the same field name in two collections it will add this key twice, which will throw the following error in MongoDB:

```
localhost:27017: Index with name: key_1 already exists with different options
```

How I create my collections:
```
    Schema::create('cms_globals', function($collection) {
      $collection->index('key');

      $collection->unique('key');
    });
    Schema::create('fields', function($collection) {
      $collection->index('key');

      $collection->unique('key');
    });
```

**Comment by Murwa** [comment]
Is it that u want to have 'key' as both an index and a unique key?

**Comment by jenssegers** [comment]
You don't have to add double indexes, just unique is fine.
