### ISSUE TITLE
embedsMany hangs 

### ISSUE THREAD

**Issue by webular** [jenssegers/laravel-mongodb#378]
#### Update ####

it turns out that it was saving but in order to see $website->menus I had to do $website->menus->toArray()

That solved my issue.  I'm going to close this issue.

___________________

I must be doing something wrong.
class Website extends Moloquent
{
	protected $collection = 'websites';

    public function menus(){
        return $this->embedsMany('Menu');
    }

}

class Menu extends Moloquent{

    public function website()
    {
        return $this->belongsTo('Website');
    }
}

you save like this right?
$website = Website::find($websiteId);
$menu = new Menu(['name' => 'This is a Menu']);
$website->menus()->save($menu);

For me this hangs.  And then when I check mongo the embeded menu is there.  However, and this is the weird part,  when I do this:

dd($website->menus) everything hangs.

Anyone else see this?  Any ideas?

**Comment by askmatey** [comment]
Questions seeking debugging help ("why isn't this code working?") must include the desired behavior, a specific problem or error and the shortest code necessary to reproduce it in the question itself.

Questions without a clear problem statement are not useful to other developers.

**Comment by darkeus** [comment]
@kojuka i dont know if you already fixed this. but it seems because on your class Menu has a BelongsTo Relationship, on embedsMany relationship automatically add parent relationship, try comment the 
public function website()
{
    return $this->belongsTo('Website');
}

maybe this will work.

**Comment by kojuka** [comment]
For those experiencing the same thing.

I've tried commenting out the following code on my menu model:

public function website()
{
return $this->belongsTo('Website');
}

No difference in behavior.  When i do the following everything still hangs - no errors:
$website->menus()->save($menu);

**Comment by Zwaen91** [comment]
I have the same problem. How did you solve it @webular ?
