### ISSUE TITLE
Date Mutator and Mass Assignment

### ISSUE THREAD

**Issue by lrills** [jenssegers/laravel-mongodb#379]
When using mass assignment method such like `User::insert; User::update()`, date mutator is not triggered and so does "created_at" "updated_at"  not maintain automatically. 
It behave like using `DB::collection('user')->insert()` without eloquent. Since code like `$user = new User(['account'=>'abc','password''=>'123']); $user->save()` works well, it make sense `insert()` and `update()` work as the same!
And btw, really enjoying the code!

**Comment by alexandre-butynski** [comment]
:+1:
