### ISSUE TITLE
Can I use eloquent on a Raw Aggregate?

### ISSUE THREAD

**Issue by juanfgs** [jenssegers/laravel-mongodb#384]
I'm doing a query with $collection->aggregate(); 
But it returns as expected an array, it is possible to wrap the object in  Eloquent (Moloquent) in order to have an unified interface?.

**Comment by hackel** [comment]
You closed this without any explanation.  Did you ever find a solution?

**Comment by jenssegers** [comment]
You should be able to use `hydrate` to create model instances from an array.

**Comment by hackel** [comment]
@jenssegers Thanks, I did find that solution mentioned in another bug report.  Was something like this what you had in mind?  It works, but feels a bit janky...
```php
        return $this->raw(function ($collection) {
            return Category::hydrate($collection->aggregate([
                ['$match' => [
                    'type' => 'metro_area'
                ]],
                ['$sort' => ['name' => 1, 'region_abbr' => 1]],
                ['$project' => [
                    'name' => [
                        '$concat' => ['$name', ', ', '$region_abbr']
                    ]
                ]]
            ])['result']);
        });
```
