### ISSUE TITLE
$fillable validation for saving arrays

### ISSUE THREAD

**Issue by fraank** [jenssegers/laravel-mongodb#387]
I think there is no syntax for saving arrays into one model when using $fillable instead of $unguarded. In my case I want to save an array (very simple, no real association, just for data readability) as on field into the db.
Fields in the form are named: "profile[name]" and "profile[firstname]". The $validator outputs the expected  data. When using $unguarded the fields are saved. I tried out syntax like "profile.name","profile[name]" or the whole with "profile" as $fillable-keys. But in all cases the fields for "profile" are not updated.

Is there a correct syntax for this quite easy case?

**Comment by marcoskubis** [comment]
@jenssegers This enhancement was done?

**Comment by xDefcon** [comment]
@jenssegers Update regarding this issue?
