### ISSUE TITLE
Question: db.collection.copyTo() method

### ISSUE THREAD

**Issue by andycaramba** [jenssegers/laravel-mongodb#388]
Hi.

How can i use mongodb methods like [db.collection.copyTo()](http://docs.mongodb.org/manual/reference/method/db.collection.copyTo/)?

**Comment by ludovic-coder** [comment]
Use `DB::getMongoDB()->execute("db.source.copyTo('target')");` doesn't work anymore, is there another way to do a copyTo ? Thanks
