### ISSUE TITLE
Many to many relations

### ISSUE THREAD

**Issue by AndreiArba** [jenssegers/laravel-mongodb#39]
Do you plan on adding many to many relation?

One way to achieve this is to keep an array of referenced objects in each entry. This would require two "inserts" for every change.

What do you think?

**Comment by royduin** [comment]
Is this implemented yet? It's an old issue but I can't find anything about it in the readme but I came across some issues where people are talking about pivot tables... I need a many-to-many relation with the same collection, for example: I've got a "values" collection with a lot of values, I'd like to create a many-to-many relation between those values.
