### ISSUE TITLE
Order by multiple column laravel eloquent

### ISSUE THREAD

**Issue by aniljailta** [jenssegers/laravel-mongodb#392]
I have a query. I want to sort a table using two columns.

this is my query:

```
 Publish::with(array('user','notify','notify.user','hoots','story','image'))
         ->whereIn('user_id',$key_with_current_user)
         ->orwhereIn('post_id',$news_data)          
          ->orderBy('score','DESC') 
          ->orderBy('created_at','DESC')             
         ->get()
         ->toArray();
```

Now result i am getting is by column specified first. for above query it is sorted by score but not by score and created_at. 

Any help? how can we sort by multiple column in mongodb using laravel eloquent queries.

I have also tested this in rockmongo's query shell and it behave same. Only get sorted by one column.

For test i have data like 

```
 {
 "_id": ObjectId("54abd1888ead0ee85f8b4569"),
 "created_at": ISODate("2015-01-06T12:14:00.819Z"),
 "post_id": "54abd1888ead0ee85f8b4568",
 "score": NumberInt(0),   
 "updated_at"▼: ISODate("2015-01-07T15:43:27.28Z"),
}
{
"_id": ObjectId("54ad2bf98ead0e22658b4569"),
"created_at": ISODate("2015-01-07T12:52:09.81Z"),
"post_id": "54ad2bf98ead0e22658b4568",
"score": 0.22106,  
"updated_at": ISODate("2015-01-07T14:20:53.942Z")
}
{
"_id": ObjectId("54accd868ead0e826a8b456a"),
"created_at": ISODate("2015-01-07T06:09:10.920Z"),
"post_id": "54accd868ead0e826a8b4569",
"score": 2.83313,   
"updated_at": ISODate("2015-01-07T08:42:22.116Z")  
```

   }

**Comment by jenssegers** [comment]
Can you post the mongodb query that was executed?

**Comment by karunais13** [comment]
Did you manage to solve the problem? if yes can you post the solution here.

**Comment by luhfilho** [comment]
UP!
I have the same problem...
How to sort by multiple fields?

**Comment by raylight75** [comment]
I have the same problem...

**Comment by luhfilho** [comment]
I solved my problem creating an index with the two columns with the sorting i want.

So, at query i sort from first field and mongo sort from second with index defined

**Comment by andrew-waters** [comment]
+1 for this. Adding a compound index isn't a viable option, particularly when performing arbitrary queries.

**Comment by HassanIbrahim** [comment]
@luhfilho Can you please post a code snippet

**Comment by NominationP** [comment]
+1 Why close

**Comment by Siebov** [comment]
Any updates here?

**Comment by Smolevich** [comment]
@Siebov, let's go to slack community. Link [here](https://github.com/jenssegers/laravel-mongodb/issues/1791)

**Comment by Siebov** [comment]
@Smolevich ty but it's seems that there is no updates for this exact bug. will wait for updates in this thread. have a nice day, 4uvak)
