### ISSUE TITLE
EmbedsMany Relations with whereIn query on array fields

### ISSUE THREAD

**Issue by FlorianWeigang** [jenssegers/laravel-mongodb#395]
Hey,

i tried to get the whereIn - Query working on embed models on an array field.

Example:

``` javascript
// Example Object
{
   'name': 'Flo',
   'likes': [
      {
         'name': 'xy',
         'categories': [1234, 6543, 9873]
      }
   ]
}
```

``` php
$user->likes()->whereIn('categories', [1234, 5678]);
```

But this doesn't work because the Jenssegers\Mongodb\Eloquent\Collection-Model the where-Method on Line 33 create a Filter-Callback which compares the values with an in_array Function:

``` php
case 'in':
   // in_array([1234, 6543, 9873], [1234, 5678]) will always be false
   return in_array($actual, $value);                    
   break;
```

So i just added a few lines of code to get this working:

``` php
case 'in':
   if (is_array($actual)) {
      return count(array_intersect($actual, $value)) > 0; 
   } 

   return in_array($actual, $value);                    
   break;
```

Then i get the right results for me. i just want to let you know :)

Best, Flo

**Comment by askmatey** [comment]
+1

Make a push request

**Comment by robsoncombr** [comment]
Any plan to have this incorporated?
