### ISSUE TITLE
Laravel 5 support?

### ISSUE THREAD

**Issue by lokielse** [jenssegers/laravel-mongodb#398]
hi ~ @jenssegers, I found that laravel-mongodb is not support L5 yet. could you please support some time?

**Comment by Ardakilic** [comment]
+1, I'd love to use this package on Laravel 5.

**Comment by salzamt** [comment]
+1!

**Comment by jenssegers** [comment]
We're working on it.

**Comment by Ardakilic** [comment]
Thanks @jenssegers for the fast response and interest, good luck :+1: !

**Comment by salzamt** [comment]
awesome, thanks a lot and much luck!

**Comment by reallyalok** [comment]
Thanks for your effort @jenssegers . Is it available now or by when it will be available to use.

**Comment by jenssegers** [comment]
Use the 2.1.0 tag. I'm currently working on a 3.x version on the develop branch, but it is no way near stable :)

**Comment by reallyalok** [comment]
Thanks for that quick reply, what do you mean by 2.1.0 tag and 3.x version here, Is that mean I can use with Laravel 5.0.0 to Laravel 5.0.2, or will be better to use L 4.2.x and if we have docs to use that with L 5 versions. Thanks a lot @jenssegers
