### ISSUE TITLE
jenssegers/mongodb migrations for creating unique index on multiple fields

### ISSUE THREAD

**Issue by ridesoft** [jenssegers/laravel-mongodb#399]
I need to create a Laravel migration for a unique key on multiple fields. The Mongodb command i want to map is something like this:
```
db.collection.ensureIndex( { a: 1, b: 1 }, { unique: true })
```
Is it possible with jenssegers/mongodb or with another package?

**Comment by ridesoft** [comment]
Schema::create('collection', function ( $collection ) {
      $collection->unique(array( 'a', 'b' ));
});

**Comment by luharm** [comment]
InsertMany with 'ordered' false not working. Means ignore duplicate and continue to insert not working.
