### ISSUE TITLE
updating model on created-observer

### ISSUE THREAD

**Issue by fraank** [jenssegers/laravel-mongodb#401]
For example I want so change the user, after (!) he has been created:

```
namespace Observers;

class UserObserver
{
public function created($user)
  {
    $user->attribute = "test";
    $user->save();
  }
}
```

This one crashes with this error-message:

> "Mod on _id not allowed"

I'm doing it right now with this ugly quickfix which one is working as expected:

```
namespace Observers;

class UserObserver
{
public function created($user)
  {
    $uuser = \User::find($user->id);
    $uuser->attribute = "test";
    $uuser->save();
    $this->attribute = $uuser->attribute;
  }
} 
```

Maybe a bug on Mongo or this interface?  Maybe it's associated with: jenssegers/laravel-mongodb#190

**Comment by jenssegers** [comment]
Is it possible to add a simple unit test as a pull request? I will look into fixing it.

**Comment by fraank** [comment]
I can do that, but not before the weekend. I'll attach it here as soon as it is finished.

**Comment by jenssegers** [comment]
Could you provide a more detailed stack trace for the error?

**Comment by franquis** [comment]
Got the same issue running MongoDB v2.4.11. 
Please note that when running MongoDB v2.6.9, it works as expected.

    class OrderController {
    	public function createOrder(){
    		$order = new Order();
    		$order->addProduct();
    		...
    		$order->save();
    	}
    }
    
    class Order extends Moloquent {
    	
    	public static function boot(){
            parent::boot();
    
            static::created(function($order) {
    			$order->fees = $order->getFees();
    			$order->save();            
            });
        }
    
        public function getFees(){
        	return ProductFee::where('order_id', $this->id)->sum('amount');
        }
    }

**STACK TRACE**

    ERROR: exception 'MongoCursorException' with message 'mongohost:43440: Mod on _id not allowed' in /vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php:59
    
    Stack trace:
    #0 [internal function]: MongoCollection->update(Array, Array, Array)
    #1 /vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Collection.php(59): call_user_func_array(Array, Array)
    #2 /vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(679): Jenssegers\Mongodb\Collection->__call('update', Array)
    #3 /vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(679): Jenssegers\Mongodb\Collection->update(Array, Array, Array)
    #4 /vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php(436): Jenssegers\Mongodb\Query\Builder->performUpdate(Array, Array)
    #5 /vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(316): Jenssegers\Mongodb\Query\Builder->update(Array)
    #6 /vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Builder.php(36): Illuminate\Database\Eloquent\Builder->update(Array)
    #7 /bootstrap/compiled.php(6874): Jenssegers\Mongodb\Eloquent\Builder->update(Array)
    #8 /bootstrap/compiled.php(6845): Illuminate\Database\Eloquent\Model->performUpdate(Object(Jenssegers\Mongodb\Eloquent\Builder), Array)
    #9 /app/models/Order.php(45): Illuminate\Database\Eloquent\Model->save()
    #10 [internal function]: Order::{closure}(Object(Order))
    #11 /bootstrap/compiled.php(6246): call_user_func_array(Object(Closure), Array)
    #12 /bootstrap/compiled.php(6923): Illuminate\Events\Dispatcher->fire('eloquent.create...', Object(Order))
    #13 /bootstrap/compiled.php(6895): Illuminate\Database\Eloquent\Model->fireModelEvent('created', false)
    #14 /bootstrap/compiled.php(6847): Illuminate\Database\Eloquent\Model->performInsert(Object(Jenssegers\Mongodb\Eloquent\Builder), Array)
    #15 /app/controllers/OrderController.php(75): Illuminate\Database\Eloquent\Model->save()
    #16 [internal function]: OrderController->createOrder()
    { ... }
    #32 /public/index.php(49): Illuminate\Foundation\Application->run()
    #33 {main} []
