### ISSUE TITLE
Query 'like' not working

### ISSUE THREAD

**Issue by Haseeb90** [jenssegers/laravel-mongodb#411]
Hi,
I have the following query but it's not returning anything

$created_at = date("Y-m");

$content = ContentModel::where('userId', $id->_id)
->where('created_at', 'like', "%{$created_at}%")
->orderBy('fav', 'DESC')
->get();

If I remove the ->where('created_at', 'like', "%{$created_at}%") it returns everything fine but I want content that was of this year and month but the query doesn't work when I put that in.

please help

**Comment by Haseeb90** [comment]
The date in the database is ISODate format
"created_at" : ISODate("2015-02-03T16:29:26.965Z")

And I want to find all content of this month 
Select * from content where created_at like '2015-02%'

The above is the SQL versions of the query

**Comment by jenssegers** [comment]
Like generates regexp queries, and I don't thing those work on mongo dates.
