### ISSUE TITLE
Issue Installing With Laravel 5

### ISSUE THREAD

**Issue by Geraden07** [jenssegers/laravel-mongodb#412]
![mongodb-laravel-issue](https://cloud.githubusercontent.com/assets/5994067/6048856/716b5924-ac81-11e4-8b99-1e8603c96b6b.jpg)

**Comment by Geraden07** [comment]
Sorry the screenshot isn't easy to read without zooming in.
Basically issued "composer require jenssegers/mongodb" as instructed in documentation and the requirements could not be resolved to an installable set of packages. Most of the issues seem related to the laravel/framework v5.0.0 dependency (specifically illuminate/events).

**Comment by jenssegers** [comment]
Try the current master branch.

**Comment by tusharvikky** [comment]
This update breaks package for Laravel v4.2.

**Comment by jenssegers** [comment]
Of course. Use the current version tag. The current master will be tagged as a new minor version I think.

**Comment by tusharvikky** [comment]
@jenssegers thanks
