### ISSUE TITLE
Push does not take MongoDate

### ISSUE THREAD

**Issue by alwaysanirudh** [jenssegers/laravel-mongodb#414]
Hi,

I have been facing this issue after the update. I'm Trying to push an array to mongo collection described as follows:
```
$activityItem = [ 'text' => 'blah blah', 'date' => new MongoDate() ];
DB::collection('customers')->where('name', 'XYZ')->push('activity', $activityItem);
```
But I get a error when I run it. 

```
Object of class MongoDate could not be converted.
```

I tried to do a raw query and it did work fine.
I think there is a problem when we try to do a push and Base model tries to convert the data.

**Comment by jenssegers** [comment]
Seems to be ok in the unit tests, can you check commit b31f54a?
