### ISSUE TITLE
Unexpected behavior with same name in route and model relationship

### ISSUE THREAD

**Issue by kimsyversen** [jenssegers/laravel-mongodb#417]
It might be me not knowing something. However, here it comes:

I'm creating an API and the unexpected beahvior comes from using the same name for a relationship method in a model as in the URL

The model
```
    public function presentations()
    {
        return $this->hasMany('Presentation', 'org', 'org');
    }
```
The respective controller has the method:

```
	public function presentations($organisation)
	{
		$limit = Input::get('limit') ?: $this->limit;

		$presentations = Organisation::where('org', '=', $organisation)->paginate($limit);
	}
```

And it can be reached by this route

```
Route::get('organisations/{organisation}/presentations', 'OrganisationsController@presentations');
```

When accessing this route, it seems to also trigger the presentations relationship and thus returning all its data.

Is this actually expected behavior?

**Comment by alexandre-butynski** [comment]
I think that no conflict could appear with the same method name in a controller and in a model. Your issue should come from something else.

Could you past more code (your entire controller method code for example) and your error page/data ?

**Comment by kimsyversen** [comment]
Actually it was me overlooking something very banal. It was expected behavior and nothing wrong with the package.

Anyways, thanks for being helpful :)
