### ISSUE TITLE
Soft deletes not working on embedded documents

### ISSUE THREAD

**Issue by hackel** [jenssegers/laravel-mongodb#422]
If I create an embedded document with soft deletes enabled, add then delete it, the deleted_at field gets set correctly, but it still shows up in results.  If I retrieve the parent document again, the embedded document still appears with the deleted_at attribute.  This is true for both embedsOne and embedsMany.

My research shows that it's not currently possible to filter out the deleted subdocuments in a Mongo query, so it will unfortunately have to be done in PHP.  Hopefully someone can figure out a better solution!

**Comment by jithinjose2** [comment]
+1

**Comment by jenssegers** [comment]
There are some limitations about the current embedded documents implementation, soft deletes is one of them. I hope I can fix these in v3.

**Comment by hackel** [comment]
So...this is fixed now?

**Comment by brosa-design** [comment]
Came across the same issue today - any updates on this?

**Comment by JoeyHoutenbos** [comment]
@jenssegers is this fixed in branch 4.2? Because I'm having this problem in Laravel 4.2 at the moment..

**Comment by dannysood** [comment]
@jenssegers Any update on this?

**Comment by george-viaud** [comment]
This still appears to be a problem in 5.2 ?
