### ISSUE TITLE
embedsOne/Many::associate() does not create timestamps

### ISSUE THREAD

**Issue by hackel** [jenssegers/laravel-mongodb#424]
When using associate() to attach a new embedded document, timestamps are not generated.  If I use save() the timestamps are added as expected.

**Comment by Murwa** [comment]
I think it's because associate doesn't send the document to the DB until you do save on the parent

**Comment by jenssegers** [comment]
Should associate generate timestamps? I don't think so.

**Comment by hackel** [comment]
@jenssegers It should if you've enabled timestamps on that model.  Why don't you think it should?  The developer is setting this option for a reason.

**Comment by jenssegers** [comment]
I could be wrong, but I don't think Eloquent does any timestamp updates when doing associate.

**Comment by hackel** [comment]
It's not that it happens in the associate method itself, but doesn't it do it when it saves the individual model?  A BelongsTo relation is slightly different than an EmbedsOne, of course.  There's really no such thing as an unassociated embedded document, so the only done to attach multiple embedded documents and save them all at once.  I would still like some way to put a timestamp on them.  Of course I could specify this manually, but it seems to me like it should just follow the existing standard for timestamps.
