### ISSUE TITLE
Question: Error trying to connect to MongoDB on Amazon EC2

### ISSUE THREAD

**Issue by tandasima** [jenssegers/laravel-mongodb#429]
Anyone knows what could be causing this? "Failed to connect to: http:0: php_network_getaddresses: getaddrinfo failed: Name or service not known"

Thanks

**Comment by alexandre-butynski** [comment]
We can' help you with so few informations. I currently use MongoDB on EC2 with no problem.

Where your MongoDB instance is located (same instance, other instance, other service like MongoLab...) ? Have you properly installed and configured the php-mongo and the mongodb packages (check php-info) ?
