### ISSUE TITLE
How can i install mongodb on the laravel 5

### ISSUE THREAD

**Issue by BruceYangMan** [jenssegers/laravel-mongodb#432]
I try to install laravel-mongodb to laravel but it happen error message.

    composer require jenssegers/mongodb

your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.0.5
    - jenssegers/mongodb v2.0.0 requires illuminate/events 4.2.* -> satisfiable by illuminate/events[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - jenssegers/mongodb v2.0.1 requires illuminate/events 4.2.* -> satisfiable by illuminate/events[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - jenssegers/mongodb v2.0.2 requires illuminate/events 4.2.* -> satisfiable by illuminate/events[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].
    - jenssegers/mongodb v2.0.3 requires illuminate/events 4.2.* -> satisfiable by illuminate/events[v4.2.1, v4.2.12, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9].

**Comment by jenssegers** [comment]
Made a temp tag for L5.
