### ISSUE TITLE
I have a problem when I use groupBy and distinct

### ISSUE THREAD

**Issue by mdeorue** [jenssegers/laravel-mongodb#433]
Hi, first sorry for my english, and congrats for this package, is awesome!

I have a problem when I use groupBy and Distinct, I have saved in a variable a Jenssegers\Mongodb\Relations\HasMany, because I use in differents functions,
$this->periodScores =  $this->scores()->where('period', $this->period);

For example when I want the average of the scores I only use this $this->periodScores->avg('score'); But in one function I need to Use distinct to get a especify values, when I use that $this->periodScores->distinct('student')->get()->count(); Works fine, but when I need to use again $this->periodScores allways use distinct values. So when I need to reuse $this->periodScores, I dont have the values that I need. Maybe I forgot something, please help me!

Thanks from Chile.

**Comment by askmatey** [comment]
Please add details to narrow the answer set or to isolate an issue that can be answered in a few paragraphs. As it's currently written, it’s hard to tell exactly what you're asking.
