### ISSUE TITLE
problem with "take"+  "remember" ?

### ISSUE THREAD

**Issue by jackbenoit** [jenssegers/laravel-mongodb#435]
Hi,
a random request : 

$query->take(2)->orderBy('date', 'DESC')->remember(10)->get()
it works perfeclty, returns 2 items, and create "a cache".

Later, I execute exactly the same query, but with a different number of results
$query->take(1)->orderBy('date', 'DESC')->remember(10)->get()

it returns me the 2 previous articles from cache, instead of only 1.

Thanks for any help ;)

**Comment by jenssegers** [comment]
Should be fixed on master now.
