### ISSUE TITLE
Paginator not working properly

### ISSUE THREAD

**Issue by geofflancaster** [jenssegers/laravel-mongodb#437]
I'm trying to use the paginate() method to get specific items from the database. When I use "getQueryLog" it does not show that the query uses take() or skip().

I'm having issues with this because I have a large number of records and it seems to be retrieving too many which is causing too much memory to be used.

Does anyone have any ideas about this?

**Comment by jenssegers** [comment]
Are you using any group operations?

**Comment by geofflancaster** [comment]
I'm not using group operations, just order by but the query log shows it's grouping.

```php
MyModel:
public function scopeWithSuccess($query) {
    return $query->withTrashed()->with('user')->where('status', '=', 1);
  }

Service:
$items = MyModel::withSuccess()->orderBy('created_at', 'DESC')->paginate(15, ['id','name']);
dd(\DB::getQueryLog());

Query Log Output:
array (size=2)
  0 => 
    array (size=3)
      'query' => string 'mymodels.aggregate([{"$match":{"$and":[{"status":"1"}]}},{"$group":{"_id":null,"aggregate":{"$sum":1}}}])' (length=105)
      'bindings' => 
        array (size=0)
          empty
      'time' => float 6.74
  1 => 
    array (size=3)
      'query' => string 'mymodels.find({"$and":[{"status":"1"}]},{"id":true,"name":true})' (length=64)
      'bindings' => 
        array (size=0)
          empty
      'time' => float 0.06

**Comment by geofflancaster** [comment]
any ideas of what could be causing this? I'm still having the issue. thanks.

**Comment by jenssegers** [comment]
The builder gets the cursor for all the results, and then calls `skip` on the cursor.

**Comment by jenssegers** [comment]
Try the current version on master.

**Comment by geofflancaster** [comment]
Is it possible to merge this into a branch that is capable of running on laravel 4.2? We have not yet upgraded to 5.0.
