### ISSUE TITLE
Deep nesting cannot delete models at level 2

### ISSUE THREAD

**Issue by Murwa** [jenssegers/laravel-mongodb#438]
I have the following models

Model1
~~~php
use Jenssegers\Mongodb\Model;
class Model1 extends Model {

    public function children() {
        return $this->embedsMany(Model2::class, 'children');
    }
}

~~~

Model2
~~~php
use Jenssegers\Mongodb\Model;
class Model2 extends Model {

    public function grandchildren() {
        return $this->embedsMany(Model2::class, 'grandchildren');
    }
}

~~~

Model1 stores a subdocument of model2 on children; while model2 stores a subdocument of itself on grandchildren. However, when deleting the embeded models, the children gets deleted but not the grandchildren. I took a look at the database and found a structure similar to this:

~~~json
{
   "url": "sgsfgsfgsfg",
   "children": [
     {
        "grandchildren": {
           "0" : {}
        }
     }
   ]
}
~~~

Does it have something to do with the grandchildren being saved as an object as opposed to array structure for the children? Any help will be highly appreciated @jenssegers

**Comment by Carthagian-Traveler** [comment]
I am also experiencing this issue.. how to deal with it!!???

**Comment by Murwa** [comment]
got it to work. thanks to @Carthagian-Traveler
