### ISSUE TITLE
BelongsToMany sync problem

### ISSUE THREAD

**Issue by nabizan** [jenssegers/laravel-mongodb#439]
Hi,

Im working with Laravel 4 and mongodb 2.0.4
I have User and Role class and Im trying to use belongsToMany relation with attach, detach and sync methods

User class

```php
public function roles()
{
    return $this->belongsToMany('Role', null, 'user_ids', 'role_ids');
}
```

Role class

```php
public function users()
{
    return $this->belongsToMany('User', null, 'role_ids', 'user_ids'
}
```

When I run attach method
```php
$user = User::find($id);
$user->roles()->attach(array($role_id));
```
mongodb generate one of the query wrong (or not?)
```
user.update({"_id":{"$id":"54f8d7802228d5e42b000036"}},{"$addToSet":{"role_ids":{"$each":["54f8d7b02228d5e42b000037"]}}},{"multiple":true})

role.update({"_id":["54f8d7b02228d5e42b000037"]},{"$addToSet":{"user_ids":{"$each":["54f8d7802228d5e42b000036"]}}},{"multiple":true})
```

user collection is updated but role collection stay intact. 
It should generate query like this?
```
role.update({"_id":{"$id":"54f8d7b02228d5e42b000037"}},{"$addToSet":{"user_ids":{"$each":["54f8d7802228d5e42b000036"]}}},{"multiple":true})
```

This problem is present with both attach and detach methods. Only sync runs correctly. But only if there is one element. If you run sync on multiple elements one of the collections stays always intact because of wrong query.

Am I missing something or there is really a problem with this relation?
Any help would be great. Thank you

**Comment by nabizan** [comment]
Hello, can anybody look at this?

**Comment by nabizan** [comment]
Hello?

**Comment by jenssegers** [comment]
I will try to take a look at it this weekend. It would be helpful if you could provide a small unit test snippet that shows this problem.

**Comment by nabizan** [comment]
Hi thank you. I have just checked your belongsToMany tests in RelationsTest and of course they are all passing.

I will create ma own test at sunday probably. 

Meantime if you have some spare time I would be more than happy if you take a look at this even without my test. Maybe I have misunderstand logic behind this. Thank you

**Comment by nabizan** [comment]
Hi, those are two failing unit tests. 8d06ac5342b00705e2dd7a78ea84368a3c7ed697 
Please take a look at them. Thank you

**Comment by nabizan** [comment]
Any update on this issue?

**Comment by jenssegers** [comment]
It took a while to debug the problem, but it is fixed now :)

**Comment by nabizan** [comment]
nice. I can confirm that fix is ok. Thank you
