### ISSUE TITLE
Paginate not working

### ISSUE THREAD

**Issue by JDurrah** [jenssegers/laravel-mongodb#440]
Hi
my query simply is:
![screenshot_1](https://cloud.githubusercontent.com/assets/3740671/6522714/b37a82f0-c3f0-11e4-83ca-94fdc345982c.png)

and the generated query is:
![screenshot_2](https://cloud.githubusercontent.com/assets/3740671/6522717/bd84eec0-c3f0-11e4-82b8-efb6c977fd90.png)

**Comment by jenssegers** [comment]
What version are you using?

**Comment by JDurrah** [comment]
It was 2.0.3.

**Comment by jenssegers** [comment]
It is using the cursor to skip and take the items from the results. I just pushed a new version that uses the aggregation framework which works better for large data sets.
