### ISSUE TITLE
PHP MongoDate toDateTime default timezone

### ISSUE THREAD

**Issue by aleplusplus** [jenssegers/laravel-mongodb#441]
The problem is the change in method DatabaseTokenRepository getPayload

getPayload protected function ($ email, $ token)
{
return ['email' => $ email, 'token' => $ token, 'created_at' => new MongoDate];
}

when using MongoDate think the timezone of MongoDate default is UTC

as explained here:

When I create new DateTime object, it has timezone from "date.timezone" setting:

print_r (new DateTime ());

DateTime Object
(
    [Date] => 03/02/2015 03: 19: 50.000000
    [Timezone_type] => 3
    [Timezone] => Europe / Moscow
)

But when i get DateTime object from MongoDate, it has UTC timezone:

print_r ((new MongoDate ()) -> ToDateTime ())

DateTime Object
(
    [Date] => 03/02/2015 00: 19: 50.000000
    [Timezone_type] => 1
    [Timezone] => +00: 00
)

How can I setup MongoDate to create DateTime objects with my default timezone?

http://stackoverflow.com/questions/28800996/php-mongodate-todatetime-default-timezone

Tomarce should consider the timezone of app.php as does new Carbon. in the modified part.

**Comment by Murwa** [comment]
Mongo date has no timezone; that means the created_at field should assume the server's timezone. When converting from MongoDate to DateTime, u'll have to set the target timezone.

**Comment by aleplusplus** [comment]
I'm running everything locally so it should take my time zone but is keeping the default UTC

**Comment by Murwa** [comment]
From the [docs](http://php.net/manual/en/class.mongodate.php)
>MongoDB stores dates as milliseconds past the epoch. This means that dates do not contain timezone information

With a created_at field, you do not need to store the timezone in the db; coz all you need is to add the tz information to your DateTime object and can be set in the .ini file or using [date_default_timezone_set](http://php.net/manual/en/function.date-default-timezone-set.php)

Either way, you now do 

~~~php
print_r((new \MongoDate())->toDateTime()->setTimezone(new \DateTimeZone(date_default_timezone_get())))
~~~

**Comment by Murwa** [comment]
Hope it worked!

**Comment by emeno89** [comment]
Easiest way:

//$mongoDate from db

$dateTime = new \DateTime();
$dateTime->setTimeStamp($mongoDate->sec);

**Comment by camohub** [comment]
The default timezone should be set in ->toDateTime() call. And only if is necessary to set another timezone it should be set up manually.

**Comment by gorcer** [comment]
> $mongoDate->sec

Mongo date does't have sec attribute.
