### ISSUE TITLE
Relationship query

### ISSUE THREAD

**Issue by tusharvikky** [jenssegers/laravel-mongodb#443]
Hello,

I have been eagerloading with 'with', I just wanted to ask how can i query the relationship and only grab those records which has relationships not returning null. 

I am using hasOne and belongsToMany relationship.

Regards

**Comment by giolvani** [comment]
I'm also try it. I have many records that the foreign key doesn't exists anymore.

+1

**Comment by jenssegers** [comment]
Does `has` work?

**Comment by tusharvikky** [comment]
@jenssegers 

The problem here is i'm querying in a relation. And if relation query satisifies only then fetch the relation
```
Test::where('isCompleted', true)
							->with(['qpaper' => function($query)
								{
								    $query->where('isPrivate', false);
								}])
							->get();
```
Do you recommend a solution?
