### ISSUE TITLE
Access Level to EmbedsOneOrMany::getQualifiedParentKeyName()

### ISSUE THREAD

**Issue by alfchee** [jenssegers/laravel-mongodb#446]
Hi,

I'm using Laravel 4.2 with laravel-mongodb ~2.0. I'm beginning to use it and I create a embedded relationship for telephones for a document, but following the documentation I obtain this error from Laravel when I ask something like ```$model->telephones```: 

```Access level to Jenssegers\Mongodb\Relations\EmbedsOneOrMany::getQualifiedParentKeyName() must be public (as in class Illuminate\Database\Eloquent\Relations\Relation)```

And changing that method to ```public``` works without problem.

Greetings

**Comment by jenssegers** [comment]
Is this still an issue if you update the package?
