### ISSUE TITLE
Authentication Laravel 5

### ISSUE THREAD

**Issue by ldynia** [jenssegers/laravel-mongodb#447]
Hi Jens. 

Grate work with the pluginn. It is awesome!! 

Just for your information there is an issue with authentication of a user in Lararavel 5 while using 'database' driver - specified in config/auth.php . User cannot loging due to the "_id" that starts with "_" -underscore This is due to below check
```php
//  GenericUser.php
public function getAuthIdentifier(){
		return $this->attributes['id'];
}
```
Nevertheless, authentication works fine with dirver set to 'eloquent'
```php
// GenericUser.pph
'driver' => 'eloquent',
```
Cheers!

**Comment by tayyabkhanrind** [comment]
Is it working for laravel 5? it's not working on my side

**Comment by ldynia** [comment]
Yes it is working

**Comment by askmatey** [comment]
This is not an issue and should be closed.
