### ISSUE TITLE
Unsupported driver [mongodb] - I've tried everything I found

### ISSUE THREAD

**Issue by pauloallex24** [jenssegers/laravel-mongodb#452]
Hi. I'm getting the error

InvalidArgumentException in ConnectionFactory.php line 191:
Unsupported driver [mongodb]

If I run php -i | grep MongoDB, I get "MongoDB Support => enabled".
I've made everything from the tutorial.
I just have this controller and if I delete the query, everything works fine.

<?php namespace App\Http\Controllers;
class HomeController extends Controller {
    public function __construct()
    {
        $this->middleware('guest');
    }
    public function index()
    {
        $messages = \DB::collection('messages')->get();
        return view('home');
    }
}

I'm sure that the DB credentials are right and I've changed the default and placed the provider on app.php.
Any ideia from where I can go now?
I'm using Laravel 5.

**Comment by jenssegers** [comment]
At first sight, it looks like your service provider is not registered correctly.

**Comment by pauloallex24** [comment]
Can you explain it better please?

**Comment by jenssegers** [comment]
The only thing I can suggest with this information is to double check your default connection and the service provider.

**Comment by pauloallex24** [comment]
Solved. You were right. Yesterday I was really tired and I've placed the string on the aliases and not on the providers. I'm really sorry and thanks for the help.
You havbe made an amazing work!
Regards

**Comment by CloudS-Hu** [comment]
i have the same question , how are you solved? thank you very much

**Comment by pauloallex24** [comment]
Hi. Sorry for the late response, hope you already solved it.
I've not much to say, but I think that it was because I have the Class string inside the Aliases array and not the Providers array.
