### ISSUE TITLE
(question) is this plugin compatible mongodb 3 - wiredtiger base ?

### ISSUE THREAD

**Issue by jackbenoit** [jenssegers/laravel-mongodb#453]
Hi, 

Is the plugin currently compatbile wih a mongo 3  - wiredtiger  base ?
not speaking of any adanced feature, just does the connexion & simple queries work or everything is broken ?

thx for you answer  (sry i dont find this information)

**Comment by jenssegers** [comment]
You can test it by running the unit tests. Let me know if it works.
