### ISSUE TITLE
laravel-mongodb not installable on laravel 4.2?

### ISSUE THREAD

**Issue by daPhantom** [jenssegers/laravel-mongodb#454]
I just setup a completely fresh laravel installation via composer and tried to add laravel-mongodb via "composer require". I receive the following error message(s). Does anyone of you know how to fix this?

http://i.imgur.com/BxlZnqa.png

**Comment by daPhantom** [comment]
Setting the minimum-stability to "dev" does not help as well...

My composer.json:

>{
	"name": "xxx/yyy",
	"description": "yyy",
	"keywords": ["yyy", "zzz"],
	"license": "MIT",
	"require": {
		"laravel/framework": "4.2.*"
	},
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "dev"
}

**Comment by daPhantom** [comment]
I found a way to get it working... So the tutorial does not work ;)
composer require jenssegers/mongodb:2.0.4

**Comment by anoopj1** [comment]
If you are using Laravel 5 then tutorial is working
Im my case L4.2
composer require jenssegers/mongodb:2.0.4
