### ISSUE TITLE
paginate getCurrentPage query builder undefined

### ISSUE THREAD

**Issue by tusharvikky** [jenssegers/laravel-mongodb#455]
hey,

I'm querying relationship, the query works but there is some problem with the getCurrentPage function.

```
                        $tests = Test::newest();

			$tests->with(['qpaper' => function($query) {
							$query->where('conditionXYZ', false);
							$query->orWhere('author_id', $this->user->id);
						}]);

			$tests->paginate(10);
```
if I ```dd($tests->paginate(10)->getCurrentPage());``` It gives me correct result. 
But ```dd($tests->getCurrentPage());``` throws ```Call to undefined method Jenssegers\Mongodb\Query\Builder::getCurrentPage() ```

EDIT: However, 
``` $tests = $tests->paginate(10); ``` 
Then ```getCurrentPage()``` is working all fine.

Why?

**Comment by jenssegers** [comment]
In Laravel 5 this is `currentPage()`

**Comment by tusharvikky** [comment]
This issue is with L4.

**Comment by tusharvikky** [comment]
Does this has something to do with #443 ?
