### ISSUE TITLE
relationship query not generating proper query

### ISSUE THREAD

**Issue by geofflancaster** [jenssegers/laravel-mongodb#456]
When I query across two different databases, an invalid query is being created. It is querying the first DB properly and then the query to the second DB is incorrect.

```
array (size=1)
  0 => 
    array (size=3)
      'query' => string 'model2.find({"$and":[{"model2.deleted_at":null},{"model2.key":{"$in":["key1","key2","key3","key4"]}}]},[])' (length=170)
      'bindings' => 
        array (size=0)
          empty
      'time' => float 0.05
```

```
class Model1 extends Eloquent {
protected $connection = 'db1';

public function children() {
return $this->hasMany('Model2', 'key', 'key');
}
}

class Model2 extends Moloquent {
protected $connection = 'db2';

public function parent() {
return $this->belongsTo('Model', 'key', 'key');
}
}
```

If I try to run the query manually I get no results. However, if I remove the collection declarations within the $and portion of the query and run it, it works correctly.

Any ideas?

**Comment by geofflancaster** [comment]
Any ideas on this one @jenssegers?

**Comment by askmatey** [comment]
Please add additional details. I can not reproduce this behavior. What version of Laravel are you using?

**Comment by geofflancaster** [comment]
4.2
