### ISSUE TITLE
Can this work alongside mysql and Eloquent?

### ISSUE THREAD

**Issue by kirkbushell** [jenssegers/laravel-mongodb#457]
We're currently looking at an alternative data store (mongo) to handle complex EAV requirements for a few of our models. MySQL just doesn't handle this well.

We need a mongo solution to work alongside Eloquent, rather than replace it - will this work?

**Comment by danpecher** [comment]
I comfortably use Doctrine ODM with Laravel.

**Comment by kirkbushell** [comment]
Not what I asked. At all =\

**Comment by danpecher** [comment]
oh sry

**Comment by alexandre-butynski** [comment]
Yes, this package can do it ! Read this section of the doc : https://github.com/jenssegers/laravel-mongodb#mysql-relations.

Anyway, you just can choose to extends `Jenssegers\Eloquent\Model` or `Illuminate\Database\Eloquent\Model` to use this package or the standard Eloquent.
