### ISSUE TITLE
Login Error Auth

### ISSUE THREAD

**Issue by ahmadsururi** [jenssegers/laravel-mongodb#458]
I tried to make the login but after I click submit error like this. I've fixed according to:
https://github.com/jenssegers/laravel-mongodb#troubleshooting

Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Grammars\Grammar, null given, called in E:\xampp\htdocs\skripsi\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 1899 and defined

but still can't. How do I fix it thank you.
In addition, I've set the default mongoDB connection.

**Comment by askmatey** [comment]
Please clarify your specific problem or add additional details to highlight exactly what you need. As it's currently written, it’s hard to tell exactly what you're asking.

Otherwise, this issue should be closed.

**Comment by jenssegers** [comment]
Double check your service provider registration and the connection your model is using.

**Comment by zeusent** [comment]
Hey!

I'm having the same problem. Using the built in register/login screens I get this error:

>**ErrorException in Builder.php line 198:**
>Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of Illuminate\Database\Query\Grammars\Grammar, null given, called in /var/www/waibleapp.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1883 and defined

even though my User model looks like this:

````
use Jenssegers\Mongodb\Model as Eloquent;

class User extends Eloquent {
    protected $connection = 'mongodb';
}
````

Am I missing something?

**Comment by zeusent** [comment]
Never mind my last comment!

I've fixed it by changing the default `User` class and make it extend `Jenssegers\Mongodb\Model`instead of `Model`.
