### ISSUE TITLE
Getting only one sub document

### ISSUE THREAD

**Issue by sameer1750** [jenssegers/laravel-mongodb#461]
So I have a product document which has a nested images document. The structure is like this:

{
    "_id" : ObjectId("551e617eccfff2fc193c9869"),
    "currency" : "US DOllar",
    "images" : [
        {
            "filename" : "551e617eccfff2fc193c9869_logo-big.jpg",
            "height" : NumberLong(500),
            "width" : NumberLong(500),
            "updated_at" : ISODate("2015-04-07T10:35:10.142Z"),
            "created_at" : ISODate("2015-04-03T09:53:31.168Z"),
            "_id" : ObjectId("551e631bccfff278173c9869"),
            "deleted_at" : ISODate("2015-04-03T09:53:43.102Z")
        },
        {
            "filename" : "551e617eccfff2fc193c9869_sameer.jpg",
            "height" : NumberLong(500),
            "width" : NumberLong(500),
            "updated_at" : ISODate("2015-04-03T10:00:39.969Z"),
            "created_at" : ISODate("2015-04-03T10:00:39.969Z"),
            "_id" : ObjectId("551e64c7ccfff200173c9869")
        }
    ],
    "is_active" : "1",
    "updated_at" : ISODate("2015-04-07T08:05:15.932Z"),
    "created_at" : ISODate("2015-04-03T09:46:38.340Z"),
}

Now I want only one sub document, i.e. image whose filename is "551e617eccfff2fc193c9869_logo-big.jpg" along with the whole document. How can I do that?

**Comment by sameer1750** [comment]
I know how to do it in mongo 
Ie.db.products.find({"images.filename":"551e617eccfff2fc193c9869_logo-big.jpg"},{"images.$.filename":1,"currency":1}).pretty()

But how to execute it with this package?

**Comment by jenssegers** [comment]
Since a recent PR, the `project()` method was added. You can give it a try.
