### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by RemiCollin** [jenssegers/laravel-mongodb#463]
When running a transaction through the mongodb driver, laravel returns an exception.

Is it possible to support them on a MongoDB database ?

**Comment by jenssegers** [comment]
Transactions are not support at this moment.

**Comment by RemiCollin** [comment]
In that case, maybe it would be cleaner to throw a more explicit exception from the child Connection class, what do you think ?

**Comment by lukepolo** [comment]
:+1: , i may work on this soon. As I will be needing this for testing ~

**Comment by JoeyHoutenbos** [comment]
Would love to see this feature =)

**Comment by chasen** [comment]
:+1:

**Comment by nabizan** [comment]
what is the status of this feature?

**Comment by lukepolo** [comment]
you can just do this public function beginDatabaseTransaction()
    {
        $this->app->make('db')->beginTransaction();
        $this->app->make('db')->connection('legacy')->beginTransaction();

        $this->beforeApplicationDestroyed(function () {
            $this->app->make('db')->rollBack();
            $this->app->make('db')->connection('legacy')->rollBack();
        });
    }

**Comment by ddctd143** [comment]
Trying to port Baum\Baum nested sets to use jenssegers/laravel-mongodb
, but they are using transactions and they aren't supported by this mongodb implementation.

**Comment by korobkadima** [comment]
what is the status of this feature?

**Comment by Clem01** [comment]
Do you plan to set up this next feature? It seems to me to be an indispensable feature. I found this package but it didn't try it: https://github.com/matryoshka-model/mongo-transactional

**Comment by sathishkumarls** [comment]
:thumbsup:

**Comment by CHOMNANP** [comment]
Anyone manage to get this work yet?

Thanks,
Punleu

**Comment by YuriScarbaci** [comment]
Need just this feature to migrate from mySql database to the MongoDB database,
Any news on it, is some1 looking to implement this or is it just forgotten?
any work around to grant my application atomocity on multiple documents and operations?

**Comment by salalaslam** [comment]
https://github.com/jenssegers/laravel-mongodb/issues/1334#issuecomment-475139754
