### ISSUE TITLE
Dealing with integers, NumberLong, etc.

### ISSUE THREAD

**Issue by hackel** [jenssegers/laravel-mongodb#464]
I was having trouble retrieving records with simple where queries, and I discovered that the PHP mongodb driver will automatically send integers to MongoDB as NumberLong().  I learned that I can disable this with the php option `mongo.native_long = 0`, but this revealed a different problem.  Queries from laravel-mongodb are quoting the integer, and so the queries return no results.  Removing the quotes around the integers causes the queries to return the expected results.

`categories.find({"$and":[{"deleted_at":null},{"type":"1"}]},[])` Does not work.
`categories.find({"$and":[{"deleted_at":null},{"type":NumberLong(1)}]},[])` works without the php config change, otherwise `categories.find({"$and":[{"deleted_at":null},{"type":1}]},[])` works fine.

I'm not sure what the best solution to this problem is, as it seems highly dependent on one's configuration and whether one is running a 32-bit OS or not.  You could add a config option to specify a wrapping function for integers and then check each where value to see if it's an int?  Not sure if this wouldn't cause additional problems, though.

**Comment by hackel** [comment]
Adding the following to Builder::compileWheres() seems to have fixed the issue for me (with mongo.native_long disabled), but I'm uncertain if there could be other side-effects.
```php
if (isset($where['value']) and is_numeric($where['value']))
{
    $where['value'] = $where['value'] + 0;
}
```
Also I just realized that I need to add a case for multiple values as well.  If you think this solution is appropriate I can make a PR for it.

**Comment by jenssegers** [comment]
When I'm looking at the query log, I don't see integers being converted to strings: `users.find({"age":{"$gte":0,"$lte":25}},[])`

**Comment by hackel** [comment]
I think it's because the integers are coming from an input form, which sends everything as a string.

**Comment by jenssegers** [comment]
Try using the new attribute casting to cast strings to integers: http://laravel.com/docs/master/eloquent#attribute-casting

**Comment by hackel** [comment]
I tried casting the field to an integer in my model, but it had no effect.

The problem is in the generated query itself.  MySQL doesn't care if you say `WHERE val=1` or `val="1"`, it treats them the same, so unfortunately many packages are designed with this assumption.  That's why I think some kind of automatic conversion within the MongoDB query builder would be appropriate.  I can use Input::merge() to cast each integer query parameter manually, but this is a major pain.

Here is my solution:
https://github.com/jenssegers/laravel-mongodb/compare/master...hackel:cast-numerics-in-wheres

Another option might be to check the $casts array in the model, and then automatically apply those casts before running the query.

Unfortunately the problem also exists for saving, but that is easier to correct using a simple mutator to manually cast the value as an integer.
