### ISSUE TITLE
Can't canonicalize query: BadValue $regex has to be a string

### ISSUE THREAD

**Issue by gidomanders** [jenssegers/laravel-mongodb#465]
I'm trying to make a filter to get some data out of my MongoDB using a regex. In the tutorial for this plugin I found this:

```
User::where('name', 'regex', new MongoRegex("/.*doe/i"))->get();
```

So my code looks like this:

```
School::where('name', 'regex', new MongoRegex("/haags/i"))->get();
```

But the result is empty. When I output the query it looks like this:

```
db.schools.find({"name":{"$regex":{"regex":"haags","flags":"i"}}})
```

And when I use that query in the console it says:

```
error: {
    "$err" : "Can't canonicalize query: BadValue $regex has to be a string",
    "code" : 17287
}
```

I also tried:

```
School::where('name', 'regexp', "/haags/i")->get();
```

But that gave me this query:

```
schools.find({"name":{"$regex":"\/haag\/i"}})
```

which apparently escapes the forward slash and makes the regex invalid. And besides that, a regex should not be between quotes or it should be something like this (found in the MongoDB manual):

```
db.products.find( { description: { $regex: /^S/, $options: 'm' } } )
```

So there is a problem in the conversion to MongoDB query or I'm doing something wrong. Can someone please tell me what it is?

**Comment by jenssegers** [comment]
That is weird, this should be tested in the unit tests, what version of mongo are you using?

**Comment by gidomanders** [comment]
Using `db.version()` in the console gives me 2.6.8. Using `mongod --version` results in 
```
2015-04-12T15:18:25.341+0000 git version: 3abc04d6d4f71de00b57378e3277def8fd7a6700
```

**Comment by raw34** [comment]
I got the same problem, is there a solution?

My MongoDB shell version: 2.4.12

**Comment by gidomanders** [comment]
Any update on this?

**Comment by jenssegers** [comment]
Do you have an example of a MongoDb query that does work with your regex?

**Comment by gidomanders** [comment]
`db.schools.find({"name":{"$regex":/haag/i}})` works, you see there's no quotes around the expression.

**Comment by eswarreddy43** [comment]
I am also facing the same issue with double slashes. Eloquent is adding that slashes. 

Is there any way to escape those slashes?

**Comment by zamanianb** [comment]
I have similar issue

**Comment by bsarraf** [comment]
I had the same issue, after debugging I figured that this error was being thrown when I was trying to apply regex on a null value. Please make sure your variable on which you are applying the regex is not null
