### ISSUE TITLE
$where operator

### ISSUE THREAD

**Issue by kahmaly** [jenssegers/laravel-mongodb#469]
Is there a way to use mongo $where operator?

**Comment by askmatey** [comment]
>**Wheres**
>
>     $users = User::where('votes', '>', 100)->take(10)->get();

[Examples](https://github.com/jenssegers/laravel-mongodb#examples)

Please clarify your specific problem or add additional details to highlight exactly what you need. As it's currently written, it’s hard to tell exactly what you're asking. Since this is not a bug, it should be closed.

**Comment by kahmaly** [comment]
In the following link you will find a section talking about mongo specific operators
[mongo specific operators](https://github.com/jenssegers/laravel-mongodb#mongodb-specific-operators)
in which you will find that there is an operator called where

Example in mongo:
db.users.find({"$where":"/3/.test(this.age)"}); 
this would get all users with a digit 3 in their age(int)

**Comment by jenssegers** [comment]
The where operator is used by default when doing `->where`
