### ISSUE TITLE
SoftDelete does not work with all query

### ISSUE THREAD

**Issue by bastiendonjon** [jenssegers/laravel-mongodb#477]
Hello,

If I'm not mistaken, SoftDelete with deleted_at value does not work with all query. All items returned ...

I use "use SoftDeletes" in my model. And delete method to remove item.

**Comment by alquesadilla** [comment]
any updates ? Were you able to solve your issue?

**Comment by jovanialferez** [comment]
one thing i noticed, by watching the logs (query), it uses the alias or collection name together with the `deleted_at`, which generally a non-existent field (e.g. `my_collection.deleted_at` vs just `deleted_at`) in that collection

**Comment by jovanialferez** [comment]
i found out the issue. this happens when you `use` `SoftDeletes` trait from Laravel, not from this library. so it should be from `Jenssegers\Mongodb\Eloquent\SoftDeletes`.
