### ISSUE TITLE
Date is retrieved as MongoDate instead of Carbon/DateTime

### ISSUE THREAD

**Issue by zeusent** [jenssegers/laravel-mongodb#478]
Hi!

So I'm using your module on a Laravel 5 installation. I have this little model defined:
````
namespace App\Classes\Model;
	
use Moloquent;

class ApiStats extends Moloquent {

	protected $collection = 'apistats';
	protected $dates = ['date'];
	
}
````

Now my problem is that whenever I'm retrieving one of this items from the DB the date attribute is a `MongoDate` instance and not a `Carbon` or `DateTime` instance (or better yet a `Jenssegers\Date\Date` instance).

Am I missing something?

**Update**

So I've figured out that if I load all the records in the DB like this
````
$all = ApiStats::all();
````
it seems to work.

But if I do it like 
````
$all = DB::collection('apistats')->get();
````
it doesn't.

What's more curious about it is that in the later $all is an array of arrays not `ApiStats` objects.

**Comment by jenssegers** [comment]
That is normal behaviour because it is not going through Eloquent.
