### ISSUE TITLE
DBReff

### ISSUE THREAD

**Issue by buszito** [jenssegers/laravel-mongodb#479]
Hello,
How can I implement DBRef mechanism using laravel-mongodb?
And for ex. if I have array of DBRef in Document how can I add/remove it using Laravel 5 mechanisms?

**Comment by approached** [comment]
:+1:  I have the same question.

I  think you mean http://docs.mongodb.org/manual/reference/database-references/#dbref-explanation
I would use the same feature. But think this feature is not available in this module.

**Comment by nenodias** [comment]
[Link](https://github.com/jenssegers/laravel-mongodb/issues/562)
