### ISSUE TITLE
question: How to get an ID of a (inserted/updated/deleted) record using Query Builder?

### ISSUE THREAD

**Issue by AleksMeshkov** [jenssegers/laravel-mongodb#48]
Could you please help me?

`DB::connection('mongodb')->collection('apiRequests')->insert($entry);`

How to get that record ID?

PS: `DB::getPdo()->lastInsertId();` doesn't works :(

**Comment by yefriddavid** [comment]
In laravel is this in the model of Eloquent (->getKey())

**Comment by yefriddavid** [comment]
namespace App\Models\MongoDB\Cases;
use Jenssegers\Mongodb\Model as Eloquent;

class MyModel extends Eloquent {
    protected $collection = 'xxxtableMongo';
    protected $connection = 'mongodb';
}


in controller

$myModel->save()
$myModel->getKey();
