### ISSUE TITLE
Running a map reduce & other native command?

### ISSUE THREAD

**Issue by Grummfy** [jenssegers/laravel-mongodb#482]
Hello,
is there a way to run a map reduce?
in native php we do this : http://php.net/manual/en/mongodb.command.php#example-1469

So is there a way to do it?

thanks

**Comment by ohmance** [comment]
You could just pull the MongoClient from the DB object and then do the exact same thing:
`$db = DB::connection('mongodb')->getMongoClient();`
 `$db->command(['mapreduce' => .... ]);`

**Comment by Grummfy** [comment]
yep, it's what I have done, but I think it could be a good improvements.

**Comment by renatobecker** [comment]
Hi
I'm trying to use this command, but I get the following error:

"Call to undefined method MongoClient::command()"

What's wrong?

**Comment by Grummfy** [comment]
for information I use this one : 

    DB::connection('mongodb')->command(....)

**Comment by renatobecker** [comment]
Hi @Grummfy 

It works!
Thank you very much.

**Comment by vincentshiqi** [comment]
i use
```
$near = [doubleval($la_x), doubleval($la_y)];
        $data = $mongodb->command([
            'geoNear'   =>  'vincent',
            'near'      =>  $near,
            'spherical' =>  true
        ]);
```
but it's work
and give me 

```
array(2) { ["ok"]=> float(0) ["errmsg"]=> string(13) "can't find ns" }

```
who can help me

**Comment by gnrcampos** [comment]
@vincentshiqi your command seems to be not properly set up. Check this example and let me know if you can't use it. $p_Lat, $p_Long and $p_Dist are raw numbers.
```
$v_Point = [
    'type' => 'Point',
    'coordinates' => [$p_Lon, $p_Lat]
];
  $v_Results = DB::connection('mongodb')->getMongoDB()->command([
    'geoNear' => 'coordinates',
    'near' => $v_Point,
    'spherical' => true,
    'distanceField' => 'dist',
    'maxDistance' => $p_Dist,
    'limit' => 5
]);
```

**Comment by fabiel-leon** [comment]
> for information I use this one :
> 
> ```
> DB::connection('mongodb')->command(....)
> ```

@Grummfy could you post an example with mapReduce
