### ISSUE TITLE
Using attribute name in function with same name

### ISSUE THREAD

**Issue by daPhantom** [jenssegers/laravel-mongodb#484]
Hey Jens,

I got a model that has the attribute "features" in it's mongo document. Now I create a public function within the model which is called `features()`. If I now use `$this->features` inside this function I receive the following error:

```
Undefined property: xxx\FooBar::$features (View: /var/www/xxx/resources/views/foobar.blade.php)
```

I figured that it might be related to the magic function calling from Laravel. Do you know more regarding this topic? I would love to call that function this way since it's merging some data from joined Models so I can't work on the attribute $foobar->features directly.

```
at HandleExceptions->handleError('8', 'Undefined property: xxx\FooBar::$features', '/var/www/xxx/app/Foobar.php', '45', array()) in Foobar.php line 45
at Foobar->features() in Model.php line 240
at Model->getAttribute('features') in Model.php line 3263
at Model->__get('features') in Foobar.php line 45
at Foobar->features() in f916cf457953d0604c10d415ab79e8c3 line 7
```

**Comment by spawn-guy** [comment]
$this->attributes['features']

**Comment by daPhantom** [comment]
Thanks spawn-guy. But that does not explain why I can't use the same name.

Is it better to always use $entity->attributes['features'] instead of $entity->features? Or is there not difference at all?

**Comment by darkeus** [comment]
@daPhantom i dont know why you u make a make a function with the same name as your attribute, but what i can say is, __get magic in model will call Model->getAttribute('features');
that have a function like this

`public function getAttribute($key)
	{
		$inAttributes = array_key_exists($key, $this->attributes);

		// If the key references an attribute, we can just go ahead and return the
		// plain attribute value from the model. This allows every attribute to
		// be dynamically accessed through the _get method without accessors.
		if ($inAttributes || $this->hasGetMutator($key))
		{
			return $this->getAttributeValue($key);
		}

		// If the key already exists in the relationships array, it just means the
		// relationship has already been loaded, so we'll just return it out of
		// here because there is no need to query within the relations twice.
		if (array_key_exists($key, $this->relations))
		{
			return $this->relations[$key];
		}

		// If the "attribute" exists as a method on the model, we will just assume
		// it is a relationship and will load and return results from the query
		// and hydrate the relationship's value on the "relationships" array.
		if (method_exists($this, $key))
		{
			return $this->getRelationshipFromMethod($key);
		}
	}`

now you see there is 
`if (method_exists($this, $key))
{
	return $this->getRelationshipFromMethod($key);
}`


that will check your model class when u call $this->features , the selection code above will add relations attribute to model, hope it answer your question =D

**Comment by spawn-guy** [comment]
@daPhantom to understand recursion you need to understand recursion.
also this is not a Moloquent issue.

**Comment by daPhantom** [comment]
Well this is kind of a recursion issue - you are right. However you are not right in pointing out that this isn't a Moloquent issue since it is. Check the code provided by darkeus and read the comment regarding the last if:

```
   // If the "attribute" exists as a method on the model, we will just assume
   // it is a relationship and will load and return results from the query
   // and hydrate the relationship's value on the "relationships" array.
```

But what I don't get is that the first if should already be returning the value instead of the last if returning the relation and therefore perform an early exit. 

The error I receive in the end is total useless and does not point to the root of this issue which is reflection.

**Comment by darkeus** [comment]
@daPhantom sorry i have a few code that i forget to post here, the function getAttribute i post above is from \Illuminate\Database\Eloquent\Model.php and yet i dont notice there is a override function in \Jenssegers\Mongodb\Model ,here the code

	/**
     * Get an attribute from the model.
     *
     * @param  string  $key
     * @return mixed
     */
    public function getAttribute($key)
    {

        // Check if the key is an array dot notation.
        if (str_contains($key, '.'))
        {
            $attributes = array_dot($this->attributes);

            if (array_key_exists($key, $attributes))
            {
                return $this->getAttributeValue($key);
            }
        }

        $camelKey = camel_case($key);

        // If the "attribute" exists as a method on the model, it may be an
        // embedded model. If so, we need to return the result before it
        // is handled by the parent method.
        if (method_exists($this, $camelKey))
        {
            
            $relations = $this->$camelKey();
            // This attribute matches an embedsOne or embedsMany relation so we need
            // to return the relation results instead of the interal attributes.
            if ($relations instanceof EmbedsOneOrMany)
            {
                // If the key already exists in the relationships array, it just means the
                // relationship has already been loaded, so we'll just return it out of
                // here because there is no need to query within the relations twice.
                if (array_key_exists($key, $this->relations) && !$this->serialized)
                {
                    return $this->relations[$key];
                }
                
                // Get the relation results.
                return $this->getRelationshipFromMethod($key, $camelKey);
            }
        }
        
        return parent::getAttribute($key);
    }


you see in moloquent it is checking the method first then return the method value if exists, but on \Illuminate\Database\Eloquent\Model.php getAttribute() it will check the attribute first instead of method_exists function, this is because moloquent extends from \Illuminate\Database\Eloquent\Model.php and using it parent function at the end of function , instead of adding some logic like its parent 

	$inAttributes = array_key_exists($key, $this->attributes);

    // If the key references an attribute, we can just go ahead and return the
    // plain attribute value from the model. This allows every attribute to
    // be dynamically accessed through the _get method without accessors.
    if ($inAttributes || $this->hasGetMutator($key))
    {
        return $this->getAttributeValue($key);
    }

    // If the key already exists in the relationships array, it just means the
    // relationship has already been loaded, so we'll just return it out of
    // here because there is no need to query within the relations twice.
    if (array_key_exists($key, $this->relations))
    {
        return $this->relations[$key];
    }

before the

        $camelKey = camel_case($key);

        // If the "attribute" exists as a method on the model, it may be an
        // embedded model. If so, we need to return the result before it
        // is handled by the parent method.
        if (method_exists($this, $camelKey))
        {
            
            $relations = $this->$camelKey();
            // This attribute matches an embedsOne or embedsMany relation so we need
            // to return the relation results instead of the interal attributes.
            if ($relations instanceof EmbedsOneOrMany)
            {
                // If the key already exists in the relationships array, it just means the
                // relationship has already been loaded, so we'll just return it out of
                // here because there is no need to query within the relations twice.
                if (array_key_exists($key, $this->relations) && !$this->serialized)
                {
                    return $this->relations[$key];
                }
                
                // Get the relation results.
                return $this->getRelationshipFromMethod($key, $camelKey);
            }
        }


so yeah to avoid confusion, you better use $this->attribute['features'] instead of $this->features, too much magic called when you call $this->features

**Comment by daPhantom** [comment]
Thanks @darkeus! That makes a lot more sense actually than with the previous code snipped.

So as a rule of thumb you can say that you should always stick with `$this->attributes['key']` instead if `$this->key` when not using a relation. Yet alone to avoid magic functions, reflection and unnecessary additional execution time.

**Comment by darkeus** [comment]
@daPhantom yep $this->key is  better used outside of the Model class, well you can use the $this->key but you should know what it do, then again if you want to make a function that will act like an attribute you better use acessor way getKeyAttribute($value) , using this will make your model accessible like $model->key, it's on getAttribute() magic logic. 

And if you actually want to make features as a function then yes to call an attribute inside model class better use $this->attribute['key'], but if you actually want to make features() function as accessor then that is a wrong way. 

sorry my bad english =p

**Comment by daPhantom** [comment]
@darkeus Yes. It is kind of an accessor but it combines features from multiple relations instead of just `FooBar`. Just like this:

```
public function features() {
    return array_merge($this->relationOne->attributes['features'], $this->attributes['features']);
}
```

Thanks again for your help. I like magic functions and reflections but sometimes it's not bad to avoid them and just stick to direct functions. Most of the time "magic" is CPU intensive.

**Comment by darkeus** [comment]
@daPhantom oh actually in your case you can write it like this 

    public function features() {
        return array_merge($this->relationOne->features, $this->attributes['features']);
    }

because relationOne magic wont affect your current model magic, unless your relationOne have another features() function, and actually i dont know magic is CPU intensive. from the magic logic it is quite good and direct, maybe the "intensive" refers to how PHP engine call the magic function?

**Comment by daPhantom** [comment]
@darkeus You are right but as I pointed out earlier I would like to stick to a fixed scheme then. First to avoid magic and second to have it stringent throughout the project. This way I know instantly if it is a relation or an attribute ;)

**Comment by darkeus** [comment]
@daPhantom  i see that's answer all my question =) good luck
