### ISSUE TITLE
where with a string that contains '/' add an escape char

### ISSUE THREAD

**Issue by Grummfy** [jenssegers/laravel-mongodb#486]
Hello,
when you do : 

```
Model::where('a', '=', 'abc/def')->get();
```

You would like to do something like that :

```
db.model.find({a: 'abc/def'});
```

But instead it does something like that

```
db.model.find({a: 'abc\/def'});
```

That's very problematic. The only whay I find to execute my query is tu use this : 

```
Model::where('a', 'not regexp', 'abc/def')->get();
```

**Comment by alexcaglairi** [comment]
Hi,
 i have the same problem! i have to search in a field that contains "/" this slash or other value like "$".
How can i search?
