### ISSUE TITLE
eager loading EmbedMany can't save embeded Object to parent Model

### ISSUE THREAD

**Issue by darkeus** [jenssegers/laravel-mongodb#488]
i found a bug if i try eager load embedMany Relation from a Model then after that i tried access the relation object, the do some update to the atribute and save, then it failed the code is like 

```
 class Lesson extends \Moloquent{

       public function sublessons(){
             return $this->embedMany(Sublesson::class);
       }
 }

 class Sublesson extends \Moloquent{

 }
```

now on routes.php i call lesson like this

```
Route::get('test',function(){
      $lesson=App\Lesson::with('sublessons')->first();
      $sub=$lesson->sublessons->first();
      $sub->name="new value";
      $sub->save();
});
```

it doesn't save the embededObject, because there is problem with $this->parentRelation in the root Model (Lesson) after eagerLoad the Moloquent will append $this->parentRelation with EmbedMany Object  that have parent of Lesson itself, i do have some workaround, 
i add flag on \Jenssegers\Mongodb\Model class i add protected $rootModel=false;

```
abstract class Model extends \Jenssegers\Eloquent\Model {
    /**
     * The key if the model is and rootmodel of an embbed model
     * dn implementation
     * @var bool
     */
    public $rootModel=false;

}
```

then on \Jenssegers\Mongodb\Relation\EmbedOneOrMany class i add some change

```
abstract class EmbedsOneOrMany extends Relation {

    /**
     * Initialize the relation on a set of models.
     *
     * @param  array   $models
     * @param  string  $relation
     * @return void
     */
    public function initRelation(array $models, $relation)
    {
        foreach ($models as $model)
        {
            //add attribute to model with rootmodel to Jenssengers\MongoDb\Model
            if(!$model->rootModel)$model->setParentRelation($this);

            $model->setRelation($relation, $this->related->newCollection());

        }

        return $models;
    }

    /**
     * Match the eagerly loaded results to their parents.
     *
     * @param  array   $models
     * @param  \Illuminate\Database\Eloquent\Collection  $results
     * @param  string  $relation
     * @return array
     */
    public function match(array $models, BaseCollection $results, $relation)
    {
        foreach ($models as $model)
        {
            $results = $model->$relation()->getResults();

            //add attribute to model with rootmodel to Jenssengers\MongoDb\Model
            if(!$model->rootModel)$model->setParentRelation($this);

            $model->setRelation($relation, $results);
        }

        return $models;
    }


    /**
     * Attach a model instance to the parent model.
     *
     * @param  \Illuminate\Database\Eloquent\Model  $model
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function save(Model $model)
    {
        if(!$model->rootModel)$model->setParentRelation($this);

        return $model->save() ? $model : false;
    }



    /**
     * Create a new instance of the related model.
     *
     * @param  array  $attributes
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function create(array $attributes)
    {
        // Here we will set the raw attributes to avoid hitting the "fill" method so
        // that we do not have to worry about a mass accessor rules blocking sets
        // on the models. Otherwise, some of these attributes will not get set.
        $instance = $this->related->newInstance($attributes);

        if(!$instance->rootModel)$instance->setParentRelation($this);

        $instance->save();

        return $instance;
    }



    /**
     * Create a related model instanced.
     *
     * @param  array  $attributes
     * @return \Illuminate\Database\Eloquent\Model
     */
    protected function  toModel($attributes = array())
    {
        if (is_null($attributes)) return null;

        $model = $this->related->newFromBuilder((array) $attributes);

        if(!$model->rootModel)$model->setParentRelation($this);

        $model->setRelation($this->foreignKey, $this->parent);

        // If you remove this, you will get segmentation faults!
        $model->setHidden(array_merge($model->getHidden(), array($this->foreignKey)));

        return $model;
    }

}
```

if change the line of 

```
$model->setParentRelation($this);
```

to

```
    if(!$model->rootModel)$model->setParentRelation($this);
```

and on Lesson Model i ovewrite the $rootModel to true since Lesson Model is Root of EmbededObject

```
 class Lesson extends \Moloquent{
       public $rootModel=true;
       public function sublessons(){
             return $this->embedMany(Sublesson::class);
       }
 }
```

that how my workaround do, @jenssegers  what do you think, do i miss something or mess up the code? i dont really familiar with the code yet. thanks =D

**Comment by spawn-guy** [comment]
Testing this approach. I do agree, that there is a problem with eagerLoading.. after eagerLoading.
The parent always exists, which results into an infinite loop on getPathHierarchy() and to getParentRelation().
Test scenario is simple, based on your models (except embedOne in my case)
```
$lesson=App\Lesson::all();
$lesson->load('sublessons');
```

**Comment by spawn-guy** [comment]
and again, this IS a *Working* solution, but.. one wouldn't be able to re-use models if they are *sometimes* embeded and *sometimes* not. this needs to be dynamic, imo.

here are my ideas:
- probably we should utilize $casts functionality by adding "collection:ModelName"/"item:ModelName" or "embedMany:ModelName"/"embedOne:ModelName" as values and "auto"-load the embeded models right when they are, basically, loaded. also Ignoring them if someone wants to "load" them afterwards
- or limit getPathHierarchy() to just 1 level up so it will not get into an endless loop

also, this does and doesn't make sense: that ::match() requires a Collection to be passed as a second parameter.

here is a "merged" vesion
https://github.com/spawn-guy/laravel-mongodb/tree/feature_EmbedModelsWithParentFlag

**Comment by mlanin** [comment]
Same here. Unfortunately, eager loading with `load()` doesn't work at all... :( I got endless loop every time I want to fetch embeded models

**Comment by BenjaminOwlient** [comment]
Still encountering this problem. Eager loading embedded objects, either by "with" or a late "load", sets an erroneous parent relation to the root object. This makes the save function ineffective.
