### ISSUE TITLE
MySQL hasOne relation to Mongo

### ISSUE THREAD

**Issue by tdicks** [jenssegers/laravel-mongodb#49]
I've never played with MongoDB before but this is really getting me into it. I'm using MySQL to store basic picture data such as filename, filesize etc, and MongoDB to store metadata which might be different for each picture (exif, ifd0) etc.

I've successfully got the MongoDB model set up and saving:

``` php
   $user = User::whereUsername('test_username')->first();
   $img = new Image();
   $img->filename = "hello.jpg";
   $img->save();

   $meta = new ImageMeta();
   $meta->exif_maker = "Canon";
   $meta->exif_model = "EOS 500D";
   $meta->save();

   $img->meta()->save($meta);
```

However when I try to get the metadata back from the image:

``` php
   echo $img->meta->exif_maker;
```

It returns NULL. Am I doing something wrong? If I look at the ImageMeta MongoDB model, I can see an image_id key which is populated with the image_id of the Image model.

Image relation:

``` php
$this->hasOne('ImageMeta');
```

ImageMeta relation:

``` php
$this->belongsTo('Image');
```

Image model table schema:

``` php
        Schema::create('images', function(Blueprint $table)
        {
            $table->increments('id');
            $table->string('filename');
            $table->integer('filesize');
            $table->string('hash');
            $table->string('hash_type');
            $table->integer('user_id');
            $table->timestamps();
        });
```

Any ideas?

**Comment by NandoSantana** [comment]
> [https://gist.github.com/ollieread/](https://gist.github.com/ollieread/8020640)

can you repost links, i have the same situation.
