### ISSUE TITLE
Issue with properties that begin with underscore

### ISSUE THREAD

**Issue by omanizer** [jenssegers/laravel-mongodb#490]
Since upgrading to L5 I have this issue.

I have a model with a nested model like this:

`public function notes()`
`{`
`return $this->embedsMany('ContactNote', '_notes');`
`}`

I get an error like this:
1) BadMethodCallException: Call to undefined method Jenssegers\Mongodb\Query\Builder::_notes()

/Dev/www/asdf/api2/trunk/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1999
/Dev/www/asdf/api2/trunk/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php:1047
/Dev/www/asdf/api2/trunk/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:933
/Dev/www/asdf/api2/trunk/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3362
/Dev/www/asdf/api2/trunk/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Model.php:508
/Dev/www/asdf/api2/trunk/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:2638
/Dev/www/asdf/api2/trunk/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:2638
/Dev/www/asdf/api2/trunk/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Model.php:257
/Dev/www/asdf/api2/trunk/app/Contact.php:455
/Dev/www/asdf/api2/trunk/app/Contact.php:496
/Dev/www/asdf/api2/trunk/app/Contact.php:485
/Dev/www/asdf/api2/trunk/app/Message.php:196
/Dev/www/asdf/api2/trunk/app/Campaign.php:352
/Dev/www/asdf/api2/trunk/tests/CampaignTest.php:103
/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:151
/.composer/vendor/phpunit/phpunit/src/TextUI/Command.php:103

Unfortunately I can't change my data model at this point so a workaround would be preferred.  A quick & dirty workaround is to add this to line 234 of Jenssegars/Mongodb/Model.php:

`if(substr($key,0,1) == '_') {`
`$camelKey = $key;`
`} else {`
`$camelKey = camel_case($key);`
`}`

Would you entertain the possibility of getting this merged?

**Comment by darkeus** [comment]
@ohmance sir i want to ask how do you access your relation? is it $model->_notes; or $model->notes?
AFAIK the function of getAttribute wont execute _notes method if you call your $model like this 

     $model->notes; 

the code of
 
     return $this->embedsMany('ContactNote', '_notes');

wil make your model accesible like this

    $model->notes

and it's still call _notes in your data model 
CMIIW =)

**Comment by ohmance** [comment]
@darkeus I agree what what you're saying as the camel_case() method strips out the preceding underscore, however it's impossible for me to interchange "notes" and "_notes" as I maintain a unique schema for every account and store such keys for each account.  A preceding underscore in my case typically indicates a system maintained field.  Long story short I need to be able to support both '_notes' and 'notes' in the case that one of my users utilizes the field 'notes' while the system is also storing data in '_notes'.

**Comment by ohmance** [comment]
Just as an update on this, I'm currently having to actually create a _parentGetAttribute() method in my class that contains the contents of Mongodb/Model's getAttribute method as well as Eloquent/Model's getAttribute method with the above $camelKey code changed.  This works and I'm able to accomplish what I need without modifying any vendor code, but it does add 80 extra lines to my model and force me to watch for changes within these two vendor methods in the future.

**Comment by borice** [comment]
Looking for a solution to this also.
