### ISSUE TITLE
Call to undefined method MongoClient::command()

### ISSUE THREAD

**Issue by renatobecker** [jenssegers/laravel-mongodb#494]
Hi 
I am trying to use the following command in my model:
$db = DB::connection('mydb')->getMongoClient();
$db->command(['mapreduce' => '...']);

However , I get this error message :
"Call to undefined method MongoClient::command()"

I saw an example of using this feature , but I could not use it. What's wrong ?

**Comment by jenssegers** [comment]
Can you try it without getMongoClient()? It seems that `command` is a method of the DB class http://php.net/manual/en/mongodb.command.php
