### ISSUE TITLE
Or where in not working as it should be.

### ISSUE THREAD

**Issue by sameer1750** [jenssegers/laravel-mongodb#495]
My Query is :Collection::WhereIn('email',$email)->orWhereIn('mobile',$mobile)->get();  
The mongo query which is getting executed is : 
collection.find({"$and":[{"deleted_at":null},{"email":{"$in":["dfsdf@fsd.dfgf","sa$d.c"]}}],"$or":[{"mobile":{"$in":["39834787348","349430984390"]}}]},[])
which is not getting the proper results
Actualy the below mongo query gives proper result but how to execute that in laravel.
db.collection.find({$or:[{"email":{$in:["dfsdf@fsd.dfgf","sa$d.c"]}},{"mobile":{$in:["9892230504"]}}]}).pretty()

**Comment by shazamjad** [comment]
Try this:

````
->where( function($query){
  $query->orWhereIn( 'email', $email );
  $query->orWhereIn( 'mobile', $mobile );
})
````
