### ISSUE TITLE
Missing argument 1 for ...\Blueprint::primary()

### ISSUE THREAD

**Issue by gianx89** [jenssegers/laravel-mongodb#497]
I've correctly set up mondo db on my laravel 5 installation. Now I'm also using this package https://github.com/lucadegasperi/oauth2-server-laravel . When I run:

```
php artisan vendor:publish
php artisan migrate
```

I receive this error:

>  [ErrorException]                                                                                                                                                                  
  Missing argument 1 for Illuminate\Database\Schema\Blueprint::primary(), called in /Users/AAA/BBB/database/migrations/2015_01_01_000001_create_oauth_scopes_table.php on line 17 and defined

I run the migrations with a mysql db, no errors. This error occours in every migration where there's something like this:

```
$table->string('id', 40)->primary();
```

If I change it to:
```
$table->string('id', 40)->primary('id');
```

All works fine with mongodb. So, is it a bug? Is an intentional behaviour? Let me know and, if it's possibile, help me.

Best regards

**Comment by jenssegers** [comment]
I don't know if Laravel supports calling `primary` without an argument: `public function primary($columns, $name = null)`.

**Comment by jenssegers** [comment]
Also, MongoDB has no `primary()` index, so I will add is as an alias for `unique()`

**Comment by jenssegers** [comment]
Should be fixed on dev-master.

**Comment by gianx89** [comment]
I confirm, it's fixed. Thank you for the fast commit.
