### ISSUE TITLE
Support for Bulk Write Operations

### ISSUE THREAD

**Issue by somnathmuluk** [jenssegers/laravel-mongodb#500]
How to do bulk operations provided by Mongo Core Library?

http://docs.mongodb.org/manual/core/bulk-write-operations/

1. Bulk.insert()
2. Bulk.find()
3. Bulk.find.upsert()
4. Bulk.find.update()
5. Bulk.find.updateOne()
6. Bulk.find.replaceOne()
7. Bulk.find.remove()
8. Bulk.find.removeOne()

**Comment by jenssegers** [comment]
`public function update(array $values, array $options = array())` will set `$options['multiple'] = true;` by default and update multiple records.

`public function insert(array $values)` uses `batchInsert` as well, to mimic Laravel insert behaviour.

**Comment by maulikmmodi** [comment]
It will work great with bulk addition, this way, you just need to create on array and pass it to it.

$temp = [
            [
                'item'=> "envelopes"
            ],`enter code here`
            [
                'item'=> "envelopesas"
            ],
            [
                'item'=> "lala"
            ]
        ];

        $userData = DB::table('log')->raw( function ( $collection ) use ($temp) {

            return $collection->insertMany($temp);
        });
