### ISSUE TITLE
Eloquent and Upsert

### ISSUE THREAD

**Issue by garymalcolm** [jenssegers/laravel-mongodb#502]
Thanks for the great library.

Can we get an example of using an eloquent object and upsert?

My code:

    class Contact extends Eloquent {
        protected $connection = 'mongodb';
        protected $collection = 'contact';
}
....
 $c = new Contact;
... add vars (a duplicate email!)
$c->save(array('upsert' => true));  
error : MongoDuplicateKeyException in Collection.php line because of my purposeful unique index

any help would be great! Thanks in advance.

Gary

**Comment by garymalcolm** [comment]
I have answered my own question:

$c->update(array('upsert' => true));

works as expected. Awesome!

**Comment by arirah** [comment]
```
$data = array ('name'=>'Jhon') ;
DB::collection('users')->where('id',$id)->update($data , array('upsert' => true));
```

Insert new row ! Then how it works ?

**Comment by cacharrin** [comment]
> Is there a way to determine if the record has been inserted or updated?
Just came here with the same question
