### ISSUE TITLE
Question: Query db by MongoDate

### ISSUE THREAD

**Issue by milosh012** [jenssegers/laravel-mongodb#51]
Hello,

first want to say that your extension is awesome!

I have one question... I have mongodb collection saved with models that have column type "Date". When I access that collection I see that column with Date type is actually MongoDate object. 

My question is how I can query by that column? I have tried next scenarios with no success:

```
DB::connection('mongodb')->collection('names')->where('date', '<', new MongoDate())
DB::connection('mongodb')->collection('names')->where('date', '<', new DateTime())
DB::connection('mongodb')->collection('names')->where('date', '<', time())
DB::connection('mongodb')->collection('names')->where('date', '<', date('Y-m-d'))
```

Thanks,
Milos

**Comment by atapatel** [comment]
I am facing the issue with new version..

**Comment by jkpatil211** [comment]
@sebastiaanluca : u can use MongoDate::toDateTime as given in following link
http://php.net/manual/en/mongodate.todatetime.php

**Comment by saraht129** [comment]
@jenssegers The `whereBetween` query doesn't work with Carbon date, only MongoDate. Using v2.2.4.

        $startDate = Carbon::createFromDate(2015, 4, 1);
        $endDate = Carbon::createFromDate(2015, 4, 30);
        $users = User::whereBetween('created_at', array($startDate, $endDate))->get();
        //Return empty result

        $startDate = new MongoDate(Carbon::createFromDate(2015, 4, 1)->timestamp);
        $endDate = new MongoDate(Carbon::createFromDate(2015, 4, 30)->timestamp);
        $users = User::whereBetween('created_at', array($startDate, $endDate))->get();
        //Return correct results

Is the Carbon date support not applicable to this case? Thanks!

**Comment by thialves** [comment]
I am facing the issue with new version..²

**Comment by mshahamirian** [comment]
@saraht129 @jenssegers I've tired your solution and still get empty result! Also tried (for example)
`User::where('created_at','>',$startDate)->where('created_at','<',$endDate)->get();`
still get empty result.
I don't know why it doesn't work with more than one where clause :disappointed:
