### ISSUE TITLE
Query on a recursive collection Laravel

### ISSUE THREAD

**Issue by masweb** [jenssegers/laravel-mongodb#512]
how can I find an object by value ?, json object can be recursive as the example

``` javascript
[id] => f81f753b30bf
[title] => aa
[description] =>
[child] => Array (
     [0] => Array (
         [id] => 0485d8538197
         [title] => 11
         [description] =>
         [url] => -
         [child] => Array (
             [0] => Array (
                 [id] => 0485d4448197
                 [title] => 11
                 [description] =>
                 [url] => -
                 [child] => Array (
                 )
             )
         )
     )
     [1] => Array (
         [id] => 95e27b97831b
         [title] => 55
         [description] =>
         [url] => -
         [child] => Array (
         )
     )
)
```

I need to recover a child object by id, thanks

**Comment by KTAnj** [comment]
`$where=array("child.id");
$data= DB::connection($connection)->collection($collection)->raw(function($collection) use($where) {
            return $collection->aggregate(array(
                       array('$unwind'=>'$child'),
                       array('$match'=>$where)
            ));
        });
        return $data['result'];`
