### ISSUE TITLE
Executor error: Overflow sort stage buffered data usage.

### ISSUE THREAD

**Issue by ViktorKudlai** [jenssegers/laravel-mongodb#518]
I'm trying to retrieve records from the database for my admin datatable. There are 2400 records, and when I'm going to the last page I getting this error.

My method for retrieving recornds.

```
/**
 * @return mixed
 */
public static function getAll()
{
    return self::orderBy('created_at', 'desc')->paginate(30, ['keyword', 'url', 'status']);
}
```

Executor error: Overflow sort stage buffered data usage of 33560679 bytes exceeds internal limit of 33554432 bytes
1. MongoCursorException
   …/­vendor/­jenssegers/­mongodb/­src/­Jenssegers/­Mongodb/­Query/­Builder.php260
2. MongoCursor rewind
   <#unknown>0
3. iterator_to_array
   …/­vendor/­jenssegers/­mongodb/­src/­Jenssegers/­Mongodb/­Query/­Builder.php260
4. Jenssegers\Mongodb\Query\Builder getFresh
   …/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Query/­Builder.php1384
5. Illuminate\Database\Query\Builder get
   …/­vendor/­jenssegers/­mongodb/­src/­Jenssegers/­Mongodb/­Query/­Builder.php124
6. Jenssegers\Mongodb\Query\Builder get
   …/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Builder.php411
7. Illuminate\Database\Eloquent\Builder getModels
   …/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Builder.php151
8. Illuminate\Database\Eloquent\Builder get
   …/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Builder.php283
9. Illuminate\Database\Eloquent\Builder ungroupedPaginate
   …/­vendor/­laravel/­framework/­src/­Illuminate/­Database/­Eloquent/­Builder.php246
10. Illuminate\Database\Eloquent\Builder paginate
    …/­app/­models/­Keywords.php147
11. App\Models\Keywords getAll
    …/­app/­controllers/­AdminController.php25
12. App\Controllers\AdminController indexAction
    <#unknown>0
13. call_user_func_array
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Controller.php231
14. Illuminate\Routing\Controller callAction
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php93
15. Illuminate\Routing\ControllerDispatcher call
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php62
16. Illuminate\Routing\ControllerDispatcher dispatch
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php967
17. Illuminate\Routing\Router Illuminate\Routing{closure}
    <#unknown>0
18. call_user_func_array
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php109
19. Illuminate\Routing\Route run
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1033
20. Illuminate\Routing\Router dispatchToRoute
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1001
21. Illuminate\Routing\Router dispatch
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php775
22. Illuminate\Foundation\Application dispatch
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php745
23. Illuminate\Foundation\Application handle
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Session/­Middleware.php72
24. Illuminate\Session\Middleware handle
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Queue.php47
25. Illuminate\Cookie\Queue handle
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Guard.php51
26. Illuminate\Cookie\Guard handle
    …/­vendor/­stack/­builder/­src/­Stack/­StackedHttpKernel.php23
27. Stack\StackedHttpKernel handle
    …/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php641
28. Illuminate\Foundation\Application run
    …/­public/­index.php49

**Comment by panbhatt** [comment]
As per the mongodb documentation 
For in-memory sorts that do not use an index, the sort() operation is significantly slower. The sort() operation will abort when it uses 32 megabytes of memory.

so please create an index over the Column on which the search is being made and also make sure the total number of indexes in the collection wont go beyond 64, as this is the limit imposed by MONGODB. 
Read further for this: 
http://stackoverflow.com/questions/24690812/index-for-gte-lte-and-sort-in-different-fields

**Comment by ViktorKudlai** [comment]
Thanks, worked for me.)
