### ISSUE TITLE
Query using Sparse Index with ".hint" method

### ISSUE THREAD

**Issue by vugtis** [jenssegers/laravel-mongodb#525]
Hi,
I don't find any explanation how to use hint with sparse index as described here:
```sh
http://docs.mongodb.org/manual/core/index-sparse/
```
Here is the snippets :
```sh
db.scores.find().sort( { score: -1 } ).hint( { score: 1 } )
```
Is it supported in this package?

**Comment by jenssegers** [comment]
It was recently added, but I don't thing it has been documented yet.
