### ISSUE TITLE
INFO: Laravel Auth and Unique

### ISSUE THREAD

**Issue by dereckmartin** [jenssegers/laravel-mongodb#528]
This is not really an issue.  I am hoping maybe to help others out there with some auth while using mongodb, so do what you want with this ticket.  I'm using the latest laravel, and I had to extend several of the functions from the auth stuff to get user authentication working.  

I don't know if anyone has tested this, but checks for uniqueness is case sensitive as well as attempting auth. 

I had to extend the user create after registration to strtolower() the email.  Other wise someuser@domain.tld was different than SomeUser@domain.tld.

When authenticating a user, I had to extend the postLogin in auth/AuthController to transform email addresses into a uniform format, so that I could auth someone that couldn't remember if they registered SomeUser@domain.tld vs someuser@domain.tld.

``` php
    /**
     * Handle a login request to the application.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function postLogin(Request $request)
    {

        /* Added code that differs from the laravel's postLogin */
        $rd = $request->all();
        $rd['email'] = strtolower($request->input('email'));
        $request->replace($rd);
        /* end of added code */

        $this->validate($request, [
            'email' => 'required|email|exists:users', 
            'password' => 'required',
        ]);

        $credentials = $this->getCredentials($request);

        var_dump($credentials);

        if (Auth::attempt($credentials, $request->has('remember'))) {
            return redirect()->intended($this->redirectPath());
        }

        return redirect($this->loginPath())
            ->withInput($request->only('email', 'remember'))
            ->withErrors([
                'email' => $this->getFailedLoginMessage(),
            ]);
    }
```

**Comment by shehi** [comment]
Closing this issue would be nice. Search engines will pick up on it anyway.
