### ISSUE TITLE
Unable to hide embedded document attributes

### ISSUE THREAD

**Issue by tekminewe** [jenssegers/laravel-mongodb#529]
Hi, I wanted to hide embedded document attributes but failed. Can you please guide me how to do it? Thank you

My code is as below

```
class User extends Model {

    protected $hidden = ['_id', 'created_at', 'updated_at'];

    public function address() {
        return $this->embedsOne('App\Mongodb\Model\Address');
    }
}

class Address extends Model {

  /**
   * @var array
   */
  protected $hidden = ['_id', 'created_at', 'updated_at'];
}
```

So when I call `Address::orderBy('birthday', 'desc')->first()`, I still get the hidden attributes in the embedded document.

```
"user": {
    "birthday": "2015-06-27",
    "address": {
      "country": "us" 
      "updated_at": {
        "sec": 1435410176,
        "usec": 812000
      },
      "created_at": {
        "sec": 1435410176,
        "usec": 812000
      },
      "_id": {
        "$id": "558e9f00f83c72ca3a0041ab"
      }
    }
}
```

**Comment by nicklee1990** [comment]
did you find a way to do this? I've embedded a user and the password is being returned in the document!

**Comment by tagmestudio** [comment]
Hi @nicklee1990 sorry for the late reply. I tried your method but I'm don't know how to do it.

Here is the way I'm write my code
````
$address = new Address();
$address->country = 'us';

$user = new User();
$user->save();
$user->address()->save($address);
````

**Comment by mzuccala** [comment]
I'm experiencing the same issue too...

**Comment by tagmestudio** [comment]
At the moment, i just manually exclude the attributes after retrieve. Anyone has the proper solution?

**Comment by kargnas** [comment]
+1
