### ISSUE TITLE
How do I find an embedded document with its id?

### ISSUE THREAD

**Issue by slickorange** [jenssegers/laravel-mongodb#532]
I am trying something like:
`$field = $modelDescription->fieldDescriptions->find($id)`

Where fieldDescriptions are embedded in a modelDescription document - but it is not working.
Why is my embedded document's id stored as an array in "_id"?

  "name": "newField1",
      "label": "New Field",
      "type": "text",
      "fillable": true,
      "id": 2,
      "_id": {
        "$id": "55931752d8e30f7b018b456e"
      }

**Comment by jenssegers** [comment]
Because it is a MongoId. Try something like `where('fieldDescriptions._id', ...)`

**Comment by slickorange** [comment]
But why is it sometimes returning the _id as a string and other times (for example - a model's relationships) as the MongoID?

I saw in another post I can use `with` to get the result I want:
`$this->modelDescription->where('name',$name)->with('fielddescriptions')->first();`

But this does not work if the relationship name is written in camel case as 'fieldDescriptions' because laravel then returns the JSON snake cased as 'field_descriptions' while it is stored in the database as fieldDescriptions.
