### ISSUE TITLE
Morph many to many

### ISSUE THREAD

**Issue by julianrantwijk** [jenssegers/laravel-mongodb#536]
Hi, 

I was wondering if the morphToMany and morphedByMany relations are supported?

Thanks ;)

**Comment by jenssegers** [comment]
They are not supported yet.

**Comment by fppont** [comment]
Hello, I was looking for the same thing, and was wondering if this is now supported or might happen later on ?

Many thanks

**Comment by Stretsh** [comment]
2 years I wonder about the status of these relationships. Are they going to be added or should we just give up hope?

**Comment by CrisGarcis** [comment]
use Jenssegers\Mongodb\Eloquent\HybridRelations;

**Comment by fplun** [comment]
> use Jenssegers\Mongodb\Eloquent\HybridRelations;

what ????
