### ISSUE TITLE
Timeout attribute is ignored

### ISSUE THREAD

**Issue by Binternet** [jenssegers/laravel-mongodb#537]
While executing this:

\DB::connection('mongodb')->collection('stats')->where('updated_at','>=', $from)->where('updated_at','<=',$to)->timeout(-1)->count()

[ $from & $to are DateTime objects ]

I still get `MongoCursorTimeoutException` after 30 seconds, hence mongo is ignoring the timeout setting on the query builder.

**Comment by inflex13** [comment]
Hi,
Any ETA on this bug?

**Comment by stefanschindler** [comment]
Hi,
unfortunately this bug is still open. Any updates?
