### ISSUE TITLE
Using $where operator

### ISSUE THREAD

**Issue by Grummfy** [jenssegers/laravel-mongodb#540]
Hello,
In the readme we speak about $where operator but without giving any example.
Could you provide one?

**Comment by jenssegers** [comment]
See http://docs.mongodb.org/manual/reference/operator/query/where/

**Comment by Grummfy** [comment]
it doesn’t explain how to use with this library ...

**Comment by jenssegers** [comment]
It passes the 3rd parameter to the $where section of the query.

**Comment by Grummfy** [comment]
$query->where('$where', null, $whereParameters); ?
