### ISSUE TITLE
Nested documents saved as numeric arrays

### ISSUE THREAD

**Issue by UnrealKazu** [jenssegers/laravel-mongodb#542]
With an EmbedsMany relation, subdocuments are saved as numeric arrays whenever their parent is a nested document. This is inconsistent with root documents, where nested documents are saved with a push operation, and as such become a unordered list of objects.

This methodology can be found in every CRUD operation with nested documents, so it seems to be a workaround. Is there any reason for this decision?

For completeness, the code I'm talking about can be found in EmbedsMany.php. Line 43 executes a normal push operation, for nested documents (ultimately) line 236 pushes an entire array.

**Comment by jenssegers** [comment]
I still have not find the ultimate way to do embedded relations, and especially multiple levels of embedded models. There is always room for improvement.

**Comment by UnrealKazu** [comment]
That is understandable, as it can be quite complex. Thanks for your quick response!

**Comment by philipbrown** [comment]
Hey Jens, have you had any more thought around this issue?
