### ISSUE TITLE
Query router

### ISSUE THREAD

**Issue by cedricve** [jenssegers/laravel-mongodb#543]
I've got a sharded setup with multiple query routers. I was wondering If it's possible to add multiple query routers, and attach a load balancing strategy?

**Comment by maxrosecollins** [comment]
how did you authenticate with your query routers?

I am getting an Authentication failed message

**Comment by cedricve** [comment]
@maxrosecollins no idea, I stopped working on this approach.

**Comment by maxrosecollins** [comment]
@cedricve damn okay

**Comment by cedricve** [comment]
Sorry @maxrosecollins! I hope you find the solution quickly +1
