### ISSUE TITLE
Question: Paginating Embedded Documents

### ISSUE THREAD

**Issue by tandasima** [jenssegers/laravel-mongodb#545]
Is it possible to paginate embedded documents?

Example:
  $user = User::find($id);

  if($user -> count()) 
  {
    $user = $user -> first();
  }

  $items = $user -> experiences; // is it possible to paginate this?

When I try to do
$items = $user -> experiences->paginate(5)  I get a "Call to undefined method Jenssegers\Mongodb\Eloquent\Collection::paginate()"

User model has  the  method experience() which returns $this->embedsMany('Listing') which is a model for an Experience.

I wonder why it doesnt work with paginate()

**Comment by hackel** [comment]
You can't paginate a standard Eloquent collection either.  Pagination operates on the query level.  There is an EmbedsMany::paginate method you can try.

The purpose of the paginate method is to retrieve DB records a few at a time so you're not storing them all in memory.  Unless you use, e.g. a $slice query to limit the number of embedded documents returned in the parent object, this isn't going to help you.  If you have thousands of embedded documents, you may want to re-think your data model.
