### ISSUE TITLE
Laravel 5.1 Migration table not found.

### ISSUE THREAD

**Issue by hugo8xx** [jenssegers/laravel-mongodb#548]
$ php artisan migrate:refresh
Migration table not found.
Migration table created successfully.
Nothing to migrate.

```
    //debug
    /vendor/laravel/framework/Illuminate/Database/Migrations/DatabaseMigrationRepository.php
    public function repositoryExists()
    {
            $schema = $this->getConnection()->getSchemaBuilder();

            var_dump($schema->hasTable($this->table));
            var_dump($schema->hasCollection($this->table));

            return $schema->hasTable($this->table);
    }
```

result:
bool(false)
bool(false)

**Comment by shannoncurnew** [comment]
Do you have a key with the name of the migration table in your ./config/database.php ?

`    'migrations' => 'migrations',`

The refresh command works fine for me in Lumen 5.1.
