### ISSUE TITLE
Question: geoNear command.

### ISSUE THREAD

**Issue by RdlP** [jenssegers/laravel-mongodb#55]
Hello, mongodb has a command called geoNear (http://docs.mongodb.org/manual/reference/command/geoNear/#dbcmd.geoNear). How can I run this command with this project?

**Comment by madmanlear** [comment]
Has anyone gotten this working cleanly? Iterating through an array doesn't really seem sustainable.

**Comment by khoatran** [comment]
Hi Mike,

I think firstly you should make the test of the geo query on a flat collection - then the next step for aggregate later.

In my case, I have a collection called poi (Point of Interest). Inside this collection, there is a field called 'geo_point'. To make it works, I do below steps:

1/ Do the  2dsphere index for the field 'geo_point'. To do that with this package, I use below command:

```
Schema::collection('poi', function ($collection) {
                $collection->index(['geo_point' => '2dsphere']);
            });

```
2/ When doing the query (eg: query poi locations that nears to a specific geo point), I just use the below code:

```
       /** @var \Jenssegers\Mongodb\Query\Builder $queryBuilder */
        $queryBuilder = DB::collection('poi');

        $result = $queryBuilder->where('geo_point', 'near', [
            '$geometry' =>  [
                'type' => 'Point',
                'coordinates' => [floatval(106.637056), floatval(10.825903)]
            ],
            '$maxDistance' => 10000,
        ])->get();
```

If you want to use query raw, then:

```
$result = $queryBuilder->whereRaw([
                    'geo_point'=> [
                        '$near' => [
                            '$geometry' =>  [
                                'type' => 'Point',
                                'coordinates' => [floatval(106.637056), floatval(10.825903)]
                            ],
                            '$maxDistance' => 10000,
                        ]
                    ]
                ]
        )->get();
```

Also, when you insert the data to the geo location field which is indexed, you must follow the specification of  MongoDB. If we do the indexing by 2dsphere, the location data must be a geometry point.

I made a function to help me convenient to create the location data format as below:

  ```
public static function createLocationData($lat, $lng) {
        return [
            'type' => 'Point',
            'coordinates' => ['lng' => floatval($lng), 'lat' => floatval($lat)]
        ];
    }
```

If you follow above steps and can make it works with the example for the flat structure, I think it's easier for you to debug and check on the aggregate function later. 

Hope this help.
