### ISSUE TITLE
Eager Loading with mysql table belongsTo not working

### ISSUE THREAD

**Issue by lohiaad** [jenssegers/laravel-mongodb#552]
Hi,

I have users table in mysql which has one to many relation with comments collection in mongo.
I have extend User model with  Jenssegers\Eloquent\Model as Eloquent and Comment model with  Jenssegers\Mongodb\Model as Eloquent. 
Relation between model is also created but when i use eager loading from comments to user it does not work.
Comment::with('user')->where('status',0)->get() . it returns comment without user.
I can get user by following code
$comments = Comment::where('status',0)->get()
foreach($comments as $comment){
$user = $comment->user;
}

**Comment by HasnBatal** [comment]
Have you reached a solution??

**Comment by HasnBatal** [comment]
MySQL Relations

If you're using a hybrid MongoDB and SQL setup, you're in luck! The model will automatically return a MongoDB- or SQL-relation based on the type of the related model. Of course, if you want this functionality to work both ways, your SQL-models will need use the Jenssegers\Mongodb\Eloquent\HybridRelations trait. Note that this functionality only works for hasOne, hasMany and belongsTo relations.

Example SQL-based User model:

```
use Jenssegers\Mongodb\Eloquent\HybridRelations;

class User extends Eloquent {

    use HybridRelations;

    protected $connection = 'mysql';


.....


}
```

**Comment by JudJin** [comment]
@HasnBatal have you tried it yourself?

**Comment by HasnBatal** [comment]
yes, but in my project, i has same problem and it solved
