### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by xdevnull** [jenssegers/laravel-mongodb#554]
Hello,

I've a collection with 100,000 documents almost.

When i try to get all() Page breaks down. (MongoDB Timeout). Eventhough i can't perform any operation.. where() will break the page too.

I've tried the Timeout code you provided but still the same problem.

Is there any snippet for setting timeout to -1 by default rather than do it when getting collections?

**Comment by sefsinalas** [comment]
+1
