### ISSUE TITLE
belongsToMany with Hybrid relationship

### ISSUE THREAD

**Issue by roosh-t3** [jenssegers/laravel-mongodb#555]
I have been trying to do Followers, Following table structure in my App 

```
public function followers(){
        return $this->belongsToMany("App\User", "user_followers", 'user_id', 'follower_id', 'user_followers');
    }

    public function following(){
        return $this->belongsToMany("App\User", "user_followers", 'follower_id', 'user_id', 'user_followers');
    }
```

with the MongoDB-Eloquent this doesn't work. as it refers to the User table and search for user_id column. but if I switch to laravel's Eloquent it works.

**Comment by duongtdvn** [comment]
Hi there,
Have you fixed your issue as I'm also having the same. Do you mind to share your fix?

**Comment by lohiaad** [comment]
Hi roosh-t3,

I have same issue. not able to find out any solution.

**Comment by StefanoFrazzetto** [comment]
Since I also had this problem and this is the first result from Google, this is how I solved it.

You need to add the HybridRelations trait from Jenssegers\Mongodb\Eloquent\HybridRelations in the SQL model you want to use.

Example:
```<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\HybridRelations;

class User
{
    use HybridRelations;
```

Reference: [laracast.com](https://laracasts.com/discuss/channels/eloquent/mongodb-and-mysql-hybrid)

**Comment by vahidei** [comment]
> Since I also had this problem and this is the first result from Google, this is how I solved it.
> 
> You need to add the HybridRelations trait from Jenssegers\Mongodb\Eloquent\HybridRelations in the SQL model you want to use.
> 
> Example:
> 
> ```
> 
> namespace App;
> 
> use Jenssegers\Mongodb\Eloquent\HybridRelations;
> 
> class User
> {
>     use HybridRelations;
> ```
> 
> Reference: [laracast.com](https://laracasts.com/discuss/channels/eloquent/mongodb-and-mysql-hybrid)

not working for belongsToMany
