### ISSUE TITLE
Unique & Sparse indices

### ISSUE THREAD

**Issue by benargo** [jenssegers/laravel-mongodb#556]
Hey,

In the scenario we're working with, sign in is optional, but we still create a User model for each person which stays with them even as guests. This means we will have multiple models with a `null` email address field. However, for those persons who have elected to sign in, and therefore we have their email address, the email field needs to be unique to ensure no duplicate accounts.

If we simply apply the Unique index to the email field, as soon as a second guest enters the app, we get the following error message:

    MongoDuplicateKeyException in Collection.php line 42:
    127.0.0.1:27017: E11000 duplicate key error index: genii.Auth_EndUsers.$email_1 dup key: { : null }

No biggie! MongoDB already thinks of this, and provides us a way of only checking entries where the field is not null (see [Sparse indices](http://docs.mongodb.org/manual/core/index-sparse/)).

It's nice to see that this library supports sparse indices, however, when I try to apply the index (using `$collection->sparse('email');`) to the already-unique index I get the following error message:

    ben$ php artisan migrate:refresh
    Nothing to rollback.

    [MongoResultException]                                                                      
    127.0.0.1:27017: exception: Index with name: email_1 already exists with different options  

Apologies if any of this is unclear. Has anyone else come across this, or found the solution?

**Comment by pengkong** [comment]
@jenssegers could you kindly add this function to Blueprint.php this will allow us to create sparse and unique indexes.

    /**
     * Specify a sparse and unique index for the collection.
     *
     * @param  string|array  $columns
     * @return Blueprint
     */
    public function sparse_and_unique($columns = null)
    {
        $columns = $this->fluent($columns);
        $this->index($columns, ['sparse' => true, 'unique' => true]);

        return $this;
    }
