### ISSUE TITLE
'upsert' option not working on Model classes

### ISSUE THREAD

**Issue by erkanarslan** [jenssegers/laravel-mongodb#558]
Upsert does not create record if it doesn't exist when called on Model class.

This works:

    DB::collection('my_collection')->where('name', 'John')->update(['age' => 25], ['upsert' => true]);

That doesn't:

    MyCollection::where('name', 'John')->update(['age' => 25], ['upsert' => true]);

`MyCollection` extends `Jenssegers\Mongodb\Model` and `$collection` property is 'my_collection'.

**Comment by Dimasdanz** [comment]
I can confirm this.  
Probably due to update method is passed on Eloquent\Builder which does not have second parameter

**Comment by darkin1** [comment]
Confirm this, LV: 5.1, Moloquent: 2.2

**Comment by pashamesh** [comment]
+1

**Comment by mynamespace** [comment]
+1

**Comment by gnrcampos** [comment]
+1
