### ISSUE TITLE
convert mongodb query to laravel

### ISSUE THREAD

**Issue by amiralii** [jenssegers/laravel-mongodb#559]
how i can use this query in laravel?

db.products.update(
{
"comments.id" : 793644433634148
}
    ,
    {
        $set:{
            "comments.$.approve":false
        }
    }
)

**Comment by alexandre-butynski** [comment]
Have you tried something like that ?

```PHP
DB::collection('products')->where('comments.id', '793644433634148')->update(['comments.$.approve', false]);

**Comment by amiralii** [comment]
Yes, but I got an error :

MongoWriteConcernException in Collection.php line 42:
localhost:27017: Modifiers operate on fields but we found a Array instead. For example: {$mod: {<field>: ...}} not {$set: [ "comments.$.approve", true ]}

**Comment by alexandre-butynski** [comment]
You can use `DB::getQueryLog();` to debug your request and see what is different between the original request and the one produced by the ORM.

Can't help you more right now :/
