### ISSUE TITLE
Class 'Jenssegers\Mongodb\Auth\PasswordResetServiceProvider' not found

### ISSUE THREAD

**Issue by blob1** [jenssegers/laravel-mongodb#561]
After adding 'Jenssegers\Mongodb\Auth\PasswordResetServiceProvider', on app/config/app.php I'm trying to install https://github.com/jenssegers/Laravel-MongoDB-Session it says :
![screenshot from 2015-08-20 05 38 28](https://cloud.githubusercontent.com/assets/3858791/9370892/20114418-46fe-11e5-8022-14054772474b.png)
I try to run composer update show that message too, thank you

**Comment by dweinerATL** [comment]
I have the same problem.

**Comment by dweinerATL** [comment]
I'm not certain if this is the fix, but it's now throwing an error anymore when I changed 'Jenssegers\Mongodb\Auth\PasswordResetServiceProvider', to 'Jenssegers\Mongodb\Auth\ReminderServiceProvider',

I'll let you know if I get it working

**Comment by dweinerATL** [comment]
That was it!  As soon as I added the getReminderEmail() method to my User model to return the users email address, it started working.

**Comment by blob1** [comment]
Thank you, It works! I changed to 'Jenssegers\Mongodb\Auth\ReminderServiceProvider', and it works! Thank you very much

**Comment by dweinerATL** [comment]
You're welcome!  In my copious free time, I'll submit a patch to the README.md :)
