### ISSUE TITLE
Update element in array

### ISSUE THREAD

**Issue by duongtdvn** [jenssegers/laravel-mongodb#565]
Hi guy, I have a cart collection and I want to update the quantity where variant_id = 2, how may I do that? My collection as bellow:

<pre>
{
    "_id" : ObjectId("55dbdb7ebffebc120c8b4567"),
    "customer_id" : 1,
    "updated_at" : ISODate("2015-08-25T03:05:34.225Z"),
    "created_at" : ISODate("2015-08-25T03:05:34.225Z"),
    "items" : [ 
        {
            "product_id" : 1,
            "variant_id" : 1,
            "name" : "Eaque aut adipisci suscipit.",
            "price" : 129.0000000000000000,
            "shipping" : 9.0000000000000000,
            "quantity" : 2,
            "options" : [ 
                "small", 
                "blue", 
                "short", 
                null, 
                null
            ]
        }, 
        {
            "product_id" : 1,
            "variant_id" : 2,
            "name" : "Eaque aut adipisci suscipit.",
            "price" : 149.0000000000000000,
            "shipping" : 9.0000000000000000,
            "quantity" : 5,
            "options" : [ 
                "small", 
                "red", 
                "long", 
                null, 
                null
            ]
        }
    ]
}
</pre>

Thank you

**Comment by chasen** [comment]
Assuming you are using an embedsMany relationship, couldnt you just use `$cart->items()->where('variant_id','=',1)->increment('quantity');` ?

**Comment by Mulkave** [comment]
Facing the same issue here:

The structure is as follows:

```
{
    "_id" : ObjectId("586ec061a3bf81899c181c83"),
    "source" : {
        "id" : "8b45331e73cf2ab8f1d8187f096bc7cc",
        "name" : "Some Name"
    },
    "events" : [ 
        {
            "id" : "4569b9491b04bbb7b7ec99a2abc1b720",
            "expression" : "* * * * * *",
            "description" : "Something Here",
        }
    ],
    "created_at" : "2017-01-05 23:05:03",
}
```

Using the following code to add a key to the matching element in `events`:

```php
$this->db->collection('schedules')
            ->where(['source.id' => $source->id(), 'events.id' => $event->id()])
            ->update(['events.$.last_run_at' => 'something here']);
```

no keys get added. Nevertheless the following works when run in MongoDB's shell/robomongo

```mongodb
db.schedules.update(
{
    "source.id": "8b45331e73cf2ab8f1d8187f096bc7cc",
    "events.id": "4569b9491b04bbb7b7ec99a2abc1b720"
},
{
    "$set": {"events.$.last_run_at": "something here"}
}
)
```
