### ISSUE TITLE
artisan queue:listen problem

### ISSUE THREAD

**Issue by i0** [jenssegers/laravel-mongodb#567]
I'm using queue with database driver and the default database connection is mongodb, Query Builder and Moloquent works perfectly but there is a problem when running php artisan queue:listen : 
  [MongoException]  
  zero-length keys are not allowed, did you use $ with double quotes?  
is there any way to use queue:listen with mongodb ?

**Comment by johngieselmann** [comment]
https://github.com/jenssegers/laravel-mongodb/issues/426

**Comment by giolvani** [comment]
I can not solve the issue with the #426 thread...

Anyone solve this?

**Comment by wprk** [comment]
I'm having this issue too. Haven't been able to find a solution and fix in #426 didn't work for me. I'm going to use beanstalkd for now as others have suggested.

**Comment by giolvani** [comment]
Actually, there is a solution, but it is in another fork https://github.com/jeremy-brenner/laravel-mongodb.

Unfortunatelly, the PR does not merged until now.
