### ISSUE TITLE
orWhere not working on model

### ISSUE THREAD

**Issue by erkanarslan** [jenssegers/laravel-mongodb#573]
This returns result:

``` php
DB::collection('tests')->where('votes', '>', 100)->orWhere('name', 'John')->get();
```

This returns **empty** Collection:

``` php
Test::where('votes', '>', 100)->orWhere('name', 'John')->get();
```

This returns result:

``` php
Test::where(function($query){
    $query->where('votes', '>', 100)->orWhere('name', 'John');
})->get();
```

**Comment by Ynk33** [comment]
I'm experiencing the same issue. I expect the 2nd call to work as well as the first one, but it does return a empty Collection.

**Comment by benargo** [comment]
I'm having the same issue as well, the 'solution' @erkanarslan outlined above works well as a way around:

> ```
Test::where(function($query){
    $query->where('votes', '>', 100)->orWhere('name', 'John');
})->get();`
```

**Comment by stuartm** [comment]
Same issue, workaround described by erkanarslan works for now.

**Comment by dannysood** [comment]
Same issue. Worked out is what i am depending on for now.
