### ISSUE TITLE
Working with attributes

### ISSUE THREAD

**Issue by evgenyponomarev** [jenssegers/laravel-mongodb#575]
I have the following model structure:

``` json
{
   "_id": ObjectId("55ed6d16e7d36a112212abf1"),
   "type": "questions",
   "attributes": {
     "title": "Test title",
     "text": "Test text",
     "updated": ISODate("2015-09-07T10:55:18.360Z"),
     "created": ISODate("2015-09-07T10:55:18.360Z") 
  } 
}
```

And model:

``` php
use Jenssegers\Mongodb\Model as Eloquent;
class Question extends Eloquent  {
}
```

Object $question doesn't receive any attributes, except "attributes" method with array inside.

``` php
$question = Question::all()->first();
$question->attributes['title'];
```

How to get and set properties like $question->title?

**Comment by hackel** [comment]
I think it's probably getting confused with Eloquent's own attributes property.  Can you rename it?  If not, perhaps you could do something like `$question->getAttribute('attributes')['title']`;
