### ISSUE TITLE
Eager loading causes 'Illegal offset type in isset or empty' exception

### ISSUE THREAD

**Issue by bram1028** [jenssegers/laravel-mongodb#576]
I have this model:

```php
<?php

namespace App;

use Jenssegers\Mongodb\Model;
use App\Scopes\ClientTrait;

class Activity extends Model
{
    use ClientTrait;
    
    protected $collection = 'activity';
    
    protected $with = ['patron'];
    
    protected $dates = ['date'];
    
    public function patron()
    {
        return $this->belongsTo('App\Patron');
    }
    
}
```

When I eager load `patron`, I get an exception:

```
ErrorException in Illuminate/Database/Eloquent/Relations/BelongsTo.php line 215:
Illegal offset type in isset or empty
```

I tracked it down to the fact that it's trying to find an array index using a MongoId object. I was able to fix this by casting the array key to a string. I don't know if this is the best way to solve this, but it seems to be working OK.

**Comment by rizalmovic** [comment]
Adding mutator method to get foreign key id to string seems to work also.

**Comment by bram1028** [comment]
I gave up on the inconsistent behavior and started using strings in Mongo instead of ObjectId to reference other documents.

**Comment by acidjazz** [comment]
@bram1028 I was about to go this way as well, but found that going after nested ID's became an issue, did you find a solution for this as well?

**Comment by bionets** [comment]
This issue still exist for me. Using the following versions:
`"php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "jenssegers/mongodb": "^3.6",
        "laravel/framework": "5.8.*",
        "laravel/passport": "^7.5",
        "laravel/tinker": "^1.0"`

All my eager loading are not working. I'm getting empty arrays on `hasMany` eager load and this error when calling a `belongsTo` relation.

Is this a package issue or am I doing something wrong? My _ids are ObjectID not string.

**Comment by bakkertjebrood** [comment]
Same here. Tried mutators but to no avail.

**Comment by bakkertjebrood** [comment]
> Adding mutator method to get foreign key id to string seems to work also.

Mutator or accessor?
