### ISSUE TITLE
How to display data from the embedded Document

### ISSUE THREAD

**Issue by dedidot** [jenssegers/laravel-mongodb#578]
MongoDB Doc : 

{
"_id" : objectId("82737237283928392hh339383"),
"username" : "admine",
"profil" : [
     {
       "address" : "new york",
       "gender" : "male"
     }
],
"like" : 200
}

My Model : 

class Testo extends Eloquent {
    protected $collection = 'testIN';

  protected $fillable = array('username','profil.address','profil.gender');
}

My Controller : 

public function ambl(){

$g = new Testo();
$g = Testo::where('username','=','soimah')->get();

return View('layouts/in', array(
'g' => $g
));
}

View : 
 <?php
    foreach($g as $j){
      echo $j['profil.gender'];
    }
  ?>

Laravel 5.0 and Mongodb
Data profil.gender not show. How to solved ? please

**Comment by chasen** [comment]
could you not do `echo $j['profil']['gender'];` ?

**Comment by ScottSpittle** [comment]
Your profile is an array of documents.
$j['profile'][0]['gender']

**Comment by ahmadsururi** [comment]
work, but data not show bro
