### ISSUE TITLE
Using the connection everywhere

### ISSUE THREAD

**Issue by nbertal** [jenssegers/laravel-mongodb#58]
Hi again,
I would like to use the MongoDB connection outside of a Model (ie. a custom class not dependant of a specific collection).

So far:
DB::getMongoDB() does'nt work (dependency issue, couldn't resolve)
DB::connection('mongodb') returns NULL

What is the best practice?

A) still use your IoC ? Then how can I proceed?
B) Open the connection using the original Mongo PHP library, everytime I need it ? Isn't it efficient because it might trigger multiple connections instead of a single instance?

Thanks in advance!

**Comment by waelwalid** [comment]
@nbertal  

Hi , I have the same issue so could you please tell me what is your solution ? 
Thank you :)
