### ISSUE TITLE
Hybrid MySql relation return error on 2.2.0!

### ISSUE THREAD

**Issue by duongtdvn** [jenssegers/laravel-mongodb#581]
Hi,
I have just upgraded from 00d3b8b0a33ec4fcca88e43a9b0e0389efb90715 to v2.2.0 and this error returned:
<pre>
Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\MySqlConnection given, called in /home/vagrant/Code/Laravel/maidzo/admin/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Model.php on line 509 and defined
</pre>
does anyone facing the same issue?

**Comment by jenssegers** [comment]
In what situation do you get this error? It seems that it is not covered by the unit tests.

Anyway, I added back a method that I deleted to cleanup the class, does it work now?

**Comment by duongtdvn** [comment]
I'm facing the issue while declaring connection as mysql as documented in: https://github.com/jenssegers/laravel-mongodb#mysql-relations

<pre>
use Jenssegers\Mongodb\Model as Eloquent;

class Customer extends Eloquent implements Transformable {
    protected $connection = 'mysql';
}
</pre>

Just applied your changes but the error still occur.

**Comment by jenssegers** [comment]
But that doesn't look right. It should be `Jenssegers\Eloquent\Model` if you want to use MySQL. There is also a `HybridRelations` trait that you can now add to original Eloquent models.

**Comment by jenssegers** [comment]
Try this:

```
use extends \Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\HybridRelations;

class Customer extends Model implements Transformable {

    use HybridRelations;

}
```

**Comment by duongtdvn** [comment]
Ah okay, the `Jenssegers\Eloquent\Model`fixed the issue without the need of change of Model.php. I have no idea why it work with `Jenssegers\ Mongodb\Model` before.
Thank you so much!
