### ISSUE TITLE
_id field always having default value

### ISSUE THREAD

**Issue by sengarawi** [jenssegers/laravel-mongodb#582]
Is there any way so that when we assign some value to _id then it should use that assigned value instead of default random string. 

I am trying to move my old mysql table id to mongo so that we can use our old data in similar manner

Please suggest

**Comment by xfight0** [comment]
:+1: I also want to use my id instead of default id

**Comment by HombreGeek** [comment]
Try to create a unique ID in your migrations ($table->unique('Id');), and use it as your own.

**Comment by HombreGeek** [comment]
> Is there any way so that when we assign some value to _id then it should use that assigned value instead of default random string.
> 
> I am trying to move my old mysql table id to mongo so that we can use our old data in similar manner
> 
> Please 

Try to create a unique ID in your migrations ($table->unique('Id');), and use it as your own.
