### ISSUE TITLE
Laravel 5.1 Eloquent method :all() and :find() return empty values.

### ISSUE THREAD

**Issue by Krlinhos** [jenssegers/laravel-mongodb#584]
Hi!, 

I have all configurated, my database connection, models, controller, providers etc. But when I try to use `all( )` or `find( )` return empty. I have seen a Issue #317 from 2014, and I follow the steps that you have said. And my query log shows this:

`Array ( [query] => promociones.find([],[]) [bindings] => Array ( ) [time] => 0.02 )`

Method `:first( )` works fine, and `:where( )`, etc, etc 

Thanks!

**Comment by rcravens** [comment]
I'm experiencing the same issue. Did a bit of debugging and in 

jenssegers/mongodb/src/jenssegers/Mongodb/Query/Builder.php

in the 'getFresh' function I placed a few var_dumps for tracing

![image](https://cloud.githubusercontent.com/assets/228847/10120726/0ceb5c24-6491-11e5-8c14-b110b8e9c625.png)

I see 'before' being emitted, but not the 'after'. Not sure why this is not returning a cursor?

**Comment by sagarrayudu** [comment]
I'm having same problem I wonder why this question has no support since it was posted ?

**Comment by Krlinhos** [comment]
For me, it was an error in my code, but it is just fixed
