### ISSUE TITLE
MongoDate values are coming back as Carbon\Carbon

### ISSUE THREAD

**Issue by ScottSpittle** [jenssegers/laravel-mongodb#585]
```
    return $this->staff->where($query)
        ->orderBy('last', 1)
        ->orderBy('first', 1)
        ->skip($skip)
        ->limit(21)
        ->get();
```

\Log::info(get_class($test->created_at));
That log outputs "Carbon\Carbon", when in the DB it is clearly a MongoDate.

If I were to dd($test), I'd get created_at as;
    "created_at" => MongoDate {#344
      +sec: 1424270085
      +usec: 203000
    }

If I were to dd($test->created_at), I'd get;
Carbon {#348
  +"date": "2015-02-18 14:34:45.000000"
  +"timezone_type": 3
  +"timezone": "UTC"
}

**Comment by jenssegers** [comment]
Eloquent returns dates as Carbon as well. This is expected behaviour.

**Comment by jenssegers** [comment]
Carbon dates are much easier to work with than MongoDate's

**Comment by ScottSpittle** [comment]
Ok, I'm trying to move over from MongoLid you see. No worries. It's just strange that other fields with MongoDate type are return as MongoDate, it's just created_at which is changed to carbon.

Thanks for the response

**Comment by sakalauskas** [comment]
If you want to return them as Carbon instance, just declare additional fields in the model.

For example: 
	protected $dates = [ 'created_at', 'updated_at', 'another_date' ];
