### ISSUE TITLE
Bug : Version 2.2.0 changed created_at field format

### ISSUE THREAD

**Issue by erkanarslan** [jenssegers/laravel-mongodb#587]
I was using version 2.1.7 and created_at fields were being saved like this in MongoDB:

```
ISODate("2015-09-16T21:10:44.822Z")
```

After I upgraded to 2.2.0 created_at field is being saved like this:

```
{
    "date" : "2015-09-16 21:11:26.000000",
    "timezone_type" : NumberLong(3),
    "timezone" : "UTC"
}
```

That breaks my application. What the hell is this? Is this something new that I didn't heard or a serious bug?

My Laravel version is 5.1.\* btw.

**Comment by ScottSpittle** [comment]
I'm with the same issue. https://github.com/jenssegers/laravel-mongodb/issues/585

**Comment by jenssegers** [comment]
Can you try the dev-master branch? I tried something small in #b4dd583.

**Comment by ScottSpittle** [comment]
Sure, just writing a ticket now regarding an issue I'm having with relationships. :D

**Comment by erkanarslan** [comment]
That solves the problem. Thank you.
