### ISSUE TITLE
Add support for the $casts attribute

### ISSUE THREAD

**Issue by tacone** [jenssegers/laravel-mongodb#589]
Hello, I'm working on Laravel 5.1 and looking at the model, I found an undocumented attribute, named `$casts`:

```
/**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'confirmed' => 'integer'
    ];
```

So far, so good, with the only problem that it does not get applied on save, it only gets applied on `toArray()`. I have no clue if it is present on former Laravel versions, but it may as well be ignored if missing or empty.

I think it would a great addition to this, library, and very easy to implement as the conversion functions are already there. If would also not break the retrocompatibility as when that attribute is empty, it just does nothing.

Let me know what you think about it.

**Comment by nayzawoo** [comment]
+1

**Comment by mean-cj** [comment]
+1

**Comment by silencechow** [comment]
+1

**Comment by inazioKam** [comment]
+1

**Comment by juliancc** [comment]
+1

**Comment by webexpert4rv** [comment]
++1

**Comment by devmustafa** [comment]
Any updates?

**Comment by zishiguo** [comment]
not ways to solve ?
