### ISSUE TITLE
Query between dates

### ISSUE THREAD

**Issue by Alexandreh** [jenssegers/laravel-mongodb#594]
I noticed a problem when I attempted to get the records between 2 dates, like this:

```php
$month = new Carbon("first day of September");

self::where(function ($query) use ($month) {
    $query->where('date', '>=', $month);
    $query->where('date', '<=', $month->modify('last day of this month'));
    
    // Also, the condition below returns a empty Collection object 
    //$query->whereBetween('date', [new Carbon("first day of September"), new Carbon("last day of September")]);
})->get();
```

It returns a empty Collection object, but if I comment any one of the `$query` lines, it works fine.

I'm running it on Lumen.

**Comment by Alexandreh** [comment]
Solved. I forgot to convert date values to a `MongoDate` object.

**Comment by mohammad-69** [comment]
@henriale Can you put your code here how did you solve it ? I'm facing same problem

**Comment by worker-zx** [comment]
@henriale @mohammad-69 Can you put your code here how did you solve it ? I'm facing same problem

**Comment by henriale** [comment]
@mohammad-69 @worker-zx sorry guys, but I don't have the solution anymore. however, I guess you should cast `Carbon` object to `MongoDate`

**Comment by marcnewton** [comment]
This post shows up still in 2019 🔢 

`use MongoDB\BSON\UTCDateTime;`

`new UTCDateTime(new \DateTime('now'));`

Carbon extends DateTime so a carbon instance should be usable:

`new UTCDateTime(Carbon::now());`

**Comment by BroJenuel** [comment]
> Solved. I forgot to convert date values to a `MongoDate` object.

where did you get the MongoDate?

**Comment by divine** [comment]
> > Solved. I forgot to convert date values to a `MongoDate` object.
> 
> where did you get the MongoDate?

https://www.php.net/manual/en/class.mongodate.php

Please, don't reply to closed issues. Have a question? Create a new discussion. Have an issue? Create it.

A lot of people are getting this notification and it becomes noisy to maintain this library.

Thanks!
