### ISSUE TITLE
BelongsToMany relationship when extending Eloquent Model

### ISSUE THREAD

**Issue by rbruhn** [jenssegers/laravel-mongodb#596]
Ran into this issue when upgrading. My BelongToMany relationships for models are no longer working due to the following

Jenssegers\Mongodb\Eloquent\HybridRelations.php

```
if ($related instanceof Model)
```

I have a Project model that extends Jenssegers\Eloquent\Model because it has a relationship with a Mongo collection. However, it also has a many to many relationship with an Actor model in MySql. Actor extends Illuminate\Database\Eloquent\Model.

When getting to the if statement above, Actor is not being seen as an instance of Model.
Mongodb\Model

```
use Illuminate\Database\Eloquent\Model as BaseModel;
Model extends BaseModel
```

Not sure if this is a PHP issue or "instanceof" simply not being used right. From what I read, it looks like it should work but does not.

I looked back at a previous version...

```
if (!is_subclass_of($related, 'Jenssegers\Mongodb\Model'))
```

I used that instead and it works correctly.

Edit: I've confirmed this is an issue with any relationship where one model uses "Jenssegers\Eloquent\Model" and subsequent models with relations use "Illuminate\Database\Eloquent\Model"

My Project model needs Jenssegers\Eloquent\Model to interact with another MongoDB relationship but also interacts with other MySql relationships. All MySql relationships are broken until fixed with the previous version code above. Seems kind of funky to require all my other models to use Jenssegers\Eloquent\Model when they have nothing to do with MongoDB.

**Comment by lohiaad** [comment]
Facing same issue. Need to extend Jenssegers\Eloquent\Model in all model

**Comment by jenssegers** [comment]
Can you check if dev-master is working for you?

**Comment by rbruhn** [comment]
Yes, it works. I see you changed back to ( ! is_subclass_of) and all my tests work accordingly.
