### ISSUE TITLE
BelongsToMany in EmbedMany silently fail when the embed model hasn't an ID yet

### ISSUE THREAD

**Issue by Rezouce** [jenssegers/laravel-mongodb#597]
``` php
<?php
use Jenssegers\Mongodb\Model;

class Main extends Model
{
    public function embeds()
    {
        return $this->embedsMany('Embed');
    }
}

class Embed extends Model
{
    public function belongs()
    {
        return $this->belongsToMany('Belong');
    }
}

class Belong extends Model
{
}

$belong = new Belong;
$belong->save();

$main = new Main;
$embed = new Embed;
$main->embeds->associate($embed);

$embed->belongs()->save($belong);

$main->save();
```

When executing this code the belongsToMany association silently fail because of the lack of ID in the embed object.

We expect this code to work or, at least, to throw an exception allowing us to know why this is not working.

I assume the problem also exists with the other type of relations.

**Comment by hackel** [comment]
Try `$embed->belongs()->attach($belong);` before `$main->embeds->associate($embed);`.
Remember, associate() is merely copying the raw attributes from the embedded model to your parent model, so if you modify it after the fact, that new information won't be saved. The two objects are not linked.
