### ISSUE TITLE
Use both MySQL Models and MongoDB models

### ISSUE THREAD

**Issue by adamlc** [jenssegers/laravel-mongodb#6]
Our application uses both MySQL and MongoDB connections, but I'm afraid I can't get both working together.

I have tried various things such as tweaking namespaces etc. If I remove the 'Jenssegers\Mongodb\MongodbServiceProvider' from providers the MySQL eloquent models work as expected.

Is there any way to get them working side by side? My guess is the ConnectionResolver has been changed and its breaking MySQL models.

Im quite new to Laravel so not 100% if the above this the problem.

**Comment by rkang30** [comment]
I have set mysql as my defaut db and set mongodb as a second. When I print DB::connection('mongodb'), it was still pull my mysql db name. Could u help me with this issue please?
