### ISSUE TITLE
Add "ext-mongo" to the composer.json require

### ISSUE THREAD

**Issue by TJM** [jenssegers/laravel-mongodb#605]
I suggest that the following should be added to the require section of composer.json.

```
"ext-mongo": "*",
```

That would ensure the mongo PHP Extension is installed, which is of course required.

REF: http://blog.mongolab.com/2014/05/mongodb-and-the-new-php-on-heroku/

**Comment by jenssegers** [comment]
Would this work in the suggests section as well?

**Comment by TJM** [comment]
Hi Jens,

According to the documentation: (https://getcomposer.org/doc/04-schema.md#suggest)
> Suggested packages that can enhance or work well with this package. These are just informational
> and are displayed after the package is installed, to give your users a hint that they could add more
> packages, even though they are not strictly required.



The README.md even indicates that it is *required*. It seems logical to include any required packages in the composer.json file: https://getcomposer.org/doc/02-libraries.md#platform-packages

~tommy

**Comment by jenssegers** [comment]
The reason I don't want to force it in the require section is because HHVM doesn't have a mongodb extension yet. Also; people can use https://github.com/mongofill/mongofill instead of the extension.

**Comment by TJM** [comment]
Hmmm, well I have a few responses to that...

* In the "ruby" world, the "Gemfile" has a notion of "platform" (mri, jruby, etc) so that you can require certain "packages" (gems) on certain platforms ... perhaps if composer intends to support multiple incompatible platforms it should look into implementing the same thing? Perhaps they are trying to? https://github.com/composer/composer/issues/1468 (and related)
* If mongofil is going to implement the same capabilities as the "official" (native?) mongo extension, then perhaps there needs to be a way to say "provides ext-mongo" and respond to all the same calls so that people don't need to modify third party code based on what extension they are using to access mongodb. Or perhaps you need an "HNI version" (branch) until the tools have caught up with having incompatible platforms? ... (from the mongofil readme)

> Note: as pure PHP, the phpversion('mongo') will return null and some libraries as Doctrine will not work properly without modifications, so please use the HNI version.

* It is ultimately your project and your prerogative, but I thought the point of a composer.json file was to list all your requirements so that people could install all requirements, including a requirement of a "sub package" (such as this one) without having to become an expert in each one. If someone is going to run on some non-standard platform, then perhaps they could deal with that? What is your core audience/market running in production?

By adding this "required" extension to the composer.json, we were able to deploy to heroku. There wasn't any "oh yea, by the way, you have to make sure you install ...." necessary, it was in the documented place to keep dependencies. Like I said, its your project :)

~tommy
