### ISSUE TITLE
Allow direct $dsn assignment for MONGOLAB_URI

### ISSUE THREAD

**Issue by TJM** [jenssegers/laravel-mongodb#606]
In PaaS, such as Heroku, when you add on a "MongoDB" service, you get a MONGOLAB_URI, which appears to be the entire $dsn required to connect. It should be possible to set the `$dsn => $_ENV["MONGOLAB_URI"]` rather than having to parse it all out just to be re-combined in Connection.php.

Tommy

**Comment by jenssegers** [comment]
You can pass the entire dsn just by using the dsn config key.

**Comment by TJM** [comment]
My apologies, I looked at the code and didn't see anything that indicated that, but it has been a long time since I worked on PHP :)

~tommy
