### ISSUE TITLE
Laravel 5.1.19 breaks exists()

### ISSUE THREAD

**Issue by adriandmitroca** [jenssegers/laravel-mongodb#607]
This commit https://github.com/laravel/framework/commit/cf668a67bd4959d9265b8e5ea46d0fce24b871f3 broke previously working exists() method with `Call to a member function compileExists() on null` exception.

**Comment by alexandre-butynski** [comment]
Same issue here.

**Comment by RTLer** [comment]
just use this https://github.com/RTLer/laravel-mongodb/commit/4ec4ff96479215dc318e958d3f2f0ccee3842b2f

**Comment by matthewnance** [comment]
Have this issue as well - RTLer's suggestion is much appreciated, but didn't seem to fix the issue for me.

**Comment by Frozire** [comment]
Seems like Laravel 5.1.20 breaks all methods, rather then just exists(), that gets returned from the query builder in:

protected $passthru = [
        'toSql', 'lists', 'insert', 'insertGetId', 'pluck',
        'count', 'min', 'max', 'avg', 'sum', 'exists', 'push', 'pull',
    ];
