### ISSUE TITLE
Eloquent ignored for nested models?

### ISSUE THREAD

**Issue by Tobiasartz** [jenssegers/laravel-mongodb#608]
I have two models: User and Income.
Users embed many Incomes.

My accessors and the $hidden property are ignored for nested models.
I actually suspect that all of the Eloquent configuration is ignored for nested documents.

User model:
```
use Jenssegers\Mongodb\Model;

final class User extends Model
{
    protected $hidden = array('_id');

    public function Incomes() {
        return $this->embedsMany('App\Models\Income');
    }
}
```
Income model:
```
use Jenssegers\Mongodb\Model;

final class Income extends Model
{
    protected $hidden = array('_id');
    public function getStartDateAttribute($value) {
        return 'Test';
    }

    public function getNameAttribute($value) {
        return 'Bla';
    }
}
```
Result:
```
{
	Name: "Barack Obama",
	Incomes: [
		{
			Name: "President of the United States",
			StartDate: {
				date: "2009-01-01 14:03:08.000000",
				timezone_type: 3,
				timezone: "UTC"
			},
			_id: {
				$id: "560e8e9cb0e6dfda498b4579"
			}
		}
	],
	updated_at: "2015-10-02 14:03:08",
	created_at: "2015-10-02 14:03:08"
}
```

As you can see it works on the first model.
How can have laravel-mongodb respect the nested configurations too?

**Comment by hackel** [comment]
Above did you spit out a plain User model, or did you look at $user->Incomes?  Just as with Eloquent, the model is not loaded automatically, even though the data is there.

**Comment by Tobiasartz** [comment]
@hackel Thank you!
That was very helpful.

I ended up modifying my User model like this:

```
    protected $appends = ['Incomes'];

    public function getIncomesAttribute() {
        return $this->Incomes;
    }

    public function Incomes() {
        return $this->embedsMany('App\Models\Income');
    }
```

This way I control the way the Incomes attribute gets returned.
