### ISSUE TITLE
How to remove a belongsToMany relation?

### ISSUE THREAD

**Issue by bitcine-darcy** [jenssegers/laravel-mongodb#609]
I feel like this should be simple...

Say I have:

    $project = new Project();
    $project->save();
    
    $user = new User();
    $user->save();
    
    $user->projects()->save($project);

This works fine. How can I remove the project from the user?

I would expect something like:

    $user = User::find('someUserID');
    $project = Project::find('someProjectID');
    $user->projects()->remove($project);

And yet it's not that simple.

**Comment by hackel** [comment]
@bitcine-darcy Hate to say it, but RTFM.  You want detach(), not remove().  This isn't even related to laravel-mongodb.  See http://laravel.com/docs/5.1/eloquent-relationships#inserting-many-to-many-relationships

**Comment by bitcine-darcy** [comment]
@hackel Oh yes, I found my answer in the laravel docs yesterday after some searching (notice you linked many-to-many when my relation is one-to-many - as I wasn't using "attach", I didn't think I would need to use "detach".)

PS If you hate to say something, you probably shouldn't. ;)

**Comment by hackel** [comment]
@bitcine-darcy Perhaps you should consider not using a bug tracker as a support forum in the future.

**Comment by bitcine-darcy** [comment]
I wasn't aware that I would face such hostility by asking a question, sorry that I'm new around here. I'll be sure to keep your comments in mind.

**Comment by dcatala** [comment]
Just to say, Hackel, your answer help me also to check faster on the manual :). You did not answer for nothing ! 
Bitcine thanks for asking héhé
