### ISSUE TITLE
Select specific fields only for relation

### ISSUE THREAD

**Issue by gildebrand** [jenssegers/laravel-mongodb#611]
First off I want to give a big Thanks(!) for creating such a great package. I hope that I will be able to contribute someday!

I've run into a problem when trying to select specific fields from relations. Take a look at my code below.

```
Customer::with(array('journals' => function($query){
    $query->select("name");
}))->get()
```

I only want to return the field "name" for the hasMany relationship "journals". However, when I put the line `$query->select("name")` in the callback function, the array with journals is empty. It works to use calls like `$query->where("name", "blablabla")` and so on, but the `select` function does unfortunately not seem to work. What could be the problem?

**Comment by azhard4int** [comment]
@gildebrand were you able to resolve this issue? We are getting the similar problem lately?

**Comment by mean-cj** [comment]
Hello @gildebrand 

How do you fix this problem?

**Comment by alignwebs** [comment]
Why no update on this @jenssegers ? Its still the issue

**Comment by HassanKareem** [comment]
I have the same issue, I think there's no way to select custom columns inside with relation

**Comment by BilalTariq01** [comment]
You can select specific fields within the relation, but the reference ID must be included in the selected columns.

```
Customer::with(array('journals' => function($query){
    $query->select("name", "customer_id");
}))->get()
```
as Eloquent uses a subquery for relations.
