### ISSUE TITLE
Facing issue with date field.

### ISSUE THREAD

**Issue by atapatel** [jenssegers/laravel-mongodb#614]
Hi i am facing same issue as below mentioned in stackoverflow. anyone have suggestions for the same??

http://stackoverflow.com/questions/19819870/date-query-with-isodate-in-mongodb-doesnt-seem-to-work

**Comment by hackel** [comment]
I'm dealing with this issue as well.  Is this a PHP issue?  When passing a Carbon date into a where query as in `where('starts_at', '<=', Carbon::now()), the resulting Mongo query is `{"starts_at":{"$lte":{"sec":1446007699,"usec":78000}}}`.  It should be `{"starts_at": {"$lte": ISODate("2015-10-28T04:57:19.000Z")}}`.  The Carbon date is clearly being converted into a MongoDate (in PHP), but the MongoDate isn't being converted into proper Mongo query language.

I thought this would work: `where('started_at', '<=', \DB::raw('IsoDate(' . Carbon\Carbon::now()->toIso8601String() . ')'))`, but no such luck, it gives the dreaded "zero-length keys are not allowed" error.  Not sure where to go from here, short of doing the query manually.
