### ISSUE TITLE
Laravel 5.1.20 Issue - mySQL TO Mongo 

### ISSUE THREAD

**Issue by lukepolo** [jenssegers/laravel-mongodb#618]
Looks like the new update has broken the ability to relate things from mySQL to Mongo.

5.1.19 works fine but once update we get the error :

"Call to a member function compileSelect() on null"

Anyone else seeing this?

**Comment by lukepolo** [comment]
This could help as well : https://github.com/laravel/framework/compare/v5.1.19...v5.1.20

**Comment by l-vear-jt** [comment]
Can confirm that I'm seeing this as well. Working in 5.1.19, broken in 5.1.20.

**Comment by marcoskubis** [comment]
Yes, i have the same problem. You solved it?

**Comment by pfzwaan** [comment]
`namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class MongoUser extends Eloquent implements AuthenticatableContract,
    AuthorizableContract, CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
}`

class User extends MongoUser


https://github.com/barryvdh/laravel-translation-manager

Did the following but when i ran php artisan translation:import still getting the error

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to a member function compileSelect() on null

**Comment by pfzwaan** [comment]
K fixed the problem was in the package itself
