### ISSUE TITLE
FatalErrorException with `illuminate/database` v5.1.20

### ISSUE THREAD

**Issue by CurosMJ** [jenssegers/laravel-mongodb#621]
I was working on a fresh install of Lumen on my box, and the following error came up.

```
FatalErrorException in Builder.php line 1315:
Call to a member function compileSelect() on a non-object
```
NOTE : `Builder.php` is pointing to `illuminate/database/Query/Builder.php`

I just tried to do a very basic `app('db')->collection('users')->get()`.

There's no error if I specify the app to use v5.1.8, v5.1.13, v5.1.16 versions. I presume the previous versions also work fine. The problem is coming with the v5.1.20. 

https://github.com/illuminate/database/releases

https://github.com/illuminate/database/releases/tag/v5.1.20

I am trying to figure out what caused this, and will try to fix it.

**Comment by alexandre-butynski** [comment]
Thanks for your report. This was fixed just now with this pull request : https://github.com/jenssegers/laravel-mongodb/pull/620.

A new version of the package will be released soon with this patch.

**Comment by loonytoons** [comment]
@alexandre-butynski Is this fix also going to be applied to the 2.2 package?

**Comment by jenssegers** [comment]
It was tagged on the master branch so it should be in there, or isn't it?

**Comment by loonytoons** [comment]
I'll check again but didn't appear to be. Just in 2.1.10

**Comment by CurosMJ** [comment]
@loonytoons `2.2.*` will always fail as of now, until a fix is provided. 
If you want to use `2.2.*`, then you can manually specify that you want to use `"illuminate/database":"v5.1.16"` (basically lesser than 5.1.20).

Something like this : 
```
"require": {
        #other dependencies
        "jenssegers/mongodb": "^2.2",
        "illuminate/database":"5.1.16"
    },
```

**Comment by alexandre-butynski** [comment]
@jenssegers I think there is an issue in the package tagging. The 2.1.* tag is more advanced than the 2.2.* tag. This bug fix is present in the 2.1.10 release but not in the 2.2.2.

**Comment by jenssegers** [comment]
You're right, I used the wrong version number! It should be fixed now :)

**Comment by loonytoons** [comment]
Awesome, thanks guys!

**Comment by juanramonperez** [comment]
Thanks!

**Comment by Vittalks** [comment]
Issue is not fixed with this version `"jenssegers/mongodb": "^3.1"`
