### ISSUE TITLE
How do I Perform Inner JOIN in MongoDB using Laravel

### ISSUE THREAD

**Issue by imdketav** [jenssegers/laravel-mongodb#624]
I'm Trying to Join Two Collections at Laravel Side using Laravel Code. But I'm not getting proper data it is displaying data from one table only.

I'm attaching code which i did.

**Books Collection**
      db.books.insert([
        {
            _id: 'b1',
            name: 'Groovy Book',
            category: 'c1',
            authors: ['a1']
        },
        {
            _id: 'b2',
            name: 'Java Book',
            category: 'c2',
            authors: ['a1','a2']
        },
    ]);

**Categories Collection**

db.categories.insert([
    {
        _id: 'c1',
        name: 'sci-fi'
    },
    {
        _id: 'c2',
        name: 'romance'
    }
]);

**Categories.php Model**
    <?php

    namespace my_app;

    use Illuminate\Database\Eloquent\Model;
    use Jenssegers\Mongodb\Model as Eloquent;
    class categories extends Eloquent
    {
        protected $connection = 'mongodb';
        protected $collection = 'categories';
        protected $guarded = [];
        protected $primarykey = "_id";

        public function categories()
        {
            return $this->hasMany('categoty');
        }
    }

**Books.php Model**
    <?php

    namespace my_app;

    use Illuminate\Database\Eloquent\Model;
    use Jenssegers\Mongodb\Model as Eloquent;
    class books extends Eloquent
    {
        protected $connection = 'mongodb';
        protected $collection = 'books';
        protected $guarded = [];
        protected $primarykey = "_id";

        public function books(){
            return $this->belongsTo('categories');
        }
    }

**Helloworld.php Controller**
    <?php

    namespace my_app\Http\Controllers;
    use my_app\Http\Controllers\Controller;
    use my_app\books;
    use my_app\categories;
    use my_app\User;

    class Helloworld extends Controller
    {
        public function __construct()
        {
            $this->middleware('auth');
        }

        public function index()
        {
            $books = DB::table('books')
                ->leftJoin('categories', 'books.category', '=', 'categories._id')
                ->get();
            echo "<pre>";
            print_r($books);
            echo "</pre>";
        }

**Routers.php**
       Route::get('join','Helloworld@index');

Following is the Output which is I'm Getting (Data Only From Books Collection)
![selection_007](https://cloud.githubusercontent.com/assets/15032918/10535565/88f89c44-7401-11e5-838a-f88c02ca7502.png)

**Comment by jenssegers** [comment]
You should use relations instead of joins since MongoDB has no joins.

**Comment by imdketav** [comment]
@jenssegers : Can you give me an example of relation?
I haven't any idea about this.

**Comment by jenssegers** [comment]
Check the Laravel documentation of the readme.

**Comment by smgom** [comment]
Hey @imdketav  are you successful, Can you give me any example?

**Comment by yehanny** [comment]
Since this question still opened here's the link of the documentation on how to use relations using jenssegers on Laravel https://github.com/jenssegers/laravel-mongodb#relations
