### ISSUE TITLE
Why relationships save Object is string?

### ISSUE THREAD

**Issue by bjsun** [jenssegers/laravel-mongodb#625]
Defining One To One Relationships.
Exmample:
class User extends Eloquent
{
  public function profile()
  {
    return $this->hasOne("App/Profile");
  }
}

class Profile extends Eloquent
{
  return $this->belongsTo("App/User");
}

$profile = new Profile();
$profile->age = 20;
$profile->save();

$user = User::first();
$user->profile->save($profile);

User Profile collection:
{"_id": ObjectId("5624694ebffebcda038b459f"), "user_id": "5624694ebffebcda038b459f"}

why user_id is strings, Answer is ObjectId("5624694ebffebcda038b459f");

Why not is MongoId ?

**Comment by ScottSpittle** [comment]
This is preventing me from using the library as all my existing data has them stored as MongoId's. So I cannot use relationships.
