### ISSUE TITLE
sum with group by not working

### ISSUE THREAD

**Issue by pragneshok** [jenssegers/laravel-mongodb#627]
Hello All,

i have two tables called users and sales described below.

table: user having fields[ _id,city,name,email]
table: sales having fields[ _id, us_u_id, us_part_number, us_quantity]

i need results like following mysql query:

select sum(us_quantity) from user left join sales group by city

i have tried following thing
in User modal i have code like following:
public function usersalesgroup(){
        return $this->belongsTo('App\UserSale', 'us_u_id', '_id')
       ->select('city', DB::raw('sum(us_quantity) as total'))
       ->groupBy('u_city');
}

in Controller i have added code like:
$userImport = User::with('usersalesgroup')->get();

Eagerly waiting for your comments...

**Comment by NominationP** [comment]
and how ?
