### ISSUE TITLE
How to find a embedded array of string with string ?

### ISSUE THREAD

**Issue by hitoz** [jenssegers/laravel-mongodb#628]
Hi Guys !

My Database structure like this:
users: {
    roles: {
        "admin",
        "user"
    }
}

And i want to select all users who have Admin Role / User Role.. 
How to do that ?

I tried to use whereRaw, whereIn, and where.. nothing is working for me :(..
User::whereRaw(array("roles" => array("$in" => array("admin"))))
User::where('roles', '=', 'admin')
User::whereIn('roles', array('admin'))

Sorry for my bad english..

Thank you

**Comment by hackel** [comment]
You're saying that "roles" is an embedded document of users, with two properties, admin and user, but what are their values?  You need to change "roles" into an array, then `User::where('roles', '=', 'admin')` should work.
