### ISSUE TITLE
Eloquent Query Scope using ScopeInterface?

### ISSUE THREAD

**Issue by abrarazeem** [jenssegers/laravel-mongodb#631]
First of all thanks for Great Contribution to a community, i came across a requirement where i need to implement query scopes, using ScopeInterface but got to know that Mongodb\Model is not compatible with that interface, Could you please guide us if there is a chance we can use Eloquent Query Scopes.

Thanks Again.

**Comment by ahmedaisar** [comment]
Still no work around for this?

**Comment by abrarazeem** [comment]
Actually there is a workaround, a bit though but it will work,
Use trait to override queries and use trait in Models where you want to apply certain type of query scoping.
like "newQuery()" method of Eloquent class to include your conditions

**Comment by ahmedaisar** [comment]
Can you show me a small example to use "newQuery()" method of Eloquent class in my models.

**Comment by abrarazeem** [comment]
Here is small example,

`trait SomeTrait{

    public function newQuery()
    {
        $query = parent::newQuery();
        $query->where('column',"value");
        return $query;
    }
}


class SomeModel extends Eloquent{
	
	use SomeTrait;

}`

whenever you will be querying SomeModel you will always have this condition in your query, which you defined in SomeTrait, You can put any conditions to include condtion or not in Trait etc.
