### ISSUE TITLE
whereBetween does not select correct date range

### ISSUE THREAD

**Issue by jkpatil211** [jenssegers/laravel-mongodb#632]
I have records like shown below

```
  {

  "_id": "562f18d16f6fc97c0b00002a",
"sg_message_id": "sendgrid_internal_message_id",
"email": "john.doe@sendgrid.com",
"timestamp": 1337197600,
"ip": "64.233.173.205",
"smtp-id": "<4FB4041F.6080505@sendgrid.com>",
"event": "click",
"userToken": "2ddcweb136jaykumarp",
"created_at": "2015-10-20 06:25:21",
"updated_at": "2015-10-20 06:25:21"
  }
```

When I use whereBetween it does not given correct data
the code is as below:

```
$input = Request::input();
$startDate = new MongoDate(strtotime($input['startDate']));  // 2015-10-16
$endDate = new MongoDate(strtotime($input['endDate']));  //2015-10-23
EmailEvents::whereBetween('created_at',array($startDate, $endDate))->get();
```

<b>Actual Result</b>: The data I get is from date 2015-10-16 to less than 2015-10-23 like in above example
<b>Expected result</b> : Data with date 2015-10-16 to  2015-10-23

If the value of created_at field is 2015-10-23  00:00:00 then the result shows that record 
but if it is like 2015-10-23 12:00:45 it does not show.
Looking for your positive reply

**Comment by Vagabondtq** [comment]
i same

**Comment by PardeepGrover** [comment]
I am facing the same issue.
