### ISSUE TITLE
Who can help me?

### ISSUE THREAD

**Issue by yufeiGit** [jenssegers/laravel-mongodb#634]
Whoops, looks like something went wrong.

``Argument 1 passed to Illuminate\Auth\EloquentUserProvider::validateCredentials() must be an instance of Illuminate\Contracts\Auth\Authenticatable, instance of App\User given, called in /alidata/www/laravel-system/vendor/laravel/framework/src/Illuminate/Auth/Guard.php on line 390 and defined``

**Comment by hackel** [comment]
This has absolutely nothing to do with laravel-mongodb.  You need to implement Illuminate\Contracts\Auth\Authenticatable in your User model.  The error message seems rather self-explanatory, no?  Please direct support questions to forums or Stackoverflow.  Github issues are for bugs only.  Thank you.

**Comment by yufeiGit** [comment]
yes. Is my fault. sorry.

**Comment by hackel** [comment]
@yufeiGit Please close the bug report.
