### ISSUE TITLE
Would like option to avoid using aggregation framework during pagination

### ISSUE THREAD

**Issue by omanizer** [jenssegers/laravel-mongodb#636]
Line 174 of Jenssegers\Mongodb\Query\Builder.php

```
if ($this->groups or $this->aggregate or $this->paginating)
```

This forces any paginated query to utilize the aggregation framework.  Is there a reason for this?  My case for otherwise is simply that the aggregation framework is sometimes 10x slower on some simple queries than a basic find operation.  Specifically when I'm adding a $sort operation after a $match operation, I'm getting query results that take 7 seconds when an equivalent find/sort operation is taking 40ms on the same collection.

Any thoughts?

**Comment by RatkoR** [comment]
Hi,

we're facing the same issue. Is there any other way to do the pagination that doesn't user aggregation?

**Comment by ohmance** [comment]
It's been on my task list but I haven't gotten to it yet.

**Comment by RatkoR** [comment]
We've extended Eloquent and Query Builder classes so that ```QueryBuilder::forPage()``` doesn't set ```paginating``` variable.

Don't know if this threw universe out of ballance, but it seems to be working for us ok.
