### ISSUE TITLE
Infinite loop on $model->push() and embedsMany

### ISSUE THREAD

**Issue by Kaylakaze** [jenssegers/laravel-mongodb#637]
I have a model ($m1) with an embedMany relationship to another model ($m2). If I update $m2 and use $m1->push() to try to save $m1 with relations, an infinite loop occurs. It appears that $m2 has a relationship to $m1 so the recursive push function never finishes.

(this shouldn't be confused with the mongodb specific $model->push(params) function that pushes a value or array onto an array)

**Comment by hackel** [comment]
You probably shouldn't be using push() with embedded relationships.  Even if it did skip the automagically created reverse relationship, it's still going to save your parent model once for every single relationship.  What I've settled on doing is:
```php
$m1->m2s()->associate($m2);
$m1->save();
```
Yes, it's annoying that you have to associate every single relationship, but at least that way there's only one save.  I think that the save() method needs to be overriden to do this automatically for embedded relationships.

**Comment by hackel** [comment]
Okay, here's what I did to my model to fix this:
```php
    public function save(array $options = [])
    {
        $this->syncEmbeddedRelations();
        parent::save($options);
    }

    public function syncEmbeddedRelations()
    {
        foreach ($this->relations as $relation => $value) {
            if (
                ($value->getParentRelation() && $value->getParentRelation()->getRelated() != $this) &&
                method_exists($this, $relation) &&
                $this->$relation() instanceof EmbedsOneOrMany
            ) {
                $value->syncEmbeddedRelations();
                $this->$relation()->associate($this->$relation);
            }
        }
    }
```
This allows freely setting values on embedded relations and associating them automatically when saving the parent, without redundant DB queries.
