### ISSUE TITLE
Is it possible to set the ordering of an index?

### ISSUE THREAD

**Issue by geofflancaster** [jenssegers/laravel-mongodb#638]
Mongo allows you to specify a 1 or -1 order for indexes. Is this possible with laravel-mongodb?

**Comment by cnhttpd** [comment]
/**
     * Simulate order by clause on the collection.
     *
     * @param  string  $key
     * @param  string  $direction
     * @return $this
     */
    public function orderBy($key, $direction = 'asc')
    {
        $descending = strtolower($direction) == 'desc';

        return $this->sortBy($key, SORT_REGULAR, $descending);
    }

**Comment by geofflancaster** [comment]
Thanks @cnhttpd. I'm familiar with the orderBy method, but that was not my question.

My question was dealing with Blueprint and creating an index on a collection.

**Comment by hackel** [comment]
Just look at the source!  Taking a peek at the Blueprint::index method, it would seem you can just do `$collection->index(['name' => -1]);`
