### ISSUE TITLE
Relation using mongodb and mysql

### ISSUE THREAD

**Issue by Danjavia** [jenssegers/laravel-mongodb#639]
I have to model 

> themes ( mongodb )
> users ( mysql )

I'm create a method user on theme model to call the user who's create 

```
public function user ()
{
    return $this->belongsTo( 'ThemeGenerator\User' );
}
```

After when I call the user in the view I try $theme->user()->username, $theme->user->username.

But noting happens.

Please help me thanks!

**Comment by steveneaston** [comment]
Does your `User` model extend `Jenssegers\Eloquent\Model`? It needs to extend that, rather than the default `Illuminate\Database\Eloquent\Model`.

**Comment by Danjavia** [comment]
Yeah, but the user model run directly on mysql. It's maybe cause a trouble?
