### ISSUE TITLE
HybridRelations error

### ISSUE THREAD

**Issue by midgard** [jenssegers/laravel-mongodb#643]
Hi, I got this error:

FatalErrorException in Model.php line 19:
Trait 'Jenssegers\Mongodb\Eloquent\HybridRelations' not found

Why?

**Comment by tobias-kuendig** [comment]
Did you run `composer dump-autoload`?

Does this file exist in your vendor directory?
`vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/HybridRelations.php`

**Comment by foolish15** [comment]
I got the same issue. It because of I still use laravel version 4.2 that mean I have to use "jenssegers/mongodb" version "2.0.*" and HybridRelations does not exist. I'm still stuck on that.
