### ISSUE TITLE
Connection type check in newBaseQueryBuilder 

### ISSUE THREAD

**Issue by tobias-kuendig** [jenssegers/laravel-mongodb#649]
My tests are failing since version 2.1.9.

The tests are running against a sqlite in memory database so I set the connection during construction:

``` php
public function __construct(array $attributes = [])
{
    parent::__construct($attributes);
    if (app()->environment() == 'testing') {
        $this->setConnection('sqlite');
    }
}
```

With version 2.1.8 everything worked fine. Since 2.1.9 I am getting the following exception:

```
ErrorException: Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\SQLiteConnection given, called in /www/x/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Model.php on line 519 and defined
```

I pinned the problem down to the newBaseQueryBuilder method. [In 2.1.8 it contained a check](https://github.com/jenssegers/laravel-mongodb/blob/v2.1.8/src/Jenssegers/Eloquent/Model.php#L279) to see if `$connection` is an instance of `\Jenssegers\Mongodb\Connection`. [In 2.1.9 this check is gone](https://github.com/jenssegers/laravel-mongodb/blob/v2.1.9/src/Jenssegers/Mongodb/Model.php#L521).

[If I add back the `instanceof` check](https://github.com/OFFLINE-GmbH/laravel-mongodb/commit/13cf99205bebecfe63eb187c360389416711fbdc) everything is working again.

Why was it removed? Do I have to change something on my side? Should I open a PR?

**Comment by alexanderkraemer** [comment]
Any solution to this problem? @tobias-kuendig 
I have the same problem in my application.
