### ISSUE TITLE
laravel-mongodb - not working after update laravel

### ISSUE THREAD

**Issue by Hussam3bd** [jenssegers/laravel-mongodb#657]
after update laravel the 'laravel-mongodb' ErrorException in Builder.php line 13:

Declaration of Jenssegers\Mongodb\Query\Builder::pluck() should be compatible with Illuminate\Database\Query\Builder::pluck($column, $key = NULL)

Image of the problem:
http://imgur.com/epXO8EA

**Comment by Hussam3bd** [comment]
this error fix after add $key parameter to pluck() function
in : **src\Jenssegers\Mongodb\Query\Builder.php**

    public function pluck($column, $key = null)
    {
        $result = (array) $this->first([$column]);

        // MongoDB returns the _id field even if you did not ask for it, so we need to
        // remove this from the result.
        if (array_key_exists('_id', $result))
        {
            unset($result['_id']);
        }

        return count($result) > 0 ? reset($result) : null;
    }

**Comment by jenssegers** [comment]
Is this still an issue?
