### ISSUE TITLE
Incompatibility with new mongodb driver?

### ISSUE THREAD

**Issue by wissamk** [jenssegers/laravel-mongodb#658]
Hi,
The driver works fine with the legacy pecl mongodb driver: https://pecl.php.net/package/mongo

However, it looks like there is incompatibility with the new driver: https://pecl.php.net/package/mongodb

More info about the two drivers here: https://docs.mongodb.org/ecosystem/drivers/php/

Any pointers?

Thank you

**Comment by paulocoghi** [comment]
I confirm this. I installed only the new `mongodb` pecl driver and [laravel-mongodb](https://github.com/jenssegers/laravel-mongodb), and it returns `Class 'MongoClient' not found`

I have installed and successfully enabled the extension in both **cli** and **fpm** .ini file

Both `phpinfo()` to fpm and `php -i` confirm the correct installation:

```
mongodb

mongodb support => enabled
mongodb version => 1.0.0
mongodb stability => stable
libmongoc version => 1.2.0
libbson version => 1.2.0
```

**Comment by paulocoghi** [comment]
Lavarel MongoDB only works with deprecated `mongo` driver at the moment.

**Comment by amiri27** [comment]
@jenssegers do you have any plan to support new mongodb driver?

**Comment by jenssegers** [comment]
I should check out what the differences are between the old and new version. Is there a changelog or something we can check with differences between the two?

**Comment by amiri27** [comment]
This is the new version of mongodb driver:

http://mongodb.github.io/mongo-php-driver/

**Comment by paulocoghi** [comment]
Since Laravel MongoDB doesn't play well with deprecated `mongo` driver in HHVM, implementing the new driver `mongodb` would enable everyone that runs HHVM to use Laravel with MongoDB

The issue with Laravel MongoDB and HHVM is explained [here](https://github.com/jenssegers/laravel-mongodb/issues/298) and it seems unfixable for [this reason](https://github.com/mongofill/mongofill/issues/23).

**Comment by wissamk** [comment]
I am getting 'SASL Authentication failed on database' error when attempting to connect to a remote database. No error when using the latest driver?!
Any pointers to integrate this driver to the library Jens?

**Comment by joaokmz** [comment]
Also with php7.

**Comment by syntheticminds** [comment]
I forked this repo yesterday to see how easy it would be to implement the new driver. It's very different to the 'legacy' one and even with the [userland library](https://github.com/mongodb/mongo-php-library), there is a lot of work to be done. I like the new driver and library but some things are trickier. For instance (and I could very well be mistaken here) but the new driver doesn't seem to expose MongoDB's cursor methods like the old library.

**Comment by jenssegers** [comment]
@syntheticminds Do you know if there's already a homebrew version of the new mongodb ext?

**Comment by syntheticminds** [comment]
I wouldn't know; I use [Homestead](http://laravel.com/docs/master/homestead). If you provision a box with the following in *~/.homestead/after.sh*, you'll be running the new driver.

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list

sudo apt-get update
sudo apt-get install mongodb-org pkg-config libsasl2-dev -y

sudo pecl install mongodb

echo 'extension=mongodb.so' | sudo tee /etc/php5/mods-available/mongodb.ini
sudo ln -s /etc/php5/mods-available/mongodb.ini /etc/php5/fpm/conf.d/mongodb.ini
sudo ln -s /etc/php5/mods-available/mongodb.ini /etc/php5/cli/conf.d/mongodb.ini

sudo service php5-fpm restart
```

I guess there are two approaches to get PHP 7 and HHVM support:
1. Use the mongodb/mongo-php-library. It does take a lot of the heavy lifting out and then cursor opperations can be performed as options on the queries themselves.
2. Use mongofill/mongofill so the MongoDB extension isn't even needed. Not sure what the performance hit is and the repo looks a bit quiet.

**Comment by infernobass7** [comment]
Has there been any updates to when mongodb will be considered as the driver for this package?

**Comment by jenssegers** [comment]
I'm working on a new version, but a lot of stuff has changed.

**Comment by infernobass7** [comment]
Thanks! That is good to know!

**Comment by jenssegers** [comment]
I currently pushed my "work in progress" changes to this branch: https://github.com/jenssegers/laravel-mongodb/tree/pecl-mongodb

Tests are still failing, would be great to have some pull requests so that we can release this faster!

**Comment by lukepolo** [comment]
I only see 1 failed test in travis , is there more that need to be tested ? I can possibly work on this later tomorrow

**Comment by jenssegers** [comment]
@lukepolo No there are still more tests failing, check my last push.

**Comment by ThibaudDauce** [comment]
Hi, I just ran the tests on the pecl-mongodb branch and everythings seems to work properly with the new driver and PHP 7 (on ArchLinux)

I just ran into one issue with the `whereIn` function that doesn't match anymore the Laravel Collection `whereIn` signature…

**Comment by devdreamajax** [comment]
Hi, I have installed mongo-hhvm driver with php version of 5.6. I have connected the mongo database while executing hhvm filename.php. I got an error as 
"**Uncaught exception: Could not open extension /usr/lib/x86_64-linux-gnu/hhvm/extensions/20150212/mongo.so: /usr/lib/x86_64-linux-gnu/hhvm/extensions/20150212/mongo.so: cannot open shared object file: No such file or directory**" . 
In php.ini file , i have specified extensions as, 
**hhvm.dynamic_extension_path=/usr/lib/x86_64-linux-gnu/hhvm/extensions/20150212,
hhvm.dynamic_extensions[mongodb]=mongodb.so .** 
kindly provide me solution to proceed further.

**Comment by paulocoghi** [comment]
What you get with `phpinfo()`? Can you paste the mongodb part in your results?

**Comment by devdreamajax** [comment]
![mongo](https://cloud.githubusercontent.com/assets/24584252/21252149/80a352ae-c37a-11e6-9a65-124f5b6c873b.png)
 **@paulocoghi**  Thanks for your response ,also i have changed the hhvm.dynamic_extension_path to "/usr/lib/php/20131226/mongo.so"  and restarted the apache server. But it dint work it out, Can you please suggest to continue the process .

**Comment by paulocoghi** [comment]
Now I see that you are trying to use the old `mongo` driver. Unfortunately **laravel-mongodb** [doesn't play well](https://github.com/jenssegers/laravel-mongodb/issues/298) with it in **hhvm** as I explained before.

You have two options:

1 - Use the new `mongodb` driver, available and stable in both HHVM and PHP7 along with **laravel-mongodb** version 3.x

2 - Use the old `mongo` driver with PHP 5.6, instead of HHVM

**Comment by puffstream** [comment]
How do you install an earlier version like 3.0.x or 3.1.x?
