### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by chenchaochen** [jenssegers/laravel-mongodb#661]
Hi, 
We're trying the SSL and replicaSet with MongoDB. Here's our settings. 

'connections' => [

```
    'mongodb' => [
        'driver'   => 'mongodb',
        'host'     => [
          'host1:27017',
          'host2:27017'
        ],
        'database'       => 'testxx',
        'options'  => [
          'ssl'      => true,
          'db'       => 'testxx',
          'username' => 'userxxx',
          'password' => 'passxxx',
          'connectTimeoutMS' => 3000,
          'replicaSet'     => 'replsetxxx',
          'readPreference' => MongoClient::RP_PRIMARY
        ],
        'driver_options' => [
          'context' => stream_context_create( [
            'ssl' => [
              'local_cert' => '/xxx/ssl/client.pem',
              'cafile'     => '/xxx/ssl/mongoCA.pem',
              'allow_self_signed' => false,
              'verify_peer'       => true,
              'verify_peer_name'  => true,
              'verify_expiry'     => true
            ]
          ])
        ]
    ],
```

]

Things seem work fine (both SSL and replicaSet) with this setting. However, we're wondering if we can catch an error when something's wrong such as disconnection. 
For example, we can catch the duplicat error using native PHP as below. 

 try {
    $col->insert($doc, $MONGO_WRITE_CONCERN);
  }
  catch (MongoCursorException $e) {
    if ($e->getCode()==64 &&
        strstr($e->getMessage(),'waiting for replication timed out')) {
      if (! $DEGRADE_MODE) {
        echo "It is written to the primaryDB. However, replicationDB is not written.\n";
        echo "To the user, programs need to display successful this.\n";
        echo "To the system administrator, programs need to inform this.\n";
        echo " code: ".$e->getCode()."\n";
        echo " errormsg: ".$e->getMessage()."\n";
        $MONGO_WRITE_CONCERN = array("w"=>"MultipleDC", "wtimeout"=>$DEGRADE_WTIME);
        $DEGRADE_MODE = true;
        echo "Change to DEGRADE_MODE\n";
   }

My question is how we're gonna do that using laravel-mongodb drive. Is there a way to catch and handle the errors?

Thanks,

**Comment by nabedesu** [comment]
> My question is how we're gonna do that using laravel-mongodb drive.
> Is there a way to catch and handle the errors?

If you use the native class then how is this?
In my environment, this worked well.

------------------------------------
    try {
      $coll->insert($doc, $MONGO_WRITE_CONCERN);
    } catch (\Exception $e) {
      if ($e->getCode() == 64) {
        echo "waiting for replication timed out.\n";
      } else {
        throw $e;
      }
    }
------------------------------------

**Comment by developernaren** [comment]
I am trying to connect to [compose.io](https://www.compose.com/) using this package. A test in local has succeeded without ssl but seems compose.io requires ssl, this is my config file.

    'driver' => 'mongodb',
            'host' => [env('MONGO_DB_HOST', '127.0.0.1'), env('MONGO_DB_HOST_2', '127.0.0.1')],
            'port' => env('MONGO_DB_PORT', 27017),
            'database' => env('MONGO_DATABASE', 'mydb'),
            'username' => env('MONGO_USERNAME', ''),
            'password' => env('MONGO_PASSWORD', ''),
            'options' => [
    'ssl' => true,
    'db' => 'mydb'
    ],
            'driver_options' => [
    'context' => stream_context_create([
        'ssl' => [
            'local_cert'        => base_path('mongo.pem'),
            'cafile'            => base_path('mongo.pem'),
            'allow_self_signed' => true,
            'verify_peer'       => true,
            'verify_peer_name'  => true,
            'verify_expiry'     => true,
        ]
    ])
    ]


No suitable servers found (`serverSelectionTryOnce` set). I have correctly set config in my `.env` file. I can confirm that the credentials work because I can connect to compose using
`$ mongo --ssl --sslCAFile mongo.pem <composeurl>:<port>/<database>  -u<username> -p<passsword>`
 
How do I reflect this config in the configuration file?

**Comment by outrunthewolf** [comment]
Same issue @developernaren 

Did you solve it?

**Comment by developernaren** [comment]
unfortunately,  no. I pushed this back and have continued with Mongo 2.I will let you know if I find a solution. Keep me posted on your progress as well ;)

**Comment by george-viaud** [comment]
It seems that using stream_context_create() inside config renders a null value for me - perhaps something has changed in how config is cached, or even how stream_context_create() works such that this results in a null value after caching?    More specifically, I am trying to setup a proper ssl connection to my database with cafile and other context options.
