### ISSUE TITLE
PHP 7 Support?

### ISSUE THREAD

**Issue by joaokamun** [jenssegers/laravel-mongodb#667]
Any chance of having the mongo driver updated to work with php7?

**Comment by mckomo** [comment]
+1

**Comment by jhariani** [comment]
AFAIK, there is no mongo PHP driver that works with PHP7 at the moment. See https://jira.mongodb.org/browse/PHPC-285 for progress on the new, phongo based one. Probably need to wait for the driver before @jenssegers can support it in this library...

**Comment by joaokmz** [comment]
Oh I see.. Thanks @jhariani !

**Comment by jhdxr** [comment]
According to mongodb/mongo-php-driver#175 , https://pecl.php.net/package/mongodb has released v1.1 for php7

**Comment by i0** [comment]
Compatibility with PHP 7 and pecl-mongodb: 
https://github.com/jenssegers/laravel-mongodb/pull/691

**Comment by MartinPham** [comment]
Because jenssegers use PHP's deprecated Mongo driver, (I think) It won't be supported in PHP 7+.
So I decided to make changes to this package to add support PHP's new MongoDB driver.
https://packagist.org/packages/martinpham/mongodb

**Comment by jenssegers** [comment]
See https://github.com/jenssegers/laravel-mongodb/issues/658, currently working on a compatible version. But quite a lot has changed and trying my best to make all current tests pass.

**Comment by jenssegers** [comment]
I currently pushed my "work in progress" changes to this branch: https://github.com/jenssegers/laravel-mongodb/tree/pecl-mongodb

Tests are still failing, would be great to have some pull requests so that we can release this faster!

**Comment by MartinPham** [comment]
Great!!! jenssegers

**Comment by ludovic-coder** [comment]
+1 @MartinPham Why not pull requests ?

**Comment by WillSkates** [comment]
Hi @jenssegers if you have done any more work on this could you please push as I'd like to get into working on this as well.

Should I extend the composer build matrix so that we can test against different versions of the laravel framework as well as differing versions of php (omitting cases where they aren't compatible)?

**Comment by WillSkates** [comment]
I've made a certain amount of headway on this today in that I have no errors just failures running on 5.6 with mongo 3.2.1 and mysql 5.7.10. https://github.com/WillSkates/laravel-mongodb is the link to my repo. I'll push a pr once I have stuff working on my end and i've stripped my test config out.

**Comment by WillSkates** [comment]
@jenssegers Please see PR [#704](https://github.com/jenssegers/laravel-mongodb/pull/704). All tests are passing.

**Comment by zakhttp** [comment]
i've created a bash script to automate the installation of mongoDB on Homestead with php7:
https://github.com/zakhttp/Mongostead7.git
