### ISSUE TITLE
`Jenssegers\Mongodb\Model` do not work with other databases

### ISSUE THREAD

**Issue by pgrzesiecki** [jenssegers/laravel-mongodb#673]
Hi,

Since version 2.1.8..2.1.9 was the change that prevents use of models inheriting `Jenssegers\Mongodb\Model` with other db drivers. For example it is impossible to use sqlite db during tests with this models. 

Exception:
`Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of  Jenssegers\Mongodb\Connection, instance of lluminate\Database\SQLiteConnection given, called in 
/[...]/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Model.php on line 519`

**Comment by zloadmin** [comment]
i has same problem.
try add connection in your mobel
protected $connection = 'mongodb';

<?php

namespace App;

class Post extends \Moloquent {

	protected $connection = 'mongodb';

    protected $collection = 'post_collection';

}
