### ISSUE TITLE
castAttribute don't work after save

### ISSUE THREAD

**Issue by mean-cj** [jenssegers/laravel-mongodb#674]
Hello

I want auto cast attribute before save to mongodb but i'm test cast with default laravel don't work.

My eloquent

```
use \Jenssegers\Mongodb\Model as Eloquent;
class Transaction extends Eloquent  {
    protected $casts = [
       'volume' => 'integer'
    ];
```

PHP Code

```
 $transaction = new \App\Transaction;
 $transaction -> volume = "2";
 $transaction -> save();
```

after save cast Attribute don't cast to int. volume storage is STRING
{
  "volume" : "2",
}

Thank.

**Comment by robsoncombr** [comment]
+1
