### ISSUE TITLE
Getting the query being generated?!

### ISSUE THREAD

**Issue by kamranahmedse** [jenssegers/laravel-mongodb#676]
It will be great to have any method similar to Eloquent's `->toSql()` etc to print the query that is being generated.

Note: If you are using [Laravel IDE Helper](https://github.com/barryvdh/laravel-ide-helper), it does show the query in the debugbar, but it will be great to have any native way of doing so.

**Comment by jenssegers** [comment]
Queries are being logged using db query log.
