### ISSUE TITLE
Unsupported driver [mongodb]

### ISSUE THREAD

**Issue by ashokcs94a** [jenssegers/laravel-mongodb#682]
Hi ,
  "  [InvalidArgumentException]    
  Unsupported driver [mongodb]  "

  i got error while i migrate in laravel 
why...?

**Comment by josephting** [comment]
Make sure you have added the service provider to your `config/app.php`.

`Jenssegers\Mongodb\MongodbServiceProvider::class,`

**Comment by vrkansagara** [comment]
@josephting it's works.
