### ISSUE TITLE
Call to undefined method MongoId::isValid

### ISSUE THREAD

**Issue by yelqandili1** [jenssegers/laravel-mongodb#683]
@jenssegers I had a FatalErrorException when I updated my project with "composer update" with the last commit.

The error is bellow : 

exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method MongoId::isValid()' in /project/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php:793

I've rolled back to an older release to get my app working again.

**Comment by wedgwood** [comment]
I meet the problem too

**Comment by alenn-m** [comment]
I have this problem too

**Comment by jenssegers** [comment]
Should be fixed in last version.
