### ISSUE TITLE
Exception:Object of class MongoId could not be converted to int

### ISSUE THREAD

**Issue by happyhero0** [jenssegers/laravel-mongodb#685]
When I write below code,

```
$users = User::all()->toJson(); // or:
$users = User::all()->toArray(); //
```

Then:

```
ErrorException in Model.php line 2875:
Object of class MongoId could not be converted to int
```

Is this a bug? I want to get user id in array / json, what should I do?
Thank you :smile:

**Comment by tabbi89** [comment]
You have to set in Your model `public $incrementing = false;`. This will avoid casting for primary key IMO `Jenssegers\Mongodb\Model` is missing this. This happens because `getCasts` method is invoked and primary key gets int cast.

```PHP
    /**
     * Get the casts array.
     *
     * @return array
     */
    protected function getCasts()
    {
        if ($this->incrementing) {
            return array_merge([
                $this->getKeyName() => 'int',
            ], $this->casts);
        }

        return $this->casts;
    }
```

**Comment by xfight0** [comment]
@tabbi89 Thank you very much :+1:
