### ISSUE TITLE
Create relationship between parent and children on the same object 

### ISSUE THREAD

**Issue by hoangmanh09it** [jenssegers/laravel-mongodb#689]
Hi everybody.
I have an collection save Post and Comment like that

"_id': ObjectId("567225874a7aafb016000029"),
"content":"content of  this post",
"comment": [
    {
      "_id":ObjectId("567225874a7aafb0160004529")
      "PARENT": NULL;
      "content": "this is parent comment",
    },
    {
      "_id":ObjectId("567225874a7aafb0160004529")
      "PARENT": "567225874a7aafb0160004529"; // this is ID of parent comment
      "content": "this is childrent comment",
    }
]

i already define relationship between post and comment. but i do'nt know how to define relationship between parent comment and children comment. Please help me

**Comment by ItomicInfrastructure** [comment]
Did you end up solving this?
