### ISSUE TITLE
Hi, I'm trying to embed many models before saving the parent model.

### ISSUE THREAD

**Issue by AyodejiO** [jenssegers/laravel-mongodb#695]
Hi, I'm trying to embed many models before saving the parent model. But i keep getting MassAssignmentException. what could I possibly do?.
i.e. I want to associate() many books under a user before $user->save() is called. 
Thanks for the help.

**Comment by mzmmlds** [comment]
hi AyodejiO , did you solved this issue? if yes then please let me know even i'm facing this exception.
