### ISSUE TITLE
Project timestamp to date

### ISSUE THREAD

**Issue by sp111** [jenssegers/laravel-mongodb#696]
Hello, 
I want to write following query in laravel. 

db.foo.aggregate({
   $project: {
       date: { $add: [new ISODate(0), "$time"] }
   }
})

Please tell me there is any way to do this. I have tried following code but got error. 

Foo::raw()->aggregate(['$project' => ['date' => [ '$add' => ['new ISODate(0)', '$time']]]]);

Error:
 exception: $add only supports numeric or date types, not String

Thanks

**Comment by spawn-guy** [comment]
change `'new ISODate(0)'`
to `new \MongoDate()`
