### ISSUE TITLE
Connection works via terminal mongo but not using Laravel-MongoDB

### ISSUE THREAD

**Issue by freak4pc** [jenssegers/laravel-mongodb#7]
Hey There,
Just installed Laravel-MongoDB on my Mongo setup, 
After setting up everything in the database.php file I'm gettting a 'Failed to connect to: localhost:27017: Authentication failed on database 'vbtest' with username 'root': auth fails' 

Even though I'm using exactly the same connection on the terminal which works.

Here's the Database.php config 

```
'connections' => array(
                'mongodb'       => array(
                        'host'          => 'localhost',
                        'port'          => 27017,
                        'database'      => 'vbtest',
                        'username'      => 'root',
                        'password'      => 'mypassword'
                )
        ),
```

And this is how It works in the terminal

```
mongo --username=root --password=mypassword
```

Any ideas?
Thanks! 
Shai.

**Comment by lawrencealan** [comment]
I fixed this by installing mongo 1.6.5 driver with `pecl upgrade mongo` (running MongoDB 3.0)
