### ISSUE TITLE
Batch Insert (pecl-mongodb) triggers $documents is not a list (unexpected index: "2")

### ISSUE THREAD

**Issue by litan1106** [jenssegers/laravel-mongodb#703]
Batch Insert triggers error if the array indexes are not in order.

InvalidArgumentException in InsertMany.php line 57:
$documents is not a list (unexpected index: "2")

```
        // Reset index values will fix the error
        $b = array_values($a);
```

**Comment by WillSkates** [comment]
Try using [this PR](https://github.com/jenssegers/laravel-mongodb/pull/704) and see if you get the same error.
