### ISSUE TITLE
Laravel 5.2 and default authentication system

### ISSUE THREAD

**Issue by ssenaria** [jenssegers/laravel-mongodb#705]
I'm getting the following error when I make a login attempt. My default drive it mongodb, the rest of the app works just fine.

    Argument 2 passed to Illuminate\Database\Query\Builder::__construct() must be an instance of    
    Illuminate\Database\Query\Grammars\Grammar, null given, called in   
    /var/www/html/ocd3/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1936 and defined

**Comment by mint-ws** [comment]
Did you resolve this? I have the same issue.

**Comment by ir0ny1** [comment]
? why is this closed

**Comment by aruncnt** [comment]
I have same issue
