### ISSUE TITLE
Compatible with Laravel 5.2?

### ISSUE THREAD

**Issue by ssenaria** [jenssegers/laravel-mongodb#706]
I see the record inserted into the collection. However, it fails with the following error. I'm not able to get pass the login screen.

Here's the error:

    App\Http\Models\User cannot use Illuminate\Foundation\Auth\User - it is not a trait

Here's my code.

    use Illuminate\Foundation\Auth\User as Authenticatable;
    use Jenssegers\Mongodb\Model as Eloquent;

    class User extends Eloquent
    {
        use Authenticatable;

**Comment by CImrie** [comment]
Hi ssenaria,

I'm not sure if I accidentally did a composer update or something, but I ended up with the same issue as you despite not making changes (to working code).

My User class is now working with the following:

```
<?php

namespace App\Models; // this might be just 'App' for you, as I prefer to put it in a folder called models
use Illuminate\Auth\Authenticatable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class User extends Eloquent implements \Illuminate\Contracts\Auth\Authenticatable
{
    use Authenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

}
```

**Comment by ganeshp0001** [comment]
Faced same issue with Laravel 5.2, after bit of debugging solve by changing User model.
Modified User model:
```javascript
namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class User extends Eloquent implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
   ........
```

**Comment by antsanchez** [comment]
On laravel 5.3, is just did that and worked perfectly.

on /vendor/laravel/framework/src/illuminate/Foundation/Auth/user.php 

added 
`use Moloquent\Eloquent\Model as Model;`

Like that:


```
namespace Illuminate\Foundation\Auth;

use Illuminate\Auth\Authenticatable;
use Moloquent\Eloquent\Model as Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
}

```

**Comment by arifulhb** [comment]
Any example for Laravel 5.4 ?

**Comment by vignesh007vicky** [comment]
same issue i have used like this

im using laravel 5.5.3  please help

<?php

namespace App;
use App\User;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

use DB;

class User extends Authenticatable 
{   
    
    use Eloquent ;
    use Notifiable;

        protected $connection = 'mongodb';
        protected $collection = 'users';
    protected $fillable = [
        'name', 'email', 'password',
    ];

    
    protected $hidden = [
        'password', 'remember_token',
    ];
}
