### ISSUE TITLE
Not guarding 

### ISSUE THREAD

**Issue by tallesdantas** [jenssegers/laravel-mongodb#707]
Hi , i've installed and everything is showing fine , but when i fill 

public $guarded = ['password']; 
it doesn't guard the value it shows everything.
the guarded value of the model is shown with the value but the return shows the field password. how can i guard attributes?

**Comment by hackel** [comment]
$guarded prevents mass-assignment, it has nothing to do with displaying values.  Try $hidden.

**Comment by tallesdantas** [comment]
i've tryed this too , same problem  https://gist.github.com/tallesdantas/f4721f0050ff65fddd12

**Comment by hackel** [comment]
What do you mean by "it shows everything?"  How are you "showing" the model?  $hidden will only remove the attributes from the output of toArray() and similar functions.  This is not a laravel-mongodb issue.

**Comment by tallesdantas** [comment]
sorry didnt know this, thx for the dumb question answer btw xD
