### ISSUE TITLE
query change - lat long 

### ISSUE THREAD

**Issue by ashokcs94a** [jenssegers/laravel-mongodb#708]
Can any one plz change  this below sql query to mongodb

 " SELECT provider.*, 1.609344 \* 3956 \* acos( cos( radians('$latitude') ) \* cos( radians(latitude) ) \* cos( radians(longitude) - radians('$longitude') ) + sin( radians('$latitude') ) \* sin( radians(latitude) ) ) as distance from provider where  is_approved = 1 and (1.609344 \* 3956 \* acos( cos( radians('$latitude') ) \* cos( radians(latitude) ) \* cos( radians(longitude) - radians('$longitude') ) + sin( radians('$latitude') ) \* sin( radians(latitude) ) ) ) <= $distance and provider.id IN($typestring) order by distance  "

**Comment by spawn-guy** [comment]
https://docs.mongodb.org/manual/reference/operator/query/near/#op._S_near

**Comment by ashokcs94a** [comment]
i m tried but its not working for me ..plz any help me out

**Comment by gnrcampos** [comment]
You can use geoNear for that. For what I understood (I'm new to the package) it's not currently supported but you can user a raw command to achieve this. In my case, here's what I had to do:
1 - Get the raw response from the database ($p_Lat = Latitude, $p_Long = Longitude, $p_Dist = Distance)
```
$v_Point = [
    'type' => 'Point',
    'coordinates' => [$p_Lon, $p_Lat]
];
$v_Results = DB::connection('mongodb')->getMongoDB()->command([
    'geoNear' => 'coordinates',
    'near' => $v_Point,
    'spherical' => true,
    'distanceField' => 'dist',
    'maxDistance' => $p_Dist,
    'limit' => 5
]);
```
2 - The result nests the object inside an 'obj' key, so I had to override the "newFromBuilder" method in the Model object and unwrap it.
```
public function newFromBuilder($attributes = [], $connection = null)
{
    if(isset($attributes['obj'])) {
        $attributes = array_merge($attributes, $attributes['obj']);
        unset($attributes['obj']);
    }
    return parent::newFromBuilder($attributes, $connection);
}
```
Please let me know if my approach wasn't the best one and I'm happy to discuss and learn more!
