### ISSUE TITLE
UTCDateTime expects parameter to be integer, float given

### ISSUE THREAD

**Issue by dostefan** [jenssegers/laravel-mongodb#712]
Hello I have an issue with the UTCDateTime.

When I try to save() an Model I get the Error:
MongoDB\Driver\Exception\InvalidArgumentException with message 'MongoDB\BSON\UTCDateTime::__construct() expects parameter 1 to be integer, float given'

I think the Problem is the round function, it returns a float value.
Model.php
    public function freshTimestamp()
    {
        return new UTCDateTime(round(microtime(true) \* 1000));
    }

I solved my issue with an cast to (int).

Best Regards

**Comment by macdabby** [comment]
👍  same issue here
