### ISSUE TITLE
Unset model values not marked as dirty => not removed on save

### ISSUE THREAD

**Issue by hackel** [jenssegers/laravel-mongodb#713]
If I unset some model values and then save the model, unless I have modified other fields on the model, the unset values don't get detected as dirty, and so the model does not actually save.

`Illuminate\Database\Eloquent\Model::getDirty` is only checking $this->attributes for changed values, when it also should do the reverse and check $this->original.  I think this change should be implemented in this package and not Laravel itself, since unsetting a value doesn't really apply to a structured DB.

**Comment by samthomson** [comment]
@hackel any workaround to this?

**Comment by hackel** [comment]
@samthomson I ended up implementing what I needed as a separate [trait](https://gist.github.com/hackel/9e2892f8609414741fee58cf7ecaaf44).  It's super hackish but gets the job done.  I had originally overridden `__unset` but took that out for some reason which I can't remember now.  I think it was causing trouble syncing embedded relations.  Unfortunately this unsets the fields in a separate DB transaction, but I think that's unavoidable due to the way library constructs queries.
