### ISSUE TITLE
Failed login fires an exception 

### ISSUE THREAD

**Issue by adriantombu** [jenssegers/laravel-mongodb#716]
Hi guys !
I'm on Laravel 5.2 and I wanted to test if everything goes fine when I test a login with a user not present in the database. But it went wrong, I get the following error

`FatalErrorException in Connection.php line 507: Call to a member function beginTransaction() on null`

`vendor/laravel/framework/src/Illuminate/Database/Connection.php line 507`

Any idea of what can cause this ?

**EDIT**
So after a few researches, the problem lies in the login throttle security which does not work
`Illuminate\Foundation\Auth\ThrottlesLogins`

I remove the `use Illuminate\Foundation\Auth\ThrottlesLogins;` from `AuthController` and it works properly now. But no throttle protection, for now !

**Comment by sachinvrg** [comment]
@adriantombu , did you find any solution ? I have same error when running command **php artisan queue:work**

**Comment by sachinvrg** [comment]
I am getting same error 
`PHP Fatal error:  Call to a member function beginTransaction() on null in /var/www/html/push-admin/setupl/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 577`
when fire **php artisan queue:work** command , I've tried your solution but still not working , can you please help me.Thanks much!!!

**Comment by adriantombu** [comment]
Hey @sachinvrg ! I'm sorry I haven't used the package on another project since then, I hope someone else will be able to help you !

**Comment by sachinvrg** [comment]
Thank you @adriantombu  , I've opened this issue also but unfortunately getting no response , do you any other package for laravel 5.2 and mongodb ? I'll switch to another , please help if you know.
