### ISSUE TITLE
php: symbol lookup error: /usr/lib/php/20151012/mongodb.so: undefined symbol: _mongoc_host_list_destroy_all

### ISSUE THREAD

**Issue by joearcher** [jenssegers/laravel-mongodb#717]
I appreciate that this looks like a problem with the mongodb client, but I get this when attempting to run `artisan migrate`.

Mongodb support shows as enabled in the output of `phpinfo()`

Using the latest homestead, the master branch of this repo and following the readme.

**Comment by Haafiz** [comment]
Are you using this MongoDB Driver:  http://php.net/manual/en/mongo.setup.php  which use pecl "mongo" package? If yes then this is depreciated. Use "MongoDB" extension.

**Comment by joearcher** [comment]
@Haafiz nope. This is using the php-mongobd driver and php7.
