### ISSUE TITLE
Laravel 5.2 Collection::whereIn() error (2.2.x & 3.0.x)

### ISSUE THREAD

**Issue by JeroenvdV** [jenssegers/laravel-mongodb#718]
After upgrading to Laravel 5.2 there is an error in Jenssegers\Mongodb\Eloquent\Collection:

ErrorException in Collection.php line 0:
Declaration of Jenssegers\Mongodb\Eloquent\Collection::whereIn() should be compatible with Illuminate\Support\Collection::whereIn($key, array $values, $strict = true)

It seems that since 5.2 the [Illuminate\Support\Collection](https://laravel.com/api/5.2/Illuminate/Support/Collection.html#method_whereIn) class also has a method named 'whereIn'. Uncommenting the method in Mongodb alleviates the problem temporarily. 

The problem did not go away when updating from 2.2.x to dev-master, which makes sense as the affected code is from [2014](https://github.com/jenssegers/laravel-mongodb/commit/12abfb3686668209d7a56ba6ac82b80d3d8b5879#diff-c36f9f1e87522d4c121162ca96cca8dcR132).

**Comment by jenssegers** [comment]
Should be fixed in 2.3.x.
