### ISSUE TITLE
Unique:database validation problem

### ISSUE THREAD

**Issue by rbruhn** [jenssegers/laravel-mongodb#721]
I ran across a situation where the "unique" validation isn't working correctly. It's trying to check the MySql connection instead of MongoDB. In a test command, I ran the following code:

```
$verifier = App::make('validation.presence');
$verifier->setConnection('mongodb');
$rules = ['id' => 'unique:transcriptions,id'];
$values = ['id' => '562d9e34f3cdc400ac00f077'];
$validator = Validator::make($values, $rules);
$validator->setPresenceVerifier($verifier);
dd($validator->fails());
```

To be clear, the id column is not the MongoDB _id. It's unique id generated for the transcription being imported.

I receive the following error. The database "biospex" is the name of the mysql db, not the mongodb.

```
[Illuminate\Database\QueryException]                                                                                                                                   
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'biospex.transcriptions' doesn't exist (SQL: select count(*) as aggregate from `transcriptions` where `id`  
   = 562d9e34f3cdc400ac00f077)
```

I also use felixkiss/uniquewith-validator in some areas of my code and it works correctly. If I use that with the above code, instead of "unique," everything works fine:

```
$verifier = App::make('validation.presence');
$verifier->setConnection('mongodb');
$rules = ['id' => 'unique_with:transcriptions,id'];
$values = ['id' => '562d9e34f3cdc400ac00f077'];
$validator = Validator::make($values, $rules);
$validator->setPresenceVerifier($verifier);
dd($validator->fails());
```

I'm using Laravel 5.2 and the latest release of Laravel-MongoDB. Any help in figuring this one out would be appreciated.

**Comment by drtzack** [comment]
Same here

**Comment by pirmax** [comment]
I have the same issue. Have you got news?
