### ISSUE TITLE
laravel 5.2.14 issue

### ISSUE THREAD

**Issue by freimanas** [jenssegers/laravel-mongodb#724]
Hi,

I am wondering if anyone else having issue with:

`Class 'Jenssegers\Mongodb\Eloquent\Model' not found`

Using: `"jenssegers/mongodb": "^2.3"`
I have registered a provider in config/app.php:

`Jenssegers\Mongodb\MongodbServiceProvider::class,`

my model looks like this:

```
namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class SomeCustomer extends Eloquent
{
    protected $collection = 'customers';

    protected $connection = 'mongodb';
}
```

So when I try to use it:
`$customers = SomeCustomer::first();`

I get the erorr:

`Class 'Jenssegers\Mongodb\Eloquent\Model' not found`

so I am wondering its just me doing something awkward, or there is some known issue?

thanks

**Comment by jenssegers** [comment]
What version are you using?

**Comment by freimanas** [comment]
"jenssegers/mongodb": "^2.3"

**Comment by jenssegers** [comment]
2.3 uses `Jenssegers\Mongodb\Model`. This is a change in the new 3.0.0 version.

**Comment by jenssegers** [comment]
In my last commit both classes should work for you. Will tag new version.

**Comment by freimanas** [comment]
That worked brilliantly!

thanks!
