### ISSUE TITLE
MongoClient class is deprecated

### ISSUE THREAD

**Issue by phongtnit** [jenssegers/laravel-mongodb#725]
Hello all,

I installed Laravel 5.2 and php_mongodb-1.1.2 driver for PHP Version 5.6.15 from http://php.net/manual/en/mongodb.installation.php. My phpinfo check: http://i.imgur.com/RHThTE4.png

I just updated lavarel-mongodb v2.3.1 for MongoDB 3.2.1.

I wrote simple model:
```
<?php
namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Test extends Eloquent {
	protected $connection  = 'mongodb';
        protected $collection = 'test';
}
```
I ran a controller and tested the model, then the error appears as the image http://i.imgur.com/SGVHzyD.png
```
Class 'MongoClient' not found
```

I checked new MongoDB driver document on http://php.net/set.mongodb. I saw that they don't support MongoClient class anymore (more detail on http://php.net/manual/en/book.mongo.php, the package was deprecated). They used MongoDB\Driver\Manager class instead (more detail on http://php.net/manual/en/set.mongodb.php).

Please check and fix it. What working version of php_mongodb package should I use with Laravel 5.2 and MongoDB 3.2? Many thanks for your support,

My environment:
```
- Laravel 5.2
- php_mongodb-1.1.2 driver for PHP Version 5.6.15 on https://pecl.php.net/package/mongodb
- lavarel-mongodb v2.3.1
- MongoDB server 3.2.1
```

**Comment by jenssegers** [comment]
Use the 3.0.0 alpha version

**Comment by orangeShadow** [comment]
Hm I have some problem Laravel 5.2, php7 (homestead last version), mongodb version => 1.1.2, error MongoDB\Driver\Manager
