### ISSUE TITLE
hasOne relationship not working in 3.0.0

### ISSUE THREAD

**Issue by CWood1** [jenssegers/laravel-mongodb#726]
When I try to do a hasOne relationship (with foreign key explicitly set, due to a schema error I now can't correct), I can't seem to actually access the object requested.

My code for the relationship itself is:

```
    public function state() {
        return $this->hasOne('App\ObjectStates', 'object_id');
    }
```

I have tried querying this relationship with all the following:

```
$object->state->toArray(); // This is how the Laravel docs say it should work
$object->state()->toArray();
$object->state->get()->toArray();
$object->state()->get()->toArray();
$object->state->all()->toArray();
$object->state()->all()->toArray();
```

I might have misinterpreted the Laravel docs themselves, however all of the above either return an empty array, or an exception of some description.

I checked using the MongoDB console that my relationship was working correctly, and for every Object, a corresponding state was set, with object_id set to the expected object.

Thanks

**Comment by jenssegers** [comment]
Can you check what queries are being executed?

**Comment by CWood1** [comment]
Sorry about the delay. Probably a stupid question, but how would I check this?

**Comment by CWood1** [comment]
Okay, yes it was a stupid question. This is what profiling gave me:

```
{
        "op" : "query",
        "ns" : "database.object_state",
        "query" : {
                "$query" : {
                        "$and" : [
                                {
                                        "object_id" : "568fe409d52bab43c80000c1"
                                },
                                {
                                        "object_id" : {
                                                "$ne" : null
                                        }
                                }
                        ]
                }
        },
        "ntoreturn" : 1,
        "ntoskip" : 0,
        "nscanned" : 0,
        "keyUpdates" : 0,
        "numYield" : 0,
        "lockStats" : {
                "timeLockedMicros" : {
                        "r" : NumberLong(156),
                        "w" : NumberLong(0)
                },
                "timeAcquiringMicros" : {
                        "r" : NumberLong(4),
                        "w" : NumberLong(3)
                }
        },
        "nreturned" : 0,
        "responseLength" : 20,
        "millis" : 0,
        "ts" : ISODate("2016-02-18T10:00:55.181Z"),
        "client" : "127.0.0.1",
        "allUsers" : [
                {
                        "user" : "username",
                        "userSource" : "database"
                }
        ],
        "user" : "username@database"
}
```

Shouldn't that object_id in the query be wrapped in ObjectId()? So, "object_id": ObjectId("568fe409d52bab43c80000c1"). Or have I just fragged my schema some?

**Comment by CWood1** [comment]
Update: Thanks to info on #744, I updated the code to use $object->state()->get()->toArray(). This doesn't error, however returns an empty array, in every case. Manually querying the database confirms that the state objects do exist (as mentioned above, using ObjectIDs on the relation).

**Comment by jasonlfunk** [comment]
Was this ever resolved? I am having the same problem.

**Comment by wuori** [comment]
I was having the same problem for 3.0 but adding a `->with('relation_name')` to the model query fixed it. I don't remember if this was required before but maybe that helps. Doesn't feel "right" but I had exhausted all other options short of going through each line of this extension. 

Additionally, `fill()` wouldn't update the relation, instead I would have to do it on the model its self: `$item->relation_name = (MongoID)`.
