### ISSUE TITLE
Redis serialisation problem with New MongoDB driver

### ISSUE THREAD

**Issue by boparaiamrit** [jenssegers/laravel-mongodb#728]
Exception in RedisStore.php line 69:
Serialization of 'MongoDB\BSON\ObjectID' is not allowed

**Comment by jensk** [comment]
Same issue for the apc driver. Probably all cache drivers are affected.

**Comment by jensk** [comment]
Related reports:

https://github.com/mongodb/mongo-php-library/issues/109
https://jira.mongodb.org/browse/PHPC-460

**Comment by boparaiamrit** [comment]
Thanks

**Comment by boparaiamrit** [comment]
May be this could help
http://mongodb.github.io/mongo-php-driver/ods/

**Comment by khoatran** [comment]
I am facing to the same issue and I posted my approach on this: [link](https://github.com/jenssegers/laravel-mongodb/issues/732)
