### ISSUE TITLE
Queue - No connector for [mongodb]

### ISSUE THREAD

**Issue by leakingminds** [jenssegers/laravel-mongodb#737]
Hey,

i keep getting this error:

InvalidArgumentException in QueueManager.php line 150:
No connector for [mongodb]

In my queue file i ve set up mongodb like this:

```php
'default' => env('QUEUE_DRIVER', 'mongodb'),


'connections' => [

...

 'mongodb' => [
            'driver' => 'mongodb',
            'table'  => 'jobs',
            'queue'  => 'default',
            'expire' => 60,
        ],

],
```

**Comment by leakingminds** [comment]
I fixed it.

As described in the Readme, one should cange the default "database" connector, and not add a new one!

**Comment by dungdoan** [comment]
Hi @leakingminds ,
I used the default connector is "database" but it always connect to mysql instead of mongodb. Can you support me?
Thank you
