### ISSUE TITLE
Queues don't work

### ISSUE THREAD

**Issue by sajadghawami** [jenssegers/laravel-mongodb#738]
hey,

i am getting the following error:

 `zero-length keys are not allowed, did you use $ with double quotes`

i am using the latest version, which should ve fixed this issue

**Comment by leakingminds** [comment]
Update:

I created a empty job, it does basically nothing... saving this to the database works without any problems... but as soon as i say: 

```queue:work```

it fires the above error... 
as i said, the job itself doesnt do anything really
