### ISSUE TITLE
Warning: Possible queue duplication with multiple processes

### ISSUE THREAD

**Issue by Bodom78** [jenssegers/laravel-mongodb#743]
@jenssegers I previously implemented queues for a project using an older version of this library and looking at the MongoQueue.php in the master branch I noticed that it may suffer from the same issue as I did.

Running the queue as a daemon with multiple processes will cause a race condition where more then 1 process can select the same job before another has marked it as reserved. This in turn will produce randomly duplicated jobs.

The fix is to to get the next job and mark it as reserved using Mongo's findAndReplace to lock the document.

I created a "getNextAvailableJobAndReserve" method and updated the "pop" method to use it.

For reference here is what my MongobdQueue class method looks like, Take note of the modified **pop** and how it uses the **getNextAvailableJobAndReserve** method.

Hope this can be of some help.

```
<?php

namespace App\Mongodb\Queue;

use Carbon\Carbon;
use Illuminate\Queue\DatabaseQueue;
use DB;

class MongodbQueue extends DatabaseQueue
{
    /**
     * Pop the next job off of the queue.
     *
     * @param  string $queue
     *
     * @return \Illuminate\Contracts\Queue\Job|null
     */
    public function pop($queue = null)
    {
        $queue = $this->getQueue($queue);

        if (!is_null($this->expire))
        {
            $this->releaseJobsThatHaveBeenReservedTooLong($queue);
        }

        if ($job = $this->getNextAvailableJobAndReserve($queue))
        {
            return new MongodbJob(
                $this->container, $this, $job, $queue
            );
        }
    }

    /**
     * Release the jobs that have been reserved for too long.
     *
     * @param  string $queue
     *
     * @return void
     */
    protected function releaseJobsThatHaveBeenReservedTooLong($queue)
    {
        $expired  = Carbon::now()->subSeconds($this->expire)->getTimestamp();
        $reserved = $this->database->collection($this->table)
                                   ->where('queue', $this->getQueue($queue))
                                   ->where('reserved', 1)
                                   ->where('reserved_at', '<=', $expired)->get();

        foreach ($reserved as $job)
        {
            $attempts = $job['attempts'] + 1;
            $this->releaseJob($job['_id'], $attempts);
        }
    }

    /**
     * Get the next available job for the queue and mark it as reserved.
     *
     * @param  string|null $queue
     *
     * @return \StdClass|null
     */
    protected function getNextAvailableJobAndReserve($queue)
    {
        $job = DB::getCollection($this->table)->findAndModify(
            [
                'queue'        => $this->getQueue($queue),
                'reserved'     => 0,
                'available_at' => ['$lte' => $this->getTime()],

            ],
            [
                '$set' => [
                    'reserved'    => 1,
                    'reserved_at' => $this->getTime(),
                ],
            ],
            null,
            [
                'new' => true,
            ]
        );

        return $job ? (object)$job : null;
    }

    /**
     * Release the given job ID from reservation.
     *
     * @param  string $id
     *
     * @return void
     */
    protected function releaseJob($id, $attempts)
    {
        $this->database->table($this->table)->where('_id', $id)->update([
            'reserved'    => 0,
            'reserved_at' => null,
            'attempts'    => $attempts,
        ]);
    }

    /**
     * Delete a reserved job from the queue.
     *
     * @param  string $queue
     * @param  string $id
     *
     * @return void
     */
    public function deleteReserved($queue, $id)
    {
        $this->database->table($this->table)->where('_id', $id)->delete();
    }
}
```

**Comment by leakingminds** [comment]
is this version 2* or 3* ?

**Comment by Bodom78** [comment]
The class I supplied above would be suitable for version 2.

I have not looked at this library in a while but it looks like it's changed a bit since I used it.

For version 3 you would need to write the "findAndModify" query using the updated syntax like seen in this comment https://github.com/jenssegers/laravel-mongodb/issues/734#issuecomment-182938779

**Comment by leakingminds** [comment]
could this be a possible solution for #738 ?

i cant find a solution... id be glad if someone could point me to the right direction ^^

**Comment by jenssegers** [comment]
@Bodom78 Would you mind doing a PR for v2 and possible v3?

**Comment by Bodom78** [comment]
@leakingminds Not too sure about the #738 error as I never came across it. Perhaps because I was using an older build of the library.

@jenssegers Sure, I'll do my best when time allows as I'm keep to look over the changes of the library since I used it last.

**Comment by giolvani** [comment]
I did a PR https://github.com/jenssegers/laravel-mongodb/pull/769 to solve this in master branch.

Now, it works fine to me. I hope help someone else.

=D

**Comment by Bodom78** [comment]
@giolvani Thanks for the PR, much appreciated.

**Comment by Bodom78** [comment]
#786
