### ISSUE TITLE
Query on embedsMany not working properly

### ISSUE THREAD

**Issue by behzadsh** [jenssegers/laravel-mongodb#744]
Let say I have model like this

```php
class Author extends Moloquent
{
    public function books()
    {
        return $this->embedsMany(Book::class);
    }
}
```

And i want to query books of an Author

```php
$author = Author::find($authorId);
$author->books()->where('pages', '>', 300)->get();
```

By running the code above I get this error
```
Missing argument 1 for Illuminate\\Support\\Collection::get()
```

if I pass column array to get method, I get:
```
array_key_exists(): The first argument should be either a string or an integer
```

**Comment by thialves** [comment]
I'm having the same problem.

:(

**Comment by jenssegers** [comment]
Embedded models are returned as an Eloquent Collection. You'll have to use the collection methods.

**Comment by thialves** [comment]
`$books = $author->books()->get()->where('pages', '>', 300);`

Worked for me!

:)

**Comment by behzadsh** [comment]
@jenssegers OK I got it, but I think you should update the code below in README:
```
$books = $user->books()->where('rating', '>', 5)->orderBy('title')->get();
```
As it has two errors:

1. the one I mentioned in OP `Missing argument 1 for Illuminate\\Support\\Collection::get()` - It'll call Illuminate version of Collection `where` method
2. few lines above that code it says `To allow a more query-like behavior, a modified version of the Collection class is used, with support for the following **additional** operations` and I checked every method you listed and none of them worked properly. *it always return all items in collection*

**Comment by jenssegers** [comment]
I removed the leftovers in the readme. Thanks for notifying me!
