### ISSUE TITLE
ext-mongo

### ISSUE THREAD

**Issue by fgyang** [jenssegers/laravel-mongodb#749]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - jenssegers/mongodb v3.0.0 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0].
    - Installation request for jenssegers/mongodb ^3.0 -> satisfiable by jenssegers/mongodb[v3.0.0].

  To enable extensions, verify that they are enabled in those .ini files:
    - D:\php-5.6.11-nts-Win32-VC11-x64\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by jenssegers** [comment]
Looks like you are missing ext-mongodb. Check the readme for the installation link.

**Comment by jasonsworld** [comment]
same problem
I can find ext-mongodb in my computer system(osx  /usr/lib/php/extensions/no-debug-non-zts-20121212),   and I and extension=mongo.so to php.ini  . I don't know what's the reason@jenssegers
