### ISSUE TITLE
PHP Memory limit exceeded - Builder.php  iterator_to_array

### ISSUE THREAD

**Issue by masettir** [jenssegers/laravel-mongodb#754]
Hello,
I'm using jenssegers/mongodb version 2
maybe I'm experiencing an issue on iterator_to_array at line 260 of Jenssegers\Mongodb\Query\Builder.

I'm trying to iterate on a lot of documents, about 138,000.

The process triggers the issue, memory exceeded, after it has processed 28,000 documents

This is a part of my code
```php
            $connection = DB::connection('mongodb');
            $theCollection = $connection->collection('grids');
            $coll = $theCollection
                ->where('division', strtolower($message['division']))
                ->where('release', $message['version_from']);
            $total = $coll->count();
            $cycle = 0;
            $coll->chunk('200', function ($chunks) use ($total, $cycle, $message) {
                foreach ($chunks as $chunk) {
                    unset($newDoc);
                    $newDoc = new MongoGrids();
                    $chunk['release'] = $message['version_name'];
                    unset($chunk['_id']);
                    foreach ($chunk as $key => $val) {
                       $newDoc->{$key} = $val;
                    }
                    $newDoc->save();
                    unset($newDoc);
                    $remain = $total - ($cycle + 1);
                }
            }); 
```

Thx ;)

Riccardo

**Comment by jenssegers** [comment]
Yeah Laravel makes is really hard to have iterators because of their Collection class.

**Comment by masettir** [comment]
Hello!!
I suspected that it was because of the Collection.

Thx ;)
R

**Comment by jenssegers** [comment]
I could create a custom collection class that somewhat supports iterators, but almost every operation on the collection requires the full data array.

**Comment by masettir** [comment]
Don't worry :)
For now I'm using your module for every common operation.
To solve my issue I've used MongoClient directly

```php
            $mC = new MongoClient('mongodb://user:pass@host:27017/db', array('replicaSet' => true, 'db' => 'admin'));
            $db = $mC->selectDB('db');
            $collection = $db->selectCollection('collection');
            $results = $collection->find(array('division' => strtolower($message['division']), 'release' => $message['version_from']));
            foreach ($results as $result) {
                unset($result['_id']);
                $result['release'] = $message['version_name'];
                $collection->insert($result);
            }
```
Maybe you can create a custom class that doesn't use iterator but for this specific behavior I can create an helper, easy way

Thx,
R

**Comment by jenssegers** [comment]
You should be able to get the mongo client from the DB class as well.

**Comment by masettir** [comment]
Haaaaa!! You are right!! Thank you :+1:

**Comment by salarmehr** [comment]
I had the same problem and come up with using the natvie mongo client. Is there any plan to return an interator when fetching column by query builder class?
