### ISSUE TITLE
Mongodb/Driver/Manager Class not found.

### ISSUE THREAD

**Issue by rohitgadia** [jenssegers/laravel-mongodb#761]
When i installed Jenssegers/mongo-db package via composer it installed a dependency 'mongodb/mongodb' and when I try to load the page I am getting this error "MongoDB/Driver/Manager Class Not Found". 
I am unable to get around with this error. Help please.

**Comment by rohitgadia** [comment]
Rectified the error, I forgot including the 'mongodb.ini' in "/etc/php5/mods-available/". Instead of including the 'mongodb.ini' my mods-available folder included 'mongo.ini' which is not supportive of "jenssegers/mongodb" dependency.

**Comment by ZaeemR** [comment]
@rohitgadia how to include 'mongo.ini' at the said location?

**Comment by StefanoFrazzetto** [comment]
@ZaeemR 

Don't know if you already solved, but I had to add these lines to my dockerfile:
```
# Install required libraries for mongodb
RUN apt-get install pkg-config libssl-dev -y && pecl install mongodb

RUN echo "extension=mongodb.so" > $PHP_INI_DIR/conf.d/mongodb.ini
```

**Comment by TechyTimo** [comment]
This worked for me:

    $ brew tap homebrew/php
    $ brew install php56-mongodb

Then add this line linking to the binary on your php.ini

extension='/usr/local/opt/**php56-mongodb**/mongodb.so'

You can change the php version to suit you.
