### ISSUE TITLE
Access level to Jenssegers\Mongodb\Schema\Blueprint::addColumn() must be public (as in class Illuminate\Database\Schema\Blueprint)

### ISSUE THREAD

**Issue by wayne5w** [jenssegers/laravel-mongodb#762]
Updated to v 2.3.3 today and am getting this error below. Any idea what is wrong?

[Symfony\Component\Debug\Exception\FatalErrorException]
  Access level to Jenssegers\Mongodb\Schema\Blueprint::addColumn() must be public (as in class Illuminate\Database\Schema\Blueprint)

**Comment by wayne5w** [comment]
Figured something out. Looks like there was a change to laravel 5.1.31. Went back to 5.1.30 and the problem disappears.

**Comment by jenssegers** [comment]
I released 2.3.4 with the fix.

**Comment by wayne5w** [comment]
thanks

**Comment by DMarine68** [comment]
Not sure if I'm missing something...  Using Laravel v5.1.34 with Jenssegers v2.2.10 and I get this error.  As far as I know, v2.3.x doesn't work with Laravel v5.1.x.  How can I overcome this error on Laravel v5.1.x?

**Comment by pentatonicfunk** [comment]
same error, "laravel/framework": "5.2.*" "jenssegers/mongodb" : "3.0.0",
