### ISSUE TITLE
Index changes not working

### ISSUE THREAD

**Issue by lobermann** [jenssegers/laravel-mongodb#771]
Hi,

running into a problem where I can not find a solution for.
I have two migrations, one where I create a collection and one newer one where I need to add an index to that collection.

When I add a `$collection->expire('created_at', 60);` to the first migration where the collection is created, it works without any issue. 
But when adding it to the new migration, with following code

```
Schema::collection('test_collection', function(Blueprint $collection)
{
    $collection->expire('created_at', 60);
});
```

it does not add the index to the collection.
What am I doing wrong? What is the correct way of adding indexes at a later stage?
Using v2.2.3 and MongoDB 3.2.

Update:
Just updated to v3.0.2 and still the same issue.

**Comment by Vagabondtq** [comment]
As I know Laravel create index is:
`$collection>index('index_cloumn');`

**Comment by lobermann** [comment]
I know, but in my case I need to create a ttl index, not a normal one.
