### ISSUE TITLE
composer does not install mongodb ubuntu

### ISSUE THREAD

**Issue by Vagabondtq** [jenssegers/laravel-mongodb#776]
```

I ran: _composer require mongodb/mongodb _
But it gave me the following error :

```
    mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    Installation request for mongodb/mongodb ^1.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1].

```
I tried : **composer show -p**

Then it gave me:
```
......
ext-iconv 0 The iconv PHP extension
ext-mcrypt 0 The mcrypt PHP extension
ext-mhash 0 The mhash PHP extension
ext-mongo 1.6.12 The mongo PHP extension
ext-mysql 1.0 The mysql PHP extension
ext-mysqli 0.1 The mysqli PHP extension
......
```

Why am I getting the error?

**php -m**

.....
libxml
mbstring
mcrypt
mhash
mongo
mysql
mysqli
openssl
pcntl
pcre
PDO
.....

```
I'm using ubuntu 14.04 LTS

**Comment by Vagabondtq** [comment]
i'm run:

    sudo apt-get install libpcre3-dev

then:

    pecl install mongodb

and add: `extension=mongodb.so` to bottom line of `cli/php.ini`

**Comment by philicious** [comment]
I openend a request at Ubuntu Launchpad to get the new php-mongodb driver also for trusty-universe (Ubuntu14). Its available in xenial but built against PHP7 API. https://bugs.launchpad.net/ubuntu/+source/php-mongodb/+bug/1579815
