### ISSUE TITLE
Wrong DateTime in created_at and updated_at fields in Laravel 5.2

### ISSUE THREAD

**Issue by phongtnit** [jenssegers/laravel-mongodb#783]
Hello all,

I'm using Laravel 5.2. I installed an authentication with `php artisan make:auth` command. I created new user successfully. However, when I checked users' collection in MongoDB database, I saw wrong datetime in `created_at` and `updated_at` fields, please refer the following image ![](http://i.imgur.com/ymT3qpQ.png)

How should I do to fix that?

Many thanks for your help,

My env:
- MongoDB: 3.2.1
- Laravel 5.2
- jenssegers/mongodb 3.0.2

**Comment by SerjioH** [comment]
Almost the same issue. I'd like to know how to store dates to mongodb. When it comes to create default "created_at" and "updated_at" mongodb sets 1970 year.

**Comment by phongtnit** [comment]
Hi @jenssegers , I guess this is a bug.

All ``created_at`` and ``updated_at`` fields automatically generated wrong date-time. More issue images ![](http://i.imgur.com/1txQnJb.png)

**Comment by zloadmin** [comment]
Me too :(
```
object(Carbon\Carbon)#231 (3) {
  ["date"]=>
  string(26) "1970-01-01 00:00:00.000000"
  ["timezone_type"]=>
  int(3)
  ["timezone"]=>
  string(3) "UTC"
}
```

**Comment by sarpdoruk** [comment]
@jenssegers I'm having the same problem.

Laravel 5.3
"jenssegers/mongodb": "^3.0"
MongoDB version: 3.4

**Comment by munotsagar** [comment]
Facing same issue, I am using Laravel  5.2 with mongodb 3.2,

I have observed that it was working fine initially but now showing wrong date in db.

Please let me know if any buddy have solution for this.

**Comment by Lemondragon** [comment]
It seems to work when I override the freshTimestamp() method on the model.
```
    /**
     * @inheritdoc
     */
    public function freshTimestamp()
    {
        return new UTCDateTime(Carbon::now()->timestamp);
    }

```

Seems like there was a *1000 on the timestamp originally, which seems to result in a wrong date (Somewhere in 1920 in my case).

**Comment by spartangian** [comment]
Thanks @Lemondragon , but in my case, I did the same with you but the difference is I didn't use Carbon. Mine is mongo 3.2.4 on Laravel 5.4

`
/**
     * @inheritdoc
     */
    public function freshTimestamp()
    {
        return new UTCDateTime();
    }
`

**Comment by abdulhanananwari** [comment]
in youre model 
protected $guarded =['created_at','updated_at];

**Comment by KeNJiKunG** [comment]
I think its may cause by integer overflow bug. 
When save the data using `new \MongoDB\BSON\UTCDateTime( round(microtime(true) * 1000));`, it save value correctly.

 I am running on 32bit version of PHP.
