### ISSUE TITLE
[Eloquent] Many to many relation with multi column

### ISSUE THREAD

**Issue by Vagabondtq** [jenssegers/laravel-mongodb#787]
I have table relation in MySQL
_table: apps_

```
ID
Name
```

_table: clients_

```
ID
Name
```

And table relationship: _app_client_

```
app_id
client_id
version
```

field '_version_' in table _app_client_ is string type

**How to create relational tables in MongoDB as containing the _version_ column?**

I create table in Mongodb:
_table: apps_

```
ID
Name
client_ids => is array: [ObjectID('client_id'), ObjectID('client_id')]
```

_table: clients_

```
ID
Name
app_ids => is array: [ObjectID('app_id'), ObjectID('app_id')]
```

My Eloquent (Model Client):

```
    public function apps(){
        return $this->belongsToMany('Model\App', null, 'client_ids', 'app_ids');
    }
```

But, not column _version_
Do you know what I mean? How to create column _version_ in database mongodb for Eloquent?

**Comment by Vagabondtq** [comment]
In MySQL + Eloquent, I use `$this->belongsToMany()->withPivot();`
In MongoDB not used

**Comment by joelcuevas** [comment]
@Vagabondtq, did you manage to do this with MongoDB?

**Comment by infernobass7** [comment]
I am looking into this now and it actually looks like the relationship model for many to many relationship will allow you to pass the attributes field in but it does absolutely nothing with the array.

**Comment by SlyRock** [comment]
+1

**Comment by dhoffmannbgp** [comment]
+1

**Comment by Saneesh** [comment]
+1

**Comment by Saneesh** [comment]
@jenssegers Could you please explain how can we achieve it or share the documentation link which helps to solve this?

**Comment by keanass** [comment]
+1
