### ISSUE TITLE
Artisan queue [failed] [retry] do not work as expected

### ISSUE THREAD

**Issue by Bodom78** [jenssegers/laravel-mongodb#789]
**artisan queue:failed** 
Does not work because the failed_at column is not stored as a timestamp.
Exception thrown: strstr() expects parameter 1 to be string, array given 

**artisan queue:retry id** 
Does re queue the job but does not delete the record in the failed_jobs collection.
Exception thrown: Undefined property: stdClass::$id

**artisan queue:retry all** 
Does not find any failed jobs even when there are some present.
Error: No failed job matches the given ID [].

**Comment by infernobass7** [comment]
Ran into this same issue. Would be very nice to see this added. +1

**Comment by domagala** [comment]
Same here, is there a planned fix?

**Comment by codeitlikemiley** [comment]
still no fixed for this?

**Comment by Bodom78** [comment]
@codeitlikemiley Fix was merged here https://github.com/jenssegers/laravel-mongodb/pull/792

If your having a similar issues it might be best to create a new ticket explaining the problem since it might be a new problem due to changes in the library since the old fix which was a couple of years ago now.
