### ISSUE TITLE
Eloquent create method does not return _id

### ISSUE THREAD

**Issue by robsoncombr** [jenssegers/laravel-mongodb#791]
Hello.

I'm using $dbModel = $model::create(array[]);

It creates the record perfectly, however, I get no _id field on $dbModel

$dbModel->_id returns NULL, but has all other fields filled.

Does anyone know what could be?

Using Laravel 5.2

Thank you.

**Comment by bhargav3** [comment]
+1

**Comment by EvanRR** [comment]
That happen to me, anyone knows the solution? and the version?

**Comment by DFurnes** [comment]
I was seeing this problem on Laravel 5.2 after upgrading to laravel-mongodb 3.0.2 as well. I had the `$incrementing` field set to `false` on the model I was saving, and removing that field (so it returned to the default `true` value) seemed to fix the issue.

**Comment by bhargav3** [comment]
@DFurnes Thanks for resolving this issue. As far as I see it is just enough to add this to the documentation and open a PR.
