### ISSUE TITLE
Eloquent type - integer gets converted to mongodb - string.

### ISSUE THREAD

**Issue by abhishekgdev** [jenssegers/laravel-mongodb#793]
Hello all,

We are trying to migrate a database collection which has columns of type integer and hence we have used $table->integer('column_name'). Post migration when we check in the mongo db, the data type for that column is shown as string. 

What can be the reason for this?

Thanks in advance...

**Comment by amiri27** [comment]
See this https://github.com/jenssegers/laravel-mongodb/pull/834
