### ISSUE TITLE
Composer can't find mongodb extension

### ISSUE THREAD

**Issue by supaheckafresh** [jenssegers/laravel-mongodb#797]
Hi - I'm running into essentially the same error as in issue #780 when executing `composer require jenssegers/mongodb`: 

```
$ composer require jenssegers/mongodb
Using version ^3.0 for jenssegers/mongodb
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb v3.0.0 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1].
    - jenssegers/mongodb v3.0.1 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1].
    - jenssegers/mongodb v3.0.2 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1].
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for jenssegers/mongodb ^3.0 -> satisfiable by jenssegers/mongodb[v3.0.0, v3.0.1, v3.0.2].

  To enable extensions, verify that they are enabled in those .ini files:
    - C:\Program Files\PHP\v7.0\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
```

I'm running Windows 10 and PHP 7. I installed the mongodb extension (php_mongodb.dll in PHP ext/ folder), and I've updated php.ini with `extension=php_mongodb.dll`. Not sure what I've missed. If anyone can help me with this, I'd greatly appreciate it. Thanks.

**Comment by Denys-Bushulyak** [comment]
Have the same problem. At searching.

**Comment by Denys-Bushulyak** [comment]
`composer require jenssegers/mongodb --ignore-platform-reqs`

**Comment by Denys-Bushulyak** [comment]
Or another thing - pecl instaling mongodb.so (if we talikng about *nix OSes) but putting to mongo.ini:
`extension=mongo.so`
and have to
`extension=mongodb.so`
If you fix this string at:
`/etc/php5/mods-available/mongo.ini`
all have to be ok.
Please, ping me if it fix.

**Comment by Siphion01** [comment]
I've been banging my head all day and night today over this issue, thank you for the fix @Denys-Bushulyak!

**Comment by supaheckafresh** [comment]
@Denys-Bushulyak. Thank you, I did try your solution in a test project & it appears to work on Windows! As far as what I was working on before, I ended up installing the mongodb-php driver and jenssegers/mongodb inside of my vagrant machine & this worked great for my earlier project. Getting things set up inside of the vagrant box should have been more obvious to me before, but I'm quite new to Laravel.

**Comment by Denys-Bushulyak** [comment]
Thank you all. It's pleasure to me to be helpful.

**Comment by alex-moreno** [comment]
@Denys-Bushulyak thanks, I was going through the xhgui install and having issues with mongo deps. That save my day.

**Comment by Criscros** [comment]
@Denys-Bushulyak  I'm running into MAMP but composer update  no work and show the same error ....  any help me please

**Comment by Denys-Bushulyak** [comment]
@Criscros, try to look:
1. `php -m` to see than extenstsion is installed
2. `php -i | grep mongo` will show you where mongodb ini file located
3. change `extension=mongo.so` if exists to `extension=mongodb.so`

**Comment by Criscros** [comment]
i can see where is ini file @Denys-Bushulyak 
![captura de pantalla 2016-09-21 a las 9 19 25 a m](https://cloud.githubusercontent.com/assets/5004586/18714897/d331507a-7fdc-11e6-8e6b-8f1237b0ef00.png)

**Comment by Denys-Bushulyak** [comment]
Sorry, I said wrong way. it 's your host spec. We need MAMP.

**Comment by Criscros** [comment]
thx

**Comment by thegregthomp** [comment]
I just needed to install the php driver for mongo

`brew install php56-mongodb`

**Comment by stea4lth** [comment]
`sudo pecl install mongodb`
`sudo nano /etc/php5/mods-available/mongodb.ini`  insert in file `extension=mongodb.so`
`sudo ln -sv /etc/php5/mods-available/mongodb.ini  /etc/php5/apache2/conf.d/20-mongodb.ini`
`sudo ln -sv /etc/php5/mods-available/mongodb.ini  /etc/php5/cli/conf.d/20-mongodb.ini`
`sudo service apache2 restart`
`composer require jenssegers/mongodb`

**Comment by Plutus038** [comment]
Hi,
     ln: failed to create symbolic link ‘/etc/php5/cli/conf.d/20-mongodb.ini’: File exists
     I can't able to create symbolic link

**Comment by Quasimodo84** [comment]
I already install the adapter and it connects well using homebrew on my OSX El Capitan..  
when i called using mongod and mongo on the terminal it works

But when i install it using composer require jenssegers/mongodb, it throws the error like the first post on this thread..

So i use  Denys-Bushulyak method and it works on the installation..my question is..is anyone working around with the complete instalation?if one doesn't use the package requirements..is it working too?

**Comment by Quasimodo84** [comment]
Ok after searching me and my coleague manage to figure some of the process and successfully install it on the el-capitan..  At first we need to compile manually and install dependencies(such as autoconf) even the openssl as well(relink and all) .. it works well now.

These link also helps greately for anyone having trouble on updating and symlink openssl
http://apple.stackexchange.com/questions/244058/homebrew-trouble-upgrading-openssl

**Comment by ZaeemR** [comment]
@Denys-Bushulyak  can you please help me resolve my issue. [here is the detail.](http://stackoverflow.com/questions/43760571/class-mongodb-driver-manager-not-found-mongo-and-laravel?noredirect=1#comment74569862_43760571)

**Comment by lanka-senanayaka** [comment]
When installing mongo db using (I'm using nginx)
sudo pecl install mongodb
sometimes it gives phpize error so you need to run
**apt-get install php7.0-dev** (or php7.1-dev)
after that it will install mongodb successfully

don't forget to run
**sudo service nginx restart**

**sudo /etc/init.d/php7.0-fpm restart**

**Comment by miljanbrakocevic** [comment]
@Denys-Bushulyak  Thank you :)

**Comment by chathurangat** [comment]
@Denys-Bushulyak  Thank you very much! it worked fine!

**Comment by TechyTimo** [comment]
Try installing the mongodb extension using homebrew

$ brew tap homebrew/php
$ brew install php56-mongodb
 
Then link it to your php.ini

extension='/usr/local/opt/php56-mongodb/mongodb.so'

Suit it to your preferred php version.

**Comment by sayan0020** [comment]
I'm using php 5.6, so it helped me 

sudo apt-get install -y php-pear php5.6-dev
sudo pecl install mongo

sudo sh -c "echo 'extension=mongo.so' > /etc/php/5.6/mods-available/mongo.ini"
sudo ln -s /etc/php/5.6/mods-available/mongo.ini /etc/php/5.6/apache2/conf.d/mongo.ini

sudo service apache2 restart

**Comment by pirmax** [comment]
Try 

> composer require jenssegers/laravel-mongodb --ignore-platform-reqs

**Comment by sayan0020** [comment]
i've, but it didn't solve my problem

**Comment by jagadeshanh** [comment]
I executed following commands in order

`sudo apt-get install php-mongodb`

`composer require mongodb/mongodb`

`composer require jenssegers/mongodb`

**Comment by lexoyo** [comment]
what I did in fedora was `sudo dnf install php-mongodb`

**Comment by mjniuz** [comment]
Make sure mongodb version/type is correct
I use this

```
sudo yum install -y openssl-devel
sudo yum install pecl
sudo yum install gcc
sudo pecl install mongodb
```

**Comment by pcarrascom** [comment]
Hi, every idea will be tested here...
I tried with "composer require jenssegers/mongodb --ignore-platform-reqs" and get this:

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Uncaught Error: Call to a member function connection() on null in C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1239
Stack trace:
#0 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1205): Illuminate\Database\Eloquent\Model::resolveConnection('mysql')
#1 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1035): Illuminate\Database\Eloquent\Model->getConnection()
#2 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(952): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#3 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(630): Illuminate\Database\Eloquent\Model->newModelQuery()
#4 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel-admin-ext\reporter\src\Reporter.php(117): Illuminate\Database\Eloqu in C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 1239
PHP Fatal error:  Uncaught Error: Call to a member function connection() on null in C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php:1239
Stack trace:
#0 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1205): Illuminate\Database\Eloquent\Model::resolveConnection('mysql')
#1 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1035): Illuminate\Database\Eloquent\Model->getConnection()
#2 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(952): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#3 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(630): Illuminate\Database\Eloquent\Model->newModelQuery()
#4 C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel-admin-ext\reporter\src\Reporter.php(117): Illuminate\Database\Eloqu in C:\Users\Proyectae01\Documents\GitHub\app\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 1239
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

**Comment by hamiozturk** [comment]
this is worked for me
https://github.com/jenssegers/laravel-mongodb/issues/797#issuecomment-218980690

**Comment by AymanElshehawy** [comment]
try this
`composer install --ignore-platform-reqs`

**Comment by bhavinjr** [comment]
This is worked for me
```
sudo pecl install mongodb
```
After installation, you may be seen this
```
Extension mongodb enabled in php.ini
```
then you need to
`composer install`

**Comment by jeanlyj** [comment]
Cool! @Denys-Bushulyak 
I have to spend a lot of time to search for a solution, but your's is the final. 
Thanks a lot!

**Comment by Ahmed-Aboud** [comment]
for windows https://pecl.php.net/package/mongodb download the DLL and place it in xampp/php/ext folder and open php.ini and add extension=php_mongodb.dll

**Comment by Loetfi** [comment]
> @Criscros, try to look:
> 
>     1. `php -m` to see than extenstsion is installed
> 
>     2. `php -i | grep mongo` will show you where mongodb ini file located
> 
>     3. change `extension=mongo.so` if exists to `extension=mongodb.so`

thanks !

**Comment by Loetfi** [comment]
> `composer require jenssegers/mongodb --ignore-platform-reqs`
> It solved my problem.

composer update --ignore-platform-reqs

**Comment by briatek** [comment]
> `composer require jenssegers/mongodb --ignore-platform-reqs`
> It solved my problem.

Thank so much it work for me

**Comment by medaharrat** [comment]
> `composer require jenssegers/mongodb --ignore-platform-reqs`
> It solved my problem.

This doesn't work on Laravel 7

**Comment by jokova91** [comment]
@medaharrat Maybe check out the compatibility of laravel & jenssegers versions https://github.com/jenssegers/laravel-mongodb#laravel-version-compatibility

**Comment by Smolevich** [comment]
> > `composer require jenssegers/mongodb --ignore-platform-reqs`
> > It solved my problem.
> 
> This doesn't work on Laravel 7

Use alpha release v4
