### ISSUE TITLE
GroupBy subdocument

### ISSUE THREAD

**Issue by oceanapplications** [jenssegers/laravel-mongodb#804]
If I try something like 
`$t = Sessions::groupBy('subdoc.id')->get();`
I get 
RuntimeException in Aggregate.php line 168:
exception: the group aggregate field name 'affiliate.affId' cannot be used because $group's field names cannot contain '.'

I saw this was fixed for the sum functions but apparently not for groupBy.

Thanks

**Comment by djit** [comment]
+1, really need this to work.
