### ISSUE TITLE
Using a like query as part of $elemMatch

### ISSUE THREAD

**Issue by DNGRLiam** [jenssegers/laravel-mongodb#805]
I am currently trying to replicate the following mongo query as part of my laravel code;

`db.getCollection('ShowsDEMO').find({performances: {$elemMatch: { start: /.*2014-08-19.*/}}})`

To do this I attempting to use this line, 

`$query = $query->where('performances', 'elemMatch', array('start', 'like', '%2014-08-19%'));`

Unfortunately at the moment that is only returning a bad query error, saying that $elemMatch needs an Object. Am I trying to build this like query incorrectly or is this functionality not something that is currently possible?

**Comment by hamutaro89** [comment]
May be you can try
`$query = $query->where('performances.start', 'like', '%2014-08-19%');`
