### ISSUE TITLE
Laravel 5 - JWT Issues

### ISSUE THREAD

**Issue by sajeeshe** [jenssegers/laravel-mongodb#810]
Hi,
I am using JWT for the authentication , I have changed  'identifier' => '_id', but the middleware $this->middleware('jwt.auth'); is firing some error .  

FatalErrorException in Builder.php line 1439:
Call to a member function compileSelect() on a non-object

If I remove the middleware it works fine.

**Comment by wuori** [comment]
Which version of Laravel and laravel-mongodb are you using?
