### ISSUE TITLE
Paginate doesn't work when only one entry in Mongo

### ISSUE THREAD

**Issue by rockmetoo** [jenssegers/laravel-mongodb#814]
I have only one object in mongo like as follows:

{
    "_id" : ObjectId("570e00998ead0ecb1f8b4569"),
    "from" : 1,
    "to" : 1,
    "subject" : "test",
    "body" : "test body",
    "is_seen" : true,
    "is_no_reply" : false,
    "deleted_at" : false,
}

However, paginate return empty and I cannot see the data in view. I am using laravel 4.2, mongodb 2.6.9 and laravel-mongodb 2.x. My query is like as follows:
`
$query = DB::connection('mongodb')->collection('testcollection');
`
`
$res = $query->where('to', 1)->where('deleted_at', false)->paginate(50);
`

Please advice me.

N.B. I have a pagination wrapper.

**Comment by gudboisgn** [comment]
I have same issue
