### ISSUE TITLE
orderByRaw no support for mongodb

### ISSUE THREAD

**Issue by tomartailored** [jenssegers/laravel-mongodb#820]
http://stackoverflow.com/questions/36594239/orderbyraw-not-working-with-jenssegers-mongodb-laravel-5

Can you please give me a suggestion or any other method for sorting the raw by column values in a queue.
example :
Table 

```
id    products    category
1          a                xy
2          b                ab
3          c                bc
4          d                cc
5          e                xy
6          f                 xy
```

I want out put as an 
order by : category (cc,ab,bc,xy)

```
id    products    category
4          d                cc
2          b                ab
3          c                bc
1          a                xy
5          e                xy
6          f                 xy
```

**Comment by eane** [comment]
I have the same problem.

**Comment by a-zog** [comment]
@jenssegers I see that you closed this issue. Would you tell me more about the support of orderByRaw() please?

I need this function so I can order by "order" and keep null values in the end. Like it's mentioned here: https://laracasts.com/discuss/channels/laravel/how-to-write-eloquent-orderby-to-put-null-columns-to-the-last

Of course, I'm still open if there is an alternative.

Thank you in advance

**Comment by Smolevich** [comment]
@a-zog it can be implemented, we are open for discussion, but better to discuss in slack channel or create new issue

**Comment by The-Architect22** [comment]
how i can find orderbyRaw ? it's not implemented in src
