### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by trololosha4real** [jenssegers/laravel-mongodb#822]
Mongo driver is compiled from the source and seen in both CLI and Apache versions. But when trying to install getting error...

```
~/www/ArtCrawler/PHP $ composer require jenssegers/mongodb
Using version ^3.0 for jenssegers/mongodb
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb v3.0.0 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1, 1.0.2].
    - jenssegers/mongodb v3.0.1 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1, 1.0.2].
    - jenssegers/mongodb v3.0.2 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.0.0, 1.0.1, 1.0.2].
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for jenssegers/mongodb ^3.0 -> satisfiable by jenssegers/mongodb[v3.0.0, v3.0.1, v3.0.2].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php5/cli/php.ini
    - /etc/php5/cli/conf.d/05-opcache.ini
    - /etc/php5/cli/conf.d/10-mysqlnd.ini
    - /etc/php5/cli/conf.d/10-pdo.ini
    - /etc/php5/cli/conf.d/20-curl.ini
    - /etc/php5/cli/conf.d/20-gd.ini
    - /etc/php5/cli/conf.d/20-json.ini
    - /etc/php5/cli/conf.d/20-mcrypt.ini
    - /etc/php5/cli/conf.d/20-mongo.ini
    - /etc/php5/cli/conf.d/20-mysql.ini
    - /etc/php5/cli/conf.d/20-mysqli.ini
    - /etc/php5/cli/conf.d/20-pdo_mysql.ini
    - /etc/php5/cli/conf.d/20-pdo_pgsql.ini
    - /etc/php5/cli/conf.d/20-pgsql.ini
    - /etc/php5/cli/conf.d/20-readline.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
~/www/ArtCrawler/PHP $ php --ini
Configuration File (php.ini) Path: /etc/php5/cli
Loaded Configuration File:         /etc/php5/cli/php.ini
Scan for additional .ini files in: /etc/php5/cli/conf.d
Additional .ini files parsed:      /etc/php5/cli/conf.d/05-opcache.ini,
/etc/php5/cli/conf.d/10-mysqlnd.ini,
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-curl.ini,
/etc/php5/cli/conf.d/20-gd.ini,
/etc/php5/cli/conf.d/20-json.ini,
/etc/php5/cli/conf.d/20-mcrypt.ini,
/etc/php5/cli/conf.d/20-mongo.ini,
/etc/php5/cli/conf.d/20-mysql.ini,
/etc/php5/cli/conf.d/20-mysqli.ini,
/etc/php5/cli/conf.d/20-pdo_mysql.ini,
/etc/php5/cli/conf.d/20-pdo_pgsql.ini,
/etc/php5/cli/conf.d/20-pgsql.ini,
/etc/php5/cli/conf.d/20-readline.ini

~/www/ArtCrawler/PHP $ php --ri mongo | grep Version
Version => 1.4.5
```

![selection_163](https://cloud.githubusercontent.com/assets/7287184/14710262/58a5a454-07dd-11e6-98d3-939d24969b7f.png)

**Comment by infernobass7** [comment]
@trololosha4real I believe your issue is that you are using the old Mongo database connector. In the newest version on this package, this connector has been deprecated. Try downloading and installing the connector listed below and then retry installing the package.

http://pecl.php.net/package/mongodb

**Comment by munotsagar** [comment]
Added php_mongo.dll in php/ext folder, but still facing same issue,

Could you please explain in detail steps ?

**Comment by munotsagar** [comment]
![mongodb](https://cloud.githubusercontent.com/assets/12947915/16415886/2554a1ee-3d5d-11e6-820a-e989e6ffe05d.JPG)

**Comment by munotsagar** [comment]
Facing this issue could you please tell me what would be the solution.

**Comment by infernobass7** [comment]
Did you add mongodb.dll/mongodb.so to the dynamic extension section ofor your php.ini files?

**Comment by munotsagar** [comment]
Yes added "extension=php_mongo.dll" in php.ini file.

**Comment by munotsagar** [comment]
![capture](https://cloud.githubusercontent.com/assets/12947915/16425259/5bb4cf06-3d81-11e6-87d2-195ccac75fe7.JPG)

**Comment by infernobass7** [comment]
It looks like you might be using the deprecated version of the driver. You want to use mongodb. Found here http://pecl.php.net/package/mongodb. If you do not want to use this new driver, then you will have to go to a previous version of this package.

**Comment by IgorDePaula** [comment]
I have the same problem and all required extensions enabled.

**Comment by IgorDePaula** [comment]
I read this issue #797  and resolved the problem.

**Comment by mmuflih** [comment]
I have the same problem
![image](https://cloud.githubusercontent.com/assets/8967131/17422722/a8a4861a-5ade-11e6-8f56-a29d315e0563.png)

I use mongodb v 2.4.9 and this is my phpinfo
![image](https://cloud.githubusercontent.com/assets/8967131/17422749/fe0fe022-5ade-11e6-9528-5360cb1fc593.png)

**Comment by acidjazz** [comment]
to fix this issue on AWS I did:

```bash
echo "extension=mongodb.so" > /etc/php.d/20-mongo.ini
```

**Comment by BillKeenan** [comment]
pretty sure you want double >
echo "extension=mongodb.so" >> /etc/php.d/20-mongo.ini

**Comment by acidjazz** [comment]
@BillKeenan either/or works, `>` will overwrite what was ever in there and `>>` will append, there shouldn't be anything else in there.

**Comment by jorgeomarmh** [comment]
my solution was 
sudo apt-get install php-mongodb

**Comment by xinnah** [comment]
# now I have the same problem..

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb v3.2.0 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - jenssegers/mongodb v3.2.1 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - jenssegers/mongodb v3.2.2 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - mongodb/mongodb 1.0.5 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.4 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for jenssegers/mongodb ^3.2 -> satisfiable by jenssegers/mongodb[v3.2.0, v3.2.1, v3.2.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - D:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

D:\xampp\htdocs\laravel-mongodb>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb v3.2.0 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - jenssegers/mongodb v3.2.1 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - jenssegers/mongodb v3.2.2 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - mongodb/mongodb 1.0.5 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.4 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for jenssegers/mongodb ^3.2 -> satisfiable by jenssegers/mongodb[v3.2.0, v3.2.1, v3.2.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - D:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

D:\xampp\htdocs\laravel-mongodb>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jenssegers/mongodb v3.2.0 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - jenssegers/mongodb v3.2.1 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - jenssegers/mongodb v3.2.2 requires mongodb/mongodb ^1.0.0 -> satisfiable by mongodb/mongodb[1.1.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1].
    - mongodb/mongodb 1.0.5 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.4 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.0 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.2 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for jenssegers/mongodb ^3.2 -> satisfiable by jenssegers/mongodb[v3.2.0, v3.2.1, v3.2.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - D:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by bhxabdou** [comment]
![capture](https://user-images.githubusercontent.com/30089652/35127857-c704c9f6-fcab-11e7-9b07-5c0e777ec793.PNG)
I install the drivers and I add the extention but it's not work

**Comment by xinnah** [comment]
i solve this problem..
when your local server is 32 bit install and you mongodb driver setup 64bit.
then create a problem.

[php_mongodb.zip](https://github.com/jenssegers/laravel-mongodb/files/1648499/php_mongodb.zip)
firstly you download this file and unzip this.
and paste xampp\php\ext\
secondly change your php.ini file.
extension=php_mongodb.dll paste this code .
and check phpinfo();
![mongo](https://user-images.githubusercontent.com/16475978/35179577-2d69ee6c-fdc7-11e7-9b01-32f0eed91379.png)

lets enjoy.

**Comment by xinnah** [comment]
https://github.com/jenssegers/laravel-mongodb/issues/822#issuecomment-359142750
check this link

**Comment by lordfhi** [comment]
> i solve this problem..
> when your local server is 32 bit install and you mongodb driver setup 64bit.
> then create a problem.
> 
> [php_mongodb.zip](https://github.com/jenssegers/laravel-mongodb/files/1648499/php_mongodb.zip)
> firstly you download this file and unzip this.
> and paste xampp\php\ext
> secondly change your php.ini file.
> extension=php_mongodb.dll paste this code .
> and check phpinfo();
> ![mongo](https://user-images.githubusercontent.com/16475978/35179577-2d69ee6c-fdc7-11e7-9b01-32f0eed91379.png)
> 
> lets enjoy.

doesnt work for me , help please

**Comment by divine** [comment]
If you still having an issue, please don't reply on old issues - it's really hard to keep eye on it.

Before creating new issue, please kindly check all suggestions that simply suggest to install mongodb extension.

Thanks!
