### ISSUE TITLE
for version 2.0.x MongoClient not found, mongo extension is deprecated.

### ISSUE THREAD

**Issue by selamialtin** [jenssegers/laravel-mongodb#824]
Mongo extension is deprecated. verison 2.0.x still require it.

**Comment by hackel** [comment]
Is this actually supposed to be helpful?  Please, think before you post.

2.x uses the old, deprecated driver.  3.0 uses the new driver.  Pretty simple.  I can't imagine anyone's going to invest the time to migrate the old Laravel 4.2 version of this package to use the new driver.  You need to upgrade.
