### ISSUE TITLE
GridFS

### ISSUE THREAD

**Issue by ryangurn** [jenssegers/laravel-mongodb#828]
Is there any support for GridFS?

**Comment by jmikola** [comment]
Cross-referencing with https://github.com/jenssegers/laravel-mongodb/issues/838#issuecomment-228841563:

> Version 3.0 of this library appears to wrap [mongodb/mongo-php-library](https://github.com/mongodb/mongo-php-library), which does not implement GridFS. Support for GridFS will show up in 1.1.0 (see: [PHPLIB-114](https://jira.mongodb.org/browse/PHPLIB-114)); however, it's API will differ significantly from the [legacy driver's GridFS API](http://php.net/mongogridfs).
