### ISSUE TITLE
[3.0] doesn't support 5.1 because PasswordBrokerManager  doesn't exists in laravel 5.1

### ISSUE THREAD

**Issue by wppd** [jenssegers/laravel-mongodb#829]
https://github.com/laravel/framework/tree/5.1/src/Illuminate/Auth/Passwords

maybe should do a laravel version check before

`PasswordResetServiceProvider.php`

```
    $this->app->singleton('auth.password', function ($app) {
        return new PasswordBrokerManager($app);
    }); 
```

**Comment by wuori** [comment]
Unless you want to port those parts in particular over from the 2.* versions I don't know of a good way to get by this. The Laravel framework for these modules were rewritten and the 3.* just won't match up. Guess the README could be updated?
