### ISSUE TITLE
I have mongo.so but still not installing.

### ISSUE THREAD

**Issue by tzsk** [jenssegers/laravel-mongodb#839]
I have old deprecated mongo.so so there is mongo db installed but still can't install it with composer.

**Comment by wuori** [comment]
You have to also install it to the CLI for PHP (that is, as the extension to two separate php.ini's).

Quick-add for the CLI
`sudo nano /etc/php/7.0/cli/php.ini`
add `extension=mongodb.so` to file

FWIW, Here's a copy of part of my `.homestead/after.sh` that installs Mongo to my Homestead box, for both ini files. It's not perfect but could be helpful. Hope that works!

```
echo "\n--- Updating APT ---\n"
sudo apt-get update

echo "\n--- Installing PHP-specific packages ---\n"
sudo apt-get -y install pkg-config > /dev/null 2>&1

echo "\n--- Installing MONGODB package ---\n"
sudo pecl install mongodb

echo "\n--- Adding Mongo Extension to both ini files ---\n"

FILES="/etc/php/7.0/fpm/php.ini
/etc/php/7.0/cli/php.ini"
module="mongodb.so"

for i in $FILES
do
grep -Eq ";extension=php_bz2.dll$" $i && {
sudo sed -i.bkp "s/^;extension=php_bz2.dll$/extension=$module/" $i &&
echo "Successfully added $module to $i"; } || echo "cant add mongodb, probably already installed"
done

echo "\n--- Restarting Nginx... ---\n"
sudo service nginx restart
echo "\n--- Nginx Restarted! ---\n"
```
