### ISSUE TITLE
How can i create and use auto increment id in laravel 5.2 with mongodb

### ISSUE THREAD

**Issue by MinhTri66** [jenssegers/laravel-mongodb#847]
Hi, thank you for this awsome packages. Can you please guide me how to create and use auto increment id in laravel 5.2 with mongodb when I insert a new data into a collection?.

I have read this guide: https://docs.mongodb.com/manual/tutorial/create-an-auto-incrementing-field/ but I don't know how to implement it with jenssegers/laravel-mongodb in laravel 5.2.

Please help me!! thank you very much...

**Comment by iRbouh** [comment]
Take a look at this gist : https://gist.github.com/iRbouh/d244ff8ad05dbbce417a0b664d2d89a4

**Comment by iRbouh** [comment]
Hi, please take a look at this gist: https://gist.github.com/iRbouh/d244ff8ad05dbbce417a0b664d2d89a4

**Comment by Gtskk** [comment]
See #851 

I have created a pull request.
