### ISSUE TITLE
Error while attempting to seed multiple embeds many relations.

### ISSUE THREAD

**Issue by damienwebdev** [jenssegers/laravel-mongodb#848]
While attempting to do...

> factory(\App\Models\MyModel::class,10)->create()
            ->each(function(App\Models\MyModel $m) {
                $m->children()->save(factory(\App\Models\MyChildModel::class, 5)->make());
            });

I get ...

`Argument 1 passed to Jenssegers\Mongodb\Relations\EmbedsOneOrMany::save() must be an instance of Illuminate\Database\Eloquent\Model, instance of Illuminate\Database\Eloquent\Collection given`

I was expecting to be able to seed multiple child embeds many relations, e.g One parent has many children.

This is doable with the regular Eloquent definition, so I was expecting the same. If this isn't possible, please let me know, and I'll see if I can pull request it in.

**Comment by jensk** [comment]
There is a [saveMany](https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Relations/EmbedsOneOrMany.php#L138) method.
