### ISSUE TITLE
Preventing a child object from saving into a new collection in an embedsMany relationship

### ISSUE THREAD

**Issue by damienwebdev** [jenssegers/laravel-mongodb#849]
Is there any way to forcibly prevent an element used in an embedsMany relationship from being saved into its own collection?

E.g.

Order embedsMany Items

can I prevent myself from accidentally writing Items::create([]) and inserting a new document into a items collection in the database? In SQL land it would theoretically throw a foreign key contstraint violation, anything similar in Mongodb?

**Comment by hackel** [comment]
I'm not aware of anything in MongoDB that would do this.  Just create an Embeddable trait that overrides create() and any other methods you don't want to use and throws an exception instead.
