### ISSUE TITLE
Document Validation Schema

### ISSUE THREAD

**Issue by samirgit** [jenssegers/laravel-mongodb#852]
as from version 3.2 MongoDB supports natively document validation
https://docs.mongodb.com/manual/core/document-validation/

is this currently supported or is there a plan to add it?

**Comment by enginkartal** [comment]
+1

**Comment by teseo** [comment]
any update on this?

**Comment by vesper8** [comment]
Also interested in knowing if this is implemented

**Comment by harrysbaraini** [comment]
+1

**Comment by michelebruno** [comment]
Why was this closed? I am looking for this feature as well but I can't see it in the docs.

Sorry if it is a dumb question, I am new to this package.

**Comment by Modex987** [comment]
I think all you need is `https://github.com/suren1986/laravel-mongo-model-schema` read also 
`https://packagist.org/packages/suren/laravel-mongo-model-schema`

**Comment by michelebruno** [comment]
Thank you very much @Modex987
