### ISSUE TITLE
laravel ^5.2.34 with Queue transaction error

### ISSUE THREAD

**Issue by ebisbe** [jenssegers/laravel-mongodb#854]
Hello,
In laravel ^5.2.34 have  added a transaction in DatabaseQueue.php:pop() https://github.com/laravel/framework/commit/2715509a2842ee0402fd8ceebc21aab92c6d1f91
From that version and above transaction are not working for me because this package does not support it. Is there a workaround or some fix we can do?

**Comment by nunomazer** [comment]
Having the same problem here, is there a good option to overwrite beginTransaction and commit() functions returning null? I made the test and it worked, but I don't know if this may have colateral effects

**Comment by ebisbe** [comment]
Can you make a Pr to the project and hope gets accepted @nunomazer ?

**Comment by sachinvrg** [comment]
I have commented codes in beginTransaction and commit()  and return null , now it is not showing error but still **php artisan queue:work**  command not sending email.
