### ISSUE TITLE
getNextSequence for ID + new MongoDate + Decrements?

### ISSUE THREAD

**Issue by sagargulati** [jenssegers/laravel-mongodb#857]
What is the substitute for the getNextSequence to auto increment the _id?

```
  public function getNextSequence($name, $db)
  {
    $ret = $db->command(array(
      "findandmodify" => "counters",
      "query" => array(
        "_id" => $name
      ),
      "update" => array(
        '$inc' => array(
          "seq" => 1
        )
      ),
      "new" => true
    ));

    return $ret['value']['seq'];
  }
```

Means to auto integrate and assign a new "_id" as in MySQL which stays unique for a user id?

What command should we opt?

Also what is the best way to insert the data?
What we used to do

```
$newData = array();
$newData['_id'] = $getNextSq->("id", $Mongo);
$newData['name'] = 'name';
$Mongo->users->insert($newData);
```

Also what about the old new MongoDate? How to insert a mongo date and timestamp?

How to decrement or increment the sub json data?

Data we have:

`{ "_id": 1, "data": { "new": { "other": 1 } } }`

Query:
`DB::connection("mongodb")->collection("developers")->where("uid", $id)->increment("data['new']['other']", 1);`

Does nothing

P.S # We are using PHP 7.

Help appreciated

Thanks!

**Comment by sagargulati** [comment]
Any updates?

**Comment by sagargulati** [comment]
Why was this closed?

**Comment by coolsam726** [comment]
Why was the issue closed?

**Comment by sagargulati** [comment]
How to auto increment _id in mongoDB?

**Comment by Ademking** [comment]
for anyone looking for a solution, try this:
https://gist.github.com/Ademking/ef99bb8abf04afda6baabd5fc5d22659
