### ISSUE TITLE
Pagination with orderBy

### ISSUE THREAD

**Issue by silencechow** [jenssegers/laravel-mongodb#858]
Member::where('status', 'A')->orderBy('code', 'desc')->paginate(15). 
I am using ->paginate(15) with using ->orderBy('code', 'desc'). 
But the result in not correct. Some of the record is missing and some of the records is duplicate.

**Comment by Acen** [comment]
The same happens with `latest()->paginate(5)`

**Comment by prashant-maven** [comment]
Paginate with orderBy having same issue.

**Comment by prashant8490** [comment]
Paginate with orderBy having same issue.
Missing some records and some are duplicated.

**Comment by puzc1993** [comment]
...->orderBy('update_time', 'desc')->paginate(5); having same issue, result with many missing and dulplicate.

**Comment by puzc1993** [comment]
use Illuminate\Pagination\Paginator;
use Illuminate\Pagination\LengthAwarePaginator;
//......

$perPage = 15;
$currentPage = $request->input('page', 1);
$total = Member::where('status','A')->count();
$result = Member::where('status','A')->orderBy('code','desc')->offset($offset)->limit($perPage)->get();
$members = new LengthAwarePaginator($result,$total,$perPage,$currentPage,[
'path' => Paginator::resolveCurrentPath(),
'pageName' => 'page']);

**Comment by yiannisdesp** [comment]
@puzc1993 thanks!

**Comment by msankar1991** [comment]
@puzc1993,

How we will render this pagination in view files. Can you give example code for this.

**Comment by puzc1993** [comment]
@msankar1991 
https://laravel.com/docs/5.4/pagination#displaying-pagination-results

**Comment by ducthang310** [comment]
@puzc1993 Thanks!

**Comment by TanND** [comment]
@puzc1993 thank you so much

**Comment by gorkie** [comment]
> $members = new LengthAwarePaginator($result,$total,$perPage,$currentPage,[
> 'path' => Paginator::resolveCurrentPath(),
> 'pageName' => 'page']);

You are saved my life 👌
