### ISSUE TITLE
Class 'Jenssegers\Mongodb\MongodbServiceProvider' not found

### ISSUE THREAD

**Issue by EdelBlau** [jenssegers/laravel-mongodb#867]
Hi, 

I can't find a solution for this error:

Class 'Jenssegers\Mongodb\MongodbServiceProvider' not found

I have added these two lines on the config/app.php file
on providers:
Jenssegers\Mongodb\MongodbServiceProvider::class,

on aliases:
'Moloquent' => 'Jenssegers\Mongodb\Model',

and I have the files on my vendor folder, I installed it via composer.

Any ideas on this? Thanks!

**Comment by hackel** [comment]
Your autoloader setup is broken.  Look for composer support.  This has nothing to do with this project.

**Comment by EdelBlau** [comment]
It was solved by installing again the dependencies so I guess that was the problem. Thanks.
