### ISSUE TITLE
Raw update not working

### ISSUE THREAD

**Issue by cherbert** [jenssegers/laravel-mongodb#868]
This updates a sub-document and works perfectly fine when passed through the PHP MongoClient library.

However, it does not work as a raw command.

Events::raw()->update(
            array('_id'  => new \MongoId($eventId), 'document_templates.document_id' => new \MongoId($value['document_id'])),
            array('$set' => array('document_templates.$' => $value))
        );

There are no errors. The sub-document simply does not get updated as it should.

Unless I am misunderstanding the capabilities of the raw the command?

**Comment by rainyson** [comment]
+1

**Comment by navneetccna** [comment]
@jenssegers what is the solution? you just closed the issue without any answer.

**Comment by joerecra** [comment]
@cherbert, how did you do to work with $ positional operator ? when I use it, I get this: "The positional operator did not find the match needed from the query. Unexpanded update: results.$.test"

Query:

DB::collection('joboffer_results')->raw(function($collection)
      {
          return $collection->updateMany([],['$set'=> ['results.$.test'=>'Joel Recra2']], ['multi'=>'true']);
      });

**Comment by tranghaviet** [comment]
Why Jenssegers just close issues like this without any answer? I think this repository no longer maintained

**Comment by tranghaviet** [comment]
I found the solution by dig into source code. Query builder use `$set` operator by default. Here is the solution:
```
$this->query->where('_id', '=', $id)
            ->where('locales.language', $language)
            ->update(['locales.$' => $request->all()]);
```
The model have `locales` is an Array.

https://github.com/jenssegers/laravel-mongodb/blob/1d2807b49742d6529c81592fbc969a220cb7a366/src/Jenssegers/Mongodb/Query/Builder.php#L582

**Comment by mzcoder-hub** [comment]
> I found the solution by dig into source code. Query builder use `$set` operator by default. Here is the solution:
> 
> ```
> $this->query->where('_id', '=', $id)
>             ->where('locales.language', $language)
>             ->update(['locales.$' => $request->all()]);
> ```
> 
> The model have `locales` is an Array.
> 
> https://github.com/jenssegers/laravel-mongodb/blob/1d2807b49742d6529c81592fbc969a220cb7a366/src/Jenssegers/Mongodb/Query/Builder.php#L582

Should i create this on models ? Or just on the controller?

**Comment by tranghaviet** [comment]
> > I found the solution by dig into source code. Query builder use `$set` operator by default. Here is the solution:
> > ```
> > $this->query->where('_id', '=', $id)
> >             ->where('locales.language', $language)
> >             ->update(['locales.$' => $request->all()]);
> > ```
> > 
> > 
> > The model have `locales` is an Array.
> > https://github.com/jenssegers/laravel-mongodb/blob/1d2807b49742d6529c81592fbc969a220cb7a366/src/Jenssegers/Mongodb/Query/Builder.php#L582
> 
> Should i create this on models ? Or just on the controller?

Replace `$this->query->` with `(new Model())->` or `Model::`. Here I used a repository with `$this->query = new Model()`
