### ISSUE TITLE
Using Mongo for Queues simply doesn't work

### ISSUE THREAD

**Issue by cherbert** [jenssegers/laravel-mongodb#869]
'connections' => [
    'database' => [
        'driver' => 'mongodb',
        'table'  => 'jobs',
        'queue'  => 'default',
        'expire' => 60,
    ],

That is in my queue.php inside the config folder.

It completely ignores the driver and continues to use the MySQL jobs table. I am using PHP 7 with Laravel 5.2

**Comment by elfeffe** [comment]
I have changed name 'database' to 'mongodb', because we already have a 'database' connection.
And then QUEUE_DRIVER=mongodb
It creates the jobs, but I still can't make them run.

**Comment by nunomazer** [comment]
See #854

**Comment by sachinvrg** [comment]
can anybody help me working it out ?
