### ISSUE TITLE
I m getting Error when in install jenssegers/laravel-mongodb

### ISSUE THREAD

**Issue by ektasingh2408** [jenssegers/laravel-mongodb#872]
![mongo](https://cloud.githubusercontent.com/assets/17611244/16258626/50f6d4c4-387c-11e6-8188-83ed96858888.PNG)
![mongoa](https://cloud.githubusercontent.com/assets/17611244/16258627/50f8daf8-387c-11e6-87dd-bf459f07c676.PNG)

**Comment by elfeffe** [comment]
You have installed mongo driver, and you need to install mongodb driver.
They are different, and I broke my head until I resolved the same problem

**Comment by tuytoosh** [comment]
how to install mogodb driver??? @elfeffe

**Comment by elfeffe** [comment]
First to uninstall mongo extension. If you remove it from php.ini is ok, but restart PHP after it.

Then do:
`sudo apt-get update`
And follow this http://mongodb.github.io/mongo-php-driver/

That is the PHP extension and this is the MongoDB library
https://github.com/mongodb/mongo-php-library

You will need to add the library to the project using composer too
`composer require "mongodb/mongodb=^1.0.0"`

**Comment by IgorDePaula** [comment]
Try issue #797
