### ISSUE TITLE
Can't save 'dates' property in model

### ISSUE THREAD

**Issue by hfuccillo** [jenssegers/laravel-mongodb#873]
I'm trying to save an object with 'dates': {start: '2016-06-22', end: '2016-06-22' } property but when I retrieve the object from the collection I realize that the property do not exists.

Is that an issue or I'm missing something?
Thanks in advance!

**Comment by hackel** [comment]
The $dates property is reserved in Eloquent models, it's an array that defines date fields.  Just pick a different name.
