### ISSUE TITLE
UTF-8 char causing UnexpectedValueException Could not convert BSON document to a PHP variable

### ISSUE THREAD

**Issue by blitzfu** [jenssegers/laravel-mongodb#874]
I searched around for this, but didn't see anything similar. After I upgraded to the newer php mongodb driver, I ran into a problem with this code:

    /*  db.10Index.aggregate({ $group: {_id: {$substr: ['$mainTerm', 0, 1]}, count: {$sum: 1}}},
        {$sort : { _id:1}})  

    */
    public function index()
    {
        $index = DB::collection('10Index')->raw()->aggregate([
            ['$group' =>
                    ['_id' => ['$substr' => ['$mainTerm', 0, 1]],
                    'count' => ['$sum' => 1]]
            ],
            ['$sort' => ['_id' => 1]]
        ]);

        $data = array();
        try {
            foreach ($index as $doc) {
                array_push($data, array('_id' => $doc['_id'], 'count' => $doc['count']));
            }
        }
        catch(\Exception $e) { /* UTF-8 character made me blow up */ }

        $results = array_filter($data, function($e) { return $e["count"] > 1; });
        $col1 = array_filter($results, function($e) { return $e["_id"] < 'N'; });
        $col2 = array_filter($results, function($e) { return $e["_id"] > 'M'; });

        return view('index.index', compact('col1', 'col2'));
    }

Once I added the try/catch to the above code I discovered it was being caused by a UTF-8 character in the BSONDocument, however, this doesn't seem like the cleanest way to do this.

Any hints on having this package deal with UTF-8, or maybe this question belongs somewhere else?

Thanks.

**Comment by whenjonny** [comment]
how to resolve this？
