### ISSUE TITLE
Updating array on embedsmany relationship.

### ISSUE THREAD

**Issue by bdschr** [jenssegers/laravel-mongodb#876]
Hello, 

There appears to be a problem when updating the array on a embedded document. Tried saving through parent relationship, saving on the embedded model itself, pull and push functions don't seem to work either. Strange enough all none array fields are saved properly without a problem.

Best Regards,
David

**Comment by george-viaud** [comment]
I am experiencing the same issue.

My embedded model has a field which is an array.  Attempting to:

```
$myModel = MyModel::find($aValidId);
$mySubModel = $myModel->SubModels->find($aValidSubModelId);
$mySubModel->push('arrayFieldName', ['some','array','data');```

This doesn't update the submodel in the DB.

Adding ```$mySubModel->save()``` or ```$myModel->save()``` doesn't appear to help.

Oddly, checking the model after push within the same function shows the data as updated, but the change is never stored in the DB.
