### ISSUE TITLE
Can this be used as the only Laravel database? Or MySql is needed?

### ISSUE THREAD

**Issue by elfeffe** [jenssegers/laravel-mongodb#877]
I'm trying to install https://github.com/sroutier/laravel-5.1-enterprise-starter-kit
And I want to use this only with MongoDB. Is that possible or MySql is needed in any case?

I have MongoDB working on a Lumen project, but it's a small project.

And can MySql and MongoDB work together?

**Comment by elfeffe** [comment]
I found this issue
https://github.com/jenssegers/laravel-mongodb/issues/253

That's exactly what I have. i don't know where to write `use Jenssegers\Mongodb\Model as Eloquent;`

**Comment by hackel** [comment]
You do not need MySQL or any other database at all.  It's totally up to you.  This package provides a HybridRelations trait if you want your models to be able to include related data from other Eloquent models (MySQL, etc.).

This is clearly not an issue with this package, just your own lack of research.  Please use Stackoverflow, etc. for such support questions.

**Comment by elfeffe** [comment]
Sure, sorry

**Comment by Barryt06** [comment]
@elfeffe Did you ever get this working? I am looking to set up the same but I am having issues trying to install this plugin with LESK, where I have been able to install it a vanilla install of Laravel.

**Comment by elfeffe** [comment]
@Barryt06 I have more experience now with Laravel.
MongoDB works great, but you should use it only for your models. 99.99% of the available package will not work with MongoDB.
So I use MySql as default DB, and Mongo with my models.
I hope Laravel support officially Mongo some day, probably in 4.0 as they included transactions.
