### ISSUE TITLE
GroupBy and COUNT together do not work

### ISSUE THREAD

**Issue by yespbs** [jenssegers/laravel-mongodb#887]
Group By and COUNT do not work together, I have tried #535 but have a better solution

mysql query:
 SELECT theCol, count(theCol) FROM theTable GROUP BY theCol;

mongodb elequent
\MyModel::get(['theCol', 'count']);

by modifying the core 
`vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php`
Line 193.
`foreach ($this->columns as $column) {
                    // count
                    if( 'count' == $column ){
                        // just test
                        $group['count'] = ['$sum' => 1];
                    }else{

```
                    $key = str_replace('.', '_', $column);

                    $group[$key] = ['$last' => '$' . $column];
                }    
            }`
```

can this be fixed in core instead of using raw method?

**Comment by maulikmmodi** [comment]
U can try like this, It will work

$nacionalidad = DB::table('medicos')->raw( function ( $collection ) {
return $collection->aggregate([
[
'$group' => [
'_id' => array(
'nacionalidad' => '$nacionalidad'
),
'count' => ['$sum' => 1],
]
],
]);
});

It will return CURSOR pointer and u need to iterate that, u can look it in here https://docs.mongodb.com/v3.0/reference/glossary/#term-cursor or by following :
