### ISSUE TITLE
php5.6 has error

### ISSUE THREAD

**Issue by dmlzj** [jenssegers/laravel-mongodb#891]
This plugin is not support php5.6?
php.ini has mongodb support.
When i use it give me a error:"Class 'MongoClient' not found".
Help me thankyou!

**Comment by sakalauskas** [comment]
You need to upgrade laravel-mongodb to 3.x version. 

There are two mongodb php libraries: mongodb (latest) and mongo (deprecated). From what you written I believe you have latest mongodb library. 

Therefore 2.x laravel-mongodb library supports the old library.

**Comment by lephleg** [comment]
Any solution on this for L4 (which uses 2.x)?
