### ISSUE TITLE
getPdo() return null on connected database

### ISSUE THREAD

**Issue by theminer3746** [jenssegers/laravel-mongodb#894]
I'm using `DB::connection('mongodb')->getPdo()` to check if the database is connected (if not phpunit will mark some test as skipped) and it's turning out that `->getPdo()` always return `null`. The connection is working proven by that I can use `php artisan migrate` to create new collection and I can insert data into the collection.

Environment : 
- OS : windows 10 running MAMP 3.2.0
- laravel : 5.2.37
- jenssegers/mongodb : 3.0.2

**Comment by iNDicat0r** [comment]
`DB::connection('mongodb')->getPdo() ` Returns `null` because `getPdo()` returnn0 the mysql PDO instance, and since you are not using mysql and you are using mongo this method is useless!

**Comment by theminer3746** [comment]
Oh, I see. thanks
