### ISSUE TITLE
::find() is not finding by the column that I set

### ISSUE THREAD

**Issue by skys215** [jenssegers/laravel-mongodb#906]
I set primary key as `id` in model file rather than `_id` of the mongo.
When run the `Model::find()`, it will find column `_id`, not the primaryKey I set.
I found it was hard coded [here](https://github.com/jenssegers/laravel-mongodb/blob/5454ac96a9748b1e812f7a5b3bcbf304bee80e0d/src/Jenssegers/Mongodb/Query/Builder.php#L201).

**Comment by ozanakman** [comment]
You should override $primaryKey attribute in your model like:
`protected $primaryKey = '_id';`

**Comment by ultraN** [comment]
I had this issue as well.
