### ISSUE TITLE
"belongsToMany" does act as "hasMany" 

### ISSUE THREAD

**Issue by noel45** [jenssegers/laravel-mongodb#908]
Hi, 

Trying to understand the differences between the different type of relations, I realized that "belongsToMany" does act the same as "hasMany".

Example in a class "Product":

**_Situation 1_**
First let's say one product has one contributor "user" :

`public function user()
    {
        return $this->belongsTo(User::class);
    }`

Product : `id:"Product1", user_id:"User1"`
User `id:"User1"`

=> This will search the field "user_id" in the table "products" and then retrieve the matching user, OK

**_Situation 2_**
Now let's say one product can have many contributors, and we choose to store the relation the other way around :

`public function user()
    {
        return $this->hasMany(User::class);
    }`

Product : `id:"Product1"`
User `id:"User1,product_id:"Product1"`
User `id:"User2,product_id:"Product1"`

=> This will search the field "product_id" in the table "users", and retrieve those that are matching the current product_id of the caller, OK

**_Situation 3 (Issue)_**
Now lets's say that we want to store the list of contributors in the table "products", exactly what is doing "belongsTo", but for many users instead of one. BelongsToMany seems what we are searching for.

`public function user()
    {
        return $this->belongsToMany(User::class);
    }`

Product : `id:"Product1", user_ids:["User1","User2"]`
User `id:"User1"`
User `id:"User2"`
=>FAILURE

=> This will search the field "product_id**s**" in the table "users" and retrieve those that are matching the current product_id of the caller, which is actually the same as "hasMany", except that the default target field has a "s" at the end. Setting local and foreign keys manually won't help, as the logic seems to be wrong.

It should actually works the same way as belongsTo, ie retrieve the field "users_id**s**" in the table "products" and then match the matching user_id(s) in the table user.

I might be wrong but after many hours of testing, it seems to be a real issue.

**Comment by jasonlfunk** [comment]
I can confirm this, `belongsToMany` seems to be broken.

My example:
```
class User {
    public function sites() {
        return $this->belongsToMany(Site::class);
    }
}
```

```
>> $user->sites()->getQuery()->toSql()
=> "select * from "sites" where "user_ids" = ?"
```

This is definitely wrong. It should be something like:
`select * from "sites" where "_id" in ?`

**Comment by jasonlfunk** [comment]
Okay, after digging around a bit, I figured out what's going on. The library automagically creates the inverse method for the relationship. So, in my case, sites was automatically getting a `user_ids` field. This is why the query is right.

My problem was that the object *must* be saved before you can add relations to it.

```
$user = new User();
$user->save(); // THIS MUST BE FIRST
$user->sites()->save($site);
```

If you do it in the other way, then site will get a `user_ids=[null]`. Which is wrong and causes the problem that I was seeing.
