### ISSUE TITLE
Why Package uses "homestead" DB ?

### ISSUE THREAD

**Issue by AliBahaari** [jenssegers/laravel-mongodb#910]
Hi, First thanks my friend for your Best Package I have ever seen ...
I have a Small Problem. I have defined in Config/app.php & in .env that It should use "Laravel" DB.
But When I add a document, It will add to "homestead" DB.
I have done a mistake ?

**Comment by sakalauskas** [comment]
Yes you did.

Check your config/database.php config

the line starting with...
`            'mongodb' => [
                'driver' => 'mongodb',
                'host' => 'localhost',
                'port' => 27017,
                'username' => '',
                'password' => '',
                'database' => env('DB_DATABASE', 'forge'),
            ],`

**Comment by ABZiko** [comment]
Thanks ...
