### ISSUE TITLE
Dates is not converted in where clauses

### ISSUE THREAD

**Issue by deividaspetraitis** [jenssegers/laravel-mongodb#913]
Following would work fine:

`model->where('start_date', Carbon::now())`

However condition like this would fail:

`model->where('start_date', ['$gte' => Carbon::now()])`

Problem seems is here: 

```
if (isset($where['value']) and $where['value'] instanceof DateTime) {
                $where['value'] = new UTCDateTime($where['value']->getTimestamp() * 1000);
}
```

File: https://github.com/jenssegers/laravel-mongodb/blob/master/src/Jenssegers/Mongodb/Query/Builder.php#L870

**Comment by sakalauskas** [comment]
Why don't just use `model->where('start_date', '>=', Carbon::now())`?

or if you want to still use $gte you can simply pass UTCDateTime there instead of Carbon object like:
`model->where('start_date', ['$gte' => new UTCDateTime(Carbon::now()->timestamp * 1000)])
`

**Comment by deividaspetraitis** [comment]
Thanks @sakalauskas , seems following expression works well:

`model->where('start_date', '>=', Carbon::now())`

However, I'll keep this pull request open, since in second example provided functionallity is the same what's done internaly with single DateTime instances and I think the same should be supported natively with MongoDB operators.

**Comment by nerijunior** [comment]
```php
$notifications = Notification::where('sent', '=', false)
            ->where('created_at', '<=', Carbon::now())
            ->get();
```

It's doesn't work for me.
