### ISSUE TITLE
Fatal errors after composer update

### ISSUE THREAD

**Issue by george-viaud** [jenssegers/laravel-mongodb#922]
Not sure if this is related but laravel-mongodb is one of the only mods I have applied to this install of 5.2.x

Was previously working until running composer update

FatalErrorException in Builder.php line 1446: Call to a member function compileSelect() on a non-object

Any ideas greatly appreciated - not very familiar with debugging Laravel

**Comment by george-viaud** [comment]
Ok - I figured out what was wrong and will clarify below, but I'm not sure if this is the cleanest way to do this as it requires modifying the framework...

The problem has to do with Auth (I'm using mongo for auto as well, I forgot I had to hack this in before and since upgrading the framework the hack needed to be re-implemented).

The vendor/laravel/framework/src/Illuminate/Foundation/Auth/User.php file now reads:

,,,
<?php

namespace Illuminate\Foundation\Auth;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Moloquent;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Moloquent implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
}
,,,

Thoughts on this?

**Comment by tera-g** [comment]
@george-viaud this is not a solution. I did change laravel framework version. (v5.2.43 -> v5.2.31)
