### ISSUE TITLE
whereBetween does not respect Eloquent date mutators

### ISSUE THREAD

**Issue by pwoo** [jenssegers/laravel-mongodb#923]
Tested on Laravel 5.2.41 & laravel-mongodb 2.3.5.

Referencing back to the example on the documentation page:

`$users = User::where('birthday', '>', new DateTime('-18 years'))->get();`

It appears as if passing a DateTime / Carbon instance to whereBetween, such as:

`$users = User::whereBetween('birthday', array(new DateTime('-18 years'), new DateTime())->get();`

Returns an empty collection with no resulting exceptions.

It looks like whereBetween is only valid when wrapping the dates with MongoDate (and presumably the PHP7 equivalent) .

**Comment by iamkallolpratim** [comment]
same problem happenning with me also. Unable to get the results when use whereBetween to compare two compare two datetime
