### ISSUE TITLE
bind with Laravel 5.3 components is broken

### ISSUE THREAD

**Issue by arhatal** [jenssegers/laravel-mongodb#924]
new the Laravel Builder concepts broked interface with MongoDb Builder.
Current Laravel Builder::where return array instead object and method all() (first, get, find) is broken with 
"Call to a member function all() on array"

**Comment by Endijs** [comment]
While this is not fixed, take a look at this pull request: https://github.com/jenssegers/laravel-mongodb/pull/905/files . I made changes for Jenssegers/Mongodb/Query/Builder.php - replaced default return values with the ones that return collection (3 edits in total). And it started to work.

**Comment by lukepolo** [comment]
Please use the search feature to find open issues #925
