### ISSUE TITLE
What about Laravel 5.3 ?

### ISSUE THREAD

**Issue by AliBahaari** [jenssegers/laravel-mongodb#927]
Hi ..., Recently Laravel 5.3 came out. Is there any problem If I use the version for Laravel 5.2 ?

**Comment by lukepolo** [comment]
Please use the search feature to find open issues #925

**Comment by gp187** [comment]
As a workaround to use `mongodb` in laravel 5.3 you can use this 



`Model`
```
use Jenssegers\Mongodb\Eloquent\Model as Moloquent;

class AdminUser extends Moloquent
{
    protected $connection="mongodb";
    protected $collection="admin_important_users";
}
```
`Controller`

```
class AdminUserController extends Controller
{
    public $model;

    public function __construct(AdminUser $user) {
        $this->model = $user;
    }
```

```
$col = $this->model->getConnection()->table('admin_important_users');
$col->get();
```

That's how you get collection object. I'll try some fixes but for now this works.

**Comment by lukepolo** [comment]
#925 solves this , no need , just needs merged.

**Comment by ABZiko** [comment]
Thanks @lukepolo & @gp187 ..., What is the problem exactly ?

**Comment by gp187** [comment]
Ok @lukepolo . Let's see it done.
Merge please @jenssegers
