### ISSUE TITLE
paginate() error (Laravel 5.3)

### ISSUE THREAD

**Issue by xxnoobmanxx** [jenssegers/laravel-mongodb#931]
Hi, I am trying to upgrade to laravel 5.3. 
In my tests, when I call `SomeMoloquent::paginate(5)`  (assume moloquent is a random mongodb model), it throws the following exception:

```
FatalErrorException in Builder.php line 1702:
Call to a member function all() on array
```

For regular Eloquent objects, `paginate` method works well

**Comment by xxnoobmanxx** [comment]
I found a possible fix to the problem in _Jenssegers\Mongodb\Query\Builder_ class :

In `get` method, substitute

```
return $this->getFresh($columns);
```

for

```
$data = $this->getFresh($columns);
return new \Illuminate\Support\Collection($data);
```

But, unfortunately, I dont know if this is the best possible solution.

**Comment by pi0** [comment]
Hi . this issue is fixed and will be resolved after new composer tag :)

**Comment by xxnoobmanxx** [comment]
Good! Thank you! @pi0
