### ISSUE TITLE
Laravel 5.3 migration

### ISSUE THREAD

**Issue by kschethan** [jenssegers/laravel-mongodb#933]
Hey, I just upgrade to Laravel to 5.3 and using "jenssegers/mongodb": "^3.0".

So while migrating, there seems to be an error, 

[ErrorException]
Declaration of Jenssegers\Mongodb\Schema\Blueprint::primary() should be compatible with Illuminate\Database\Schema\Blueprint::primary($columns, $name = NULL, $algorithm = NULL)

Please take a took this ASAP and suggest what can be done to fix it.

![screen shot 2016-08-30 at 3 11 51 pm](https://cloud.githubusercontent.com/assets/9974824/18084256/2208196a-6ec4-11e6-948d-36c82a8d3679.png)

**Comment by jenssegers** [comment]
We're working on this :)

**Comment by yazeed** [comment]
Any update? :)

**Comment by pi0** [comment]
@yazeed it is already fixed in 3.1.x release ;) @jenssegers would you close this issue ?
