### ISSUE TITLE
[HowTo] Rebasing PRs

### ISSUE THREAD

**Issue by pi0** [jenssegers/laravel-mongodb#937]
There are new breaking changes on master so all UnitTests was failing on PRs.

In order to rebase your forks with master branch and running UnitTests against latest changes you can follow this steps.  
Assuming we want to rebase #918 (`fieteboerner:aggregate-subdocument`). on your fork :

``` bash

# Add upstream and fetch everything
git remote add upstream git@github.com:jenssegers/laravel-mongodb.git
git fetch upstream

# Checkout to patch branch
git checkout aggregate-subdocument

# Rebase with upstream's master
git rebase upstream/master

# Fast-Forward Changes
git push -ff

```

Then you can check your PR again for failing tests and fix them :)

**Comment by Bodom78** [comment]
Thanks @pi0, I have followed your instructions and #792 is now passing all checks.
