### ISSUE TITLE
ConnectionTimeoutException

### ISSUE THREAD

**Issue by yazeed** [jenssegers/laravel-mongodb#942]
Is the following caused by a bug in the library or something to contact mlab.com about?

ConnectionTimeoutException in Collection.php line 466:
No suitable servers found (`serverselectiontryonce` set): [connection timeout calling ismaster on '******_.mlab.com:**_**']

**Comment by sefsinalas** [comment]
same error here

**Comment by ptitkiller** [comment]
same error here

**Comment by siteclub** [comment]
same here

**Comment by prashant-pokhriyal** [comment]
This is because your mongodb service is not running. Check the status of your mongodb service by typing :

`service mongod status` . 

If the status is failed or inactive, try to run the service again by typing 
`service mongod start`
 and then again check the status of mongodb service

**Comment by davorminchorov** [comment]
I get this error too. The weird part is that at times it shows up 5 times in a row and the 6th time it works fine like nothing happened before.

**Comment by NickBefore** [comment]
@prashant-pokhriyal solved it to me.
