### ISSUE TITLE
Raw or custom method input

### ISSUE THREAD

**Issue by jamieshepherd** [jenssegers/laravel-mongodb#943]
I want to perform db.collection.stats() on a collection, because it's a really lightweight way of getting the count of a collection (through size field). Current count() on millions of rows becomes incredibly very slow. Is there a way or feature planned to allow custom methods to be called on a collection. E.g.

`DB::collection('users')->stats()`

or even perhaps

`DB::collection('users')->custom('stats')`

if you didn't want to support that method in particular but wanted to allow people to call other MongoDB methods.

**Comment by pi0** [comment]
We probably add features like this in next releases ... ;) +1 for your suggestion :)

**Comment by teamelliel** [comment]
Does this work, if yes, I cannot seem to find the command in the example docs. Any suggestions?
