### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found

### ISSUE THREAD

**Issue by jetsynthesys** [jenssegers/laravel-mongodb#944]
Hi, 

Earlier I was using dev-master branch which was supporting new MongoDB drivers. Recently i updated it to 3.1-alpha and 3.0 version but am getting this Uncaught Error for class 'Illuminate\Foundation\Application'. Before update this was working fine and now its breaking entire thing. I am using this outside laravel framework. 

`Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in /var/www/jetmetrix_new/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php:99 Stack trace: #0 /var/www/jetmetrix_new/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php(536): Jenssegers\Mongodb\Query\Builder->__construct(Object(Jenssegers\Mongodb\Connection), Object(Jenssegers\Mongodb\Query\Processor)) #1 /var/www/jetmetrix_new/vendor/illuminate/database/Eloquent/Model.php(1831): Jenssegers\Mongodb\Eloquent\Model->newBaseQueryBuilder() #2 /var/www/jetmetrix_new/vendor/illuminate/database/Eloquent/Model.php(1801): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes() #3 /var/www/jetmetrix_new/vendor/illuminate/database/Eloquent/Model.php(3513): Illuminate\Database\Eloquent\Model->newQuery() #4 /var/www/jetmetrix_new/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php(553): Illuminate\Database\Eloquent\Model->__call('where', Array) #5 /var/www/jetmetrix_new/lib/JetMetrix.php(3926): Jensseg in /var/www/jetmetrix_new/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Query/Builder.php on line 99`

**Comment by acidjazz** [comment]
same here

**Comment by acidjazz** [comment]
if it helps speed things up @jenssegers it looks like instead of that constant there is a an $app->version() function for Lumen (which is what I'm using)

**Comment by jetsynthesys** [comment]
@acidjazz @jenssegers when using this outside laravel framework, the version compare of laravel framework is not required so it's best to put inside a condition 

```php
if (class_exists('\\Illuminate\\Foundation\\Application')) {
	$this->useCollections = version_compare(\Illuminate\Foundation\Application::VERSION, '5.3', '>=');
} else {
	$this->useCollections = true;
}
```

**Comment by acidjazz** [comment]
@jetsynthesys thanks, why is that though? why does returning collections only exist in 5.3 now but in Lumen it was always OK?

**Comment by acidjazz** [comment]
It looks like PR #948 seems to address this, if you look at [the addition](https://github.com/jenssegers/laravel-mongodb/pull/948/files)

**Comment by GreenLamantin** [comment]
Subscribe

**Comment by GreenLamantin** [comment]
You can add to your bootstrap as temporary solution
```
if (!class_exists('\Illuminate\Foundation\Application')) {
    class_alias(\App\Application::class, '\Illuminate\Foundation\Application');
}
```

**Comment by acidjazz** [comment]
@GreenLamantin I would say @morrislaptop 's change is the most sound in #948 so far since he's still actually checking for the version

**Comment by giaule** [comment]
@GreenLamantin i had try used your idea, this good

Thanks.

**Comment by petidesoftwares** [comment]
i need help on the following issue:
<b>Fatal error</b>: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in
C:\Users\DELL\Documents\GitHub\arms-backend\bootstrap\app.php:14
Stack trace:
#0 C:\Users\DELL\Documents\GitHub\arms-backend\public\index.php(38): require_once()
#1 C:\Users\DELL\Documents\GitHub\arms-backend\server.php(21): require_once('C:\\Users\\DELL\\D...')
#2 {main}
thrown in <b>C:\Users\DELL\Documents\GitHub\arms-backend\bootstrap\app.php</b> on line <b>14</b><br />
