### ISSUE TITLE
Problems with Laravel MongoDB Eloquent

### ISSUE THREAD

**Issue by joelpiccoli** [jenssegers/laravel-mongodb#945]
Hello Everyone!
I'm starting to use *jenssegers/laravel-mongodb* library to handle my mongodb database, I was trying it out, doing some examples by myself and I couldn't get it to work with Eloquent (Moloquent).

When I use something like  **DB::collection('usuarios')->get();** it's ok, bring me the result with no problem, but when I try to use **Model::all()** or **Model::find(x)** don't work...

I really don't know what happen, anyone can help me solve this?

## The error message
https://drive.google.com/open?id=0B4Te5CFLgo4ARGo5bkE2NnJyeXM

## The Provider and Alias

```php
Jenssegers\Mongodb\MongodbServiceProvider::class
```
```php
'Moloquent' => Jenssegers\Mongodb\Eloquent\Model::class,
```

## The Connection Config

```php
'mongodb' => [
            'driver'   => 'mongodb',
            'host'     => 'localhost',
            'port'     => 27017,
            'database' => env('DB_DATABASE'),
            'username' => env('DB_USERNAME'),
            'password' => env('DB_PASSWORD'),
            'options'  => [
                'database' => 'testes' // sets the authentication database required by mongo 3
            ]
        ]
```

## The Model

```php
namespace App\Models;

use Moloquent;

class UsuariosModel extends Moloquent
{
    protected $collection = 'usuarios';
}
```

## The Controller

```php
    namespace App\Http\Controllers;

    use App\Http\Requests;
    use App\Models\UsuariosModel;

    class UsuariosController extends Controller
    {
        public function index()
        {
            $usuarios = UsuariosModel::all();

            dd($usuarios);
        }
    }
```

**Comment by linusstaf** [comment]
I guess you are using laravel 5.3? 

If that is the case you need to use v3.1.0-alpha of this library to be compatible with the latest release of Laravel. 

Run `composer require jenssegers/mongodb:v3.1.0-alpha` to use that version, or edit your composer.json file and then run composer update.

**Comment by joelpiccoli** [comment]
Thanks a lot @linusstaf! 
I thought might be something like this. Now everything is running like should... xD

**Comment by jay-proaxiom** [comment]
I am using latest version still i am getting undefined type everywhere but works fine with laravel but showing problem with undefined with when where get everywhere

**Comment by yashvirdelimp** [comment]
I have Added  on payment Method add as well
