### ISSUE TITLE
Issue with get() method when fetching data from Mongo Model

### ISSUE THREAD

**Issue by haridarshan** [jenssegers/laravel-mongodb#955]
Hi,

Sorry, for posting this issue over here because I don't know whether exact issue with this mongodb library v3.0.2 or laravel orm v5.3.4

I'am using Illuminate database orm with laravel-mongodb outside laravel framework. Recently I updated both libraries to latest release versions and suddenly I started getting issue with get() when fetching data from collection. Previous version which I was using were laravel database v.5.2.43 and laravel-mongodb v3.0.0

This is the call am using and getting below error. 

``` php
$getFacebookPosts = \App\Models\Mongo\Facebookpost::where(
    'facebook_account_id', $userDetails['facebook']['id']
)
->where('created_at', '>', $date_from)
->where('created_at', '<=', $date_to)
->get();
```

```php
Fatal error: Uncaught Error: Call to a member function all() on array in /var/www/app/vendor/illuminate/database/Eloquent/Builder.php:613 Stack trace: #0 /var/www/app/vendor/illuminate/database/Eloquent/Builder.php(318): Illuminate\Database\Eloquent\Builder->getModels(Array) #1 /var/www/app/lib/App.php(3833): Illuminate\Database\Eloquent\Builder->get() #2 /var/www/app/influencer/partials/facebook-user-details.php(4): App->facebookUserData('15') #3 {main} thrown in /var/www/app/vendor/illuminate/database/Eloquent/Builder.php on line 613
```

**Comment by cherbert** [comment]
If you are using Laravel 5.3 you need to update composer to install "jensegers/mongodb": ^"3.2"

**Comment by haridarshan** [comment]
Hi, 

Still getting this error after updating 

> illuminate database from v5.2.43 to v5.3.16
> jenssegers/mongodb from v3.0.0 to v3.1.3

`Fatal error: Uncaught Error: Call to a member function all() on array in /var/www/app/vendor/illuminate/database/Eloquent/Builder.php:613 Stack trace: #0 /var/www/app/vendor/illuminate/database/Eloquent/Builder.php(318): Illuminate\Database\Eloquent\Builder->getModels(Array) #1 /var/www/app/vendor/illuminate/database/Eloquent/Model.php(632): Illuminate\Database\Eloquent\Builder->get(Array) #2 /var/www/app/config.php(138): Illuminate\Database\Eloquent\Model::all() #3 /var/www/app/handler.do(3): require('/var/www/app...') #4 {main} thrown in /var/www/app/vendor/illuminate/database/Eloquent/Builder.php on line 613`

**Comment by wedgwood** [comment]
Still getting this error after updating too.

**Comment by haridarshan** [comment]
Yes, only when am using latest release version of illuminate database

**Comment by wedgwood** [comment]
@haridarshan you could solve it use method from #1037 before fixed.

**Comment by haridarshan** [comment]
@wedgwood 
Since am using different components from different frameworks in our project so is it possible to have that fix inside `shouldUseCollections` method. That will be great when anyone using laravel-mongodb outside laravel framework.

**Comment by haridarshan** [comment]
@wedgwood 
Hi,
It did work but I have a use case where am fetching data from Mongo and fetch some values from Sql db and in fetched Mongo am updating the value. When doing so, am getting this error

`Argument 1 passed to Jenssegers\Mongodb\Query\Builder::__construct() must be an instance of Jenssegers\Mongodb\Connection, instance of Illuminate\Database\MySqlConnection given, called in /var/www/app/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php on line 399`

Here is what am doing

```php
/**
* Get all running live streams
*/
$getAllLiveStreams = LiveVideoStream::where([
	'status' => 'live'
])->get();

if (! $getAllLiveStreams->isEmpty()) {
	foreach ($getAllLiveStreams as $liveStream) {
		/**
		* Get all subscribed user for topic
		*/
		$getAllSubscribedUserCount = SubscribedUser::select('client_id')->where([
			'topics' => $liveStream->mqtt_topic
		])->count();
		
		/**
		* Save this count in LiveVideoStream
		*/
		$liveStream->live_viewers = $getAllSubscribedUserCount;
		try {
			$liveStream->save();
		} catch (\Throwable $exception) {
			// do nothing	
		}
	}
}
```
