### ISSUE TITLE
Multiple relations to same model

### ISSUE THREAD

**Issue by dmitov** [jenssegers/laravel-mongodb#956]
Hello,

I'll go with the code directly.

Imagine you have Users that can have two relations to Tasks model. One is watched tasks, the other is pinned tasks. 

```
    /**
     * An user can have multiple watched tasks
     *
     * @return Jenssegers\Mongodb\Relations\BelongsToMany
     */
    public function watched()
    {
        return $this->belongsToMany(Application::class);
    }

    /**
     * An user can have multiple pinned taks
     *
     * @return Jenssegers\Mongodb\Relations\BelongsToMany
     */
    public function pinned()
    {
        return $this->belongsToMany(Application::class);
    }
```

But on attaching any of those relations, you get a property on the document called `application_ids`. As you might found out, both methods will use the same property and will collide with each other.

Anyone faced this issue before?

**Comment by felipebastosweb** [comment]
Do You tryed ...
 public function groups()
    {
        return $this->belongsToMany('Group', null, 'user_ids', 'group_ids');
    }

And failed?

**Comment by felipebastosweb** [comment]
Or watched and pinned are condictions, example:

Task
pinned bool
watched bool

???

**Comment by dmitov** [comment]
@felipebastosweb Thank you, I will try your first example and will let you know.

The second example is not appropriate as pinned and watched are user-related.
