### ISSUE TITLE
$databaseName is invalid:

### ISSUE THREAD

**Issue by luzhuqun** [jenssegers/laravel-mongodb#958]
in`.env`
`DB_CONNECTION=mongodb`
`DB_HOST=192.168.10.8`
`DB_DATABASE=test`
`DB_USERNAME=`
`DB_PASSWORD=`
but
`InvalidArgumentException in Database.php line 66:`
`$databaseName is invalid:`
`at Connection->__construct(array('driver' => 'mongodb', 'host' => '192.168.10.8', 'port' => '27017', 'database' => null, 'username' => null, 'password' => null, 'options' => array('database' => 'test'))) in MongodbServiceProvider.php line 27`
why `'database' => null`?

**Comment by luzhuqun** [comment]
in `config/database.php`
`'database' => env('test'), `
I changed this to 
`'database' => 'test',`
Then it's okay. Why?

**Comment by ricardofontanelli** [comment]
I think the right way is:
-- config/database.php
'database' => env('DB_DATABASE', 'test'),

It means that if DB_DATABASE doesn't exist in your env, Laravel should use 'test'
