### ISSUE TITLE
Relation is not working with ObjectId as reference 

### ISSUE THREAD

**Issue by talukdar** [jenssegers/laravel-mongodb#96]
Collection One User:
 {
   "_id": ObjectId("52b6bd7ad6861b6101000003"),
   "name": "John Doe",
   "updated_at": ISODate("2013-12-22T10:22:50.180Z"),
   "created_at": ISODate("2013-12-22T10:22:50.180Z")
}   

Collection Two Role:
 {
   "_id": ObjectId("52b6bd7ad6861b6101000006"),
   "type": "sword",
   "user_id": ObjectId("52b6bd7ad6861b6101000003"),
   "updated_at": ISODate("2013-12-22T10:22:50.189Z"),
   "created_at": ISODate("2013-12-22T10:22:50.189Z")
}   

If user saved as string on Role collection then all relation is working fine. But its not working when reference id is saved as ObjectId. Is there any way to make it work?

**Comment by rohitkhatri** [comment]
Any workaround for this?

**Comment by Chintan7027** [comment]
For the application where data is produced by Nodejs or any other framework, it stores relationship as ObjectId('related model id'), 

In my case I am using database where Related model id are stored as MongoDb\BSON\ObjectID(). 

NON of Moloquent relationship working

**Comment by mehulpanchasara** [comment]
@talukdar here is your solution,
$userFiles = UserFile::whereIn('directory_id',$userDirectories->pluck('directory_id')->map(function($row){
    return new \MongoDB\BSON\ObjectID($row);
}))->get();
However you'll not be able to use any Eloquent/Moloquent Relationships in these type of case as described by @Chintan7027
