### ISSUE TITLE
Queues still not working

### ISSUE THREAD

**Issue by cherbert** [jenssegers/laravel-mongodb#960]
Setting Job Queues to use mongodb is still not working. I have followed your instructions and put mongodb in as the driver and including the relevant ServiceProvider but Laravel simply ignores it and continues to put jobs into the MySQL table.

Is this feature ever going to work or am I doing something wrong?

Using Laravel 5.3 and laravel-mongodb 3.2-dev

**Comment by ricardofontanelli** [comment]
Is your config/queue.php correctly configured?

**Comment by cherbert** [comment]
My config is configured as per the instructions.

`'connections' => [
    'database' => [
        'driver' => 'mongodb',
        'table'  => 'jobs',
        'queue'  => 'default',
        'expire' => 60,
    ],`

**Comment by sachinvrg** [comment]
I have the same issue when running **php artisan queue:work**  command , getting following error 
PHP Fatal error:  Call to a member function beginTransaction() on null in /var/www/html/push_admin/setupl/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 576

**Comment by JuCarr** [comment]
See here: https://github.com/jenssegers/laravel-mongodb/issues/854.
It works with laravel version < 5.2.32.

**Comment by sachinvrg** [comment]
@JuCarr  , thank you for your timely reply , my laravel version is 5.2.0 , I am not getting exactly what is solution in #854 , I have commented codes in beginTransaction() and commit() function and return null instead, error has gone after that but still queue is not working , when I run **php artisan queue:work** command , it prints nothing , neither it works.

**Comment by sachinvrg** [comment]
When I run php artisan queue:failed command , it says 
[PDOException]                                                               
  SQLSTATE[28000] [1045] Access denied for user 'forge'@'localhost' (using pa  
  ssword: NO)
I don't know in which file I have to change it , I have checked **.env** and **database.php** files.

**Comment by cherbert** [comment]
Why has this been closed? What is the solution?
