### ISSUE TITLE
query using mongodate not working in master branch

### ISSUE THREAD

**Issue by anchetaWern** [jenssegers/laravel-mongodb#961]
I'm previously using version 2.3 and the following query works for me:

``` php
'time_created' => [
          '$gte' => new \MongoDate(Carbon::parse('2016-01-02')->timestamp),
          '$lte' => new \MongoDate(Carbon::parse('2016-10-10')->timestamp)
        ]
```

But now that I switched to master branch, supplying the queries above results in no results being returned. I tried the following to format the raw date but it didn't work:
- Carbon's iso8601 date format
- Carbon's raw datetime object

any ideas? this is an aggregate query

**Comment by ricardofontanelli** [comment]
The master branch works with a new PHP mongoDB [driver](http://php.net/manual/pt_BR/set.mongodb.php) (MongoDB). Now all DateTime objects are converted to an MongoDB\BSON\UTCDateTime. You should run ```php -i | grep -i mongoDB ``` and see something like that:
MongoDB Support => enabled
MONGODB-CR => enabled
MONGODB-X509 => enabled

If you have the driver installed, change all MongoDate to DateTim or Carbon objects.

I opened an #953 to fix the automatic translation from DateTime to MongoDB\BSON\UTCDateTime when using whereBetween, you can use the test cases to see how it works!
