### ISSUE TITLE
Problems using $geoNear

### ISSUE THREAD

**Issue by guicunha** [jenssegers/laravel-mongodb#965]
i make a simple raw and don't understand where are the wrong

$proximos = Perfil::raw(function($collection)
{
return $collection->aggregate(
[
'$geoNear' => [
'near' => [
'coordinates' => [-19.927954,-43.938203]
],
'sphercial' => 'true'
]
]);
});

InvalidArgumentException in Aggregate.php line 93:
$pipeline is not a list (unexpected index: "$geoNear")

**Comment by guicunha** [comment]
`return $collection->aggregate([
               [
                '$geoNear' => [
                    'near' => [
                        'coordinates' => [-19.927954,-43.938203],
                        'type' => 'Point'
                    ],
                    'distanceField' => 'distancia.calculada',
                    'spherical' => true
                ]
            ]]);`

but return nohing in CLI returns 

> db.perfils.aggregate({
...             $geoNear: {
...                 near: {
...                     coordinates: [-19.927954,-43.938203],
...                     type: 'Point'
...                 },
...                 distanceField : "distancia",
...                 spherical: true
...             }
...         });
{ "_id" : ObjectId("57d086a7269f335d067af2df"), "contato" : { "cep" : "30150150" }, "localizacao" : { "coordinates" : [ -23.555141, -46.635746 ], "type" : "Point" }, "updated_at" : ISODate("2016-09-07T21:29:11.608Z"), "created_at" : ISODate("2016-09-07T21:29:11.608Z"), "distancia" : 413277.8945996578 }

**Comment by RafaelPlantard** [comment]
```
'property_name' => [
	'$nearSphere' => [
		'$geometry'    => [
			'type'        => 'Point',
			'coordinates' => [
				$latitude,
				$longitude
			]
		],
		'$maxDistance' => $rangeInKm * self::meters_per_km
	]
]
```
