### ISSUE TITLE
Reset Password problem

### ISSUE THREAD

**Issue by DimasL** [jenssegers/laravel-mongodb#966]
Hi,

"laravel/framework": "5.3.*",
"jenssegers/mongodb": "3.1.0-alpha"

1) php artisan make:auth
2) register user
3) logout
4) send email reset password link
5) try to reset password

[result](http://screencast.com/t/ZcPh7n0k)

Please help :)

**Comment by kudosagency** [comment]
I'm having the same issue with:
"laravel/framework": "5.3.*",
"jenssegers/mongodb": "^3.1.1",

**Comment by pi0** [comment]
@DimasL @kudosagency Please [See Here](https://github.com/jenssegers/laravel-mongodb#auth)

**Comment by kudosagency** [comment]
thanks pi0, worked a treat

**Comment by DimasL** [comment]
Thanks !
