### ISSUE TITLE
date whereBetween problem

### ISSUE THREAD

**Issue by sbarbosa115** [jenssegers/laravel-mongodb#974]
Hi,

When I try filter records by whereBetween, the filter not works. 

$df= new \DateTime();
$df->modify('-1 month');

$from = Carbon::instance($df);
$now = Carbon::now();
$interactions = Interaction::whereBetween('created_at', array($from, $now))->get();

The problem is that var $interactions is empty.

**Comment by pi0** [comment]
Your issue is related to #953 . This pull request is already merged to [Moloquent](https://github.com/moloquent/moloquent)  Branch. [Read More](https://moloquent.github.io)
