### ISSUE TITLE
How to change a field name / running a raw query?

### ISSUE THREAD

**Issue by royduin** [jenssegers/laravel-mongodb#976]
I'd like to run this from my application:
```
db.values.updateMany( { entity_id: 123 }, { $rename: { "oldname": "newname" } } )
```
I've tried multiple functions like `raw()` and a direct statement with `statement()` on the connection `\DB::connection('mongodb')` but everything is producing errors like `Call to a member function prepare() on null`.

How can I run this?

**Comment by pi0** [comment]
You may use something like this to rename

```php
        DB::connection('mongodb')->collection('values')->update([
            { entity_id: 123 },
            '$rename'=>['oldname'=> "newname"],
        ]);
```

See [here](https://docs.mongodb.com/manual/reference/method/db.collection.update/) for more details.

**Comment by royduin** [comment]
Thank you @pi0! The working result:
```
\DB::connection('mongodb')->collection('values')->where('entity_id',123)->update([
    '$rename' => ['oldname' => 'newname']
]);
```
