### ISSUE TITLE
return response()->json($data) _id no wokding

### ISSUE THREAD

**Issue by zhang-wenchao** [jenssegers/laravel-mongodb#977]
object(MongoDB\BSON\ObjectID)[80]
  public 'oid' => string '5714c60f08d087f5588b4834' (length=24)

return response()->json($data);

json: {}

no _id Field

**Comment by pi0** [comment]
try adding `_id` field to your model's `$visible` array

**Comment by SPRING-Z** [comment]
@pi0  I can not do that，_id am the restful api user key.

**Comment by kiwina** [comment]
maybe $this->makeVisible
