### ISSUE TITLE
Save Migration History in mongodb

### ISSUE THREAD

**Issue by Idnan** [jenssegers/laravel-mongodb#980]
How can i save the migration history in `mongodb`? As currently its being saved in mysql in `migrations` table.

**Comment by pi0** [comment]
@idnan Did you setup your default mongo connection ?  [Check here](https://github.com/jenssegers/laravel-mongodb#configuration)

**Comment by Idnan** [comment]
@pi0 yep i know about this one. But i have a different scenario. I have both migrations for mysql and mongodb. 
Now i want a model `MysqlMigration` and `MongoMigration` or something like this. 
So if the migration is extended from `MysqlMigration` then the migration history should save in `mysql`.
And if the migration is extended from `MongoMigration` then the migration history should save in `mongodb`.

**Comment by pi0** [comment]
If you see base Migration class (https://github.com/illuminate/database/blob/master/Migrations/Migration.php)

```php
<?php
namespace Illuminate\Database\Migrations;
abstract class Migration
{
    /**
     * The name of the database connection to use.
     *
     * @var string
     */
    protected $connection;
    /**
     * Get the migration connection name.
     *
     * @return string
     */
    public function getConnection()
    {
        return $this->connection;
    }
}
```

You can simply override and change `$connection` variable to either `default` or `mysql` for each individual migration :)

**Comment by Idnan** [comment]
I got it resolved by using the `--database` & `--path` on the artisan migrate command.
