### ISSUE TITLE
Mongodb UTCDateTime is not being saved as expected

### ISSUE THREAD

**Issue by tperrelli** [jenssegers/laravel-mongodb#981]
Hello. When i want to save and consider **only a date**, i do something like $myCarbonDate->startOfDate(). Then, i would get something like that "2016-10-10 00:00:00".

When the object is converted to UTCDateTime i don't get the result as the example above. Instead of this, i get something like "2016-10-10 11:57:00". But remember that i forced my carbon object to reset hour minutes and second.

The thing is that UTCDateTime is being created with the current hour minute and second. So when try to filter a query using only **date**, i never can get the row database. What would i do in this case? What i'm missing? Thanks

**Comment by pi0** [comment]
Two possible solutions : 
As you already mentioned you can use `startOfDate` method to set time part to 0, this can be done using methods like defining settter mutator on Model for that date fields. how ever i personally recommand a better approach, using `whereBetween` queries for non-exact dates, this way you can ensure your query always works correct! (consider situations you have databases with already some data without setting every minute and second to 0 or using )

**Comment by tperrelli** [comment]
I already use the startOfDate() function to ensure that my date will consider "00:00:00".

Your suggestions would be nice to creation date or timestamp stuff. I'm working with date flight. in a cached form fields. I need to fetch the same result when another user do  exactly the same query. So that i really need more precision. :(

**Comment by pi0** [comment]
I hope you can fix this using mutators :)

> When another user do exactly the same query, I need to fetch the same result.
Redis Cache Can be Also utilized if you have exactly one result for each query ...

@tperrelli is this is not really an issue or bug , would you please close it ?

**Comment by tperrelli** [comment]
Using redis will not solve my problem. Another insertion example:

If i insert something like: "2016-10-10 09:10:55" (Notice that this time i passed a date time), the **time** is completely ignored by UTCDateTime and it sets the **current time** by default.

In other words **09:10:55** is not being inserted in the databasem only current time.

**Comment by pi0** [comment]
Soooo this may be really interesting bug :D i'll try to reproduce same situation and stack trace it tonight :)

**Comment by tperrelli** [comment]
Did you get that?

**Comment by pi0** [comment]
Yes, I can confirm this bug.. we even have that issue in our production .. will try to resolve it ASAP dude

**Comment by tperrelli** [comment]
OK. Thanks buddy.
