### ISSUE TITLE
v3.1.0 Fatal error: Class 'Illuminate\Foundation\Application' not found 

### ISSUE THREAD

**Issue by enginkartal** [jenssegers/laravel-mongodb#983]
i'm using lumen 5.2 and laravel-mongodb v3.0.2. When i do composer update, laravel-mongodb updated to 3.1. Meanwhile i get these errors:

`Fatal error: Class 'Illuminate\Foundation\Application' not found in \vendor\jenssegers\mongodb\src\Jenssegers\Mongodb\Query\Builder.php on line 106`

**Comment by pi0** [comment]
This issue is known in PR #948 :) Hopefully it will be merged and resolved soon

**Comment by enginkartal** [comment]
thank's :) problem is solved 👍
