### ISSUE TITLE
detach(doesn't works)

### ISSUE THREAD

**Issue by kanav-kapoor** [jenssegers/laravel-mongodb#985]
I've a Many to Many relation. `Campaign` model has "Many To Many" relation with `Country` model

```
public function countriesDetail()
{
    return $this->belongsToMany('App\Country')->withTimestamps();
}
```

This works
`$campaign->countriesDetail()->sync([1, 2, 3]);`

This works
`$campaign->countriesDetail()->attach(1);`

This works:
`$campaign->countriesDetail()->detach(1);`

This doesn't works
`// remove all countries`
`$campaign->countriesDetail()->detach();`

**Comment by mostafamaklad** [comment]
Try this
```
$campaign->countriesDetail()->detach();
foreach($campaign->countriesDetail() as $countryDetail){
  $countryDetail->campaign()->detach($campaign)
}
```
