### ISSUE TITLE
Can't paginate raw query results

### ISSUE THREAD

**Issue by EdelBlau** [jenssegers/laravel-mongodb#987]
I have this raw query

$empresas = Empresa::raw()->find(array('$text'=>(array('$search'=>$s))),
                            array("score"=> array('$meta'=>"textScore"))
                );

And I want to paginate the results. When I try this:

$empresas = Empresa::raw()->find(array('$text'=>(array('$search'=>$s))),
                            array("score"=> array('$meta'=>"textScore"))
                );
 $empresas = $empresas->paginate(15);

It throws the following error

FatalErrorException in EmpresasController.php line 35: Call to undefined method MongoDB\Driver\Cursor::paginate()

Could you please tell me what I'm doing wrong? 

Thanks in advance

**Comment by pi0** [comment]
@EdelBlau why are you using `raw()` method ?? i think you have to use library query builder to use features like pagination .. `raw` method returns native `Cursor object`

**Comment by EdelBlau** [comment]
I want to use text search and that's the only way I have found.

**Comment by msankar1991** [comment]
I'm also using Raw queries only while using `lookup and text search` options. How we can apply pagination for `raw() query` result `cursor object`. Is any other option there for this problem
