### ISSUE TITLE
Union not working?

### ISSUE THREAD

**Issue by kunzelmanm** [jenssegers/laravel-mongodb#990]
Just trying to implement the simple example from the Query Builder docs:
$first = DB::table('users')
            ->whereNull('first_name');

$users = DB::table('users')
            ->whereNull('last_name')
            ->union($first)
            ->get();

```
    $first = DB::table('content')
    ->where('type' , '=', 'webcast');

    $second = DB::table('content')
        ->where('type', '=', 'video')
        ->union($first)
        ->get();
```

All I end up being returned is the results of the second query. Both queries individually return the expected data.

**Comment by jalbee** [comment]
I would like to know the answer to this as well if anybody cares to respond....

**Comment by inklingsofreality** [comment]
It's been several months on this. I would like to get results from several different collections that are not related. How might I do that? union should be the solution, but it's not working apparently.

**Comment by RemiCollin** [comment]
Same here. 

The only way I managed to make it work is not having the second query in the same fluent statement. 

Using the OP example : 

```php

 $first = DB::table('content')
    ->where('type' , '=', 'webcast');

 $second = DB::table('content')
      ->where('type', '=', 'video');

$results = DB::table('content')->union($first)->union($second)->get();

```

**Comment by RemiCollin** [comment]
+1, not working here. The union() statement are simply not compiled into the query.

**Comment by inklingsofreality** [comment]
It turns out that union was not what I needed anyways. To combine the two queries I ended up using merge, such as the following:
```
$cards = Card::all();
$stores = Retail::all();
$result = $cards->merge($stores);
return $result;
```
That chains the two together. I believe union would be if I needed to reference one from the other.
