### ISSUE TITLE
Call to a member function getDateFormat() on null

### ISSUE THREAD

**Issue by mohammad-69** [jenssegers/laravel-mongodb#991]
I've just installed laravel 5.3.16 And I've added `composer require jenssegers/mongodb` package to my project and configured it. then I've added `composer require laravel/passport` package to my project and I've followed this tutorial : 

> https://laravel.com/docs/5.3/passport 

steps to make passport package work but when i'm running : `php artisan passport:install` 
I get this error message : 
`PHP Fatal error:  Call to a member function getDateFormat() on null in /usr/local/ampps/www/test5_3/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 2992`

Any idea how to fix it ?

**Comment by SanderSander** [comment]
https://github.com/jenssegers/laravel-mongodb/issues/947 ;)

**Comment by uriel2707** [comment]
## For Laravel 5.3 
**Call to a member function getDateFormat() on nul**
	
In the file **vendor/laravel/framework/src/Illuminate/Foundation/Auth/User.php**

Replace `use Illuminate\Database\Eloquent\Model;` for this
`use Jenssegers\Mongodb\Eloquent\Model as Model;`

#### Its Works

**Comment by mohammad-69** [comment]
Thanks

**Comment by armashfankar** [comment]
Hello,
i am also getting same error and i tried above solution but its not working out for me.
Any other solution?
![screenshot from 2017-01-19 15 21 13](https://cloud.githubusercontent.com/assets/6822592/22101875/3bb64808-de5b-11e6-8c3e-8988ed6a0d64.png)

**Comment by armashfankar** [comment]
@mohammad-69 have you solved this? please let me know the solution.

**Comment by uriel2707** [comment]
###Error: Class Model Laravel no extens for Class Jenssegers Model


Search line `use Illuminate\Database\Eloquent\Model;` in the plugin passport path `/httpdocs/vendor/laravel/passport`

Replace Model line for this
`use Jenssegers\Mongodb\Eloquent\Model as Model;`


```
httpdocs/vendor/laravel/passport/src/AuthCode.php
httpdocs/vendor/laravel/passport/src/Client.php
httpdocs/vendor/laravel/passport/src/Http/Controllers/AuthorizationController.php
httpdocs/vendor/laravel/passport/src/Http/Controllers/ClientController.php
httpdocs/vendor/laravel/passport/src/Http/Controllers/RetrievesAuthRequestFromSession.php
httpdocs/vendor/laravel/passport/src/PersonalAccessClient.php
httpdocs/vendor/laravel/passport/src/Token.php
httpdocs/vendor/laravel/passport/src/TokenRepository.php
```

Repeat in Contact User Model 
In the file **vendor/laravel/framework/src/Illuminate/Foundation/Auth/User.php**

Replace `use Illuminate\Database\Eloquent\Model;` for this
`use Jenssegers\Mongodb\Eloquent\Model as Model;`

Go to console enter

`php artisan passport:install`

![imagen](https://cloud.githubusercontent.com/assets/89768/22119999/53996d1e-de43-11e6-917d-7a61c6d439a9.png)

@mohammad-69 @armashfankar @SanderSander

**Comment by CHOMNANP** [comment]
@uriel2707 thank you.
Your solution work for my case. Noted.
We also need to apply "use CrudTrait;" in each model as well.

**Comment by rajkuttie** [comment]
Check your code for Correct Order
```
<?php
namespace App;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;


```

**Comment by erkanarslan** [comment]
@uriel2707 Thanks, your solution works.

However, editing gitignored files is not a correct solution. Every time someone clones the project or pulls this change, he will need to manually edit files. This is a temporary solution, a correct solution should be implemented into laravel-mongodb repository.

**Comment by w33ladalah** [comment]
I have working solution but maybe not the best solution. 
I have modified file _/app/User.php_ file.
`<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

use Jenssegers\Mongodb\Eloquent\Model as Model;

class UserAuthenticatable extends Model implements
    AuthenticatableContract,
    AuthorizableContract,
    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;
}


class User extends UserAuthenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}
`
Hope this will help :)

**Comment by baobazbarley** [comment]
hello

i've the same problem and this is working for me.

on app/User.php
change this
`use Illuminate\Foundation\Auth\User as Authenticatable;`
to
`use Jenssegers\Mongodb\Auth\User as Authenticatable;`

**Comment by uriel2707** [comment]
## other solution
**Call to a member function getDateFormat() on null**
	
After installation laravel-mongodb run command for composer 
`php artisan clear-compiled` and `composer dump-autoload` => for composer global installation

#### Its Works

**Comment by DMNSteve** [comment]
This is fixed with https://github.com/jenssegers/laravel-mongodb/pull/1333
