### ISSUE TITLE
Call to a member function compileInsertGetId() on a non-object

### ISSUE THREAD

**Issue by CihanAksoy** [jenssegers/laravel-mongodb#994]
```
$dbInsert = new TickTack_Email();
$dbInsert->email = $request->input('newEmail');
$dbInsert->save();
```

Call to a member function compileInsertGetId() on a non-object

**Comment by pi0** [comment]
Would you please provide `TickTack_Email` implementation ?

**Comment by CihanAksoy** [comment]
What do you mean ?

**Comment by pi0** [comment]
I mean Source Code of `TickTack_Email.php` File :)

**Comment by CihanAksoy** [comment]
Edited :)

**Comment by pi0** [comment]
Looks strange, would you please also provide error's stack trace? (i mean full error output from browser) or this file : `storage/logs/app.log`

**Comment by CihanAksoy** [comment]
storage/logs/ is empty

**Comment by CihanAksoy** [comment]
Solved. 

Change

`use Illuminate\Database\Eloquent\Model;`
to
`use Jenssegers\Mongodb\Eloquent\Model;`
