### ISSUE TITLE
Near 'dis' is not in returned obj

### ISSUE THREAD

**Issue by ebychu** [jenssegers/laravel-mongodb#996]
`$result = \MongodbUser::WhereRaw(
            [
                'coordinates' => [
                    '$near' => [
                        'type' => 'Point',
                        'coordinates' => [116, 24.491]
                    ],
                    '$spherical' => true,
                    '$maxDistance' => 100
                ],
            ])
           ->get();`
The distance returned by the latitude , longitude query can not be found, I want   like this (feild dis):
`stdClass Object
    (
        [waitedMS] => 0
        [results] => Array
            (
                [0] => stdClass Object
                    (
                        [dis] => 111.31884502173
                        [obj] => stdClass Object
                            (
                                [_id] => MongoDB\BSON\ObjectID Object
                                    (
                                        [oid] => 5806000a0a674a0930001561
                                    )
                                [user_id] => 1
                                [identifier] => 1000878
                                [user_code] => 1000878
                            ）
                    ）
            ）
    ）
`

**Comment by WenXuanYuan** [comment]
``
db.places.find(
...    {
...      location:
...        { $near :
...           {
...             $geometry: { type: "Point",  coordinates: [ -73.9667, 40.78 ] },
...             $minDistance: 1000,
...             $maxDistance: 5000
...           }
...        }
...    }
... )
``

**Comment by ebychu** [comment]
@WenXuanYuan  Thanks,  but I use the ORM query in the collection is not dis fields, I want to use the ORM query to get the distance,, 
```
\MongodbUser::WhereRaw( 
 [ 'coordinates' =>
 [ '$near' =>
 [ 'type' => 'Point', 'coordinates' => [116, 24.491] ],
 '$spherical' => true, '$maxDistance' => 100 ],
 ])->get()
```
