### ISSUE TITLE
OrderBy not working correctly

### ISSUE THREAD

**Issue by ashiqmc** [jenssegers/laravel-mongodb#997]
Product::orderBy('product_name','ASC')->get(array('name'));

In the above query result is first order by uppercase then lowercase.Please help 
[{"_id":"57bfd45eb771c80744007d43","name":"Aquila"},{"_id":"58061c35b771c803340040e1","name":"Dell"},
{"_id":"58061caeb771c803340040e2","name":"aquila"},{"_id":"57bfd478b771c80744007d44","name":"focuz"},
{"_id":"57bfd48cb771c80744007d45","name":"test"}]

**Comment by srabouin** [comment]
Looks like this is a mongo issue, see https://jira.mongodb.org/browse/SERVER-90

**Comment by hendra1** [comment]
I have same problem too..
the orderBy doesnt work well with create_at column

**Comment by azhard4int** [comment]
@hendra1 , try using the created_at.date instead of the direct created_at column.

Had the same problem in past, but using the created_at.date as DESC worked.

**Comment by VirendraArekar** [comment]
OrderBy not working for me please help me.
HotelReview::orderBy('created_at','desc')->get()
