### ISSUE TITLE
created_at not added when records are created using update/upsert

### ISSUE THREAD

**Issue by srabouin** [jenssegers/laravel-mongodb#998]
I think this option should be set by default:
https://docs.mongodb.com/manual/reference/operator/update/setOnInsert/#up._S_setOnInsert

`Profile::whereId(1)->update(['name' => 'joe'],['upsert' => true]);`

This produces the updated_at but is missing created_at.

**Comment by judhizputra** [comment]
+1

**Comment by quando12** [comment]
Why issue is close?

**Comment by Smolevich** [comment]
@quando12 i'm not sure that it's expected behavior

**Comment by erickneverson** [comment]
What is the alternative here, use create() if you cannot first find()?  upsert (by definition) would create a new document if one could not be found.  This (in my opinion) should cause the `created_at` field to be included automatically.

**Comment by gottaloveit** [comment]
+1
